CODE-U-S/Coding_Test_Study

2st/Riyeon/모음 사전.java
| 모음 사전 | 프로그래머스 | Level.2 |
<hr/>
- 모음 사전 : 사전에 알파벳 모음 'A', 'E', 'I', 'O', 'U'만을 사용하여 만들 수 있는, 길이 5 이하의 모든 단어가 수록되어 있습니다. 사전에서 첫 번째 단어는 "A"이고, 그다음은 "AA"이며, 마지막 단어는 "UUUUU"입니다. 단어 하나 word가 매개변수로 주어질 때, 이 단어가 사전에서 몇 번째 단어인지 return 하도록 solution 함수를 완성해주세요.
=> [96일차] 김리연 / 모음 사전

3st/Jaeyoung/글자 이어 붙여 문자열 만들기.js
https://school.programmers.co.kr/learn/courses/30/lessons/181915
| 글자 이어 붙여 문자열 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 글자 이어 붙여 문자열 만들기 : 문자열 my_string과 정수 배열 index_list가 매개변수로 주어집니다. my_string의 index_list의 원소들에 해당하는 인덱스의 글자들을 순서대로 이어 붙인 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [2일차] 박재영 / 글자 이어 붙여 문자열 만들기

2st/Riyeon/문자열 내 p와 y의 개수.py
| 문자열 내 p와 y의 개수 | 프로그래머스 | Level.1 |
<hr/>
- 문자열 내 p와 y의 개수 : 대문자와 소문자가 섞여있는 문자열 s가 주어집니다. s에 'p'의 개수와 'y'의 개수를 비교해 같으면 True, 다르면 False를 return 하는 solution를 완성하세요. 'p', 'y' 모두 하나도 없는 경우는 항상 True를 리턴합니다. 단, 개수를 비교할 때 대문자와 소문자는 구별하지 않습니다. 예를 들어 s가 "pPoooyY"면 true를 return하고 "Pyy"라면 false를 return합니다.
=> [97일차] 김리연 / 문자열 내 p와 y의 개수

3st/Jaehee/홀짝 구분하기.java
| 제목 | 프로그래머스 | Level.0 |
<hr/>
- 홀짝 구분하기
: 자연수 n이 입력으로 주어졌을 때 만약 n이 짝수이면 "n is even"을, 홀수이면 "n is odd"를 출력하는 코드를 작성해 보세요.
=> [2일차] 이제희 / 홀짝 구분하기

3st/Juhee/직사각형 넓이 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120860
| 직사각형 넓이 구하기 | 프로그래머스 | Level.0 |
<hr/>
- 직사각형 넓이 구하기 : 2차원 좌표 평면에 변이 축과 평행한 직사각형이 있습니다. 직사각형 네 꼭짓점의 좌표 [[x1, y1], [x2, y2], [x3, y3], [x4, y4]]가 담겨있는 배열 dots가 매개변수로 주어질 때, 직사각형의 넓이를 return 하도록 solution 함수를 완성해보세요.
=> [2일차] 최주희 / 직사각형 넓이 구하기

3st/Jaeyoung/올바른 괄호.js
https://school.programmers.co.kr/learn/courses/30/lessons/12909
| 올바른 괄호 | 프로그래머스 | Level.2 |
<hr/>
- 올바른 괄호 : 괄호가 바르게 짝지어졌다는 것은 '(' 문자로 열렸으면 반드시 짝지어서 ')' 문자로 닫혀야 한다는 뜻입니다. 예를 들어
"()()" 또는 "(())()" 는 올바른 괄호입니다.
")()(" 또는 "(()(" 는 올바르지 않은 괄호입니다.
'(' 또는 ')' 로만 이루어진 문자열 s가 주어졌을 때, 문자열 s가 올바른 괄호이면 true를 return 하고, 올바르지 않은 괄호이면 false를 return 하는 solution 함수를 완성해 주세요.
=> [3일차] 박재영 / 올바른 괄호

3st/Seojun/홀수 vs 짝수{.java
https://school.programmers.co.kr/learn/courses/30/lessons/181887
| 홀수 vs 짝수 | 프로그래머스 | Level.0 |
<hr/>
=> [3일차] 김서준 / 홀수 vs 짝수

3st/Jaehee/문자열 돌리기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181945
| 문자열 돌리기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 돌리 : 문자열 str이 주어집니다.
=> [3일차] 이제희/문자열 돌리기

3st/Juhee/제곱수 판별하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120909
| 제곱수 판별하기 | 프로그래머스 | Level.0 |
<hr/>
- 제곱수 판별하기 : 어떤 자연수를 제곱했을 때 나오는 정수를 제곱수라고 합니다. 정수 n이 매개변수로 주어질 때, n이 제곱수라면 1을 아니라면 2를 return하도록 solution 함수를 완성해주세요.
=> [3일차] 최주희 / 제곱수 판별하기

2st/Yeonwoo/그림 확대.py
| 그림 확대 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181836)|
<hr/>
- 그림 확 : 직사각형 형태의 그림 파일이 있고, 이 그림 파일은 1 × 1 크기의 정사각형 크기의 픽셀로 이루어져 있습니다. 이 그림 파일을 나타낸 문자열 배열 picture과 정수 k가 매개변수로 주어질 때, 이 그림 파일을 가로 세로로 k배 늘린 그림 파일을 나타내도록 문자열 배열을 return 하는 solution 함수를 작성해 주세요.
=> [98일차] 채연우 / 그림 확대

2st/Riyeon/문자열을 정수로 바꾸기.py
| 문자열을 정수로 바꾸기 | 프로그래머스 | Level.1 |
<hr/>
- 문자열을 정수로 바꾸기 : 문자열 s를 숫자로 변환한 결과를 반환하는 함수, solution을 완성하세요.
=> [98일차] 김리연 / 문자열을 정수로 바꾸기

3st/Juhee/중앙값 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120811
<hr/>
=> [4일차] 최주희 / 중앙값 구하기

3st/Jaeyoung/다음 큰 숫자.js
https://school.programmers.co.kr/learn/courses/30/lessons/12911
| 다음 큰 숫자 | 프로그래머스 | Level.2 |
<hr/>
- 다음 큰 숫자 : 자연수 n이 주어졌을 때, n의 다음 큰 숫자는 다음과 같이 정의 합니다.
조건 1. n의 다음 큰 숫자는 n보다 큰 자연수 입니다.
조건 2. n의 다음 큰 숫자와 n은 2진수로 변환했을 때 1의 갯수가 같습니다.
조건 3. n의 다음 큰 숫자는 조건 1, 2를 만족하는 수 중 가장 작은 수 입니다.
예를 들어서 78(1001110)의 다음 큰 숫자는 83(1010011)입니다.
자연수 n이 매개변수로 주어질 때, n의 다음 큰 숫자를 return 하는 solution 함수를 완성해주세요.
=> [4일차] 박재영 / 다음 큰 숫자

3st/Jaehee/저축.java
https://school.programmers.co.kr/learn/courses/30/lessons/250130
| 저축 | 프로그래머스 |  Level.0 |
<hr/>
- 저축 : 진우는 돈을 모으기 위해 저축을 하려고 합니다. 목표로 하는 금액은 100만 원이며, 첫 달에 일정 금액을 넣은 뒤 70만 원까지는 매월 조금씩 저축하다가 70만 원 이후부터는 월 저축량을 늘려 빠르게 목표 금액을 달성하고자 합니다.
첫 달에 저축하는 금액을 나타내는 정수 start, 두 번째 달 부터 70만 원 이상 모일 때까지 매월 저축하는 금액을 나타내는 정수 before, 100만 원 이상 모일 때 까지 매월 저축하는 금액을 나타내는 정수 after가 주어질 때, 100만 원 이상을 모을 때까지 걸리는 개월 수를 출력하도록 빈칸을 채워 코드를 완성해 주세요.
=> [4일차] 이제희 / 저축

3st/Seojun/두 수의 곱.java, 3st/Seojun/두 수의 나눗셈.java, 3st/Seojun/숫자 비교하기.java, 3st/Seojun/홀수 vs 짝수{.java
| 숫자 비교하기 |  프로그래머스 |  Level.0 |
| 두 수의 나눗셈 |  프로그래머스 |  Level.0 |
<hr/>
- 두 수의 나눗셈 : 정수 num1과 num2가 매개변수로 주어질 때, num1을 num2로 나눈 값에 1,000을 곱한 후 정수 부분을 return 하도록 soltuion 함수를 완성해주세요.
=> [4일차] 김서준 / 숫자 비교하기/외1개

2st/Yeonwoo/숫자의 합.py
| 숫자의 합 | 백준 | [브론즈 IV ](https://www.acmicpc.net/submit/11720/83375066)|
<hr/>
- 숫자의 합 : N개의 숫자가 공백 없이 쓰여있다. 이 숫자를 모두 합해서 출력하는 프로그램을 작성하시오.
=> [99일차] 채연우 /  숫자의 합

2st/Yeonwoo/단어 길이 재기.py
| 단어 길이 재기 | 백준 | [브론즈 V](https://www.acmicpc.net/submit/2743/83375342) |
<hr/>
- 단어 길이 재기 : 알파벳으로만 이루어진 단어를 입력받아, 그 길이를 출력하는 프로그램을 작성하시오.
=> [100일차] 채연우 / 단어 길이 재기

2st/Riyeon/정수 내림차순으로 배치하기.py
| 정수 내림차순으로 배치하기 | 프로그래머스 | Level.1 |
<hr/>
- 정수 내림차순으로 배치하기 : 함수 solution은 정수 n을 매개변수로 입력받습니다. n의 각 자릿수를 큰것부터 작은 순으로 정렬한 새로운 정수를 리턴해주세요. 예를들어 n이 118372면 873211을 리턴하면 됩니다.
=> [100일차] 김리연 / 정수 내림차순으로 배치하기

3st/Juhee/7의 개수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120912
| 7의 개수 | 프로그래머스 | Level.0 |
<hr/>
- 7의 개수 : 머쓱이는 행운의 숫자 7을 가장 좋아합니다. 정수 배열 array가 매개변수로 주어질 때, 7이 총 몇 개 있는지 return 하도록 solution 함수를 완성해보세요.
=> [5일차] 최주희 / 7의 개수

3st/Jaeyoung/구구단.cs
https://www.acmicpc.net/problem/2739
| 구구단 | 백준 | 브론즈 5 |
<hr/>
=> [5일차] 박재영 / 구구단

3st/Seojun/나머지 구하기.java
| 나머지 구하기  프로그래머스 |  Level.0 |
<hr/>
=> [5일차] 김서준 / 나머지 구하

3st/Jaeyoung/짝수는 싫어요.java
https://school.programmers.co.kr/learn/courses/30/lessons/120813
| 짝수는 싫어요 | 프로그래머스 | Level.0 |
<hr/>
=> [6일차] 박재영 / 짝수는 싫어요

3st/Seojun/문자열 붙여서 출력하기.java
=> [6일차] 김서준 / 문자열 붙여서 출력하기

3st/Jaehee/a와 b 출력하기.java, 3st/Jaehee/특수문자 출력하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181948
| 특수문자 출력하기 | 프로그래머스 | Level.0 |
<hr/>
- 특수문자 출력하 : 다음과 같이 출력하도록 코드를 작성해 주세요. !@#$%^&*(\'"<>?:;
=> [PGS] 이제희/특수문자 출력하기

2st/Riyeon/정수 제곱근 판별.py
| 정수 제곱근 판별 | 프로그래머스 | Level.1 |
<hr/>
- 정수 제곱근 판별 : 임의의 양의 정수 n에 대해, n이 어떤 양의 정수 x의 제곱인지 아닌지 판단하려 합니다.
n이 양의 정수 x의 제곱이라면 x+1의 제곱을 리턴하고, n이 양의 정수 x의 제곱이 아니라면 -1을 리턴하는 함수를 완성하세요.
=> [101일차] 김리연 / 정수 제곱근 판별

2st/Yeonwoo/단어의 개수.py
| 단어의 개수 | 백준 | [브론즈 ||](https://www.acmicpc.net/submit/1152/83490572) |
<hr/>
- 단어의 개수 : 영어 대소문자와 공백으로 이루어진 문자열이 주어진다. 이 문자열에는 몇 개의 단어가 있을까? 이를 구하는 프로그램을 작성하시오. 단, 한 단어가 여러 번 등장하면 등장한 횟수만큼 모두 세어야 한다.
=> [101일차] 채연우 / 단어의 개수

3st/Jaeyoung/정수 제곱근 판별.js
https://school.programmers.co.kr/learn/courses/30/lessons/12934
| 정수 제곱근 판별 | 프로그래머스 | Level.1 |
<hr/>
- 정수 제곱근 판별 : 임의의 양의 정수 n에 대해, n이 어떤 양의 정수 x의 제곱인지 아닌지 판단하려 합니다.
n이 양의 정수 x의 제곱이라면 x+1의 제곱을 리턴하고, n이 양의 정수 x의 제곱이 아니라면 -1을 리턴하는 함수를 완성하세요.
=> [7일차] 박재영 / 정수 제곱근 판별

3st/Seojun/문자열 출력하기.java
| 문자열 출력하기 | 프로그래머스 |  Level.0 |
<hr/>
- 문자열 출력하기 : 문자열 str이 주어질 때, str을 출력하는 코드를 작성해 보세요.
=> [7일차] 김서준 / 문자열 출력하기

3st/Jaehee/피타고라스의 정리.Scanner;
https://school.programmers.co.kr/learn/courses/30/lessons/250132
| 피타고라스의 정리| 프로그래머스 | Level.0 |
<hr/>
- 피타고라스의 정리: 직각삼각형이 주어졌을 때 빗변의 제곱은 다른 두 변을 각각 제곱한 것의 합과 같습니다.
직각삼각형의 한 변의 길이를 나타내는 정수 a와 빗변의 길이를 나타내는 정수 c가 주어질 때, 다른 한 변의 길이의 제곱, b_square 을 출력하도록 한 줄을 수정해 코드를 완성해 주세요.
=> [7일차] 이제희/피타고라스의 정리

2st/Riyeon/하샤드 수.py
| 하샤드 수 | 프로그래머스 | Level.1 |
<hr/>
- 하샤드 수 : 양의 정수 x가 하샤드 수이려면 x의 자릿수의 합으로 x가 나누어져야 합니다. 예를 들어 18의 자릿수 합은 1+8=9이고, 18은 9로 나누어 떨어지므로 18은 하샤드 수입니다. 자연수 x를 입력받아 x가 하샤드 수인지 아닌지 검사하는 함수, solution을 완성해주세요.
=> [102일차] 김리연 / 하샤드 수

2st/Yeonwoo/상수.py
| 상수 | 백준 | [브론즈 ||](https://www.acmicpc.net/submit/2908/83546409)|
<hr/>
- 상수 : 상근이의 동생 상수는 수학을 정말 못한다. 상수는 숫자를 읽는데 문제가 있다. 이렇게 수학을 못하는 상수를 위해서 상근이는 수의 크기를 비교하는 문제를 내주었다. 상근이는 세 자리 수 두 개를 칠판에 써주었다. 그 다음에 크기가 큰 수를 말해보라고 했다.
상수는 수를 다른 사람과 다르게 거꾸로 읽는다. 예를 들어, 734와 893을 칠판에 적었다면, 상수는 이 수를 437과 398로 읽는다. 따라서, 상수는 두 수중 큰 수인 437을 큰 수라고 말할 것이다.
두 수가 주어졌을 때, 상수의 대답을 출력하는 프로그램을 작성하시오.
=> [102일차] 채연우 / 상수

3st/Juhee/주사위 게임 2.java
https://school.programmers.co.kr/learn/courses/30/lessons/181930
| 주사위 게임 2 | 프로그래머스 | Level.0 |
<hr/>
- 주사위 게임 2 : 1부터 6까지 숫자가 적힌 주사위가 세 개 있습니다. 세 주사위를 굴렸을 때 나온 숫자를 각각 a, b, c라고 했을 때 얻는 점수는 다음과 같습니다.
세 숫자가 모두 다르다면 a + b + c 점을 얻습니다.
세 숫자 중 어느 두 숫자는 같고 나머지 다른 숫자는 다르다면 (a + b + c) × (a2 + b2 + c2 )점을 얻습니다.
세 숫자가 모두 같다면 (a + b + c) × (a2 + b2 + c2 ) × (a3 + b3 + c3 )점을 얻습니다.
세 정수 a, b, c가 매개변수로 주어질 때, 얻는 점수를 return 하는 solution 함수를 작성해 주세요.
=> [7일차] 최주희 / 주사위 게임 2

3st/Jaeyoung/특정 문자 제거하기.js
https://school.programmers.co.kr/learn/courses/30/lessons/120826
<hr/>
=> [8일차] 박재영 / 특정 문자 제거하기

3st/Seojun/각도기.java
| 각도기 |  프로그래머스 |  Level.0 |
<hr/>
예각 : 0 < angle < 90
직각 : angle = 90
둔각 : 90 < angle < 180
평각 : angle = 180
=> [8일]  김서준 / 각도기

2st/Yeonwoo/문자와 문자열.py
| 문자와 문자열 | 백준 | [브론즈 V](https://www.acmicpc.net/submit/27866/83546059) |
<hr/>
- 문자와 문자열 : 단어 S와 정수 i가 주어졌을 때, S의 i번째 글자를 출력하는 프로그램을 작성하시오.
=> [103일차] 채연우 / 문자와 문자열

2st/Riyeon/두 정수 사이의 합.py
| 두 정수 사이의 합 | 프로그래머스 | Level.1 |
<hr/>
- 두 정수 사이의 합 : 두 정수 a, b가 주어졌을 때 a와 b 사이에 속한 모든 정수의 합을 리턴하는 함수, solution을 완성하세요. 예를 들어 a = 3, b = 5인 경우, 3 + 4 + 5 = 12이므로 12를 리턴합니다.
=> [103일차] 김리연 / 두 정수 사이의 합

3st/Juhee/수 조작하기 1.java
https://school.programmers.co.kr/learn/courses/30/lessons/181926
<hr/>
- 수 조작하기 1 : 정수 n과 문자열 control이 주어집니다. control은 "w", "a", "s", "d"의 4개의 문자로 이루어져 있으며, control의 앞에서부터 순서대로 문자에 따라 n의 값을 바꿉니다.
"w" : n이 1 커집니다.
"s" : n이 1 작아집니다.
"d" : n이 10 커집니다.
"a" : n이 10 작아집니다.
위 규칙에 따라 n을 바꿨을 때 가장 마지막에 나오는 n의 값을 return 하는 solution 함수를 완성해 주세요.
=> [8일차] 최주희 / 수 조작하기 1

3st/Juhee/수 조작하기 2.java
https://school.programmers.co.kr/learn/courses/30/lessons/181925
| 수 조작하기 2 | 프로그래머스 | Level.0 |
<hr/>
- 수 조작하기 2 : 정수 배열 numLog가 주어집니다. 처음에 numLog[0]에서 부터 시작해 "w", "a", "s", "d"로 이루어진 문자열을 입력으로 받아 순서대로 다음과 같은 조작을 했다고 합시다.
"w" : 수에 1을 더한다.
"s" : 수에 1을 뺀다.
"d" : 수에 10을 더한다.
"a" : 수에 10을 뺀다.
그리고 매번 조작을 할 때마다 결괏값을 기록한 정수 배열이 numLog입니다. 즉, numLog[i]는 numLog[0]로부터 총 i번의 조작을 가한 결과가 저장되어 있습니다.
주어진 정수 배열 numLog에 대해 조작을 위해 입력받은 문자열을 return 하는 solution 함수를 완성해 주세요.
=> [9일차] 최주희 / 수 조작하기 2

3st/Seojun/아이스 아메리카노.java
| 아이스 아메리카노 | 프로그래머스 |  Level.0 |
<hr/>
=> [9일차] 김서준 / 아이스 아메리카노

3st/Jaeyoung/아이스 아메리카노.java
https://school.programmers.co.kr/learn/courses/30/lessons/120819
<hr/>
=> [9일차] 박재영 / 아이스 아메리카노

3st/Jaehee/문자열 붙여서 출력하기.java
<hr/>
- 문자열 붙여서 출력하기
문자열 붙여서 출력하기 : 두 개의 문자열 str1, str2가 공백으로 구분되어 입력으로 주어집니다.
=> [9일차] 이제희/문자열 붙여서 출력하기

2st/Riyeon/나머지가 1이 되는 수 찾기.py
| 나머지가 1이 되는 수 찾기 | 프로그래머스 | Level.1 |
<hr/>
- 나머지가 1이 되는 수 찾기 : 자연수 n이 매개변수로 주어집니다. n을 x로 나눈 나머지가 1이 되도록 하는 가장 작은 자연수 x를 return 하도록 solution 함수를 완성해주세요. 답이 항상 존재함은 증명될 수 있습니다.
=> [104일차] 김리연 / 나머지가 1이 되는 수 찾기

3st/Juhee/문자 리스트를 문자열로 변환하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181941?language=java
<hr/>
=> [10일차] 최주희 / 문자 리스트를 문자열로 변환하기

3st/Jaeyoung/첫 번째로 나오는 음수.java
https://school.programmers.co.kr/learn/courses/30/lessons/181896
<hr/>
=> [10일차] 박재영 / 첫 번째로 나오는 음수

3st/Seojun/짝수의 합.java
https://school.programmers.co.kr/learn/courses/30/lessons/120831
| 짝수의 합 | 프로그래머스 |  Level.0 |
<hr/>
- 짝수의 합 : 정수 n이 주어질 때, n이하의 짝수를 모두 더한 값을 return 하도록 solution 함수를 작성해주세요.
=> [9일차] 김서준 / 짝수의 합

3st/Jaehee/문자열 출력하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181952
| 문자열 출력하기| 프로그래머스 | Level.0|
<hr/>
- 문자열 출력하기: 문자열 str이 주어질 때, str을 출력하는 코드를 작성해 보세요.
제한사항
1 ≤ str의 길이 ≤ 1,000,000
str에는 공백이 없으며, 첫째 줄에 한 줄로만 주어집니다.
=> [10일] 이제희/문자열 출력하기

2st/Riyeon/평균 구하기.py
| 평균 구하기 | 프로그래머스 | Level.1 |
<hr/>
=> [105일차] 김리연 / 평균 구하기

2st/Yeonwoo/A+B-4.py
| A+B-4 | 백준 | [브론즈 V](https://www.acmicpc.net/submit/10951/83618121) |
<hr/>
- A+B-4 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [105일차] 채연우 / A+B-4

2st/Yeonwoo/A+B-5.py
| A+B-5 | 백준 | [브론즈 V](https://www.acmicpc.net/submit/10952/83618427) |
<hr/>
- A+B-5 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [106일차] 채연우 / A+B-5

3st/Juhee/문자열 섞기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181942
| 문자열 섞기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 섞기 : 길이가 같은 두 문자열 str1과 str2가 주어집니다.
두 문자열의 각 문자가 앞에서부터 서로 번갈아가면서 한 번씩 등장하는 문자열을 만들어 return 하는 solution 함수를 완성해 주세요.
=> [11일차] 최주희 / 문자열 섞기

3st/Seojun/배열의 평균값.java
| 배열의 평균 값 | 프로그래머스 | Level.0 |
<hr/>
- 배열의 평균 값 : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소의 평균값을 return하도록 solution 함수를 완성해주세요.
=> [11일차] 김서준 / 배열의 평균 값

3st/Jaehee/나이계산.java
https://school.programmers.co.kr/learn/courses/30/lessons/250131
| 나이 계산| 프로그래머스 | Level.0 |
<hr/>
- 나이 계산: 나이를 세는 방법은 여러 가지가 있습니다. 그중 한국식 나이는 태어난 순간 1살이 되며 해가 바뀔 때마다 1살씩 더 먹게 됩니다. 연 나이는 태어난 순간 0살이며 해가 바뀔 때마다 1살씩 더 먹게 됩니다. 각각 나이의 계산법은 다음과 같습니다.
한국식 나이 : 현재 연도 - 출생 연도 + 1
연 나이 : 현재 연도 - 출생 연도
출생 연도를 나타내는 정수 year와 구하려는 나이의 종류를 나타내는 문자열 age_type이 주어질 때 2030년에 몇 살인지 출력하도록 빈칸을 채워 코드를 완성해 주세요. age_type이 "Korea"라면 한국식 나이를, "Year"라면 연 나이를 출력합니다.
=> [PGS] 나이계산/Lv.0

3st/Seojun/중복된 숫자 개수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120583
<hr/>
=> [12일차] 김서준 / 중복된 숫자 개수

3st/Jaehee/두 수의 차.java
https://school.programmers.co.kr/learn/courses/30/lessons/120803
| 두 수의 차 | 프로그래머스 | Level.0|
<hr/>
- 두 수의 차 : 정수 num1과 num2가 주어질 때, num1에서 num2를 뺀 값을 return하도록 soltuion 함수를 완성해주세요.
=> [11일] 이제희/두 수의 차

3st/Juhee/문자열 곱하기.java
=> [12일차] 최주희 / 문자열 곱하기

2st/Yeonwoo/A+B - 7.py, 2st/Yeonwoo/A+B-8.py
| A+B-8 | 백준 | [브론즈 V](https://www.acmicpc.net/problem/11022) |
<hr/>
- A+B-8 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [107일차] 채연우 / A+B-8

2st/Riyeon/콜라츠 추측.py
| 콜라츠 추측 | 프로그래머스 | Level.1 |
<hr/>
- 콜라츠 추측 : 1937년 Collatz란 사람에 의해 제기된 이 추측은, 주어진 수가 1이 될 때까지 다음 작업을 반복하면, 모든 수를 1로 만들 수 있다는 추측입니다. 작업은 다음과 같습니다.
1-1. 입력된 수가 짝수라면 2로 나눕니다. 
1-2. 입력된 수가 홀수라면 3을 곱하고 1을 더합니다. 
2. 결과로 나온 수에 같은 작업을 1이 될 때까지 반복합니다. 
예를 들어, 주어진 수가 6이라면 6 → 3 → 10 → 5 → 16 → 8 → 4 → 2 → 1 이 되어 총 8번 만에 1이 됩니다. 위 작업을 몇 번이나 반복해야 하는지 반환하는 함수, solution을 완성해 주세요. 단, 주어진 수가 1인 경우에는 0을, 작업을 500번 반복할 때까지 1이 되지 않는다면 –1을 반환해 주세요.
=> [107일차] 김리연 / 콜라츠 추측

3st/Juhee/flag에 따라 다른 값 반환하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181933
<hr/>
=> [13일차] 최주희 / flag에 따라 다른 값 반환하기

3st/Seojun/머쓱이보다 키 큰 사람.java
| 머쓱이보다 키 큰 사람 | 프로그래머스 |  Level.0 |
<hr/>
- 머쓱이보다 키 큰 사람 : 머쓱이는 학교에서 키 순으로 줄을 설 때 몇 번째로 서야 하는지 궁금해졌습니다. 머쓱이네 반 친구들의 키가 담긴 정수 배열 array와 머쓱이의 키 height가 매개변수로 주어질 때, 머쓱이보다 키 큰 사람 수를 return 하도록 solution 함수를 완성해보세요.
=> [13일차] 김서  / 머쓱이보다 키 큰 사람

2st/Yeonwoo/A+B-7.py
| A+B-7 | 백준 | [브론즈 V](https://www.acmicpc.net/submit/11021/83619529) |
<hr/>
- A+B-7 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [108일차] 채연우 / A+B-7

2st/Riyeon/음양 더하기.py
| 음양 더하기 | 프로그래머스 | Level.1 |
<hr/>
- 음양 더하기 : 어떤 정수들이 있습니다. 이 정수들의 절댓값을 차례대로 담은 정수 배열 absolutes와 이 정수들의 부호를 차례대로 담은 불리언 배열 signs가 매개변수로 주어집니다. 실제 정수들의 합을 구하여 return 하도록 solution 함수를 완성해주세요.
=> [108일차] 김리연 / 음양 더하기

3st/Jaehee/출력.java
https://school.programmers.co.kr/learn/courses/30/lessons/250133
| 제목 | 백준 / 프로그래머스 | 브론즈 V / Level.1 |
<hr/>
- 출력ttps://school.programmers.co.kr/learn/courses/30/lessons/250133
| 제목 | 백준 / 프로그래머스 | 브론즈 V / Level.1 |
<hr/>
- 출력 : 주어진 초기 코드는 변수에 데이터를 저장하고 출력하는 코드입니다. 아래와 같이 출력되도록 빈칸을 채워 코드를 완성해 주세요.
=> [PGS] 출력/Lv.0

3st/Seojun/짝수와 홀수.java
| 짝수와 홀수 |  프로그래머스 |  Level.1 |
<hr/>
- 짝수와 홀수 : 정수 num이 짝수일 경우 "Even"을 반환하고 홀수인 경우 "Odd"를 반환하는 함수, solution을 완성해주세요.
=> [14일차] 김서준 / 짝수와 홀수

3st/Jaeyoung/세균 증식.java
https://github.com/parkjay0709/Coding_Test_Study/tree/main/3st
<hr/>
- 세균 증식 : 어떤 세균은 1시간에 두배만큼 증식한다고 합니다. 처음 세균의 마리수 n과 경과한 시간 t가 매개변수로 주어질 때 t시간 후 세균의 수를 return하도록 solution 함수를 완성해주세요.
=> [14일차] 박재영 / 세균 증식

3st/Juhee/조건 문자열.java
https://school.programmers.co.kr/learn/courses/30/lessons/181934
| 조건 문자열 | 프로그래머스 | Level.0 |
<hr/>
- 조건 문자열 : 문자열에 따라 다음과 같이 두 수의 크기를 비교하려고 합니다.
두 수가 n과 m이라면
">", "=" : n >= m
"<", "=" : n <= m
">", "!" : n > m
"<", "!" : n < m
두 문자열 ineq와 eq가 주어집니다. ineq는 "<"와 ">"중 하나고, eq는 "="와 "!"중 하나입니다. 그리고 두 정수 n과 m이 주어질 때, n과 m이 ineq와 eq의 조건에 맞으면 1을 아니면 0을 return하도록 solution 함수를 완성해주세요.
=> [14일차] 최주희 / 조건 문자열

3st/Jaehee/나머지 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120810
| 나머지 구하기| 프로그래머스 | Level.0 |
<hr/>
- 나머지 구하기: 정수 num1, num2가 매개변수로 주어질 때, num1를 num2로 나눈 나머지를 return 하도록 solution 함수를 완성해주세요.
=> [14일차] 이제희/ 나머지 구하기

2st/Riyeon/없는 숫자 더하기.py
| 없는 숫자 더하기 | 프로그래머스 | Level.1 |
<hr/>
- 없는 숫자 더하기 : 0부터 9까지의 숫자 중 일부가 들어있는 정수 배열 numbers가 매개변수로 주어집니다. numbers에서 찾을 수 없는 0부터 9까지의 숫자를 모두 찾아 더한 수를 return 하도록 solution 함수를 완성해주세요.
=> [109일차] 김리연 / 없는 숫자 더하기

2st/Yeonwoo/문자열 반복.py
| 문자열 반복 | 백준 | [브론즈 ||](https://www.acmicpc.net/submit/2675/83861122) |
<hr/>
- 문자열 반복 : 문자열 S를 입력받은 후에, 각 문자를 R번 반복해 새 문자열 P를 만든 후 출력하는 프로그램을 작성하시오. 즉, 첫 번째 문자를 R번 반복하고, 두 번째 문자를 R번 반복하는 식으로 P를 만들면 된다. S에는 QR Code "alphanumeric" 문자만 들어있다.
QR Code "alphanumeric" 문자는 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\$%*+-./: 이다.
=> [109일차] 채연우 / 문자열 반복

3st/Juhee/원소들의 곱과 합.java
https://school.programmers.co.kr/learn/courses/30/lessons/181929
<hr/>
=> [15일차] 최주희 / 원소들의 곱과 합

3st/Seojun/평균 구하기.java
| 평균 구하기 |  프로그래머스 | Level.1 |
<hr/>
=> [15일차]김서준 / 평균 구하기

2st/Riyeon/나누어 떨어지는 숫자 배열.py
| 나누어 떨어지는 숫자 배열 | 프로그래머스 | Level.1 |
<hr/>
- 나누어 떨어지는 숫자 배열 : array의 각 element 중 divisor로 나누어 떨어지는 값을 오름차순으로 정렬한 배열을 반환하는 함수, solution을 작성해주세요. divisor로 나누어 떨어지는 element가 하나도 없다면 배열에 -1을 담아 반환하세요.
=> [110일차] 김리연 / 나누어 떨어지는 숫자 배열

3st/Jaeyoung/점의 위치 구하기.java
<hr/>
x 좌표 (x, y)를 차례대로 담은 정수 배열 dot이 매개변수로 주어집니다. 좌표 dot이 사분면 중 어디에 속하는지 1, 2, 3, 4 중 하나를 return 하도록 solution 함수를 완성해주세요.
=> [15일차] 박재영 / 점의 위치 구하기

2st/Yeonwoo/별 찍기 -1.py
| 별 찍기 -1 | 백준 | [브론즈 V](https://www.acmicpc.net/problem/2438) |
<hr/>
- 별 찍기 -1 : 첫째 줄에는 별 1개, 둘째 줄에는 별 2개, N번째 줄에는 별 N개를 찍는 문제
=> [110일차] 채연우 / 별 찍기 -1

2st/Yeonwoo/별 찍기-2.py
| 별 찍기-2 | 백준 | [브론즈 IV](https://www.acmicpc.net/submit/2439/83861705) |
<hr/>
- 별 찍기-2 : 첫째 줄에는 별 1개, 둘째 줄에는 별 2개, N번째 줄에는 별 N개를 찍는 문제
=> [111일차] 채연우 / 별 찍기-2

2st/Riyeon/제일 작은 수 제거하기.py
| 제일 작은 수 제거하기 | 프로그래머스 | Level.1 |
<hr/>
- 제일 작은 수 제거하기 : 정수를 저장한 배열, arr 에서 가장 작은 수를 제거한 배열을 리턴하는 함수, solution을 완성해주세요. 단, 리턴하려는 배열이 빈 배열인 경우엔 배열에 -1을 채워 리턴하세요. 예를들어 arr이 [4,3,2,1]인 경우는 [4,3,2]를 리턴 하고, [10]면 [-1]을 리턴 합니다.
=> [111일차] 김리연 / 제일 작은 수 제거하기

3st/Jaeyoung/심폐소생술.java, 3st/Jaeyoung/카운트 다운.java
https://school.programmers.co.kr/learn/courses/30/lessons/181899
<hr/>
=> [16일차] 박재영 / 카운트 다운

3st/Seojun/약수의 합.java
| 약수의 합 | 프로그래머스 |  Level.1 |
<hr/>
- 약수의 합 : 정수 n을 입력받아 n의 약수를 모두 더한 값을 리턴하는 함수, solution을 완성해주세요
=> [18일차]  김서준  / 약수의 합

3st/Jaeyoung/짝수 홀수 개수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120824
<hr/>
=> [17일차] 박재영 / 짝수 홀수 개수

2st/Riyeon/핸드폰 번호 가리기.py
| 핸드폰 번호 가리기 | 프로그래머스 | Level.1 |
<hr/>
- 핸드폰 번호 가리기 : 프로그래머스 모바일은 개인정보 보호를 위해 고지서를 보낼 때 고객들의 전화번호의 일부를 가립니다. 전화번호가 문자열 phone_number로 주어졌을 때, 전화번호의 뒷 4자리를 제외한 나머지 숫자를 전부 *으로 가린 문자열을 리턴하는 함수, solution을 완성해주세요.
=> [112일차] 김리연 / 핸드폰 번호 가리기

3st/Juhee/카운트 업.java
https://school.programmers.co.kr/learn/courses/30/lessons/181920
<hr/>
=> [17일차] 최주희 / 카운트 업

2st/Yeonwoo/평균.py
| 평균 | 백준 | [브론즈 I](https://www.acmicpc.net/problem/1546) |
<hr/>
- 평균 : 세준이는 기말고사를 망쳤다. 세준이는 점수를 조작해서 집에 가져가기로 했다. 일단 세준이는 자기 점수 중에 최댓값을 골랐다. 이 값을 M이라고 한다. 그리고 나서 모든 점수를 점수/M*100으로 고쳤다.
예를 들어, 세준이의 최고점이 70이고, 수학점수가 50이었으면 수학점수는 50/70*100이 되어 71.43점이 된다.
세준이의 성적을 위의 방법대로 새로 계산했을 때, 새로운 평균을 구하는 프로그램을 작성하시오.
=> [112일차] 채연우 / 평균

3st/Jaeyoung/가장 큰 수 찾기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120899
<hr/>
=> [18일차] 박재영 / 가장 큰 수 찾기

2st/Riyeon/수박수박수박수박수박수.py
| 수박수박수박수박수박수? | 프로그래머스 | Level.1 |
<hr/>
- 수박수박수박수박수박수? : 길이가 n이고, "수박수박수박수...."와 같은 패턴을 유지하는 문자열을 리턴하는 함수, solution을 완성하세요. 예를들어 n이 4이면 "수박수박"을 리턴하고 3이라면 "수박수"를 리턴하면 됩니다.
=> [113일차] 김리연 / 수박수박수박수박수박수?

3st/Juhee/이어 붙인 수.java
https://school.programmers.co.kr/learn/courses/30/lessons/181928
<hr/>
=> [18일차] 최주희 / 이어 붙인 수

3st/Seojun/배역 두배 만들기.java
| 배열 두 배 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 열 두 배 만들기 : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 각 원소에 두배한 원소를 가진 배열을 return하도록 solution 함수를 완성해주세요.
=> [19일차] 김서준 / 배열 두 배 만들기

2st/Yeonwoo/X보다 작은 수.py
| X보다 작은 수 | 백준 | [브론즈 V](https://www.acmicpc.net/submit/10871/83943486) |
<hr/>
- X보다 작은 수 : 정수 N개로 이루어진 수열 A와 정수 X가 주어진다. 이때, A에서 X보다 작은 수를 모두 출력하는 프로그램을 작성하시오.
=> [113일차] 채연우 / X보다 작은 수

3st/Jaehee/대문자와 소문자.java
https://school.programmers.co.kr/learn/courses/30/lessons/120893
| 대문자와 소문자| 프로그래머스 | Level.0 |
<hr/>
- 대문자와 소문자: 문자열 my_string이 매개변수로 주어질 때, 대문자는 소문자로 소문자는 대문자로 변환한 문자열을 return하도록 solution 함수를 완성해주세요.
=> [PGS] 이제희/대문자와 소문자

2st/Riyeon/약수의 개수와 덧셈.py
| 약수의 개수와 덧셈 | 프로그래머스 | Level.1 |
<hr/>
- 약수의 개수와 덧셈 : 두 정수 left와 right가 매개변수로 주어집니다. left부터 right까지의 모든 수들 중에서, 약수의 개수가 짝수인 수는 더하고, 약수의 개수가 홀수인 수는 뺀 수를 return 하도록 solution 함수를 완성해주세요.
=> [114일차] 김리연 / 약수의 개수와 덧셈

3st/Juhee/수열과 구간 쿼리 3.java
https://school.programmers.co.kr/learn/courses/30/lessons/181924
| 수열과 구간 쿼리 3 | 프로그래머스 | Level.0 |
<hr/>
- 수열과 구간 쿼리 3 : 정수 배열 arr와 2차원 정수 배열 queries이 주어집니다. queries의 원소는 각각 하나의 query를 나타내며, [i, j] 꼴입니다.
각 query마다 순서대로 arr[i]의 값과 arr[j]의 값을 서로 바꿉니다.
=> [19일차] 최주희 / 수열과 구간 쿼리 3

2st/Yeonwoo/최댓값.py
| 최댓값 | 백준 | [브론즈 III](https://www.acmicpc.net/submit/2562/83541136) |
<hr/>
- 최댓값 : 9개의 서로 다른 자연수가 주어질 때, 이들 중 최댓값을 찾고 그 최댓값이 몇 번째 수인지를 구하는 프로그램을 작성하시오.
예를 들어, 서로 다른 9개의 자연수
3, 29, 38, 12, 57, 74, 40, 85, 61
이 주어지면, 이들 중 최댓값은 85이고, 이 값은 8번째 수이다.
=> [114일차] 채연우 / 최댓값

3st/Jaeyoung/편지.java
https://school.programmers.co.kr/learn/courses/30/lessons/120898
<hr/>
- 편지 : 머쓱이는 할머니께 생신 축하 편지를 쓰려고 합니다. 할머니가 보시기 편하도록 글자 한 자 한 자를 가로 2cm 크기로 적으려고 하며, 편지를 가로로만 적을 때, 축하 문구 message를 적기 위해 필요한 편지지의 최소 가로길이를 return 하도록 solution 함수를 완성해주세요.
=> [19일차] 박재영 / 편지

3st/Jaeyoung/문자 출력.java
https://school.programmers.co.kr/learn/courses/30/lessons/340207
| 문자 출력 | 프로그래머스 | Level.0 |
<hr/>
- 문자 출력 : 주어진 코드는 변수에 데이터를 저장하고 출력하는 코드입니다. 아래와 같이 출력되도록 빈칸을 채워 코드를 완성해 주세요.
=> [20일차] 박재영 / 문자 출력

2st/Riyeon/문자열 내림차순으로 배치하기.py
| 문자열 내림차순으로 배치하기 | 프로그래머스 | Level.1 |
<hr/>
- 문자열 내림차순으로 배치하기 : 문자열 s에 나타나는 문자를 큰것부터 작은 순으로 정렬해 새로운 문자열을 리턴하는 함수, solution을 완성해주세요. s는 영문 대소문자로만 구성되어 있으며, 대문자는 소문자보다 작은 것으로 간주합니다.
=> [115일차] 김리연 / 문자열 내림차순으로 배치하기

3st/Seojun/출력.java
https://school.programmers.co.kr/learn/courses/30/lessons/250133
| 출력 | 프로그래머스 | Level.0 |
<hr/>
- 출력 : 주어진 초기 코드는 변수에 데이터를 저장하고 출력하는 코드입니다. 아래와 같이 출력되도록 빈칸을 채워 코드를 완성해 주세요.
=> [21일차] 김서준 / 출력

2st/Yeonwoo/최소, 최대.py
| 최소, 최대 | 백준 | [브론즈 III](https://www.acmicpc.net/submit/10818/83399989) |
<hr/>
- 최소, 최대 : N개의 정수가 주어진다. 이때, 최솟값과 최댓값을 구하는 프로그램을 작성하시오.
=> [115일차] 채연우 / 최소, 최대

3st/Jaehee/문자 리스트를 문자열로 변환하기.java, 3st/Jaehee/문자열 겹쳐쓰기.java
| 문자 리스트를 문자열로 변환하기| 프로그래머스 | Level.0 |
<hr/>
- 문자 리스트를 문자열로 변환하기: 문자들이 담겨있는 배열 arr가 주어집니다. arr의 원소들을 순서대로 이어 붙인 문자열을 return 하는 solution함수를 작성해 주세요.
=> [21일차] 이제희/문자 리스트를 문자열로 변환하기

3st/Juhee/9로 나눈 나머지.java
https://school.programmers.co.kr/learn/courses/30/lessons/181914
| 9로 나눈 나머지 | 프로그래머스 | Level.0 |
<hr/>
- 9로 나눈 나머지 : 음이 아닌 정수를 9로 나눈 나머지는 그 정수의 각 자리 숫자의 합을 9로 나눈 나머지와 같은 것이 알려져 있습니다.
이 사실을 이용하여 음이 아닌 정수가 문자열 number로 주어질 때, 이 정수를 9로 나눈 나머지를 return 하는 solution 함수를 작성해주세요.
=> [20일차] 최주희 / 9로 나눈 나머지

3st/Jaehee/공배수.java
https://school.programmers.co.kr/learn/courses/30/lessons/181936
| 공배수|  프로그래머스 | Level.0 |
<hr/>
- 공배수: 정수 number와 n, m이 주어집니다. number가 n의 배수이면서 m의 배수이면 1을 아니라면 0을 return하도록 solution 함수를 완성해주세요.
=> [22일차] 이제희/공배수

2st/Riyeon/피로도.java
| 피로도 | 프로그래머스 | Level.2 |
<hr/>
- 피로도 : XX게임에는 피로도 시스템(0 이상의 정수로 표현합니다)이 있으며, 일정 피로도를 사용해서 던전을 탐험할 수 있습니다. 이때, 각 던전마다 탐험을 시작하기 위해 필요한 "최소 필요 피로도"와 던전 탐험을 마쳤을 때 소모되는 "소모 피로도"가 있습니다. "최소 필요 피로도"는 해당 던전을 탐험하기 위해 가지고 있어야 하는 최소한의 피로도를 나타내며, "소모 피로도"는 던전을 탐험한 후 소모되는 피로도를 나타냅니다. 예를 들어 "최소 필요 피로도"가 80, "소모 피로도"가 20인 던전을 탐험하기 위해서는 유저의 현재 남은 피로도는 80 이상 이어야 하며, 던전을 탐험한 후에는 피로도 20이 소모됩니다.
이 게임에는 하루에 한 번씩 탐험할 수 있는 던전이 여러개 있는데, 한 유저가 오늘 이 던전들을 최대한 많이 탐험하려 합니다. 유저의 현재 피로도 k와 각 던전별 "최소 필요 피로도", "소모 피로도"가 담긴 2차원 배열 dungeons 가 매개변수로 주어질 때, 유저가 탐험할수 있는 최대 던전 수를 return 하도록 solution 함수를 완성해주세요.
=> [116일차] 김리연 / 피로도

3st/Juhee/수열과 구간 쿼리 4.java
https://school.programmers.co.kr/learn/courses/30/lessons/181922?language=java
| 수열과 구간 쿼리 4 | 프로그래머스 | Level.0 |
<hr/>
- 수열과 구간 쿼리 4 : 정수 배열 arr와 2차원 정수 배열 queries이 주어집니다. queries의 원소는 각각 하나의 query를 나타내며, [s, e, k] 꼴입니다.
각 query마다 순서대로 s ≤ i ≤ e인 모든 i에 대해 i가 k의 배수이면 arr[i]에 1을 더합니다.
=> [21일차] 최주희 / 수열과 구간 쿼리 4

3st/Jaeyoung/a와 b 출력하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181951
<hr/>
- a와 b 출력하기 : 정수 a와 b가 주어집니다. 각 수를 입력받아 입출력 예와 같은 형식으로 출력하는 코드를 작성해 보세요.
=> [21일차] 박재영 / a와 b 출력하기

2st/Yeonwoo/삼각형 외우기.py
| 삼각형 외우기 | 백준 | [브론즈 IV](https://www.acmicpc.net/problem/10101) |
<hr/>
- 삼각형 외우기 : 창영이는 삼각형의 종류를 잘 구분하지 못한다. 따라서 프로그램을 이용해 이를 외우려고 한다.
삼각형의 세 각을 입력받은 다음,
세 각의 크기가 모두 60이면, Equilateral
세 각의 합이 180이고, 두 각이 같은 경우에는 Isosceles
세 각의 합이 180이고, 같은 각이 없는 경우에는 Scalene
세 각의 합이 180이 아닌 경우에는 Error
를 출력하는 프로그램을 작성하시오.
=> [116일차] 채연우 / 삼각형 외우기

3st/Seojun/나머지가 1이 되는 수 찾기.java
| 나머지가 1이 되는 수 찾기 | 프로그래머스 |  Level.1 |
<hr/>
- 나머지가 1이 되는 수 찾기 : 설명
=> [22일차] 김서준 / 나머지가 1이 되는 수 찾기

3st/Hyeonseo/programmer/중복된 숫자 개수.c
https://school.programmers.co.kr/learn/courses/30/lessons/120583
<hr/>
=> [22일차] 조현서 / 중복된 숫자 개수

3st/Juhee/간단한 논리 연산.java
https://school.programmers.co.kr/learn/courses/30/lessons/181917?language=java
| 간단한 논리 연산 | 프로그래머스 | Level.0 |
<hr/>
- 간단한 논리 연산 : boolean 변수 x1, x2, x3, x4가 매개변수로 주어질 때, 다음의 식의 true/false를 return 하는 solution 함수를 작성해 주세요.
(x1 ∨ x2) ∧ (x3 ∨ x4)
=> [22일차] 최주희 / 간단한 논리 연산

3st/Jaeyoung/수 조작하기 1.java
<hr/>
- 수 조작하기 1 : 정수 n과 문자열 control이 주어집니다. control은 "w", "a", "s", "d"의 4개의 문자로 이루어져 있으며, control의 앞에서부터 순서대로 문자에 따라 n의 값을 바꿉니다.
"w" : n이 1 커집니다.
"s" : n이 1 작아집니다.
"d" : n이 10 커집니다.
"a" : n이 10 작아집니다.
위 규칙에 따라 n을 바꿨을 때 가장 마지막에 나오는 n의 값을 return 하는 solution 함수를 완성해 주세요.
=> [22일차] 박재영 /  수 조작하기 1

3st/Seojun/flag에 따라 다른 값 반환하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181933
| flag에 따라 다른 값 반환하기 |  프로그래머스 |  Level.0 |
<hr/>
=> [23일차] 김서준 / flag에 따라 다른 값 반환하기

2st/Yeonwoo/그대로 출력하기.py
| 그대로 출력하기 | 백준 | [브론즈 III](https://www.acmicpc.net/submit/11718/84189186) |
<hr/>
- 그대로 출력하기 : 입력 받은 대로 출력하는 프로그램을 작성하시오.
=> [117일차] 채연우 / 그대로 출력하기

3st/Jaehee/문자열 섞기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181942?language=java
| 문자열 섞기 | 프로그래머스 |  Level.0 |
<hr/>
- 문자열 섞기 : 길이가 같은 두 문자열 str1과 str2가 주어집니다.
두 문자열의 각 문자가 앞에서부터 서로 번갈아가면서 한 번씩 등장하는 문자열을 만들어 return 하는 solution 함수를 완성해 주세요.
=> [23일차] 이제희/문자열 섞기

3st/Juhee/글자 이어 붙여 문자열 만들기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181915
| 글자 이어 붙여 문자열 만들기 |  프로그래머스 | Level.0 |
<hr/>
- 글자 이어 붙여 문자열 만들기 : 문자열 my_string과 정수 배열 index_list가 매개변수로 주어집니다. my_string의 index_list의 원소들에 해당하는 인덱스의 글자들을 순서대로 이어 붙인 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [23일차] 최주희 / 글자 이어 붙여 문자열 만들기

2st/Yeonwoo/아스키 코드.py
| 아스키 코드 | 백준  | [브론즈 V](https://www.acmicpc.net/problem/11654) |
<hr/>
- 아스키 코드 : 알파벳 소문자, 대문자, 숫자 0-9중 하나가 주어졌을 때, 주어진 글자의 아스키 코드값을 출력하는 프로그램을 작성하시오.
=> [118일차] 채연우 / 아스키 코드

2st/Riyeon/타겟 넘버.java
| 타겟 넘버 | 프로그래머스 | Level.2 |
<hr/>
- 타겟 넘버 : n개의 음이 아닌 정수들이 있습니다. 이 정수들을 순서를 바꾸지 않고 적절히 더하거나 빼서 타겟 넘버를 만들려고 합니다. 예를 들어 [1, 1, 1, 1, 1]로 숫자 3을 만들려면 다음 다섯 방법을 쓸 수 있습니다.
사용할 수 있는 숫자가 담긴 배열 numbers, 타겟 넘버 target이 매개변수로 주어질 때 숫자를 적절히 더하고 빼서 타겟 넘버를 만드는 방법의 수를 return 하도록 solution 함수를 작성해주세요.
=> [118일차] 김리연 / 타겟 넘버

3st/Jaehee/문자열 뒤집기.java
| 문자열 뒤집기| 프로그래머스 |  Level.0 |
<hr/>
- 문자열 뒤집기: 문자열 my_string과 정수 s, e가 매개변수로 주어질 때, my_string에서 인덱스 s부터 인덱스 e까지를 뒤집은 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [24일] 이제희/문자열 뒤집기

3st/Seojun/옷가게 할인 받기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120818
| 옷가게 할인 받기 |  프로그래머스 |  Level.0 |
<hr/>
- 옷가게 할인 받기 : 머쓱이네 옷가게는 10만 원 이상 사면 5%, 30만 원 이상 사면 10%, 50만 원 이상 사면 20%를 할인해줍니다.
=> [24일차] 김서준 / 옷가게 할인 받기

3st/Jaeyoung/원소들의 곱과 합.java
=> [23일차] 박재영 / 원소들의 곱과 합

3st/Hyeonseo/com/n의 배수.java, 3st/Hyeonseo/com/하드샤 수.java
https://school.programmers.co.kr/learn/courses/30/lessons/181937
| n의 배수 | 프로그래머스 | Level.0 |
<hr/>
- n의 배수 : 정수 num과 n이 매개 변수로 주어질 때, num이 n의 배수이면 1을 return n의 배수가 아니라면 0을 return하도록 solution 함수를 완성해주세요.
=> [24일차] 조현서 /  n의 배수

2st/Riyeon/압축.java
| 압축 | 프로그래머스 | Level.2 |
<hr/>
- 압축 : 신입사원 어피치는 카카오톡으로 전송되는 메시지를 압축하여 전송 효율을 높이는 업무를 맡게 되었다. 메시지를 압축하더라도 전달되는 정보가 바뀌어서는 안 되므로, 압축 전의 정보를 완벽하게 복원 가능한 무손실 압축 알고리즘을 구현하기로 했다.
어피치는 여러 압축 알고리즘 중에서 성능이 좋고 구현이 간단한 LZW(Lempel–Ziv–Welch) 압축을 구현하기로 했다. LZW 압축은 1983년 발표된 알고리즘으로, 이미지 파일 포맷인 GIF 등 다양한 응용에서 사용되었다.
LZW 압축은 다음 과정을 거친다.
1. 길이가 1인 모든 단어를 포함하도록 사전을 초기화한다.
2. 사전에서 현재 입력과 일치하는 가장 긴 문자열 w를 찾는다.
3. w에 해당하는 사전의 색인 번호를 출력하고, 입력에서 w를 제거한다.
4. 입력에서 처리되지 않은 다음 글자가 남아있다면(c), w+c에 해당하는 단어를 사전에 등록한다.
5. 단계 2로 돌아간다.
압축 알고리즘이 영문 대문자만 처리한다고 할 때, 사전은 다음과 같이 초기화된다. 사전의 색인 번호는 정수값으로 주어지며, 1부터 시작한다고 하자.
=> [119일차] 김리연 / 압축

3st/Jaeyoung/평균 구하기.java
| 평균 구하기 | 프로그래머스 | Level.1 |
<hr/>
=> [24일차] 박재영 / 평균 구하기

3st/Seojun/가장 큰 수 찾기.java
| 가장 큰 수 찾기 |  프로그래머스 |  Level.0 |
<hr/>
=> [24일차] 김서준 / 가장 큰 수 찾기

3st/Jaehee/두 수의 합1.java
| 두 수의 합 | 프로그래머스 |  Level.0 |
<hr/>
- 두 수의 합 : 0 이상의 두 정수가 문자열 a, b로 주어질 때, a + b의 값을 문자열로 return 하는 solution 함수를 작성해 주세요.
=> [24일] 이제희/두 수의 합

3st/Hyeonseo/com/x만큼 간격이 있는 n개의 숫자.java, 3st/Hyeonseo/com/없는 숫자 더하기.java, 3st/Hyeonseo/com/하드샤 수.java
https://school.programmers.co.kr/learn/courses/30/lessons/181831
| 특이한 이차원 배열 2 | 프로그래머스 | Level.0 |
<hr/>
- 특이한 이차원 배열 2 : n × n 크기의 이차원 배열 arr이 매개변수로 주어질 때, arr이 다음을 만족하면 1을 아니라면 0을 return 하는 solution 함수를 작성해 주세요.
0 ≤ i, j < n인 정수 i, j에 대하여 arr[i][j] = arr[j][i]
=> [25일차] 조현서 / 특이한 이차원 배열 2

2st/Yeonwoo/평행.py
| 평행 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120875) |
<hr/>
- 평행 : 점 네 개의 좌표를 담은 이차원 배열  dots가 다음과 같이 매개변수로 주어집니다.
[[x1, y1], [x2, y2], [x3, y3], [x4, y4]]
주어진 네 개의 점을 두 개씩 이었을 때, 두 직선이 평행이 되는 경우가 있으면 1을 없으면 0을 return 하도록 solution 함수를 완성해보세요.
=> [119일차] 채연우 / 평행

3st/Jaeyoung/홀수 vs 짝수.java
https://school.programmers.co.kr/learn/courses/30/lessons/181887
| 홀수 vs 짝수 | 프로그래머스 | Level.0 |
<hr/>
=> [25일차] 박재영 / 홀수 vs 짝수

3st/Juhee/문자열의 앞의 n글자.java
https://school.programmers.co.kr/learn/courses/30/lessons/181907
<hr/>
=> [25일차] 최주희 / 문자열의 앞의 n글자

2st/Riyeon/부족한 금액 계산하기.py
| 부족한 금액 계산하기 | 프로그래머스 | Level.1 |
<hr/>
- 부족한 금액 계산하기 : 새로 생긴 놀이기구는 인기가 매우 많아 줄이 끊이질 않습니다. 이 놀이기구의 원래 이용료는 price원 인데, 놀이기구를 N 번 째 이용한다면 원래 이용료의 N배를 받기로 하였습니다. 즉, 처음 이용료가 100이었다면 2번째에는 200, 3번째에는 300으로 요금이 인상됩니다.
놀이기구를 count번 타게 되면 현재 자신이 가지고 있는 금액에서 얼마가 모자라는지를 return 하도록 solution 함수를 완성하세요.
단, 금액이 부족하지 않으면 0을 return 하세요.
=> [120일차] 김리연 / 부족한 금액 계산하기

3st/Jaehee/두 수의 합1.java, 3st/Jaehee/문자열 곱하기.java
| 문자열 곱하기 | 프로그래머스 |  Level.0 |
<hr/>
=> [25일차] 이제희/문자열 곱하기

3st/Seojun/짝수 홀수 개수.java
| 짝수 홀수 개수 |  프로그래머스 | Level.0 |
<hr/>
=> [25일차] 김서준 / 짝수 홀수 개수

2st/Yeonwoo/크기가 작은 부분문자열.py
| 크기가 작은 부분문자열 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/147355) |
<hr/>
- 크기가 작은 부분문자열 : 숫자로 이루어진 문자열 t와 p가 주어질 때, t에서 p와 길이가 같은 부분문자열 중에서, 이 부분문자열이 나타내는 수가 p가 나타내는 수보다 작거나 같은 것이 나오는 횟수를 return하는 함수 solution을 완성하세요.
예를 들어, t="3141592"이고 p="271" 인 경우, t의 길이가 3인 부분 문자열은 314, 141, 415, 159, 592입니다. 이 문자열이 나타내는 수 중 271보다 작거나 같은 수는 141, 159 2개 입니다.
=> [120일차] 채연우 / 크기가 작은 부분문자열

3st/Jaeyoung/문자열 출력하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181952
| 문자열 출력하기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 출력하기 : 문자열 str이 주어질 때, str을 출력하는 코드를 작성해 보세요.
=> [26일차] 박재영 / 문자열 출력하기

2st/Riyeon/문자열 다루기 기본.py
| 문자열 다루기 기본 | 프로그래머스 | Level.1 |
<hr/>
- 문자열 다루기 기본 : 문자열 s의 길이가 4 혹은 6이고, 숫자로만 구성돼있는지 확인해주는 함수, solution을 완성하세요. 예를 들어 s가 "a234"이면 False를 리턴하고 "1234"라면 True를 리턴하면 됩니다.
=> [121일차] 김리연 / 문자열 다루기 기본

3st/Jaehee/분수의 덧셈.java
| 분수의 덧셈| 프로그래머스 |  Level.0|
<hr/>
- 분수의 덧셈 : 첫 번째 분수의 분자와 분모를 뜻하는 numer1, denom1, 두 번째 분수의 분자와 분모를 뜻하는 numer2, denom2가 매개변수로 주어집니다. 두 분수를 더한 값을 기약 분수로 나타냈을 때 분자와 분모를 순서대로 담은 배열을 return 하도록 solution 함수를 완성해보세요.
=> [26일차] 이제희/분수의 덧셈

2st/Yeonwoo/최소직사각형.py
| 최소직사각형 | 프로그래머스 | [Level.1 ](https://school.programmers.co.kr/learn/courses/30/lessons/86491)|
<hr/>
- 최소직사각형 : 명함 지갑을 만드는 회사에서 지갑의 크기를 정하려고 합니다. 다양한 모양과 크기의 명함들을 모두 수납할 수 있으면서, 작아서 들고 다니기 편한 지갑을 만들어야 합니다. 이러한 요건을 만족하는 지갑을 만들기 위해 디자인팀은 모든 명함의 가로 길이와 세로 길이를 조사했습니다.
아래 표는 4가지 명함의 가로 길이와 세로 길이를 나타냅니다.
가장 긴 가로 길이와 세로 길이가 각각 80, 70이기 때문에 80(가로) x 70(세로) 크기의 지갑을 만들면 모든 명함들을 수납할 수 있습니다. 하지만 2번 명함을 가로로 눕혀 수납한다면 80(가로) x 50(세로) 크기의 지갑으로 모든 명함들을 수납할 수 있습니다. 이때의 지갑 크기는 4000(=80 x 50)입니다.
모든 명함의 가로 길이와 세로 길이를 나타내는 2차원 배열 sizes가 매개변수로 주어집니다. 모든 명함을 수납할 수 있는 가장 작은 지갑을 만들 때, 지갑의 크기를 return 하도록 solution 함수를 완성해주세요.
=> [121일차] 채연우 / 최소직사각형

3st/Seojun/배열 비교하기.java
| 배열 비교하기 | 프로그래머스 | Level.0 |
<hr/>
- 배열 비교하기 : 이 문제에서 두 정수 배열의 대소관계를 다음과 같이 정의합니다.
두 배열의 길이가 다르다면, 배열의 길이가 긴 쪽이 더 큽니다.
배열의 길이가 같다면 각 배열에 있는 모든 원소의 합을 비교하여 다르다면 더 큰 쪽이 크고, 같다면 같습니다.
두 정수 배열 arr1과 arr2가 주어질 때, 위에서 정의한 배열의 대소관계에 대하여 arr2가 크다면 -1, arr1이 크다면 1, 두 배열이 같다면 0을 return 하는 solution 함수를 작성해 주세요.
=> [26일차] 김서준 / 배열 비교하기

3st/Jaeyoung/더 크게 합치기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181939
| 더 크게 합치기 | 프로그래머스 | Level.0 |
<hr/>
- 더 크게 합치기 : 연산 ⊕는 두 정수에 대한 연산으로 두 정수를 붙여서 쓴 값을 반환합니다. 예를 들면 다음과 같습니다.
12 ⊕ 3 = 123
3 ⊕ 12 = 312
양의 정수 a와 b가 주어졌을 때, a ⊕ b와 b ⊕ a 중 더 큰 값을 return 하는 solution 함수를 완성해 주세요.
단, a ⊕ b와 b ⊕ a가 같다면 a ⊕ b를 return 합니다.
=> [27일차] 박재영 / 더 크게 합치기

3st/Seojun/중악값 구하기,java
=> [27일차] 김서준 / 중앙값 구하기

2st/Yeonwoo/직사각형 별찍기.py
| 직사각형 별찍기 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/12969)|
<hr/>
- 직사각형 별찍기 : 이 문제에는 표준 입력으로 두 개의 정수 n과 m이 주어집니다.
별(*) 문자를 이용해 가로의 길이가 n, 세로의 길이가 m인 직사각형 형태를 출력해보세요.
=> [122일차] 채연우 / 직사각형 별찍기

2st/Riyeon/최댓값과 최솟값.py
| 최댓값과 최솟값 | 프로그래머스 | Level.1 |
<hr/>
- 최댓값과 최솟값 : 문자열 s에는 공백으로 구분된 숫자들이 저장되어 있습니다. str에 나타나는 숫자 중 최소값과 최대값을 찾아 이를 "(최소값) (최대값)"형태의 문자열을 반환하는 함수, solution을 완성하세요.
=> [122일차] 김리연 / 최댓값과 최솟값

3st/Juhee/부분 문자열 이어 붙여 문자열 만들기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181911?language=java
<hr/>
- 부분 문자열 이어 붙여 문자열 만들기 : 길이가 같은 문자열 배열 my_strings와 이차원 정수 배열 parts가 매개변수로 주어집니다. parts[i]는 [s, e] 형태로, my_string[i]의 인덱스 s부터 인덱스 e까지의 부분 문자열을 의미합니다. 각 my_strings의 원소의 parts에 해당하는 부분 문자열을 순서대로 이어 붙인 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [27일차] 최주희 / 부분 문자열 이어 붙여 문자열 만들기

3st/Jaehee/몫 구하기.java
| 몫 구하기| 프로그래머스 | Level.0 |
<hr/>
- 몫 구하기: 정수 num1, num2가 매개변수로 주어질 때, num1을 num2로 나눈 몫을 return 하도록 solution 함수를 완성해주세요.
=> [27일차] 이제희/몫 구하기

3st/Hyeonseo/com/문자열 뒤집기.java, 3st/Hyeonseo/programmer/하드샤 수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120822
<hr/>
=> [27일차] 조현서 / 문자열 뒤집기

3st/Jaehee/두 수의 나눗셈.java
https://school.programmers.co.kr/learn/courses/30/lessons/120806
|  두 수의 나눗셈| 프로그래머스 | Level.0 |
<hr/>
-  두 수의 나눗셈 : 정수 num1과 num2가 매개변수로 주어질 때, num1을 num2로 나눈 값에 1,000을 곱한 후 정수 부분을 return 하도록 soltuion 함수를 완성해주세요.
=> [28일] 이제희/두 수의 나눗셈

3st/Juhee/접두사인지 확인하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181906
| 접두사인지 확인하기 | 프로그래머스 | Level.0 |
<hr/>
- 접두사인지 확인하기 : 어떤 문자열에 대해서 접두사는 특정 인덱스까지의 문자열을 의미합니다. 예를 들어, "banana"의 모든 접두사는 "b", "ba", "ban", "bana", "banan", "banana"입니다.
문자열 my_string과 is_prefix가 주어질 때, is_prefix가 my_string의 접두사라면 1을, 아니면 0을 return 하는 solution 함수를 작성해 주세요.
=> [28일차] 최주희 / 접두사인지 확인하기

2st/Riyeon/게임 맵 최단거리.java
| 게임 맵 최단거리 | 프로그래머스 | Level.2 |
<hr/>
- 게임 맵 최단거리 : ROR 게임은 두 팀으로 나누어서 진행하며, 상대 팀 진영을 먼저 파괴하면 이기는 게임입니다. 따라서, 각 팀은 상대 팀 진영에 최대한 빨리 도착하는 것이 유리합니다.
지금부터 당신은 한 팀의 팀원이 되어 게임을 진행하려고 합니다.  검은색 부분은 벽으로 막혀있어 갈 수 없는 길이며, 흰색 부분은 갈 수 있는 길입니다. 캐릭터가 움직일 때는 동, 서, 남, 북 방향으로 한 칸씩 이동하며, 게임 맵을 벗어난 길은 갈 수 없습니다.
만약, 상대 팀이 자신의 팀 진영 주위에 벽을 세워두었다면 상대 팀 진영에 도착하지 못할 수도 있습니다. 
게임 맵의 상태 maps가 매개변수로 주어질 때, 캐릭터가 상대 팀 진영에 도착하기 위해서 지나가야 하는 칸의 개수의 최솟값을 return 하도록 solution 함수를 완성해주세요. 단, 상대 팀 진영에 도착할 수 없을 때는 -1을 return 해주세요.
=> [123일차] 김리연 / 게임 맵 최단거리

2st/Yeonwoo/K번째수.py
| K번째수 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/42748) |
<hr/>
- K번째수 : 배열 array의 i번째 숫자부터 j번째 숫자까지 자르고 정렬했을 때, k번째에 있는 수를 구하려 합니다.
예를 들어 array가 [1, 5, 2, 6, 3, 7, 4], i = 2, j = 5, k = 3이라면
array의 2번째부터 5번째까지 자르면 [5, 2, 6, 3]입니다.
1에서 나온 배열을 정렬하면 [2, 3, 5, 6]입니다.
2에서 나온 배열의 3번째 숫자는 5입니다.
배열 array, [i, j, k]를 원소로 가진 2차원 배열 commands가 매개변수로 주어질 때, commands의 모든 원소에 대해 앞서 설명한 연산을 적용했을 때 나온 결과를 배열에 담아 return 하도록 solution 함수를 작성해주세요.
=> [123일차] 채연우 / K번째수

3st/Jaeyoung/문자열 곱하기.java, 3st/Jaeyoung/정수 찾기.java
=> [29일차] 박재영 / 문자열 곱하기

3st/Juhee/특정 문자 제거하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120826
<hr/>
=> [29일차] 최주희 / 특정 문자 제거하기

2st/Yeonwoo/같은 숫자는 싫어.py
| 같은 숫자는 싫어 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/12906) |
<hr/>
- 같은 숫자는 싫어 : 배열 arr가 주어집니다. 배열 arr의 각 원소는 숫자 0부터 9까지로 이루어져 있습니다. 이때, 배열 arr에서 연속적으로 나타나는 숫자는 하나만 남기고 전부 제거하려고 합니다. 단, 제거된 후 남은 수들을 반환할 때는 배열 arr의 원소들의 순서를 유지해야 합니다. 예를 들면,
arr = [1, 1, 3, 3, 0, 1, 1] 이면 [1, 3, 0, 1] 을 return 합니다.
arr = [4, 4, 4, 3, 3] 이면 [4, 3] 을 return 합니다.
배열 arr에서 연속적으로 나타나는 숫자는 제거하고 남은 수들을 return 하는 solution 함수를 완성해 주세요.
=> [124일차] 채연우 / 같은 숫자는 싫어

3st/Jaehee/짝수는 싫어요.java
| 짝수는 싫어요| 프로그래머스 | Level.0 |
<hr/>
=> [29일차] 이제희/짝수는 싫어요

3st/Hyeonseo/com/2016년.java, 3st/Hyeonseo/com/세균 증식.java, 3st/Hyeonseo/com/홀수 vs 짝수.java
| 홀짝 구분하기 | 프로그래머스 | Level.0 |
<hr/>
=> [29일차] 조현서 / 홀짝 구분하기

3st/Jaeyoung/공배수.java
| 공배수 | 프로그래머스 | Level.0 |
<hr/>
=> [30일차] 박재영 / 공배수

3st/Juhee/콜라츠 수열 만들기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181919
<hr/>
=> [30일차] 최주희 / 콜라츠 수열 만들기

3st/Seojun/세균 증식.java
<hr/>
- 세균 증식 : 어떤 세균은 1시간에 두배만큼 증식한다고 합니다. 처음 세균의 마리수 n과 경과한 시간 t가 매개변수로 주어질 때 t시간 후 세균의 수를 return하도록 solution 함수를 완성해주세요.
=> [30일차] 김서준 / 세균 증식

2st/Yeonwoo/최댓값과 최솟값.py
| 최댓값과 최솟값 | 프로그래머스 | [Level.2](https://school.programmers.co.kr/learn/courses/30/lessons/12939) |
<hr/>
- 최댓값과 최솟값 : 문자열 s에는 공백으로 구분된 숫자들이 저장되어 있습니다. str에 나타나는 숫자 중 최소값과 최대값을 찾아 이를 "(최소값) (최대값)"형태의 문자열을 반환하는 함수, solution을 완성하세요.
=> [125일차] 채연우 / 최댓값과 최솟값

3st/Jaehee/k의 개수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120887
| k의 개수|  프로그래머스 | Level.0 |
<hr/>
- k의 개수 : 1부터 13까지의 수에서, 1은 1, 10, 11, 12, 13 이렇게 총 6번 등장합니다. 정수 i, j, k가 매개변수로 주어질 때, i부터 j까지 k가 몇 번 등장하는지 return 하도록 solution 함수를 완성해주세요.
=> [30일차] 이제희/k의 개수

3st/Juhee/카운트 다운.java, 3st/Juhee/콜라츠 수열 만들기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181899
<hr/>
=> [31일차] 최주희 / 카운트 다운

3st/Jaeyoung/문자열을 정수로 변환하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181848
<hr/>
- 문자열을 정수로 변환하기 : 숫자로만 이루어진 문자열 n_str이 주어질 때, n_str을 정수로 변환하여 return하도록 solution 함수를 완성해주세요.
=> [31일차] 박재영 / 문자열을 정수로 변환하기

3st/Jaehee/7의 개수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120912
| 7의 개수| 프로그래머스 | Level.0 |
<hr/>
- 7의 개수: 머쓱이는 행운의 숫자 7을 가장 좋아합니다. 정수 배열 array가 매개변수로 주어질 때, 7이 총 몇 개 있는지 return 하도록 solution 함수를 완성해보세요.
=> [31일차] 이제희/7의 개수

2st/Riyeon/더 맵게.java
| 더 맵게 | 프로그래머스 | Level.2 |
<hr/>
- 더 맵게 : 매운 것을 좋아하는 Leo는 모든 음식의 스코빌 지수를 K 이상으로 만들고 싶습니다. 모든 음식의 스코빌 지수를 K 이상으로 만들기 위해 Leo는 스코빌 지수가 가장 낮은 두 개의 음식을 아래와 같이 특별한 방법으로 섞어 새로운 음식을 만듭니다.
섞은 음식의 스코빌 지수 = 가장 맵지 않은 음식의 스코빌 지수 + (두 번째로 맵지 않은 음식의 스코빌 지수 * 2)
Leo는 모든 음식의 스코빌 지수가 K 이상이 될 때까지 반복하여 섞습니다.
Leo가 가진 음식의 스코빌 지수를 담은 배열 scoville과 원하는 스코빌 지수 K가 주어질 때, 모든 음식의 스코빌 지수를 K 이상으로 만들기 위해 섞어야 하는 최소 횟수를 return 하도록 solution 함수를 작성해주세요.
=> [126일차] 김리연 / 더 맵게

3st/Juhee/가까운 1 찾기.java, 3st/Juhee/카운트 다운.java
https://school.programmers.co.kr/learn/courses/30/lessons/181898
<hr/>
- 가까운 1 찾기 : 정수 배열 arr가 주어집니다. 이때 arr의 원소는 1 또는 0입니다. 정수 idx가 주어졌을 때, idx보다 크면서 배열의 값이 1인 가장 작은 인덱스를 찾아서 반환하는 solution 함수를 완성해 주세요.
단, 만약 그러한 인덱스가 없다면 -1을 반환합니다.
=> [32일차] 최주희 / 가까운 1 찾기

3st/Jaeyoung/배열 비교하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181856
| 배열 비교하기 | 프로그래머스 | Level.0 |
<hr/>
- 배열 비교하기 : 이 문제에서 두 정수 배열의 대소관계를 다음과 같이 정의합니다.
두 배열의 길이가 다르다면, 배열의 길이가 긴 쪽이 더 큽니다.
배열의 길이가 같다면 각 배열에 있는 모든 원소의 합을 비교하여 다르다면 더 큰 쪽이 크고, 같다면 같습니다.
두 정수 배열 arr1과 arr2가 주어질 때, 위에서 정의한 배열의 대소관계에 대하여 arr2가 크다면 -1, arr1이 크다면 1, 두 배열이 같다면 0을 return 하는 solution 함수를 작성해 주세요.
=> [32일차] 박재영 / 배열 비교하기

3st/Jaehee/합성수 찾기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120846
| 합성수 찾기| 프로그래머스 | Level.0 |
<hr/>
- 합성수 찾기: 약수의 개수가 세 개 이상인 수를 합성수라고 합니다. 자연수 n이 매개변수로 주어질 때 n이하의 합성수의 개수를 return하도록 solution 함수를 완성해주세요.
=> [32일차] 이제희/합성수 찾기

2st/Riyeon/직사각형 별찍기.py
| 직사각형 별찍기 | 프로그래머스 | Level.1 |
<hr/>
- 직사각형 별찍기 : 이 문제에는 표준 입력으로 두 개의 정수 n과 m이 주어집니다. 별(*) 문자를 이용해 가로의 길이가 n, 세로의 길이가 m인 직사각형 형태를 출력해보세요.
=> [127일차] 김리연 / 직사각형 별찍기

3st/Jaeyoung/문자열 붙여서 출력하기.java
<hr/>
- 문자열 붙여서 출력하기 : 두 개의 문자열 str1, str2가 공백으로 구분되어 입력으로 주어집니다.
=> [33일차] 박재영 / 문자열 붙여서 출력하기

3st/Hyeonseo/com/가운데 글자 가져오기.java
https://school.programmers.co.kr/learn/courses/30/lessons/12903
| 가운데 숫자 가져오기 | 프로그래머스 | Level.1 |
<hr/>
- 가운데 글자 가져오기 : 단어 s의 가운데 글자를 반환하는 함수, solution을 만들어 보세요. 단어의 길이가 짝수라면 가운데 두글자를 반환하면 됩니다.
=> [33일차] 조현서 / 가운데 숫자 가져오기

3st/Seojun/마지막 두 원소.java
| 마지막 두 원소 | 프로그래머스 | Level.0 |
<hr/>
=> [33일차] 김서준 / 마지막 두 원소

3st/Juhee/두 수의 연산값 비교하기.java, 3st/Juhee/문자열의 뒤의 n글자.java
https://school.programmers.co.kr/learn/courses/30/lessons/181938
| 두 수의 연산값 비교하기 | 프로그래머스 | Level.1 |
<hr/>
12 ⊕ 3 = 123
3 ⊕ 12 = 312
=> [33일차] 최주희 / 두 수의 연산값 비교하기

3st/Jaeyoung/배열의 평균값.java
| 배열의 평균값 | 프로그래머스 | Level.0 |
<hr/>
- 배열의 평균값 : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소의 평균값을 return하도록 solution 함수를 완성해주세요.
=> [34일차] 박재영 / 배열의 평균값

3st/Juhee/등차수열의 특정한 항만 더하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181931
| 등차수열의 특정한 항만 더하기 | 프로그래머스 | Level.0 |
<hr/>
- 등차수열의 특정한 항만 더하기 : 두 정수 a, d와 길이가 n인 boolean 배열 included가 주어집니다. 첫째항이 a, 공차가 d인 등차수열에서 included[i]가 i + 1항을 의미할 때, 이 등차수열의 1항부터 n항까지 included가 true인 항들만 더한 값을 return 하는 solution 함수를 작성해 주세요.
=> [34일차] 최주희 / 등차수열의 특정한 항만 더하기

3st/Seojun/첫 번째로 나오는 음수.java
=> [34일차] 김서준 /첫 번째로 나오는 음수

3st/Juhee/접미사 배열.java
https://school.programmers.co.kr/learn/courses/30/lessons/181909?language=java
| 접미사 배열 | 프로그래머스 | Level.0 |
<hr/>
- 접미사 배열 : 어떤 문자열에 대해서 접미사는 특정 인덱스부터 시작하는 문자열을 의미합니다. 예를 들어, "banana"의 모든 접미사는 "banana", "anana", "nana", "ana", "na", "a"입니다.
문자열 my_string이 매개변수로 주어질 때, my_string의 모든 접미사를 사전순으로 정렬한 문자열 배열을 return 하는 solution 함수를 작성해 주세요.
=> [34일차] 최주희 / 접미사 배열

3st/Jaehee/홀짝에 따라 다른 값 반환하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181935?language=java
| 홀짝에 따라 다른 값 반환하기 | 프로그래머스 | Level.0|
<hr/>
- 홀짝에 따라 다른 값 반환하기: 양의 정수 n이 매개변수로 주어질 때, n이 홀수라면 n 이하의 홀수인 모든 양의 정수의 합을 return 하고 n이 짝수라면 n 이하의 짝수인 모든 양의 정수의 제곱의 합을 return 하는 solution 함수를 작성해 주세요.
=> [34일차] 이제희/홀짝에 따라 다른 값 반환하기

2st/Riyeon/크기가 작은 부분문자열.py
| 크기가 작은 부분문자열 | 프로그래머스 | Level.1 |
<hr/>
- 크기가 작은 부분문자열 : 숫자로 이루어진 문자열 t와 p가 주어질 때, t에서 p와 길이가 같은 부분문자열 중에서, 이 부분문자열이 나타내는 수가 p가 나타내는 수보다 작거나 같은 것이 나오는 횟수를 return하는 함수 solution을 완성하세요.
=> [129일차] 김리연 / 크기가 작은 부분문자열

2st/Riyeon/이상한 문자 만들기.py
| 이상한 문자 만들기 | 프로그래머스 | Level.1 |
<hr/>
- 이상한 문자 만들기 : 문자열 s는 한 개 이상의 단어로 구성되어 있습니다. 각 단어는 하나 이상의 공백문자로 구분되어 있습니다. 각 단어의 짝수번째 알파벳은 대문자로, 홀수번째 알파벳은 소문자로 바꾼 문자열을 리턴하는 함수, solution을 완성하세요.
=> [130일차] 김리연 / 이상한 문자 만들기

3st/Juhee/접미사인지 확인하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181908
| 접미사인지 확인하기 | 프로그래머스 | Level.0 |
<hr/>
- 접미사인지 확인하기 : 어떤 문자열에 대해서 접미사는 특정 인덱스부터 시작하는 문자열을 의미합니다. 예를 들어, "banana"의 모든 접미사는 "banana", "anana", "nana", "ana", "na", "a"입니다.
문자열 my_string과 is_suffix가 주어질 때, is_suffix가 my_string의 접미사라면 1을, 아니면 0을 return 하는 solution 함수를 작성해 주세요.
=> [35일차] 최주희 / 접미사인지 확인하기

3st/Jaehee/배열 두 배 만들기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120809
| 배열 두 배 만들기 | 프로그래머스 |  Level.0|
<hr/>
- 배열 두 배 만들기 : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 각 원소에 두배한 원소를 가진 배열을 return하도록 solution 함수를 완성해주세요.
=> [35일차] 이제희/배열 두 배 만들기

3st/Jaeyoung/자연수 뒤집어 배열로 만들기.js
| 자연수 뒤집어 배열로 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 자연수 뒤집어 배열로 만들기 : 자연수 n을 뒤집어 각 자리 숫자를 원소로 가지는 배열 형태로 리턴해주세요. 예를들어 n이 12345이면 [5,4,3,2,1]을 리턴합니다.
=> [35일차] 박재영 / 자연수 뒤집어 배열로 만들기

3st/Juhee/세로 읽기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181904
| 세로 읽기 | 프로그래머스 | Level.0 |
<hr/>
- 세로 읽기 : 문자열 my_string과 두 정수 m, c가 주어집니다. my_string을 한 줄에 m 글자씩 가로로 적었을 때 왼쪽부터 세로로 c번째 열에 적힌 글자들을 문자열로 return 하는 solution 함수를 작성해 주세요.
=> [36일차] 최주희 / 세로 읽기

3st/Jaeyoung/문자열 반복해서 출력하기.java
| 문자열 반복해서 출력하기 | 프로그래머스 | Level.0 |
<hr/>
=> [36일차] 박재영 / 문자열 반복해서 출력하기

3st/Jaehee/나이 출력.java
https://school.programmers.co.kr/learn/courses/30/lessons/120820
<hr/>
- 나이 출력 : 머쓱이는 선생님이 몇 년도에 태어났는지 궁금해졌습니다. 2022년 기준 선생님의 나이 age가 주어질 때, 선생님의 출생 연도를 return 하는 solution 함수를 완성해주세요
=> [36일차] 이제희/나이 출력

3st/Seojun/삼각형의 완성조건(1).java
| 삼각형의 완성조건 (1) | 프로그래머스 | Level.0 |
<hr/>
- 삼각형의 완성조건 (1) : 선분 세 개로 삼각형을 만들기 위해서는 다음과 같은 조건을 만족해야 합니다.
가장 긴 변의 길이는 다른 두 변의 길이의 합보다 작아야 합니다.
삼각형의 세 변의 길이가 담긴 배열 sides이 매개변수로 주어집니다. 세 변으로 삼각형을 만들 수 있다면 1, 만들 수 없다면 2를 return하도록 solution 함수를 완성해주세요.
=> [36일차] 김서준 /삼각형의 완성조건 (1)

2st/Riyeon/숫자의 표현.py
| 숫자의 표현 | 프로그래머스 | Level.2 |
<hr/>
- 숫자의 표현 : 자연수 n이 매개변수로 주어질 때, 연속된 자연수들로 n을 표현하는 방법의 수를 return하는 solution를 완성해주세요.
=> [131일차] 김리연 / 숫자의 표현

3st/Seojun/짝수는 싫어요.java
|짝수는 싫어요| 프로그래머스 | Level.0 |
<hr/>
=> [37일차] 김서준 / 짝수는 싫어요

3st/Juhee/세로 읽기.java, 3st/Juhee/첫 번째로 나오는 음수.java
https://school.programmers.co.kr/learn/courses/30/lessons/181896
<hr/>
=> [37일차] 최주희 / 첫 번째로 나오는 음수

3st/Jaehee/세로 읽기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181904
| 세로 읽기 | 프로그래머스 |  Level.0|
<hr/>
- 세로 읽기 : 문자열 my_string과 두 정수 m, c가 주어집니다. my_string을 한 줄에 m 글자씩 가로로 적었을 때 왼쪽부터 세로로 c번째 열에 적힌 글자들을 문자열로 return 하는 solution 함수를 작성해 주세요.
=> [37일] 이제희/세로 읽기

2st/Riyeon/삼총사.py
| 삼총사 | 프로그래머스 | Level.1 |
<hr/>
- 삼총사 : 한국중학교에 다니는 학생들은 각자 정수 번호를 갖고 있습니다. 이 학교 학생 3명의 정수 번호를 더했을 때 0이 되면 3명의 학생은 삼총사라고 합니다. 예를 들어, 5명의 학생이 있고, 각각의 정수 번호가 순서대로 -2, 3, 0, 2, -5일 때, 첫 번째, 세 번째, 네 번째 학생의 정수 번호를 더하면 0이므로 세 학생은 삼총사입니다. 또한, 두 번째, 네 번째, 다섯 번째 학생의 정수 번호를 더해도 0이므로 세 학생도 삼총사입니다. 따라서 이 경우 한국중학교에서는 두 가지 방법으로 삼총사를 만들 수 있습니다.
한국중학교 학생들의 번호를 나타내는 정수 배열 number가 매개변수로 주어질 때, 학생들 중 삼총사를 만들 수 있는 방법의 수를 return 하도록 solution 함수를 완성하세요.
=> [132일차] 김리연 / 삼총사

3st/Jaehee/최빈값 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120812
| 최빈값 구하기 | 프로그래머스 |  Level.0 |
<hr/>
=> [38일차] 이제희/최빈값 구하기

3st/Jaeyoung/카운트 업.java
=> [38일차] 박재영 / 카운트 업

3st/Juhee/순서 바꾸기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181891
<hr/>
- 순서 바꾸기 : 정수 리스트 num_list와 정수 n이 주어질 때, num_list를 n 번째 원소 이후의 원소들과 n 번째까지의 원소들로 나눠 n 번째 원소 이후의 원소들을 n 번째까지의 원소들 앞에 붙인 리스트를 return하도록 solution 함수를 완성해주세요.
=> [39일차] 최주희 / 순서 바꾸기

3st/Seojun/A+B.java
| A+B | 백준 | 브론즈 V |
<hr/>
- A+B : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [BJ] A+B / A+B

2st/Riyeon/최소직사각형.py
| 최소직사각형 | 프로그래머스 | Level.1 |
<hr/>
- 최소직사각형 : 모든 명함의 가로 길이와 세로 길이를 나타내는 2차원 배열 sizes가 매개변수로 주어집니다. 모든 명함을 수납할 수 있는 가장 작은 지갑을 만들 때, 지갑의 크기를 return 하도록 solution 함수를 완성해주세요.
=> [134일차] 김리연 / 최소직사각형

3st/Juhee/n 번째 원소까지
https://school.programmers.co.kr/learn/courses/30/lessons/181889
<hr/>
- n 번째 원소까지 : 정수 리스트 num_list와 정수 n이 주어질 때, num_list의 첫 번째 원소부터 n 번째 원소까지의 모든 원소를 담은 리스트를 return하도록 solution 함수를 완성해주세요.
=> [40일차] 최주희 / n 번째 원소까지

3st/Seojun/문자 리스트를 문자열로 변환하기.java
=> [PGS] 문자 리스트를 문자열로 변환하기 / level.0

2st/Riyeon/피보나치 수.py
| 피보나치 수 | 프로그래머스 | Level.2 |
<hr/>
- 피보나치 수 : 2 이상의 n이 입력되었을 때, n번째 피보나치 수를 1234567으로 나눈 나머지를 리턴하는 함수, solution을 완성해 주세요.
=> [135일차] 김리연 / 피보나치 수

2st/Riyeon/시저 암호.py
| 시저 암호 | 프로그래머스 | Level.1 |
<hr/>
- 시저 암호 : 어떤 문장의 각 알파벳을 일정한 거리만큼 밀어서 다른 알파벳으로 바꾸는 암호화 방식을 시저 암호라고 합니다. 예를 들어 "AB"는 1만큼 밀면 "BC"가 되고, 3만큼 밀면 "DE"가 됩니다. "z"는 1만큼 밀면 "a"가 됩니다. 문자열 s와 거리 n을 입력받아 s를 n만큼 민 암호문을 만드는 함수, solution을 완성해 보세요.
=> [136일차] 김리연 / 시저 암호

3st/Seojun/카운트 업.java
=> [41알차] 김서준 / 카운트 업

3st/Juhee/n개 간격의 원소들.java
https://school.programmers.co.kr/learn/courses/30/lessons/181888
<hr/>
=> [41일차] 최주희 / n개 간격의 원소들

3st/Jaehee/중앙값 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120811
| 중앙값 구하기 |  프로그래머스 |  Level.0 |
<hr/>
=> [41일] 이제희/중앙값 구하기

3st/Jaeyoung/버스.py
https://school.programmers.co.kr/learn/courses/30/lessons/340201
| [PCCE 기출문제] 7번 버스 | 프로그래머스 | Level.0 |
<hr/>
- [PCCE 기출문제] 7번 버스 : 영진이는 약속장소에 가기 위해 버스를 타려고 합니다. 버스에는 좌석이 총 seat개만큼 있습니다. 영진이는 버스 좌석에 앉아서 갈 수 있을지 궁금해합니다. 기점에서 출발한 버스가 영진이가 기다리는 정거장에 도착하기 전에 방문하는 각 정거장에서 승/하차한 승객 정보가 주어질 때, 영진이가 버스에 탄 순간 빈 좌석은 몇 개인지 구해주세요. 영진이가 기다리는 정거장에서는 영진이가 제일 먼저 버스에 탑승하며, 이전 정거장에서 버스에 탑승한 승객들은 남는 좌석이 있다면 항상 앉는다고 가정합니다. 또, 기점에서 출발하는 버스에는 승객이 0명 타고 있습니다.
예를 들어 다음은 좌석이 5개인 버스에 각 정거장에서 승/하차한 승객 정보를 나타냅니다. 영진이는 4번 정거장에서 기다리고 있으며, "On"은 승차한 승객, "Off"는 하차한 승객을 의미합니다.
=> [41]  박재영 / [PCCE 기출문제] 7번 버스

3st/Hyeonseo/programmer/x만큼 간격이 있는 n개의 숫자.java, 3st/Hyeonseo/programmer/문자 반복 출력하기.java
| 조현서 | 프로그래머스 | Level.0 |
<hr/>
=> [42일차] 조현서 / 홀짝 구분하기

3st/Jaeyoung/[PCCP 기출문제] 1번 동영상 재생기.py
| [PCCP 기출문제] 1번 동영상 재생기 | 프로그래머스 | Level.1 |
<hr/>
- [PCCP 기출문제] 1번 동영상 재생기 : 당신은 동영상 재생기를 만들고 있습니다. 당신의 동영상 재생기는 10초 전으로 이동, 10초 후로 이동, 오프닝 건너뛰기 3가지 기능을 지원합니다. 각 기능이 수행하는 작업은 다음과 같습니다.
10초 전으로 이동: 사용자가 "prev" 명령을 입력할 경우 동영상의 재생 위치를 현재 위치에서 10초 전으로 이동합니다. 현재 위치가 10초 미만인 경우 영상의 처음 위치로 이동합니다. 영상의 처음 위치는 0분 0초입니다.
10초 후로 이동: 사용자가 "next" 명령을 입력할 경우 동영상의 재생 위치를 현재 위치에서 10초 후로 이동합니다. 동영상의 남은 시간이 10초 미만일 경우 영상의 마지막 위치로 이동합니다. 영상의 마지막 위치는 동영상의 길이와 같습니다.
오프닝 건너뛰기: 현재 재생 위치가 오프닝 구간(op_start ≤ 현재 재생 위치 ≤ op_end)인 경우 자동으로 오프닝이 끝나는 위치로 이동합니다.
동영상의 길이를 나타내는 문자열 video_len, 기능이 수행되기 직전의 재생위치를 나타내는 문자열 pos, 오프닝 시작 시각을 나타내는 문자열 op_start, 오프닝이 끝나는 시각을 나타내는 문자열 op_end, 사용자의 입력을 나타내는 1차원 문자열 배열 commands가 매개변수로 주어집니다. 이때 사용자의 입력이 모두 끝난 후 동영상의 위치를 "mm:ss" 형식으로 …
=> [42일차] 박재영 / [PCCP 기출문제] 1번 동영상 재생기

2st/Riyeon/가장 가까운 같은 글자.py
| 가장 가까운 같은 글자 | 프로그래머스 | Level.1 |
<hr/>
- 가장 가까운 같은 글자 : 문자열 s가 주어졌을 때, s의 각 위치마다 자신보다 앞에 나왔으면서, 자신과 가장 가까운 곳에 있는 같은 글자가 어디 있는지 알고 싶습니다.
예를 들어, s="banana"라고 할 때,  각 글자들을 왼쪽부터 오른쪽으로 읽어 나가면서 다음과 같이 진행할 수 있습니다.
b는 처음 나왔기 때문에 자신의 앞에 같은 글자가 없습니다. 이는 -1로 표현합니다.
a는 처음 나왔기 때문에 자신의 앞에 같은 글자가 없습니다. 이는 -1로 표현합니다.
n은 처음 나왔기 때문에 자신의 앞에 같은 글자가 없습니다. 이는 -1로 표현합니다.
a는 자신보다 두 칸 앞에 a가 있습니다. 이는 2로 표현합니다.
n도 자신보다 두 칸 앞에 n이 있습니다. 이는 2로 표현합니다.
a는 자신보다 두 칸, 네 칸 앞에 a가 있습니다. 이 중 가까운 것은 두 칸 앞이고, 이는 2로 표현합니다.
따라서 최종 결과물은 [-1, -1, -1, 2, 2, 2]가 됩니다.
문자열 s이 주어질 때, 위와 같이 정의된 연산을 수행하는 함수 solution을 완성해주세요.
=> [137일차] 김리연 / 가장 가까운 같은 글자

3st/Juhee/n보다 커질 때까지 더하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181884
<hr/>
- n보다 커질 때까지 더하기 : 정수 배열 numbers와 정수 n이 매개변수로 주어집니다. numbers의 원소를 앞에서부터 하나씩 더하다가 그 합이 n보다 커지는 순간 이때까지 더했던 원소들의 합을 return 하는 solution 함수를 작성해 주세요.
=> [42일차] 최주희 / n보다 커질 때까지 더하기

3st/Seojun/직각삼각형 출력하기.java
| 각삼각형 출력하기 | 프로그래머스 |Level.0|
<hr/>
- 각삼각형 출력하기 : "*"의 높이와 너비를 1이라고 했을 때, "*"을 이용해 직각 이등변 삼각형을 그리려고합니다. 정수 n 이 주어지면 높이와 너비가 n 인 직각 이등변 삼각형을 출력하도록 코드를 작성해보세요.
=> [42일차] 김서준 / 각삼각형 출력하기

3st/Jaehee/피자 나눠 먹기 (1).java
| 피자 나눠 먹기 (1) | 프로그래머스 | Level.0|
<hr/>
=> [42일] 이제희/피자 나눠 먹기 (1)

3st/Seojun/편지.java
<hr/>
- 편 : 머쓱이는 할머니께 생신 축하 편지를 쓰려고 합니다. 할머니가 보시기 편하도록 글자 한 자 한 자를 가로 2cm 크기로 적으려고 하며, 편지를 가로로만 적을 때, 축하 문구 message를 적기 위해 필요한 편지지의 최소 가로길이를 return 하도록 solution 함수를 완성해주세요.
=> [42일차] 김서준 / 편지

3st/Juhee/5명씩.java
https://school.programmers.co.kr/learn/courses/30/lessons/181886
<hr/>
=> [43일차] 최주희 / 5명씩

3st/Jaehee/문자 출력.java
https://school.programmers.co.kr/learn/courses/30/lessons/340207
| 문자 출력 |프로그래머스 |  Level.0 |
<hr/>
- 문자 출력 : 주어진 코드는 변수에 데이터를 저장하고 출력하는 코드입니다. 아래와 같이 출력되도록 빈칸을 채워 코드를 완성해 주세요.
=> [43일] 이제희/문자 출력

3st/Hyeonseo/com/n의 배수 고르기.java, 3st/Hyeonseo/com/문자열안에 문자열.java, 3st/Hyeonseo/com/양꼬치.java, 3st/Hyeonseo/com/자릿수 더하기.java, 3st/Hyeonseo/com/제곱수 판별하기.java, 3st/Hyeonseo/com/중앙값 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120830
<hr/>
=> [43일차] 조현서 / 양꼬치

2st/Riyeon/두 개 뽑아서 더하기.py
| 두 개 뽑아서 더하기 | 프로그래머스 | Level.1 |
<hr/>
- 두 개 뽑아서 더하기 : 정수 배열 numbers가 주어집니다. numbers에서 서로 다른 인덱스에 있는 두 개의 수를 뽑아 더해서 만들 수 있는 모든 수를 배열에 오름차순으로 담아 return 하도록 solution 함수를 완성해주세요.
=> [138일차] 김리연 / 두 개 뽑아서 더하기

2st/Riyeon/콜라 문제.py
| 콜라 문제 | 프로그래머스 | Level.1 |
<hr/>
- 콜라 문제 : 문제를 열심히 풀던 상빈이는 일반화된 콜라 문제를 생각했습니다. 이 문제는 빈 병 a개를 가져다주면 콜라 b병을 주는 마트가 있을 때, 빈 병 n개를 가져다주면 몇 병을 받을 수 있는지 계산하는 문제입니다. 기존 콜라 문제와 마찬가지로, 보유 중인 빈 병이 a개 미만이면, 추가적으로 빈 병을 받을 순 없습니다. 상빈이는 열심히 고심했지만, 일반화된 콜라 문제의 답을 찾을 수 없었습니다. 상빈이를 도와, 일반화된 콜라 문제를 해결하는 프로그램을 만들어 주세요.
콜라를 받기 위해 마트에 주어야 하는 병 수 a, 빈 병 a개를 가져다 주면 마트가 주는 콜라 병 수 b, 상빈이가 가지고 있는 빈 병의 개수 n이 매개변수로 주어집니다. 상빈이가 받을 수 있는 콜라의 병 수를 return 하도록 solution 함수를 작성해주세요.
=> [139일차] 김리연 / 콜라 문제

3st/Seojun/문자열로 변화.java
| 문자열로 변환 | 프로그래머스 | Level.0 |
<hr/>
- 문자열로 변환 : 정수 n이 주어질 때, n을 문자열로 변환하여 return하도록 solution 함수를 완성해주세요.
=> [44일차] 김서준 / 문자열로 변환

3st/Jaehee/A 강조하기.groovy
https://school.programmers.co.kr/learn/courses/30/lessons/181874
| A 강조하기 | 프로그래머스 |  Level.0 |
<hr/>
=> [44일차] 이제희/A 강조하기

3st/Jaeyoung/[PCCE 기출문제] 10번 공원.java
https://school.programmers.co.kr/learn/courses/30/lessons/340198
| [PCCE 기출문제] 10번 공원 | 프로그래머스 | Level.1 |
<hr/>
- [PCCE 기출문제] 10번 공원 : 지민이는 다양한 크기의 정사각형 모양 돗자리를 가지고 공원에 소풍을 나왔습니다. 공원에는 이미 돗자리를 깔고 여가를 즐기는 사람들이 많아 지민이가 깔 수 있는 가장 큰 돗자리가 어떤 건지 확인하려 합니다. 예를 들어 지민이가 가지고 있는 돗자리의 한 변 길이가 5, 3, 2 세 종류이고, 사람들이 다음과 같이 앉아 있다면 지민이가 깔 수 있는 가장 큰 돗자리는 3x3 크기입니다.
지민이가 가진 돗자리들의 한 변의 길이들이 담긴 정수 리스트 mats, 현재 공원의 자리 배치도를 의미하는 2차원 문자열 리스트 park가 주어질 때 지민이가 깔 수 있는 가장 큰 돗자리의 한 변 길이를 return 하도록 solution 함수를 완성해 주세요. 아무런 돗자리도 깔 수 없는 경우 -1을 return합니다.
=> [44일차] 박재영 / [PCCE 기출문제] 10번 공원

3st/Juhee/할 일 목록.java
https://school.programmers.co.kr/learn/courses/30/lessons/181885
<hr/>
=> [45일차] 최주희 / 할 일 목록

3st/Seojun/문자열을 정수로 변환하기.java
<hr/>
- 문자열을 정수로 변환하기 : 숫자로만 이루어진 문자열 n_str이 주어질 때, n_str을 정수로 변환하여 return하도록 solution 함수를 완성해주세요.
=> [45일차] 김서준 / 문자열을 정수로 변환하기

3st/Jaeyoung/[PCCP 기출문제] 1번 붕대 감기.java
https://school.programmers.co.kr/learn/courses/30/lessons/250137?language=java
| [PCCP 기출문제] 1번 붕대 감기 | 프로그래머스 | Level.1 |
<hr/>
- [PCCP 기출문제] 1번 붕대 감기 : 어떤 게임에는 붕대 감기라는 기술이 있습니다.
붕대 감기는 t초 동안 붕대를 감으면서 1초마다 x만큼의 체력을 회복합니다. t초 연속으로 붕대를 감는 데 성공한다면 y만큼의 체력을 추가로 회복합니다. 게임 캐릭터에는 최대 체력이 존재해 현재 체력이 최대 체력보다 커지는 것은 불가능합니다.
기술을 쓰는 도중 몬스터에게 공격을 당하면 기술이 취소되고, 공격을 당하는 순간에는 체력을 회복할 수 없습니다. 몬스터에게 공격당해 기술이 취소당하거나 기술이 끝나면 그 즉시 붕대 감기를 다시 사용하며, 연속 성공 시간이 0으로 초기화됩니다.
몬스터의 공격을 받으면 정해진 피해량만큼 현재 체력이 줄어듭니다. 이때, 현재 체력이 0 이하가 되면 캐릭터가 죽으며 더 이상 체력을 회복할 수 없습니다.
당신은 붕대감기 기술의 정보, 캐릭터가 가진 최대 체력과 몬스터의 공격 패턴이 주어질 때 캐릭터가 끝까지 생존할 수 있는지 궁금합니다.
붕대 감기 기술의 시전 시간, 1초당 회복량, 추가 회복량을 담은 1차원 정수 배열 bandage와 최대 체력을 의미하는 정수 health, 몬스터의 공격 시간과 피해량을 담은 2차원 정수 배열 attacks가 매개변수로 주어집니다. 모든 공격이 …
=> [45일차] 박재영 / [PCCP 기출문제] 1번 붕대 감기

2st/Riyeon/문자열 내 마음대로 정렬하기.py
| 문자열 내 마음대로 정렬하기 | 프로그래머스 | Level.1 |
<hr/>
- 문자열 내 마음대로 정렬하기 : 문자열로 구성된 리스트 strings와, 정수 n이 주어졌을 때, 각 문자열의 인덱스 n번째 글자를 기준으로 오름차순 정렬하려 합니다. 예를 들어 strings가 ["sun", "bed", "car"]이고 n이 1이면 각 단어의 인덱스 1의 문자 "u", "e", "a"로 strings를 정렬합니다.
=> [140일차] 김리연 / 문자열 내 마음대로 정렬하기

3st/Juhee/원하는 문자열 찾기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181878
| 원하는 문자열 찾기 | 프로그래머스 | Level.0 |
<hr/>
- 원하는 문자열 찾기 : 알파벳으로 이루어진 문자열 myString과 pat이 주어집니다. myString의 연속된 부분 문자열 중 pat이 존재하면 1을 그렇지 않으면 0을 return 하는 solution 함수를 완성해 주세요.
단, 알파벳 대문자와 소문자는 구분하지 않습니다.
=> [46일차] 최주희 / 원하는 문자열 찾기

3st/Jaehee/A 강조하기.java, 3st/Jaehee/배열 뒤집기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120821
| 배열 뒤집기|프로그래머스 | Level.0 |
<hr/>
- 배열 뒤집기: 정수가 들어 있는 배열 num_list가 매개변수로 주어집니다. num_list의 원소의 순서를 거꾸로 뒤집은 배열을 return하도록 solution 함수를 완성해주세요.
=> [46일] 이제희/배열 뒤집기

3st/Seojun/n보다 커질 때까지 더하기.java
<hr/>
- n보다 커질 때까지 더하기 : 정수 배열 numbers와 정수 n이 매개변수로 주어집니다. numbers의 원소를 앞에서부터 하나씩 더하다가 그 합이 n보다 커지는 순간 이때까지 더했던 원소들의 합을 return 하는 solution 함수를 작성해 주세요.
=> [46일차] 김서준 / n보다 커질 때까지 더하기

2st/Riyeon/추억 점수.py
| 추억 점수 | 프로그래머스 | Level.1 |
<hr/>
- 추억 점수 : 사진들을 보며 추억에 젖어 있던 루는 사진별로 추억 점수를 매길려고 합니다. 사진 속에 나오는 인물의 그리움 점수를 모두 합산한 값이 해당 사진의 추억 점수가 됩니다. 예를 들어 사진 속 인물의 이름이 ["may", "kein", "kain"]이고 각 인물의 그리움 점수가 [5점, 10점, 1점]일 때 해당 사진의 추억 점수는 16(5 + 10 + 1)점이 됩니다. 다른 사진 속 인물의 이름이 ["kali", "mari", "don", "tony"]이고 ["kali", "mari", "don"]의 그리움 점수가 각각 [11점, 1점, 55점]]이고, "tony"는 그리움 점수가 없을 때, 이 사진의 추억 점수는 3명의 그리움 점수를 합한 67(11 + 1 + 55)점입니다.
그리워하는 사람의 이름을 담은 문자열 배열 name, 각 사람별 그리움 점수를 담은 정수 배열 yearning, 각 사진에 찍힌 인물의 이름을 담은 이차원 문자열 배열 photo가 매개변수로 주어질 때, 사진들의 추억 점수를 photo에 주어진 순서대로 배열에 담아 return하는 solution 함수를 완성해주세요.
=> [141일차] 김리연 / 추억 점수

3st/Jaehee/문자열 뒤집기1.java
https://school.programmers.co.kr/learn/courses/30/lessons/120822
<hr/>
=> [47일] 이제희/문자열 뒤집기

2st/Riyeon/명예의 전당 (1).py
| 명예의 전당 (1) | 프로그래머스 | Level.1 |
<hr/>
- 명예의 전당 (1) : "명예의 전당"이라는 TV 프로그램에서는 매일 1명의 가수가 노래를 부르고, 시청자들의 문자 투표수로 가수에게 점수를 부여합니다. 매일 출연한 가수의 점수가 지금까지 출연 가수들의 점수 중 상위 k번째 이내이면 해당 가수의 점수를 명예의 전당이라는 목록에 올려 기념합니다. 즉 프로그램 시작 이후 초기에 k일까지는 모든 출연 가수의 점수가 명예의 전당에 오르게 됩니다. k일 다음부터는 출연 가수의 점수가 기존의 명예의 전당 목록의 k번째 순위의 가수 점수보다 더 높으면, 출연 가수의 점수가 명예의 전당에 오르게 되고 기존의 k번째 순위의 점수는 명예의 전당에서 내려오게 됩니다.
명예의 전당 목록의 점수의 개수 k, 1일부터 마지막 날까지 출연한 가수들의 점수인 score가 주어졌을 때, 매일 발표된 명예의 전당의 최하위 점수를 return하는 solution 함수를 완성해주세요.
=> [142일차] 김리연 / 명예의 전당 (1)

3st/Juhee/길이에 따른 연산.java, 3st/Juhee/조건에 맞게 수열 변환하기 1.java
| 길이에 따른 연산 | 프로그래머스 | Level.0 |
<hr/>
=> [48일차] 최주희 / 길이에 따른 연산

3st/Jaehee/배열의 평균값.java
https://school.programmers.co.kr/learn/courses/30/lessons/120817
| 배열의 평균값| 프로그래머스 | Level.0 |
<hr/>
- 배열의 평균값: 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소의 평균값을 return하도록 solution 함수를 완성해주세요.
=> [48일] 이제희/배열의 평균값

2st/Yeonwoo/Python 개발자 찾기.sql
| Python 개발자 찾기 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/276013) |
<hr/>
- Python 개발자 찾기 : DEVELOPER_INFOS 테이블은 개발자들의 프로그래밍 스킬 정보를 담은 테이블입니다. DEVELOPER_INFOS 테이블 구조는 다음과 같으며, ID, FIRST_NAME, LAST_NAME, EMAIL, SKILL_1, SKILL_2, SKILL_3는 각각 ID, 이름, 성, 이메일, 첫 번째 스킬, 두 번째 스킬, 세 번째 스킬을 의미합니다. DEVELOPER_INFOS 테이블에서 Python 스킬을 가진 개발자의 정보를 조회하려 합니다. Python 스킬을 가진 개발자의 ID, 이메일, 이름, 성을 조회하는 SQL 문을 작성해 주세요.
결과는 ID를 기준으로 오름차순 정렬해 주세요.
=> [143일차] 채연우 / Python 개발자 찾기

2st/Riyeon/K번째수.py
| K번째수 | 프로그래머스 | Level.1 |
<hr/>
- K번째수 : 배열 array의 i번째 숫자부터 j번째 숫자까지 자르고 정렬했을 때, k번째에 있는 수를 구하려 합니다.
예를 들어 array가 [1, 5, 2, 6, 3, 7, 4], i = 2, j = 5, k = 3이라면, array의 2번째부터 5번째까지 자르면 [5, 2, 6, 3]입니다. 배열을 정렬하면 [2, 3, 5, 6]입니다. 배열의 3번째 숫자는 5입니다.
배열 array, [i, j, k]를 원소로 가진 2차원 배열 commands가 매개변수로 주어질 때, commands의 모든 원소에 대해 앞서 설명한 연산을 적용했을 때 나온 결과를 배열에 담아 return 하도록 solution 함수를 작성해주세요.
=> [143일차] 김리연 / K번째수

3st/Juhee/대문자로 바꾸기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181877
<hr/>
=> [49일차] 최주희 / 대문자로 바꾸기

3st/Seojun/배열의 길이에 따라 다른 연산하기.java
| 배열의 길이에 따라 다른 연산하기 | 프로그래머스 | Level.0 |
<hr/>
=> [48일차] 김서준 / 배열의 길이에 따라 다른 연산하기

3st/Jaehee/9로 나눈 나머지.java
https://school.programmers.co.kr/learn/courses/30/lessons/181914
| 9로 나눈 나머지 |  프로그래머스 | Level.0 |
<hr/>
- /9로 나눈 나머지: 음이 아닌 정수를 9로 나눈 나머지는 그 정수의 각 자리 숫자의 합을 9로 나눈 나머지와 같은 것이 알려져 있습니다.
이 사실을 이용하여 음이 아닌 정수가 문자열 number로 주어질 때, 이 정수를 9로 나눈 나머지를 return 하는 solution 함수를 작성해주세요.
=> [49일] 이제희/9로 나눈 나머지

2st/Riyeon/푸드 파이트 대회.py
| 푸드 파이트 대회 | 프로그래머스 | Level.1 |
<hr/>
- 제목 : 수웅이는 매달 주어진 음식을 빨리 먹는 푸드 파이트 대회를 개최합니다. 이 대회에서 선수들은 1대 1로 대결하며, 매 대결마다 음식의 종류와 양이 바뀝니다. 대결은 준비된 음식들을 일렬로 배치한 뒤, 한 선수는 제일 왼쪽에 있는 음식부터 오른쪽으로, 다른 선수는 제일 오른쪽에 있는 음식부터 왼쪽으로 순서대로 먹는 방식으로 진행됩니다. 중앙에는 물을 배치하고, 물을 먼저 먹는 선수가 승리하게 됩니다.
이때, 대회의 공정성을 위해 두 선수가 먹는 음식의 종류와 양이 같아야 하며, 음식을 먹는 순서도 같아야 합니다. 또한, 이번 대회부터는 칼로리가 낮은 음식을 먼저 먹을 수 있게 배치하여 선수들이 음식을 더 잘 먹을 수 있게 하려고 합니다. 이번 대회를 위해 수웅이는 음식을 주문했는데, 대회의 조건을 고려하지 않고 음식을 주문하여 몇 개의 음식은 대회에 사용하지 못하게 되었습니다.
예를 들어, 3가지의 음식이 준비되어 있으며, 칼로리가 적은 순서대로 1번 음식을 3개, 2번 음식을 4개, 3번 음식을 6개 준비했으며, 물을 편의상 0번 음식이라고 칭한다면, 두 선수는 1번 음식 1개, 2번 음식 2개, 3번 음식 3개씩을 먹게 되므로 음식의 배치는 "1223330333221"이 됩니다. 따라서 1번 음식 1개는 대회에 사용하지 못합니다.
수웅이가 준비한 음식의 양을 칼로리가 적은 순서대로 나타내는 정수 배열 food가 주어졌을 때, 대회를 위한 …
=> [144일차] 김리연 / 푸드 파이트 대회

2st/Riyeon/n진수 게임.java
| n진수 게임 | 프로그래머스 | Level.2 |
<hr/>
- n진수 게임 : 튜브가 활동하는 코딩 동아리에서는 전통적으로 해오는 게임이 있다. 이 게임은 여러 사람이 둥글게 앉아서 숫자를 하나씩 차례대로 말하는 게임인데, 규칙은 다음과 같다.
숫자를 0부터 시작해서 차례대로 말한다. 첫 번째 사람은 0, 두 번째 사람은 1, … 열 번째 사람은 9를 말한다.
10 이상의 숫자부터는 한 자리씩 끊어서 말한다. 즉 열한 번째 사람은 10의 첫 자리인 1, 열두 번째 사람은 둘째 자리인 0을 말한다.
이렇게 게임을 진행할 경우,
0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 0, 1, 1, 1, 2, 1, 3, 1, 4, …
순으로 숫자를 말하면 된다.
한편 코딩 동아리 일원들은 컴퓨터를 다루는 사람답게 이진수로 이 게임을 진행하기도 하는데, 이 경우에는
0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, …
순으로 숫자를 말하면 된다.
이진수로 진행하는 게임에 익숙해져 질려가던 사람들은 좀 더 난이도를 높이기 위해 이진법에서 십육진법까지 모든 진법으로 게임을 진행해보기로 했다. 숫자 게임이 익숙하지 않은 튜브는 게임에 져서 벌칙을 받는 굴욕을 피하기 위해, 자신이 말해야 하는 숫자를 스마트폰에 미리 출력해주는 프로그램을 만들려고 한다. 튜브의 프로그램을 구현하라.
=> [145일차] 김리연 / n진수 게임

3st/Juhee/특정한 문자를 대문자로 바꾸기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181873
| 특정한 문자를 대문자로 바꾸기 | 프로그래머스 | Level.0 |
<hr/>
- 특정한 문자를 대문자로 바꾸기 : 영소문자로 이루어진 문자열 my_string과 영소문자 1글자로 이루어진 문자열 alp가 매개변수로 주어질 때, my_string에서 alp에 해당하는 모든 글자를 대문자로 바꾼 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [50일차] 최주희 / 특정한 문자를 대문자로 바꾸기

3st/Jaehee/옷가게 할인 받기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120818
| 옷가게 할인 받기 | 프로그래머스 | Level.0 |
<hr/>
- 옷가게 할인 받기: 머쓱이네 옷가게는 10만 원 이상 사면 5%, 30만 원 이상 사면 10%, 50만 원 이상 사면 20%를 할인해줍니다.
=> [50일] 이제희/옷가게 할인 받기

3st/Seojun/길이에 따른 연산.java
| 길이에 따른 연산 | 프로그래머스 | Level.0 |
<hr/>
=> [49일차] 김서준 / 길이에 따른 연산

3st/Jaeyoung/[PCCE 기출문제] 6번 물 부족.java, 3st/Jaeyoung/[PCCE 기출문제] 9번 이웃한 칸.java
https://school.programmers.co.kr/learn/courses/30/lessons/250126
| [PCCE 기출문제] 8번 창고 정리 | 프로그래머스 | Level.1 |
<hr/>
- [PCCE 기출문제] 8번 창고 정리 : 선빈이는 게임을 즐기던 중 가지고 있는 물건이 너무 많아 창고 정리를 하기로 했습니다. 선빈이가 보유한 게임 속 창고는 여러 칸으로 나누어져 있고 각 칸에는 물건들이 담겨있습니다. 창고를 정리할 방법을 고민하던 선빈이는 같은 물건이 여러 칸에 나누어 들어있는 것을 발견하고 우선 같은 물건끼리 최대한 겹쳐쌓는 방식으로 창고를 정리하기로 했습니다. 선빈이의 창고에 들어있는 물건의 이름과 개수는 리스트 형태로 주어지며, 한 칸에 겹쳐질 수 있는 물건의 개수에는 제한이 없다고 가정합니다.
예를 들어 창고의 각 칸에 담겨있는 물건의 이름이storage = ["pencil", "pencil", "pencil", "book"], 각 물건의 개수가 num = [2, 4, 3, 1]이라면 연필과 책을 한 칸에 각각 겹쳐 쌓아 간단하게 clean_storage = ["pencil", "book"], clean_num = [9, 1]로 만들 수 있습니다.
pencil book javacpp.jpg
주어진 solution 함수는 정리되기 전 창고의 물건 이름이 담긴 문자열 리스트 storage와 각 물건의 개수가 담긴 정수 리스트 num이 주어질 때, 정리된 창고에서 개수가 가장 많은 물건의 이름을 …
=> [51일차] 박재영 / [PCCE 기출문제] 8번 창고 정리

3st/Juhee/공백으로 구분하기 1.java
https://school.programmers.co.kr/learn/courses/30/lessons/181869
| 공백으로 구분하기 1 | 프로그래머스 | Level.0 |
<hr/>
- 공백으로 구분하기 1 : 단어가 공백 한 개로 구분되어 있는 문자열 my_string이 매개변수로 주어질 때, my_string에 나온 단어를 앞에서부터 순서대로 담은 문자열 배열을 return 하는 solution 함수를 작성해 주세요.
=> [51일차] 최주희 / 공백으로 구분하기 1

3st/Jaehee/문자열을 정수로 변환하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181848
| 문자열을 정수로 변환하기| 프로그래머스 |Level.0 |
<hr/>
- 문자열을 정수로 변환하기: 숫자로만 이루어진 문자열 n_str이 주어질 때, n_str을 정수로 변환하여 return하도록 solution 함수를 완성해주세요.
=> [51일] 이제희/문자열을 정수로 변환하기

3st/Seojun/문자열 곱하기.java
=> [51일차] 김서준 / 문자열 곱하기

2st/Riyeon/k진수에서 소수 개수 구하기.java
| k진수에서 소수 개수 구하기 | 프로그래머스 | Level.2 |
<hr/>
- k진수에서 소수 개수 구하기 : 양의 정수 n이 주어집니다. 이 숫자를 k진수로 바꿨을 때, 변환된 수 안에 아래 조건에 맞는 소수(Prime number)가 몇 개인지 알아보려 합니다.
-0P0처럼 소수 양쪽에 0이 있는 경우
-P0처럼 소수 오른쪽에만 0이 있고 왼쪽에는 아무것도 없는 경우
-0P처럼 소수 왼쪽에만 0이 있고 오른쪽에는 아무것도 없는 경우
-P처럼 소수 양쪽에 아무것도 없는 경우
-단, P는 각 자릿수에 0을 포함하지 않는 소수입니다.
예를 들어, 101은 P가 될 수 없습니다.
예를 들어, 437674을 3진수로 바꾸면 211020101011입니다. 여기서 찾을 수 있는 조건에 맞는 소수는 왼쪽부터 순서대로 211, 2, 11이 있으며, 총 3개입니다. (211, 2, 11을 k진법으로 보았을 때가 아닌, 10진법으로 보았을 때 소수여야 한다는 점에 주의합니다.) 211은 P0 형태에서 찾을 수 있으며, 2는 0P0에서, 11은 0P에서 찾을 수 있습니다.
정수 n과 k가 매개변수로 주어집니다. n을 k진수로 바꿨을 때, 변환된 수 안에서 찾을 수 있는 위 조건에 맞는 소수의 개수를 return 하도록 solution 함수를 완성해 주세요.
=> [146일차] 김리연 / k진수에서 소수 개수 구하기

3st/Jaeyoung/[PCCE 기출문제] 1번 출력.cpp, 3st/Jaeyoung/[PCCE 기출문제] 8번 창고 정리.java
| [PCCE 기출문제] 1번 출력 | 프로그래머스 | Level.0 |
<hr/>
- [PCCE 기출문제] 1번 출력 : 주어진 초기 코드는 변수에 데이터를 저장하고 출력하는 코드입니다. 아래와 같이 출력되도록 빈칸을 채워 코드를 완성해 주세요.
=> [52일차] 박재영 / [PCCE 기출문제] 1번 출력

3st/Jaehee/문자열로 변환.java
https://school.programmers.co.kr/learn/courses/30/lessons/181848
| 문자열을 정수로 변환하기| 프로그래머스 | Level.0 |
<hr/>
- 문자열을 정수로 변환하기 : 정수 n이 주어질 때, n을 문자열로 변환하여 return하도록 solution 함수를 완성해주세요
=> [52일] 이제희/문자열을 정수로 변환하기

3st/Juhee/문자열이 몇 번 등장하는지 세기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181871
| 문자열이 몇 번 등장하는지 세기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열이 몇 번 등장하는지 세기 : 문자열 myString과 pat이 주어집니다. myString에서 pat이 등장하는 횟수를 return 하는 solution 함수를 완성해 주세요.
=> [52일차] 최주희 / 문자열이 몇 번 등장하는지 세기

2st/Riyeon/지폐 접기.java
| 지폐 접기 | 프로그래머스 | Level.1 |
<hr/>
- 지폐 접기 : 민수는 다양한 지폐를 수집하는 취미를 가지고 있습니다. 지폐마다 크기가 달라 지갑에 넣으려면 여러 번 접어서 넣어야 합니다. 예를 들어 지갑의 크기가 30 * 15이고 지폐의 크기가 26 * 17이라면 한번 반으로 접어 13 * 17 크기로 만든 뒤 90도 돌려서 지갑에 넣을 수 있습니다. 지폐를 접을 때는 다음과 같은 규칙을 지킵니다.
1. 지폐를 접을 때는 항상 길이가 긴 쪽을 반으로 접습니다. 
2. 접기 전 길이가 홀수였다면 접은 후 소수점 이하는 버립니다. 
3. 접힌 지폐를 그대로 또는 90도 돌려서 지갑에 넣을 수 있다면 그만 접습니다.
지갑의 가로, 세로 크기를 담은 정수 리스트 wallet과 지폐의 가로, 세로 크기를 담은 정수 리스트 bill가 주어질 때, 지갑에 넣기 위해서 지폐를 최소 몇 번 접어야 하는지 return하도록 solution함수를 완성해 주세요.
=> [147일차] 김리연 / 지폐 접기|

3st/Seojun/문자열 뒤집기.java
=> [53일차] 김서준 / 문자열 뒤집기

3st/Juhee/배열 만들기 3.java
https://school.programmers.co.kr/learn/courses/30/lessons/181895
| 배열 만들기 3 | 프로그래머스 | Level.0 |
<hr/>
- 배열 만들기 3 : 정수 배열 arr와 2개의 구간이 담긴 배열 intervals가 주어집니다.
intervals는 항상 [[a1, b1], [a2, b2]]의 꼴로 주어지며 각 구간은 닫힌 구간입니다. 닫힌 구간은 양 끝값과 그 사이의 값을 모두 포함하는 구간을 의미합니다.
이때 배열 arr의 첫 번째 구간에 해당하는 배열과 두 번째 구간에 해당하는 배열을 앞뒤로 붙여 새로운 배열을 만들어 return 하는 solution 함수를 완성해 주세요.
=> [53일차] 최주희 / 배열 만들기 3

3st/Jaehee/9로 나눈 나머지.java, 3st/Jaehee/정수 찾기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181840
| 정수 찾기| 프로그래머스 | Level.0 |
<hr/>
- 정수 찾기:정수 리스트 num_list와 찾으려는 정수 n이 주어질 때, num_list안에 n이 있으면 1을 없으면 0을 return하도록 solution 함수를 완성해주세요.
=> [53일] 이제희/정수 찾기

2st/Riyeon/실패율.java
| 실패율 | 프로그래머스 | Level.1 |
<hr/>
- 실패율 : 슈퍼 게임 개발자 오렐리는 큰 고민에 빠졌다. 그녀가 만든 프랜즈 오천성이 대성공을 거뒀지만, 요즘 신규 사용자의 수가 급감한 것이다. 원인은 신규 사용자와 기존 사용자 사이에 스테이지 차이가 너무 큰 것이 문제였다.
이 문제를 어떻게 할까 고민 한 그녀는 동적으로 게임 시간을 늘려서 난이도를 조절하기로 했다. 역시 슈퍼 개발자라 대부분의 로직은 쉽게 구현했지만, 실패율을 구하는 부분에서 위기에 빠지고 말았다. 오렐리를 위해 실패율을 구하는 코드를 완성하라.
실패율은 다음과 같이 정의한다.
스테이지에 도달했으나 아직 클리어하지 못한 플레이어의 수 / 스테이지에 도달한 플레이어 수
전체 스테이지의 개수 N, 게임을 이용하는 사용자가 현재 멈춰있는 스테이지의 번호가 담긴 배열 stages가 매개변수로 주어질 때, 실패율이 높은 스테이지부터 내림차순으로 스테이지의 번호가 담겨있는 배열을 return 하도록 solution 함수를 완성하라.
=> [148일차] 김리연 / 실패율

3st/Seojun/피자 나눠머기(1).java
| 피자 나눠 먹기 (1) | 프로그래머스 | Level.0 |
<hr/>
=> [54일차] 김서준 / 피자 나눠 먹기 (1)

2st/Riyeon/닉네임 규칙.java
| 닉네임 규칙 | 프로그래머스 | Level.0 |
<hr/>
- 닉네임 규칙 : 온라인 서비스를 이용하기 위해서 닉네임이 필요합니다. 이때 닉네임이 될 수 있는 조건은 다음과 같습니다.
닉네임의 길이가 4자 이상 8자 이하여야합니다.
닉네임에는 소문자 l과w, 대문자 O와 W를 사용할 수 없습니다.
이외의 영어 대소문자와 숫자는 모두 사용이 가능합니다.
주어진 solution 함수는 사용할 수 없는 닉네임 nickname을 받아 사용할 수 있는 닉네임으로 바꿔주는 함수입니다. 이때 닉네임을 변경하는 규칙은 다음과 같으며 첫 번째 규칙부터 순서대로 적용합니다.
소문자 l을 대문자 I로 변경합니다.
소문자 w를 두 개의 소문자 v, 즉 vv로 변경합니다.
대문자 W를 두 개의 대문자 V, 즉 VV로 변경합니다.
대문자 O를 숫자 0으로 변경합니다.
수정된 닉네임의 길이가 4 미만일 경우 뒤에 소문자 o를 길이가 4가 될때까지 이어붙입니다.
수정된 닉네임의 길이가 8보다 클 경우 8번째 문자까지만 사용합니다.
주어진 solution 함수에는 위의 규칙 중 올바르게 적용되지 않는 것이 있습니다. solution 함수가 올바르게 작동하도록 한 줄을 수정해주세요.
=> [149일차] 김리연 / 닉네임 규칙

3st/Jaehee/아이스 아메리카노.java
https://school.programmers.co.kr/learn/courses/30/lessons/120819
| 아이스 아메리카노| 프로그래머스 | Level.0 |
<hr/>
- 아이스 아메리카노: 머쓱이는 추운 날에도 아이스 아메리카노만 마십니다. 아이스 아메리카노는 한잔에 5,500원입니다. 머쓱이가 가지고 있는 돈 money가 매개변수로 주어질 때, 머쓱이가 최대로 마실 수 있는 아메리카노의 잔 수와 남는 돈을 순서대로 담은 배열을 return 하도록 solution 함수를 완성해보세요.
=> [54일] 이제희/아이스 아메리카노

3st/Juhee/배열에서 문자열 대소문자 변환하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181875
| 배열에서 문자열 대소문자 변환하기 |프로그래머스 | Level.0 |
<hr/>
=> [54일차] 최주희 / 배열에서 문자열 대소문자 변환하기

3st/Jaeyoung/[PCCE 기출문제] 6번 가채점.py
| [PCCE 기출문제] 6번 가채점 | 프로그래머스 | Level.0 |
<hr/>
- [PCCE 기출문제] 6번 가채점 : A반 학생들은 시험이 끝난 뒤 성적이 나오기 전 자기 시험지를 가채점해 보았습니다. 이후에 선생님이 실제 성적을 불러 줄 때 가채점한 점수와 실제 성적이 다른 학생들이 있어 선생님께 문의를 하려고 합니다.
성적을 문의하려는 학생들의 번호가 담긴 정수 리스트 numbers와 가채점한 점수가 성적을 문의하려는 학생 순서대로 담긴 정수 리스트 our_score, 실제 성적이 번호 순서대로 담긴 정수 리스트 score_list가 주어집니다. 주어진 solution 함수는 가채점한 점수가 실제 성적과 동일하다면 "Same"을, 다르다면 "Different"를 순서대로 리스트에 담아 return하는 함수입니다. solution 함수가 올바르게 작동하도록 한 줄을 수정해 주세요.
=> [54일차] 박재영 / [PCCE 기출문제] 6번 가채점

2st/Riyeon/5번 산책.java
| 5번 산책 | 프로그래머스 | Level.0 |
<hr/>
- 5번 산책 : 여름이는 강아지를 산책시키려고 합니다. 여름이는 2차원 좌표평면에서 동/서/남/북 방향으로 1m 단위로 이동하면서 강아지를 산책시킵니다. 산책루트가 담긴 문자열 route가 주어질 때, 도착점의 위치를 return하도록 빈칸을 채워 solution함수를 완성해 주세요.
route는 "N", "S", "E", "W"로 이루어져 있습니다.
"N"은 북쪽으로 1만큼 움직입니다.
"S"는 남쪽으로 1만큼 움직입니다.
북쪽으로 -1만큼 움직인 것과 같습니다.
"E"는 동쪽으로 1만큼 움직입니다.
"W"는 서쪽으로 1만큼 움직입니다.
동쪽으로 -1만큼 움직인 것과 같습니다.
출발점으로부터 [동쪽으로 떨어진 거리, 북쪽으로 떨어진 거리]형태로 강아지의 최종 위치를 구해서 return해야 합니다.
출발점을 기준으로 서쪽, 남쪽에 있는 경우는 동쪽, 북쪽으로 음수만큼 떨어진 것으로 표현합니다.
출발점으로부터 동쪽으로 2, 북쪽으로 3만큼 떨어졌다면 [2, 3]을 return 합니다.
출발점으로부터 서쪽으로 1, 남쪽으로 4만큼 떨어졌다면 [-1, -4]를 return 합니다.
=> [150일차] 김리연 / 5번 산책

3st/Juhee/A 강조하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181874
<hr/>
=> [55일차] 최주희 / A 강조하기

3st/Jaehee/소문자로 바꾸기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181876
| 소문자로 바꾸기| 프로그래머스 | Level.0 |
<hr/>
- 소문자로 바꾸기: 알파벳으로 이루어진 문자열 myString이 주어집니다. 모든 알파벳을 소문자로 변환하여 return 하는 solution 함수를 완성해 주세요.
=> [55일] 이제희/소문자로 바꾸기

3st/Jaeyoung/[PCCE 기출문제] 3번 수 나누기.java
https://school.programmers.co.kr/learn/courses/30/lessons/340205?language=java
| [PCCE 기출문제] 3번 수 나누기 | 프로그래머스 | Level.0 |
<hr/>
- [PCCE 기출문제] 3번 수 나누기 : 2자리 이상의 정수 number가 주어집니다. 주어진 코드는 이 수를 2자리씩 자른 뒤, 자른 수를 모두 더해서 그 합을 출력하는 코드입니다. 코드가 올바르게 작동하도록 한 줄을 수정해 주세요.
=> [56일차] 박재영 / [PCCE 기출문제] 3번 수 나누기

3st/Juhee/숨어있는 숫자의 덧셈 (1).java
https://school.programmers.co.kr/learn/courses/30/lessons/120851
| 숨어있는 숫자의 덧셈 (1) | 프로그래머스 | Level.0 |
<hr/>
- 숨어있는 숫자의 덧셈 (1) : 문자열 my_string이 매개변수로 주어집니다. my_string안의 모든 자연수들의 합을 return하도록 solution 함수를 완성해주세요.
=> [56일차 ] 최주희 / 숨어있는 숫자의 덧셈 (1)

3st/Jaehee/직각삼각형 출력하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120823
| 직각삼각형 출력하기| 프로그래머스 | Level.0 |
<hr/>
- 직각삼각형 출력하기: "*"의 높이와 너비를 1이라고 했을 때, "*"을 이용해 직각 이등변 삼각형을 그리려고합니다. 정수 n 이 주어지면 높이와 너비가 n 인 직각 이등변 삼각형을 출력하도록 코드를 작성해보세요.
=> [56일] 이제희/직각삼각형 출력하기

3st/Juhee/문자열안에 문자열.java
https://school.programmers.co.kr/learn/courses/30/lessons/120908
<hr/>
=> [57일차] 최주희 / 문자열안에 문자열

3st/Jaehee/공백으로 구분하기 1.java
https://school.programmers.co.kr/learn/courses/30/lessons/181869
| 공백으로 구분하기 1 | 프로그래머스 |  Level.0 |
<hr/>
- 공백으로 구분하기 1 : 단어가 공백 한 개로 구분되어 있는 문자열 my_string이 매개변수로 주어질 때, my_string에 나온 단어를 앞에서부터 순서대로 담은 문자열 배열을 return 하는 solution 함수를 작성해 주세요.
=> [57일] 이제희/공백으로 구분하기 1

2st/Riyeon/2번_각도 합치기.java
| 2번_각도 합치기 | 프로그래머스 | Level.0 |
<hr/>
- 2번_각도 합치기 : 일반적으로 두 선분이 이루는 각도는 한 바퀴를 360도로 하여 표현합니다. 따라서 각도에 360의 배수를 더하거나 빼더라도 같은 각을 의미합니다. 예를 들면, 30도와 390도는 같은 각도입니다.
주어진 코드는 각도를 나타내는 두 정수 angle1과 angle2가 주어질 때, 이 두 각의 합을 0도 이상 360도 미만으로 출력하는 코드입니다. 코드가 올바르게 작동하도록 한 줄을 수정해 주세요.
=> [152일차] 김리연 / 2번_각도 합치기

2st/Riyeon/7번_가습기.java
| 7번_가습기 | 프로그래머스 | Level.0 |
<hr/>
- 7번_가습기 : 상우가 사용하는 가습기에는 "auto", "target", "minimum"의 세 가지 모드가 있습니다.  상우가 설정한 가습기의 모드를 나타낸 문자열 mode_type, 현재 공기 중 습도를 나타낸 정수 humidity, 설정값을 나타낸 정수 val_set이 주어질 때 현재 가습기가 몇 단계로 작동 중인지 return하도록 빈칸을 채워 solution 함수를 완성해 주세요.
=> [154일차] 김리연 / 7번_가습기

2st/Riyeon/5번_심폐소생술.java
| 5번_심폐소생술 | 프로그래머스 | Level.0 |
<hr/>
- 5번_심폐소생술 : 주어진 solution 함수는 심폐소생술을 하는 방법의 순서가 담긴 문자열들이 무작위 순서로 담긴 리스트 cpr이 주어질 때 각각의 방법이 몇 번째 단계인지 순서대로 담아 return하는 함수입니다. solution 함수가 올바르게 작동하도록 빈칸을 채워 solution 함수를 완성해 주세요.
=> [155일차] 김리연 / 5번_심폐소생술

2st/Riyeon/3번_수 나누기.java
| 3번_수 나누기 | 프로그래머스 | Level.0 |
<hr/>
- 3번_수 나누기 : 2자리 이상의 정수 number가 주어집니다. 주어진 코드는 이 수를 2자리씩 자른 뒤, 자른 수를 모두 더해서 그 합을 출력하는 코드입니다. 코드가 올바르게 작동하도록 한 줄을 수정해 주세요.
=> [156일차] 김리연 / 3번_수 나누기

2st/Riyeon/1번_문자 출력.java
| 1번_문자 출력 | 프로그래머스 | Level.0 |
<hr/>
- 1번_문자 출력 : 주어진 코드는 변수에 데이터를 저장하고 출력하는 코드입니다. 아래와 같이 출력되도록 빈칸을 채워 코드를 완성해 주세요.
=> [157일차] 김리연 / 1번_문자 출력

3st/Jaehee/대문자로 바꾸기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181877
| 대문자로 바꾸기| 프로그래머스 | Level.0 |
<hr/>
- 대문자로 바꾸기: 알파벳으로 이루어진 문자열 myString이 주어집니다. 모든 알파벳을 대문자로 변환하여 return 하는 solution 함수를 완성해 주세요.
=> [58일]  이제희/대문자로 바꾸기

2st/Riyeon/6번_물 부족.java
| 6번_물 부족 | 프로그래머스 | Level.0 |
<hr/>
- 6번_물 부족 : 현재 저수지에 저장된 물의 양을 나타내는 정수 storage와 지난 달 물 사용량을 나타내는 정수 usage, 월별 물 사용량이 전 달 대비 어떻게 변하는지 저장된 정수 리스트 change가 주어질 때 몇 달 뒤 물이 부족해지는지 return 하도록 solution 함수를 작성하려 합니다. 코드가 올바르게 작동하도록 한 줄을 수정해 solution 함수를 완성해 주세요. 가뭄이 끝날때 까지 저수지의 물이 남아 있다면 -1을 return합니다.
=> [158일차] 김리연 / 6번_물 부족

3st/Jaeyoung/[PCCE 기출문제] 3번 나이 계산.py
https://school.programmers.co.kr/learn/courses/30/lessons/250131?language=python3
| [PCCE 기출문제] 3번 나이 계산 | 프로그래머스 | Level.0 |
<hr/>
- [PCCE 기출문제] 3번 나이 계산 : 나이를 세는 방법은 여러 가지가 있습니다. 그중 한국식 나이는 태어난 순간 1살이 되며 해가 바뀔 때마다 1살씩 더 먹게 됩니다. 연 나이는 태어난 순간 0살이며 해가 바뀔 때마다 1살씩 더 먹게 됩니다. 각각 나이의 계산법은 다음과 같습니다.
한국식 나이 : 현재 연도 - 출생 연도 + 1
연 나이 : 현재 연도 - 출생 연도
출생 연도를 나타내는 정수 year와 구하려는 나이의 종류를 나타내는 문자열 age_type이 주어질 때 2030년에 몇 살인지 출력하도록 빈칸을 채워 코드를 완성해 주세요. age_type이 "Korea"라면 한국식 나이를, "Year"라면 연 나이를 출력합니다.
=> [59일차] 박재영 / [PCCE 기출문제] 3번 나이 계산

3st/Seojun/대문자로 바꾸기.java
<hr/>
- 대문자로 바꾸 : 알파벳으로 이루어진 문자열 myString이 주어집니다. 모든 알파벳을 대문자로 변환하여 return 하는 solution 함수를 완성해 주세요.
=> [59일차] 김서준 / 대문자로 바꾸기

3st/Juhee/배열의 유사도.java
https://school.programmers.co.kr/learn/courses/30/lessons/120903
<hr/>
=> [59일차] 최주희 / 배열의 유사도

3st/Jaehee/정수 부분.java
https://school.programmers.co.kr/learn/courses/30/lessons/181850
| 정수 부분| 프로그래머스 |  Level.0 |
<hr/>
=> [59일]  이제희/정수 부분

3st/Jaeyoung/[PCCE 기출문제] 4번 병과분류.java
https://school.programmers.co.kr/learn/courses/30/lessons/340204?language=java
| [PCCE 기출문제] 4번 병과분류 | 프로그래머스 | Level.0 |
<hr/>
- [PCCE 기출문제] 4번 병과분류 : <html>
<body>
<p style="box-sizing: border-box; padding: 0px; margin: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: 1.8; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-optical-sizing: inherit; …
=> [60일차] 박재영 / [PCCE 기출문제] 4번 병과분류

2st/Riyeon/방문 길이.java
| 방문 길이 | 프로그래머스 | Level.2 |
<hr/>
- 방문 길이 : 게임 캐릭터를 4가지 명령어를 통해 움직이려 합니다. 명령어는 다음과 같습니다.
U: 위쪽으로 한 칸 가기 /  D: 아래쪽으로 한 칸 가기 /  R: 오른쪽으로 한 칸 가기 /  L: 왼쪽으로 한 칸 가기
캐릭터는 좌표평면의 (0, 0) 위치에서 시작합니다. 좌표평면의 경계는 왼쪽 위(-5, 5), 왼쪽 아래(-5, -5), 오른쪽 위(5, 5), 오른쪽 아래(5, -5)로 이루어져 있습니다.
이때, 우리는 게임 캐릭터가 지나간 길 중 캐릭터가 처음 걸어본 길의 길이를 구하려고 합니다. 예를 들어 위의 예시에서 게임 캐릭터가 움직인 길이는 9이지만, 캐릭터가 처음 걸어본 길의 길이는 7이 됩니다. (8, 9번 명령어에서 움직인 길은 2, 3번 명령어에서 이미 거쳐 간 길입니다) 단, 좌표평면의 경계를 넘어가는 명령어는 무시합니다.
명령어가 매개변수 dirs로 주어질 때, 게임 캐릭터가 처음 걸어본 길의 길이를 구하여 return 하는 solution 함수를 완성해 주세요.
=> [159일차] 김리연 / 방문 길이

3st/Jaehee/소인수분해.java
https://school.programmers.co.kr/learn/courses/30/lessons/120852
| 소인수분해| 프로그래머스 |  Level.0 |
<hr/>
- 소인수분해: 소인수분해란 어떤 수를 소수들의 곱으로 표현하는 것입니다. 예를 들어 12를 소인수 분해하면 2 * 2 * 3 으로 나타낼 수 있습니다. 따라서 12의 소인수는 2와 3입니다. 자연수 n이 매개변수로 주어질 때 n의 소인수를 오름차순으로 담은 배열을 return하도록 solution 함수를 완성해주세요.
=> [60일]  이제희/소인수분해

3st/Juhee/문자열 뒤집기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120822
<hr/>
=> [60일차] 최주희 / 문자열 뒤집기

3st/Hyeonseo/programmer/제곱수 판별하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/12935
| 제일 작은 수 제거하기 | 프로그래머스 | Level.1 |
<hr/>
- 제일 작은 수 제거하기 : 정수를 저장한 배열, arr 에서 가장 작은 수를 제거한 배열을 리턴하는 함수, solution을 완성해주세요. 단, 리턴하려는 배열이 빈 배열인 경우엔 배열에 -1을 채워 리턴하세요. 예를들어 arr이 [4,3,2,1]인 경우는 [4,3,2]를 리턴 하고, [10]면 [-1]을 리턴 합니다.
=> [60일차] 조현서 / 제일 작은 수 제거하기

3st/Seojun/소문자로 바꾸기.java
=> [60일차] 김서준 / 소문자로 바꾸기

3st/Jaeyoung/[PCCE 기출문제] 4번 저축.py
https://school.programmers.co.kr/learn/courses/30/lessons/250130
| [PCCE 기출문제] 4번 저축 | 프로그래머스 | Level.0 |
<hr/>
- [PCCE 기출문제] 4번 저축 : 진우는 돈을 모으기 위해 저축을 하려고 합니다. 목표로 하는 금액은 100만 원이며, 첫 달에 일정 금액을 넣은 뒤 70만 원까지는 매월 조금씩 저축하다가 70만 원 이후부터는 월 저축량을 늘려 빠르게 목표 금액을 달성하고자 합니다.
첫 달에 저축하는 금액을 나타내는 정수 start, 두 번째 달 부터 70만 원 이상 모일 때까지 매월 저축하는 금액을 나타내는 정수 before, 100만 원 이상 모일 때 까지 매월 저축하는 금액을 나타내는 정수 after가 주어질 때, 100만 원 이상을 모을 때까지 걸리는 개월 수를 출력하도록 빈칸을 채워 코드를 완성해 주세요.
=> [61일차] 박재영 / [PCCE 기출문제] 4번 저축

2st/Riyeon/땅따먹기.java
| 땅따먹기 | 프로그래머스 | Level.2 |
<hr/>
- 땅따먹기 : 땅따먹기 게임을 하려고 합니다. 땅따먹기 게임의 땅(land)은 총 N행 4열로 이루어져 있고, 모든 칸에는 점수가 쓰여 있습니다. 1행부터 땅을 밟으며 한 행씩 내려올 때, 각 행의 4칸 중 한 칸만 밟으면서 내려와야 합니다. 단, 땅따먹기 게임에는 한 행씩 내려올 때, 같은 열을 연속해서 밟을 수 없는 특수 규칙이 있습니다.
마지막 행까지 모두 내려왔을 때, 얻을 수 있는 점수의 최대값을 return하는 solution 함수를 완성해 주세요.
=> [160일차] 김리연 /  땅따먹기

3st/Jaehee/Hello World.java, 3st/Jaehee/소인수분해.java
https://www.acmicpc.net/submit/2557/82941543
| Hello World | 백준|  Level.0 |
<hr/>
- Hello World : Hello World!를 출력하시오.
=> [61일] 이제희/Hello World

3st/Juhee/자릿수 더하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120906
<hr/>
=> [61일차] 최주희 / 자릿수 더하기

3st/Seojun/배열 뒤집기.java
| 배열 뒤집기 | 프로그래머스 | Level.0 |
<hr/>
- 배열 뒤집기 : 정수가 들어 있는 배열 num_list가 매개변수로 주어집니다. num_list의 원소의 순서를 거꾸로 뒤집은 배열을 return하도록 solution 함수를 완성해주세요.
=> [60일차] 김서준 / 배열 뒤집기

3st/Hyeonseo/programmer/가장 큰 수 찾기.java
https://school.programmers.co.kr/learn/courses/30/lessons/42746
|  가장 큰 수 | 프로그래머스 | Level.2 |
<hr/>
-  가장 큰 수 : 0 또는 양의 정수가 주어졌을 때, 정수를 이어 붙여 만들 수 있는 가장 큰 수를 알아내 주세요.
예를 들어, 주어진 정수가 [6, 10, 2]라면 [6102, 6210, 1062, 1026, 2610, 2106]를 만들 수 있고, 이중 가장 큰 수는 6210입니다.
0 또는 양의 정수가 담긴 배열 numbers가 매개변수로 주어질 때, 순서를 재배치하여 만들 수 있는 가장 큰 수를 문자열로 바꾸어 return 하도록 solution 함수를 작성해주세요.
=> [62일차] 조현서 / 가장 큰 수

2st/Riyeon/주식가격.java
| 주식가격 | 프로그래머스 | Level.2 |
<hr/>
- 주식가격 : 초 단위로 기록된 주식가격이 담긴 배열 prices가 매개변수로 주어질 때, 가격이 떨어지지 않은 기간은 몇 초인지를 return 하도록 solution 함수를 완성하세요.
=> [161일차] 김리연 / 주식가격

3st/Jaeyoung/[PCCE 기출문제] 4번 저축.py, 3st/Jaeyoung/[PCCE 기출문제] 5번 산책.py
| [PCCE 기출문제] 5번 산책 | 프로그래머스 | Level.0 |
<hr/>
- [PCCE 기출문제] 5번 산책 : 여름이는 강아지를 산책시키려고 합니다. 여름이는 2차원 좌표평면에서 동/서/남/북 방향으로 1m 단위로 이동하면서 강아지를 산책시킵니다. 산책루트가 담긴 문자열 route가 주어질 때, 도착점의 위치를 return하도록 빈칸을 채워 solution함수를 완성해 주세요.
route는 "N", "S", "E", "W"로 이루어져 있습니다.
"N"은 북쪽으로 1만큼 움직입니다.
"S"는 남쪽으로 1만큼 움직입니다.
북쪽으로 -1만큼 움직인 것과 같습니다.
"E"는 동쪽으로 1만큼 움직입니다.
"W"는 서쪽으로 1만큼 움직입니다.
동쪽으로 -1만큼 움직인 것과 같습니다.
출발점으로부터 [동쪽으로 떨어진 거리, 북쪽으로 떨어진 거리]형태로 강아지의 최종 위치를 구해서 return해야 합니다.
출발점을 기준으로 서쪽, 남쪽에 있는 경우는 동쪽, 북쪽으로 음수만큼 떨어진 것으로 표현합니다.
출발점으로부터 동쪽으로 2, 북쪽으로 3만큼 떨어졌다면 [2, 3]을 return 합니다.
출발점으로부터 서쪽으로 1, 남쪽으로 4만큼 떨어졌다면 [-1, -4]를 return 합니다.
=> [62일차] 박재영 / [PCCE 기출문제] 5번 산책

3st/Seojun/대문자와소문자.java
=> [62일차] 김서준 / 대문자와 소문자

2st/Yeonwoo/두 수의 차.c++, 2st/Yeonwoo/몫 구하기.c++
| 두 수의 차 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/120803?language=cpp) |
<hr/>
- 두 수의 차 : 정수 num1과 num2가 주어질 때, num1에서 num2를 뺀 값을 return하도록 soltuion 함수를 완성해주세요.
=> [161일차] 채연우 / 두 수의 차

3st/Jaeyoung/가장 많이 받은 선물.java
| 가장 많이 받은 선물 | 프로그래머스 | Level.1 |
<hr/>
- 가장 많이 받은 선물 : 선물을 직접 전하기 힘들 때 카카오톡 선물하기 기능을 이용해 축하 선물을 보낼 수 있습니다. 당신의 친구들이 이번 달까지 선물을 주고받은 기록을 바탕으로 다음 달에 누가 선물을 많이 받을지 예측하려고 합니다.
두 사람이 선물을 주고받은 기록이 있다면, 이번 달까지 두 사람 사이에 더 많은 선물을 준 사람이 다음 달에 선물을 하나 받습니다.
예를 들어 A가 B에게 선물을 5번 줬고, B가 A에게 선물을 3번 줬다면 다음 달엔 A가 B에게 선물을 하나 받습니다.
두 사람이 선물을 주고받은 기록이 하나도 없거나 주고받은 수가 같다면, 선물 지수가 더 큰 사람이 선물 지수가 더 작은 사람에게 선물을 하나 받습니다.
선물 지수는 이번 달까지 자신이 친구들에게 준 선물의 수에서 받은 선물의 수를 뺀 값입니다.
예를 들어 A가 친구들에게 준 선물이 3개고 받은 선물이 10개라면 A의 선물 지수는 -7입니다. B가 친구들에게 준 선물이 3개고 받은 선물이 2개라면 B의 선물 지수는 1입니다. 만약 A와 B가 선물을 주고받은 적이 없거나 정확히 같은 수로 선물을 주고받았다면, 다음 달엔 B가 A에게 선물을 하나 받습니다.
만약 두 사람의 선물 지수도 같다면 다음 달에 선물을 주고받지 않습니다.
위에서 설명한 규칙대로 다음 달에 선물을 주고받을 때, 당신은 선물을 가장 많이 받을 친구가 받을 선물의 수를 알고 싶습니다.
친구들의 이름을 담은 …
=> [63일차] 박재영 / 가장 많이 받은 선물

3st/Seojun/공배수.java
| 공배수 | 프로그래머스 | Level.0 |
<hr/>
=> [63일차] 김서준 / 공배수

3st/Juhee/모음 제거.java, 3st/Juhee/자릿수 더하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120849
<hr/>
- 모음 제거 : 영어에선 a, e, i, o, u 다섯 가지 알파벳을 모음으로 분류합니다. 문자열 my_string이 매개변수로 주어질 때 모음을 제거한 문자열을 return하도록 solution 함수를 완성해주세요.
=> [63일차] 최주희 / 모음 제거

2st/Yeonwoo/두 수의 곱.c++
| 두 수의 곱 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/120804?language=cpp) |
<hr/>
- 두 수의 곱 : 정수 num1, num2가 매개변수 주어집니다. num1과 num2를 곱한 값을 return 하도록 solution 함수를 완성해주세요.
=> [162일차] 채연우 / 두 수의 곱

2st/Yeonwoo/숫자 비교하기.c++
| 숫자 비교하기 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/120807?language=cpp) |
<hr/>
=> [163일차] 채연우 / 숫자 비교하기

3st/Jaehee/원소들의 곱과 합.java
https://school.programmers.co.kr/learn/courses/30/lessons/181929
<hr/>
=> [64일] 이제희/원소들의 곱과 합

3st/Seojun/이어 붙인수.java
=> [64일차] 김서준 / 이어 붙인 수

3st/Juhee/배열 회전시키기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120844
| 배열 회전시키기 | 프로그래머스 | Level.0 |
<hr/>
- 배열 회전시키기 : 정수가 담긴 배열 numbers와 문자열 direction가 매개변수로 주어집니다. 배열 numbers의 원소를 direction방향으로 한 칸씩 회전시킨 배열을 return하도록 solution 함수를 완성해주세요.
=> [64일차] 최주희 / 배열 회전시키기

3st/Jaeyoung/옹알이 (1).cpp
https://school.programmers.co.kr/learn/courses/30/lessons/120956?language=cpp
| 옹알이 (1) | 프로그래머스 | Level.0 |
<hr/>
- 옹알이 (1) : 머쓱이는 태어난 지 6개월 된 조카를 돌보고 있습니다. 조카는 아직 "aya", "ye", "woo", "ma" 네 가지 발음을 최대 한 번씩 사용해 조합한(이어 붙인) 발음밖에 하지 못합니다. 문자열 배열 babbling이 매개변수로 주어질 때, 머쓱이의 조카가 발음할 수 있는 단어의 개수를 return하도록 solution 함수를 완성해주세요.
=> [64일차] 박재영 / 옹알이 (1)

3st/Jaeyoung/두 수의 연산값 비교하기.java
| 두 수의 연산값 비교하기 | 프로그래머스 | Level.0 |
<hr/>
12 ⊕ 3 = 123
3 ⊕ 12 = 312
=> [65일차] 박재영 / 두 수의 연산값 비교하기

3st/Seojun/A강조하기.java
| A강조하기 | 프로그래머스 | Level.0 |
<hr/>
- A강조하기 : 문자열 myString이 주어집니다. myString에서 알파벳 "a"가 등장하면 전부 "A"로 변환하고, "A"가 아닌 모든 대문자 알파벳은 소문자 알파벳으로 변환하여 return 하는 solution 함수를 완성하세요.
=> [65일차]  / A강조하기

3st/Jaehee/특정한 문자를 대문자로 바꾸기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181873
| 특정한 문자를 대문자로 바꾸기| 프로그래머스 |  Level.0 |
<hr/>
- 특정한 문자를 대문자로 바꾸기: 영소문자로 이루어진 문자열 my_string과 영소문자 1글자로 이루어진 문자열 alp가 매개변수로 주어질 때, my_string에서 alp에 해당하는 모든 글자를 대문자로 바꾼 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [65일] 이제희/특정한 문자를 대문자로 바꾸기

3st/Juhee/배열 원소의 길이.java, 3st/Juhee/배열 회전시키기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120854
<hr/>
- 배열 원소의 길이 : 문자열 배열 strlist가 매개변수로 주어집니다. strlist 각 원소의 길이를 담은 배열을 return하도록 solution 함수를 완성해주세요.
=> [65일차] 최주희 / 배열 원소의 길이

2st/Yeonwoo/짝수의 합.c++
| 짝수의 합 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/120831?language=cpp) |
<hr/>
- 짝수의 합 : 정수 n이 주어질 때, n이하의 짝수를 모두 더한 값을 return 하도록 solution 함수를 작성해주세요.
=> [164일차] 채연우 / 짝수의 합

2st/Yeonwoo/나이 출력.c++
| 나이 출력 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/120820?language=cpp) |
<hr/>
- 나이 출력 : 머쓱이는 선생님이 몇 년도에 태어났는지 궁금해졌습니다. 2022년 기준 선생님의 나이 age가 주어질 때, 선생님의 출생 연도를 return 하는 solution 함수를 완성해주세요.
=> [165일차] 채연우 / 나이 출력

3st/Jaeyoung/x 사이의 개수.java
https://school.programmers.co.kr/learn/courses/30/lessons/181867
| x 사이의 개수  | 프로그래머스 | Level.0 |
<hr/>
- x 사이의 개수 : 문자열 myString이 주어집니다. myString을 문자 "x"를 기준으로 나눴을 때 나눠진 문자열 각각의 길이를 순서대로 저장한 배열을 return 하는 solution 함수를 완성해 주세요.
=> [66일차] 박재영 / x 사이의 개수

3st/Juhee/숫자 찾기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120904
<hr/>
=> [66일차] 최주희 / 숫자 찾기

3st/Seojun/배열에서 문자열 대소문자 변환하기.java
=> [66일차] 김서준 / 배열에서 문자열 대소문자 변환하기

3st/Jaehee/짝수의 합.java
https://school.programmers.co.kr/learn/courses/30/lessons/120831
| 짝수의 합| 프로그래머스 | Level.0 |
<hr/>
- 짝수의 합: 정수 n이 주어질 때, n이하의 짝수를 모두 더한 값을 return 하도록 solution 함수를 작성해주세요.
=> [66일] 이제희/짝수의 합

3st/Seojun/순서쌍의 개수.java
=> [67일차] 김서준 / 순서쌍의 개수

2st/Yeonwoo/배열의 평균값.c++
| 배열의 평균값 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/120817?language=cpp) |
<hr/>
- 배열의 평균값 : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소의 평균값을 return하도록 solution 함수를 완성해주세요.
=> [166일차] 채연우 / 배열의 평균값

3st/Jaehee/OX퀴즈.java
https://school.programmers.co.kr/learn/courses/30/lessons/120907
| OX퀴즈 | 프로그래머스 | Level.0 |
<hr/>
- OX퀴즈 : 덧셈, 뺄셈 수식들이 'X [연산자] Y = Z' 형태로 들어있는 문자열 배열 quiz가 매개변수로 주어집니다. 수식이 옳다면 "O"를 틀리다면 "X"를 순서대로 담은 배열을 return하도록 solution 함수를 완성해주세요.
=> [67일] 이제희/OX퀴즈

3st/Jaeyoung/배열의 길이에 따라 다른 연산하기.java
| 배열의 길이에 따라 다른 연산하기 | 백프로그래머스 | Level.0 |
<hr/>
=> [68일차] 박재영 / 배열의 길이에 따라 다른 연산하기

2st/Yeonwoo/짝수는 싫어요.c++
| 짝수는 싫어요 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120813?language=cpp) |
<hr/>
=> [167일차] 채연우 / 짝수는 싫어요

3st/Seojun/특정한 문자를 대문자로 바꾸기.java
| 특정한 문자를 대문자로 바꾸기 | 프로그래머스 |  Level.1 0
<hr/>
- 특정한 문자를 대문자로 바꾸기 : 영소문자로 이루어진 문자열 my_string과 영소문자 1글자로 이루어진 문자열 alp가 매개변수로 주어질 때, my_string에서 alp에 해당하는 모든 글자를 대문자로 바꾼 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [68일차] 김서준 / 특정한 문자를 대문자로 바꾸기

3st/Jaeyoung/x 사이의 개수.java, 3st/Jaeyoung/문자열의 앞의 n글자.java
=> [69일차] 박재영 / 문자열의 앞의 n글자

3st/Hyeonseo/programmer/대문자로 바꾸기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181877
| 대문자로 바꾸기 | 프로그래머스 | Level.1 |
<hr/>
=> [69일차] 조현서 /  대문자로 바꾸기 

2st/Yeonwoo/배열 두배 만들기.c++
| 배열 두배 만들기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120809?language=cpp) |
<hr/>
- 배열 두배 만들기 : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 각 원소에 두배한 원소를 가진 배열을 return하도록 solution 함수를 완성해주요.
=> [168일차] 채연우 / 배열 두배 만들기

3st/Jaehee/점의 위치 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120841
| 점의 위치 구하기 | 프로그래머스 |  Level.0 |
<hr/>
=> [69일] 이제희/점의 위치 구하기

3st/Juhee/문자열 정렬하기 (2).java
https://school.programmers.co.kr/learn/courses/30/lessons/120911
<hr/>
=> [69일차] 최주희 / 문자열 정렬하기 (2)

3st/Seojun/뒤에서 5등까지.java
=> [69일차] 김서준 / 뒤에서 5등까지

2st/Riyeon/조건에 맞는 개발자 찾기.SQL
| 조건에 맞는 개발자 찾기 | 프로그래머스 | Level.2 |
<hr/>
- 조건에 맞는 개발자 찾기 : DEVELOPERS 테이블에서 Python이나 C# 스킬을 가진 개발자의 정보를 조회하려 합니다. 조건에 맞는 개발자의 ID, 이메일, 이름, 성을 조회하는 SQL 문을 작성해 주세요. 
결과는 ID를 기준으로 오름차순 정렬해 주세요.
=> [168일차] 김리연 / 조건에 맞는 개발자 찾기

3st/Jaehee/배열 만들기 1.java
https://school.programmers.co.kr/learn/courses/30/lessons/181901
<hr/>
=> [70일] 이제희/배열 만들기 1

2st/Yeonwoo/짝수 홀수 개수.c++
| 짝수 홀수 개수 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120824?language=cpp) |
<hr/>
=> [169일차] 채연우 / 짝수 홀수 개수

3st/Juhee/문자열 정렬하기 (1).java
https://school.programmers.co.kr/learn/courses/30/lessons/120850
| 문자열 정렬하기 (1) | 프로그래머스 | Level.0 |
<hr/>
- 문자열 정렬하기 (1) : 문자열 my_string이 매개변수로 주어질 때, my_string 안에 있는 숫자만 골라 오름차순 정렬한 리스트를 return 하도록 solution 함수를 작성해보세요.
=> [70일차] 최주희 / 문자열 정렬하기 (1)

3st/Juhee/인덱스 바꾸기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120895
| 인덱스 바꾸기 | 프로그래머스 | Level.0 |
<hr/>
- 인덱스 바꾸기 : 문자열 my_string과 정수 num1, num2가 매개변수로 주어질 때, my_string에서 인덱스 num1과 인덱스 num2에 해당하는 문자를 바꾼 문자열을 return 하도록 solution 함수를 완성해보세요.
=> [71일차] 최주희 / 인덱스 바꾸기

3st/Hyeonseo/programmer/정수 찾기.java, 3st/Hyeonseo/programmer/카운트 업.java
https://school.programmers.co.kr/learn/courses/30/lessons/181920
|  카운트 업 | 프로그래머스 | Level.0 |
<hr/>
-  카운트 업 : 정수 start_num와 end_num가 주어질 때, start_num부터 end_num까지의 숫자를 차례로 담은 리스트를 return하도록 solution 함수를 완성해주세요.
=> [71일차] 조현서 / 카운트 업

3st/Seojun/가위바위보.java
| 가위 바위 보 | 프로그래머스 | Level.0 |
<hr/>
- 가위 바위 보 : 가위는 2 바위는 0 보는 5로 표현합니다. 가위 바위 보를 내는 순서대로 나타낸 문자열 rsp가 매개변수로 주어질 때, rsp에 저장된 가위 바위 보를 모두 이기는 경우를 순서대로 나타낸 문자열을 return하도록 solution 함수를 완성해보세요.
=> [71일차] 김서준 / 가위 바위 보

3st/Jaehee/문자열 정수의 합.java
https://school.programmers.co.kr/learn/courses/30/lessons/181849
<hr/>
=> [71일] 이제희/문자열 정수의 합

2st/Yeonwoo/문자열 뒤집기.c++
| 문자열 뒤집기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120822?language=cpp) |
<hr/>
=> [170일차] 채연우 / 문자열 뒤집기

3st/Jaeyoung/꼬리 문자열.java
<hr/>
- 꼬리 문자열 : 문자열들이 담긴 리스트가 주어졌을 때, 모든 문자열들을 순서대로 합친 문자열을 꼬리 문자열이라고 합니다. 꼬리 문자열을 만들 때 특정 문자열을 포함한 문자열은 제외시키려고 합니다. 예를 들어 문자열 리스트 ["abc", "def", "ghi"]가 있고 문자열 "ef"를 포함한 문자열은 제외하고 꼬리 문자열을 만들면 "abcghi"가 됩니다.
문자열 리스트 str_list와 제외하려는 문자열 ex가 주어질 때, str_list에서 ex를 포함한 문자열을 제외하고 만든 꼬리 문자열을 return하도록 solution 함수를 완성해주세요.
=> [71일] 박재영 / 꼬리 문자열

3st/Jaeyoung/직각삼각형 출력하기.java
| 직각삼각형 출력하기 | 프로그래머스 | Level.0 |
<hr/>
- 직각삼각형 출력하기 : "*"의 높이와 너비를 1이라고 했을 때, "*"을 이용해 직각 이등변 삼각형을 그리려고합니다. 정수 n 이 주어지면 높이와 너비가 n 인 직각 이등변 삼각형을 출력하도록 코드를 작성해보세요.
=> [72일차] 박재영 / 직각삼각형 출력하기

3st/Juhee/암호 해독.java
https://school.programmers.co.kr/learn/courses/30/lessons/120892
| 암호 해독 | 프로그래머스 | Level.0 |
<hr/>
- 암호 해독 : 군 전략가 머쓱이는 전쟁 중 적군이 다음과 같은 암호 체계를 사용한다는 것을 알아냈습니다.
암호화된 문자열 cipher를 주고받습니다.
그 문자열에서 code의 배수 번째 글자만 진짜 암호입니다.
문자열 cipher와 정수 code가 매개변수로 주어질 때 해독된 암호 문자열을 return하도록 solution 함수를 완성해주세요.
=> [72일차] 최주희 / 암호 해독

3st/Jaehee/팩토리얼.java
https://school.programmers.co.kr/learn/courses/30/lessons/120848
| 팩토리얼 | 프로그래머스 | Level.0 |
<hr/>
- 팩토리얼 : i팩토리얼 (i!)은 1부터 i까지 정수의 곱을 의미합니다. 예를들어 5! = 5 * 4 * 3 * 2 * 1 = 120 입니다. 정수 n이 주어질 때 다음 조건을 만족하는 가장 큰 정수 i를 return 하도록 solution 함수를 완성해주세요.
=> [72일] 이제희/팩토리얼

2st/Yeonwoo/중복된 숫자 개수.c++, 2st/Yeonwoo/중앙값 구하기.c++
| 중복된 숫자 개수 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120583?language=cpp) |
<hr/>
=> [171일차] 채연우 / 중복된 숫자 개수

2st/Yeonwoo/배열 뒤집기.c++
| 배열 뒤집기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120821) |
<hr/>
- 배열 뒤집기 : 정수가 들어 있는 배열 num_list가 매개변수로 주어집니다. num_list의 원소의 순서를 거꾸로 뒤집은 배열을 return하도록 solution 함수를 완성해주세요.
=> [172일차] 채연우 / 배열 뒤집기

3st/Hyeonseo/programmer/홀짝에 따라 다른 값 반환하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181935
<hr/>
=> [73일차] 조현서 / 홀짝에 따라 다른 값 반환하기

3st/Jaehee/Main.java
https://www.acmicpc.net/submit/1001/82941739
| A-B | 백준 | Level.0 |
<hr/>
- A-B  : 두 정수 A와 B를 입력받은 다음, A-B를 출력하는 프로그램을 작성하시오.
=> [73일] 이제/A-B

3st/Jaeyoung/부분 문자열.java
<hr/>
- 부분 문자열 : 어떤 문자열 A가 다른 문자열 B안에 속하면 A를 B의 부분 문자열이라고 합니다. 예를 들어 문자열 "abc"는 문자열 "aabcc"의 부분 문자열입니다.
문자열 str1과 str2가 주어질 때, str1이 str2의 부분 문자열이라면 1을 부분 문자열이 아니라면 0을 return하도록 solution 함수를 완성해주세요.
=> [74일차] 박재영 / 부분 문자열

2st/Yeonwoo/머쓱이보다 키 큰 사람.c++
| 머쓱이보다 키 큰 사람 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120585?language=cpp) |
<hr/>
- 머쓱이보다 키 큰 사람 : 머쓱이는 학교에서 키 순으로 줄을 설 때 몇 번째로 서야 하는지 궁금해졌습니다. 머쓱이네 반 친구들의 키가 담긴 정수 배열 array와 머쓱이의 키 height가 매개변수로 주어질 때, 머쓱이보다 키 큰 사람 수를 return 하도록 solution 함수를 완성해보세요.
=> [173일차] 채연우 / 머쓱이보다 키 큰 사람

3st/Juhee/합성수 찾기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120846
| 합성수 찾기 | 프로그래머스 | Level.0 |
<hr/>
- 합성수 찾기 : 약수의 개수가 세 개 이상인 수를 합성수라고 합니다. 자연수 n이 매개변수로 주어질 때 n이하의 합성수의 개수를 return하도록 solution 함수를 완성해주세요.
=> [75일차] 최주희 / 합성수 찾기

3st/Seojun/Coding_Test240626.java, 3st/Seojun/점의 위치 구하기.java, 3st/Seojun/출력.java, 3st/Seojun/편지.java
<hr/>
- 점의 위치 구하기 : 
사분면은 한 평면을 x축과 y축을 기준으로 나눈 네 부분입니다. 사분면은 아래와 같이 1부터 4까지 번호를매깁니다.
스크린샷 2022-07-07 오후 3.27.04 복사본.png
x 좌표 (x, y)를 차례대로 담은 정수 배열 dot이 매개변수로 주어집니다. 좌표 dot이 사분면 중 어디에 속하는지 1, 2, 3, 4 중 하나를 return 하도록 solution 함수를 완성해주세요
=> [75일차] 김서준 / 점의 위치 구하기

3st/Jaeyoung/접두사인지 확인하기.java
| 접두사인지 확인하기 | 프로그래머스 | Level.0 |
<hr/>
- 접두사인지 확인하기 : 어떤 문자열에 대해서 접두사는 특정 인덱스까지의 문자열을 의미합니다. 예를 들어, "banana"의 모든 접두사는 "b", "ba", "ban", "bana", "banan", "banana"입니다.
문자열 my_string과 is_prefix가 주어질 때, is_prefix가 my_string의 접두사라면 1을, 아니면 0을 return 하는 solution 함수를 작성해 주세요.
=> [75일차] 박재영 / 접두사인지 확인하기

2st/Yeonwoo/n의 배수 고르기.c++
| n의 배수 고르기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120905?language=cpp) |
<hr/>
=> [174일차] 채연우 / n의 배수 고르기

3st/Hyeonseo/com/JadenCase 문자열 만들기.java, 3st/Hyeonseo/programmer/피자 나눠 먹기(1).java
| 피자 나눠 먹기  | 프로그래머스 | Level.0 |
<hr/>
- 피자 나눠 먹기  : 머쓱이네 피자가게는 피자를 일곱 조각으로 잘라 줍니다. 피자를 나눠먹을 사람의 수 n이 주어질 때, 모든 사람이 피자를 한 조각 이상 먹기 위해 필요한 피자의 수를 return 하는 solution 함수를 완성해보세요.
=> [75일차] 조현서 / 피자 나눠 먹기 

2st/Riyeon/루시와 엘라 찾기.sql
| 루시와 엘라 찾기 | 프로그래머스 | Level.2 |
<hr/>
- 루시와 엘라 찾기 : 동물 보호소에 들어온 동물 중 이름이 Lucy, Ella, Pickle, Rogan, Sabrina, Mitty인 동물의 아이디와 이름, 성별 및 중성화 여부를 조회하는 SQL 문을 작성해주세요.
=> [174일차] 김리연 / 루시와 엘라 찾기

3st/Hyeonseo/com/최솟값 만들기.java
httpst://school.programmers.co.kr/learn/courses/30/lessons/120895
| 인덱스 바꾸기  | 프로그래머스 | Level.0 |
<hr/>
- 인덱스 바꾸기  : 문자열 my_string과 정수 num1, num2가 매개변수로 주어질 때, my_string에서 인덱스 num1과 인덱스 num2에 해당하는 문자를 바꾼 문자열을 return 하도록 solution 함수를 완성해보세요.
=> [76일차] 조현서 / 인덱스 바꾸기 

3st/Jaehee/두 수의 연산값 비교하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181938
| 두 수의 연산값 비교하기 |프로그래머스 | Level.0 |
<hr/>
12 ⊕ 3 = 123
3 ⊕ 12 = 312
=> [76일] 이제희/두 수의 연산값 비교하기

3st/Seojun/문자 반복 출력하기.java
=> [77일차] 김서준 / 문자 반복 출력하기

3st/Jaehee/배열에서 문자열 대소문자 변환하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181875
<hr/>
=> [77일] 이제희/배열에서 문자열 대소문자 변환하기

3st/Hyeonseo/com/영어 끝말잇기.java, 3st/Hyeonseo/programmer/문자열 붙여서 출력하기.java, 3st/Hyeonseo/programmer/인덱스 바꾸기.java
<hr/>
- 문자열 붙여서 출력하기 : 두 개의 문자열 str1, str2가 공백으로 구분되어 입력으로 주어집니다.
=> [77일차] 조현서 / 문자열 붙여서 출력하기

3st/Juhee/최빈값 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120812
| 최빈값 구하기 | 프로그래머스 | Level.0 |
<hr/>
=> [77일차] 최주희 / 최빈값 구하기

3st/Jaeyoung/문자열 바꿔서 찾기.java
=> [78일차] 박재영 / 문자열 바꿔서 찾기

3st/Jaehee/피자 나눠 먹기 (2).java
https://school.programmers.co.kr/learn/courses/30/lessons/120815
| 피자 나눠 먹기 (2) | 프로그래머스 | Level.0 |
<hr/>
- 피자 나눠 먹기 (2) : 머쓱이네 피자가게는 피자를 여섯 조각으로 잘라 줍니다. 피자를 나눠먹을 사람의 수 n이 매개변수로 주어질 때, n명이 주문한 피자를 남기지 않고 모두 같은 수의 피자 조각을 먹어야 한다면 최소 몇 판을 시켜야 하는지를 return 하도록 solution 함수를 완성해보세요.
=> [78일] 이제희/피자 나눠 먹기 (2)

3st/Seojun/배열 자르기.java
=> [78일차] 김서준 / 배열 자르기

3st/Juhee/2차원으로 만들기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120842
| 2차원으로 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 2차원으로 만들기 : 정수 배열 num_list와 정수 n이 매개변수로 주어집니다. num_list를 다음 설명과 같이 2차원 배열로 바꿔 return하도록 solution 함수를 완성해주세요.
num_list가 [1, 2, 3, 4, 5, 6, 7, 8] 로 길이가 8이고 n이 2이므로 num_list를 2 * 4 배열로 다음과 같이 변경합니다. 2차원으로 바꿀 때에는 num_list의 원소들을 앞에서부터 n개씩 나눠 2차원 배열로 변경합니다.
=> [78일차] 최주희 / 2차원으로 만들기

2st/Yeonwoo/가위 바위 보.c++
| 가위 바위 보 |  프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120839?language=cpp) |
<hr/>
- 가위 바위 보 : 가위는 2 바위는 0 보는 5로 표현합니다. 가위 바위 보를 내는 순서대로 나타낸 문자열 rsp가 매개변수로 주어질 때, rsp에 저장된 가위 바위 보를 모두 이기는 경우를 순서대로 나타낸 문자열을 return하도록 solution 함수를 완성해보세요.
=> [177일차] 채연우 / 가위 바위 보

3st/Juhee/진료 순서 정하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120835
| 진료 순서 정하기 | 프로그래머스 | Level.0 |
<hr/>
- 진료 순서 정하기 : 외과의사 머쓱이는 응급실에 온 환자의 응급도를 기준으로 진료 순서를 정하려고 합니다. 정수 배열 emergency가 매개변수로 주어질 때 응급도가 높은 순서대로 진료 순서를 정한 배열을 return하도록 solution 함수를 완성해주세요.
=> [79일차] 최주희 / 진료 순서 정하기

3st/Jaehee/문자 반복 출력하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120825
<hr/>
=> [79일] 이제희/문자 반복 출력하기

3st/Jaeyoung/l로 만들기.js
| l로 만들기 | 프로그래머스 | Level.0 |
<hr/>
- l로 만들기 : 알파벳 소문자로 이루어진 문자열 myString이 주어집니다. 알파벳 순서에서 "l"보다 앞서는 모든 문자를 "l"로 바꾼 문자열을 return 하는 solution 함수를 완성해 주세요.
=> [79일차] 박재영 / l로 만들기

3st/Jaeyoung/모음 제거.java, 3st/Jaeyoung/할 일 목록.java
=> [80일차] 박재영 / 할 일 목록

3st/Seojun/개미군단.java
<hr/>
- 개미 군단 : 개미 군단이 사냥을 나가려고 합니다. 개미군단은 사냥감의 체력에 딱 맞는 병력을 데리고 나가려고 합니다. 장군개미는 5의 공격력을, 병정개미는 3의 공격력을 일개미는 1의 공격력을 가지고 있습니다. 예를 들어 체력 23의 여치를 사냥하려고 할 때, 일개미 23마리를 데리고 가도 되지만, 장군개미 네 마리와 병정개미 한 마리를 데리고 간다면 더 적은 병력으로 사냥할 수 있습니다. 사냥감의 체력 hp가 매개변수로 주어질 때, 사냥감의 체력에 딱 맞게 최소한의 병력을 구성하려면 몇 마리의 개미가 필요한지를 return하도록 solution 함수를 완성해주세요.
=> [80일] 김서준 / 개미 군단

2st/Yeonwoo/A로 B 만들기.c++
| A로 B 만들기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120886?language=cpp) |
<hr/>
- A로 B 만들기 : 문자열 before와 after가 매개변수로 주어질 때, before의 순서를 바꾸어 after를 만들 수 있으면 1을, 만들 수 없으면 0을 return 하도록 solution 함수를 완성해보세요.
=> [179일차] 채연우 / A로 B 만들기

3st/Jaehee/양꼬치.java
https://school.programmers.co.kr/learn/courses/30/lessons/120830#
<hr/>
=> [80일] 이제희/양꼬치

3st/Seojun/문자열안에 문자열.java
| 문자열안에 문자열 |프로그래머스 | Level.0 |
<hr/>
=> [81일] 김서준 / 문자열안에 문자열

2st/Yeonwoo/숫자 찾기.c++
| 숫자 찾기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120904?language=cpp) |
<hr/>
=> [180일차] 채연우 / 숫자 찾기

3st/Hyeonseo/com/옹알이(1).java, 3st/Hyeonseo/com/옹알이(2).java, 3st/Hyeonseo/programmer/머쓱이보다 키 큰 사람.JAVA, 3st/Hyeonseo/programmer/문자열 곱하기.java, 3st/Hyeonseo/programmer/이상한 문자 만들기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120956
| 옹알이(1) | 프로그래머스 | Level.0 |
<hr/>
- 옹알이(1) : 머쓱이는 태어난 지 6개월 된 조카를 돌보고 있습니다. 조카는 아직 "aya", "ye", "woo", "ma" 네 가지 발음을 최대 한 번씩 사용해 조합한(이어 붙인) 발음밖에 하지 못합니다. 문자열 배열 babbling이 매개변수로 주어질 때, 머쓱이의 조카가 발음할 수 있는 단어의 개수를 return하도록 solution 함수를 완성해주세요.
=> [81일차] 조현서 /  옹알이(1)

3st/Jaeyoung/뒤에서 5등 위로.java
| 뒤에서 5등 위로 | 프로그래머스 | Level.0 |
<hr/>
- 뒤에서 5등 위로 : 정수로 이루어진 리스트 num_list가 주어집니다. num_list에서 가장 작은 5개의 수를 제외한 수들을 오름차순으로 담은 리스트를 return하도록 solution 함수를 완성해주세요.
=> [81일차] 박재영 / 뒤에서 5등 위로

3st/Jaeyoung/부분 문자열 이어 붙여 문자열 만들기.java
<hr/>
- 부분 문자열 이어 붙여 문자열 만들기 : 길이가 같은 문자열 배열 my_strings와 이차원 정수 배열 parts가 매개변수로 주어집니다. parts[i]는 [s, e] 형태로, my_string[i]의 인덱스 s부터 인덱스 e까지의 부분 문자열을 의미합니다. 각 my_strings의 원소의 parts에 해당하는 부분 문자열을 순서대로 이어 붙인 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [82일차] 박재영 / 부분 문자열 이어 붙여 문자열 만들기

3st/Jaehee/배열 자르기.groovy
https://school.programmers.co.kr/learn/courses/30/lessons/120833
<hr/>
- 배열 자르기 : 정수 배열 numbers와 정수 num1, num2가 매개변수로 주어질 때, numbers의 num1번 째 인덱스부터 num2번째 인덱스까지 자른 정수 배열을 return 하도록 solution 함수를 완성해보세요
=> [82일] 이제희/배열 자르기

3st/Seojun/특정 문자 제거하기.java
=> [82일차] 김서준 / 특정 문자 제거하기

3st/Juhee/중복된 문자 제거.java
https://school.programmers.co.kr/learn/courses/30/lessons/120888
| 중복된 문자 제거 | 프로그래머스 | Level.0 |
<hr/>
- 중복된 문자 제거 : 문자열 my_string이 매개변수로 주어집니다. my_string에서 중복된 문자를 제거하고 하나의 문자만 남긴 문자열을 return하도록 solution 함수를 완성해주세요.
=> [82일차] 최주희 / 중복된 문자 제거

2st/Yeonwoo/홀수 vs 짝수.c++
| 홀수 vs 짝수 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181887?language=cpp) |
<hr/>
=> [181일차] 채연우 / 홀수 vs 짝수

3st/Seojun/순서 바꾸기.java
<hr/>
- 순서 바꾸기 : 정수 리스트 num_list와 정수 n이 주어질 때, num_list를 n 번째 원소 이후의 원소들과 n 번째까지의 원소들로 나눠 n 번째 원소 이후의 원소들을 n 번째까지의 원소들 앞에 붙인 리스트를 return하도록 solution 함수를 완성해주세요.
=> [83일차] 김서준 / 순서 바꾸기

3st/Hyeonseo/programmer/옹알이(2).java
https://school.programmers.co.kr/learn/courses/30/lessons/42885#qna
| 구명보트 | 프로그래머스 | Level.2 |
<hr/>
- 구명보트 : 무인도에 갇힌 사람들을 구명보트를 이용하여 구출하려고 합니다. 구명보트는 작아서 한 번에 최대 2명씩 밖에 탈 수 없고, 무게 제한도 있습니다.
예를 들어, 사람들의 몸무게가 [70kg, 50kg, 80kg, 50kg]이고 구명보트의 무게 제한이 100kg이라면 2번째 사람과 4번째 사람은 같이 탈 수 있지만 1번째 사람과 3번째 사람의 무게의 합은 150kg이므로 구명보트의 무게 제한을 초과하여 같이 탈 수 없습니다.
구명보트를 최대한 적게 사용하여 모든 사람을 구출하려고 합니다.
사람들의 몸무게를 담은 배열 people과 구명보트의 무게 제한 limit가 매개변수로 주어질 때, 모든 사람을 구출하기 위해 필요한 구명보트 개수의 최솟값을 return 하도록 solution 함수를 작성해주세요.
=> [83일차] 조현서 / 구명보트

3st/Jaehee/최댓값 만들기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120847
| 최댓값 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 최댓값 만들기 : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소 중 두 개를 곱해 만들 수 있는 최댓값을 return하도록 solution 함수를 완성해주세요.
=> [83일] 이제희/최댓값 만들기

3st/Jaeyoung/주사위 게임 1.java
| 주사위 게임 1 | 프로그래머스 | Level.0 |
<hr/>
- 주사위 게임 1 : 1부터 6까지 숫자가 적힌 주사위가 두 개 있습니다. 두 주사위를 굴렸을 때 나온 숫자를 각각 a, b라고 했을 때 얻는 점수는 다음과 같습니다.
두 정수 a와 b가 매개변수로 주어질 때, 얻는 점수를 return 하는 solution 함수를 작성해 주세요.
=> [83일차] 박재영 / 주사위 게임 1

3st/Juhee/모스부호(1).java
https://school.programmers.co.kr/learn/courses/30/lessons/120838
| 모스부호 (1) | 프로그래머스 | Level.0 |
<hr/>
- 모스부호 (1) : 머쓱이는 친구에게 모스부호를 이용한 편지를 받았습니다. 그냥은 읽을 수 없어 이를 해독하는 프로그램을 만들려고 합니다. 문자열 letter가 매개변수로 주어질 때, letter를 영어 소문자로 바꾼 문자열을 return 하도록 solution 함수를 완성해보세요.
모스부호는 다음과 같습니다.
=> [83일차] 최주희 / 모스부호 (1)

3st/Jaehee/A나누기B.java
https://www.acmicpc.net/submit/1008/82942205
| A/B | 백준 | Level.0 |
<hr/>
- A/B : 두 정수 A와 B를 입력받은 다음, A/B를 출력하는 프로그램을 작성하시오.
=> [84일] 이제희/A/B

3st/Juhee/팩토리얼.java
https://school.programmers.co.kr/learn/courses/30/lessons/120848
| 팩토리얼 | 프로그래머스 | Level.0 |
<hr/>
- 팩토리얼 : i팩토리얼 (i!)은 1부터 i까지 정수의 곱을 의미합니다. 예를들어 5! = 5 * 4 * 3 * 2 * 1 = 120 입니다. 정수 n이 주어질 때 다음 조건을 만족하는 가장 큰 정수 i를 return 하도록 solution 함수를 완성해주세요.
i! ≤ n
=> [84일차] 최주희 / 팩토리얼

3st/Seojun/제곱수 판별하기.java
| 제곱수 판별하기 | 프로그래머스 | Level.0 |
<hr/>
- 제곱수 판별하기 : 설명
=> [84일차] 김서준 / 제곱수 판별하기

3st/Jaeyoung/대충 만든 자판.java
| 대충 만든 자판 | 프로그래머스 | Level.1 |
<hr/>
- 대충 만든 자판 : 휴대폰의 자판은 컴퓨터 키보드 자판과는 다르게 하나의 키에 여러 개의 문자가 할당될 수 있습니다. 키 하나에 여러 문자가 할당된 경우, 동일한 키를 연속해서 빠르게 누르면 할당된 순서대로 문자가 바뀝니다.
예를 들어, 1번 키에 "A", "B", "C" 순서대로 문자가 할당되어 있다면 1번 키를 한 번 누르면 "A", 두 번 누르면 "B", 세 번 누르면 "C"가 되는 식입니다.
같은 규칙을 적용해 아무렇게나 만든 휴대폰 자판이 있습니다. 이 휴대폰 자판은 키의 개수가 1개부터 최대 100개까지 있을 수 있으며, 특정 키를 눌렀을 때 입력되는 문자들도 무작위로 배열되어 있습니다. 또, 같은 문자가 자판 전체에 여러 번 할당된 경우도 있고, 키 하나에 같은 문자가 여러 번 할당된 경우도 있습니다. 심지어 아예 할당되지 않은 경우도 있습니다. 따라서 몇몇 문자열은 작성할 수 없을 수도 있습니다.
이 휴대폰 자판을 이용해 특정 문자열을 작성할 때, 키를 최소 몇 번 눌러야 그 문자열을 작성할 수 있는지 알아보고자 합니다.
1번 키부터 차례대로 할당된 문자들이 순서대로 담긴 문자열배열 keymap과 입력하려는 문자열들이 담긴 문자열 배열 targets가 주어질 때, 각 문자열을 작성하기 위해 키를 최소 몇 번씩 눌러야 하는지 순서대로 배열에 담아 return 하는 solution 함수를 완성해 주세요.
단, 목표 문자열을 작성할 수 없을 때는 …
=> [84일차] 박재영 / 대충 만든 자판

2st/Yeonwoo/뒤에서 5등까지.c++
| 뒤에서 5등까지 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181853?language=cpp) |
<hr/>
=> [183일차] 채연우 / 뒤에서 5등까지

3st/Seojun/자릿수 더하기.java
| 자릿수 더하기 | 프로그래머스 |  Level.0 |
<hr/>
=> [85일차] 김서준/ 자릿수 더하기

2st/Yeonwoo/문자 반복 출력하기.c++
| 나머지 구하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120810?language=cpp) |
<hr/>
=> [184일차] 채연우 / 나머지 구하기

3st/Jaehee/사칙연산.java
https://www.acmicpc.net/submit/10869/82942388
| 사칙연산 | 백준 | Level.0 |
<hr/>
- 사칙연산 : 두 자연수 A와 B가 주어진다. 이때, A+B, A-B, A*B, A/B(몫), A%B(나머지)를 출력하는 프로그램을 작성하시오.
=> [85일] 이제희/사칙연산

3st/Jaeyoung/특정 문자 제거하기.java
=> [86일차] 박재영 / 특정 문자 제거하기

3st/Jaehee/Main.java
https://www.acmicpc.net/submit/10926/83164671
| ??!| 백준 | Level.0 |
<hr/>
- ??!: 준하는 사이트에 회원가입을 하다가 joonas라는 아이디가 이미 존재하는 것을 보고 놀랐다. 준하는 놀람을 ??!로 표현한다. 준하가 가입하려고 하는 사이트에 이미 존재하는 아이디가 주어졌을 때, 놀람을 표현하는 프로그램을 작성하시오.
=> [86일] 이제희/??!

3st/Seojun/더 크게 합치기.java
| 더 크게 합치기  | 프로그래머스 | Level.0 |
<hr/>
- 더 크게 합치기  : 연산 ⊕는 두 정수에 대한 연산으로 두 정수를 붙여서 쓴 값을 반환합니다. 예를 들면 다음과 같습니다.
12 ⊕ 3 = 123
3 ⊕ 12 = 312
양의 정수 a와 b가 주어졌을 때, a ⊕ b와 b ⊕ a 중 더 큰 값을 return 하는 solution 함수를 완성해 주세요.
단, a ⊕ b와 b ⊕ a가 같다면 a ⊕ b를 return 합니다.
=> [86일차] 김서준 / 더 크게 합치기 

3st/Juhee/가까운 수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120890
| 가까운 수 | 프로그래머스 | Level.0 |
<hr/>
- 가까운 수 : 정수 배열 array와 정수 n이 매개변수로 주어질 때, array에 들어있는 정수 중 n과 가장 가까운 수를 return 하도록 solution 함수를 완성해주세요.
=> [86일차] 최주희 / 가까운 수

3st/Jaeyoung/점의 위치 구하기.js
<hr/>
x 좌표 (x, y)를 차례대로 담은 정수 배열 dot이 매개변수로 주어집니다. 좌표 dot이 사분면 중 어디에 속하는지 1, 2, 3, 4 중 하나를 return 하도록 solution 함수를 완성해주세요.
=> [87일차] 박재영 / 점의 위치 구하기

3st/Seojun/숨어있는 숫자의 덧셈.java
| 숨어있는 숫자의 덧셈 (1) | 프로그래머스 |  Level.0 |
<hr/>
- 숨어있는 숫자의 덧셈 (1) : 문자열 my_string이 매개변수로 주어집니다. my_string안의 모든 자연수들의 합을 return하도록 solution 함수를 완성해주세요.
=> [87일차] 김서 / 숨어있는 숫자의 덧셈 (1)

3st/Juhee/한 번만 등장한 문자.java
https://school.programmers.co.kr/learn/courses/30/lessons/120896
| 한 번만 등장한 문자 | 프로그래머스 | Level.0 |
<hr/>
- 한 번만 등장한 문자 : 문자열 s가 매개변수로 주어집니다. s에서 한 번만 등장하는 문자를 사전 순으로 정렬한 문자열을 return 하도록 solution 함수를 완성해보세요. 한 번만 등장하는 문자가 없을 경우 빈 문자열을 return 합니다.
=> [87일차] 최주희 / 한 번만 등장한 문자

3st/Jaehee/나머지.java
https://www.acmicpc.net/submit/10430/83165919
| 나머지 | 백준 | Level.0 |
<hr/>
- 나머지 : (A+B)%C는 ((A%C) + (B%C))%C 와 같을까?
(A×B)%C는 ((A%C) × (B%C))%C 와 같을까?
세 수 A, B, C가 주어졌을 때, 위의 네 가지 값을 구하는 프로그램을 작성하시오.
=> [88일] 이제희/나머지

3st/Jaeyoung/문자열 뒤집기.js
=> [88일차] 박재영 / 문자열 뒤집기

2st/Yeonwoo/할 일 목록.c++
| 할 일 목록 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181885?language=cpp) |
<hr/>
=> [187일차] 채연우 / 할 일 목록

3st/Juhee/숨어있는 숫자의 덧셈 (2).java
https://school.programmers.co.kr/learn/courses/30/lessons/120864?language=java
| 숨어있는 숫자의 덧셈 (2) | 프로그래머스 | Level.0 |
<hr/>
- 숨어있는 숫자의 덧셈 (2) : 문자열 my_string이 매개변수로 주어집니다. my_string은 소문자, 대문자, 자연수로만 구성되어있습니다. my_string안의 자연수들의 합을 return하도록 solution 함수를 완성해주세요.
=> [89일차] 최주희 / 숨어있는 숫자의 덧셈 (2)

2st/Riyeon/완주하지 못한 선수.py
| 완주하지 못한 선수 | 프로그래머스 | Level.1 |
<hr/>
- 완주하지 못한 선수 : 수많은 마라톤 선수들이 마라톤에 참여하였습니다. 단 한 명의 선수를 제외하고는 모든 선수가 마라톤을 완주하였습니다.
마라톤에 참여한 선수들의 이름이 담긴 배열 participant와 완주한 선수들의 이름이 담긴 배열 completion이 주어질 때, 완주하지 못한 선수의 이름을 return 하도록 solution 함수를 작성해주세요.
=> [188일차] 김리연 / 완주하지 못한 선수

3st/Jaehee/곱셈.java
https://www.acmicpc.net/submit/2588/83166344
| 곱셈| 백준| Level.0 |
<hr/>
- 곱셈: (세 자리 수) × (세 자리 수)는 다음과 같은 과정을 통하여 이루어진다.
(1)과 (2)위치에 들어갈 세 자리 자연수가 주어질 때 (3), (4), (5), (6)위치에 들어갈 값을 구하는 프로그램을 작성하시오.
=> [89] 이제희/곱셈

2st/Yeonwoo/배열의 길이를 2의 거듭제곱으로 만들기.py
| 배열의 길이를 2의 거듭제곱으로 만들기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181857) |
<hr/>
- 배열의 길이를 2의 거듭제곱으로 만들기 : 정수 배열 arr이 매개변수로 주어집니다. arr의 길이가 2의 정수 거듭제곱이 되도록 arr 뒤에 정수 0을 추가하려고 합니다. arr에 최소한의 개수로 0을 추가한 배열을 return 하는 solution 함수를 작성해 주세요.
=> [188일차] 채연우 / 배열의 길이를 2의 거듭제곱으로 만들기

2st/Riyeon/전화번호 목록.py
| 전화번호 목록 | 프로그래머스 | Level.2 |
<hr/>
- 전화번호 목록 : 전화번호부에 적힌 전화번호를 담은 배열 phone_book 이 solution 함수의 매개변수로 주어질 때, 어떤 번호가 다른 번호의 접두어인 경우가 있으면 false를 그렇지 않으면 true를 return 하도록 solution 함수를 작성해주세요.
=> [189일차] 김리연 / 전화번호 목록

3st/Jaeyoung/배열 자르기.py, 3st/Jaeyoung/자릿수 더하기.java
=> [90일차] 박재영 / 자릿수 더하기

3st/Jaehee/꼬마 정민.java
https://www.acmicpc.net/submit/11382/83166664
| 꼬마 정민| 백준 | Level.0 |
<hr/>
- 꼬마 정민: 꼬마 정민이는 이제 A + B 정도는 쉽게 계산할 수 있다. 이제 A + B + C를 계산할 차례이다!
=> [90일] 이제희/꼬마 정민

2st/Yeonwoo/마지막 두 원소.c++
| 마지막 두 원소 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181927?language=cpp) |
<hr/>
=> [189일차] 채연우 / 마지막 두 원소

3st/Juhee/A로 B 만들기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120886
| A로 B 만들기 | 프로그래머스 | Level.0 |
<hr/>
- A로 B 만들기 : 문자열 before와 after가 매개변수로 주어질 때, before의 순서를 바꾸어 after를 만들 수 있으면 1을, 만들 수 없으면 0을 return 하도록 solution 함수를 완성해보세요.
=> [90일차] 최주희 / A로 B 만들기

2st/Yeonwoo/공배수.c++
| 공배수 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181936?language=cpp) |
<hr/>
=> [190일차] 채연우 / 공배수

3st/Jaehee/고양이.java
https://www.acmicpc.net/submit/10171/86854062
| 고양이 | 백준 | Level.0 |
<hr/>
- 고양이 : 아래 예제와 같이 고양이를 출력하시오.
=> [91일] 이제희/고양이

3st/Juhee/k의 개수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120887
| k의 개수 | 프로그래머스 | Level.0 |
<hr/>
- k의 개수 : 1부터 13까지의 수에서, 1은 1, 10, 11, 12, 13 이렇게 총 6번 등장합니다. 정수 i, j, k가 매개변수로 주어질 때, i부터 j까지 k가 몇 번 등장하는지 return 하도록 solution 함수를 완성해주세요.
=> [91일차] 최주희 / k의 개수

3st/Jaeyoung/배열의 유사도.py
=> [91일차] 박재영 / 배열의 유사도

3st/Seojun/두 수의 합,java, 3st/Seojun/배열의 유사도.java
=> [91일차] 김서준 / 배열의 유사도

3st/Jaehee/개.java
https://www.acmicpc.net/submit/10171/86854062
| 개| 백준 | Level.0 |
<hr/>
- 개: 아래 예제와 같이 개를 출력하시오.
=> [92일] 이제희/개

3st/Juhee/컨트롤 제트.java
https://school.programmers.co.kr/learn/courses/30/lessons/120853
| 컨트롤 제트 | 프로그래머스 | Level.0 |
<hr/>
- 컨트롤 제트 : 숫자와 "Z"가 공백으로 구분되어 담긴 문자열이 주어집니다. 문자열에 있는 숫자를 차례대로 더하려고 합니다. 이 때 "Z"가 나오면 바로 전에 더했던 숫자를 뺀다는 뜻입니다. 숫자와 "Z"로 이루어진 문자열 s가 주어질 때, 머쓱이가 구한 값을 return 하도록 solution 함수를 완성해보세요.
=> [92일차] 최주희 / 컨트롤 제트

3st/Seojun/조건에 맞게 수열 변환하기1.java
| 조건에 맞게 수열 변환하기 1 | 프로그래머스 | Level.0 |
<hr/>
- 조건에 맞게 수열 변환하기 1 : 정수 배열 arr가 주어집니다. arr의 각 원소에 대해 값이 50보다 크거나 같은 짝수라면 2로 나누고, 50보다 작은 홀수라면 2를 곱합니다. 그 결과인 정수 배열을 return 하는 solution 함수를 완성해 주세요.
=> [92일차] 김서준 / 조건에 맞게 수열 변환하기 1

3st/Jaeyoung/최댓값 만들기(1).py
| 최댓값 만들기(1) | 프로그래머스 | Level.0 |
<hr/>
=> [92일차] 박재영 / 최댓값 만들기(1)

2st/Yeonwoo/정수 찾기.c++
| 정수 찾기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181840?language=cpp) |
<hr/>
- 정수 찾기 : 정수 리스트 num_list와 찾으려는 정수 n이 주어질 때, num_list안에 n이 있으면 1을 없으면 0을 return하도록 solution 함수를 완성해주세요.
=> [191일차] 채연우 / 정수 찾기

3st/Jaeyoung/삼각형의 완성조건 (1).py
| 삼각형의 완성조건 (1) | 프로그래머스 | Level.0 |
<hr/>
- 삼각형의 완성조건 (1) : 선분 세 개로 삼각형을 만들기 위해서는 다음과 같은 조건을 만족해야 합니다.
가장 긴 변의 길이는 다른 두 변의 길이의 합보다 작아야 합니다.
삼각형의 세 변의 길이가 담긴 배열 sides이 매개변수로 주어집니다. 세 변으로 삼각형을 만들 수 있다면 1, 만들 수 없다면 2를 return하도록 solution 함수를 완성해주세요.
=> [93일차] 박재영 / 삼각형의 완성조건 (1)

3st/Juhee/소인수분해.java
https://school.programmers.co.kr/learn/courses/30/lessons/120852
| 소인수분해 | 프로그래머스 | Level.0 |
<hr/>
- 소인수분해 : 소인수분해란 어떤 수를 소수들의 곱으로 표현하는 것입니다. 예를 들어 12를 소인수 분해하면 2 * 2 * 3 으로 나타낼 수 있습니다. 따라서 12의 소인수는 2와 3입니다. 자연수 n이 매개변수로 주어질 때 n의 소인수를 오름차순으로 담은 배열을 return하도록 solution 함수를 완성해주세요.
=> [93일차] ㅚ주희 / 소인수분해

3st/Seojun/할 일 몰록.java
=> [93일차] 김서준 / 할 일 목록

3st/Jaehee/두 수 비교하기.java
https://www.acmicpc.net/submit/1330/87800622
| 두 수 비교하기 | 백준 | Level.0 |
<hr/>
- 두 수 비교하기 : 두 정수 A와 B가 주어졌을 때, A와 B를 비교하는 프로그램을 작성하시오.
=> [93일] 이제희/두 수 비교하기

2st/Yeonwoo/1로 만들기.c++
| 1로 만들기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181880?language=cpp) |
<hr/>
- 1로 만들기 : 정수가 있을 때, 짝수라면 반으로 나누고, 홀수라면 1을 뺀 뒤 반으로 나누면, 마지막엔 1이 됩니다. 예를 들어 10이 있다면 다음과 같은 과정으로 1이 됩니다.
10 / 2 = 5
2 / 2 = 1
=> [192일차] 채연우 / 1로 만들기

2st/Riyeon/택배상자.java
| 택배상자 | 프로그래머스 | Level.2 |
<hr/>
- 택배상자 : 영재는 택배상자를 트럭에 싣는 일을 합니다. 영재가 실어야 하는 택배상자는 크기가 모두 같으며 1번 상자부터 n번 상자까지 번호가 증가하는 순서대로 컨테이너 벨트에 일렬로 놓여 영재에게 전달됩니다. 컨테이너 벨트는 한 방향으로만 진행이 가능해서 벨트에 놓인 순서대로(1번 상자부터) 상자를 내릴 수 있습니다. 하지만 컨테이너 벨트에 놓인 순서대로 택배상자를 내려 바로 트럭에 싣게 되면 택배 기사님이 배달하는 순서와 택배상자가 실려 있는 순서가 맞지 않아 배달에 차질이 생깁니다. 따라서 택배 기사님이 미리 알려준 순서에 맞게 영재가 택배상자를 실어야 합니다.
만약 컨테이너 벨트의 맨 앞에 놓인 상자가 현재 트럭에 실어야 하는 순서가 아니라면 그 상자를 트럭에 실을 순서가 될 때까지 잠시 다른 곳에 보관해야 합니다. 하지만 고객의 물건을 함부로 땅에 둘 수 없어 보조 컨테이너 벨트를 추가로 설치하였습니다. 보조 컨테이너 벨트는 앞 뒤로 이동이 가능하지만 입구 외에 다른 면이 막혀 있어서 맨 앞의 상자만 뺄 수 있습니다(즉, 가장 마지막에 보조 컨테이너 벨트에 보관한 상자부터 꺼내게 됩니다). 보조 컨테이너 벨트를 이용해도 기사님이 원하는 순서대로 상자를 싣지 못 한다면, 더 이상 상자를 싣지 않습니다.
택배 기사님이 원하는 상자 순서를 나타내는 정수 배열 order가 주어졌을 때, 영재가 몇 개의 상자를 실을 수 있는지 return 하는 solution …
=> [192일차] 김리연 / 택배상자

3st/Seojun/rny_string.java
<hr/>
- rny_string : 'm'과 "rn"이 모양이 비슷하게 생긴 점을 활용해 문자열에 장난을 하려고 합니다. 문자열 rny_string이 주어질 때, rny_string의 모든 'm'을 "rn"으로 바꾼 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [94일차] 김서준 / rny_string

3st/Juhee/이진수 더하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120885
| 이진수 더하기 | 프로그래머스 | Level.0 |
<hr/>
- 이진수 더하기 : 이진수를 의미하는 두 개의 문자열 bin1과 bin2가 매개변수로 주어질 때, 두 이진수의 합을 return하도록 solution 함수를 완성해주세요.
=> [94일차] 최주희 / 이진수 더하기

3st/Jaeyoung/중앙값 구하기.java
=> [94일차] 박재영 / 중앙값 구하기

3st/Jaehee/시험 성적.java
https://www.acmicpc.net/submit/9498/87834633
| 시험 성적| 백준 | Level.0 |
<hr/>
- 시험 성적: 시험 점수를 입력받아 90 ~ 100점은 A, 80 ~ 89점은 B, 70 ~ 79점은 C, 60 ~ 69점은 D, 나머지 점수는 F를 출력하는 프로그램을 작성하시오.
=> [94일] 이제희/시험 성적

2st/Yeonwoo/조건에 맞게 수열 변환하기 1.c++
| 조건에 맞게 수열 변환하기 1 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181882?language=cpp) |
<hr/>
- 조건에 맞게 수열 변환하기 1 : 정수 배열 arr가 주어집니다. arr의 각 원소에 대해 값이 50보다 크거나 같은 짝수라면 2로 나누고, 50보다 작은 홀수라면 2를 곱합니다. 그 결과인 정수 배열을 return 하는 solution 함수를 완성해 주세요.
=> [193일차] 채연우 / 조건에 맞게 수열 변환하기 1

3st/Jaehee/사분면 고르기.java, 3st/Jaehee/윤년.java
https://www.acmicpc.net/submit/2753/87879157
| 윤년 | 백준 | Level.0 |
<hr/>
- 윤년 : 연도가 주어졌을 때, 윤년이면 1, 아니면 0을 출력하는 프로그램을 작성하시오.
윤년은 연도가 4의 배수이면서, 100의 배수가 아닐 때 또는 400의 배수일 때이다.
예를 들어, 2012년은 4의 배수이면서 100의 배수가 아니라서 윤년이다. 1900년은 100의 배수이고 400의 배수는 아니기 때문에 윤년이 아니다. 하지만, 2000년은 400의 배수이기 때문에 윤년이다.
=> [95일] 이제희/윤년

3st/Seojun/5명씩.java
=> [95일차] 김서준 / 5명씩

3st/Jaeyoung/이어 붙인 수.java
=> [95일차] 박재영 / 이어 붙인 수

2st/Yeonwoo/조건 문자열.c++
| 조건 문자열 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181934?language=cpp) |
<hr/>
- 조건 문자열 : 문자열에 따라 다음과 같이 두 수의 크기를 비교하려고 합니다.
두 수가 n과 m이라면
">", "=" : n >= m
"<", "=" : n <= m
">", "!" : n > m
"<", "!" : n < m
두 문자열 ineq와 eq가 주어집니다. ineq는 "<"와 ">"중 하나고, eq는 "="와 "!"중 하나입니다. 그리고 두 정수 n과 m이 주어질 때, n과 m이 ineq와 eq의 조건에 맞으면 1을 아니면 0을 return하도록 solution 함수를 완성해주세요.
=> [194일차] 채연우 / 조건 문자열

3st/Juhee/잘라서 배열로 저장하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120913
| 잘라서 배열로 저장하기 | 프로그래머스 | Level.0 |
<hr/>
- 잘라서 배열로 저장하기 : 문자열 my_str과 n이 매개변수로 주어질 때, my_str을 길이 n씩 잘라서 저장한 배열을 return하도록 solution 함수를 완성해주세요.
=> [96일차] 최주희 / 잘라서 배열로 저장하기

2st/Yeonwoo/길이에 따른 연산.c++
| 길이에 따른 연산 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181879?language=cpp) |
<hr/>
=> [195일차] 채연우 / 길이에 따른 연산

3st/Jaehee/알람 시계.java
https://www.acmicpc.net/submit/2884/87917340
| 알람 시계 | 백준 | Level.0 |
<hr/>
- 알람 시계 : 상근이는 매일 아침 알람을 듣고 일어난다. 알람을 듣고 바로 일어나면 다행이겠지만, 항상 조금만 더 자려는 마음 때문에 매일 학교를 지각하고 있다.
상근이는 모든 방법을 동원해보았지만, 조금만 더 자려는 마음은 그 어떤 것도 없앨 수가 없었다.
이런 상근이를 불쌍하게 보던 창영이는 자신이 사용하는 방법을 추천해 주었다.
바로 "45분 일찍 알람 설정하기"이다.
이 방법은 단순하다. 원래 설정되어 있는 알람을 45분 앞서는 시간으로 바꾸는 것이다. 어차피 알람 소리를 들으면, 알람을 끄고 조금 더 잘 것이기 때문이다. 이 방법을 사용하면, 매일 아침 더 잤다는 기분을 느낄 수 있고, 학교도 지각하지 않게 된다.
현재 상근이가 설정한 알람 시각이 주어졌을 때, 창영이의 방법을 사용한다면, 이를 언제로 고쳐야 하는지 구하는 프로그램을 작성하시오.
=> [96일] 이제희/알람 시계

3st/Juhee/공 던지기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120843
| 공 던지기 | 프로그래머스 | Level.0 |
<hr/>
- 공 던지기 : 머쓱이는 친구들과 동그랗게 서서 공 던지기 게임을 하고 있습니다. 공은 1번부터 던지며 오른쪽으로 한 명을 건너뛰고 그다음 사람에게만 던질 수 있습니다. 친구들의 번호가 들어있는 정수 배열 numbers와 정수 K가 주어질 때, k번째로 공을 던지는 사람의 번호는 무엇인지 return 하도록 solution 함수를 완성해보세요.
=> [97일차] 최주희 / 공 던지기

3st/Jaehee/구구단.java
https://www.acmicpc.net/submit/2739/87949107
| 구구단 | 백준 | Level.0 |
<hr/>
=> [97일] 이제희/구구단

3st/Seojun/공백으로 구분하기.java
| 공백으로 구분하기 1 | 프로그래머스 | Level.1 |
<hr/>
- 공백으로 구분하기 1 : 설명
=> [96일차] 김서준 / 공백으로 구분하기 1

3st/Jaehee/A+B - 3.java
https://www.acmicpc.net/submit/10950/87985173
| A+B - 3| 백준 | Level.0 |
<hr/>
- A+B - 3: 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [98일] 이제희/A+B - 3

3st/Juhee/문자열 계산하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120902
| 문자열 계산하기| 프로그래머스 | Level.0 |
<hr/>
- 문자열 계산하기: my_string은 "3 + 5"처럼 문자열로 된 수식입니다. 문자열 my_string이 매개변수로 주어질 때, 수식을 계산한 값을 return 하는 solution 함수를 완성해주세요.
=> [98일차] 최주희 / 문자열 계산하기

3st/Hyeonseo/com/나머지 구하기.cpp, 3st/Hyeonseo/com/두 수의 차.cpp, 3st/Hyeonseo/com/숫자 비교하기.cpp, 3st/Hyeonseo/programmer/A 강조하기.java, 3st/Hyeonseo/programmer/대문자와 소문자.java, 3st/Hyeonseo/programmer/배열자르기.java, 3st/Hyeonseo/programmer/소수 찾기.java, 3st/Hyeonseo/programmer/약수 구하기.java, 3st/Hyeonseo/programmer/완주하지 못한 선수.java, 3st/Hyeonseo/programmer/특수 문자 제거하기.java, 3st/Hyeonseo/programmer/편지.cpp
https://school.programmers.co.kr/learn/courses/30/lessons/120898?language=cpp
<hr/>
- 편지 : 머쓱이는 할머니께 생신 축하 편지를 쓰려고 합니다. 할머니가 보시기 편하도록 글자 한 자 한 자를 가로 2cm 크기로 적으려고 하며, 편지를 가로로만 적을 때, 축하 문구 message를 적기 위해 필요한 편지지의 최소 가로길이를 return 하도록 solution 함수를 완성해주세요.
=> [98일차] 조현서 / 편지

3st/Seojun/n개의간격의 원소들.java
=> [98일차] 김서 / n개 간격의 원소들

2st/Yeonwoo/카운트 다운.c++
| 카운트 다운 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181899) |
<hr/>
=> [197일차] 채연우 / 카운트 다운

3st/Seojun/n 번째 원소까지.java
| n 번째 원소까지  | 프로그래머스 | Level.0 |
<hr/>
- n 번째 원소까지  : 정수 리스트 num_list와 정수 n이 주어질 때, num_list의 첫 번째 원소부터 n 번째 원소까지의 모든 원소를 담은 리스트를 return하도록 solution 함수를 완성해주세요.
=> [100일차] 김서준 /  n 번째 원소까지 

3st/Jaeyoung/개미 군단.java
<hr/>
- 개미 군단 : 개미 군단이 사냥을 나가려고 합니다. 개미군단은 사냥감의 체력에 딱 맞는 병력을 데리고 나가려고 합니다. 장군개미는 5의 공격력을, 병정개미는 3의 공격력을 일개미는 1의 공격력을 가지고 있습니다. 예를 들어 체력 23의 여치를 사냥하려고 할 때, 일개미 23마리를 데리고 가도 되지만, 장군개미 네 마리와 병정개미 한 마리를 데리고 간다면 더 적은 병력으로 사냥할 수 있습니다. 사냥감의 체력 hp가 매개변수로 주어질 때, 사냥감의 체력에 딱 맞게 최소한의 병력을 구성하려면 몇 마리의 개미가 필요한지를 return하도록 solution 함수를 완성해주세요.
=> [99일차] 박재영 / 개미 군단

2st/Yeonwoo/카운트 업.c++
| 카운트 업 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181920) |
<hr/>
=> [198일차] 채연우 / 카운트 업

3st/Jaeyoung/문자 반복 출력하기.java
=> [100일차] 박재영 / 문자 반복 출력하기

3st/Juhee/영어가 싫어요.java
https://school.programmers.co.kr/learn/courses/30/lessons/120894
| 영어가 싫어요| 프로그래머스 | Level.0 |
<hr/>
- 영어가 싫어요: 영어가 싫은 머쓱이는 영어로 표기되어있는 숫자를 수로 바꾸려고 합니다. 문자열 numbers가 매개변수로 주어질 때, numbers를 정수로 바꿔 return 하도록 solution 함수를 완성해 주세요.
=> [100일차] 최주희 / 영어가 싫어요

3st/Jaehee/합.java
https://www.acmicpc.net/submit/8393/88054258
| 합| 백준 | Level.0 |
<hr/>
- 합: n이 주어졌을 때, 1부터 n까지 합을 구하는 프로그램을 작성하시오.
=> [100일] 이제희/합

3st/Jaehee/별 찍기 - 1.java
https://www.acmicpc.net/submit/2438/88094291
| 별 찍기 - 1| 백준 | Level.1 |
<hr/>
- 별 찍기 - 1: 첫째 줄에는 별 1개, 둘째 줄에는 별 2개, N번째 줄에는 별 N개를 찍는 문제
=> [101일] 이제희/별 찍기 - 1

3st/Seojun/n 번째 원소부터.java
| n 번째 원소부터 | 프로그래머스 | Level.0 |
<hr/>
=> [101일차] 김서준 / n 번째 원소부터

3st/Juhee/구슬을 나누는 경우의 수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120840
| 구슬을 나누는 경우의 수 | 프로그래머스 | Level.0 |
<hr/>
- 구슬을 나누는 경우의 수 : 머쓱이는 구슬을 친구들에게 나누어주려고 합니다. 구슬은 모두 다르게 생겼습니다. 머쓱이가 갖고 있는 구슬의 개수 balls와 친구들에게 나누어 줄 구슬 개수 share이 매개변수로 주어질 때, balls개의 구슬 중 share개의 구슬을 고르는 가능한 모든 경우의 수를 return 하는 solution 함수를 완성해주세요.
=> [101일차] 최주희 / 구슬을 나누는 경우의 수

2st/Yeonwoo/n의 배수.c++
| n의 배수 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181937) |
<hr/>
- n의 배수 : 정수 num과 n이 매개 변수로 주어질 때, num이 n의 배수이면 1을 return n의 배수가 아니라면 0을 return하도록 solution 함수를 완성해주세요.
=> [200일차] 채연우 / n의 배수

3st/Jaeyoung/가위 바위 보.java, 3st/Jaeyoung/공배수.java
| 가위 바위 보 | 프로그래머스 | Level.0 |
<hr/>
- 가위 바위 보 : 가위는 2 바위는 0 보는 5로 표현합니다. 가위 바위 보를 내는 순서대로 나타낸 문자열 rsp가 매개변수로 주어질 때, rsp에 저장된 가위 바위 보를 모두 이기는 경우를 순서대로 나타낸 문자열을 return하도록 solution 함수를 완성해보세요.
=> [102일차] 박재영 / 가위 바위 보

3st/Juhee/외계어 사전.java
https://school.programmers.co.kr/learn/courses/30/lessons/120869
| 외계어 사전 | 프로그래머스 | Level.0 |
<hr/>
- 외계어 사전 : PROGRAMMERS-962 행성에 불시착한 우주비행사 머쓱이는 외계행성의 언어를 공부하려고 합니다. 알파벳이 담긴 배열 spell과 외계어 사전 dic이 매개변수로 주어집니다. spell에 담긴 알파벳을 한번씩만 모두 사용한 단어가 dic에 존재한다면 1, 존재하지 않는다면 2를 return하도록 solution 함수를 완성해주세요.
=> [102일차] 최주희 / 외계어 사전

3st/Jaehee/별 찍기 - 2.java
https://www.acmicpc.net/submit/2439/88145897
| 별 찍기 - 2| 백준 | Level.0 |
<hr/>
- 별 찍기 - 2: 첫째 줄에는 별 1개, 둘째 줄에는 별 2개, N번째 줄에는 별 N개를 찍는 문제
=> [102일] 이제희/별 찍기 - 2

2st/Yeonwoo/더 크게 합치기.c++
| 더 크게 합치기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181939) |
<hr/>
- 더 크게 합치기 : 연산 ⊕는 두 정수에 대한 연산으로 두 정수를 붙여서 쓴 값을 반환합니다. 예를 들면 다음과 같습니다.
12 ⊕ 3 = 123
3 ⊕ 12 = 312
양의 정수 a와 b가 주어졌을 때, a ⊕ b와 b ⊕ a 중 더 큰 값을 return 하는 solution 함수를 완성해 주세요.
단, a ⊕ b와 b ⊕ a가 같다면 a ⊕ b를 return 합니다.
=> [201일차] 채연우 / 더 크게 합치기

3st/Jaeyoung/문자열 안에 문자열.java
| 문자열 안에 문자열 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 안에 문자열 : 문자열 str1, str2가 매개변수로 주어집니다. str1 안에 str2가 있다면 1을 없다면 2를 return하도록 solution 함수를 완성해주세요.
=> [103일차] 박재영 / 문자열 안에 문자열

3st/Seojun/모음 제거.java, 3st/Seojun/접두사인지 확인하기.java
<hr/>
- 모음 제거 : 영어에선 a, e, i, o, u 다섯 가지 알파벳을 모음으로 분류합니다. 문자열 my_string이 매개변수로 주어질 때 모음을 제거한 문자열을 return하도록 solution 함수를 완성해주세요.
=> [103일차] 김서준 / 모음 제거

3st/Jaehee/개수 세기.java
https://www.acmicpc.net/submit/10807/88178774
| 개수 세기| 백준 | Level.0 |
<hr/>
- 개수 세기: 총 N개의 정수가 주어졌을 때, 정수 v가 몇 개인지 구하는 프로그램을 작성하시오.
=> [103일] 이제희/개수 세기

3st/Juhee/OX퀴즈.java
https://school.programmers.co.kr/learn/courses/30/lessons/120907
| OX퀴즈 | 프로그래머스 | Level.0 |
<hr/>
- OX퀴즈 : 덧셈, 뺄셈 수식들이 'X [연산자] Y = Z' 형태로 들어있는 문자열 배열 quiz가 매개변수로 주어집니다. 수식이 옳다면 "O"를 틀리다면 "X"를 순서대로 담은 배열을 return하도록 solution 함수를 완성해주세요.
=> [103일차] 최주희 / OX퀴즈

2st/Yeonwoo/배열의 원소만큼 추가하기.c++
| 배열의 원소만큼 추가하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181861) |
<hr/>
=> [202일차] 채연우 / 배열의 원소만큼 추가하기

3st/Juhee/캐릭터의 좌표.java
https://school.programmers.co.kr/learn/courses/30/lessons/120861
| 캐릭터의 좌표 | 프로그래머스 | Level.0 |
<hr/>
- 캐릭터의 좌표 : 머쓱이는 RPG게임을 하고 있습니다. 게임에는 up, down, left, right 방향키가 있으며 각 키를 누르면 위, 아래, 왼쪽, 오른쪽으로 한 칸씩 이동합니다. 예를 들어 [0,0]에서 up을 누른다면 캐릭터의 좌표는 [0, 1], down을 누른다면 [0, -1], left를 누른다면 [-1, 0], right를 누른다면 [1, 0]입니다. 머쓱이가 입력한 방향키의 배열 keyinput와 맵의 크기 board이 매개변수로 주어집니다. 캐릭터는 항상 [0,0]에서 시작할 때 키 입력이 모두 끝난 뒤에 캐릭터의 좌표 [x, y]를 return하도록 solution 함수를 완성해주세요.
[0, 0]은 board의 정 중앙에 위치합니다. 예를 들어 board의 가로 크기가 9라면 캐릭터는 왼쪽으로 최대 [-4, 0]까지 오른쪽으로 최대 [4, 0]까지 이동할 수 있습니다.
=> [104일차] 최주희 / 캐릭터의 좌표

3st/Seojun/문자열 앞의 n글자.java
| 문자열의 앞의 n글자 | 프로그래머스 |  Level.0 |
<hr/>
=> [104일차] 김서준 / 문자열의 앞의 n글자

2st/Yeonwoo/배열의 길이에 따라 다른 연산하기.c++
| 배열의 길이에 따라 다른 연산하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181854) |
<hr/>
=> [203일차] 채연우 / 배열의 길이에 따라 다른 연산하기

3st/Jaehee/A+B - 5.java, 3st/Jaehee/별 찍기 - 7.java
https://www.acmicpc.net/submit/10952/88263002
| A+B - 5| 백준 | Level.0 |
<hr/>
- A+B - 5: 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [105일] 이제희/A+B - 5

3st/Seojun/주사위의 개수.java, 3st/Seojun/최댓값 만들기 (2).java
| 주사위의 개수 | 프로그래머스 | Level.0 |
<hr/>
- 주사위의 개수 : 머쓱이는 직육면체 모양의 상자를 하나 가지고 있는데 이 상자에 정육면체 모양의 주사위를 최대한 많이 채우고 싶습니다. 상자의 가로, 세로, 높이가 저장되어있는 배열 box와 주사위 모서리의 길이 정수 n이 매개변수로 주어졌을 때, 상자에 들어갈 수 있는 주사위의 최대 개수를 return 하도록 solution 함수를 완성해주세요.
=> [105일차] 김서준 / 주사위의 개수

3st/Juhee/다항식 더하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120863
| 다항식 더하기 | 프로그래머스 | Level.0 |
<hr/>
- 다항식 더하기 : 한 개 이상의 항의 합으로 이루어진 식을 다항식이라고 합니다. 다항식을 계산할 때는 동류항끼리 계산해 정리합니다. 덧셈으로 이루어진 다항식 polynomial이 매개변수로 주어질 때, 동류항끼리 더한 결괏값을 문자열로 return 하도록 solution 함수를 완성해보세요. 같은 식이라면 가장 짧은 수식을 return 합니다.
=> [105일차] 최주희 / 다항식 더하기

2st/Yeonwoo/rny_string.c++
| rny_string | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181863) |
<hr/>
- rny_string : 'm'과 "rn"이 모양이 비슷하게 생긴 점을 활용해 문자열에 장난을 하려고 합니다. 문자열 rny_string이 주어질 때, rny_string의 모든 'm'을 "rn"으로 바꾼 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [204일차] 채연우 / rny_string

2st/Yeonwoo/문자 리스트를 문자열로 변환하기.c++
| 문자 리스트를 문자열로 변환하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181941) |
<hr/>
=> [205일차] 채연우 / 문자 리스트를 문자열로 변환하기

3st/Jaehee/문자와 문자열.java
https://www.acmicpc.net/submit/27866/88324157
| 문자와 문자열| 백준 | Level.0 |
<hr/>
- 문자와 문자열: 단어 S와 정수 i가 주어졌을 때, S의 i번째 글자를 출력하는 프로그램을 작성하시오.
=> [105] 이제희/문자와 문자열

3st/Seojun/최댓값 만들기 (2).java
| 최댓값 만들기 (2) |프로그래머스 | Level.0 |
<hr/>
- 최댓값 만들기 (2) : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소 중 두 개를 곱해 만들 수 있는 최댓값을 return하도록 solution 함수를 완성해주세요.
=> [106일] 김서준 / 최댓값 만들기 (2)

3st/Seojun/인덱스 바꾸기.java
| 인덱스 바꾸기 | 프로그래머스 | Level.0 |
<hr/>
- 인덱스 바꾸기 : 문자열 my_string과 정수 num1, num2가 매개변수로 주어질 때, my_string에서 인덱스 num1과 인덱스 num2에 해당하는 문자를 바꾼 문자열을 return 하도록 solution 함수를 완성해보세요.
=> [107일차] 김서준 / 인덱스 바꾸기

3st/Jaehee/단어 길이 재기.java
https://www.acmicpc.net/submit/2743/88369603
| 단어 길이 재기| 백준 | Level.0 |
<hr/>
- 단어 길이 재기: 알파벳으로만 이루어진 단어를 입력받아, 그 길이를 출력하는 프로그램을 작성하시오.
=> [107일} 이제희/단어 길이 재기

3st/Hyeonseo/programmer/짝수의 합.cpp
https://school.programmers.co.kr/learn/courses/30/lessons/120831?language=cpp
| 짝수의 합| 프로그래머스 | Level.0 |
<hr/>
- 짝수의 합: 정수 n이 주어질 때, n이하의 짝수를 모두 더한 값을 return 하도록 solution 함수를 작성해주세요.
=> [107일차]  조현서 / 짝수의 합

2st/Yeonwoo/홀짝 구분하기.c++
| 홀짝 구분하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181944) |
<hr/>
=> [206일차] 채연우 / 홀짝 구분하기

3st/Juhee/종이 자르기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120922
| 종이 자르기 | 프로그래머스 | Level.0 |
<hr/>
- 종이 자르기 : 머쓱이는 큰 종이를 1 x 1 크기로 자르려고 합니다. 예를 들어 2 x 2 크기의 종이를 1 x 1 크기로 자르려면 최소 가위질 세 번이 필요합니다.
=> [107일차] 최주희 / 종이 자르기

3st/Jaehee/직사각형.java
https://www.acmicpc.net/submit/27323/88421804
| 직사각형 | 백준 | Level.0 |
<hr/>
- 직사각형: 정수 A, B 가 주어진다. 세로 길이가 A cm, 가로 길이가 B cm 인 아래와 같은 직사각형의 넓이를 cm2 단위로 구하시오.
=> [108일} 이제희/직사각형

3st/Seojun/약수 구하기.java
=> [108일차] 김서준 / 약수 구하기

2st/Yeonwoo/n개 간격의 원소들.c++
| n개 간격의 원소들 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181888) |
<hr/>
=> [207일차] 채연우 / n개 간격의 원소들

3st/Jaehee/A+B - 4.java
https://www.acmicpc.net/submit/10951/88467625
| A+B - 4| 백준 | Level.0 |
<hr/>
- A+B - 4: 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [109} 이제희/A+B - 4

3st/Juhee/연속된 수의 합.java
https://school.programmers.co.kr/learn/courses/30/lessons/120923
| 연속된 수의 합 | 프로그래머스 | Level.0 |
<hr/>
- 연속된 수의 합 : 연속된 세 개의 정수를 더해 12가 되는 경우는 3, 4, 5입니다. 두 정수 num과 total이 주어집니다. 연속된 수 num개를 더한 값이 total이 될 때, 정수 배열을 오름차순으로 담아 return하도록 solution함수를 완성해보세요.
=> [109일차] 최주희 / 연속된 수의 합

2st/Yeonwoo/n 번째 원소부터.c++
| n 번째 원소부터 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181892) |
<hr/>
=> [208일차] 채연우 / n 번째 원소부터

3st/Jaehee/주사위 세개.java
https://www.acmicpc.net/submit/2480
| 주사위 세개| 백준 | Level.0 |
<hr/>
- 주사위 세개: 1에서부터 6까지의 눈을 가진 3개의 주사위를 던져서 다음과 같은 규칙에 따라 상금을 받는 게임이 있다.
같은 눈이 3개가 나오면 10,000원+(같은 눈)×1,000원의 상금을 받게 된다.
같은 눈이 2개만 나오는 경우에는 1,000원+(같은 눈)×100원의 상금을 받게 된다.
모두 다른 눈이 나오는 경우에는 (그 중 가장 큰 눈)×100원의 상금을 받게 된다.
예를 들어, 3개의 눈 3, 3, 6이 주어지면 상금은 1,000+3×100으로 계산되어 1,300원을 받게 된다. 또 3개의 눈이 2, 2, 2로 주어지면 10,000+2×1,000 으로 계산되어 12,000원을 받게 된다. 3개의 눈이 6, 2, 5로 주어지면 그중 가장 큰 값이 6이므로 6×100으로 계산되어 600원을 상금으로 받게 된다.
3개 주사위의 나온 눈이 주어질 때, 상금을 계산하는 프로그램을 작성 하시오.
=> [110일} 이제희/주사위 세개

3st/Seojun/꼬리 문자열.java, 3st/Seojun/조건에 맞게 수열 볂환하기.java
<hr/>
- 꼬리 문자열 : 문자열들이 담긴 리스트가 주어졌을 때, 모든 문자열들을 순서대로 합친 문자열을 꼬리 문자열이라고 합니다. 꼬리 문자열을 만들 때 특정 문자열을 포함한 문자열은 제외시키려고 합니다. 예를 들어 문자열 리스트 ["abc", "def", "ghi"]가 있고 문자열 "ef"를 포함한 문자열은 제외하고 꼬리 문자열을 만들면 "abcghi"가 됩니다.
문자열 리스트 str_list와 제외하려는 문자열 ex가 주어질 때, str_list에서 ex를 포함한 문자열을 제외하고 만든 꼬리 문자열을 return하도록 solution 함수를 완성해주세요.
=> [110일차] 김서준 / 꼬리 문자열

3st/Juhee/다음에 올 숫자.java
https://school.programmers.co.kr/learn/courses/30/lessons/120924
| 다음에 올 숫자 | 프로그래머스 | Level.0 |
<hr/>
- 다음에 올 숫자 : 등차수열 혹은 등비수열 common이 매개변수로 주어질 때, 마지막 원소 다음으로 올 숫자를 return 하도록 solution 함수를 완성해보세요.
=> [110일차] 최주희 / 다음에 올 숫자

2st/Yeonwoo/5명씩.c++
| 5명씩 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181886) |
<hr/>
=> [209일차] 채연우 / 5명씩

3st/Jaeyoung/피자 나눠 먹기 (3).java
| 피자 나눠 먹기 (3) | 프로그래머스 | Level.0 |
<hr/>
- 피자 나눠 먹기 (3) : 머쓱이네 피자가게는 피자를 두 조각에서 열 조각까지 원하는 조각 수로 잘라줍니다. 피자 조각 수 slice와 피자를 먹는 사람의 수 n이 매개변수로 주어질 때, n명의 사람이 최소 한 조각 이상 피자를 먹으려면 최소 몇 판의 피자를 시켜야 하는지를 return 하도록 solution 함수를 완성해보세요.
=> [110일차] 박재영 / 피자 나눠 먹기 (3)

3st/Jaehee/아스키 코드.java
https://www.acmicpc.net/submit/11654/88650509
| 아스키 코드| 백준 | Level.0 |
<hr/>
- 아스키 코드: 알파벳 소문자, 대문자, 숫자 0-9중 하나가 주어졌을 때, 주어진 글자의 아스키 코드값을 출력하는 프로그램을 작성하시오.
=> [111일} 이제희/아스키 코드

3st/Juhee/안전지대.java
https://school.programmers.co.kr/learn/courses/30/lessons/120866
| 안전지대 | 프로그래머스 | Level.0 |
<hr/>
- 안전지대 : 다음 그림과 같이 지뢰가 있는 지역과 지뢰에 인접한 위, 아래, 좌, 우 대각선 칸을 모두 위험지역으로 분류합니다.
지뢰는 2차원 배열 board에 1로 표시되어 있고 board에는 지뢰가 매설 된 지역 1과, 지뢰가 없는 지역 0만 존재합니다.
지뢰가 매설된 지역의 지도 board가 매개변수로 주어질 때, 안전한 지역의 칸 수를 return하도록 solution 함수를 완성해주세요.
=> [111일차] 최주희 / 안전지대

3st/Seojun/부분 문자열.java
| 부분  문자열 | 프로그래머스 | Level.0 |
<hr/>
- 부분  문자열 : 어떤 문자열 A가 다른 문자열 B안에 속하면 A를 B의 부분 문자열이라고 합니다. 예를 들어 문자열 "abc"는 문자열 "aabcc"의 부분 문자열입니다.
문자열 str1과 str2가 주어질 때, str1이 str2의 부분 문자열이라면 1을 부분 문자열이 아니라면 0을 return하도록 solution 함수를 완성해주세요.
=> [111일차] 김서준 / 부분  문자열

3st/Jaehee/A+B - 7.java
https://www.acmicpc.net/problem/11021
| A+B - 7 | 백준 | Level.0 |
<hr/>
- A+B - 7 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [112일} 이제희/A+B - 7

3st/Juhee/유한소수 판별하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120878
| 유한소수 판별하기 | 프로그래머스 | Level.0 |
<hr/>
- 유한소수 판별하기 : 소수점 아래 숫자가 계속되지 않고 유한개인 소수를 유한소수라고 합니다. 분수를 소수로 고칠 때 유한소수로 나타낼 수 있는 분수인지 판별하려고 합니다. 유한소수가 되기 위한 분수의 조건은 다음과 같습니다.
기약분수로 나타내었을 때, 분모의 소인수가 2와 5만 존재해야 합니다.
두 정수 a와 b가 매개변수로 주어질 때, a/b가 유한소수이면 1을, 무한소수라면 2를 return하도록 solution 함수를 완성해주세요.
=> [112일차] 최주희 / 유한소수 판별하기

3st/Seojun/부분문자열인지 확인하기.java
| 부분 문자열인지 확인하기 | 프로그래머스 | Level.0 |
<hr/>
- 부분 문자열인지 확인하기 : 부분 문자열이란 문자열에서 연속된 일부분에 해당하는 문자열을 의미합니다. 예를 들어, 문자열 "ana", "ban", "anana", "banana", "n"는 모두 문자열 "banana"의 부분 문자열이지만, "aaa", "bnana", "wxyz"는 모두 "banana"의 부분 문자열이 아닙니다.
문자열 my_string과 target이 매개변수로 주어질 때, target이 문자열 my_string의 부분 문자열이라면 1을, 아니라면 0을 return 하는 solution 함수를 작성해 주세요.
=> [112일차] 김서준 / 부분 문자열인지 확인하기

3st/Jaehee/순서쌍의 개수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120836?language=java
<hr/>
=> [113일} 이제희/순서쌍의 개수

2st/Yeonwoo/문자열의 앞의 n글자.c++
| 문자열의 앞의 n글자 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181907) |
<hr/>
=> [212일차] 채연우 / 문자열의 앞의 n글자

3st/Juhee/등수 매기기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120882
| 등수 매기기 | 프로그래머스 | Level.0 |
<hr/>
- 등수 매기기 : 영어 점수와 수학 점수의 평균 점수를 기준으로 학생들의 등수를 매기려고 합니다. 영어 점수와 수학 점수를 담은 2차원 정수 배열 score가 주어질 때, 영어 점수와 수학 점수의 평균을 기준으로 매긴 등수를 담은 배열을 return하도록 solution 함수를 완성해주세요.
=> [113일차] 최주희 / 등수 매기기

3st/Juhee/특이한 정렬.java
https://school.programmers.co.kr/learn/courses/30/lessons/120880
| 특이한 정렬 | 프로그래머스 | Level.0 |
<hr/>
- 특이한 정렬 : 정수 n을 기준으로 n과 가까운 수부터 정렬하려고 합니다. 이때 n으로부터의 거리가 같다면 더 큰 수를 앞에 오도록 배치합니다. 정수가 담긴 배열 numlist와 정수 n이 주어질 때 numlist의 원소를 n으로부터 가까운 순서대로 정렬한 배열을 return하도록 solution 함수를 완성해주세요.
=> [114일차] 최주희 / 특이한 정렬

2st/Riyeon/조건별로 분류하여 주문상태 출력하기.sql
| 조건별로 분류하여 주문상태 출력하기 | 프로그래머스 | Level.3 |
<hr/>
- 조건별로 분류하여 주문상태 출력하기 : FOOD_ORDER 테이블에서 2022년 5월 1일을 기준으로 주문 ID, 제품 ID, 출고일자, 출고여부를 조회하는 SQL문을 작성해주세요. 출고여부는 2022년 5월 1일까지 출고완료로 이 후 날짜는 출고 대기로 미정이면 출고미정으로 출력해주시고, 결과는 주문 ID를 기준으로 오름차순 정렬해주세요.
=> [213일차] 김리연 / 조건별로 분류하여 주문상태 출력하기

3st/Juhee/저주의 숫자 3.java
https://school.programmers.co.kr/learn/courses/30/lessons/120871
| 저주의 숫자 3 | 프로그래머스 | Level.0 |
<hr/>
- 저주의 숫자 3 : 3x 마을 사람들은 3을 저주의 숫자라고 생각하기 때문에 3의 배수와 숫자 3을 사용하지 않습니다. 3x 마을 사람들의 숫자는 다음과 같습니다. 정수 n이 매개변수로 주어질 때, n을 3x 마을에서 사용하는 숫자로 바꿔 return하도록 solution 함수를 완성해주세요.
=> [115일차] 최주희 / 저주의 숫자 3

2st/Yeonwoo/이어 붙인 수.c++
| 이어 붙인 수 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181928) |
<hr/>
=> [214일차] 채연우 / 이어 붙인 수

3st/Jaehee/각도기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120829
| 각도기| 프로그래머스 | Level.0 |
<hr/>
- 각도기: 각에서 0도 초과 90도 미만은 예각, 90도는 직각, 90도 초과 180도 미만은 둔각 180도는 평각으로 분류합니다. 각 angle이 매개변수로 주어질 때 예각일 때 1, 직각일 때 2, 둔각일 때 3, 평각일 때 4를 return하도록 solution 함수를 완성해주세요.
=> [115일} 이제희/각도기

2st/Yeonwoo/문자열 돌리기.c++
| 문자열 돌리기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181945) |
<hr/>
- 문자열 돌리기 : 문자열 str이 주어집니다.
=> [215일차] 채연우 / 문자열 돌리기

3st/Seojun/뒤에서 5등위로.java
https://school.programmers.co.kr/learn/courses/30/lessons/181852
|  뒤에서 5등 위로 | 프로그래머스 | Level.0 |
<hr/>
-  뒤에서 5등 위로 : 정수로 이루어진 리스트 num_list가 주어집니다. num_list에서 가장 작은 5개의 수를 제외한 수들을 오름차순으로 담은 리스트를 return하도록 solution 함수를 완성해주세요.
=> [115일차] 김서준 /  뒤에서 5등 위로 

3st/Jaehee/특정 문자 제거하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120826
| 특정 문자 제거하기| 프로그래머스 | Level.0 |
<hr/>
- 특정 문자 제거하기: 문자열 my_string과 문자 letter이 매개변수로 주어집니다. my_string에서 letter를 제거한 문자열을 return하도록 solution 함수를 완성해주세요.
=> [115일} 이제희/특정 문자 제거하기

3st/Hyeonseo/programmer/자릿수 더하기.cpp
https://school.programmers.co.kr/learn/courses/30/lessons/12931?language=cpp
| 자릿수 더하기 | 프로그래머스 | Level.1 |
<hr/>
- 자릿수 더하기 : 자연수 N이 주어지면, N의 각 자릿수의 합을 구해서 return 하는 solution 함수를 만들어 주세요.
예를들어 N = 123이면 1 + 2 + 3 = 6을 return 하면 됩니다.
=> [117일차] 조현서 / 자릿수 더하기 

2st/Yeonwoo/짝수와 홀수.c++
| 짝수와 홀수 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/12937) |
<hr/>
- 짝수와 홀수 : 정수 num이 짝수일 경우 "Even"을 반환하고 홀수인 경우 "Odd"를 반환하는 함수, solution을 완성해주세요.
=> [216일차] 채연우 / 짝수와 홀수

3st/Jaehee/외계행성의 나이.java
https://school.programmers.co.kr/learn/courses/30/lessons/120834
| 외계행성의 나이| 프로그래머스 | Level.0 |
<hr/>
- 외계행성의 나이 : 설명
=> [117일} 이제희/외계행성의 나이

3st/Seojun/배열의 원소만큼 추가하기.java
=> [117일차] 김서준 / 배열의 원소만큼 추가하기

3st/Seojun/문자열 바꿔서 착기.java
=> [118일차] 김서준 / 문자열 바꿔서 찾기

3st/Juhee/문자열 밀기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120921
| 문자열 밀기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 밀기 : 문자열 "hello"에서 각 문자를 오른쪽으로 한 칸씩 밀고 마지막 문자는 맨 앞으로 이동시키면 "ohell"이 됩니다. 이것을 문자열을 민다고 정의한다면 문자열 A와 B가 매개변수로 주어질 때, A를 밀어서 B가 될 수 있다면 밀어야 하는 최소 횟수를 return하고 밀어서 B가 될 수 없으면 -1을 return 하도록 solution 함수를 완성해보세요.
=> [118일차] 최주희 / 문자열 밀기

2st/Yeonwoo/평균 구하기.c++
| 평균 구하기 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/12944) |
<hr/>
=> [217일차] 채연우 / 평균 구하기

3st/Seojun/공백으로 구분하기 2.java
| 공백으로 구분하기 2 | 프로그래머스 | Level.0 |
<hr/>
- 공백으로 구분하기 2 : 단어가 공백 한 개 이상으로 구분되어 있는 문자열 my_string이 매개변수로 주어질 때, my_string에 나온 단어를 앞에서부터 순서대로 담은 문자열 배열을 return 하는 solution 함수를 작성해 주세요.
=> [119일차] 김서준 / 공백으로 구분하기 2

2st/Riyeon/대장균의 크기에 따라 분류하기 1.sql
| 대장균의 크기에 따라 분류하기 1 | 프로그래머스 | Level.3 |
<hr/>
- 대장균의 크기에 따라 분류하기 1 : 대장균 개체의 크기가 100 이하라면 'LOW', 100 초과 1000 이하라면 'MEDIUM', 1000 초과라면 'HIGH' 라고 분류합니다. 대장균 개체의 ID(ID) 와 분류(SIZE)를 출력하는 SQL 문을 작성해주세요.이때 결과는 개체의 ID 에 대해 오름차순 정렬해주세요.
=> [218일차] 김리연 / 대장균의 크기에 따라 분류하기 1

2st/Yeonwoo/문자열을 정수로 바꾸기.c++
| 문자열을 정수로 바꾸기 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/12925) |
<hr/>
- 문자열을 정수로 바꾸기 : 문자열 s를 숫자로 변환한 결과를 반환하는 함수, solution을 완성하세요.
제한 조건
s의 길이는 1 이상 5이하입니다.
s의 맨앞에는 부호(+, -)가 올 수 있습니다.
s는 부호와 숫자로만 이루어져있습니다.
s는 "0"으로 시작하지 않습니다.
=> [218일차] 채연우 / 문자열을 정수로 바꾸기

3st/Juhee/로그인 성공.java
https://school.programmers.co.kr/learn/courses/30/lessons/120883
| 로그인 성공? | 프로그래머스 | Level.0 |
<hr/>
- 로그인 성공? : 머쓱이는 프로그래머스에 로그인하려고 합니다. 머쓱이가 입력한 아이디와 패스워드가 담긴 배열 id_pw와 회원들의 정보가 담긴 2차원 배열 db가 주어질 때, 다음과 같이 로그인 성공, 실패에 따른 메시지를 return하도록 solution 함수를 완성해주세요.
아이디와 비밀번호가 모두 일치하는 회원정보가 있으면 "login"을 return합니다.
로그인이 실패했을 때 아이디가 일치하는 회원이 없다면 “fail”를, 아이디는 일치하지만 비밀번호가 일치하는 회원이 없다면 “wrong pw”를 return 합니다.
=> [119일차] 최주희 / 로그인 성공?

3st/Jaehee/머쓱이보다 키 큰 사람.java, 3st/Jaehee/편지.java
https://school.programmers.co.kr/learn/courses/30/lessons/120585
| 머쓱이보다 키 큰 사람| 프로그래머스 | Level.0 |
<hr/>
- 머쓱이보다 키 큰 사람: 머쓱이는 학교에서 키 순으로 줄을 설 때 몇 번째로 서야 하는지 궁금해졌습니다. 머쓱이네 반 친구들의 키가 담긴 정수 배열 array와 머쓱이의 키 height가 매개변수로 주어질 때, 머쓱이보다 키 큰 사람 수를 return 하도록 solution 함수를 완성해보세요.
=> [119일} 이제희/머쓱이보다 키 큰 사람

3st/Seojun/ad제거하기.java
| ad 제거하기 | 프로그래머스 | Level.0 |
<hr/>
- ad 제거하기 : 문자열 배열 strArr가 주어집니다. 배열 내의 문자열 중 "ad"라는 부분 문자열을 포함하고 있는 모든 문자열을 제거하고 남은 문자열을 순서를 유지하여 배열로 return 하는 solution 함수를 완성해 주세요
=> [120일] 김서준 / ad 제거하기

3st/Seojun/원하는 문자열찾기.java
| 원하는 문자열 찾기 | 프로그래머스 | Level.0 |
<hr/>
- 원하는 문자열 찾기 : 알파벳으로 이루어진 문자열 myString과 pat이 주어집니다. myString의 연속된 부분 문자열 중 pat이 존재하면 1을 그렇지 않으면 0을 return 하는 solution 함수를 완성해 주세요.
단, 알파벳 대문자와 소문자는 구분하지 않습니다.
=> [121일차] 김서준 / 원하는 문자열 찾기

2st/Yeonwoo/문자열 내 p와 y의 개수.c++
| 문자열 내 p와 y의 개수 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/12916) |
<hr/>
- 문자열 내 p와 y의 개수 : 대문자와 소문자가 섞여있는 문자열 s가 주어집니다. s에 'p'의 개수와 'y'의 개수를 비교해 같으면 True, 다르면 False를 return 하는 solution를 완성하세요. 'p', 'y' 모두 하나도 없는 경우는 항상 True를 리턴합니다. 단, 개수를 비교할 때 대문자와 소문자는 구별하지 않습니다.
예를 들어 s가 "pPoooyY"면 true를 return하고 "Pyy"라면 false를 return합니다.
=> [220일차] 채연우 / 문자열 내 p와 y의 개수

3st/Juhee/평행.java
https://school.programmers.co.kr/learn/courses/30/lessons/120875
| 평행 | 프로그래머스 | Level.0 |
<hr/>
- 평행 : 점 네 개의 좌표를 담은 이차원 배열  dots가 다음과 같이 매개변수로 주어집니다.
[[x1, y1], [x2, y2], [x3, y3], [x4, y4]]
주어진 네 개의 점을 두 개씩 이었을 때, 두 직선이 평행이 되는 경우가 있으면 1을 없으면 0을 return 하도록 solution 함수를 완성해보세요.
=> [121일차] 최주희 / 평행

2st/Riyeon/문자와 문자열.java
| 문자와 문자열 | 백준 | 브론즈 V |
<hr/>
- 문자와 문자열 : 단어 S와 정수 i가 주어졌을 때, S의 i번째 글자를 출력하는 프로그램을 작성하시오.
=> [220일차] 김리연 / 문자와 문자열

2st/Yeonwoo/직각삼각형 출력하기.c++
| 직각삼각형 출력하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120823?language=cpp) |
<hr/>
- 직각삼각형 출력하기 : "*"의 높이와 너비를 1이라고 했을 때, "*"을 이용해 직각 이등변 삼각형을 그리려고합니다. 정수 n 이 주어지면 높이와 너비가 n 인 직각 이등변 삼각형을 출력하도록 코드를 작성해보세요.
=> [221일차] 채연우 / 직각삼각형 출력하기
