CODE-U-S/Coding_Test_Study

2st/Riyeon/단어 길이 재기.java
| 단어 길이 재기 | 백준 | 브론즈 V |
<hr/>
- 단어 길이 재기 : 알파벳으로만 이루어진 단어를 입력받아, 그 길이를 출력하는 프로그램을 작성하시오.
=> [221일차] 김리연 / 단어 길이 재기

3st/Juhee/옹알이 (1).java
https://school.programmers.co.kr/learn/courses/30/lessons/120956
| 옹알이 (1) | 프로그래머스 | Level.0 |
<hr/>
- 옹알이 (1) : 머쓱이는 태어난 지 6개월 된 조카를 돌보고 있습니다. 조카는 아직 "aya", "ye", "woo", "ma" 네 가지 발음을 최대 한 번씩 사용해 조합한(이어 붙인) 발음밖에 하지 못합니다. 문자열 배열 babbling이 매개변수로 주어질 때, 머쓱이의 조카가 발음할 수 있는 단어의 개수를 return하도록 solution 함수를 완성해주세요.
=> [122일차] 최주희 / 옹알이 (1)

3st/Juhee/배열 만들기 2.java
https://school.programmers.co.kr/learn/courses/30/lessons/181921
| 배열 만들기 2 | 프로그래머스 | Level.0 |
<hr/>
- 배열 만들기 2 : 정수 l과 r이 주어졌을 때, l 이상 r이하의 정수 중에서 숫자 "0"과 "5"로만 이루어진 모든 정수를 오름차순으로 저장한 배열을 return 하는 solution 함수를 완성해 주세요.
만약 그러한 정수가 없다면, -1이 담긴 배열을 return 합니다.
=> [123일차] 최주희 / 배열 만들기 2

2st/Yeonwoo/세 개의 구분자.py
| 세 개의 구분자 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181862) |
<hr/>
- 세 개의 구분자 : 임의의 문자열이 주어졌을 때 문자 "a", "b", "c"를 구분자로 사용해 문자열을 나누고자 합니다.
예를 들어 주어진 문자열이 "baconlettucetomato"라면 나눠진 문자열 목록은 ["onlettu", "etom", "to"] 가 됩니다.
문자열 myStr이 주어졌을 때 위 예시와 같이 "a", "b", "c"를 사용해 나눠진 문자열을 순서대로 저장한 배열을 return 하는 solution 함수를 완성해 주세요.
단, 두 구분자 사이에 다른 문자가 없을 경우에는 아무것도 저장하지 않으며, return할 배열이 빈 배열이라면 ["EMPTY"]를 return 합니다.
=> [222일차] 채연우 / 세 개의 구분자

2st/Riyeon/문자열.java
| 문자열 | 백준 | 브론즈 V |
<hr/>
- 문자열 : 문자열을 입력으로 주면 문자열의 첫 글자와 마지막 글자를 출력하는 프로그램을 작성하시오.
=> [222일차] 김리연 / 문자열

2st/Yeonwoo/조건에 맞게 수열 변환하기 2.py
| 조건에 맞게 수열 변환하기 2 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181881) |
<hr/>
- 조건에 맞게 수열 변환하기 2 : 정수 배열 arr가 주어집니다. arr의 각 원소에 대해 값이 50보다 크거나 같은 짝수라면 2로 나누고, 50보다 작은 홀수라면 2를 곱하고 다시 1을 더합니다.
이러한 작업을 x번 반복한 결과인 배열을 arr(x)라고 표현했을 때, arr(x) = arr(x + 1)인 x가 항상 존재합니다. 이러한 x 중 가장 작은 값을 return 하는 solution 함수를 완성해 주세요.
단, 두 배열에 대한 "="는 두 배열의 크기가 서로 같으며, 같은 인덱스의 원소가 각각 서로 같음을 의미합니다.
=> [223일차] 채연우 / 조건에 맞게 수열 변환하기 2

2st/Riyeon/아스키 코드.java
| 아스키 코드 | 백준 | 브론즈 V |
<hr/>
- 아스키 코드 : 알파벳 소문자, 대문자, 숫자 0-9중 하나가 주어졌을 때, 주어진 글자의 아스키 코드값을 출력하는 프로그램을 작성하시오.
=> [225일차] 김리연 / 아스키 코드

2st/Yeonwoo/진료 순서 정하기.py
| 진료 순서 정하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120835) |
<hr/>
- 진료 순서 정하기 : 외과의사 머쓱이는 응급실에 온 환자의 응급도를 기준으로 진료 순서를 정하려고 합니다. 정수 배열 emergency가 매개변수로 주어질 때 응급도가 높은 순서대로 진료 순서를 정한 배열을 return하도록 solution 함수를 완성해주세요.
=> [225일차] 채연우 / 진료 순서 정하기

2st/Yeonwoo/공 던지기.py
| 공 던지기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120843) |
<hr/>
- 공 던지기 : 머쓱이는 친구들과 동그랗게 서서 공 던지기 게임을 하고 있습니다. 공은 1번부터 던지며 오른쪽으로 한 명을 건너뛰고 그다음 사람에게만 던질 수 있습니다. 친구들의 번호가 들어있는 정수 배열 numbers와 정수 K가 주어질 때, k번째로 공을 던지는 사람의 번호는 무엇인지 return 하도록 solution 함수를 완성해보세요.
=> [226일차] 채연우 / 공 던지기

3st/Juhee/수열과 구간 쿼리 2.java
https://school.programmers.co.kr/learn/courses/30/lessons/181923
| 수열과 구간 쿼리 2 | 프로그래머스 | Level.0 |
<hr/>
- 수열과 구간 쿼리 2 : 정수 배열 arr와 2차원 정수 배열 queries이 주어집니다. queries의 원소는 각각 하나의 query를 나타내며, [s, e, k] 꼴입니다.
각 query마다 순서대로 s ≤ i ≤ e인 모든 i에 대해 k보다 크면서 가장 작은 arr[i]를 찾습니다.
각 쿼리의 순서에 맞게 답을 저장한 배열을 반환하는 solution 함수를 완성해 주세요.
단, 특정 쿼리의 답이 존재하지 않으면 -1을 저장합니다.
=> [127일차] 최주희 / 수열과 구간 쿼리 2

2st/Riyeon/숫자의 합.java
| 숫자의 합 | 백준 | 브론즈 IV |
<hr/>
- 숫자의 합 : N개의 숫자가 공백 없이 쓰여있다. 이 숫자를 모두 합해서 출력하는 프로그램을 작성하시오.
=> [226일차] 김리연 / 숫자의 합

접미사 배열.java
| 접미사 배열 | 프로그래머스 | Level.0 |
<hr/>
- 접미사 배열 : 어떤 문자열에 대해서 접미사는 특정 인덱스부터 시작하는 문자열을 의미합니다. 예를 들어, "banana"의 모든 접미사는 "banana", "anana", "nana", "ana", "na", "a"입니다.
문자열 my_string이 매개변수로 주어질 때, my_string의 모든 접미사를 사전순으로 정렬한 문자열 배열을 return 하는 solution 함수를 작성해 주세요.
=> [128일차] 김서준 / 접미사 배열

문자열 위데 n글자.java
<hr/>
- 문자열의 뒤의 n글자 : 문자열 my_string과 정수 n이 매개변수로 주어질 때, my_string의 뒤의 n글자로 이루어진 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [129일차] 김서준 / 문자열의 뒤의 n글자

2st/Riyeon/문자열 반복.java
| 문자열 반복 | 백준 | 브론즈 II |
<hr/>
- 문자열 반복 : 문자열 S를 입력받은 후에, 각 문자를 R번 반복해 새 문자열 P를 만든 후 출력하는 프로그램을 작성하시오. 즉, 첫 번째 문자를 R번 반복하고, 두 번째 문자를 R번 반복하는 식으로 P를 만들면 된다. S에는 QR Code "alphanumeric" 문자만 들어있다.
=> [228일차] 김리연 / 문자열 반복

3st/Juhee/문자열 여러 번 뒤집기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181913
| 문자열 여러 번 뒤집기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 여러 번 뒤집기 : 문자열 my_string과 이차원 정수 배열 queries가 매개변수로 주어집니다. queries의 원소는 [s, e] 형태로, my_string의 인덱스 s부터 인덱스 e까지를 뒤집으라는 의미입니다. my_string에 queries의 명령을 순서대로 처리한 후의 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [129일차] 최주희 / 문자열 여러 번 뒤집기

2st/Yeonwoo/특정 문자 제거하기.java
| 특정 문자 제거하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120826?language=java) |
<hr/>
=> [228일차] 채연우 / 특정 문자 제거하기

3st/Juhee/글자 지우기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181900
| 글자 지우기 | 프로그래머스 | Level.0 |
<hr/>
- 글자 지우기 : 문자열 my_string과 정수 배열 indices가 주어질 때, my_string에서 indices의 원소에 해당하는 인덱스의 글자를 지우고 이어 붙인 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [130일차] 최주희 / 글자 지우기

부분 문자열 이어 붙여 문자열 만들기.java
<hr/>
- 부분 문자열 이어 붙여 문자열 만들기 : 길이가 같은 문자열 배열 my_strings와 이차원 정수 배열 parts가 매개변수로 주어집니다. parts[i]는 [s, e] 형태로, my_string[i]의 인덱스 s부터 인덱스 e까지의 부분 문자열을 의미합니다. 각 my_strings의 원소의 parts에 해당하는 부분 문자열을 순서대로 이어 붙인 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [220일차] 김서준 / 부분 문자열 이어 붙여 문자열 만들기

2st/Yeonwoo/가장 큰 수 찾기.java
| 가장 큰 수 찾기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120899?language=java) |
<hr/>
=> [229일차] 채연우 / 가장 큰 수 찾기

2st/Riyeon/단어의 개수.java
| 단어의 개수 | 백준 | 브론즈 II |
<hr/>
- 단어의 개수 : 영어 대소문자와 공백으로 이루어진 문자열이 주어진다. 이 문자열에는 몇 개의 단어가 있을까? 이를 구하는 프로그램을 작성하시오. 단, 한 단어가 여러 번 등장하면 등장한 횟수만큼 모두 세어야 한다.
=> [229일차] 김리연 / 단어의 개수

2st/Yeonwoo/5명씩.java
| 5명씩 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181886?language=java) |
<hr/>
=> [230일차] 채연우 / 5명씩

2st/Riyeon/상수.java
| 상수 | 백준 | 브론즈 II |
<hr/>
- 상수 : 상근이의 동생 상수는 수학을 정말 못한다. 상수는 숫자를 읽는데 문제가 있다. 이렇게 수학을 못하는 상수를 위해서 상근이는 수의 크기를 비교하는 문제를 내주었다. 상근이는 세 자리 수 두 개를 칠판에 써주었다. 그 다음에 크기가 큰 수를 말해보라고 했다.
상수는 수를 다른 사람과 다르게 거꾸로 읽는다. 예를 들어, 734와 893을 칠판에 적었다면, 상수는 이 수를 437과 398로 읽는다. 따라서, 상수는 두 수중 큰 수인 437을 큰 수라고 말할 것이다.
두 수가 주어졌을 때, 상수의 대답을 출력하는 프로그램을 작성하시오.
=> [231일차] 김리연 / 상수

수 조작하기2.java
| 수 조작하기 2 | 프로그래머스 |  Level.0 |
<hr/>
- 수 조작하기 2 : 정수 배열 numLog가 주어집니다. 처음에 numLog[0]에서 부터 시작해 "w", "a", "s", "d"로 이루어진 문자열을 입력으로 받아 순서대로 다음과 같은 조작을 했다고 합시다.
"w" : 수에 1을 더한다.
"s" : 수에 1을 뺀다.
"d" : 수에 10을 더한다.
"a" : 수에 10을 뺀다.
그리고 매번 조작을 할 때마다 결괏값을 기록한 정수 배열이 numLog입니다. 즉, numLog[i]는 numLog[0]로부터 총 i번의 조작을 가한 결과가 저장되어 있습니다.
주어진 정수 배열 numLog에 대해 조작을 위해 입력받은 문자열을 return 하는 solution 함수를 완성해 주세요.
=> [132일차] 김서준 / 수 조작하기 2

2st/Yeonwoo/정수 부분.java
| 정수 부분 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181850?language=java) |
<hr/>
=> [231일차] 채연우 / 정수 부분

3st/Juhee/2의 영역.java
https://school.programmers.co.kr/learn/courses/30/lessons/181894
| 2의 영역 | 프로그래머스 | Level.0 |
<hr/>
- 2의 영역 : 정수 배열 arr가 주어집니다. 배열 안의 2가 모두 포함된 가장 작은 연속된 부분 배열을 return 하는 solution 함수를 완성해 주세요.
단, arr에 2가 없는 경우 [-1]을 return 합니다.
=> [133일차] 최주희 / 2의 영역

2st/Riyeon/다이얼.java
| 다이얼 | 백준 | 브론즈 II |
<hr/>
- 다이얼 : 전화를 걸고 싶은 번호가 있다면, 숫자를 하나를 누른 다음에 금속 핀이 있는 곳 까지 시계방향으로 돌려야 한다. 숫자를 하나 누르면 다이얼이 처음 위치로 돌아가고, 다음 숫자를 누르려면 다이얼을 처음 위치에서 다시 돌려야 한다.
숫자 1을 걸려면 총 2초가 필요하다. 1보다 큰 수를 거는데 걸리는 시간은 이보다 더 걸리며, 한 칸 옆에 있는 숫자를 걸기 위해선 1초씩 더 걸린다.
상근이의 할머니는 전화 번호를 각 숫자에 해당하는 문자로 외운다. 즉, 어떤 단어를 걸 때, 각 알파벳에 해당하는 숫자를 걸면 된다. 예를 들어, UNUCIC는 868242와 같다.
할머니가 외운 단어가 주어졌을 때, 이 전화를 걸기 위해서 필요한 최소 시간을 구하는 프로그램을 작성하시오.
=> [232일차] 김리연 / 다이얼

글자 이어 붙어 문자열 만들기.java
| 글자 이어 붙어 문자열 만들기 | 프로그래머스 |  Level.0 |
<hr/>
- 글자 이어 붙어 문자열 만들기 : 문자열 my_string과 정수 배열 index_list가 매개변수로 주어집니다. my_string의 index_list의 원소들에 해당하는 인덱스의 글자들을 순서대로 이어 붙인 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [133일차] 김서준 / 글자 이어 붙어 문자열 만들기

2st/Yeonwoo/문자열 정수의 합.java
| 문자열 정수의 합 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181849?language=java) |
<hr/>
=> [232일차] 채연우 / 문자열 정수의 합

2st/Yeonwoo/소문자로 바꾸기.java
| 소문자로 바꾸기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181876?language=java) |
<hr/>
=> [233일차] 채연우 / 소문자로 바꾸기

콜라츠 수열 만들기.java
=> [134일차] 김서준 / 콜라츠 수열 만들기

2st/Riyeon/그대로 출력하기.java
| 그대로 출력하기 | 백준 | 브론즈 III |
<hr/>
- 그대로 출력하기 : 입력 받은 대로 출력하는 프로그램을 작성하시오.
=> [233일차] 김리연 / 그대로 출력하기

2st/Yeonwoo/대문자로 바꾸기.java
| 대문자로 바꾸기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181877?language=java) |
<hr/>
=> [234일차] 채연우 / 대문자로 바꾸기

3st/Juhee/배열 조각하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181893
| 배열 조각하기 | 프로그래머스 | Level.0 |
<hr/>
- 배열 조각하기 : 정수 배열 arr와 query가 주어집니다.
query를 순회하면서 다음 작업을 반복합니다.
짝수 인덱스에서는 arr에서 query[i]번 인덱스를 제외하고 배열의 query[i]번 인덱스 뒷부분을 잘라서 버립니다.
홀수 인덱스에서는 arr에서 query[i]번 인덱스는 제외하고 배열의 query[i]번 인덱스 앞부분을 잘라서 버립니다.
위 작업을 마친 후 남은 arr의 부분 배열을 return 하는 solution 함수를 완성해 주세요.
=> [135일차] 최주희 / 배열 조각하기

2st/Riyeon/킹, 퀸, 룩, 비숍, 나이트, 폰.java
| 킹, 퀸, 룩, 비숍, 나이트, 폰 | 백준 | 브론즈 V |
<hr/>
- 킹, 퀸, 룩, 비숍, 나이트, 폰 : 동혁이는 오래된 창고를 뒤지다가 낡은 체스판과 피스를 발견했다. 체스판의 먼지를 털어내고 걸레로 닦으니 그럭저럭 쓸만한 체스판이 되었다. 하지만, 검정색 피스는 모두 있었으나, 흰색 피스는 개수가 올바르지 않았다. 체스는 총 16개의 피스를 사용하며, 킹 1개, 퀸 1개, 룩 2개, 비숍 2개, 나이트 2개, 폰 8개로 구성되어 있다.
동혁이가 발견한 흰색 피스의 개수가 주어졌을 때, 몇 개를 더하거나 빼야 올바른 세트가 되는지 구하는 프로그램을 작성하시오.
=> [234일차] 김리연 / 킹, 퀸, 룩, 비숍, 나이트, 폰

3st/Jaehee/오븐 시계.java
https://www.acmicpc.net/submit/2525/90077130
| 오븐 시계| 백준| Level.0 |
<hr/>
- 오븐 시계: KOI 전자에서는 건강에 좋고 맛있는 훈제오리구이 요리를 간편하게 만드는 인공지능 오븐을 개발하려고 한다. 인공지능 오븐을 사용하는 방법은 적당한 양의 오리 훈제 재료를 인공지능 오븐에 넣으면 된다. 그러면 인공지능 오븐은 오븐구이가 끝나는 시간을 분 단위로 자동적으로 계산한다.
또한, KOI 전자의 인공지능 오븐 앞면에는 사용자에게 훈제오리구이 요리가 끝나는 시각을 알려 주는 디지털 시계가 있다.
훈제오리구이를 시작하는 시각과 오븐구이를 하는 데 필요한 시간이 분단위로 주어졌을 때, 오븐구이가 끝나는 시각을 계산하는 프로그램을 작성하시오.
=> [135일} 이제희/오븐 시계

3st/Juhee/문자 개수 세기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181902
| 문자 개수 세기 | 프로그래머스 | Level.0 |
<hr/>
- 문자 개수 세기 : 알파벳 대소문자로만 이루어진 문자열 my_string이 주어질 때, my_string에서 'A'의 개수, my_string에서 'B'의 개수,..., my_string에서 'Z'의 개수, my_string에서 'a'의 개수, my_string에서 'b'의 개수,..., my_string에서 'z'의 개수를 순서대로 담은 길이 52의 정수 배열을 return 하는 solution 함수를 작성해 주세요.
=> [136일차] 최주희 / 문자 개수 세기

2st/Yeonwoo/길이에 따른 연산.java
| 길이에 따른 연산 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181879?language=java) |
<hr/>
=> [235일차] 채연우 / 길이에 따른 연산

수 조작하기 1.java
<hr/>
- 수 조작하기 1 : 정수 n과 문자열 control이 주어집니다. control은 "w", "a", "s", "d"의 4개의 문자로 이루어져 있으며, control의 앞에서부터 순서대로 문자에 따라 n의 값을 바꿉니다.
"w" : n이 1 커집니다.
"s" : n이 1 작아집니다.
"d" : n이 10 커집니다.
"a" : n이 10 작아집니다.
위 규칙에 따라 n을 바꿨을 때 가장 마지막에 나오는 n의 값을 return 하는 solution 함수를 완성해 주세요.
=> [137일차] 김서준 / 수 조작하기 1

2st/Riyeon/별 찍기 - 7.java
| 별 찍기 - 7 | 백준 | 브론즈 III |
<hr/>
- 별 찍기 - 7 : 예제를 보고 규칙을 유추한 뒤에 별을 찍어 보세요.
=> [236일차] 김리연 / 별 찍기 - 7

2st/Yeonwoo/할 일 목록.java
| 할 일 목록 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181885?language=java) |
<hr/>
=> [236일차] 채연우 / 할 일 목록

3st/Jaehee/수 나누기.java
https://school.programmers.co.kr/learn/courses/30/lessons/340205
| 수 나누기| 프로그래머스 | Level.0 |
<hr/>
- 수 나누기: 2자리 이상의 정수 number가 주어집니다. 주어진 코드는 이 수를 2자리씩 자른 뒤, 자른 수를 모두 더해서 그 합을 출력하는 코드입니다. 코드가 올바르게 작동하도록 한 줄을 수정해 주세요.
=> [137일} 이제희 / 수 나누기

3st/Seojun/문자열 돌리기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181945
|  문자열 돌리기 | 프로그래머스 | Level.0 |
<hr/>
-  문자열 돌리기 : 문자열 str이 주어집니다.
=> [138일차] 김서 /  문자열 돌리기

2st/Riyeon/팰린드롬인지 확인하기.java
| 팰린드롬인지 확인하기 | 백준 | 브론즈 III |
<hr/>
- 팰린드롬인지 확인하기 : 알파벳 소문자로만 이루어진 단어가 주어진다. 이때, 이 단어가 팰린드롬인지 아닌지 확인하는 프로그램을 작성하시오. 
팰린드롬이란 앞으로 읽을 때와 거꾸로 읽을 때 똑같은 단어를 말한다. level, noon은 팰린드롬이고, baekjoon, online, judge는 팰린드롬이 아니다.
=> [237일차] 김리연 / 팰린드롬인지 확인하기

3st/Juhee/리스트 자르기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181897
| 리스트 자르기 | 프로그래머스 | Level.0 |
<hr/>
- 리스트 자르기 : 정수 n과 정수 3개가 담긴 리스트 slicer 그리고 정수 여러 개가 담긴 리스트 num_list가 주어집니다. slicer에 담긴 정수를 차례대로 a, b, c라고 할 때, n에 따라 다음과 같이 num_list를 슬라이싱 하려고 합니다.
n = 1 : num_list의 0번 인덱스부터 b번 인덱스까지
n = 2 : num_list의 a번 인덱스부터 마지막 인덱스까지
n = 3 : num_list의 a번 인덱스부터 b번 인덱스까지
n = 4 : num_list의 a번 인덱스부터 b번 인덱스까지 c 간격으로
올바르게 슬라이싱한 리스트를 return하도록 solution 함수를 완성해주세요.
=> [138일차] 최주희 / 리스트 자르기

2st/Yeonwoo/카운트 다운.java
| 카운트 다운 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181899?language=java) |
<hr/>
=> [237일차] 채연우 / 카운트 다운

2st/Riyeon/단어 공부.java
| 단어 공부 | 백준 | 브론즈 I |
<hr/>
- 단어 공부 : 알파벳 대소문자로 된 단어가 주어지면, 이 단어에서 가장 많이 사용된 알파벳이 무엇인지 알아내는 프로그램을 작성하시오. 단, 대문자와 소문자를 구분하지 않는다.
=> [238일차] 김리연 / 단어 공부

3st/Seojun/문자열 정렬하기 1.java
| 문자열 정렬하기1 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 정렬하기1 : 문자열 my_string이 매개변수로 주어질 때, my_string 안에 있는 숫자만 골라 오름차순 정렬한 리스트를 return 하도록 solution 함수를 작성해보세요.
=> [139일차] 김서준 / 문자열 정렬하기1

3st/Juhee/1로 만들기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181880
| 1로 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 1로 만들기 : 정수가 있을 때, 짝수라면 반으로 나누고, 홀수라면 1을 뺀 뒤 반으로 나누면, 마지막엔 1이 됩니다. 예를 들어 10이 있다면 다음과 같은 과정으로 1이 됩니다.
10 / 2 = 5
2 / 2 = 1
=> [139일차] 최주희 / 1로 만들기

2st/Riyeon/크로아티아 알파벳.java
| 크로아티아 알파벳 | 백준 | 실버 V |
<hr/>
- 크로아티아 알파벳 : 예전에는 운영체제에서 크로아티아 알파벳을 입력할 수가 없었다. 따라서, 크로아티아 알파벳을 변경해서 입력했다. 예를 들어, ljes=njak은 크로아티아 알파벳 6개(lj, e, š, nj, a, k)로 이루어져 있다. 단어가 주어졌을 때, 몇 개의 크로아티아 알파벳으로 이루어져 있는지 출력한다. 
dž는 무조건 하나의 알파벳으로 쓰이고, d와 ž가 분리된 것으로 보지 않는다. lj와 nj도 마찬가지이다. 위 목록에 없는 알파벳은 한 글자씩 센다.
=> [239일차] 김리연 / 크로아티아 알파벳

3st/Hyeonseo/programmer/편지.js
https://school.programmers.co.kr/learn/courses/30/lessons/120802?language=javascript
| 두 수의 합 | 프로그래머스 | Level.0 |
<hr/>
- 두 수의 합 : 정수 num1과 num2가 주어질 때, num1과 num2의 합을 return하도록 soltuion 함수를 완성해주세요.
=> [140일차] 조현서 / 두 수의 합

2st/Yeonwoo/문자 리스트를 문자열로 변환하기.java
| 문자 리스트를 문자열로 변환하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181941?language=java) |
<hr/>
=> [239일차] 채연우 / 문자 리스트를 문자열로 변환하기

3st/Juhee/수열과 구간 쿼리 1.java
https://school.programmers.co.kr/learn/courses/30/lessons/181883
<hr/>
- 수열과 구간 쿼리 1 : 정수 배열 arr와 2차원 정수 배열 queries이 주어집니다. queries의 원소는 각각 하나의 query를 나타내며, [s, e] 꼴입니다.
=> [140일차] 최주희 / 수열과 구간 쿼리 1

2st/Riyeon/10926번.java
| ??! | 백준 | 브론즈 V |
<hr/>
- ??! : 준하는 사이트에 회원가입을 하다가 joonas라는 아이디가 이미 존재하는 것을 보고 놀랐다. 준하는 놀람을 ??!로 표현한다. 준하가 가입하려고 하는 사이트에 이미 존재하는 아이디가 주어졌을 때, 놀람을 표현하는 프로그램을 작성하시오.
=> [240일차] 김리연 / ??!

2st/Yeonwoo/문자열 돌리기.java
| 문자열 돌리기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181945?language=java) |
<hr/>
- 문자열 돌리기 : 문자열 str이 주어집니다.
=> [240일차] 채연우 / 문자열 돌리기

3st/Juhee/소문자로 바꾸기.java, 3st/Juhee/조건에 맞게 수열 변환하기 2.java
https://school.programmers.co.kr/learn/courses/30/lessons/181881
| 조건에 맞게 수열 변환하기 2 | 프로그래머스 | Level.0 |
<hr/>
- 조건에 맞게 수열 변환하기 2 : 정수 배열 arr가 주어집니다. arr의 각 원소에 대해 값이 50보다 크거나 같은 짝수라면 2로 나누고, 50보다 작은 홀수라면 2를 곱하고 다시 1을 더합니다.
이러한 작업을 x번 반복한 결과인 배열을 arr(x)라고 표현했을 때, arr(x) = arr(x + 1)인 x가 항상 존재합니다. 이러한 x 중 가장 작은 값을 return 하는 solution 함수를 완성해 주세요.
단, 두 배열에 대한 "="는 두 배열의 크기가 서로 같으며, 같은 인덱스의 원소가 각각 서로 같음을 의미합니다.
=> [141일차] 최주희 / 조건에 맞게 수열 변환하기 2

2st/Yeonwoo/0 떼기.java
| 0 떼기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181847?language=java) |
<hr/>
- 0 떼기 : 정수로 이루어진 문자열 n_str이 주어질 때, n_str의 가장 왼쪽에 처음으로 등장하는 0들을 뗀 문자열을 return하도록 solution 함수를 완성해주세요.
=> [241일차] 채연우 / 0 떼기

3st/Juhee/특정 문자열로 끝나는 가장 긴 부분 문자열 찾기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181872
| 특정 문자열로 끝나는 가장 긴 부분 문자열 찾기 | 프로그래머스 | Level.0 |
<hr/>
- 특정 문자열로 끝나는 가장 긴 부분 문자열 찾기 : 문자열 myString과 pat가 주어집니다. myString의 부분 문자열중 pat로 끝나는 가장 긴 부분 문자열을 찾아서 return 하는 solution 함수를 완성해 주세요.
=> [142일차] 최주희 / 특정 문자열로 끝나는 가장 긴 부분 문자열 찾기

2st/Riyeon/나머지.java
| 나머지 | 백준 | 브론즈 V |
<hr/>
- 나머지 : (A+B)%C는 ((A%C) + (B%C))%C 와 같을까? (A×B)%C는 ((A%C) × (B%C))%C 와 같을까?
세 수 A, B, C가 주어졌을 때, 위의 네 가지 값을 구하는 프로그램을 작성하시오.
=> [242일차] 김리연 / 나머지

2st/Yeonwoo/9로 나눈 나머지.java
| 9로 나눈 나머지 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181914?language=java) |
<hr/>
- 9로 나눈 나머지 : 음이 아닌 정수를 9로 나눈 나머지는 그 정수의 각 자리 숫자의 합을 9로 나눈 나머지와 같은 것이 알려져 있습니다.
이 사실을 이용하여 음이 아닌 정수가 문자열 number로 주어질 때, 이 정수를 9로 나눈 나머지를 return 하는 solution 함수를 작성해주세요.
=> [242일차] 채연우 / 9로 나눈 나머지

3st/Juhee/공백으로 구분하기 2.java
https://school.programmers.co.kr/learn/courses/30/lessons/181868
| 공백으로 구분하기 2 | 프로그래머스 | Level.0 |
<hr/>
- 공백으로 구분하기 2 : 단어가 공백 한 개 이상으로 구분되어 있는 문자열 my_string이 매개변수로 주어질 때, my_string에 나온 단어를 앞에서부터 순서대로 담은 문자열 배열을 return 하는 solution 함수를 작성해 주세요.
=> [143일차] 최주희 / 공백으로 구분하기 2

2st/Riyeon/곱셈.java
| 곱셈 | 백준 | 브론즈 III |
<hr/>
- 곱셈 : (세 자리 수) × (세 자리 수)는 다음과 같은 과정을 통하여 이루어진다. (1)과 (2)위치에 들어갈 세 자리 자연수가 주어질 때 (3), (4), (5), (6)위치에 들어갈 값을 구하는 프로그램을 작성하시오.
=> [243일차] 김리연 / 곱셈

3st/Juhee/x 사이의 개수.java
https://school.programmers.co.kr/learn/courses/30/lessons/181867
| x 사이의 개수 | 프로그래머스 | Level.0 |
<hr/>
- x 사이의 개수 : 문자열 myString이 주어집니다. myString을 문자 "x"를 기준으로 나눴을 때 나눠진 문자열 각각의 길이를 순서대로 저장한 배열을 return 하는 solution 함수를 완성해 주세요.
=> [144일차] 최주희 / x 사이의 개수

2st/Yeonwoo/콜라츠 수열 만들기.java
| 콜라츠 수열 만들기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181919?language=java) |
<hr/>
=> [243일차] 채연우 / 콜라츠 수열 만들기

2st/Riyeon/꼬마 정민.java
| 꼬마 정민 | 백준 | 브론즈 V |
<hr/>
- 꼬마 정민 : 꼬마 정민이는 이제 A + B 정도는 쉽게 계산할 수 있다. 이제 A + B + C를 계산할 차례이다!
=> [244일차] 김리연 / 꼬마 정민

3st/Juhee/간단한 식 계산하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181865
<hr/>
=> [145일차] 최주희 / 간단한 식 계산하기

2st/Yeonwoo/주사위 게임 2.java
| 주사위 게임 2 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181930?language=java) |
<hr/>
- 주사위 게임 2 : 1부터 6까지 숫자가 적힌 주사위가 세 개 있습니다. 세 주사위를 굴렸을 때 나온 숫자를 각각 a, b, c라고 했을 때 얻는 점수는 다음과 같습니다.
세 숫자가 모두 다르다면 a + b + c 점을 얻습니다.
세 숫자 중 어느 두 숫자는 같고 나머지 다른 숫자는 다르다면 (a + b + c) × (a2 + b2 + c2 )점을 얻습니다.
세 숫자가 모두 같다면 (a + b + c) × (a2 + b2 + c2 ) × (a3 + b3 + c3 )점을 얻습니다.
세 정수 a, b, c가 매개변수로 주어질 때, 얻는 점수를 return 하는 solution 함수를 작성해 주세요.
=> [244일차] 채연우 / 주사위 게임 2

2st/Riyeon/3052번.java
| 나머지 | 백준 | 브론즈 II |
<hr/>
- 나머지 : 두 자연수 A와 B가 있을 때, A%B는 A를 B로 나눈 나머지 이다. 예를 들어, 7, 14, 27, 38을 3으로 나눈 나머지는 1, 2, 0, 2이다. 
수 10개를 입력받은 뒤, 이를 42로 나눈 나머지를 구한다. 그 다음 서로 다른 값이 몇 개 있는지 출력하는 프로그램을 작성하시오.
=> [245일차] 김리연 / 나머지

3st/Juhee/간단한 식 계산하기.java, 3st/Juhee/문자열 바꿔서 찾기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181864
<hr/>
=> [146일차] 최주희 / 문자열 바꿔서 찾기

2st/Riyeon/곱셈.java, 2st/Yeonwoo/콜라츠 수열 만들기.java, 3st/Juhee/x 사이의 개수.java
https://school.programmers.co.kr/learn/courses/30/lessons/181877?language=javascript
<hr/>
=> [146일차] 조현서 / 대문자로 바꾸기

2st/Yeonwoo/간단한 식 계산하기.java
| 간단한 식 계산하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181865?language=java) |
<hr/>
=> [245일차] 채연우 / 간단한 식 계산하기

3st/Juhee/문자열 잘라서 정렬하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181866
| 문자열 잘라서 정렬하기 | 프로그래머스 | Level. |
<hr/>
- 문자열 잘라서 정렬하기 : 문자열 myString이 주어집니다. "x"를 기준으로 해당 문자열을 잘라내 배열을 만든 후 사전순으로 정렬한 배열을 return 하는 solution 함수를 완성해 주세요.
단, 빈 문자열은 반환할 배열에 넣지 않습니다.
=> [147일차] 최주희 / 문자열 잘라서 정렬하기

2st/Riyeon/10811번.java
| 바구니 뒤집기 | 백준 | 브론즈 II |
<hr/>
- 바구니 뒤집기 : 도현이는 바구니를 총 N개 가지고 있고, 각각의 바구니에는 1번부터 N번까지 번호가 순서대로 적혀져 있다. 바구니는 일렬로 놓여져 있고, 가장 왼쪽 바구니를 1번째 바구니, 그 다음 바구니를 2번째 바구니, ..., 가장 오른쪽 바구니를 N번째 바구니라고 부른다. 
도현이는 앞으로 M번 바구니의 순서를 역순으로 만들려고 한다. 도현이는 한 번 순서를 역순으로 바꿀 때, 순서를 역순으로 만들 범위를 정하고, 그 범위에 들어있는 바구니의 순서를 역순으로 만든다.
바구니의 순서를 어떻게 바꿀지 주어졌을 때, M번 바구니의 순서를 역순으로 만든 다음, 바구니에 적혀있는 번호를 가장 왼쪽 바구니부터 출력하는 프로그램을 작성하시오.
=> [246일차] 김리연 / 바구니 뒤집기

2st/Yeonwoo/ad 제거하기.java
| ad 제거하기 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/181870?language=java) |
<hr/>
- ad 제거하기 : 문자열 배열 strArr가 주어집니다. 배열 내의 문자열 중 "ad"라는 부분 문자열을 포함하고 있는 모든 문자열을 제거하고 남은 문자열을 순서를 유지하여 배열로 return 하는 solution 함수를 완성해 주세요.
=> [246일차] 채연우 / ad 제거하기

2st/Riyeon/5597번.java
| 과제 안 내신 분..? | 백준 | 브론즈 III |
<hr/>
- 과제 안 내신 분..? : X대학 M교수님은 프로그래밍 수업을 맡고 있다. 교실엔 학생이 30명이 있는데, 학생 명부엔 각 학생별로 1번부터 30번까지 출석번호가 붙어 있다.
교수님이 내준 특별과제를 28명이 제출했는데, 그 중에서 제출 안 한 학생 2명의 출석번호를 구하는 프로그램을 작성하시오.
=> [247일차] 김리연 / 과제 안 내신 분..?

2st/Yeonwoo/나누어 떨어지는 숫자 배열.c++
| 나누어 떨어지는 숫자 배열 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/12910?language=cpp) |
<hr/>
- 나누어 떨어지는 숫자 배열 : array의 각 element 중 divisor로 나누어 떨어지는 값을 오름차순으로 정렬한 배열을 반환하는 함수, solution을 작성해주세요.
divisor로 나누어 떨어지는 element가 하나도 없다면 배열에 -1을 담아 반환하세요.
제한사항
arr은 자연수를 담은 배열입니다.
정수 i, j에 대해 i ≠ j 이면 arr[i] ≠ arr[j] 입니다.
divisor는 자연수입니다.
array는 길이 1 이상인 배열입니다.
=> [247일차] 채연우 / 나누어 떨어지는 숫자 배열

3st/Hyeonseo/programmer/ad 제거하기.java, 3st/Hyeonseo/programmer/n의 배수.cpp, 3st/Hyeonseo/programmer/n의 배수.js, 3st/Hyeonseo/programmer/각도기.cpp, 3st/Hyeonseo/programmer/공배수.java, 3st/Hyeonseo/programmer/나머지 구하기.js, 3st/Hyeonseo/programmer/나이 출력.js, 3st/Hyeonseo/programmer/두 수의 곱.cpp, 3st/Hyeonseo/programmer/두 수의 곱.js, 3st/Hyeonseo/programmer/두 수의 나눗셈.cpp, 3st/Hyeonseo/programmer/두 수의 나눗셈.js, 3st/Hyeonseo/programmer/두 수의 연산값 비교하기.java, 3st/Hyeonseo/programmer/두 수의 합.js, 3st/Hyeonseo/programmer/두수의 차.js, 3st/Hyeonseo/programmer/머쓱이보다 키 큰 사람.js, 3st/Hyeonseo/programmer/몫 구하기.js, 3st/Hyeonseo/programmer/문자열안에 문자열.cpp, 3st/Hyeonseo/programmer/배열 뒤집기.cpp, 3st/Hyeonseo/programmer/배열의 평균값.js, 3st/Hyeonseo/programmer/세균 증식.cpp, 3st/Hyeonseo/programmer/세균 증식.js, 3st/Hyeonseo/programmer/소문자로 바꾸기.js, 3st/Hyeonseo/programmer/숫자 비교하기.js, 3st/Hyeonseo/programmer/정수 제곱근 판별.java, 3st/Hyeonseo/programmer/제곱수 판별하기.cpp, 3st/Hyeonseo/programmer/직사각형 별찍기.java, 3st/Hyeonseo/programmer/짝수의 합.js, 대문자로 바꾸기.js
https://school.programmers.co.kr/learn/courses/30/lessons/12969
| 직사각형 별 찍기 | 프로그래머스 | Level.1 |
<hr/>
- 직사각형 별 찍기 : 이 문제에는 표준 입력으로 두 개의 정수 n과 m이 주어집니다.
별(*) 문자를 이용해 가로의 길이가 n, 세로의 길이가 m인 직사각형 형태를 출력해보세요.
=> [149일차] 조현서 / 직사각형 별 찍기

2st/Riyeon/1546번.java
| 평균 | 백준 | 브론즈 I |
<hr/>
- 평균 : 세준이는 기말고사를 망쳤다. 세준이는 점수를 조작해서 집에 가져가기로 했다. 일단 세준이는 자기 점수 중에 최댓값을 골랐다. 이 값을 M이라고 한다. 그리고 나서 모든 점수를 점수/M*100으로 고쳤다. 예를 들어, 세준이의 최고점이 70이고, 수학점수가 50이었으면 수학점수는 50/70*100이 되어 71.43점이 된다.
세준이의 성적을 위의 방법대로 새로 계산했을 때, 새로운 평균을 구하는 프로그램을 작성하시오.
=> [248일차] 김리연 / 평균

3st/Jaeyoung/n의 배수 고르기.js
| n의 배수 고르기 | 프로그래머스 | Level.0 |
<hr/>
=> [149일차] 박재영 / n의 배수 고르기

2st/Riyeon/1316번.java
| 그룹 단어 체커 | 백준 | 실버 V |
<hr/>
- 그룹 단어 체커 : 그룹 단어란 단어에 존재하는 모든 문자에 대해서, 각 문자가 연속해서 나타나는 경우만을 말한다. 예를 들면, ccazzzzbb는 c, a, z, b가 모두 연속해서 나타나고, kin도 k, i, n이 연속해서 나타나기 때문에 그룹 단어이지만, aabbbccb는 b가 떨어져서 나타나기 때문에 그룹 단어가 아니다.
단어 N개를 입력으로 받아 그룹 단어의 개수를 출력하는 프로그램을 작성하시오.
=> [249일차] 김리연 / 그룹 단어 체커

2st/Yeonwoo/커피 심부름.c++
| 커피 심부름 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181837?language=cpp) |
<hr/>
- 커피 심부름 : 팀의 막내인 철수는 아메리카노와 카페 라테만 판매하는 카페에서 팀원들의 커피를 사려고 합니다. 아메리카노와 카페 라테의 가격은 차가운 것과 뜨거운 것 상관없이 각각 4500, 5000원입니다. 각 팀원에게 마실 메뉴를 적어달라고 하였고, 그 중에서 메뉴만 적은 팀원의 것은 차가운 것으로 통일하고 "아무거나"를 적은 팀원의 것은 차가운 아메리카노로 통일하기로 하였습니다.
각 직원이 적은 메뉴가 문자열 배열 order로 주어질 때, 카페에서 결제하게 될 금액을 return 하는 solution 함수를 작성해주세요. order의 원소는 아래의 것들만 들어오고, 각각의 의미는 다음과 같습니다.
=> [249일차] 채연우 / 커피 심부름

3st/Juhee/rny_string.java
https://school.programmers.co.kr/learn/courses/30/lessons/181863
<hr/>
- rny_string : 'm'과 "rn"이 모양이 비슷하게 생긴 점을 활용해 문자열에 장난을 하려고 합니다. 문자열 rny_string이 주어질 때, rny_string의 모든 'm'을 "rn"으로 바꾼 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [150일차] 최주희 / rny_string

2st/Riyeon/25206번.java
| 너의 평점은 | 백준 | 실버 V |
<hr/>
- 너의 평점은 : 인하대학교 컴퓨터공학과를 졸업하기 위해서는, 전공평점이 3.3 이상이거나 졸업고사를 통과해야 한다. 그런데 아뿔싸, 치훈이는 깜빡하고 졸업고사를 응시하지 않았다는 사실을 깨달았다! 전공평점은 전공과목별 (학점 × 과목평점)의 합을 학점의 총합으로 나눈 값이다.
치훈이의 전공평점을 계산해주는 프로그램을 작성해보자.
=> [250일차] 김리연 / 너의 평점은

2st/Yeonwoo/날짜 비교하기.java
| 날짜 비교하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181838?language=java) |
<hr/>
- 날짜 비교하기 : 정수 배열 date1과 date2가 주어집니다. 두 배열은 각각 날짜를 나타내며 [year, month, day] 꼴로 주어집니다. 각 배열에서 year는 연도를, month는 월을, day는 날짜를 나타냅니다.
만약 date1이 date2보다 앞서는 날짜라면 1을, 아니면 0을 return 하는 solution 함수를 완성해 주세요.
=> [250일차] 채연우 / 날짜 비교하기

3st/Hyeonseo/programmer/중복된 숫자 개수.java, 3st/Hyeonseo/programmer/직사각형 별찍기.java
https://github.com/hyeonseo8822/Coding_Test_Study
| 배열 만들기1 | 프로그래머스 | Level.0 |
<hr/>
- 배열 만들기1 : 정수 n과 k가 주어졌을 때, 1 이상 n이하의 정수 중에서 k의 배수를 오름차순으로 저장한 배열을 return 하는 solution 함수를 완성해 주세요.
=> [151일차] 조현서 / 배열 만들기1 

3st/Juhee/배열의 길이에 따라 다른 연산하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181854?language=java
| 배열의 길이에 따라 다른 연산하기 | 프로그래머스 |  Level.0 |
<hr/>
=> [152일차] 최주희 / 배열의 길이에 따라 다른 연산하기

2st/Riyeon/2738번.java
| 행렬 덧셈 | 백준 | 브론즈 III |
<hr/>
- 행렬 덧셈 : N*M크기의 두 행렬 A와 B가 주어졌을 때, 두 행렬을 더하는 프로그램을 작성하시오.
=> [251일차] 김리연 / 행렬 덧셈

3st/Hyeonseo/com/9로 나눈 나머지.java
https://school.programmers.co.kr/learn/courses/30/lessons/181856
| 배열 비교하기 | 프로그래머스 | Level.1 |
<hr/>
- 배열 비교하기 : 이 문제에서 두 정수 배열의 대소관계를 다음과 같이 정의합니다.
두 배열의 길이가 다르다면, 배열의 길이가 긴 쪽이 더 큽니다.
배열의 길이가 같다면 각 배열에 있는 모든 원소의 합을 비교하여 다르다면 더 큰 쪽이 크고, 같다면 같습니다.
두 정수 배열 arr1과 arr2가 주어질 때, 위에서 정의한 배열의 대소관계에 대하여 arr2가 크다면 -1, arr1이 크다면 1, 두 배열이 같다면 0을 return 하는 solution 함수를 작성해 주세요.
=> [152일차] 조현서 / 배열 비교하기 

2st/Yeonwoo/홀짝에 따라 다른 값 반환하기.java
| 홀짝에 따라 다른 값 반환하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181935?language=java) |
<hr/>
=> [251일차] 채연우 / 홀짝에 따라 다른 값 반환하기

2st/Riyeon/2566번.java
| 최댓값 | 백준 | 브론즈 III |
<hr/>
- 최댓값 : 9×9 격자판에 쓰여진 81개의 자연수 또는 0이 주어질 때, 이들 중 최댓값을 찾고 그 최댓값이 몇 행 몇 열에 위치한 수인지 구하는 프로그램을 작성하시오.
=> [252일차] 김리연 / 최댓값

2st/Yeonwoo/제곱수 판별하기.c++
| 제곱수 판별하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120909?language=cpp) |
<hr/>
- 제곱수 판별하기 : 어떤 자연수를 제곱했을 때 나오는 정수를 제곱수라고 합니다. 정수 n이 매개변수로 주어질 때, n이 제곱수라면 1을 아니라면 2를 return하도록 solution 함수를 완성해주세요.
=> [252일차] 채연우 / 제곱수 판별하기

2st/Riyeon/10798번.java
| 세로읽기 | 백준 | 브론즈 I |
<hr/>
- 세로읽기 : 한 줄의 단어는 글자들을 빈칸 없이 연속으로 나열해서 최대 15개의 글자들로 이루어진다. 또한 만들어진 다섯 개의 단어들의 글자 개수는 서로 다를 수 있다. 
심심해진 영석이는 칠판에 만들어진 다섯 개의 단어를 세로로 읽으려 한다. 세로로 읽을 때, 각 단어의 첫 번째 글자들을 위에서 아래로 세로로 읽는다. 다음에 두 번째 글자들을 세로로 읽는다. 이런 식으로 왼쪽에서 오른쪽으로 한 자리씩 이동 하면서 동일한 자리의 글자들을 세로로 읽어 나간다. 위의 그림 1의 경우처럼 세로로 읽을 때 해당 자리의 글자가 없으면, 읽지 않고 그 다음 글자를 계속 읽는다.
칠판에 붙여진 단어들이 주어질 때, 영석이가 세로로 읽은 순서대로 글자들을 출력하는 프로그램을 작성하시오.
=> [253일차] 김리연 / 세로읽기

3st/Juhee/배열의 원소만큼 추가하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181861
<hr/>
=> [154일차] 최주희 / 배열의 원소만큼 추가하기

2st/Riyeon/2563번.java
| 색종이 | 백준 | 실버 V |
<hr/>
- 색종이 : 가로, 세로의 크기가 각각 100인 정사각형 모양의 흰색 도화지가 있다. 이 도화지 위에 가로, 세로의 크기가 각각 10인 정사각형 모양의 검은색 색종이를 색종이의 변과 도화지의 변이 평행하도록 붙인다. 이러한 방식으로 색종이를 한 장 또는 여러 장 붙인 후 색종이가 붙은 검은 영역의 넓이를 구하는 프로그램을 작성하시오.
=> [254일차] 김리연 / 색종이

3st/Hyeonseo/programmer/0 떼기.java, 3st/Hyeonseo/programmer/배열 만들기1.java, 3st/Hyeonseo/programmer/배열 비교하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120841
<hr/>
- 점의 위치 구하기 : dot의 길이 = 2
dot[0]은 x좌표를, dot[1]은 y좌표를 나타냅니다
-500 ≤ dot의 원소 ≤ 500
dot의 원소는 0이 아닙니다.
=> [156일차] 조현서 / 점의 위치 구하기 

3st/Jaeyoung/n 번째 원소까지.js, 3st/Jaeyoung/피자 나눠 먹기 (3).java
<hr/>
- n 번째 원소까지 : 정수 리스트 num_list와 정수 n이 주어질 때, num_list의 첫 번째 원소부터 n 번째 원소까지의 모든 원소를 담은 리스트를 return하도록 solution 함수를 완성해주세요.
=> [156일차] 박재영 / n 번째 연소까지

3st/Juhee/뒤에서 5등 위로.java
https://school.programmers.co.kr/learn/courses/30/lessons/181852?language=java
| 뒤에서 5등 위로 | 프로그래머스 | Level.0 |
<hr/>
- 뒤에서 5등 위로 : 정수로 이루어진 리스트 num_list가 주어집니다. num_list에서 가장 작은 5개의 수를 제외한 수들을 오름차순으로 담은 리스트를 return하도록 solution 함수를 완성해주세요.
=> [157일차] 최주희 / 뒤에서 5등 위로

3st/Hyeonseo/programmer/점의 위치 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181948
| 특수문자 출력하기 | 프로그래머스 | Level.0 |
<hr/>
- 특수문자 출력하기 : 다음과 같이 출력하도록 코드를 작성해 주세요.
=> [157일차] 조현서 / 특수문자 출력하기 

3st/Jaeyoung/배열에서 문자열 대소문자 변환하기.js
=> [157일차] 박재영 / 배열에서 문자열 대소문자 변환하기

2st/Riyeon/11005번.java
| 진법 변환 2 | 백준 | 브론즈 I |
<hr/>
- 진법 변환 2 : 10진법 수 N이 주어진다. 이 수를 B진법으로 바꿔 출력하는 프로그램을 작성하시오.
10진법을 넘어가는 진법은 숫자로 표시할 수 없는 자리가 있다. 이런 경우에는 다음과 같이 알파벳 대문자를 사용한다. A: 10, B: 11, ..., F: 15, ..., Y: 34, Z: 35
=> [257일차] 김리연 / 진법 변환 2

3st/Juhee/빈 배열에 추가, 삭제하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181860
| 빈 배열에 추가, 삭제하기 | 프로그래머스 | Level.0 |
<hr/>
- 빈 배열에 추가, 삭제하기 : 아무 원소도 들어있지 않은 빈 배열 X가 있습니다. 길이가 같은 정수 배열 arr과 boolean 배열 flag가 매개변수로 주어질 때, flag를 차례대로 순회하며 flag[i]가 true라면 X의 뒤에 arr[i]를 arr[i] × 2 번 추가하고, flag[i]가 false라면 X에서 마지막 arr[i]개의 원소를 제거한 뒤 X를 return 하는 solution 함수를 작성해 주세요.
=> [158일차] 최주희 / 빈 배열에 추가, 삭제하기

3st/Juhee/정수 부분.java
https://school.programmers.co.kr/learn/courses/30/lessons/181850
| 정수 부분 | 프로그래머스 | Level.0 |
<hr/>
=> [159일차] 최주희 / 정수 부분

2st/Riyeon/2720번.java
| 세탁소 사장 동혁 | 백준 | 브론즈 III |
<hr/>
- 세탁소 사장 동혁 : 미국으로 유학간 동혁이는 세탁소를 운영하고 있다. 동혁이는 최근에 아르바이트로 고등학생 리암을 채용했다. 동혁이는 리암에게 실망했다. 리암은 거스름돈을 주는 것을 자꾸 실수한다. 심지어 $0.5달러를 줘야하는 경우에 거스름돈으로 $5달러를 주는것이다!
어쩔수 없이 뛰어난 코딩 실력을 발휘해 리암을 도와주는 프로그램을 작성하려고 하지만, 디아블로를 하느라 코딩할 시간이 없어서 이 문제를 읽고 있는 여러분이 대신 해주어야 한다.
거스름돈의 액수가 주어지면 리암이 줘야할 쿼터(Quarter, $0.25)의 개수, 다임(Dime, $0.10)의 개수, 니켈(Nickel, $0.05)의 개수, 페니(Penny, $0.01)의 개수를 구하는 프로그램을 작성하시오. 거스름돈은 항상 $5.00 이하이고, 손님이 받는 동전의 개수를 최소로 하려고 한다. 예를 들어, $1.24를 거슬러 주어야 한다면, 손님은 4쿼터, 2다임, 0니켈, 4페니를 받게 된다.
=> [259일차] 김리연 / 세탁소 사장 동혁

3st/Juhee/세 개의 구분자.java
https://school.programmers.co.kr/learn/courses/30/lessons/181862
| 세 개의 구분자 | 프로그래머스 | Level.0 |
<hr/>
- 세 개의 구분자 : 임의의 문자열이 주어졌을 때 문자 "a", "b", "c"를 구분자로 사용해 문자열을 나누고자 합니다.
예를 들어 주어진 문자열이 "baconlettucetomato"라면 나눠진 문자열 목록은 ["onlettu", "etom", "to"] 가 됩니다.
문자열 myStr이 주어졌을 때 위 예시와 같이 "a", "b", "c"를 사용해 나눠진 문자열을 순서대로 저장한 배열을 return 하는 solution 함수를 완성해 주세요.
단, 두 구분자 사이에 다른 문자가 없을 경우에는 아무것도 저장하지 않으며, return할 배열이 빈 배열이라면 ["EMPTY"]를 return 합니다.
=> [160일차] 최주희 / 세 개의 구분자

3st/Jaeyoung/문자열의 앞의 n글자.py
=> [PGS] 문자열의 앞의 n글자 / Level.0

3st/Juhee/문자열 묶기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181855
| 문자열 묶기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 묶기 : 문자열 배열 strArr이 주어집니다. strArr의 원소들을 길이가 같은 문자열들끼리 그룹으로 묶었을 때 가장 개수가 많은 그룹의 크기를 return 하는 solution 함수를 완성해 주세요.
=> [161일차] 최주희 / 문자열 묶기

2st/Riyeon/2292번.java
| 벌집 | 백준 | 브론즈 II |
<hr/>
- 벌집 : 육각형으로 이루어진 벌집이 있다.  중앙의 방 1부터 시작해서 이웃하는 방에 돌아가면서 1씩 증가하는 번호를 주소로 매길 수 있다. 숫자 N이 주어졌을 때, 벌집의 중앙 1에서 N번 방까지 최소 개수의 방을 지나서 갈 때 몇 개의 방을 지나가는지(시작과 끝을 포함하여)를 계산하는 프로그램을 작성하시오. 예를 들면, 13까지는 3개, 58까지는 5개를 지난다.
=> [261일차] 김리연 / 벌집

3st/Juhee/문자열 정수의 합.java
https://school.programmers.co.kr/learn/courses/30/lessons/181849
<hr/>
=> [162일차] 최주희 / 문자열 정수의 합

3st/Jaeyoung/문자열의 뒤의 n글자.py
<hr/>
- 문자열의 뒤의 n글자 : 문자열 my_string과 정수 n이 매개변수로 주어질 때, my_string의 뒤의 n글자로 이루어진 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [162일차] 박재영 / 문자열의 뒤의 n글자

3st/Hyeonseo/programmer/369게임.java, 3st/Hyeonseo/programmer/rn_string.java, 3st/Hyeonseo/programmer/점의 위치 구하기.java, 3st/Hyeonseo/programmer/첫 번째로 나오는 음수.java, 3st/Hyeonseo/programmer/최댓값 만들기 (2).java, 3st/Hyeonseo/programmer/특수문자 출력하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181868
| 공백으로 구분하기 | 프로그래머스 | Level.0 |
<hr/>
- 공백으로 구분하기 : 단어가 공백 한 개 이상으로 구분되어 있는 문자열 my_string이 매개변수로 주어질 때, my_string에 나온 단어를 앞에서부터 순서대로 담은 문자열 배열을 return 하는 solution 함수를 작성해 주세요.
=> [163일차] 조현서 / 공백으로 구분하기 

2st/Riyeon/1193번.java
| 분수찾기 | 백준 | 실버 V |
<hr/>
- 분수찾기 : 나열된 분수들을 1/1 → 1/2 → 2/1 → 3/1 → 2/2 → … 과 같은 지그재그 순서로 차례대로 1번, 2번, 3번, 4번, 5번, … 분수라고 하자. 
X가 주어졌을 때, X번째 분수를 구하는 프로그램을 작성하시오.
=> [262일차] 김리연 / 분수찾기

3st/Jaeyoung/A 강조하기.js
=> [163일차] 박재영 / A 강조하기

3st/Jaeyoung/A 강조하기.js, 3st/Jaeyoung/가까운 1 찾기.js
<hr/>
- 가까운 1 찾기 : 정수 배열 arr가 주어집니다. 이때 arr의 원소는 1 또는 0입니다. 정수 idx가 주어졌을 때, idx보다 크면서 배열의 값이 1인 가장 작은 인덱스를 찾아서 반환하는 solution 함수를 완성해 주세요.
단, 만약 그러한 인덱스가 없다면 -1을 반환합니다.
=> [164일차] 박재영 / 가까운 1 찾기

3st/Hyeonseo/programmer/가까운 1 찾기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181898
<hr/>
- 가까운 1 찾기 : 정수 배열 arr가 주어집니다. 이때 arr의 원소는 1 또는 0입니다. 정수 idx가 주어졌을 때, idx보다 크면서 배열의 값이 1인 가장 작은 인덱스를 찾아서 반환하는 solution 함수를 완성해 주세요.
단, 만약 그러한 인덱스가 없다면 -1을 반환합니다.
=> [165일차] 조현서 / 가까운 1 찾기 

2st/Riyeon/2869번.java
| 달팽이는 올라가고 싶다 | 백준 | 브론즈 I |
<hr/>
- 달팽이는 올라가고 싶다 : 땅 위에 달팽이가 있다. 이 달팽이는 높이가 V미터인 나무 막대를 올라갈 것이다. 달팽이는 낮에 A미터 올라갈 수 있다. 하지만, 밤에 잠을 자는 동안 B미터 미끄러진다. 또, 정상에 올라간 후에는 미끄러지지 않는다.
달팽이가 나무 막대를 모두 올라가려면, 며칠이 걸리는지 구하는 프로그램을 작성하시오.
=> [265일차] 김리연 / 달팽이는 올라가고 싶다

2st/Riyeon/5086번.java
| 배수와 약수 | 백준 | 브론즈 III |
<hr/>
- 배수와 약수 : 두 수가 주어졌을 때, 다음 3가지 중 어떤 관계인지 구하는 프로그램을 작성하시오.
1. 첫 번째 숫자가 두 번째 숫자의 약수이다.
2. 첫 번째 숫자가 두 번째 숫자의 배수이다.
3. 첫 번째 숫자가 두 번째 숫자의 약수와 배수 모두 아니다.
=> [266일차] 김리연 / 배수와 약수

1st/Jaehee/1로 만들기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181880
| 1로 만들기| 프로그래머스 | Level.0 |
<hr/>
- 1로 만들기: 정수가 있을 때, 짝수라면 반으로 나누고, 홀수라면 1을 뺀 뒤 반으로 나누면, 마지막엔 1이 됩니다. 예를 들어 10이 있다면 다음과 같은 과정으로 1이 됩니다.
10 / 2 = 5
2 / 2 = 1
=> [168일} 이제희/1로 만들기

2st/Riyeon/2501번.java
| 약수 구하기 | 백준 | 브론즈 III |
<hr/>
- 약수 구하기 : 어떤 자연수 p와 q가 있을 때, 만일 p를 q로 나누었을 때 나머지가 0이면 q는 p의 약수이다. 
두 개의 자연수 N과 K가 주어졌을 때, N의 약수들 중 K번째로 작은 수를 출력하는 프로그램을 작성하시오.
=> [267일차] 김리연 / 약수 구하기

3st/Jaeyoung/문자열 정렬하기 (2).js
=> [169일차] 박재영 / 문자열 정렬하기 (2)

3st/Hajeong/피자 나눠 먹기 (1).java
| 피자 나눠 먹기(1)  | 프로그래머스 | Level.0 |
<hr/>
- 피자 나눠 먹기(1)  : 머쓱이네 피자가게는 피자를 일곱 조각으로 잘라 줍니다. 피자를 나눠먹을 사람의 수 n이 주어질 때, 모든 사람이 피자를 한 조각 이상 먹기 위해 필요한 피자의 수를 return 하는 solution 함수를 완성해보세요.
=> [169일차] 임하정 / 피자 나눠 먹기(1) 

1st/Jaehee/각도 합치기.java
https://school.programmers.co.kr/learn/courses/30/lessons/340206
| 각도 합치기| 프로그래머스 | 브론즈 V / Level.1 |
<hr/>
- 각도 합치기: 일반적으로 두 선분이 이루는 각도는 한 바퀴를 360도로 하여 표현합니다. 따라서 각도에 360의 배수를 더하거나 빼더라도 같은 각을 의미합니다. 예를 들면, 30도와 390도는 같은 각도입니다.
주어진 코드는 각도를 나타내는 두 정수 angle1과 angle2가 주어질 때, 이 두 각의 합을 0도 이상 360도 미만으로 출력하는 코드입니다. 코드가 올바르게 작동하도록 한 줄을 수정해 주세요.
=> [169일} 이제희/각도 합치기

2st/Riyeon/데이터 분석.java
| 데이터 분석 | 프로그래머스 | Level.1 |
<hr/>
- 데이터 분석 : 정렬한 데이터들이 담긴 이차원 정수 리스트 data와 어떤 정보를 기준으로 데이터를 뽑아낼지를 의미하는 문자열 ext, 뽑아낼 정보의 기준값을 나타내는 정수 val_ext, 정보를 정렬할 기준이 되는 문자열 sort_by가 주어집니다.
data에서 ext 값이 val_ext보다 작은 데이터만 뽑은 후, sort_by에 해당하는 값을 기준으로 오름차순으로 정렬하여 return 하도록 solution 함수를 완성해 주세요. 단, 조건을 만족하는 데이터는 항상 한 개 이상 존재합니다.
=> [269일차] 김리연 / 데이터 분석

프로그래머스/0/120822. 뒤집힌 문자열/README.md, 프로그래머스/0/120822. 뒤집힌 문자열/뒤집힌 문자열.java
https://school.programmers.co.kr/learn/courses/30/lessons/120816
| 피자 나눠 먹기 | 프로그래머스 | Level.0 |
<hr/>
- 피자 나눠 먹기 : 머쓱이네 피자가게는 피자를 두 조각에서 열 조각까지 원하는 조각 수로 잘라줍니다. 피자 조각 수 slice와 피자를 먹는 사람의 수 n이 매개변수로 주어질 때, n명의 사람이 최소 한 조각 이상 피자를 먹으려면 최소 몇 판의 피자를 시켜야 하는지를 return 하도록 solution 함수를 완성해보세요.
=> [2일차] 임하정 / 피자 나눠 먹기

2st/Riyeon/27323번.java
| 직사각형 | 프로그래머스 | 브론즈 V |
<hr/>
- 직사각형 : 정수 A, B 가 주어진다. 세로 길이가 A cm, 가로 길이가 B cm 인 아래와 같은 직사각형의 넓이를 cm2 단위로 구하시오.
=> [270일차] 김리연 / 직사각형

2st/Yeonwoo/중성화 여부 파악하기.SQL
| 중성화 여부 파악하기 | 프로그래머스 | [Level.2](https://school.programmers.co.kr/learn/courses/30/lessons/59409) |
<hr/>
- 중성화 여부 파악하기 : 보호소의 동물이 중성화되었는지 아닌지 파악하려 합니다. 중성화된 동물은 SEX_UPON_INTAKE 컬럼에 'Neutered' 또는 'Spayed'라는 단어가 들어있습니다. 동물의 아이디와 이름, 중성화 여부를 아이디 순으로 조회하는 SQL문을 작성해주세요. 이때 중성화가 되어있다면 'O', 아니라면 'X'라고 표시해주세요.
=> [270일차] 채연우 / 중성화 여부 파악하기

2st/Riyeon/1085번.java
| 직사각형에서 탈출 | 백준 | 브론즈 III |
<hr/>
- 직사각형에서 탈출 : 한수는 지금 (x, y)에 있다. 직사각형은 각 변이 좌표축에 평행하고, 왼쪽 아래 꼭짓점은 (0, 0), 오른쪽 위 꼭짓점은 (w, h)에 있다. 직사각형의 경계선까지 가는 거리의 최솟값을 구하는 프로그램을 작성하시오.
=> [271일차] 김리연 / 직사각형에서 탈출 

2st/Riyeon/27323번.java, 2st/Yeonwoo/중성화 여부 파악하기.SQL, 프로그래머스/0/120822. 뒤집힌 문자열/README.md, 프로그래머스/0/120822. 뒤집힌 문자열/뒤집힌 문자열.java, 프로그래머스/0/181842. 부분 문자열/README.md, 프로그래머스/0/181842. 부분 문자열/부분 문자열.java
<hr/>
- 부분 문자열 : 어떤 문자열 A가 다른 문자열 B안에 속하면 A를 B의 부분 문자열이라고 합니다. 예를 들어 문자열 "abc"는 문자열 "aabcc"의 부분 문자열입니다.
문자열 str1과 str2가 주어질 때, str1이 str2의 부분 문자열이라면 1을 부분 문자열이 아니라면 0을 return하도록 solution 함수를 완성해주세요.
=> [172일] 조현서 / 부분 문자열

2st/Riyeon/3009번.java
| 네 번째 점 | 백준 | 브론즈 III |
<hr/>
- 네 번째 점 : 세 점이 주어졌을 때, 축에 평행한 직사각형을 만들기 위해서 필요한 네 번째 점을 찾는 프로그램을 작성하시오.
=> [272일차] 김리연 / 네 번째 점

2st/Yeonwoo/조건별로 분류하여 주문상태 출력하기.SQL
| 조건별로 분류하여 주문상태 출력하기 | 프로그래머스 | [Level.3](https://school.programmers.co.kr/learn/courses/30/lessons/131113) |
<hr/>
- 조건별로 분류하여 주문상태 출력하기 : FOOD_ORDER 테이블에서 2022년 5월 1일을 기준으로 주문 ID, 제품 ID, 출고일자, 출고여부를 조회하는 SQL문을 작성해주세요. 출고여부는 2022년 5월 1일까지 출고완료로 이 후 날짜는 출고 대기로 미정이면 출고미정으로 출력해주시고, 결과는 주문 ID를 기준으로 오름차순 정렬해주세요.
=> [272일차] 채연우 / 조건별로 분류하여 주문상태 출력하기

프로그래머스/0/120892. 암호 해독/README.md, 프로그래머스/0/120892. 암호 해독/암호 해독.java
| 암호 해독 | 프로그래머스 | Level.0 |
<hr/>
- 암호 해독 : 군 전략가 머쓱이는 전쟁 중 적군이 다음과 같은 암호 체계를 사용한다는 것을 알아냈습니다.
암호화된 문자열 cipher를 주고받습니다.
그 문자열에서 code의 배수 번째 글자만 진짜 암호입니다.
문자열 cipher와 정수 code가 매개변수로 주어질 때 해독된 암호 문자열을 return하도록 solution 함수를 완성해주세요.
=> [174일차]  조현서 / 암호 해독

3st/Jaeyoung/문자열 정수의 합.js
=> [174일차] 박재영 / 문자열 정수의 합

2st/Riyeon/15894번.java
| 수학은 체육과목 입니다 | 백준 | 브론즈 III |
<hr/>
- 수학은 체육과목 입니다 : "한 변의 길이가 1인 정사각형을 아래 그림과 같이 겹치지 않게 빈틈없이 계속 붙여 나간다. 가장 아랫부분의 정사각형이 n개가 되었을 때, 실선으로 이루어진 도형의 둘레의 길이를 구하시오."
가장 아랫부분의 정사각형 개수가 주어지면 그에 해당하는 답을 출력하는 프로그램을 만들어 형석이를 도와주자!
=> [273일차] 김리연 / 수학은 체육과목 입니다

3st/Jaeyoung/약수의 합.java, 3st/Jaeyoung/평균 구하기.js
| 약수의 합 | 프로그래머스 | Level.1 |
<hr/>
- 약수의 합 : 정수 n을 입력받아 n의 약수를 모두 더한 값을 리턴하는 함수, solution을 완성해주세요.
=> [175일차] 박재영 / 약수의 합

2st/Riyeon/9063번.java
| 대지 | 백준 | 브론즈 III |
<hr/>
- 대지 : 임씨의 이름이 새겨진 옥구슬의 위치 N 개가 주어질 때에, 임씨에게 돌아갈 대지의 넓이를 계산하는 프로그램을 작성하시오. 단, 옥구슬의 위치는 2 차원 정수 좌표로 주어지고 옥구슬은 같은 위치에 여러 개가 발견될 수도 있으며, x 축의 양의방향을 동쪽, y 축의 양의방향을 북쪽이라고 가정한다.
=> [274일차] 김리연 / 대지

3st/Hajeong/programmer/하샤드 수.java, 프로그래머스/1/12947. 하샤드 수/README.md, 프로그래머스/1/12947. 하샤드 수/하샤드 수.java
| 하샤드 수 | 프로그래머스 | Level.1 |
<hr/>
- 하샤드 수 : 양의 정수 x가 하샤드 수이려면 x의 자릿수의 합으로 x가 나누어져야 합니다. 예를 들어 18의 자릿수 합은 1+8=9이고, 18은 9로 나누어 떨어지므로 18은 하샤드 수입니다. 자연수 x를 입력받아 x가 하샤드 수인지 아닌지 검사하는 함수, solution을 완성해주세요.
=> [6일차] 임하정 / 하샤드 수

3st/Jaeyoung/분수의 덧셈.py
| 분수의 덧셈 | 프로그래머스 | Level.0 |
<hr/>
- 분수의 덧셈 : 첫 번째 분수의 분자와 분모를 뜻하는 numer1, denom1, 두 번째 분수의 분자와 분모를 뜻하는 numer2, denom2가 매개변수로 주어집니다. 두 분수를 더한 값을 기약 분수로 나타냈을 때 분자와 분모를 순서대로 담은 배열을 return 하도록 solution 함수를 완성해보세요.
=> [176일차] 박재영 / 분수의 덧셈

2st/Riyeon/10101번.java
| 삼각형 외우기 | 백준 | 브론즈 IV  |
<hr/>
- 삼각형 외우기 : 삼각형의 세 각을 입력받은 다음, 세 각의 크기가 모두 60이면 Equilateral, 세 각의 합이 180이고, 두 각이 같은 경우에는 Isosceles, 세 각의 합이 180이고 같은 각이 없는 경우에는 Scalene, 세 각의 합이 180이 아닌 경우에는 Error 를 출력하는 프로그램을 작성하시오.
=> [275일차] 김리연 / 삼각형 외우기

4st/Eunseong/두 수의 합 구하기.c, 4st/Eunseong/뒤집힌 문자열.java, 4st/Eunseong/분수의 덧셈.java, 4st/Eunseong/피자 나눠 먹기(1).c, 4st/Eunseong/피자 나눠 먹기(3).c, 4st/Eunseong/피자 나눠 먹기(3).java
| 피자 나눠 먹기(1) | 프로그래머스 | Level.0 |
| 피자 나눠 먹기(3) | 프로그래머스 | Level.0 |
| 뒤집힌 문자열 | 프로그래머스 | Level.0 |
| 분수의 덧셈 | 프로그래머스 | Level.0 |
<hr/>
- 피자 나눠 먹기(1) : 머쓱이네 피자가게는 피자를 일곱 조각으로 잘라 줍니다. 피자를 나눠먹을 사람의 수 n이 주어질 때, 모든 사람이 피자를 한 조각 이상 먹기 위해 필요한 피자의 수를 return 하는 solution 함수를 완성해보세요.
- 피자 나눠 먹기(3) : 머쓱이네 피자가게는 피자를 두 조각에서 열 조각까지 원하는 조각 수로 잘라줍니다. 피자 조각 수 slice와 피자를 먹는 사람의 수 n이 매개변수로 주어질 때, n명의 사람이 최소 한 조각 이상 피자를 먹으려면 최소 몇 판의 피자를 시켜야 하는지를 return 하도록 solution 함수를 완성해보세요.
- 뒤집힌 문자열 : 문자열 my_string이 매개변수로 주어집니다. my_string을 거꾸로 뒤집은 문자열을 return하도록 solution 함수를 완성해주세요.
- 첫 번째 분수의 분자와 분모를 뜻하는 numer1, denom1, 두 번째 분수의 분자와 분모를 뜻하는 numer2, denom2가 매개변수로 주어집니다. 두 분수를 더한 값을 기약 분수로 나타냈을 때 분자와 분모를 순서대로 담은 배열을 return 하도록 solution 함수를 완성해보세요.
=> [1일차] 공은성 / 피자 나눠 먹기(1) 외 4개

4st/Eunseong/각도기.c, 4st/Eunseong/양꼬치.c
=> [2일차] 공은성 / 각도기 외 1개

2st/Riyeon/5073번.java
| 삼각형과 세 변 | 백준 | 브론즈 III |
<hr/>
- 삼각형과 세 변 : 삼각형의 세 변의 길이가 주어질 때 변의 길이에 따라 다음과 같이 정의한다.
Equilateral :  세 변의 길이가 모두 같은 경우
Isosceles : 두 변의 길이만 같은 경우
Scalene : 세 변의 길이가 모두 다른 경우
단 주어진 세 변의 길이가 삼각형의 조건을 만족하지 못하는 경우에는 "Invalid" 를 출력한다. 예를 들어 6, 3, 2가 이 경우에 해당한다. 가장 긴 변의 길이보다 나머지 두 변의 길이의 합이 길지 않으면 삼각형의 조건을 만족하지 못한다.
세 변의 길이가 주어질 때 위 정의에 따른 결과를 출력하시오.
=> [278일차] 김리연 / 삼각형과 세 변

2st/Riyeon/14215번.java
| 세 막대 | 백준 | 브론즈 III |
<hr/>
- 세 막대 : 영선이는 길이가 a, b, c인 세 막대를 가지고 있고, 각 막대의 길이를 마음대로 줄일 수 있다. 영선이는 세 막대를 이용해서 아래 조건을 만족하는 삼각형을 만들려고 한다. 
각 막대의 길이는 양의 정수이다
세 막대를 이용해서 넓이가 양수인 삼각형을 만들 수 있어야 한다.
삼각형의 둘레를 최대로 해야 한다.
a, b, c가 주어졌을 때, 만들 수 있는 가장 큰 둘레를 구하는 프로그램을 작성하시오.
=> [279일차] 김리연 / 세 막대

2st/Riyeon/9506번.java
| 약수들의 합 | 백준 | 브론즈 I |
<hr/>
- 약수들의 합 : 어떤 숫자 n이 자신을 제외한 모든 약수들의 합과 같으면, 그 수를 완전수라고 한다. 
예를 들어 6은 6 = 1 + 2 + 3 으로 완전수이다. 
n이 완전수인지 아닌지 판단해주는 프로그램을 작성하라.
=> [280일차] 김리연 / 약수들의 합

2st/Riyeon/1978번.java
| 소수 찾기 | 백준 | 브론즈 II |
<hr/>
- 소수 찾기 : 주어진 수 N개 중에서 소수가 몇 개인지 찾아서 출력하는 프로그램을 작성하시오.
=> [281일차] 김리연 / 소수 찾기

2st/Riyeon/2581번.java
| 소수 | 백준 | 브론즈 II |
<hr/>
- 소수 : 자연수 M과 N이 주어질 때 M이상 N이하의 자연수 중 소수인 것을 모두 골라 이들 소수의 합과 최솟값을 찾는 프로그램을 작성하시오.
예를 들어 M=60, N=100인 경우 60이상 100이하의 자연수 중 소수는 61, 67, 71, 73, 79, 83, 89, 97 총 8개가 있으므로, 이들 소수의 합은 620이고, 최솟값은 61이 된다.
=> [282일차] 김리연 / 소수

2st/Riyeon/11653번.java
| 소인수분해 | 백준 | 브론즈 I |
<hr/>
- 소인수분해 : 정수 N이 주어졌을 때, 소인수분해하는 프로그램을 작성하시오.
=> [283일차] 김리연 / 소인수분해

2st/Riyeon/2750번.java
| 수 정렬하기 | 백준 | 브론즈 II |
<hr/>
- 수 정렬하기 : N개의 수가 주어졌을 때, 이를 오름차순으로 정렬하는 프로그램을 작성하시오.
=> [284일차] 김리연 / 수 정렬하기

2st/Riyeon/2587번.java
| 대표값2 | 백준 | 브론즈 II |
<hr/>
- 대표값2 : 어떤 수들이 있을 때, 그 수들을 대표하는 값으로 가장 흔하게 쓰이는 것은 평균이다. 평균은 주어진 모든 수의 합을 수의 개수로 나눈 것이다. 평균 이외의 또 다른 대표값으로 중앙값이라는 것이 있다. 중앙값은 주어진 수를 크기 순서대로 늘어 놓았을 때 가장 중앙에 놓인 값이다. 다섯 개의 자연수가 주어질 때 이들의 평균과 중앙값을 구하는 프로그램을 작성하시오.
=> [286일차] 김리연 / 대표값2

2st/Riyeon/25305번.java
| 커트라인 | 백준 | 브론즈 II |
<hr/>
- 커트라인 : 2022 연세대학교 미래캠퍼스 슬기로운 코딩생활에 N명의 학생들이 응시했다. 이들 중 점수가 가장 높은 k명은 상을 받을 것이다. 이 때, 상을 받는 커트라인이 몇 점인지 구하라.
커트라인이란 상을 받는 사람들 중 점수가 가장 가장 낮은 사람의 점수를 말한다.
=> [287일차] 김리연/ 커트라인

프로그래머스/1/12950. 행렬의 덧셈/README.md, 프로그래머스/1/12950. 행렬의 덧셈/행렬의 덧셈.java
| 행렬의 덧셈 | 프로그래머스 | Level.1 |
<hr/>
- 행렬의 덧셈 : 행렬의 덧셈은 행과 열의 크기가 같은 두 행렬의 같은 행, 같은 열의 값을 서로 더한 결과가 됩니다. 2개의 행렬 arr1과 arr2를 입력받아, 행렬 덧셈의 결과를 반환하는 함수, solution을 완성해주세요.
=> [189일차] 조현서 / 행렬의 덧셈

프로그래머스/0/340205. ［PCCE 기출문제］ 3번 ／ 수 나누기/README.md, 프로그래머스/0/340205. ［PCCE 기출문제］ 3번 ／ 수 나누기/［PCCE 기출문제］ 3번 ／ 수 나누기.java
…MB -BaekjoonHub
| 수 나누기 | 프로그래머스 | Level.1 |
<hr/>
- 수 나누기 : 2자리 이상의 정수 number가 주어집니다. 주어진 코드는 이 수를 2자리씩 자른 뒤, 자른 수를 모두 더해서 그 합을 출력하는 코드입니다. 코드가 올바르게 작동하도록 한 줄을 수정해 주세요.
=> [190일차] 조현서 / 수 나누기

4st/Eunseong/피자 나눠 먹기(2).java
https://school.programmers.co.kr/learn/courses/30/lessons/120815
| 피자 나눠 먹기 (2) | 프로그래머스 | Level.0 |
<hr/>
- 피자 나눠 먹기 (2) : 머쓱이네 피자가게는 피자를 여섯 조각으로 잘라 줍니다. 피자를 나눠먹을 사람의 수 n이 매개변수로 주어질 때, n명이 주문한 피자를 남기지 않고 모두 같은 수의 피자 조각을 먹어야 한다면 최소 몇 판을 시켜야 하는지를 return 하도록 solution 함수를 완성해보세요.
=> [2일차] 공은성 / 피자 나눠 먹기 (2)

4st/Seohyun/programmer/나머지 구하기.java, 4st/Seohyun/programmer/짝수와 홀수.java
https://school.programmers.co.kr/learn/courses/30/lessons/12937
| 짝수와 홀수 | 프로그래머스 | Level.1 |
<hr/>
- 짝수와 홀수 : 정수 num이 짝수일 경우 "Even"을 반환하고 홀수인 경우 "Odd"를 반환하는 함수, solution을 완성해주세요.
=> [2일차] 이서현 / 짝수와 홀수

3st/Juram/programmer/왼쪽 오른쪽.js, 3st/Juram/programmer/홀짝 구분하기.java
| 왼쪽 오른쪽 | 프로그래머스 | Level.0 |
<hr/>
- 왼쪽 오른쪽 : 문자열 리스트 str_list에는 "u", "d", "l", "r" 네 개의 문자열이 여러 개 저장되어 있습니다. str_list에서 "l"과 "r" 중 먼저 나오는 문자열이 "l"이라면 해당 문자열을 기준으로 왼쪽에 있는 문자열들을 순서대로 담은 리스트를, 먼저 나오는 문자열이 "r"이라면 해당 문자열을 기준으로 오른쪽에 있는 문자열들을 순서대로 담은 리스트를 return하도록 solution 함수를 완성해주세요. "l"이나 "r"이 없다면 빈 리스트를 return합니다.
=> [2일차] 김주람 / 왼쪽 오른쪽

4st/Eunseong/편지.java
https://school.programmers.co.kr/learn/courses/30/lessons/120898
<hr/>
- 편지 : 머쓱이는 할머니께 생신 축하 편지를 쓰려고 합니다. 할머니가 보시기 편하도록 글자 한 자 한 자를 가로 2cm 크기로 적으려고 하며, 편지를 가로로만 적을 때, 축하 문구 message를 적기 위해 필요한 편지지의 최소 가로길이를 return 하도록 solution 함수를 완성해주세요.
=> [3일차] 공은성 / 편지

4st/Gau/baekjoon/Hello World, 4st/Gau/baekjoon/두수비교하기.java
https://www.acmicpc.net/problem/2557
| Hello world | 백준 / 프로그래머스 | 브론즈 V / Level.1 |
<hr/>
- Hello world :Hello World!를 출력하시오.
=> [1일차] 노가우 / Hello World

4st/Hani/baekjoon/A×B
https://www.acmicpc.net/problem/10998
| A×B | 백준 | 브론즈 5 |
<hr/>
- A×B : 두 정수 A와 B를 입력받은 다음, A×B를 출력하는 프로그램을 작성하시오.
=> [3일차] 최한이 A×B / 브론즈5

4st/Seohyun/programmer/각도기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120829
<hr/>
=> [3일차] 이서현 / 각도기

3st/Juram/programmer/rny_string.js, 3st/Juram/programmer/문자 리스트를 문자열로 변환하기.js, 3st/Juram/programmer/문자열의 앞의 n글자.js
<hr/>
- 제목 : 'm'과 "rn"이 모양이 비슷하게 생긴 점을 활용해 문자열에 장난을 하려고 합니다. 문자열 rny_string이 주어질 때, rny_string의 모든 'm'을 "rn"으로 바꾼 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [3일차] 김주람 / rny_string 외 2개

3st/Juram/programmer/할 일 목록.js
<hr/>
- 제목 : 오늘 해야 할 일이 담긴 문자열 배열 todo_list와 각각의 일을 지금 마쳤는지를 나타내는 boolean 배열 finished가 매개변수로 주어질 때, todo_list에서 아직 마치지 못한 일들을 순서대로 담은 문자열 배열을 return 하는 solution 함수를 작성해 주세요.
=> [4일차] 김주람 / 할 일 목록

3st/Jiyu/baekjoon/별 찍기 - 1.py, 3st/Jiyu/baekjoon/코딩은 체육과목 입니다.py, 3st/Jiyu/baekjoon/합.py
https://www.acmicpc.net/problem/8393
| 코딩은 체육과목 입니다  | 백준 | 브론즈 V |
| 별 찍기 - 1 | 백준 | 브론즈 V |
<hr/>
- 코딩은 체육과목 입니다 : 오늘은 혜아의 면접 날이다. 면접 준비를 열심히 해서 앞선 질문들을 잘 대답한 혜아는 이제 마지막으로 칠판에 직접 코딩하는 문제를 받았다. 혜아가 받은 문제는 두 수를 더하는 문제였다. C++ 책을 열심히 읽었던 혜아는 간단히 두 수를 더하는 코드를 칠판에 적었다. 코드를 본 면접관은 다음 질문을 했다. “만약, 입출력이 
$N$바이트 크기의 정수라면 프로그램을 어떻게 구현해야 할까요?”
혜아는 책에 있는 정수 자료형과 관련된 내용을 기억해 냈다. 책에는 long int는 
$4$바이트 정수까지 저장할 수 있는 정수 자료형이고 long long int는 
$8$바이트 정수까지 저장할 수 있는 정수 자료형이라고 적혀 있었다. 혜아는 이런 생각이 들었다. “int 앞에 long을 하나씩 더 붙일 때마다 
$4$바이트씩 저장할 수 있는 공간이 늘어나는 걸까? 분명 long long long int는 
$12$바이트, long long long long int는 
$16$바이트까지 저장할 수 있는 정수 자료형일 거야!” 그렇게 혜아는 당황하는 면접관의 얼굴을 뒤로한 채 칠판에 정수 자료형을 써 내려가기 시작했다.
혜아가 
$N$바이트 정수까지 저장할 수 있다고 생각해서 칠판에 쓴 정수 자료형의 이름은 무엇일까?
- 별찍기 - …
=> [2일차] 임지유  /  합

3st/Jaeyoung/두 수의 차 구하기.py
=> 박재영 / 두 수의 차 구하기

3st/Jaehee/문자열 출력하기.py
문자열 str이 주어질 때, str을 출력하는 코드를 작성해 보세요.
| 문자열 출력하기| 프로그래머스 | Level.0 |
<hr/>
- 문자열 출력하기 : 문자열 str이 주어질 때, str을 출력하는 코드를 작성해 보세요.
=> [193일] 이제희/문자열 출력하기

4st/Eunseong/특정 문자 제거하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120826
<hr/>
=> [4일차] 공은성 / 특정 문자 제거하기

4st/Eunseong/최댓값 만들기(1).java
https://school.programmers.co.kr/learn/courses/30/lessons/120847
| 최댓값 만들기 (1) | 프로그래머스 | Level.0 |
<hr/>
- 최댓값 만들기 (1) : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소 중 두 개를 곱해 만들 수 있는 최댓값을 return하도록 solution 함수를 완성해주세요.
=> [5일차] 공은성 / 최댓값 만들기 (1)

3st/Jiyu/baekjoon/두 수 비교하기.java
https://www.acmicpc.net/problem/1330
| 두 수 비교하기 | 백준 / 프로그래머스 | 브론즈 V |
<hr/>
- 두 수 비교하기 : 두 정수 A와 B가 주어졌을 때, A와 B를 비교하는 프로그램을 작성하시오.
=> [5일차] 임지유 / 두 수 비교하기

3st/Jaehee/a와 b 출력하기.py
https://school.programmers.co.kr/learn/courses/30/lessons/181951
<hr/>
- a와 b 출력하기 : 정수 a와 b가 주어집니다. 각 수를 입력받아 입출력 예와 같은 형식으로 출력하는 코드를 작성해 보세요.
=> [194일] 이제희/a와 b 출력하기

4st/Gau/baekjoon/꼬마정민.java
https://www.acmicpc.net/submit/11382/94028678
| 꼬마 정민 | 백준 | 브론즈 V |
<hr/>
- 꼬마정민 : 꼬마 정민이는 이제 A + B 정도는 쉽게 계산할 수 있다. 이제 A + B + C를 계산할 차례이다!
- A+B+C의 값을 출력한다.
=> [5일차] 노가우 / 꼬마 정민

4st/Eunseong/짝수는 싫어요.java
https://school.programmers.co.kr/learn/courses/30/lessons/120813
| 짝수는 싫어요 | 프로그래머스 | Level.0 |
<hr/>
=> [6일차] 공은성 / 짝수는 싫어요

3st/Jaehee/문자열 반복해서 출력하기.py
https://school.programmers.co.kr/learn/courses/30/lessons/181950?language=python3
| 문자열 반복해서 출력하기 | 프로그래머스 | Level.0 |
<hr/>
=> [195] 이제희/문자열 반복해서 출력하기

4st/Eunseong/자릿수 더하기.java
=> [7일차] 공은성 / 자릿수 더하기

3st/Juram/programmer/정수 제곱근 판별.java
| 정수 제곱근 판별 | 프로그래머스 | Level.1 |
<hr/>
- 제목 : 임의의 양의 정수 n에 대해, n이 어떤 양의 정수 x의 제곱인지 아닌지 판단하려 합니다.
n이 양의 정수 x의 제곱이라면 x+1의 제곱을 리턴하고, n이 양의 정수 x의 제곱이 아니라면 -1을 리턴하는 함수를 완성하세요.
=> [7일차] 김주람 / 정수 제곱근 판별

3st/Juram/programmer/a와 b 출력하기.c, 3st/Juram/programmer/특정 문자 제거하기.js
<hr/>
- 제목 : 정수 a와 b가 주어집니다. 각 수를 입력받아 입출력 예와 같은 형식으로 출력하는 코드를 작성해 보세요.
=> [9일차] 김주람 / a와 b 출력하기 외 1개

3st/Jiyu/baekjoon/시험 성적.java
https://www.acmicpc.net/problem/9498
| 시험 성적 | 백준 | 브론즈 V |
<hr/>
- 시험 성적 : 시험 점수를 입력받아 90 ~ 100점은 A, 80 ~ 89점은 B, 70 ~ 79점은 C, 60 ~ 69점은 D, 나머지 점수는 F를 출력하는 프로그램을 작성하시오.
=> [8일차]  임지유 / 시험 성적

4st/Eunseong/최빈값 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120812
| 최빈값 구하기 | 프로그래머스 | Level.0 |
<hr/>
=> [8일차] 공은성 / 최빈값 구하기

3st/Jaehee/두 수의 차 구하기.py
https://school.programmers.co.kr/learn/courses/30/lessons/120803?language=python3
<hr/>
=> [197일] 이제희/두 수의 차 구하기

4st/Hani/baekjoon/나머지.java
https://www.acmicpc.net/problem/10430
| 나머지 | 백준 | 브론즈 5 |
<hr/>
- 나머지 : (A+B)%C는 ((A%C) + (B%C))%C 와 같을까?
(A×B)%C는 ((A%C) × (B%C))%C 와 같을까?
세 수 A, B, C가 주어졌을 때, 위의 네 가지 값을 구하는 프로그램을 작성하시오.
=> [8일차] 최한이 / 나머지

4st/Gau/baekjoon/구구단.java
https://www.acmicpc.net/submit/2739/94185192
| 제목| 사이트| 레벨 |
| 구구단 | 백준 | 브론즈 V |
<hr/>
=> [8일차] 노가우 / 구구단

3st/Jiyu/baekjoon/윤년.java
https://www.acmicpc.net/problem/2753
| 윤년 | 백준 | 브론즈 V |
<hr/>
- 윤년 : 연도가 주어졌을 때, 윤년이면 1, 아니면 0을 출력하는 프로그램을 작성하시오.
윤년은 연도가 4의 배수이면서, 100의 배수가 아닐 때 또는 400의 배수일 때이다.
예를 들어, 2012년은 4의 배수이면서 100의 배수가 아니라서 윤년이다. 1900년은 100의 배수이고 400의 배수는 아니기 때문에 윤년이 아니다. 하지만, 2000년은 400의 배수이기 때문에 윤년이다.
=> [9일차] 임지유 / 윤년

4st/Hani/baekjoon/곱셈.java
https://www.acmicpc.net/problem/2588
| 곱셈 | 백준 | 브론즈 5|
<hr/>
- 곱 : (세 자리 수) × (세 자리 수)는 다음과 같은 과정을 통하여 이루어진다.
(1)과 (2)위치에 들어갈 세 자리 자연수가 주어질 때 (3), (4), (5), (6)위치에 들어갈 값을 구하는 프로그램을 작성하시오.
=> [9일차] 최한이 / 곱셈

3st/Juram/programmer/1로 만들기.java
| 1로 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 1로 만들기 : 정수가 있을 때, 짝수라면 반으로 나누고, 홀수라면 1을 뺀 뒤 반으로 나누면, 마지막엔 1이 됩니다. 예를 들어 10이 있다면 다음과 같은 과정으로 1이 됩니다.
10 / 2 = 5
2 / 2 = 1
=> [9일차] 김주람 / 1로 만들기

3st/Jaehee/두 수의 곱 구하기.py
https://school.programmers.co.kr/learn/courses/30/lessons/120804?language=python3
<hr/>
=> [198일] 이제희/두 수의 곱 구하기

4st/Eunseong/짝수 홀수 개수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120824
| 짝수 홀수 갯수 | 프로그래머스 | Level.0 |
<hr/>
- 짝수 홀수 갯수 : 정수가 담긴 리스트 num_list가 주어질 때, num_list의 원소 중 짝수와 홀수의 개수를 담은 배열을 return 하도록 solution 함수를 완성해보세요.
=> [9일차] 공은성 / 짝수 홀수 갯수

3st/Juram/programmer/n 번쨰 원소까지.js
<hr/>
- n 번째 원소까지 : 정수 리스트 num_list와 정수 n이 주어질 때, num_list의 첫 번째 원소부터 n 번째 원소까지의 모든 원소를 담은 리스트를 return하도록 solution 함수를 완성해주세요.
=> [10일차] 김주람 / n 번째 원소까지

4st/Eunseong/중앙값 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120811
<hr/>
=> [10일차] 공은성 / 중앙값 구하기

3st/Jaehee/몫 구하기.py
https://school.programmers.co.kr/learn/courses/30/lessons/120805
| 몫 구하기 | 프로그래머스 | Level.0 |
<hr/>
- 몫 구하기 : 정수 num1, num2가 매개변수로 주어질 때, num1을 num2로 나눈 몫을 return 하도록 solution 함수를 완성해주세요.
=> [199일] 이제희/몫 구하기

3st/Hyeonseo/programmer/덧셈식 출력하기.java, 3st/Hyeonseo/programmer/문자 리스트를 문자열로 변환하기.py, 프로그래머스/0/181941. 문자 리스트를 문자열로 변환하기/README.md, 프로그래머스/0/181941. 문자 리스트를 문자열로 변환하기/문자 리스트를 문자열로 변환하기.py
<hr/>
- 문자 리스트를 문자열로 변환하기 : 문자들이 담겨있는 배열 arr가 주어집니다. arr의 원소들을 순서대로 이어 붙인 문자열을 return 하는 solution함수를 작성해 주세요
=> [199일차] 조현서 / 문자 리스트를 문자열로 변환하기

3st/Jiyu/baekjoon/꼬마 정민.java
https://www.acmicpc.net/problem/11382
| 꼬마 정민 | 백준 | 브론즈 V |
<hr/>
- 꼬마 정민 : 꼬마 정민이는 이제 A + B 정도는 쉽게 계산할 수 있다. 이제 A + B + C를 계산할 차례이다!
=> [10일차] 임지유 / 꼬마 정민

4st/Hani/baekjoon/ID check.java, 4st/Hani/baekjoon/꼬마 정민.java
https://www.acmicpc.net/problem/11382
| 꼬마 정민 | 백준 | 브론즈5 |
<hr/>
- 꼬마 정민 : 꼬마 정민이는 이제 A + B 정도는 쉽게 계산할 수 있다. 이제 A + B + C를 계산할 차례이다!
=> [10일차] 최한이 / 꼬마 정민

3st/Jaeyoung/문자열 정렬하기 (1).js
| 문자열 정렬하기 (1) | 프로그래머스 | Level.0 |
<hr/>
- 문자열 정렬하기 (1) : 문자열 my_string이 매개변수로 주어질 때, my_string 안에 있는 숫자만 골라 오름차순 정렬한 리스트를 return 하도록 solution 함수를 작성해보세요.
=> [199일차] 박재영 / 문자열 정렬하기 (1)

4st/Gau/baekjoon/두수곱하기.java
https://www.acmicpc.net/submit/10998/94231936
| 두수곱하기 | 백준 | 브론즈5 |
| 두수곱하기 | 백준 / 프로그래머스 | 브론즈 V / Level.1 |
<hr/>
- A*B : 두 정수 A와 B를 입력받은 다음, A×B를 출력하는 프로그램을 작성하시오.
=> [BOJ] 9일차/ 두수곱하기 / 브론즈 5

3st/Jiyu/baekjoon/사분면 고르기.py
https://www.acmicpc.net/problem/14681
| 사분면 고르기 | 백준 | 브론즈 V |
<hr/>
- 사분면 고르기 : 흔한 수학 문제 중 하나는 주어진 점이 어느 사분면에 속하는지 알아내는 것이다. 사분면은 아래 그림처럼 1부터 4까지 번호를 갖는다. "Quadrant n"은 "제n사분면"이라는 뜻이다.
예를 들어, 좌표가 (12, 5)인 점 A는 x좌표와 y좌표가 모두 양수이므로 제1사분면에 속한다. 점 B는 x좌표가 음수이고 y좌표가 양수이므로 제2사분면에 속한다.
점의 좌표를 입력받아 그 점이 어느 사분면에 속하는지 알아내는 프로그램을 작성하시오. 단, x좌표와 y좌표는 모두 양수나 음수라고 가정한다.
=> [BOJ] 임지유 / 사분면 고르기

4st/Eunseong/가위 바위 보.java, 4st/Eunseong/가장 큰 수 찾기.java, 4st/Eunseong/개미 군단.java, 4st/Eunseong/나머지 구하기.java, 4st/Eunseong/나이 출력.c, 4st/Eunseong/더 크게 합치기.java, 4st/Eunseong/두 수의 곱 구하기.c, 4st/Eunseong/두 수의 나눗셈.c, 4st/Eunseong/두 수의 차 구하기.c, 4st/Eunseong/머쓱이보다 키 큰 사람.java, 4st/Eunseong/몫 구하기.c, 4st/Eunseong/문자 반복 출력하기.java, 4st/Eunseong/문자열안에 문자열.java, 4st/Eunseong/배열 뒤집기.java, 4st/Eunseong/배열 원소의 길이.java, 4st/Eunseong/배열의 유사도.java, 4st/Eunseong/배열의 평균값.java, 4st/Eunseong/삼각형의 완성조건(1).java, 4st/Eunseong/세균 증식.java, 4st/Eunseong/순서쌍의 개수.java, 4st/Eunseong/숨어있는 숫자의 덧셈(1).java, 4st/Eunseong/숫자 비교하기.java, 4st/Eunseong/아이스 아메리카노.java, 4st/Eunseong/암호 해독.java, 4st/Eunseong/약수 구하기.java, 4st/Eunseong/옷가게 할인 받기.java, 4st/Eunseong/외계행성의 나이.java, 4st/Eunseong/제곱수 판별하기.java, 4st/Eunseong/중복된 숫자 개수.java, 4st/Eunseong/직각삼각형 출력하기.java
| 가위 바위 보 | 프로그래머스 | Level.0 |
| 더 크게 합치기 | 프로그래머스 | Level.0 |
| 두 수의 나눗셈 | 프로그래머스 | Level.0 |
| 머쓱이보다 키 큰 사람 | 프로그래머스 | Level.0 |
| 몫 구하기 | 프로그래머스 | Level.0 |
| 배열 뒤집기 | 프로그래머스 | Level.0 |
| 배열의 평균값 | 프로그래머스 | Level.0 |
| 삼각형의 완성조건 (1) | 프로그래머스 | Level.0 |
| 순서쌍의 갯수 | 프로그래머스 | Level.0 |
| 숨어있는 숫자의 덧셈 (1) | 프로그래머스 | Level.0 |
| 암호 해독 | …
=> [11일차] 공은성 / 가위 바위 보 (외 29개)

3st/Jaehee/두 수의 나눗셈.py
https://school.programmers.co.kr/learn/courses/30/lessons/120806?language=python3
| 두 수의 나눗셈 | 프로그래머스 | Level.0 |
<hr/>
- 두 수의 나눗셈 : 정수 num1과 num2가 매개변수로 주어질 때, num1을 num2로 나눈 값에 1,000을 곱한 후 정수 부분을 return 하도록 solution 함수를 완성해주세요.
=> [200일] 이제희/두 수의 나눗셈

4st/Seohyun/programmer/A+B.java
https://www.acmicpc.net/submit/1000/94292484
| A+B | 백준 | 브론즈 V |
<hr/>
- A+B : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [10일차] 이서현 /A+B

4st/Jisoo/baekjoon/곱셈.java
https://www.acmicpc.net/submit/2588/94250682
| 곱셈 | 백준 | Level.0 |
<hr/>
- 곱셈 : (세 자리 수) × (세 자리 수)는 다음과 같은 과정을 통하여 이루어진다.
(1)과 (2)위치에 들어갈 세 자리 자연수가 주어질 때 (3), (4), (5), (6)위치에 들어갈 값을 구하는 프로그램을 작성하시오.
=> [10일차]  임지수 /곱셈 

4st/Gau/baekjoon/시험성적.java
https://www.acmicpc.net/submit/9498/94275559
| 시험성적 | 백준 | 브론즈5 |
| 시험성적 | 백준 / 프로그래머스 | 브론즈 V / Level.1 |
<hr/>
- 제목 : 시험 점수를 입력받아 90 ~ 100점은 A, 80 ~ 89점은 B, 70 ~ 79점은 C, 60 ~ 69점은 D, 나머지 점수는 F를 출력하는 프로그램을 작성하시오.
=> [BOJ] 11일차/ 시험성적 / 브론즈 5

4st/Hani/baekjoon/고양이.java, 4st/Hani/baekjoon/두 수 비교하기.java
https://www.acmicpc.net/problem/10171
| 고양이 | 백준 | 브론즈5 |
<hr/>
- 고양 : 아래 예제와 같이 고양이를 출력하시오.
=> [11일차] 최한이 / 고양이

3st/Jaeyoung/최댓값 만들기 (2).py
| 최댓값 만들기 (2) | 프로그래머스 | Level.0 |
<hr/>
- 최댓값 만들기 (2) : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소 중 두 개를 곱해 만들 수 있는 최댓값을 return하도록 solution 함수를 완성해주세요.
=> [200일차] 박재영 / 최댓값 만들기 (2)

3st/Juram/programmer/첫 번째로 나오는 음수.js
=> [11일차] 김주람 / 첫 번째로 나오는 음수

3st/Juram/programmer/n 번째 원소부터.js
| n 번째 원소부터 | 프로그래머스 | Level.1 |
<hr/>
=> [12일차] 김주람 / n 번째 원소부터

4st/Eunseong/369게임.java
https://school.programmers.co.kr/learn/courses/30/lessons/120891
| 369게임 | 프로그래머스 | Level.0 |
<hr/>
- 369게임 : 머쓱이는 친구들과 369게임을 하고 있습니다. 369게임은 1부터 숫자를 하나씩 대며 3, 6, 9가 들어가는 숫자는 숫자 대신 3, 6, 9의 개수만큼 박수를 치는 게임입니다. 머쓱이가 말해야하는 숫자 order가 매개변수로 주어질 때, 머쓱이가 쳐야할 박수 횟수를 return 하도록 solution 함수를 완성해보세요.
=> [12일차] 공은성 / 369게임

4st/Hani/baekjoon/개.java
https://www.acmicpc.net/problem/10172
| 개 | 백준 | 브론즈5 |
<hr/>
- 개 : 아래 예제와 같이 개를 출력하시오.
=> [12일차] 최한이 / 개

4st/Jisoo/baekjoon/1998년생인 내가 태국, 4st/Jisoo/baekjoon/A+B.java, 4st/Jisoo/baekjoon/A-B.java, 4st/Jisoo/baekjoon/A/B.java, 4st/Jisoo/baekjoon/A/사칙연산.java, 4st/Jisoo/baekjoon/A×B.java, 4st/Jisoo/baekjoon/나머지.java, 4st/Jisoo/baekjoon/물음표물음표느낌표.java
https://www.acmicpc.net/problem/11382
| 꼬마 정민 | 백준 | Level.1 |
<hr/>
- 꼬마 정민 : 꼬마 정민이는 이제 A + B 정도는 쉽게 계산할 수 있다. 이제 A + B + C를 계산할 차례이다!
=> [11일차] 임지수 / 꼬마 정민 

3st/Jaehee/숫자 비교하기.py
https://school.programmers.co.kr/learn/courses/30/lessons/120807?language=python3
<hr/>
=> [201일] 이제희/숫자 비교하기

프로그래머스/0/120904. 숫자 찾기/README.md, 프로그래머스/0/120904. 숫자 찾기/숫자 찾기.py
=> [201일차] 조현서 / 숫자 찾기

3st/Jiyu/baekjoon/합.java
https://www.acmicpc.net/problem/8393
| 합 | 백준 | 브론즈 V |
<hr/>
- 합 : n이 주어졌을 때, 1부터 n까지 합을 구하는 프로그램을 작성하시오.
=> [12일차] 임지유 / 합

4st/Seohyun/programmer/A-B.java, 4st/Seohyun/programmer/A×B.java, 4st/Seohyun/programmer/Hello World.java
| A-B | 백준 | 브론즈 V |
<hr/>
- A-B : 두 정수 A와 B를 입력받은 다음, A-B를 출력하는 프로그램을 작성하시오.
=> [12일차] 이서현 / A-B

3st/Juram/programmer/ad 제거하기.js
| ad 제거하기 | 프로그래머스 | Level.0 |
<hr/>
- ad 제거하기 : 문자열 배열 strArr가 주어집니다. 배열 내의 문자열 중 "ad"라는 부분 문자열을 포함하고 있는 모든 문자열을 제거하고 남은 문자열을 순서를 유지하여 배열로 return 하는 solution 함수를 완성해 주세요.
=> [13일차] 김주람 / ad 제거하기

3st/Jaehee/분수의 덧셈.py
https://school.programmers.co.kr/learn/courses/30/lessons/120808?language=python3
| 분수의 덧셈 | 프로그래머스 | Level.1 |
<hr/>
- 분수의 덧셈 : 첫 번째 분수의 분자와 분모를 뜻하는 numer1, denom1, 두 번째 분수의 분자와 분모를 뜻하는 numer2, denom2가 매개변수로 주어집니다. 두 분수를 더한 값을 기약 분수로 나타냈을 때 분자와 분모를 순서대로 담은 배열을 return 하도록 solution 함수를 완성해보세요.
=> [202일] 이제희/분수의 덧셈

4st/Seohyun/programmer/사칙연산.java
| 사칙연산 | 백준 | 브론즈 V |
<hr/>
- 사칙연산 : 두 자연수 A와 B가 주어진다. 이때, A+B, A-B, A*B, A/B(몫), A%B(나머지)를 출력하는 프로그램을 작성하시오.
=> [13일차] 이서현 / 사칙연산

3st/Jiyu/baekjoon/구구단.py
https://www.acmicpc.net/problem/2739
| 구구단 | 백준 | 브론즈 V |
<hr/>
=> [13일차] 임지유 / 구구단

3st/Juram/programmer/수열과 구간 쿼리 1.js
<hr/>
- 수열과 구간 쿼리 1 : 정수 배열 arr와 2차원 정수 배열 queries이 주어집니다. queries의 원소는 각각 하나의 query를 나타내며, [s, e] 꼴입니다.
=> [14일차] 김주람 / 수열과 구간 쿼리 1

4st/Hani/baekjoon/시험 성적.java
https://www.acmicpc.net/problem/9498
| 시험 성적 | 백준 | 브론즈5 |
<hr/>
- 시험 성적 : 시험 점수를 입력받아 90 ~ 100점은 A, 80 ~ 89점은 B, 70 ~ 79점은 C, 60 ~ 69점은 D, 나머지 점수는 F를 출력하는 프로그램을 작성하시오.
=> [14일차] 최한이 시험 성적 / 브론즈5

3st/Jaehee/문자 출력.py
https://school.programmers.co.kr/learn/courses/30/lessons/340207?language=python3
| 문자 출력 | 프로그래머스 | Level.0 |
<hr/>
- 문자 출력 : 주어진 코드는 변수에 데이터를 저장하고 출력하는 코드입니다. 아래와 같이 출력되도록 빈칸을 채워 코드를 완성해 주세요.
=> [203일] 이제희/문자 출력

4st/Jisoo/baekjoon/개.java, 4st/Jisoo/baekjoon/고양이.java, 4st/Jisoo/baekjoon/꼬마정민.java
https://www.acmicpc.net/problem/10172
| 개 | 백준 | Level.0 |
<hr/>
- 개 : 아래 예제와 같이 개를 출력하시오.
=> [13일차] 임지수 / 개 

4st/Eunseong/n의 배수.java, 4st/Eunseong/합성수 찾기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120846
| 합성수 찾기 | 프로그래머스 | Level.0 |
<hr/>
- 합성수 찾기 : 약수의 개수가 세 개 이상인 수를 합성수라고 합니다. 자연수 n이 매개변수로 주어질 때 n이하의 합성수의 개수를 return하도록 solution 함수를 완성해주세요.
=> [14일차] 공은성 / 합성수 찾기

4st/Hani/baekjoon/윤년.java
https://www.acmicpc.net/problem/2753
| 윤년 | 백준 | 브론즈5 |
<hr/>
- 윤 : 연도가 주어졌을 때, 윤년이면 1, 아니면 0을 출력하는 프로그램을 작성하시오.
윤년은 연도가 4의 배수이면서, 100의 배수가 아닐 때 또는 400의 배수일 때이다.
예를 들어, 2012년은 4의 배수이면서 100의 배수가 아니라서 윤년이다. 1900년은 100의 배수이고 400의 배수는 아니기 때문에 윤년이 아니다. 하지만, 2000년은 400의 배수이기 때문에 윤년이다.
=> [15일차] 최한이 / 윤년

3st/Jiyu/baekjoon/구구단.java
https://www.acmicpc.net/problem/2739
| 구구단 | 백준  | 브론즈 V |
<hr/>
=> [14일차] 임지유 / 구구단

3st/Juram/programmer/A 강조하기.java, 3st/Juram/programmer/[PCCE 가출문제] 4번 병과분류.java
=> [15일차] 김주람 / A 강조하기 외 1개

4st/Eunseong/flag에 따라 다른 값 반환하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181933
<hr/>
=> [15일차] 공은성 / flag에 따라 다른 값 반환하기

4st/Hani/baekjoon/사분면 고르기.java
https://www.acmicpc.net/problem/14681
| 사분면 고르기 | 백준 | 브론즈5 |
<hr/>
- 사분면 고르기 : 흔한 수학 문제 중 하나는 주어진 점이 어느 사분면에 속하는지 알아내는 것이다. 사분면은 아래 그림처럼 1부터 4까지 번호를 갖는다. "Quadrant n"은 "제n사분면"이라는 뜻이다.
예를 들어, 좌표가 (12, 5)인 점 A는 x좌표와 y좌표가 모두 양수이므로 제1사분면에 속한다. 점 B는 x좌표가 음수이고 y좌표가 양수이므로 제2사분면에 속한다.
점의 좌표를 입력받아 그 점이 어느 사분면에 속하는지 알아내는 프로그램을 작성하시오. 단, x좌표와 y좌표는 모두 양수나 음수라고 가정한다.
=> [16일차] 최한이 / 사분면 고르기

3st/Jiyu/baekjoon/별 찍기 - 1.java
https://www.acmicpc.net/problem/2438
| 별 찍기 - 1 | 백준 | 브론즈 V |
<hr/>
- 별 찍기 - 1 : 첫째 줄에는 별 1개, 둘째 줄에는 별 2개, N번째 줄에는 별 N개를 찍는 문제
=> [15일차] 임지유 /  별 찍기 - 1

4st/Eunseong/공배수.java
https://school.programmers.co.kr/learn/courses/30/lessons/181936
| 공배수 | 프로그래머스 | Level.0 |
<hr/>
=> [16일차] 공은성 / 공배수

3st/Hajeong/programmer/두 수의 합 구하기.c, 프로그래머스/0/120802. 두 수의 합 구하기/README.md, 프로그래머스/0/120802. 두 수의 합 구하기/두 수의 합 구하기.c
| 두 수의 합 구하기 | 프로그래머스 | Level.0 |
<hr/>
- 두 수의 합 구하기 : 정수 num1과 num2가 주어질 때, num1과 num2의 합을 return하도록 soltuion 함수를 완성해주세요.
=> [15일차] 임하정 / 두 수의 합 구하기

프로그래머스/0/181866. 문자열 잘라서 정렬하기/README.md, 프로그래머스/0/181866. 문자열 잘라서 정렬하기/문자열 잘라서 정렬하기.py
| 문자열 잘라서 정렬하기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 잘라서 정렬하기 : 문자열 myString이 주어집니다. "x"를 기준으로 해당 문자열을 잘라내 배열을 만든 후 사전순으로 정렬한 배열을 return 하는 solution 함수를 완성해 주세요.
단, 빈 문자열은 반환할 배열에 넣지 않습니다.
=> [205일차] 조현서 / 문자열 잘라서 정렬하기

4st/Hani/baekjoon/알람 시계.java
https://www.acmicpc.net/problem/2884
| 알람 시계 | 백준 | 브론즈5 |
<hr/>
- 알람 시계 : 상근이는 매일 아침 알람을 듣고 일어난다. 알람을 듣고 바로 일어나면 다행이겠지만, 항상 조금만 더 자려는 마음 때문에 매일 학교를 지각하고 있다.
상근이는 모든 방법을 동원해보았지만, 조금만 더 자려는 마음은 그 어떤 것도 없앨 수가 없었다.
이런 상근이를 불쌍하게 보던 창영이는 자신이 사용하는 방법을 추천해 주었다.
바로 "45분 일찍 알람 설정하기"이다.
이 방법은 단순하다. 원래 설정되어 있는 알람을 45분 앞서는 시간으로 바꾸는 것이다. 어차피 알람 소리를 들으면, 알람을 끄고 조금 더 잘 것이기 때문이다. 이 방법을 사용하면, 매일 아침 더 잤다는 기분을 느낄 수 있고, 학교도 지각하지 않게 된다.
현재 상근이가 설정한 알람 시각이 주어졌을 때, 창영이의 방법을 사용한다면, 이를 언제로 고쳐야 하는지 구하는 프로그램을 작성하시오.
=> [17일차] 최한이 / 알람 시계

3st/Juram/programmer/배열 회전시키기.js
| 배열 회전시키기 | 프로그래머스 | Level.0 |
<hr/>
- 배열 회전시키기 : 정수가 담긴 배열 numbers와 문자열 direction가 매개변수로 주어집니다. 배열 numbers의 원소를 direction방향으로 한 칸씩 회전시킨 배열을 return하도록 solution 함수를 완성해주세요.
=> [16일차] 김주람 / 배열 회전시키기

3st/Hajeong/programmer/나머지 구하기.c, 3st/Hajeong/programmer/두 수의 차 구하기.c, 프로그래머스/0/120803. 두 수의 차 구하기/README.md, 프로그래머스/0/120803. 두 수의 차 구하기/두 수의 차 구하기.c, 프로그래머스/0/120810. 나머지 구하기/README.md, 프로그래머스/0/120810. 나머지 구하기/나머지 구하기.c
=> [16일차] 임하정 / 두 수의 차 구하기

4st/Jisoo/baekjoon/두 수 비교하기.java, 4st/Jisoo/baekjoon/시험 성적.java
https://school.programmers.co.kr/learn/courses/30/lessons/120810
<hr/>
=> [16일차] 임지수 / 나머지 구하기 

4st/Eunseong/n의 배수 고르기.java, 4st/Eunseong/카운트 다운.java
https://school.programmers.co.kr/learn/courses/30/lessons/120905
| n의 배수 고르기 | 프로그래머스 | Level.0 |
<hr/>
=> [17일차] 공은성 / n의 배수 고르기

3st/Juram/programmer/배열의 유사도.java
=> [18일차] 김주람 / 배열의 유사도

프로그래머스/0/181839. 주사위 게임 1/README.md, 프로그래머스/0/181839. 주사위 게임 1/주사위 게임 1.java
| 주사위게임 | 프로그래머스 | Level.0 |
<hr/>
- 주사위게임 : 1부터 6까지 숫자가 적힌 주사위가 두 개 있습니다. 두 주사위를 굴렸을 때 나온 숫자를 각각 a, b라고 했을 때 얻는 점수는 다음과 같습니다.
두 정수 a와 b가 매개변수로 주어질 때, 얻는 점수를 return 하는 solution 함수를 작성해 주세요.
=> [207일차] 조현서 / 주사위게임

4st/Eunseong/올바른 괄호.java, 4st/Eunseong/최댓값과 최솟값.java
https://school.programmers.co.kr/learn/courses/30/lessons/12939
https://school.programmers.co.kr/learn/courses/30/lessons/12909
| 최댓값과 최솟값 | 프로그래머스 | Level.2 |
| 올바른 괄호 | 프로그래머스 | Level.2 |
<hr/>
- 최댓값과 최솟값 : 문자열 s에는 공백으로 구분된 숫자들이 저장되어 있습니다. str에 나타나는 숫자 중 최소값과 최대값을 찾아 이를 "(최소값) (최대값)"형태의 문자열을 반환하는 함수, solution을 완성하세요.
- 올바른 괄호 : 괄호가 바르게 짝지어졌다는 것은 '(' 문자로 열렸으면 반드시 짝지어서 ')' 문자로 닫혀야 한다는 뜻입니다. 예를 들어
"()()" 또는 "(())()" 는 올바른 괄호입니다.
")()(" 또는 "(()(" 는 올바르지 않은 괄호입니다.
'(' 또는 ')' 로만 이루어진 문자열 s가 주어졌을 때, 문자열 s가 올바른 괄호이면 true를 return 하고, 올바르지 않은 괄호이면 false를 return 하는 solution 함수를 완성해 주세요.
=> [18일차] 공은성 / 최댓값과 최솟값 (외 1개)

4st/Seohyun/baekjoon/고양이.java, 4st/Seohyun/programmer/몫 구하기 .java, 4st/Seohyun/programmer/직각삼각형 출력하기.java, 4st/Seohyun/programmer/직사각형 별찍기.java, 4st/Seohyun/programmer/피자 나눠 먹기(1).java
| 고양이 | 백준 | 브론즈 V |
<hr/>
- 고양이 : 아래 예제와 같이 고양이를 출력하시오.
=> [17일차] 이서현 / 고양이

3st/Jiyu/baekjoon/단어 길이 재기.py
https://www.acmicpc.net/problem/2743
| 단어 길이 재기 | 백준 | 브론즈 V |
<hr/>
- 단어 길이 재기 : 알파벳으로만 이루어진 단어를 입력받아, 그 길이를 출력하는 프로그램을 작성하시오.
=> [17일차] 임지유 / 단어 길이 재기

3st/Jaeyoung/몫 구하기.cpp, 3st/Jaeyoung/수열과 구간 쿼리 1.cpp, 3st/Jaeyoung/암호 해독.py
<hr/>
- 수열과 구간 쿼리 1 : 정수 배열 arr와 2차원 정수 배열 queries이 주어집니다. queries의 원소는 각각 하나의 query를 나타내며, [s, e] 꼴입니다.
=> [207일차] 박재영 / 수열과 구간 쿼리 1

4st/Jisoo/programmer/나머지 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120803
<hr/>
=> [17일차] 임지수 / 두 수의 차 구하기

3st/Jaehee/각도 합치기.py
https://school.programmers.co.kr/learn/courses/30/lessons/340206?language=python3
| 각도 합치기 | 프로그래머스 | Level.0 |
<hr/>
- 각도 합치기 : 일반적으로 두 선분이 이루는 각도는 한 바퀴를 360도로 하여 표현합니다. 따라서 각도에 360의 배수를 더하거나 빼더라도 같은 각을 의미합니다. 예를 들면, 30도와 390도는 같은 각도입니다.
주어진 코드는 각도를 나타내는 두 정수 angle1과 angle2가 주어질 때, 이 두 각의 합을 0도 이상 360도 미만으로 출력하는 코드입니다. 코드가 올바르게 작동하도록 한 줄을 수정해 주세요.
=> [207일] 이제희/각도 합치기

4st/Gau/baekjoon/별찍기-1.java
https://www.acmicpc.net/submit/2438/94581758
| 별찍기-1 | BOJ | 레벨 |
| 별찍기-1 | 백준 / 프로그래머스 | 브론즈 V / Level.1 |
<hr/>
- 별찍기-1: 첫째 줄에는 별 1개, 둘째 줄에는 별 2개, N번째 줄에는 별 N개를 찍는 문제
=> [BOJ] 12일차/ 별찍기-1 / 브론즈 5

4st/Gau/baekjoon/놀람.java
https://www.acmicpc.net/submit/10926/94621699
| ??! | BOJ | 레벨 |
| ??! | 백준 / 프로그래머스 | 브론즈 V / Level.1 |
<hr/>
- ??! : 준하는 사이트에 회원가입을 하다가 joonas라는 아이디가 이미 존재하는 것을 보고 놀랐다. 준하는 놀람을 ??!로 표현한다. 준하가 가입하려고 하는 사이트에 이미 존재하는 아이디가 주어졌을 때, 놀람을 표현하는 프로그램을 작성하시오.
=> [BOJ] 13일차/ ??! / 브론즈 5

3st/Jiyu/baekjoon/문자와 문자열.py
https://www.acmicpc.net/problem/27866
| 문자와 문자열 | 백준 | 브론즈 V |
<hr/>
- 문자와 문자열 : 단어 S 와 정수 I 가 주어졌을 때, S 의 i 번째 글자를 출력하는 프로그램을 작성하시오.
=> [18일차] 임지유 / 문자와 문자열

프로그래머스/0/181942. 문자열 섞기/README.md, 프로그래머스/0/181942. 문자열 섞기/문자열 섞기.js
| 문자열 섞기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 섞기 : 길이가 같은 두 문자열 str1과 str2가 주어집니다.
두 문자열의 각 문자가 앞에서부터 서로 번갈아가면서 한 번씩 등장하는 문자열을 만들어 return 하는 solution 함수를 완성해 주세요.
=> [208일차] 조현서 / 문자열 섞기

4st/Eunseong/콜라츠 수열 만들기.java, 4st/Eunseong/콜라츠 추측.java, 4st/Eunseong/피보나치 수.java
| 콜라츠 추측 | 프로그래머스 | Level.1 |
| 피보나치 수 | 프로그래머스 | Level.2 |
<hr/>
- 콜라츠 추측 : 1937년 Collatz란 사람에 의해 제기된 이 추측은, 주어진 수가 1이 될 때까지 다음 작업을 반복하면, 모든 수를 1로 만들 수 있다는 추측입니다. 작업은 다음과 같습니다.
1-1. 입력된 수가 짝수라면 2로 나눕니다. 
1-2. 입력된 수가 홀수라면 3을 곱하고 1을 더합니다. 
2. 결과로 나온 수에 같은 작업을 1이 될 때까지 반복합니다. 
예를 들어, 주어진 수가 6이라면 6 → 3 → 10 → 5 → 16 → 8 → 4 → 2 → 1 이 되어 총 8번 만에 1이 됩니다. 위 작업을 몇 번이나 반복해야 하는지 반환하는 함수, solution을 …
=> [19일차] 공은성 / 콜라츠 수열 만들기 (외 2개)

3st/Hajeong/programmer/숫자 비교하기.c, 프로그래머스/0/120807. 숫자 비교하기/README.md, 프로그래머스/0/120807. 숫자 비교하기/숫자 비교하기.c
=> [17일차] 임하정 / 숫자 비교하기

4st/Jisoo/programmer/두 수의 차 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120807
<hr/>
=> [18일차] 임지수 / 숫자 비교하기

3st/Juram/programmer/문자열안에 문자열.js
=> [19일차] 김주람 / 문자열안에 문자열

3st/Juram/programmer/짝수 홀수 개수.js
=> [20일차] 김주람 / 짝수 홀수 개수

3st/Jaehee/나머지 구하기.py
https://school.programmers.co.kr/learn/courses/30/lessons/120810?language=python3
<hr/>
=> [209일] 이제희/나머지 구하기

3st/Hajeong/programmer/두 수의 곱 구하기.c, 프로그래머스/0/120804. 두 수의 곱 구하기/README.md, 프로그래머스/0/120804. 두 수의 곱 구하기/두 수의 곱 구하기.c
=> [18일차] 임하정 / 두 수의 곱 구하기

4st/Seohyun/programmer/덧셈식 출력하기.java
| 덧셈식 출력하기 | 프로그래머스 | Level.1 |
<hr/>
=> [20일차] 이서현 / 덧셈식 출력하기

4st/Eunseong/n 번째 원소까지.java, 4st/Eunseong/주사위 게임 3.java, 4st/Eunseong/컨트롤 제트.java
https://school.programmers.co.kr/learn/courses/30/lessons/181916
https://school.programmers.co.kr/learn/courses/30/lessons/120853
| 주사위 게임 3 | 프로그래머스 | Level.0 |
| 컨트롤 제트 | 프로그래머스 | Level.0 |
<hr/>
- 주사위 게임 3 : 1부터 6까지 숫자가 적힌 주사위가 네 개 있습니다. 네 주사위를 굴렸을 때 나온 숫자에 따라 다음과 같은 점수를 얻습니다.
네 주사위에서 나온 숫자가 모두 p로 같다면 1111 × p점을 얻습니다.
세 주사위에서 나온 숫자가 p로 같고 나머지 다른 주사위에서 나온 숫자가 q(p ≠ q)라면 (10 × p + q)2 점을 얻습니다.
주사위가 두 개씩 같은 값이 나오고, 나온 숫자를 각각 p, q(p ≠ q)라고 한다면 (p + q) × |p - q|점을 얻습니다.
어느 두 주사위에서 나온 숫자가 p로 같고 나머지 두 주사위에서 나온 숫자가 각각 p와 다른 q, r(q ≠ r)이라면 q × r점을 얻습니다.
네 주사위에 적힌 숫자가 모두 다르다면 나온 숫자 중 가장 작은 숫자 만큼의 점수를 얻습니다.
네 주사위를 굴렸을 때 나온 숫자가 정수 매개변수 a, b, c, d로 주어질 때, 얻는 점수를 return 하는 solution 함수를 작성해 주세요.
- 컨트롤 제트 : 숫자와 "Z"가 공백으로 구분되어 담긴 문자열이 주어집니다. 문자열에 있는 숫자를 …
=> [20일차] 공은성 / 주사위 게임 3 (외 1개)

4st/Eunseong/ad 제거하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181870
| ad 제거하기 | 프로그래머스 | Level.1 |
<hr/>
- ad 제거하기 : 문자열 배열 strArr가 주어집니다. 배열 내의 문자열 중 "ad"라는 부분 문자열을 포함하고 있는 모든 문자열을 제거하고 남은 문자열을 순서를 유지하여 배열로 return 하는 solution 함수를 완성해 주세요.
=> [21일차] 공은성 / ad 제거하기

4st/Hani/baekjoon/오븐 시계.java
https://www.acmicpc.net/problem/2525
| 오븐 시계 | 백준 | 브론즈5 |
<hr/>
- 오븐 시 : KOI 전자에서는 건강에 좋고 맛있는 훈제오리구이 요리를 간편하게 만드는 인공지능 오븐을 개발하려고 한다. 인공지능 오븐을 사용하는 방법은 적당한 양의 오리 훈제 재료를 인공지능 오븐에 넣으면 된다. 그러면 인공지능 오븐은 오븐구이가 끝나는 시간을 분 단위로 자동적으로 계산한다.
또한, KOI 전자의 인공지능 오븐 앞면에는 사용자에게 훈제오리구이 요리가 끝나는 시각을 알려 주는 디지털 시계가 있다.
훈제오리구이를 시작하는 시각과 오븐구이를 하는 데 필요한 시간이 분단위로 주어졌을 때, 오븐구이가 끝나는 시각을 계산하는 프로그램을 작성하시오.
=> [18일차] 최한이 / 오븐 시계

4st/Seohyun/programmer/짝수의 합.c
| 짝수의 합 | 프로그래머스 | Level.1 |
<hr/>
- 짝수의  : 정수 n이 주어질 때, n이하의 짝수를 모두 더한 값을 return 하도록 solution 함수를 작성해주세요.
=> [22일차] 이서현 / 짝수의 합

3st/Jaehee/출력.txt
https://school.programmers.co.kr/learn/courses/30/lessons/250133
| 출력 | 프로그래머스 | Level.0 |
<hr/>
- 출력 : 주어진 초기 코드는 변수에 데이터를 저장하고 출력하는 코드입니다. 아래와 같이 출력되도록 빈칸을 채워 코드를 완성해 주세요.
=> [211일]  이제희/출력 

4st/Hani/baekjoon/주사위 세개.java
https://www.acmicpc.net/problem/2480
| 주사위 세개 | 백준 | 브론즈5 |
<hr/>
- 주사위 세개 : 1에서부터 6까지의 눈을 가진 3개의 주사위를 던져서 다음과 같은 규칙에 따라 상금을 받는 게임이 있다.
같은 눈이 3개가 나오면 10,000원+(같은 눈)×1,000원의 상금을 받게 된다.
같은 눈이 2개만 나오는 경우에는 1,000원+(같은 눈)×100원의 상금을 받게 된다.
모두 다른 눈이 나오는 경우에는 (그 중 가장 큰 눈)×100원의 상금을 받게 된다.
예를 들어, 3개의 눈 3, 3, 6이 주어지면 상금은 1,000+3×100으로 계산되어 1,300원을 받게 된다. 또 3개의 눈이 2, 2, 2로 주어지면 10,000+2×1,000 으로 계산되어 12,000원을 받게 된다. 3개의 눈이 6, 2, 5로 주어지면 그중 가장 큰 값이 6이므로 6×100으로 계산되어 600원을 상금으로 받게 된다.
3개 주사위의 나온 눈이 주어질 때, 상금을 계산하는 프로그램을 작성 하시오.
=> [19일차] 최한이 / 주사위 세개

3st/Juram/programmer/점의 위치 구하기.js
<hr/>
x 좌표 (x, y)를 차례대로 담은 정수 배열 dot이 매개변수로 주어집니다. 좌표 dot이 사분면 중 어디에 속하는지 1, 2, 3, 4 중 하나를 return 하도록 solution 함수를 완성해주세요.
=> [23일차] 김주람 / 점의 위치 구하기

4st/Seohyun/programmer/나이 출력.java, 4st/Seohyun/programmer/두 수의 곱 구하기.c
=> [23일차] 이서현 / 두 수의 곱 구하기

4st/Eunseong/A 강조하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181874
<hr/>
=> [23일차] 공은성 / A 강조하기

3st/Jaehee/피타고라스의 정리.py
https://school.programmers.co.kr/learn/courses/30/lessons/250132?language=python3
| 피타고라스의 정리 | 프로그래머스 | Level.0 |
<hr/>
- 피타고라스의 정리 : 직각삼각형의 한 변의 길이를 나타내는 정수 a와 빗변의 길이를 나타내는 정수 c가 주어질 때, 다른 한 변의 길이의 제곱, b_square 을 출력하도록 한 줄을 수정해 코드를 완성해 주세요.
=> [213일]  이제희/피타고라스의 정리

3st/Jaeyoung/크레인 인형뽑기 게임.js
| 크레인 인형뽑기 게임 | 프로그래머스 | Level.1 |
<hr/>
- 크레인 인형뽑기 게임 : 게임개발자인 "죠르디"는 크레인 인형뽑기 기계를 모바일 게임으로 만들려고 합니다.
"죠르디"는 게임의 재미를 높이기 위해 화면 구성과 규칙을 다음과 같이 게임 로직에 반영하려고 합니다.
게임 화면은 "1 x 1" 크기의 칸들로 이루어진 "N x N" 크기의 정사각 격자이며 위쪽에는 크레인이 있고 오른쪽에는 바구니가 있습니다. (위 그림은 "5 x 5" 크기의 예시입니다). 각 격자 칸에는 다양한 인형이 들어 있으며 인형이 없는 칸은 빈칸입니다. 모든 인형은 "1 x 1" 크기의 격자 한 칸을 차지하며 격자의 가장 아래 칸부터 차곡차곡 쌓여 있습니다. 게임 사용자는 크레인을 좌우로 움직여서 멈춘 위치에서 가장 위에 있는 인형을 집어 올릴 수 있습니다. 집어 올린 인형은 바구니에 쌓이게 되는 데, 이때 바구니의 가장 아래 칸부터 인형이 순서대로 쌓이게 됩니다. 다음 그림은 [1번, 5번, 3번] 위치에서 순서대로 인형을 집어 올려 바구니에 담은 모습입니다.
만약 같은 모양의 인형 두 개가 바구니에 연속해서 쌓이게 되면 두 인형은 터뜨려지면서 바구니에서 사라지게 됩니다. 위 상태에서 이어서 [5번] 위치에서 인형을 집어 바구니에 쌓으면 같은 모양 인형 두 개가 없어집니다.
크레인 작동 시 인형이 집어지지 않는 경우는 없으나 만약 인형이 없는 곳에서 크레인을 작동시키는 경우에는 아무런 일도 일어나지 않습니다. 또한 바구니는 모든 …
=> [213일차] 박재영 / 크레인 인형뽑기 게임

4st/Eunseong/2차원으로 만들기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120842
| 2차원으로 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 2차원으로 만들기 : 정수 배열 num_list와 정수 n이 매개변수로 주어집니다. num_list를 다음 설명과 같이 2차원 배열로 바꿔 return하도록 solution 함수를 완성해주세요.
num_list가 [1, 2, 3, 4, 5, 6, 7, 8] 로 길이가 8이고 n이 2이므로 num_list를 2 * 4 배열로 다음과 같이 변경합니다. 2차원으로 바꿀 때에는 num_list의 원소들을 앞에서부터 n개씩 나눠 2차원 배열로 변경합니다.
=> [24일차] 공은성 / 2차원으로 만들기

3st/Juram/programmer/중복된 숫자 개수.js
=> [25일차] 김주람 / 중복된 숫자 개수

3st/Jaehee/나이 계산.py
https://school.programmers.co.kr/learn/courses/30/lessons/250131?language=python3
| 나이 계산 | 프로그래머스 | Level.0 |
<hr/>
- 나이 계산 : 나이를 세는 방법은 여러 가지가 있습니다. 그중 한국식 나이는 태어난 순간 1살이 되며 해가 바뀔 때마다 1살씩 더 먹게 됩니다. 연 나이는 태어난 순간 0살이며 해가 바뀔 때마다 1살씩 더 먹게 됩니다. 각각 나이의 계산법은 다음과 같습니다.
한국식 나이 : 현재 연도 - 출생 연도 + 1
연 나이 : 현재 연도 - 출생 연도
출생 연도를 나타내는 정수 year와 구하려는 나이의 종류를 나타내는 문자열 age_type이 주어질 때 2030년에 몇 살인지 출력하도록 빈칸을 채워 코드를 완성해 주세요. age_type이 "Korea"라면 한국식 나이를, "Year"라면 연 나이를 출력합니다.
=> [214일] 이제희/나이 계산

4st/Gau/baekjoon/1998년생인 내가 태국에서는 2541년생.java
https://www.acmicpc.net/submit/10951/94846084
| A+B-4 | BOJ | 레벨 |
| A+B-4 | 백준 / 프로그래머스 | 브론즈 V / Level.1 |
<hr/>
- A+B-4 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
입력
입력은 여러 개의 테스트 케이스로 이루어져 있다.
각 테스트 케이스는 한 줄로 이루어져 있으며, 각 줄에 A와 B가 주어진다. (0 < A, B < 10)
출력
각 테스트 케이스마다 A+B를 출력한다.
예제 입력 1 
1 1
2 3
3 4
9 8
5 2
예제 출력 1 
2
5
7
17
7
=> [BOJ] 15일차/ A+B-4 / 브론즈 5

4st/Eunseong/7의 개수.java, 4st/Eunseong/문자열 정렬하기 (2).java, 4st/Eunseong/배열 회전시키기.java, 4st/Eunseong/종이 자르기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120911
https://school.programmers.co.kr/learn/courses/30/lessons/120844
https://school.programmers.co.kr/learn/courses/30/lessons/120912
https://school.programmers.co.kr/learn/courses/30/lessons/120922
| 배열 회전시키기 | 프로그래머스 | Level.0 |
| 7의 개수 | 프로그래머스 | Level.0 |
| 종이 자르기 | 프로그래머스 | Level.0 |
<hr/>
- 배열 회전시키기 : 정수가 담긴 배열 numbers와 문자열 direction가 매개변수로 주어집니다. 배열 numbers의 원소를 direction방향으로 한 칸씩 회전시킨 배열을 return하도록 solution 함수를 완성해주세요.
- 7의 개수 : 머쓱이는 행운의 숫자 7을 가장 좋아합니다. 정수 배열 array가 매개변수로 주어질 때, 7이 총 몇 개 있는지 return 하도록 …
=> [25일차] 공은성 / 문자열 정렬하기 (2) (외 3개)

3st/Jaeyoung/조건에 맞게 수열 변환하기 1.cpp
| 조건에 맞게 수열 변환하기 1 | 프로그래머스 | Level.0 |
<hr/>
- 조건에 맞게 수열 변환하기 1 : 정수 배열 arr가 주어집니다. arr의 각 원소에 대해 값이 50보다 크거나 같은 짝수라면 2로 나누고, 50보다 작은 홀수라면 2를 곱합니다. 그 결과인 정수 배열을 return 하는 solution 함수를 완성해 주세요.
=> [214일차] 박재영 / 조건에 맞게 수열 변환하기 1

3st/Juram/programmer/정수 부분.js
| 정수 부분 | 프로그래머스 | Level.0 |
<hr/>
=> [26일차] 김주람 / 정수 부분

4st/Jisoo/programmer/두 수의 나눗셈.java, 4st/Jisoo/programmer/두 수의합 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120804?language=java
<hr/>
- 두 수의 곱 하기 : 정수 num1, num2가 매개변수 주어집니다. num1과 num2를 곱한 값을 return 하도록 solution 함수를 완성해주세요.
=> [24일차] 임지수 / 두 수의 곱 구하기 

3st/Hajeong/programmer/피자 나눠 먹기 (1).c, 프로그래머스/0/120814. 피자 나눠 먹기 （1）/README.md, 프로그래머스/0/120814. 피자 나눠 먹기 （1）/피자 나눠 먹기 （1）.c
| 피자 나눠 먹기 (1) | 1프로그래머스 | Level.0 |
<hr/>q
=> [22일차] 임하정 / 피자 나눠 먹기 (1)q

4st/Eunseong/문자 리스트를 문자열로 변환하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181941
<hr/>
=> [26일차] 공은성 / 문자 리스트를 문자열로 변환하기

3st/Jaeyoung/길이에 따른 연산.cpp, 3st/Jaeyoung/짝수의 합.cpp
| 짝수의 합 | 프로그래머스 | Level.0 |
<hr/>
- 짝수의 합 : 정수 n이 주어질 때, n이하의 짝수를 모두 더한 값을 return 하도록 solution 함수를 작성해주세요.
=> [216일차] 박재영 / 짝수의 합

4st/Jisoo/programmer/각도기.java
<hr/>
-각도기 : 각에서 0도 초과 90도 미만은 예각, 90도는 직각, 90도 초과 180도 미만은 둔각 180도는 평각으로 분류합니다. 각 angle이 매개변수로 주어질 때 예각일 때 1, 직각일 때 2, 둔각일 때 3, 평각일 때 4를 return하도록 solution 함수를 완성해주세요.
예각 : 0 < angle < 90
직각 : angle = 90
둔각 : 90 < angle < 180
평각 : angle = 180
=> [24일차] 임지수 / 각도기

4st/Eunseong/진료 순서 정하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120835
| 진료 순서 정하기 | 프로그래머스 | Level.0 |
<hr/>
- 진료 순서 정하기 : 외과의사 머쓱이는 응급실에 온 환자의 응급도를 기준으로 진료 순서를 정하려고 합니다. 정수 배열 emergency가 매개변수로 주어질 때 응급도가 높은 순서대로 진료 순서를 정한 배열을 return하도록 solution 함수를 완성해주세요.
=> [27일차] 공은성 / 진료 순서 정하기

4st/Seohyun/programmer/두 수의 합 구하기.c
| 두 수의 합 구하기 | 프로그래머스 |  Level.1 |
<hr/>
- 두 수의 합 구하기 : 정수 num1과 num2가 주어질 때, num1과 num2의 합을 return하도록 soltuion 함수를 완성해주세요.
=> [24일차] 이서현 / 두 수의 합 구하기

4st/Hani/baekjoon/별 찍기 - 1.java
https://www.acmicpc.net/problem/2438
| 별 찍기 - 1 | 백준 | 브론즈5 |
<hr/>
- 별 찍기 - 1 : 첫째 줄에는 별 1개, 둘째 줄에는 별 2개, N번째 줄에는 별 N개를 찍는 문제
=> [23일차] 최한이 / 별 찍기 - 1

3st/Hajeong/programmer/n의 배수 고르기.java, 프로그래머스/0/120905. n의 배수 고르기/README.md, 프로그래머스/0/120905. n의 배수 고르기/n의 배수 고르기.java
| n의 배수 고르기 | 프로그래머스 |  Level.0 |
<hr/>
=> [24일차] 임하정 / n의 배수 고르기

3st/Jaehee/문자열 붙여서 출력하기.py
https://school.programmers.co.kr/learn/courses/30/lessons/181946?language=python3
<hr/>
- 문자열 붙여서 출력하기  : 두 개의 문자열 str1, str2가 공백으로 구분되어 입력으로 주어집니다.
=> [217일] 이제희/문자열 붙여서 출력하기 

4st/Seohyun/programmer/나머지 구하기.c
| 나머지 구하기 |  프로그래머스 |  Level.0 |
<hr/>
=> [25일차] 이서현 / 나머지 구하기

4st/Hani/baekjoon/별 찍기 - 2.java
https://www.acmicpc.net/problem/2439
| 별 찍기 - 2 | 백준 | 브론즈5 |
<hr/>
- 별 찍기 - 2 : 첫째 줄에는 별 1개, 둘째 줄에는 별 2개, N번째 줄에는 별 N개를 찍는 문제
=> [24일차] 최한이 / 별 찍기 - 2

4st/Eunseong/대문자와 소문자.java
https://school.programmers.co.kr/learn/courses/30/lessons/120893
<hr/>
=> [29일차] 공은성 / 대문자와 소문자

3st/Jaeyoung/두 수의 곱 구하기.cpp
=> [218일차] 박재영 / 두 수의 곱 구하기

3st/Juram/programmer/모음 제거.js, 3st/Juram/programmer/최댓값 만들기(1).java
| 최댓값 만들기(1) | 프로그래머스 | Level.0 |
<hr/>
=> [30일차] 김주람 / 최댓값 만들기(1) 외 1개

4st/Hani/programmer/문자 출력.java
https://school.programmers.co.kr/learn/courses/30/lessons/340207
| 문자 출력 | 프로그래머스 | Level.0 |
<hr/>
- 문자 출력 : 주어진 코드는 변수에 데이터를 저장하고 출력하는 코드입니다. 아래와 같이 출력되도록 빈칸을 채워 코드를 완성해 주세요.
=> [25일차] 최한이 / 문자 출력

4st/Eunseong/공 던지기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120843
| 공 던지기 | 프로그래머스 | Level.0 |
<hr/>
- 공 던지기 : 머쓱이는 친구들과 동그랗게 서서 공 던지기 게임을 하고 있습니다. 공은 1번부터 던지며 오른쪽으로 한 명을 건너뛰고 그다음 사람에게만 던질 수 있습니다. 친구들의 번호가 들어있는 정수 배열 numbers와 정수 K가 주어질 때, k번째로 공을 던지는 사람의 번호는 무엇인지 return 하도록 solution 함수를 완성해보세요.
=> [30일차] 공은성 / 공 던지기

3st/Juram/programmer/자릿수 더하기.js
=> [31일차] 김주람 / 자릿수 더하기

4st/Seohyun/programmer/각도기.c
=> [26일차] 이서현 / 각도기

3st/Hajeong/programmer/자릿수 더하기.java, 프로그래머스/1/12931. 자릿수 더하기/README.md, 프로그래머스/1/12931. 자릿수 더하기/자릿수 더하기.java
| 자릿수 더하기 | 프로그래머스 | Level.1 |
<hr/>
- 자릿수 더하기 : 자연수 N이 주어지면, N의 각 자릿수의 합을 구해서 return 하는 solution 함수를 만들어 주세요.
예를들어 N = 123이면 1 + 2 + 3 = 6을 return 하면 됩니다.
=> [26일차] 임하정 / 자릿수 더하기

3st/Jaehee/각도기.py
https://school.programmers.co.kr/learn/courses/30/lessons/120829?language=python3#
<hr/>
=> [221일] 이제희/각도기

3st/Jaeyoung/더 크게 합치기.cpp
| 더 크게 합치기 | 프로그래머스 | Level.0 |
<hr/>
- 더 크게 합치기 : 연산 ⊕는 두 정수에 대한 연산으로 두 정수를 붙여서 쓴 값을 반환합니다. 예를 들면 다음과 같습니다.
12 ⊕ 3 = 123
3 ⊕ 12 = 312
양의 정수 a와 b가 주어졌을 때, a ⊕ b와 b ⊕ a 중 더 큰 값을 return 하는 solution 함수를 완성해 주세요.
단, a ⊕ b와 b ⊕ a가 같다면 a ⊕ b를 return 합니다.
=> [221일차] 박재영 / 더 크게 합치기

4st/Hani/programmer/나머지 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120810
<hr/>
=> [26일차] 최한이 / 나머지 구하기

4st/Gau/programmer/a와b 출력하기.java
링크
|  a와b를 출력하기 | 프로그래머스 | Level.1 |
<hr/>
-  a와b를 출력하기 : 정수 a와 b가 주어집니다. 각 수를 입력받아 입출력 예와 같은 형식으로 출력하는 코드를 작성해 보세요.
=> [32일차] 노가우 / a와b를 출력하기

3st/Juram/programmer/머쓱이보다 키 큰 사람.js, 3st/Juram/programmer/삼각형의 완성조건 (1).js
| 머쓱이보다 키 큰 사람 |  프로그래머스 | Level.0 |
<hr/>
- 머쓱이보다 키 큰 사람 : 머쓱이는 학교에서 키 순으로 줄을 설 때 몇 번째로 서야 하는지 궁금해졌습니다. 머쓱이네 반 친구들의 키가 담긴 정수 배열 array와 머쓱이의 키 height가 매개변수로 주어질 때, 머쓱이보다 키 큰 사람 수를 return 하도록 solution 함수를 완성해보세요.
=> [32일차] 김주람 / 머쓱이보다 키 큰 사람 외 1개

4st/Hani/programmer/두 수의 차 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120803
<hr/>
=> [27일차] 최한이 / 두 수의 차 구하기

4st/Eunseong/다항식 더하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120863
| 다항식 더하기 | 프로그래머스 | Level.0 |
<hr/>
- 다항식 더하기 : 한 개 이상의 항의 합으로 이루어진 식을 다항식이라고 합니다. 다항식을 계산할 때는 동류항끼리 계산해 정리합니다. 덧셈으로 이루어진 다항식 polynomial이 매개변수로 주어질 때, 동류항끼리 더한 결괏값을 문자열로 return 하도록 solution 함수를 완성해보세요. 같은 식이라면 가장 짧은 수식을 return 합니다.
=> [33일차] 공은성 / 다항식 더하기

3st/Hajeong/programmer/문자열안에 문자열.java, 프로그래머스/0/120908. 문자열안에 문자열/README.md, 프로그래머스/0/120908. 문자열안에 문자열/문자열안에 문자열.java
=> [27일차] 임하정 / 문자열안에 문자열

3st/Jiyu/baekjoon/아스키 코드.py
https://www.acmicpc.net/problem/11654
| 아스키 코드 | 백준 | 브론즈 V |
<hr/>
- 아스키 코드 : 알파벳 소문자, 대문자, 숫자 0-9중 하나가 주어졌을 때, 주어진 글자의 아스키 코드값을 출력하는 프로그램을 작성하시오.
=> [20일차] 임지유 / 아스키 코드

3st/Jaeyoung/두 수의 차 구하기.cpp
=> [223일차] 박재영 / 두 수의 차 구하기

4st/Hani/programmer/나이 출력.java, 4st/Hani/programmer/숫자 비교하기.java, 4st/Hani/programmer/짝수의 합.java
https://school.programmers.co.kr/learn/courses/30/lessons/120807
| 두 수 비교하기 | 프로그래머스 | Level.0 |
<hr/>
- 두 수 비교하기 : 정수 num1과 num2가 매개변수로 주어집니다. 두 수가 같으면 1 다르면 -1을 retrun하도록 solution 함수를 완성해주세요.
=> [28일차] 최한이 / 두 수 비교하기

4st/Eunseong/문자열 계산하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120902#
| 문자열 계산하기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 계산하기 : my_string은 "3 + 5"처럼 문자열로 된 수식입니다. 문자열 my_string이 매개변수로 주어질 때, 수식을 계산한 값을 return 하는 solution 함수를 완성해주세요.
=> [35일차] 공은성 / 문자열 계산하기

3st/Juram/programmer/순서쌍의 개수.js
=> [35일차] 김주람 / 순서쌍의 개수

4st/Jisoo/programmer/문자출력.java
| [PCCE 기출문제] 1번 / 문자 출력 | 프로그래머스 | Level.0 |
<hr/>
- [PCCE 기출문제] 1번 / 문자 출력 : 주어진 코드는 변수에 데이터를 저장하고 출력하는 코드입니다. 아래와 같이 출력되도록 빈칸을 채워 코드를 완성해 주세요.
=> [29일차] 임지수 / [PCCE 기출문제] 1번 / 문자 출력

4st/Hani/programmer/나이 출력.java
https://school.programmers.co.kr/learn/courses/30/lessons/120820
<hr/>
- 나이 출력 : 머쓱이는 선생님이 몇 년도에 태어났는지 궁금해졌습니다. 2022년 기준 선생님의 나이 age가 주어질 때, 선생님의 출생 연도를 return 하는 solution 함수를 완성해주세요
=> [29일차] 최한이 / 나이 출력

3st/Hajeong/programmer/중복된 숫자 개수.java, 프로그래머스/0/120583. 중복된 숫자 개수/README.md, 프로그래머스/0/120583. 중복된 숫자 개수/중복된 숫자 개수.java
<hr/>
- 문자열안에 문자열 : 정수가 담긴 배열 array와 정수 n이 매개변수로 주어질 때, array에 n이 몇 개 있는 지를 return 하도록 solution 함수를 완성해보세요.
=> [26일차] 임하정 / 문자열안에 문자열

4st/Gau/programmer/문자열 반복해서 출력하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181950
| 문자열 반복해서 출력하기 |  프로그래머스 |  Level.0 |
<hr/>
=> [PGS] 노가우/ 19일차 / 문자열 반복해서 출력하기 / LV.0

3st/Juram/programmer/n의 배수 고르기.js
| n의 배수 고르기 | 프로그래머스 | Level.0 |
<hr/>
=> [36일차] 김주람 / n의 배수 고르기

4st/Eunseong/[PCCE 기출문제] 6번 ／ 물 부족
https://school.programmers.co.kr/learn/courses/30/lessons/340202
| [PCCE 기출문제] 6번 / 물 부족 | 프로그래머스 | Level.0 |
<hr/>
- [PCCE 기출문제] 6번 / 물 부족 : ㅇㅇ시에서는 저수지가 하나 있는데, 도시 내에서 사용하는 모든 물은 이 저수지에 저장된 물을 끌어와 사용합니다. 이상 기후로 인해 극심한 가뭄이 예고된 상황에서, 지난 달의 물 사용량과 이번달부터 일정 기간 동안의 월별 물 사용량의 변화를 예측한 값을 이용해 몇 달 뒤 물이 부족해지는지 예측하려고 합니다.
이번달부터의 월별 물 사용량 변화를 예측한 값은 다음과 같이 리스트에 담겨 주어집니다.
[10, -10, 10, -10, 10, -10, 10, -10, 10, -10]
리스트의 각 원소는 해당 월의 물 사용량이 전 달에 비해 몇 % 만큼 증가 또는 감소하는지를 나타냅니다.
예를 들어, 이번달의 물 사용량 (리스트의 첫 번째 원소)은 지난 달 보다 10% 증가한 값이며, 다음 달(리스트의 두 번째 원소)의 물 사용량은 이번달 사용량에서 10%만큼 감소한 값입니다.
자세한 값은 입출력 예시를 참고해 주세요.
현재 저수지에 저장된 물의 양을 나타내는 정수 storage와 지난 달 물 사용량을 나타내는 정수 usage, 월별 물 사용량이 전 달 대비 어떻게 변하는지 저장된 정수 리스트 change가 주어질 때 몇 달 뒤 물이 부족해지는지 return 하도록 solution 함수를 …
=> [36일차] 공은성 / [PCCE 기출문제] 6번 / 물 부족

3st/Hyeonseo/programmer/가까운 수.java, 3st/Hyeonseo/programmer/마지막 두 원소.js, 3st/Hyeonseo/programmer/무작위로 K개의 수 뽑기.py, 3st/Hyeonseo/programmer/배열에서 문자열 대소문자 변환하기.js, 프로그래머스/0/181865. 간단한 식 계산하기/README.md, 프로그래머스/0/181865. 간단한 식 계산하기/간단한 식 계산하기.py
=> [225일차] 조현서 / 간단한 식 계산하기 

4st/Gau/programmer/덧셈식 출력하기.java
| 덧셈식 출력하기 | 프로그래머스 | Level.0 |
<hr/>
=> [PGS] 노가우 / 20일차 / 덧셈식 출력하기 / Lv.0

3st/Jaehee/병과분류.py
https://school.programmers.co.kr/learn/courses/30/lessons/340204
| 병과분류 | 프로그래머스 | Level.0 |
<hr/>
- 병과분류 : 퓨쳐종합병원에서는 접수한 환자가 진료받을 병과에 따라 자동으로 환자 코드를 부여해 주는 프로그램이 있습니다. 환자 코드의 마지막 네 글자를 보면 환자가 어디 병과에서 진료를 받아야 할지 알 수 있습니다. 예를 들어 환자의 코드가 "_eye"로 끝난다면 안과를, "head"로 끝난다면 신경외과 진료를 보게 됩니다. 환자 코드의 마지막 글자에 따른 병과 분류 기준은 다음과 같습니다.
=> [226일] 이제희/병과분류

4st/Hani/baekjoon/A+B-7.java
https://www.acmicpc.net/problem/11021
| A+B-7 | 백준 | 브론즈5 |
<hr/>
- A+B-7 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [31일차] 최한이 / A+B-7

3st/Juram/programmer/배열 원소의 길이.js
<hr/>
- 배열 원소의 길이 : 문자열 배열 strlist가 매개변수로 주어집니다. strlist 각 원소의 길이를 담은 배열을 return하도록 solution 함수를 완성해주세요.
=> [37일차] 김주람 / 배열 원소의 길이

3st/Juram/programmer/아이스 아메리카노.java
=> [38일차] 김주람 / 아이스 아메리카노

4st/Hani/baekjoon/A+B-8.java
https://www.acmicpc.net/problem/11022
| A+B-8 | 백준 | 브론즈5 |
<hr/>
- A+B-8 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [32일차] 최한이 / A+B-8

3st/Hajeong/programmer/최댓값 만들기(1).java, 프로그래머스/0/120847. 최댓값 만들기 （1）/README.md, 프로그래머스/0/120847. 최댓값 만들기 （1）/최댓값 만들기 （1）.java
| 최댓값 만들기(1) | 프로그래머스 | Level.0 |
<hr/>
=> [38일차] 임하정 / 최댓값 만들기(1)

4st/Hani/programmer/두 수의 곱 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120804
<hr/>
- 두 수의 곱 구하 : 정수 num1, num2가 매개변수 주어집니다. num1과 num2를 곱한 값을 return 하도록 solution 함수를 완성해주세요.
=> [33일차] 최한이 / 두 수의 곱 구하기

3st/Juram/programmer/원소들의 곱과 합.js
=> [39일차] 김주람 / 원소들의 곱과 합

4st/Eunseong/구슬을 나누는 경우의 수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120840#
| 구슬을 나누는 경우의 수 | 프로그래머스 | Level.0 |
<hr/>
- 구슬을 나누는 경우의 수 : 머쓱이는 구슬을 친구들에게 나누어주려고 합니다. 구슬은 모두 다르게 생겼습니다. 머쓱이가 갖고 있는 구슬의 개수 balls와 친구들에게 나누어 줄 구슬 개수 share이 매개변수로 주어질 때, balls개의 구슬 중 share개의 구슬을 고르는 가능한 모든 경우의 수를 return 하는 solution 함수를 완성해주세요.
=> [39일차] 공은성 / 구슬을 나누는 경우의 수

4st/Eunseong/[PCCE 기출문제] 7번 ／ 가습기.java
https://school.programmers.co.kr/learn/courses/30/lessons/250127
| [PCCE 기출문제] 7번 / 가습기 | 프로그래머스 | Level.0 |
<hr/>
- [PCCE 기출문제] 7번 / 가습기 : 상우가 사용하는 가습기에는 "auto", "target", "minimum"의 세 가지 모드가 있습니다. 가습기의 가습량은 0~5단계로 구분되며 각 모드 별 동작 방식은 다음과 같습니다.
"auto" 모드
습도가 0 이상 10 미만인 경우 : 5단계
습도가 10 이상 20 미만인 경우 : 4단계
습도가 20 이상 30 미만인 경우 : 3단계
습도가 30 이상 40 미만인 경우 : 2단계
습도가 40 이상 50 미만인 경우 : 1단계
습도가 50 이상인 경우 : 0단계
"target" 모드
습도가 설정값 미만일 경우 : 3단계
습도가 설정값 이상일 경우 : 1단계
"minimum"모드
습도가 설정값 미만일 경우 : 1단계
습도가 설정값 이상일 경우 : 0단계
상우가 설정한 가습기의 모드를 나타낸 문자열 mode_type, 현재 공기 중 습도를 나타낸 정수 humidity, 설정값을 나타낸 정수 val_set이 주어질 때 현재 가습기가 몇 단계로 작동 중인지 return하도록 빈칸을 채워 solution 함수를 완성해 주세요.
=> [40일차] 공은성 / [PCCE 기출문제] 7번 / 가습기

3st/Juram/programmer/n의 배수.js
| n의 배수 | 프로그래머스 | Level.0 |
<hr/>
- n의 배수 : 정수 num과 n이 매개 변수로 주어질 때, num이 n의 배수이면 1을 return n의 배수가 아니라면 0을 return하도록 solution 함수를 완성해주세요.
=> [40일차] 김주람 / n의 배수

3st/Hajeong/programmer/배열자르기.java, 프로그래머스/0/120833. 배열 자르기/README.md, 프로그래머스/0/120833. 배열 자르기/배열 자르기.java
=> [40일차] 임하정 / 배열 자르기

3st/Juram/programmer/flag에 따라 다른 값 반환하기.js
=> [41일차] 김주람 / flag에 따라 다른 값 반환하기

4st/Hani/programmer/양꼬치.java
https://school.programmers.co.kr/learn/courses/30/lessons/120830
<hr/>
=> [34일차] 최한이 / 양꼬치

4st/Jisoo/programmer/제곱수 판별하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120824
<hr/>
=> [32일차] 임지수 / 짝수 홀수 개수

3st/Hajeong/programmer/모음 제거.java, 프로그래머스/0/120849. 모음 제거/README.md, 프로그래머스/0/120849. 모음 제거/모음 제거.java
<hr/>
- 모음 제거 : 영어에선 a, e, i, o, u 다섯 가지 알파벳을 모음으로 분류합니다. 문자열 my_string이 매개변수로 주어질 때 모음을 제거한 문자열을 return하도록 solution 함수를 완성해주세요.
=> [41일차] 임하정 / 모음 제거

4st/Eunseong/a와 b 출력하기
https://school.programmers.co.kr/learn/courses/30/lessons/181951
<hr/>
- a와 b 출력하기 : 정수 a와 b가 주어집니다. 각 수를 입력받아 입출력 예와 같은 형식으로 출력하는 코드를 작성해 보세요.
=> [42일차] 공은성 / a와 b 출력하기

3st/Hyeonseo/programmer/간단한 식 계산하기.py, 프로그래머스/0/181888. n개 간격의 원소들/README.md, 프로그래머스/0/181888. n개 간격의 원소들/n개 간격의 원소들.js
=> [231일차] 조현서 / n개 간격의 원소들 

3st/Hajeong/programmer/문자 리스트를 문자열로 변환하기.java, 프로그래머스/0/181941. 문자 리스트를 문자열로 변환하기/README.md, 프로그래머스/0/181941. 문자 리스트를 문자열로 변환하기/문자 리스트를 문자열로 변환하기.java
=> [43일차] 임하정 / 문자 리스트를 문자열로 변환하기

4st/Hani/baekjoon/A+B-5.java
https://www.acmicpc.net/problem/10952
| A+B-5 | 백준 | 브론즈5 |
<hr/>
- A+B-5 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [35일차] 최한이 / A+B-5

4st/Eunseong/소문자로 바꾸기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181876
| 소문자로 바꾸기 | 프로그래머스 |  Level.0 |
<hr/>
=> [43일차] 공은성 / 소문자로 바꾸기

3st/Jaeyoung/나머지 구하기.cpp
=> [232일차] 박재영 / 나머지 구하기

4st/Eunseong/A로 B 만들기.java, 4st/Eunseong/숫자 찾기.java, 4st/Eunseong/인덱스 바꾸기.java
| 인덱스 바꾸기 | 프로그래머스 | Level.0 |
| A로 B 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 인덱스 바꾸기 : 문자열 my_string과 정수 num1, num2가 매개변수로 주어질 때, my_string에서 인덱스 num1과 인덱스 num2에 해당하는 문자를 바꾼 문자열을 return 하도록 solution 함수를 완성해보세요.
- A로 B 만들기 : 문자열 before와 after가 매개변수로 주어질 때, before의 순서를 바꾸어 after를 만들 수 있으면 1을, 만들 수 없으면 0을 return 하도록 solution 함수를 완성해보세요.
=> [44일차] 공은성 / 인덱스 바꾸기 (외 2개)

4st/Hani/programmer/각도기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120829
<hr/>
=> [36일차] 최한이 / 각도기

4st/Seohyun/programmer/짝수 홀수 개수.java
=> [31일차] 이서현 / 짝수 홀수 개수

4st/Eunseong/문자열 곱하기.java
=> [45일차] 공은성 / 문자열 곱하기

4st/Jisoo/baekjoon/별 찍기-1.java
https://www.acmicpc.net/problem/2439
| 별 찍기-2  | 백준 | 브론즈 V |
<hr/>
- 별 찍기-2 : 첫째 줄에는 별 1개, 둘째 줄에는 별 2개, N번째 줄에는 별 N개를 찍는 문제
=> [34일차] 임지수 / 별 찍기 

4st/Hani/baekjoon/개수 세기.java, 4st/Hani/programmer/배열 두 배 만들기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120809
| 배열 두 배 만들기 | 프로그래머스 | Level.1 |
<hr/>
- 배열 두 배 만들 : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 각 원소에 두배한 원소를 가진 배열을 return하도록 solution 함수를 완성해주세요.
=> [37일차] 최한이 / 배열 두 배 만들기

3st/Jaeyoung/두 수의 나눗셈.cpp
| 두 수의 나눗셈 | 프로그래머스 | Level.0 |
<hr/>
- 두 수의 나눗셈 : 정수 num1과 num2가 매개변수로 주어질 때, num1을 num2로 나눈 값에 1,000을 곱한 후 정수 부분을 return 하도록 solution 함수를 완성해주세요.
=> [235일차] 박재영 / 두 수의 나눗셈

4st/Eunseong/문자열 붙여서 출력하기.java
<hr/>
- 문자열 붙여서 출력하기 : 두 개의 문자열 str1, str2가 공백으로 구분되어 입력으로 주어집니다.
=> [46일차] 공은성 / 문자열 붙여서 출력하기

4st/Hani/baekjoon/X보다 작은 수.java
https://www.acmicpc.net/problem/10807
| 개수 세기 | 백준 | 브론즈5 |
<hr/>
- 개수 세기 : 총 N개의 정수가 주어졌을 때, 정수 v가 몇 개인지 구하는 프로그램을 작성하시오.
=> [38일차] 최한이 / 개수 세기

4st/Jisoo/baekjoon/별 찍기-2.java, 4st/Jisoo/programmer/홀짝 구분하기.java
| 덧셈식 출력하기 | 프로그래머스 | Level.0 |
<hr/>
a + b = c
=> [36일차] 임지수 / 덧셈식 출력하기 

4st/Eunseong/n개 간격의 원소들.java
https://school.programmers.co.kr/learn/courses/30/lessons/181888
<hr/>
=> [47일차] 공은성 / n개 간격의 원소들

3st/Juram/programmer/두 수의 연산값 비교하기.js
| 두 수의 연산값 비교하기 | 프로그래머스 | Level.0 |
<hr/>
12 ⊕ 3 = 123
3 ⊕ 12 = 312
=> [48일차] 김주람 / 두 수의 연산값 비교하기

3st/Hajeong/programmer/두 수의 곱 구하기.py
https://school.programmers.co.kr/learn/courses/30/lessons/120804?language=python3
<hr/>
=> [48일차] 임하정 / 두 수의 곱 구하기

4st/Eunseong/조건에 맞게 수열 변환하기 1.java
https://school.programmers.co.kr/learn/courses/30/lessons/181882
| 조건에 맞게 수열 변환하기 1 | 프로그래머스 | Level.0 |
<hr/>
- 조건에 맞게 수열 변환하기 1 : 정수 배열 arr가 주어집니다. arr의 각 원소에 대해 값이 50보다 크거나 같은 짝수라면 2로 나누고, 50보다 작은 홀수라면 2를 곱합니다. 그 결과인 정수 배열을 return 하는 solution 함수를 완성해 주세요.
=> [48일차] 공은성 / 조건에 맞게 수열 변환하기 1

4st/Hani/programmer/문자열 붙여서 출력하기.java
<hr/>
- 문자열 붙여서 출력하기 : 두 개의 문자열 str1, str2가 공백으로 구분되어 입력으로 주어집니다.
=> [39일차] 최한이 / 문자열 붙여서 출력하기

4st/Seohyun/programmer/제곱수 판별하기.java
| 제곱수 판별하기 | 프로그래머스 | Level.0 |
<hr/>
- 제목 : 어떤 자연수를 제곱했을 때 나오는 정수를 제곱수라고 합니다. 정수 n이 매개변수로 주어질 때, n이 제곱수라면 1을 아니라면 2를 return하도록 solution 함수를 완성해주세요.
=> [33일차] 이서현 / 제곱수 판별하기

3st/Jaeyoung/세균 증식.cpp
<hr/>
- 세균 증식 : 어떤 세균은 1시간에 두배만큼 증식한다고 합니다. 처음 세균의 마리수 n과 경과한 시간 t가 매개변수로 주어질 때 t시간 후 세균의 수를 return하도록 solution 함수를 완성해주세요.
=> [238일차] 박재영 / 세균 증식

4st/Hani/programmer/덧셈식 출력하기.java, 4st/Hani/programmer/문자열 출력하기.java
| 덧셈식 출력하기 | 프로그래머스 | Level.1 |
<hr/>
=> [40일차] 최한이 / 덧셈식 출력하기

3st/Juram/programmer/중앙값 구하기.js
https://school.programmers.co.kr/learn/courses/30/lessons/120811
<hr/>
=> [49일차] 김주람 / 중앙값 구하기

4st/Eunseong/특수문자 출력하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181948
| 특수문자 출력하기 | 프로그래머스 | Level.0 |
<hr/>
- 특수문자 출력하기 : 다음과 같이 출력하도록 코드를 작성해 주세요.
=> [PGS] 특수문자 출력하기 / level.0

3st/Juram/programmer/문자열 뒤의 n글자.js
<hr/>
- 문자열의 뒤의 n글자 : 문자열 my_string과 정수 n이 매개변수로 주어질 때, my_string의 뒤의 n글자로 이루어진 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [50일차] 김주람 / 문자열의 뒤의 n글자

4st/Hani/programmer/a와 b 출력하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181951
<hr/>
- a와 b 출력하 : 정수 a와 b가 주어집니다. 각 수를 입력받아 입출력 예와 같은 형식으로 출력하는 코드를 작성해 보세요.
=> [41일차] 최한이 / a와 b 출력하기

4st/Seohyun/programmer/A+B.java, 4st/Seohyun/programmer/개미 군단.java, 4st/Seohyun/programmer/나머지 구하기.java, 4st/Seohyun/programmer/나이 출력.c, 4st/Seohyun/programmer/몫 구하기.c, 4st/Seohyun/programmer/옷가게 할인 받기.java, 4st/Seohyun/programmer/주사위의 개수.java, 4st/Seohyun/programmer/특수문자 출력하기.java
| 주사위의 개수 | 프로그래머스 | Level.0 |
<hr/>
- 주사위의 개수 : 머쓱이는 직육면체 모양의 상자를 하나 가지고 있는데 이 상자에 정육면체 모양의 주사위를 최대한 많이 채우고 싶습니다. 상자의 가로, 세로, 높이가 저장되어있는 배열 box와 주사위 모서리의 길이 정수 n이 매개변수로 주어졌을 때, 상자에 들어갈 수 있는 주사위의 최대 개수를 return 하도록 solution 함수를 완성해주세요.
=> [34일차] 이서현 / 주사위의 개수

4st/Eunseong/뒤에서 5등까지.java
https://school.programmers.co.kr/learn/courses/30/lessons/181853
<hr/>
=> [52일차] 공은성 / 뒤에서 5등까지

4st/Gau/baekjoon/별찍기-2.java
링크
| 제목 | 백준 / 프로그래머스 | 브론즈 V / Level.1 |
<hr/>
- 제목 : 설명
=> [BOJ]  노가우 / 29일차 / 별찍기-2

4st/Seohyun/programmer/배열 두배 만들기.java
| 배열 두배 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 배열 두배 만들기 : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 각 원소에 두배한 원소를 가진 배열을 return하도록 solution 함수를 완성해주세요.
=> [35일차] 이서현 / 배열 두배 만들기

4st/Jisoo/baekjoon/A+B-4.java, 4st/Jisoo/baekjoon/합.java
https://www.acmicpc.net/problem/10807
| 개수 세기 | 백준 | 브론즈 V |
<hr/>
- 개수 세기 : 총 N개의 정수가 주어졌을 때, 정수 v가 몇 개인지 구하는 프로그램을 작성하시오.
=> [40일차] 임지수 / 개수 세기

4st/Hani/programmer/문자열 반복해서 출력하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181950
| 문자열 반복해서 출력하기 | 프로그래머스 | Level.1 |
<hr/>
=> [43일차] 최한이 / 문자열 반복해서 출력하기

3st/Juram/programmer/옷가게 할인 받기.js
| 옷가게 할인 받기 | 프로그래머스 | Level.0 |
<hr/>
- 옷가게 할인 받기 : 머쓱이네 옷가게는 10만 원 이상 사면 5%, 30만 원 이상 사면 10%, 50만 원 이상 사면 20%를 할인해줍니다.
=> [52일차] 김주람 / 옷가게 할인 받기

3st/Jaeyoung/별 찍기 - 1.cpp
| 별 찍기 - 1 | 백준 | 브론즈 V |
<hr/>
- 별 찍기 - 1 : 첫째 줄에는 별 1개, 둘째 줄에는 별 2개, N번째 줄에는 별 N개를 찍는 문제
=> [241일차] 박재영 / 별 찍기 - 1

4st/Hani/programmer/배열 자르기.java, 4st/Hani/programmer/수박수박수박수박수박수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120833
| 배열 자르기 | 프로그래머스 | Level.1 |
<hr/>
=> [44일차] 최한이 / 배열 자르기

3st/Jaeyoung/We love kriii.cpp, 3st/Jaeyoung/나머지 구하기.cpp, 3st/Jaeyoung/올바른 괄호.cpp
| We love kriii | 백준 | 브론즈 V |
<hr/>
- We love kriii : ACM-ICPC 인터넷 예선, Regional, 그리고 World Finals까지 이미 2회씩 진출해버린 kriii는 미련을 버리지 못하고 왠지 모르게 올해에도 파주 World Finals 준비 캠프에 참여했다.
대회를 뜰 줄 모르는 지박령 kriii를 위해서 격려의 문구를 출력해주자.
=> [242일차] 박재영 / We love kriii

4st/Eunseong/369게임.java, 4st/Eunseong/대소문자 바꿔서 출력하기.java, 4st/Eunseong/분수의 덧셈.java, 4st/Eunseong/특별한 이차원 배열 1.java, 4st/Eunseong/특별한 이차원 배열 2.java
https://school.programmers.co.kr/learn/courses/30/lessons/181833
| 특별한 이차원 배열 1 | 프로그래머스 | Level.0 |
| 특별한 이차원 배열 2 | 프로그래머스 | Level.0 |
| 대소문자 바꿔서 출력하기 | 프로그래머스 | Level.0 |
<hr/>
- 특별한 이차원 배열 1 : 정수 n이 매개변수로 주어질 때, 다음과 같은 n × n 크기의 이차원 배열 arr를 return 하는 solution 함수를 작성해 주세요.
- 특별한 이차원 배열 2 : n × n 크기의 이차원 배열 arr이 매개변수로 주어질 때, arr이 다음을 만족하면 1을 아니라면 0을 return 하는 solution 함수를 작성해 주세요.
- 대소문자 바꿔서 출력하기 : 영어 알파벳으로 이루어진 문자열 str이 주어집니다. 각 알파벳을 대문자는 소문자로 소문자는 대문자로 변환해서 출력하는 코드를 작성해 보세요.
=> [54일차] 공은성 / 특별한 이차원 배열 1 (외 2개)

3st/Jaeyoung/별 찍기 - 2.cpp
| 별 찍기 - 2 | 백준 | 브론즈 IV |
<hr/>
- 별 찍기 - 2 : 첫째 줄에는 별 1개, 둘째 줄에는 별 2개, N번째 줄에는 별 N개를 찍는 문제
=> [244일차] 박재영 / 별 찍기 - 2

4st/Eunseong/접두사인지 확인하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181906
| 접두사인지 확인하기 | 프로그래머스 | Level.0 |
<hr/>
- 접두사인지 확인하기 : 어떤 문자열에 대해서 접두사는 특정 인덱스까지의 문자열을 의미합니다. 예를 들어, "banana"의 모든 접두사는 "b", "ba", "ban", "bana", "banan", "banana"입니다.
문자열 my_string과 is_prefix가 주어질 때, is_prefix가 my_string의 접두사라면 1을, 아니면 0을 return 하는 solution 함수를 작성해 주세요.
=> [55일차] 공은성 / 접두사인지 확인하기

4st/Jisoo/baekjoon/X보다 작은 수.java, 4st/Jisoo/baekjoon/개수 세기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120809
| 배열 두 배 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 배열 두 배 만들기: 정수 배열 numbers가 매개변수로 주어집니다. numbers의 각 원소에 두배한 원소를 가진 배열을 return하도록 solution 함수를 완성해주세요.
=> [55일차] 임지수 / 배열 두 배 만들기

3st/Jaeyoung/별 찍기 - 3.cpp
| 별 찍기 - 3 | 백준 | 브론즈 IV |
<hr/>
- 별 찍기 - 3 : 첫째 줄에는 별 N개, 둘째 줄에는 별 N-1개, ..., N번째 줄에는 별 1개를 찍는 문제
=> [245일차] 박재영 / 별 찍기 - 3

3st/Juram/programmer/숨어있는 숫자의 덧셈 (1).js
| 숨어있는 숫자의 덧셈 (1) | 프로그래머스 | Level.0 |
<hr/>
- 숨어있는 숫자의 덧셈 (1) : 문자열 my_string이 매개변수로 주어집니다. my_string안의 모든 자연수들의 합을 return하도록 solution 함수를 완성해주세요.
=> [56일차] 김주람 / 숨어있는 숫자의 덧셈 (1)

4st/Eunseong/홀짝에 따라 다른 값 반환하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181935
<hr/>
=> [57일차] 공은성 / 홀짝에 따라 다른 값 반환하기

4st/Hani/programmer/피타고라스의 정리.java
https://school.programmers.co.kr/learn/courses/30/lessons/250132
| 피타고라스의 정리 | 프로그래머스 |  Level.1 |
<hr/>
- 피타고라스의 정리 : 직각삼각형이 주어졌을 때 빗변의 제곱은 다른 두 변을 각각 제곱한 것의 합과 같습니다.
직각삼각형의 한 변의 길이를 나타내는 정수 a와 빗변의 길이를 나타내는 정수 c가 주어질 때, 다른 한 변의 길이의 제곱, b_square 을 출력하도록 한 줄을 수정해 코드를 완성해 주세요.
=> [57일차]  최한이 / 피타고라스의 정리

3st/Juram/programmer/가장 큰 수 찾기.js
=> [57일차] 김주람 / 가장 큰 수 찾기

4st/Eunseong/모스부호 (1).java
https://school.programmers.co.kr/learn/courses/30/lessons/120838
| 모스부호 (1) | 프로그래머스 | Level.0 |
<hr/>
- 모스부호 (1) : 머쓱이는 친구에게 모스부호를 이용한 편지를 받았습니다. 그냥은 읽을 수 없어 이를 해독하는 프로그램을 만들려고 합니다. 문자열 letter가 매개변수로 주어질 때, letter를 영어 소문자로 바꾼 문자열을 return 하도록 solution 함수를 완성해보세요.
=> [58일차] 공은성 / 모스부호 (1)

3st/Jaeyoung/합.c
| 합 | 백준 | 브론즈 V |
<hr/>
- 합 : n이 주어졌을 때, 1부터 n까지 합을 구하는 프로그램을 작성하시오.
=> [247일차] 박재영 / 합

3st/Jaehee/버스.java
https://school.programmers.co.kr/learn/courses/30/lessons/340201?language=java
| 버스 | 프로그래머스 |  Level.0 |
<hr/>
- 버스 : 영진이는 약속장소에 가기 위해 버스를 타려고 합니다. 버스에는 좌석이 총 seat개만큼 있습니다. 영진이는 버스 좌석에 앉아서 갈 수 있을지 궁금해합니다. 기점에서 출발한 버스가 영진이가 기다리는 정거장에 도착하기 전에 방문하는 각 정거장에서 승/하차한 승객 정보가 주어질 때, 영진이가 버스에 탄 순간 빈 좌석은 몇 개인지 구해주세요. 영진이가 기다리는 정거장에서는 영진이가 제일 먼저 버스에 탑승하며, 이전 정거장에서 버스에 탑승한 승객들은 남는 좌석이 있다면 항상 앉는다고 가정합니다. 또, 기점에서 출발하는 버스에는 승객이 0명 타고 있습니다.
예를 들어 다음은 좌석이 5개인 버스에 각 정거장에서 승/하차한 승객 정보를 나타냅니다. 영진이는 4번 정거장에서 기다리고 있으며, "On"은 승차한 승객, "Off"는 하차한 승객을 의미합니다.
=> [247일] 이제희/버스

4st/Gau/baekjoon/A-B-7.java
https://www.acmicpc.net/submit/11021/95809792
| A-B-7 | 백준 | 브론즈 V |
<hr/>
- A-B-7 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
입력
첫째 줄에 테스트 케이스의 개수 T가 주어진다.
각 테스트 케이스는 한 줄로 이루어져 있으며, 각 줄에 A와 B가 주어진다. (0 < A, B < 10)
출력
각 테스트 케이스마다 "Case #x: "를 출력한 다음, A+B를 출력한다. 테스트 케이스 번호는 1부터 시작한다.
예제 입력 1 
5
1 1
2 3
3 4
9 8
5 2
예제 출력 1 
Case #1: 2
Case #2: 5
Case #3: 7
Case #4: 17
Case #5: 7
=> [BOJ] / 노가우 / 58일차 / A-B-7

4st/Eunseong/소인수분해.java, 4st/Eunseong/숨어있는 숫자의 덧셈 (2).java, 4st/Eunseong/이진수 더하기.java, 4st/Eunseong/중복된 문자 제거.java
| 중복된 문자 제거 | 프로그래머스 | Level.0 |
| 숨어있는 숫자의 덧셈 (2) | 프로그래머스 | Level.0 |
| 소인수분해 | 프로그래머스 | Level.0 |
| 이진수 더하기 | 프로그래머스 | Level.0 |
<hr/>
- 중복된 문자 제거 : 문자열 my_string이 매개변수로 주어집니다. my_string에서 중복된 문자를 제거하고 하나의 문자만 남긴 문자열을 return하도록 solution 함수를 완성해주세요.
- 숨어있는 숫자의 덧셈 (2) : 문자열 my_string이 매개변수로 주어집니다. my_string은 소문자, 대문자, 자연수로만 구성되어있습니다. my_string안의 자연수들의 합을 return하도록 solution 함수를 완성해주세요.
- 소인수분해 : 소인수분해란 어떤 수를 소수들의 곱으로 표현하는 것입니다. 예를 들어 12를 소인수 분해하면 2 * 2 * 3 으로 나타낼 수 있습니다. 따라서 12의 소인수는 2와 3입니다. 자연수 n이 매개변수로 주어질 때 n의 소인수를 오름차순으로 담은 배열을 return하도록 solution 함수를 완성해주세요.
- 이진수 더하기 : 이진수를 의미하는 두 개의 문자열 bin1과 bin2가 매개변수로 주어질 때, 두 이진수의 합을 return하도록 solution 함수를 완성해주세요.
=> [58일차] 공은성 / 중복된 문자 제거 (외 3개)

3st/Juram/programmer/소문자로 바꾸기.js
=> [59일차] 김주람 / 소문자로 바꾸기

4st/Hani/programmer/n의 배수 고르기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120905
| n의 배수 고르기 | 프로그래머스 | Level.1 |
<hr/>
=> [59일차] 최한이 / n의 배수 고르기

4st/Hani/programmer/아이스 아메리카노.java
https://school.programmers.co.kr/learn/courses/30/lessons/120819
<hr/>
=> [60일차] 최한이 / 아이스 아메리카노

4st/Eunseong/삼각형의 완성조건 (2).java
https://school.programmers.co.kr/learn/courses/30/lessons/120868
| 삼각형의 완성조건 (2) | 프로그래머스 | Level.0 |
<hr/>
- 삼각형의 완성조건 (2) : 선분 세 개로 삼각형을 만들기 위해서는 다음과 같은 조건을 만족해야 합니다.
가장 긴 변의 길이는 다른 두 변의 길이의 합보다 작아야 합니다.
삼각형의 두 변의 길이가 담긴 배열 sides이 매개변수로 주어집니다. 나머지 한 변이 될 수 있는 정수의 개수를 return하도록 solution 함수를 완성해주세요.
=> [60일차] 공은성 / 삼각형의 완성조건 (2)

4st/Eunseong/OX퀴즈.java
https://school.programmers.co.kr/learn/courses/30/lessons/120907
| OX퀴즈 | 프로그래머스 | Level.0 |
<hr/>
- OX퀴즈 : 덧셈, 뺄셈 수식들이 'X [연산자] Y = Z' 형태로 들어있는 문자열 배열 quiz가 매개변수로 주어집니다. 수식이 옳다면 "O"를 틀리다면 "X"를 순서대로 담은 배열을 return하도록 solution 함수를 완성해주세요.
=> [61일차] 공은성 / OX퀴즈

3st/Jaeyoung/A+B - 5.cpp, 3st/Jaeyoung/두 수의 합 구하기.cpp
| 두 수의 합 구하기 | 프로그래머스 | Level.0 |
<hr/>
- 두 수의 합 구하기 : 정수 num1과 num2가 주어질 때, num1과 num2의 합을 return하도록 soltuion 함수를 완성해주세요.
=> [249일차] 박재영 / 두 수의 합 구하기

4st/Eunseong/안전지대.java
https://school.programmers.co.kr/learn/courses/30/lessons/120866
| 안전지대 | 프로그래머스 | Level.0 |
<hr/>
- 안전지대 : 다음 그림과 같이 지뢰가 있는 지역과 지뢰에 인접한 위, 아래, 좌, 우 대각선 칸을 모두 위험지역으로 분류합니다.
지뢰는 2차원 배열 board에 1로 표시되어 있고 board에는 지뢰가 매설 된 지역 1과, 지뢰가 없는 지역 0만 존재합니다.
지뢰가 매설된 지역의 지도 board가 매개변수로 주어질 때, 안전한 지역의 칸 수를 return하도록 solution 함수를 완성해주세요.
=> [62일차] 공은성 / 안전지대

4st/Hani/programmer/홀짝 구분하기.java
| 홀짝 구분하기 | 프로그래머스 | Level.1 |
<hr/>
=> [63일차] 최한이 / 홀짝 구분하기

4st/Eunseong/꼬리 문자열.java, 4st/Eunseong/뒤에서 5등 뒤로.java
https://school.programmers.co.kr/learn/courses/30/lessons/181852
| 뒤에서 5등 뒤로 | 프로그래머스 | Level.0 |
<hr/>
- 뒤에서 5등 뒤로 : 정수로 이루어진 리스트 num_list가 주어집니다. num_list에서 가장 작은 5개의 수를 제외한 수들을 오름차순으로 담은 리스트를 return하도록 solution 함수를 완성해주세요.
=> [64일차] 공은성 / 뒤에서 5등 뒤로

3st/Hyeonseo/programmer/I로 만들기.py, 프로그래머스/0/181834. l로 만들기/README.md, 프로그래머스/0/181834. l로 만들기/l로 만들기.py
| I로 만들기 | 프로그래머스 | Level.0 |
<hr/>
- I로 만들기 : 알파벳 소문자로 이루어진 문자열 myString이 주어집니다. 알파벳 순서에서 "l"보다 앞서는 모든 문자를 "l"로 바꾼 문자열을 return 하는 solution 함수를 완성해 주세요.
=> [254일차] 조현서 / I로 만들기 

4st/Hani/programmer/피자 나눠 먹기(1).java
https://school.programmers.co.kr/learn/courses/30/lessons/120z814
| 피자 나눠 먹기(1) | 프로그래머스 | Level.0 |
<hr/>
- 피자 나눠 먹기(1) : 머쓱이네 피자가게는 피자를 일곱 조각으로 잘라 줍니다. 피자를 나눠먹을 사람의 수 n이 주어질 때, 모든 사람이 피자를 한 조각 이상 먹기 위해 필요한 피자의 수를 return 하는 solution 함수를 완성해보세요.
=> [66일차] 최한이 / 피자 나눠 먹기(1)

4st/Eunseong/문자열 정수의 합.java
https://school.programmers.co.kr/learn/courses/30/lessons/181849
<hr/>
=> [66일차] 공은성 / 문자열 정수의 합

3st/Hyeonseo/programmer/문자열 돌리기.py, 프로그래머스/0/181945. 문자열 돌리기/README.md, 프로그래머스/0/181945. 문자열 돌리기/문자열 돌리기.py
| 문자열 돌리기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 돌리기 : 문자열 str이 주어집니다.
=> [254일차] 조현서 / 문자열 돌리기

3st/Jaehee/두 수의 합 구하기.js
http://school.programmers.co.kr/learn/courses/30/lessons/120802?language=javascript
| 두 수의 합 구하기  | 프로그래머스 | Level.0 |
<hr/>
- 두 수의 합 구하기  : 정수 num1과 num2가 주어질 때, num1과 num2의 합을 return하도록 soltuion 함수를 완성해주세요.
=> [255일] 이제희/두 수의 합 구하기 

4st/Hani/programmer/중복된 숫자 개수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120583
| 중복된 숫자 개수 | 프로그래머스 | Level.1 |
<hr/>
=> [67일차] 최한이 / 중복된 숫자 개수

4st/Eunseong/이어 붙인 수.java
https://school.programmers.co.kr/learn/courses/30/lessons/181928
<hr/>
=> [67일차] 공은성 / 이어 붙인 수

3st/Juram/programmer/n보다 커질 때까지 더하기.java
<hr/>
- n보다 커질 때까지 더하기 : 정수 배열 numbers와 정수 n이 매개변수로 주어집니다. numbers의 원소를 앞에서부터 하나씩 더하다가 그 합이 n보다 커지는 순간 이때까지 더했던 원소들의 합을 return 하는 solution 함수를 작성해 주세요.
=> [67일차] 김주람 / n보다 커질 때까지 더하기

4st/Eunseong/유한소수 판별하기.java, 4st/Eunseong/평행.java
https://school.programmers.co.kr/learn/courses/30/lessons/120878
| 유한소수 판별하기 | 프로그래머스 | Level.0 |
| 평행 | 프로그래머스 | Level.0 |
<hr/>
- 유한소수 판별하기 : 소수점 아래 숫자가 계속되지 않고 유한개인 소수를 유한소수라고 합니다. 분수를 소수로 고칠 때 유한소수로 나타낼 수 있는 분수인지 판별하려고 합니다. 유한소수가 되기 위한 분수의 조건은 다음과 같습니다.
기약분수로 나타내었을 때, 분모의 소인수가 2와 5만 존재해야 합니다.
두 정수 a와 b가 매개변수로 주어질 때, a/b가 유한소수이면 1을, 무한소수라면 2를 return하도록 solution 함수를 완성해주세요.
- 평행 : 점 네 개의 좌표를 담은 이차원 배열  dots가 다음과 같이 매개변수로 주어집니다.
[[x1, y1], [x2, y2], [x3, y3], [x4, y4]]
주어진 네 개의 점을 두 개씩 이었을 때, 두 직선이 평행이 되는 경우가 있으면 1을 없으면 0을 return 하도록 solution 함수를 완성해보세요.
=> [68일차] 공은성 / 유한소수 판별하기 (외 1개)

3st/Jaehee/덧셈식 출력하기.py
| 덧셈식 출력하기  | 프로그래머스 | Level.0 |
<hr/>
- 덧셈식 출력하기  : 두 정수 a, b가 주어질 때 다음과 같은 형태의 계산식을 출력하는 코드를 작성해 보세요.
=> [256일] 이제희/덧셈식 출력하기 

4st/Eunseong/겹치는 선분의 길이.java, 4st/Eunseong/옹알이 (1).java, 4st/Eunseong/특이한 정렬.java
https://school.programmers.co.kr/learn/courses/30/lessons/120876#
https://school.programmers.co.kr/learn/courses/30/lessons/120880
https://school.programmers.co.kr/learn/courses/30/lessons/120956
| 겹치는 선분의 길이 | 프로그래머스 | Level.0 |
| 특이한 정렬 | 프로그래머스 | Level.0 |
| 옹알이 (1) | 프로그래머스 | Level.0 |
<hr/>
- 겹치는 선분의 길이 : 선분 3개가 평행하게 놓여 있습니다. 세 선분의 시작과 끝 좌표가 [[start, end], [start, end], [start, end]] 형태로 들어있는 2차원 배열 lines가 매개변수로 주어질 때, 두 개 이상의 선분이 겹치는 부분의 길이를 return 하도록 solution 함수를 완성해보세요.
lines가 [[0, 2], [-3, -1], [-2, 1]]일 때 그림으로 나타내면 다음과 같습니다.
선분이 두 개 이상 겹친 곳은 [-2, -1], [0, 1]로 길이 2만큼 겹쳐있습니다.
- 특이한 정렬 : 정수 n을 기준으로 n과 가까운 수부터 정렬하려고 합니다. 이때 n으로부터의 거리가 같다면 더 큰 수를 앞에 오도록 배치합니다. 정수가 담긴 배열 numlist와 정수 n이 주어질 때 numlist의 원소를 n으로부터 가까운 순서대로 정렬한 배열을 return하도록 …
=> [69일차] 공은성 / 겹치는 선분의 길이 (외 2개)

3st/Juram/programmer/배열 만들기 1.java
=> [69일차] 김주람 / 배열 만들기 1

프로그래머스/0/120911. 문자열 정렬하기 （2）/README.md, 프로그래머스/0/120911. 문자열 정렬하기 （2）/문자열 정렬하기 （2）.py
=> [258일차] 조현서 / 문자열 정렬하기 (2) 

3st/Jaehee/소문자로 바꾸기.js
https://school.programmers.co.kr/learn/courses/30/lessons/181876
<hr/>
=> [258일] 이제희/소문자로 바꾸기

4st/Eunseong/주사위 게임 1.java
https://school.programmers.co.kr/learn/courses/30/lessons/181839
| 주사위 게임 1 | 프로그래머스 | Level.0 |
<hr/>
- 주사위 게임 1 : 1부터 6까지 숫자가 적힌 주사위가 두 개 있습니다. 두 주사위를 굴렸을 때 나온 숫자를 각각 a, b라고 했을 때 얻는 점수는 다음과 같습니다.
두 정수 a와 b가 매개변수로 주어질 때, 얻는 점수를 return 하는 solution 함수를 작성해 주세요.
=> [72일차] 공은성 / 주사위 게임 1

4st/Hani/programmer/병과분류.java
https://school.programmers.co.kr/learn/courses/30/lessons/340204
| 병과분류 | 프로그래머스 | Level.1 |
<hr/>
- 병과분류 : 퓨쳐종합병원에서는 접수한 환자가 진료받을 병과에 따라 자동으로 환자 코드를 부여해 주는 프로그램이 있습니다. 환자 코드의 마지막 네 글자를 보면 환자가 어디 병과에서 진료를 받아야 할지 알 수 있습니다. 예를 들어 환자의 코드가 "_eye"로 끝난다면 안과를, "head"로 끝난다면 신경외과 진료를 보게 됩니다. 환자 코드의 마지막 글자에 따른 병과 분류 기준은 다음과 같습니다.
- 환자의 코드를 나타내는 문자열 code를 입력받아 위 표에 맞는 병과를 출력하도록 빈칸을 채워 코드를 완성해 주세요. 위 표의 단어로 끝나지 않는다면 "direct recommendation"를 출력합니다.
=> [73일차] 최한이 / 병과분류

4st/Eunseong/조건 문자열.java
https://school.programmers.co.kr/learn/courses/30/lessons/181934
| 조건 문자열 | 프로그래머스 | Level.0 |
<hr/>
- 조건 문자열 : 문자열에 따라 다음과 같이 두 수의 크기를 비교하려고 합니다.
두 수가 n과 m이라면
">", "=" : n >= m
"<", "=" : n <= m
">", "!" : n > m
"<", "!" : n < m
두 문자열 ineq와 eq가 주어집니다. ineq는 "<"와 ">"중 하나고, eq는 "="와 "!"중 하나입니다. 그리고 두 정수 n과 m이 주어질 때, n과 m이 ineq와 eq의 조건에 맞으면 1을 아니면 0을 return하도록 solution 함수를 완성해주세요.
=> [74일차] 공은성 / 조건 문자열

3st/Hyeonseo/programmer/문자열 바꿔서 찾기.py, 3st/Hyeonseo/programmer/문자열 정렬하기 (2).PY, 3st/Hyeonseo/programmer/배열의 원소만큼 추가하기.py, 프로그래머스/0/181861. 배열의 원소만큼 추가하기/README.md, 프로그래머스/0/181861. 배열의 원소만큼 추가하기/배열의 원소만큼 추가하기.py
=> [262일차] 조현서 / 배열의 원소만큼 추가하기

3st/Jaehee/특정한 문자를 대문자로 바꾸기.py
https://school.programmers.co.kr/learn/courses/30/lessons/181873
| 특정한 문자를 대문자로 바꾸기 | 프로그래머스 | Level.0 |
<hr/>
- 특정한 문자를 대문자로 바꾸기 : 영소문자로 이루어진 문자열 my_string과 영소문자 1글자로 이루어진 문자열 alp가 매개변수로 주어질 때, my_string에서 alp에 해당하는 모든 글자를 대문자로 바꾼 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [262일] 이제희/특정한 문자를 대문자로 바꾸기

3st/Juram/programmer/카운트 다운.java
=> [74일차] 김주람 / 카운트 다운

4st/Seohyun/programmer/머쓱이보다 키 큰 사람.java
| 머쓱이보다 키 큰 사람 | 프로그래머스 | Level.0 |
<hr/>
- 머쓱이보다 키 큰 사람  : 머쓱이는 학교에서 키 순으로 줄을 설 때 몇 번째로 서야 하는지 궁금해졌습니다. 머쓱이네 반 친구들의 키가 담긴 정수 배열 array와 머쓱이의 키 height가 매개변수로 주어질 때, 머쓱이보다 키 큰 사람 수를 return 하도록 solution 함수를 완성해보세요.
=> [74일차] 이서현 / 머쓱이보다 키 큰 사람

4st/Hani/programmer/평균 구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/12944
| 평균 구하기 | 프로그래머스 | Level.1 |
<hr/>
=> [74일차] 최한이 / 평균 구하기

4st/Hani/programmer/두 정수 사이의 합.java
https://school.programmers.co.kr/learn/courses/30/lessons/12912
| 두 정수 사이의 합 | 프로그래머스 | Level.1 |
<hr/>
- 두 정수 사이의 합 : 두 정수 a, b가 주어졌을 때 a와 b 사이에 속한 모든 정수의 합을 리턴하는 함수, solution을 완성하세요.
예를 들어 a = 3, b = 5인 경우, 3 + 4 + 5 = 12이므로 12를 리턴합니다.
=> [75일차] 최한이 / 두 정수 사이의 합

4st/Seohyun/programmer/머쓱이보다 키 큰 사람.c, 4st/Seohyun/programmer/아이스 아메리카노.java
| 아이스 아메리카노  | 프로그래머스 | Level.0 |
<hr/>
=> [75일차] 이서현 / 아이스 아메리카노

4st/Eunseong/문자열의 앞의 n글자.java
https://school.programmers.co.kr/learn/courses/30/lessons/181907
<hr/>
=> [75일차] 공은성 / 문자열의 앞의 n글자

3st/Juram/programmer/9로 나눈 나머지.java
| 9로 나눈 나머지 | 프로그래머스 | Level.0 |
<hr/>
- 9로 나눈 나머지 : 음이 아닌 정수를 9로 나눈 나머지는 그 정수의 각 자리 숫자의 합을 9로 나눈 나머지와 같은 것이 알려져 있습니다.
이 사실을 이용하여 음이 아닌 정수가 문자열 number로 주어질 때, 이 정수를 9로 나눈 나머지를 return 하는 solution 함수를 작성해주세요.
=> [75일차] 김주람 / 9로 나눈 나머지

4st/Seohyun/programmer/홀수 vs 짝수.java
| 홀수 vs 짝수 | 프로그래머스 | Level.0 |
<hr/>
=> [76일차] 이서현 / 홀수 vs 짝수

4st/Eunseong/1로 만들기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181880
| 1로 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 1로 만들기 : 정수가 있을 때, 짝수라면 반으로 나누고, 홀수라면 1을 뺀 뒤 반으로 나누면, 마지막엔 1이 됩니다. 예를 들어 10이 있다면 다음과 같은 과정으로 1이 됩니다.
10 / 2 = 5
2 / 2 = 1
=> [76일차] 공은성 / 1로 만들기

3st/Hajeong/programmer/가장 큰 수 찾기.java, 프로그래머스/0/120899. 가장 큰 수 찾기/README.md, 프로그래머스/0/120899. 가장 큰 수 찾기/가장 큰 수 찾기.java
=> [76일차] 임하정 / 가장 큰 수 찾기

3st/Juram/programmer/수 조작하기 1.java
<hr/>
- 수 조작하기 1 : 정수 n과 문자열 control이 주어집니다. control은 "w", "a", "s", "d"의 4개의 문자로 이루어져 있으며, control의 앞에서부터 순서대로 문자에 따라 n의 값을 바꿉니다.
"w" : n이 1 커집니다.
"s" : n이 1 작아집니다.
"d" : n이 10 커집니다.
"a" : n이 10 작아집니다.
위 규칙에 따라 n을 바꿨을 때 가장 마지막에 나오는 n의 값을 return 하는 solution 함수를 완성해 주세요.
=> [76일차] 김주람 / 수 조작하기 1

4st/Hani/programmer/홀수vs짝수.java
https://school.programmers.co.kr/learn/courses/30/lessons/181887
| 홀수vs짝수 | 프로그래머스 | Level.1 |
<hr/>
- 홀수vs짝수 : 정수 리스트 num_list가 주어집니다. 가장 첫 번째 원소를 1번 원소라고 할 때, 홀수 번째 원소들의 합과 짝수 번째 원소들의 합 중 큰 값을 return 하도록 solution 함수를 완성해주세요. 두 값이 같을 경우 그 값을 return합니다.
=> [76일차] 최한이 / 홀수vs짝수

4st/Hani/programmer/산책.java
https://school.programmers.co.kr/learn/courses/30/lessons/250129
| 산책 | 프로그래머스 | Level.1 |
<hr/>
- 산책 : 여름이는 강아지를 산책시키려고 합니다. 여름이는 2차원 좌표평면에서 동/서/남/북 방향으로 1m 단위로 이동하면서 강아지를 산책시킵니다. 산책루트가 담긴 문자열 route가 주어질 때, 도착점의 위치를 return하도록 빈칸을 채워 solution함수를 완성해 주세요.
=> [77일차] 최한이 / 산책

3st/Juram/programmer/홀짝에 따라 다른 값 반환하기.java
=> [77일차] 홀짝에 따라 다른 값 반환하기 / Level.0

4st/Eunseong/n 번째 원소부터.java
https://school.programmers.co.kr/learn/courses/30/lessons/181892
| n 번째 원소부터 | 프로그래머스 | Level.0 |
<hr/>
=> [77일차] 공은성 / n 번째 원소부터

3st/Hajeong/programmer/n보다 커질 때까지 더하기.java, 프로그래머스/0/181884. n보다 커질 때까지 더하기/README.md, 프로그래머스/0/181884. n보다 커질 때까지 더하기/n보다 커질 때까지 더하기.java
<hr/>
- n보다 커질 때까지 더하기 : 정수 배열 numbers와 정수 n이 매개변수로 주어집니다. numbers의 원소를 앞에서부터 하나씩 더하다가 그 합이 n보다 커지는 순간 이때까지 더했던 원소들의 합을 return 하는 solution 함수를 작성해 주세요.
=> [77일차] 임하정 / n보다 커질 때까지 더하기

3st/Hyeonseo/programmer/문자열 정렬하기 (1).js, 3st/Hyeonseo/programmer/배열의 원소 삭제하기.js, 프로그래머스/0/181844. 배열의 원소 삭제하기/README.md, 프로그래머스/0/181844. 배열의 원소 삭제하기/배열의 원소 삭제하기.js
| 배열의 원소 삭제하기 | 프로그래머스 | Level.0 |
<hr/>
- 배열의 원소 삭제하기 : 정수 배열 arr과 delete_list가 있습니다. arr의 원소 중 delete_list의 원소를 모두 삭제하고 남은 원소들은 기존의 arr에 있던 순서를 유지한 배열을 return 하는 solution 함수를 작성해 주세요.
=> [265일차] 조현서 / 배열의 원소 삭제하기 

3st/Jaeyoung/A + B.c
| A + B | 백준 | 브론즈 V |
<hr/>
- A + B : Given two non-negative integers $A$ and $B$, compute $A + B$.
=> [266일차] 박재영 / A + B

4st/Seohyun/programmer/[PCCE 기출문제] 2번_각도 합치기.java, 4st/Seohyun/programmer/문자열 출력하기.java
| [PCCE 기출문제] 2번_ 각도 합치기 | 프로그래머스 | Level.0 |
<hr/>
- [PCCE 기출문제] 2번_ 각도 합치기 : 일반적으로 두 선분이 이루는 각도는 한 바퀴를 360도로 하여 표현합니다. 따라서 각도에 360의 배수를 더하거나 빼더라도 같은 각을 의미합니다. 예를 들면, 30도와 390도는 같은 각도입니다.
주어진 코드는 각도를 나타내는 두 정수 angle1과 angle2가 주어질 때, 이 두 각의 합을 0도 이상 360도 미만으로 출력하는 코드입니다. 코드가 올바르게 작동하도록 한 줄을 수정해 주세요.
=> [78일차] 이서현 / [PCCE 기출문제] 2번_ 각도 합치기

4st/Eunseong/카운트 업.java
https://school.programmers.co.kr/learn/courses/30/lessons/181920
<hr/>
=> [79일차] 공은성 / 카운트 업

4st/Seohyun/programmer/[PCCE 기출문제] 5번_심폐소생술.java
| [PCCE 기출문제] 5번_ 심폐소생술 | 프로그래머스 | Level.0 |
<hr/>
- [PCCE 기출문제] 5번_ 심폐소생술 : 심정지 및 무호흡 확인 [check]
도움 및 119 신고 요청 [call]
가슴압박 30회 시행 [pressure]
인공호흡 2회 시행 [respiration]
가슴압박, 인공호흡 반복 [repeat]
주어진 solution 함수는 심폐소생술을 하는 방법의 순서가 담긴 문자열들이 무작위 순서로 담긴 리스트 cpr이 주어질 때 각각의 방법이 몇 번째 단계인지 순서대로 담아 return하는 함수입니다. solution 함수가 올바르게 작동하도록 빈칸을 채워 solution 함수를 완성해 주세요.
=> [80일차] 이서현 / [PCCE 기출문제] 5번_ 심폐소생술

3st/Hyeonseo/programmer/순서쌍의 개수.py, 프로그래머스/0/120836. 순서쌍의 개수/README.md, 프로그래머스/0/120836. 순서쌍의 개수/순서쌍의 개수.py
=> [268일차] 조현서 / 순서쌍의 개수 

3st/Juram/programmer/l로 만들기.java
| l로 만들기 | 프로그래머스 | Level.0 |
<hr/>
- l로 만들기 : 알파벳 소문자로 이루어진 문자열 myString이 주어집니다. 알파벳 순서에서 "l"보다 앞서는 모든 문자를 "l"로 바꾼 문자열을 return 하는 solution 함수를 완성해 주세요.
=> [80일차] 김주람 / l로 만들기

4st/Eunseong/배열의 원소만큼 추가하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181861
| 배열의 원소만큼 추가하기 | 프로그래머스 |  Level.0 |
<hr/>
=> [81일차] 공은성 / 배열의 원소만큼 추가하기

4st/Hani/programmer/서울에서 김서방 찾기.java
https://school.programmers.co.kr/learn/courses/30/lessons/12919
| 서울에서 김서방 찾기 | 프로그래머스 | Level.1 |
<hr/>
- 서울에서 김서방 찾기 : String형 배열 seoul의 element중 "Kim"의 위치 x를 찾아, "김서방은 x에 있다"는 String을 반환하는 함수, solution을 완성하세요. seoul에 "Kim"은 오직 한 번만 나타나며 잘못된 값이 입력되는 경우는 없습니다.
=> [81일차] 최한이 / 서울에서 김서방 찾기

4st/Eunseong/연속된 수의 합.java
https://school.programmers.co.kr/learn/courses/30/lessons/120923
| 연속된 수의 합 | 프로그래머스 | Level.0 |
<hr/>
- 연속된 수의 합 : 연속된 세 개의 정수를 더해 12가 되는 경우는 3, 4, 5입니다. 두 정수 num과 total이 주어집니다. 연속된 수 num개를 더한 값이 total이 될 때, 정수 배열을 오름차순으로 담아 return하도록 solution함수를 완성해보세요.
=> [82일차] 공은성 / 연속된 수의 합

4st/Hani/programmer/뒤집힌 문자열.java
https://school.programmers.co.kr/learn/courses/30/lessons/120822
| 뒤집힌 문자열 | 프로그래머스 | Level.1 |
<hr/>
- 뒤집힌 문자열 : 문자열 my_string이 매개변수로 주어집니다. my_string을 거꾸로 뒤집은 문자열을 return하도록 solution 함수를 완성해주세요.
=> [83일차] 최한이 / 뒤집힌 문자열

4st/Hani/programmer/문자 반복 출력하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/120825
| 문자 반복 출력하기 | 프로그래머스 | Level.1 |
<hr/>
=> [84일차] 최한이 / 문자 반복 출력하기

3st/Hajeong/programmer/배열의 유사도.java, 프로그래머스/0/120899. 가장 큰 수 찾기/README.md, 프로그래머스/0/120899. 가장 큰 수 찾기/가장 큰 수 찾기.java, 프로그래머스/0/120903. 배열의 유사도/README.md, 프로그래머스/0/120903. 배열의 유사도/배열의 유사도.java
=> [84일차] 임하정 / 배열의 유사도

4st/Seohyun/programmer/[PCCE 기출문제] 4번_저축.java
| [PCCE 기출문제] 4번_저축 | 프로그래머스 | Level.0 |
<hr/>
- [PCCE 기출문제] 4번_저축 :
첫 달에 저축하는 금액을 나타내는 정수 start, 두 번째 달 부터 70만 원 이상 모일 때까지 매월 저축하는 금액을 나타내는 정수 before, 100만 원 이상 모일 때 까지 매월 저축하는 금액을 나타내는 정수 after가 주어질 때, 100만 원 이상을 모을 때까지 걸리는 개월 수를 출력하도록 빈칸을 채워 코드를 완성해 주세요.
=> [87일차] 이서현 / [PCCE 기출문제] 4번_저축

4st/Hani/programmer/배열 만들기 1.java
https://school.programmers.co.kr/learn/courses/30/lessons/181901
| 배열 만들기 1 | 프로그래머스 | Level.1 |
<hr/>
=> [87일차] 최한이 / 배열 만들기 1

4st/Seohyun/programmer/내적.java
| 내적 | 프로그래머스 | Level.0 |
<hr/>
- 내적 : 길이가 같은 두 1차원 정수 배열 a, b가 매개변수로 주어집니다. a와 b의 [내적]을 return 하도록 solution 함수를 완성해주세요.
=> [88일차] 이서현 / 내적

4st/Eunseong/코드 처리하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181932
| 코드 처리하기 | 프로그래머스 | Level.0 |
<hr/>
- 코드 처리하기 : 문자열 code가 주어집니다.
code를 앞에서부터 읽으면서 만약 문자가 "1"이면 mode를 바꿉니다. mode에 따라 code를 읽어가면서 문자열 ret을 만들어냅니다.
mode는 0과 1이 있으며, idx를 0 부터 code의 길이 - 1 까지 1씩 키워나가면서 code[idx]의 값에 따라 다음과 같이 행동합니다.
mode가 0일 때
code[idx]가 "1"이 아니면 idx가 짝수일 때만 ret의 맨 뒤에 code[idx]를 추가합니다.
code[idx]가 "1"이면 mode를 0에서 1로 바꿉니다.
mode가 1일 때
code[idx]가 "1"이 아니면 idx가 홀수일 때만 ret의 맨 뒤에 code[idx]를 추가합니다.
code[idx]가 "1"이면 mode를 1에서 0으로 바꿉니다.
문자열 code를 통해 만들어진 문자열 ret를 return 하는 solution 함수를 완성해 주세요.
단, 시작할 때 mode는 0이며, return 하려는 ret가 만약 빈 문자열이라면 대신 "EMPTY"를 return 합니다.
=> [88일차] 공은성 / 코드 처리하기

4st/Seohyun/programmer/음양 더하기.java
| 음양 더하기 | 프로그래머스 | Level.1 |
<hr/>
- 음양 더하기 : 어떤 정수들이 있습니다. 이 정수들의 절댓값을 차례대로 담은 정수 배열 absolutes와 이 정수들의 부호를 차례대로 담은 불리언 배열 signs가 매개변수로 주어집니다. 실제 정수들의 합을 구하여 return 하도록 solution 함수를 완성해주세요.
=> [89일차] 이서현 / 음양 더하기

3st/Juram/programmer/꼬리 문자열.js
<hr/>
- 꼬리 문자열 : 문자열들이 담긴 리스트가 주어졌을 때, 모든 문자열들을 순서대로 합친 문자열을 꼬리 문자열이라고 합니다. 꼬리 문자열을 만들 때 특정 문자열을 포함한 문자열은 제외시키려고 합니다. 예를 들어 문자열 리스트 ["abc", "def", "ghi"]가 있고 문자열 "ef"를 포함한 문자열은 제외하고 꼬리 문자열을 만들면 "abcghi"가 됩니다.
문자열 리스트 str_list와 제외하려는 문자열 ex가 주어질 때, str_list에서 ex를 포함한 문자열을 제외하고 만든 꼬리 문자열을 return하도록 solution 함수를 완성해주세요.
=> [89일차] 김주람 / 꼬리 문자열

3st/Juram/programmer/0 떼기.js
| 0 떼기 | 프로그래머스 | Level.0 |
<hr/>
- 0 떼기 : 정수로 이루어진 문자열 n_str이 주어질 때, n_str의 가장 왼쪽에 처음으로 등장하는 0들을 뗀 문자열을 return하도록 solution 함수를 완성해주세요.
=> [90일차] 김주람 / 0 떼기

3st/Juram/programmer/마지막 두 원소.js, 3st/Juram/programmer/정수 찾기.js
| 마지막 두 원소 | 프로그래머스 | Level.0 |
<hr/>
=> [91일차] 김주람 / 마지막 두 원소 외 1개

4st/Eunseong/원소들의 곱과 합.java
https://school.programmers.co.kr/learn/courses/30/lessons/181929
<hr/>
=> [91일차] 공은성 / 원소들의 곱과 합

4st/Eunseong/수열과 구간 쿼리 (3).java
https://school.programmers.co.kr/learn/courses/30/lessons/181924
| 수열과 구관 쿼리 (3) | 프로그래머스 | Level.0 |
<hr/>
- 수열과 구간 쿼리 (3) : 정수 배열 arr와 2차원 정수 배열 queries이 주어집니다. queries의 원소는 각각 하나의 query를 나타내며, [i, j] 꼴입니다.
각 query마다 순서대로 arr[i]의 값과 arr[j]의 값을 서로 바꿉니다.
=> [92일차] 공은성 / 수열과 구간 쿼리 (3)

3st/Juram/programmer/숫자 찾기.js
=> [93일차] 김주람 / 숫자 찾기

4st/Eunseong/문자열 바꿔서 찾기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181864
<hr/>
=> [95일차] 공은성 / 문자열 바꿔서 찾기

4st/Seohyun/programmer/편지.java
<hr/>
- 편지 : 머쓱이는 할머니께 생신 축하 편지를 쓰려고 합니다. 할머니가 보시기 편하도록 글자 한 자 한 자를 가로 2cm 크기로 적으려고 하며, 편지를 가로로만 적을 때, 축하 문구 message를 적기 위해 필요한 편지지의 최소 가로길이를 return 하도록 solution 함수를 완성해주세요.
=> [96일차] 이서현 / 편지

4st/Gau/baekjoon/A+B - 3.java, 4st/Gau/baekjoon/나머지.java, 4st/Gau/baekjoon/빠른 A+B.java, 4st/Gau/baekjoon/윤년.java, 4st/Gau/baekjoon/합.java, 4st/Gau/programmer/나머지 구하기.java, 4st/Gau/programmer/문자열 붙여서 출력하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181946#qna
<hr/>
- 문자열 붙여서 출력하기 :두 개의 문자열 str1, str2가 공백으로 구분되어 입력으로 주어집니다.
=> [PGS] 노가우 / 96일차 / 문자열 붙여서 출력하기

3st/Jaeyoung/엄청난 부자2.cpp
| 엄청난 부자2 | 백준 | 브론즈 V |
<hr/>
- 엄청난 부자2 : 갑부 최백준 조교는 동전을 최소로 바꾸는데 성공했으나 김재홍 조교가 그 돈을 발견해서 최백준 조교에게 그 돈을 나누자고 따진다.
그 사실이 전 우주로 알려지자 우주에 있던 많은 생명체들이 자신들에게 돈을 분배해 달라고 당장 달려오기 시작했다.
프로토스 중앙 우주 정부의 정책인, ‘모든 지적 생명체는 동등하다’라는 규칙에 입각해서 돈을 똑같이 분배하고자 한다.
한 생명체에게 얼마씩 돈을 줄 수 있는가?
또, 생명체들에게 동일하게 분배한 후 남는 돈은 얼마인가?
=> [284일차] 박재영 / 엄청난 부자2

4st/Seohyun/programmer/배열 원소의 길이.java
<hr/>
- 배열 원소의 길이 : 문자열 배열 strlist가 매개변수로 주어집니다. strlist 각 원소의 길이를 담은 배열을 return하도록 solution 함수를 완성해주세요.
=> [97일차] 이서현 / 배열 원소의 길이

3st/Jaeyoung/사파리월드.cpp
| 사파리월드 | 백준 | 브론즈 V |
<hr/>
- 사파리월드 : 사파리월드는 인터넷으로만 존재하는 미스테리한 나라이다. 사파리월드에는 2개의 서브도메인이 seunghwan.royal.gov.sw와 kyuhyun.royal.gov.sw 이 있는데, 이것이 couple.royal.gov.sw으로 합쳐질 것이다. 그러나 도메인 관리 센터 SWNIC(센터장: 김동규)에는 엄격한 룰이 있다. 두 서브도메인을 합칠 때, 유명도의 차이가 너무 차이나지 않을 경우에만 두 서브도메인을 결혼시키는 것이다. 서브도메인의 유명도는 정수이다. 두 서브도메인의 유명도가 주어졌을 때, 그 차이를 구하는 프로그램을 작성하시오.
=> [287일차] 박재영 / 사파리월드

4st/Gau/programmer/n의 배수.java, 4st/Gau/programmer/문자열 돌리기.java
=> [PGS] 노가우 / 100일차 / 문자열 곱하기

프로그래머스/1/59036. 아픈 동물 찾기/README.md, 프로그래머스/1/59036. 아픈 동물 찾기/아픈 동물 찾기.sql
| 아픈 동물 찾기 | 프로그래머스 | Level.1 |
<hr/>
- 아픈 동물 찾기 : 동물 보호소에 들어온 동물 중 아픈 동물의 아이디와 이름을 조회하는 SQL 문을 작성해주세요. 이때 결과는 아이디 순으로 조회해주세요.
=> [100일차] 최한이 / 아픈 동물 찾기

4st/Eunseong/배열 만들기 2.java
https://school.programmers.co.kr/learn/courses/30/lessons/181921
| 배열 만들기 2 | 프로그래머스 | Level.0 |
<hr/>
- 배열 만들기 2 : 정수 l과 r이 주어졌을 때, l 이상 r이하의 정수 중에서 숫자 "0"과 "5"로만 이루어진 모든 정수를 오름차순으로 저장한 배열을 return 하는 solution 함수를 완성해 주세요.
만약 그러한 정수가 없다면, -1이 담긴 배열을 return 합니다.
=> [102일차] 공은성 / 배열 만들기 2

3st/Juram/programmer/암호 해독.js
| 암호 해독 | 프로그래머스 | Level.0 |
<hr/>
- 암호 해독 : 군 전략가 머쓱이는 전쟁 중 적군이 다음과 같은 암호 체계를 사용한다는 것을 알아냈습니다.
암호화된 문자열 cipher를 주고받습니다.
그 문자열에서 code의 배수 번째 글자만 진짜 암호입니다.
문자열 cipher와 정수 code가 매개변수로 주어질 때 해독된 암호 문자열을 return하도록 solution 함수를 완성해주세요.
=> [102일차] 김주람 / 암호 해독

4st/Gau/자바방학숙제/Accumulate_1304_0723.java, 4st/Gau/자바방학숙제/Attendance_1304_0724.java
https://school.programmers.co.kr/learn/courses/30/lessons/181943
| 문자열 겹쳐쓰기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 겹쳐쓰기 : 문자열 my_string, overwrite_string과 정수 s가 주어집니다. 문자열 my_string의 인덱스 s부터 overwrite_string의 길이만큼을 문자열 overwrite_string으로 바꾼 문자열을 return 하는 solution 함수를 작성해 주세요.
=>  [PGS] 노가우 / 102일차 / 문자열 겹쳐쓰기

3st/Jaehee/문자열로 변환.py
https://school.programmers.co.kr/learn/challenges?order=recent&page=1&levels=0&languages=javascript
| 문자열로 변환 | 프로그래머스 | Level.0 |
<hr/>
- 문자열로 변환 : 정수 n이 주어질 때, n을 문자열로 변환하여 return하도록 solution 함수를 완성해주세요.
=> [291일] 이제희/문자열로 변환

3st/Juram/programmer/문자열 정렬하기 (2).js
=> [103일차] 김주람 / 문자열 정렬하기 (2)

4st/Eunseong/배열의 원소 삭제하기.py
https://school.programmers.co.kr/learn/courses/30/lessons/181844
| 배열의 원소 삭제하기 | 프로그래머스 | Level.0 |
<hr/>
- 배열의 원소 삭제하기: 정수 배열 arr과 delete_list가 있습니다. arr의 원소 중 delete_list의 원소를 모두 삭제하고 남은 원소들은 기존의 arr에 있던 순서를 유지한 배열을 return 하는 solution 함수를 작성해 주세요.
=> [103일차] 공은성 / 배열의 원소 삭제하기

3st/Jaeyoung/단어 길이 재기.cpp
| 단어 길이 재기 | 백준 | 브론즈 V |
<hr/>
- 단어 길이 재기 : 알파벳으로만 이루어진 단어를 입력받아, 그 길이를 출력하는 프로그램을 작성하시오.
=> [291일차] 박재영 / 단어 길이 재기

3st/Hyeonseo/programmer/공 던지기.py
https://school.programmers.co.kr/learn/courses/30/lessons/120843
| 공 던지기 | 프로그래머스 | Level.0 |
<hr/>
- 공 던지기 : 머쓱이는 친구들과 동그랗게 서서 공 던지기 게임을 하고 있습니다. 공은 1번부터 던지며 오른쪽으로 한 명을 건너뛰고 그다음 사람에게만 던질 수 있습니다. 친구들의 번호가 들어있는 정수 배열 numbers와 정수 K가 주어질 때, k번째로 공을 던지는 사람의 번호는 무엇인지 return 하도록 solution 함수를 완성해보세요.
=> [292일차] 조현서 / 공 던지기 

3st/Juram/programmer/부분 문자열.js
<hr/>
- 부분 문자열 : 어떤 문자열 A가 다른 문자열 B안에 속하면 A를 B의 부분 문자열이라고 합니다. 예를 들어 문자열 "abc"는 문자열 "aabcc"의 부분 문자열입니다.
문자열 str1과 str2가 주어질 때, str1이 str2의 부분 문자열이라면 1을 부분 문자열이 아니라면 0을 return하도록 solution 함수를 완성해주세요.
=> [104일차] 김주람 / 부분 문자열

4st/Hani/programmer/어린 동물 찾기.sql, 프로그래머스/1/59037. 어린 동물 찾기/README.md, 프로그래머스/1/59037. 어린 동물 찾기/어린 동물 찾기.sql
| 어린 동물 찾기 | 프로그래머스 | Level.1 |
<hr/>
- 어린 동물 찾기 : ANIMAL_INS 테이블은 동물 보호소에 들어온 동물의 정보를 담은 테이블입니다. ANIMAL_INS 테이블 구조는 다음과 같으며, ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE는 각각 동물의 아이디, 생물 종, 보호 시작일, 보호 시작 시 상태, 이름, 성별 및 중성화 여부를 나타냅니다.동물 보호소에 들어온 동물 중 젊은 동물[1]의 아이디와 이름을 조회하는 SQL 문을 작성해주세요. 이때 결과는 아이디 순으로 조회해주세요.
=> [106일차] 최한이 / 어린 동물 찾기

프로그래머스/1/132201. 12세 이하인 여자 환자 목록 출력하기/12세 이하인 여자 환자 목록 출력하기.sql, 프로그래머스/1/132201. 12세 이하인 여자 환자 목록 출력하기/README.md, 프로그래머스/2/131533. 상품 별 오프라인 매출 구하기/README.md, 프로그래머스/2/131533. 상품 별 오프라인 매출 구하기/상품 별 오프라인 매출 구하기.sql, 프로그래머스/2/144854. 조건에 맞는 도서와 저자 리스트 출력하기/README.md, 프로그래머스/2/144854. 조건에 맞는 도서와 저자 리스트 출력하기/조건에 맞는 도서와 저자 리스트 출력하기.sql
| 12세 이하인 여자 환자 목록 출력하기 | 프로그래머스 | Level.1 |
<hr/>
- 12세 이하인 여자 환자 목록 출력하기 : PATIENT 테이블에서 12세 이하인 여자환자의 환자이름, 환자번호, 성별코드, 나이, 전화번호를 조회하는 SQL문을 작성해주세요. 이때 전화번호가 없는 경우, 'NONE'으로 출력시켜 주시고 결과는 나이를 기준으로 내림차순 정렬하고, 나이 같다면 환자이름을 기준으로 오름차순 정렬해주세요.
=> [107일차] 최한이 / 12세 이하인 여자 환자 목록 출력하기

3st/Juram/programmer/대문자로 바꾸기.js
=> [107일차] 김주람 / 대문자로 바꾸기

4st/Eunseong/대문자로 바꾸기.java, 4st/Eunseong/문자열 뒤집기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181905
<hr/>
- 문자열 뒤집기 : 문자열 my_string과 정수 s, e가 매개변수로 주어질 때, my_string에서 인덱스 s부터 인덱스 e까지를 뒤집은 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [107일차] 공은성 / 문자열 뒤집기

4st/Eunseong/하샤드 수.java
https://school.programmers.co.kr/learn/courses/30/lessons/12947
| 하샤드 수 | 프로그래머스 | Level.1 |
<hr/>
- 하샤드 수 : 양의 정수 x가 하샤드 수이려면 x의 자릿수의 합으로 x가 나누어져야 합니다. 예를 들어 18의 자릿수 합은 1+8=9이고, 18은 9로 나누어 떨어지므로 18은 하샤드 수입니다. 자연수 x를 입력받아 x가 하샤드 수인지 아닌지 검사하는 함수, solution을 완성해주세요.
=> [108일차] 공은성 / 하샤드 수

4st/Hani/programmer/이름이 있는 동물의 아이디.sql, 프로그래머스/2/273709. 조건에 맞는 아이템들의 가격의 총합 구하기/README.md, 프로그래머스/2/273709. 조건에 맞는 아이템들의 가격의 총합 구하기/조건에 맞는 아이템들의 가격의 총합 구하기.sql
https://school.programmers.co.kr/learn/courses/30/lessons/59407
| 이름이 있는 동물의 아이디 | 프로그래머스 | Level.1 |
<hr/>
- 이름이 있는 동물의 아이디 : 동물 보호소에 들어온 동물 중, 이름이 있는 동물의 ID를 조회하는 SQL 문을 작성해주세요. 단, ID는 오름차순 정렬되어야 합니다.
=> [110일차] 최한이 / 이름이 있는 동물의 아이디

3st/Hyeonseo/programmer/개미 군단.py, 3st/Hyeonseo/programmer/이진 변환 반복하기.py, 3st/Jaeyoung/상근이의 친구들.cpp, 3st/Jaeyoung/카드 게임.cpp, 3st/Juram/programmer/배열 비교하기.js, 4st/Eunseong/x 사이의 개수.java, 4st/Eunseong/수열과 구간 쿼리 4.java, 4st/Hani/programmer/이름이 있는 동물의 아이디.sql, 4st/Hani/programmer/조건에 맞는 아이템들의 가격의 총합 구하기.sql, 프로그래머스/2/273709. 조건에 맞는 아이템들의 가격의 총합 구하기/README.md, 프로그래머스/2/273709. 조건에 맞는 아이템들의 가격의 총합 구하기/조건에 맞는 아이템들의 가격의 총합 구하기.sql, 프로그래머스/2/70129. 이진 변환 반복하기/README.md, 프로그래머스/2/70129. 이진 변환 반복하기/이진 변환 반복하기.py
| 이진 변환 반환하기 | 프로그래머스 | Level.2 |
<hr/>
- 이진 변환 반환하기 : 0과 1로 이루어진 어떤 문자열 x에 대한 이진 변환을 다음과 같이 정의합니다.
x의 모든 0을 제거합니다.
x의 길이를 c라고 하면, x를 "c를 2진법으로 표현한 문자열"로 바꿉니다.
예를 들어, x = "0111010"이라면, x에 이진 변환을 가하면 x = "0111010" -> "1111" -> "100" 이 됩니다.
0과 1로 이루어진 문자열 s가 매개변수로 주어집니다. s가 "1"이 될 때까지 계속해서 s에 이진 변환을 가했을 때, 이진 변환의 횟수와 변환 과정에서 제거된 모든 0의 개수를 각각 배열에 담아 return 하도록 solution 함수를 완성해주세요.
=> [300일차] 조현서 / 이진 변환 반환하기 

4st/Eunseong/문자열 여러 번 뒤집기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181913
| 문자열 여러 번 뒤집기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 여러 번 뒤집기 : 문자열 my_string과 이차원 정수 배열 queries가 매개변수로 주어집니다. queries의 원소는 [s, e] 형태로, my_string의 인덱스 s부터 인덱스 e까지를 뒤집으라는 의미입니다. my_string에 queries의 명령을 순서대로 처리한 후의 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [112일차] 공은성 / 문자열 여러 번 뒤집기

4st/Eunseong/qr code.java
https://school.programmers.co.kr/learn/courses/30/lessons/181903
| qr code | 프로그래머스 | Level.0 |
<hr/>
- qr code : 두 정수 q, r과 문자열 code가 주어질 때, code의 각 인덱스를 q로 나누었을 때 나머지가 r인 위치의 문자를 앞에서부터 순서대로 이어 붙인 문자열을 return 하는 solution 함수를 작성해 주세요.
=> [113일차] 공은성 / qr code

4st/Gau/baekjoon/A+B-8.java, 4st/Gau/programmer/더크게합치기.java
https://school.programmers.co.kr/learn/courses/30/lessons/181938
| 두 수의 연산값 비교하기 | 프로그래머스 | Level.0 |
<hr/>
12 ⊕ 3 = 123
3 ⊕ 12 = 312
=> [PGS] 노가우 / 114일차 / 두 수의 연산값 비교하기

4st/Hani/programmer/상위 n개 레코드.sql, 프로그래머스/2/59041. 동명 동물 수 찾기/README.md, 프로그래머스/2/59041. 동명 동물 수 찾기/동명 동물 수 찾기.undefined
https://school.programmers.co.kr/learn/courses/30/lessons/59405
| 상위 n개 레코드  | 프로그래머스 | Level.1 |
<hr/>
- 상위 n개 레코드  : 동물 보호소에 가장 먼저 들어온 동물의 이름을 조회하는 SQL 문을 작성해주세요.
=> [114일차] 최한이 / 상위 n개 레코드 

3st/Juram/programmer/문자열 바꿔서 찾기.js
https://school.programmers.co.kr/learn/courses/30/lessons/181864
<hr/>
=> [114일차] 김주람 / 문자열 바꿔서 찾기

4st/Jisoo/programmer/중복된 숫자 개수.java
https://school.programmers.co.kr/learn/courses/30/lessons/120583
<hr/>
=> [115일차] 임지수 / 중복된 숫자 개수

3st/Juram/programmer/뒤에서 5등까지.js
=> [115일차] 김주람 / 뒤에서 5등까지

4st/Eunseong/배열 만들기 5.java
https://school.programmers.co.kr/learn/courses/30/lessons/181912
| 배열 만들기 5 | 프로그래머스 | Level.0 |
<hr/>
- 배열 만들기 5 : 문자열 배열 intStrs와 정수 k, s, l가 주어집니다. intStrs의 원소는 숫자로 이루어져 있습니다.
배열 intStrs의 각 원소마다 s번 인덱스에서 시작하는 길이 l짜리 부분 문자열을 잘라내 정수로 변환합니다. 이때 변환한 정수값이 k보다 큰 값들을 담은 배열을 return 하는 solution 함수를 완성해 주세요.
=> [115일차] 공은성 / 배열 만들기 5

4st/Seohyun/programmer/최댓값 만들기(1).c
| 최댓값 만들기(1) | 프로그래머스 | Level.1 |
<hr/>
=> [117일차] 이서현 / 최댓값 만들기(1)

3st/Jaeyoung/문자열.cpp
| 문자열 | 백준 | 브론즈 V |
<hr/>
- 문자열 : 문자열을 입력으로 주면 문자열의 첫 글자와 마지막 글자를 출력하는 프로그램을 작성하시오.
=> [305일차] 박재영 / 문자열

3st/Juram/programmer/공백으로 구분하기 1.js
| 공백으로 구분하기 1 | 프로그래머스 | Level.0 |
<hr/>
- 공백으로 구분하기 1 : 단어가 공백 한 개로 구분되어 있는 문자열 my_string이 매개변수로 주어질 때, my_string에 나온 단어를 앞에서부터 순서대로 담은 문자열 배열을 return 하는 solution 함수를 작성해 주세요.
=> [117일차] 김주람 / 공백으로 구분하기 1

4st/Eunseong/2의 영역.java
https://school.programmers.co.kr/learn/courses/30/lessons/181894
| 2의 영역 | 프로그래머스 | Level.0 |
<hr/>
- 2의 영역 : 정수 배열 arr가 주어집니다. 배열 안의 2가 모두 포함된 가장 작은 연속된 부분 배열을 return 하는 solution 함수를 완성해 주세요.
단, arr에 2가 없는 경우 [-1]을 return 합니다.
=> [118일차] 공은성 / 2의 영역

3st/Juram/programmer/문자열을 정수로 변환하기.js
<hr/>
- 문자열을 정수로 변환하기 : 숫자로만 이루어진 문자열 n_str이 주어질 때, n_str을 정수로 변환하여 return하도록 solution 함수를 완성해주세요.
=> [118일차] 김주람 / 문자열을 정수로 변환하기

3st/Jaeyoung/큰 수 A+B.cpp
| 큰 수 A+B | 백준 | 브론즈 V |
<hr/>
- 큰 수 A+B : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [307일차] 박재영 / 큰 수 A+B

3st/Juram/programmer/대문자와 소문자.js
=> [119일차] 김주람 / 대문자와 소문자

3st/Juram/programmer/콜라츠 수열 만들기.js
=> [120일차] 김주람 / 콜라츠 수열 만들기

4st/Seohyun/programmer/아이스 아메리카노.c
=> [120일차] 이서현 / 아이스 아메리카노

4st/Seohyun/programmer/순서쌍의 개수.java
=> [121] 이서현 / 순서쌍의 개수

4st/Hani/programmer/공배수.java
https://school.programmers.co.kr/learn/courses/30/lessons/181936
| 공배수 | 프로그래머스 | Level.0 |
<hr/>
=> [121일차] 최한이 / 공배수

4st/Hani/programmer/이름에 el이 들어가는 동물 찾기.sql
https://school.programmers.co.kr/learn/courses/30/lessons/59047
| 이름에 el이 들어가는 동물 찾기 | 프로그래머스 | Level.2 |
<hr/>
- 이름에 el이 들어가는 동물 찾기 : 보호소에 돌아가신 할머니가 기르던 개를 찾는 사람이 찾아왔습니다. 이 사람이 말하길 할머니가 기르던 개는 이름에 'el'이 들어간다고 합니다. 동물 보호소에 들어온 동물 이름 중, 이름에 "EL"이 들어가는 개의 아이디와 이름을 조회하는 SQL문을 작성해주세요. 이때 결과는 이름 순으로 조회해주세요. 단, 이름의 대소문자는 구분하지 않습니다.
=> [123일차] 최한이 / 이름에 el이 들어가는 동물 찾기

3st/Jaeyoung/X보다 작은 수.cpp
| X보다 작은 수 | 백준 | 브론즈 V |
<hr/>
- X보다 작은 수 : 정수 N개로 이루어진 수열 A와 정수 X가 주어진다. 이때, A에서 X보다 작은 수를 모두 출력하는 프로그램을 작성하시오.
=> [311일차] 박재영 / X보다 작은 수

4st/Eunseong/수열과 구간 쿼리 1.java
https://school.programmers.co.kr/learn/courses/30/lessons/181883
<hr/>
- 수열과 구간 쿼리 : 정수 배열 arr와 2차원 정수 배열 queries이 주어집니다. queries의 원소는 각각 하나의 query를 나타내며, [s, e] 꼴입니다.
=> [124일차] 공은성 / 수열과 구간 쿼리 1

프로그래머스/0/120836. 순서쌍의 개수/README.md, 프로그래머스/0/120836. 순서쌍의 개수/순서쌍의 개수.java
=> [124일차] 임하정 / 순서쌍의 개수

3st/Jaeyoung/팬들에게 둘러싸인 홍준.cpp
| 팬들에게 둘러싸인 홍준 | 백준 | 브론즈 V |
<hr/>
- 팬들에게 둘러싸인 홍준 : 홍준은 참 팬이 많다. 이를 본 구사과는 BOJ 슬랙에서 이모티콘을 만들었다.
=> [312일차] 박재영 / 팬들에게 둘러싸인 홍준

3st/Jaeyoung/A+B - 7.cpp
| A+B - 7 | 백준 | 브론즈 V |
<hr/>
- A+B - 7 : 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
=> [314일차] 박재영 / A+B - 7

3st/Juram/programmer/문자열 묶기.js
| 문자열 묶기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 묶기 : 문자열 배열 strArr이 주어집니다. strArr의 원소들을 길이가 같은 문자열들끼리 그룹으로 묶었을 때 가장 개수가 많은 그룹의 크기를 return 하는 solution 함수를 완성해 주세요.
=> [127일차] 김주람 / 문자열 묶기

3st/Jaeyoung/CAPS.cpp
| CAPS | 백준 | 브론즈 V |
<hr/>
- CAPS : Earth is under attack! Messages need to be sent to the Earth Defense Force (EDF) that makes clear that the situation is dire. The EDF’s strongest forces consist of mechs (huge bipedal robots) that are piloted by Japanese teenagers. To make sure that the messages come across as urgent, they must be displayed on the monitors of the pilots in uppercase letters. Unfortunately, the tachyon communication system that is used by the EDF is only able to send strings in lower-case alphabetic characters.
The set of lower-case alphabetic characters is made up of the following characters: ’a’, ’b’, ’c’, ’d’, ’e’, ’f’, ’g’, ’h’, ’i’, ’j’, ’k’, ’l’, ’m’, ’n’, ’o’, ’p’, ’q’, ’r’, ’s’, ’t’, ’u’, ’v’, ’w’, ’x’, ’y’, ’z’. …
=> [315일차] 박재영 / CAPS

3st/Juram/programmer/중복된 문자 제거.js
| 중복된 문자 제거 | 프로그래머스 | Level.0 |
<hr/>
- 중복된 문자 제거 : 문자열 my_string이 매개변수로 주어집니다. my_string에서 중복된 문자를 제거하고 하나의 문자만 남긴 문자열을 return하도록 solution 함수를 완성해주세요.
=> [128일차] 김주람 / 중복된 문자 제거

4st/Seohyun/programmer/배열 만들기 1.java
=> [128일차] 이서현 / 배열 만들기 1

4st/Hani/programmer/Python 개발자 찾기.sql, 프로그래머스/1/131535. 조건에 맞는 회원수 구하기/README.md, 프로그래머스/1/131535. 조건에 맞는 회원수 구하기/조건에 맞는 회원수 구하기.sql, 프로그래머스/1/133024. 인기있는 아이스크림/README.md, 프로그래머스/1/133024. 인기있는 아이스크림/인기있는 아이스크림.sql, 프로그래머스/2/131529. 카테고리 별 상품 개수 구하기/README.md, 프로그래머스/2/131529. 카테고리 별 상품 개수 구하기/카테고리 별 상품 개수 구하기.sql, 프로그래머스/2/59408. 중복 제거하기/README.md, 프로그래머스/2/59408. 중복 제거하기/중복 제거하기.sql, 프로그래머스/2/59409. 중성화 여부 파악하기/README.md, 프로그래머스/2/59409. 중성화 여부 파악하기/중성화 여부 파악하기.sql
https://school.programmers.co.kr/learn/courses/30/lessons/276013
| Python 개발자 찾기 | 프로그래머스 | Level.1 |
<hr/>
- Python 개발자 찾기 : DEVELOPER_INFOS 테이블에서 Python 스킬을 가진 개발자의 정보를 조회하려 합니다. Python 스킬을 가진 개발자의 ID, 이메일, 이름, 성을 조회하는 SQL 문을 작성해 주세요.
결과는 ID를 기준으로 오름차순 정렬해 주세요.
=> [128일차] 최한이 / Python 개발자 찾기

3st/Jaeyoung/Rectangles.cpp
| Rectangles | 백준 | 브론즈 V |
<hr/>
- Rectangles : Read two integer numbers R and C from the standard input and then print R lines with C asterisks (*) each.
Example (R=3, C=5):
```
*****
*****
*****
```
Example (R=2, C=10):
```
**********
**********
```
=> [316일차] 박재영 / Rectangles

3st/Jaeyoung/연세대학교.cpp
| 연세대학교 | 백준 | 브론즈 V |
<hr/>
- 연세대학교 : 연세대학교의 영문명은 YONSEI, 슬로건은 Leading the Way to the Future이다.
이를 출력하는 프로그램을 작성해보도록 하자.
=> [317일차] 박재영 / 연세대학교

3st/Juram/programmer/간단한 식 계산하기.js
=> [130일차] 김주람 / 간단한 식 계산하기

3st/Jaeyoung/새로운 시작.cpp
| 새로운 시작 | 백준 | 브론즈 V |
<hr/>
- 새로운 시 : 부산일과학고등학교는 태어난지 얼마 안 된 킹-갓 과학고등학교다. 우리들을 위해 응원의 한마디를 출력하자.
=> [319일차] 박재영 / 새로운 시작

4st/Hani/programmer/조건에 맞는 회원수 구하기.sql
https://school.programmers.co.kr/learn/courses/30/lessons/131535
| 조건에 맞는 회원수 구하기 | 프로그래머스 | Level.1 |
<hr/>
- 조건에 맞는 회원수 구하기 : USER_INFO 테이블에서 2021년에 가입한 회원 중 나이가 20세 이상 29세 이하인 회원이 몇 명인지 출력하는 SQL문을 작성해주세요.
=> [131일차] 최한이 / 조건에 맞는 회원수 구하기

4st/Hani/programmer/평균 일일 대여 요금 구하기.sql, 프로그래머스/1/151136. 평균 일일 대여 요금 구하기/README.md, 프로그래머스/1/151136. 평균 일일 대여 요금 구하기/평균 일일 대여 요금 구하기.sql, 프로그래머스/1/293258. 잔챙이 잡은 수 구하기/README.md, 프로그래머스/1/293258. 잔챙이 잡은 수 구하기/잔챙이 잡은 수 구하기.sql
| 평균 일일 대여 요금 구하기 | 프로그래머스 | Level.1 |
<hr/>
- 평균 일일 대여 요금 구하기 : CAR_RENTAL_COMPANY_CAR 테이블에서 자동차 종류가 'SUV'인 자동차들의 평균 일일 대여 요금을 출력하는 SQL문을 작성해주세요. 이때 평균 일일 대여 요금은 소수 첫 번째 자리에서 반올림하고, 컬럼명은 AVERAGE_FEE 로 지정해주세요.
=> [132일차] 최한이 / 평균 일일 대여 요금 구하기

3st/Jaeyoung/이상한 기호.cpp
| 이상한 기호 | 백준 | 브론즈 V |
<hr/>
- 이상한 기호 : 부산일과학고등학교의 효진이는 수학의 귀재이다. 어떤 문제라도 보면 1분 내에 풀어버린다는 학교의 전설이 내려올 정도였는데, 이런 킹ㅡ갓 효진에게도 고민이 생겼다. 대부분의 문제에서 반복되는 연산이 있었기 때문이다! 이 연산은 너무 길어서 종이에 풀던 효진이는 너무 고통스러워서, 자신이 새로 연산자를 만들기로 했다.
연산자의 기호는 ＠으로, A＠B = (A+B)×(A-B)으로 정의내리기로 했다.
하지만, 효진이는 막상 큰 숫자가 들어오자 계산하기 너무 귀찮아졌다.
효진이를 도와 정수 A, B가 주어지면 A＠B를 계산하는 프로그램을 만들어주자!
=> [321일차] 박재영 / 이상한 기호

4st/Seohyun/programmer/가장 큰 수 찾기.java, 4st/Seohyun/programmer/약수 구하기.java
=> [133일차] 이서현 / 약수 구하기

4st/Eunseong/두 개 뽑아서 더하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/68644
| 두 개 뽑아서 더하기 | 프로그래머스 | Level.1 |
<hr/>
- 두 개 뽑아서 더하기 : 정수 배열 numbers가 주어집니다. numbers에서 서로 다른 인덱스에 있는 두 개의 수를 뽑아 더해서 만들 수 있는 모든 수를 배열에 오름차순으로 담아 return 하도록 solution 함수를 완성해주세요.
=> [134일차] 공은성 / 두 개 뽑아서 더하기

3st/Jaeyoung/제리와 톰.cpp
| 제리와 톰 | 백준 | 브론즈 V |
<hr/>
- 제리와 톰 : 톰은 마트에서 치즈 1kg 을 사서 집으로 돌아왔습니다.
그런데 톰이 한눈을 판 사이 제리가 와서 A/B kg 만큼 훔쳐갔습니다.
제리가 치즈를 훔쳐 간 후 톰이 가지고 있는 치즈의 무게는 얼마인가요?
=> [322일차] 박재영 / 제리와 톰

4st/Hani/programmer/과일로 만든 아이스크림 고르기.sql
https://school.programmers.co.kr/learn/courses/30/lessons/133025
| 과일로 만든 아이스크림 고르기 | 프로그래머스 | Level.1 |
<hr/>
- 과일로 만든 아이스크림 고르기 : 상반기 아이스크림 총주문량이 3,000보다 높으면서 아이스크림의 주 성분이 과일인 아이스크림의 맛을 총주문량이 큰 순서대로 조회하는 SQL 문을 작성해주세요.
=> [135일차] 최한이 / 과일로 만든 아이스크림 고르기

4st/Hani/programmer/잔챙이 잡은 수 구하기.sql
https://school.programmers.co.kr/learn/courses/30/lessons/293258
| 잔챙이 잡은 수 구하기 | 프로그래머스 | Level.1 |
<hr/>
- 잔챙이 잡은 수 구하기 : 잡은 물고기 중 길이가 10cm 이하인 물고기의 수를 출력하는 SQL 문을 작성해주세요.
물고기의 수를 나타내는 컬럼 명은 FISH_COUNT로 해주세요.
=> [136일차] 최한이 / 잔챙이 잡은 수 구하기

4st/Eunseong/직사각형 별찍기.java
https://school.programmers.co.kr/learn/courses/30/lessons/12969
| 직사각형 별찍기 | 프로그래머스 | Level.1 |
<hr/>
- 직사각형 별찍기 : 이 문제에는 표준 입력으로 두 개의 정수 n과 m이 주어집니다.
별(*) 문자를 이용해 가로의 길이가 n, 세로의 길이가 m인 직사각형 형태를 출력해보세요.
=> [136일차] 공은성 / 직사각형 별찍기

3st/Jaeyoung/분산처리.cpp
| 분산처리 | 백준 | 브론즈 V |
<hr/>
- 분산처리 : 재용이는 최신 컴퓨터 10대를 가지고 있다. 어느 날 재용이는 많은 데이터를 처리해야 될 일이 생겨서 각 컴퓨터에 1번부터 10번까지의 번호를 부여하고, 10대의 컴퓨터가 다음과 같은 방법으로 데이터들을 처리하기로 하였다.
1번 데이터는 1번 컴퓨터, 2번 데이터는 2번 컴퓨터, 3번 데이터는 3번 컴퓨터, ... ,
10번 데이터는 10번 컴퓨터, 11번 데이터는 1번 컴퓨터, 12번 데이터는 2번 컴퓨터, ...
총 데이터의 개수는 항상 ab개의 형태로 주어진다. 재용이는 문득 마지막 데이터가 처리될 컴퓨터의 번호가 궁금해졌다. 이를 수행해주는 프로그램을 작성하라.
=> [326일차] 박재영 / 분산처리

3st/Juram/programmer/외계행성의 나이.js
| 외계행성의 나이 | 프로그래머스 | Level.0 |
<hr/>
- 외계행성의 나이 : 우주여행을 하던 머쓱이는 엔진 고장으로 PROGRAMMERS-962 행성에 불시착하게 됐습니다. 입국심사에서 나이를 말해야 하는데, PROGRAMMERS-962 행성에서는 나이를 알파벳으로 말하고 있습니다. a는 0, b는 1, c는 2, ..., j는 9입니다. 예를 들어 23살은 cd, 51살은 fb로 표현합니다. 나이 age가 매개변수로 주어질 때 PROGRAMMER-962식 나이를 return하도록 solution 함수를 완성해주세요.
=> [139일차] 김주람 / 외계행성의 나이

4st/Hani/programmer/가장 큰 물고기 10마리 구하기.sql, 4st/Hani/programmer/모든 레코드 조회하기.sql
https://school.programmers.co.kr/learn/courses/30/lessons/298517
| 가장 큰 물고기 10마리 구하기 | 프로그래머스 | Level.1 |
<hr/>
- 가장 큰 물고기 10마리 구하기 : FISH_INFO 테이블에서 가장 큰 물고기 10마리의 ID와 길이를 출력하는 SQL 문을 작성해주세요. 결과는 길이를 기준으로 내림차순 정렬하고, 길이가 같다면 물고기의 ID에 대해 오름차순 정렬해주세요. 단, 가장 큰 물고기 10마리 중 길이가 10cm 이하인 경우는 없습니다.
ID 컬럼명은 ID, 길이 컬럼명은 LENGTH로 해주세요.
=> [139일차] 최한이 / 가장 큰 물고기 10마리 구하기

3st/Jaeyoung/새싹.cpp
| 새싹 | 백준 | 브론즈 V |
<hr/>
- 새싹 : 아래 예제와 같이 새싹을 출력하시오.
=> [328일차] 박재영 / 새싹

4st/Hani/programmer/최댓값 구하기.sql
| 최댓값 구하기 | 프로그래머스 | Level.1 |
<hr/>
- 최댓값 구하기 : 가장 최근에 들어온 동물은 언제 들어왔는지 조회하는 SQL 문을 작성해주세요.
=> [141일차] 최한이 / 최댓값 구하기

4st/Eunseong/개인정보 수집 유효기간.java
https://school.programmers.co.kr/learn/courses/30/lessons/150370?language=java
| 개인정보 수집 유효기간 | 프로그래머스 |  Level.1 |
<hr/>
- 개인정보 수집 유효기간 : 고객의 약관 동의를 얻어서 수집된 1~n번으로 분류되는 개인정보 n개가 있습니다. 약관 종류는 여러 가지 있으며 각 약관마다 개인정보 보관 유효기간이 정해져 있습니다. 당신은 각 개인정보가 어떤 약관으로 수집됐는지 알고 있습니다. 수집된 개인정보는 유효기간 전까지만 보관 가능하며, 유효기간이 지났다면 반드시 파기해야 합니다.
예를 들어, A라는 약관의 유효기간이 12 달이고, 2021년 1월 5일에 수집된 개인정보가 A약관으로 수집되었다면 해당 개인정보는 2022년 1월 4일까지 보관 가능하며 2022년 1월 5일부터 파기해야 할 개인정보입니다.
당신은 오늘 날짜로 파기해야 할 개인정보 번호들을 구하려 합니다.
모든 달은 28일까지 있다고 가정합니다.
다음은 오늘 날짜가 2022.05.19일 때의 예시입니다.
약관 종류	유효기간
A	6 달
B	12 달
C	3 달
번호	개인정보 수집 일자	약관 종류
1	2021.05.02	A
2	2021.07.01	B
3	2022.02.19	C
4	2022.02.20	C
첫 번째 개인정보는 A약관에 의해 2021년 11월 1일까지 보관 가능하며, 유효기간이 지났으므로 파기해야 할 개인정보입니다.
두 번째 개인정보는 B약관에 의해 2022년 6월 …
=> [141일차] 공은성 / 개인정보 수집 유효기간

4st/Hani/programmer/특정 옵션이 포함된 자동차 리스트 찾기.sql
https://school.programmers.co.kr/learn/courses/30/lessons/157343
| 특정 옵션이 포함된 자동차 리스트 구하기 | 프로그래머스 | Level.1 |
<hr/>
- 특정 옵션이 포함된 자동차 리스트 구하기 : CAR_RENTAL_COMPANY_CAR 테이블에서 '네비게이션' 옵션이 포함된 자동차 리스트를 출력하는 SQL문을 작성해주세요. 결과는 자동차 ID를 기준으로 내림차순 정렬해주세요.
=> [142일차] 최한이 / 특정 옵션이 포함된 자동차 리스트 구하기

3st/Jaeyoung/Julka.cpp
| Julka | 백준 | 브론즈 V |
<hr/>
- Julka : Julka zaskoczyła wczoraj w przedszkolu swoją wychowawczynię rozwiązując następującą zagadkę:
Klaudia i Natalia mają razem 10 jabłek, ale Klaudia ma o 2 jabłka więcej niż Natalia. Ile jabłek ma każda z dziewczynek?
Julka odpowiedziała bez namysłu: Klaudia ma sześć jabłek, natomiast Natalia ma cztery jabłka.
Wychowywaczyni postanowiła sprawdzić, czy odpowiedź Julki nie była przypadkowa i powtarzała zagadkę, za każdym razem zwiększając liczby jabłek w zadaniu. Julka zawsze odpowiadała prawidłowo. Zaskoczona wychowawczyni chciała kontynuować ,,badanie'' Julki, ale przy bardzo dużych liczbach sama nie potrafiła szybko rozwiązać zagadki. Pomóż pani przedszkolance i napisz program, który będzie podpowiadał jej …
=> [331일차] 박재영 / Julka
