CODE-U-S/Coding_Test_Study

Hyeseung/html.html

| 2023.04.10 | 1주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `eclipse` |
| A + B | 백준 | 브론즈 V | 208ms | https://www.acmicpc.net/problem/1000 |
- A + B : Scanner를 이용해 A, B를 입력받아 A + B 출력

first commit

---

Jiin/BreakEvenPoit_1712.java
Jiin/CdingIsPT.cpp

| 2023.05.15 | 1주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br>  `c++` <br> `vscode`|
| 손익분기점 | 백준 | 브론즈 II | 108ms | https://www.acmicpc.net/problem/1712 |
| 코딩은 체육과목 입니다 | 백준 | 브론즈 V | 0ms | https://www.acmicpc.net/problem/25314 |
- 손익분기점 : 고정비용, 가변비용, 제품의 값이 차례료 입력될 때 손익분기점 구하기
- 코딩은 체육과목 입니다 : 혜아가 long을 n개 붙일수록 4byte씩 더 저장할 수 있다고 생각할 때, _**N**_ byte값을 저장하기 위한 long~ int 출력하기

[1주차] 이지인 / 손익분기점 외 1개

---

Hyeseung/Baekjoon/_4880.java
Hyeseung/Baekjoon/_5893.py

| 2023.05.20 | 2주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` `python` <br> `vscode` |
| 다음수 | 백준 | 브론즈 3 | 180ms | https://www.acmicpc.net/problem/4880 |
| 17배 | 백준 | 브론즈 3 | 40ms | https://www.acmicpc.net/problem/5893 |
- 다음수 : 0 0 0이 들어오기 전까지 무한반복하면서 등차수열인지 등비수열인지 확인하기
BufferedReader, split 사용
- 17배 : 2진수를 입력받고 17을 곱한 후 해당 값을 2진수로 출력하기'
bin(), [2:0] 사용

[2주차] 김혜승 / 다음수 외 1개

---

Jiin/Why_do_you_say_it_twice.c
Jiin/a_common_multiple.c

| 2023.05.20 | 2주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `c` |
| 2의 영역 | 프로그래머스 | Lv. 0 | 36.52ms | https://school.programmers.co.kr/learn/courses/30/lessons/181894 |
| 공배수 | 프로그래머스 | Lv. 0 | 0.01ms | https://school.programmers.co.kr/learn/courses/30/lessons/181936 |
- 2의 영역 : 숫자 배열에서 처음 2부터 마지막 2까지의 배열 리턴
- 공배수 : number가 n과 m의 공배수인지 구하기
***
'2의 영역' 문제 조건이 리턴되는 배열을 동적할당 하는 것입니다.
멍하게 바라보고 있었는데 흐릿하게나마 기억이 나서 풀었습니다.
이런 중요한 것을 기억에 지워지지 않도록 복습해야겠습니다.

[2주차] 이지인 / 2의 영역 외 1개

---

Hyeseung/Baekjoon/_10988.java
Hyeseung/Baekjoon/_2231.java
Hyeseung/Baekjoon/_2309.java

| 2023.05.27 | 3주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 일곱 난쟁이 | 백준 | 브론즈 I | 208ms | https://www.acmicpc.net/problem/10988 |
| 팰린드롬인지 확인하기 | 백준 | 브론즈 II | 208ms | https://www.acmicpc.net/problem/2309 |
- 일곱 난쟁이 : 9명의 난쟁이 중 가짜 2명의 난쟁이를 제외시키면 나머지 진짜 7명의 난쟁이의 키 합이 100이 된다. 이 진짜 난쟁이의 키들을 구하시오.
for문을 이용하여  브루트 포스 문제를 풀었음
- 팰린드롬인지 확인하기 : 팰린드롬이란 앞으로 읽을 때와 거꾸로 읽을 때 똑같은 단어를 말하는데, 팰린드롬인지 확인하기
while문으로 left, right 변수를 주어 문자열 앞 뒤를 비교함

[3주차] 김혜승 / 팰린드롬인지 확인하기 외 1개

---

Sunhee/PGS/Even and odd numbers.py
Sunhee/PGS/Watermelon.py

| 2023.06.01 | 4주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `python3` <br> `vscode` |
| 짝수와 홀수 | 프로그래머스 | Lv.1 | 0.01ms | https://school.programmers.co.kr/learn/courses/30/lessons/12937 |
| 수박수박수박수박수박수? | 프로그래머스 | Lv.1 | 0.01ms | https://school.programmers.co.kr/learn/courses/30/lessons/12922?language=python3 |
- 길이가 n이고, "수박수박수박수...."와 같은 패턴을 유지하는 문자열을 리턴하는 함수, solution을 완성하세요. 예를들어 n이 4이면 "수박수박"을 리턴하고 3이라면 "수박수"를 리턴하면 됩니다.
- 정수 num이 짝수일 경우 "Even"을 반환하고 홀수인 경우 "Odd"를 반환하는 함수, solution을 완성해주세요.

[4주차] 김선희 / 짝수와 홀수 외 1개

---

Jihyun/BaekJoon_No_1547.c
Jihyun/BaekJoon_No_5522.c

| 2023.06.04 | 4주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 카드게임 | 백준 | 브론즈 V | 0ms | https://www.acmicpc.net/problem/5522 |
| 공 | 백준 | 브론즈 III | 0ms | https://www.acmicpc.net/problem/1547 |
- 카드게임 : 5회 동안 게임의 득점을 나타내는 정수가 주어졌을 때 총점을 구하는 프로그램을 작성하였다.
- 공 : 컵 3개를 옮긴 후 공이 들어있는 컵의 번호를 구하는 프로그램을 작성하였다.

[4주차] 김지현 / 카드게임 외 1개

---

Sojeong/Programmers/PGS_java_문자열뒤집기.java
Sojeong/Programmers/PGS_java_배열의유사도.java

| 2023.06.04 | 4주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 배열의 유사도 | 프로그래머스 | Lv.0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/120903 |
| 문자열 뒤집기 | 프로그래머스 | Lv.0 | 1.15ms | https://school.programmers.co.kr/learn/courses/30/lessons/120822 |
- 배열의 유사도: 문자열 배열 s1과 s2가 매개변수로 주어질 때 같은 원소의 개수를 return하는 문제
- equals()를 사용하여 s1[i]와 s2[j]를 비교하였다.
- 문자열 뒤집기: my_string이 매개변수로 주어질 때, 거꾸로 뒤집은 문자열을 return하는 문제
- for문을 my_string.length() - 1부터 돌렸다. (마지막 인덱스의 값은 length - 1이기 때문)
- substring()을 사용하여 문자열을 하나씩 잘라 이어붙였다. (substring(start, end)을 사용하면서 잠깐 어려움을 겪었는데, end의 전까지 문자열을 발췌하는 것인지 모르고 있었기 때문이다. …

[4주차] 나소정 / 배열의 유사도 외 1개

---

Hyeseung/Baekjoon/_28074.java
Hyeseung/Baekjoon/_28097.java

| 2023.06.04 | 4주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 모비스 | 백준 | 브론즈 IV | 124ms | https://www.acmicpc.net/problem/28074 |
| 모범생 포닉스 | 백준 | 브론즈 IV | 124ms | https://www.acmicpc.net/problem/28097 |
- 모비스 : 입력한 값으로 MOBIS를 만들어낼 수 있을까?
BufferedReader 사용, contains()를 사용하여 각 단어들이 포함되어 있는지 확인(포함되어 있지 않을 경우 바로 no, 종료시키기)
- 모범생 포닉스 : 시간들을 입력하고 모든 시간들을 더한 다음, 다음 시간으로 넘어갈 때 각 텀들을 8시간이 가정하고 그 8시간
또한 더하기. 하루를 24시간이라 했을 때 몇일 몇시간 걸리는지 구하기
BufferedReader 사용, split() 사용

[4주차] 김혜승 / 모비스 외 1개

---

Jiin/returnCode.java
Jiin/specialChar.java

| 2023.06.04 | 4주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` |
| 코드 처리하기 | 프로그래머스 | Lv. 0 | 348.29ms | https://school.programmers.co.kr/learn/courses/30/lessons/181932 |
| 특수문자 출력하기 | 프로그래머스 | Lv. 0 | 137.58ms | https://school.programmers.co.kr/learn/courses/30/lessons/181948?language=java |
- 코드 처리하기 : 문자열 code를 한 글자씩 읽으며 조건에 따라 처리하기
- 특수문자 출력하기 : !@#$%^&*(\'"<>?:;을 출력하는 문제
***
문해력을 높이기 위해 문제가 긴 문제를 한 번 풀어보았습니다.
잘못 읽어서 Character.getNumericValue()라는 처음 보는 메서드도 사용해 보다가 
코드를 다 짜고 나서야 저 메서드는 필요가 없다는 것을 알았습니다.
앞으로도 더 많이 긴 문제들을 풀어봐야겠습니다.

[4주차] 이지인 / 코드 처리하기 외 1개

---

Jinseon/Cellphone.java
Jinseon/Homework.java
Sojeong/Baekjoon/BOJ_2420.java
Sojeong/Programmers/PGS_java_문자열뒤집기.java
Sojeong/Programmers/PGS_java_배열의유사도.java

| 2023.06.11 | 5주차 | <ul><li>[ ] 문제 풀이</li><li>[x] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |

[Fix] 명명규칙

---

Sojeong/Baekjoon/BOJ_1264.java
Sojeong/Programmers/PGS_java_문자열정렬하기.java

| 2023.06.11 | 5주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 문자열 정렬하기(1) | 프로그래머스 | Lv.0 | 0.79ms | https://school.programmers.co.kr/learn/courses/30/lessons/120850 |
| 모음의 개수 | 백준 | 브론즈 4 | 120ms | https://www.acmicpc.net/problem/1264 |
- 문자열 정렬하기(1): 매개변수로 주어지는 문자열 my_string 안의 숫자만 골라 오름차순 정렬하여 return하는 문제.
- replaceAll()를 사용하여 a~z가 아닌 값을 ""로 치환함.
- split()을 사용하여 "을 기준으로 자른 배열을 만듦.
- Arrays.sort를 사용하여 오름차순 정렬함.
- 모음의 개수: 영문 문장을 입력받아 모음의 개수를 세는 문제.
- BufferedReader를 사용하여 입력받음.
- toLowerCase()를 사용하여 입력받은 영문 문장을 소문자로 변환함.
- (여담): 처음엔 toLowerCase()를 생각하지 못하고 대문자까지 조건으로 주었다가 코드가 너무 길어져서 더 나은 해결 방안을 찾느라 시간을 좀 …

[5주차] 나소정 / 문자열 정렬하기(1) 외 1개

---

Hyeseung/Programmers/길이에따른연산.java
Hyeseung/Programmers/문자열뒤n글자.java

| 2023.06.11 | 5주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 문자열의 뒤의 n글자 | 프로그래머스 | Lv.0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/181910 |
| 길이에 따른 연산 | 프로그래머스 | Lv.0 | 0.95ms | https://school.programmers.co.kr/learn/courses/30/lessons/181879 |
- 문자열의 뒤의 n글자 : 뒤의 n글자만 출력하기
substring() 사용
- 길이에 따른 연산 : 11이상이면 모든 리스트 값을 더하고 아니면 곱하기
stream api 사용

[5주차] 김혜승 / 문자열의 뒤의 n글자 외 1개	

---

Jinseon/dice.java
Jinseon/flag.java

| 2023.06.11 | 5주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 주사위 게임 | 프로그래머스 | Level 0 | 0.27ms | https://school.programmers.co.kr/learn/courses/30/lessons/181916 |
| flag에 따라 다른 값 반환하기 | 프로그래머스 | Level 0 | 0.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/181933 |
- 주사위 게임 : 배열을 사용하여 문제 풀기
- flag에 따라 다른 값 반환하기 : flag가 boolean타입임을 이용하여 다른 값 반환

[5주차] 이진선 / 주사위 게임 외 1개

---

Jihyun/BaekJoon_No_1100.c
Jihyun/BaekJoon_No_2455.c

| 2023.06.11 | 5주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `C11` <br> `vscode` |
| 하얀 칸 | 백준 | 브론즈 II | 0ms | https://www.acmicpc.net/problem/1100 |
| 지능형 기차 | 백준 | 브론즈 III | 0ms | https://www.acmicpc.net/problem/2455 |
- 하얀 칸 : 체스판의 하얀칸 위 말의 갯수를 구하는 프로그램이다.
- 지능형 기차 : 1번역부터 4번역까지 가는 도중 기차 안에 사람이 가장 많을 때를 계산하여 구하는 프로그램이다.

[5주차] 김지현 / 하얀 칸 외 1개

---

Sunhee/PGS/A coke problem.py
Sunhee/PGS/The nearest same letter closest to.py

| 2023.06.11 | 5주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `python3` <br> `vscode` |
| 가장 가까운 같은 글자 | 프로그래머스 | Lv.1 | 3.26ms | https://school.programmers.co.kr/learn/courses/30/lessons/142086 |
| 콜라 문제 | 프로그래머스 | Lv.1 | 0.37ms | https://school.programmers.co.kr/learn/courses/30/lessons/132267 |
- 문자열 s가 주어졌을 때, s의 각 위치마다 자신보다 앞에 나왔으면서, 자신과 가장 가까운 곳에 있는 같은 글자가 어디 있는지 알고 싶습니다.
예를 들어, s="banana"라고 할 때,  각 글자들을 왼쪽부터 오른쪽으로 읽어 나가면서 다음과 같이 진행할 수 있습니다.
b는 처음 나왔기 때문에 자신의 앞에 같은 글자가 없습니다. 이는 -1로 표현합니다.
a는 처음 나왔기 때문에 자신의 앞에 같은 글자가 없습니다. 이는 -1로 표현합니다.
n은 처음 나왔기 때문에 자신의 앞에 같은 글자가 없습니다. 이는 -1로 표현합니다.
a는 자신보다 두 칸 앞에 a가 있습니다. 이는 2로 표현합니다.
n도 자신보다 두 칸 …

[5주차] 김선희 / 가장 가까운 같은 글자 외 1개

---

Jiin/JustPrint.cpp
Jiin/StringMix.cpp
Jiin/negative.cpp

| 2023.06.11 | 5주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `c++` |
| 첫 번째로 나오는 음수 | 프로그래머스 | Lv. 0 | 0.01ms | https://school.programmers.co.kr/learn/courses/30/lessons/181896?language=cpp |
| 문자열 출력하기 | 프로그래머스 | Lv. 0 | 2.16ms | https://school.programmers.co.kr/learn/courses/30/lessons/181952 |
| 문자열 섞기 | 프로그래머스 | Lv. 0 | 0.01ms | https://school.programmers.co.kr/learn/courses/30/lessons/181942 |
- 첫 번째로 나오는 음수 : 콜렉터(vector)에서 가장 먼저 나오는 음수의 인덱스 값 구하기
- 문자열 출력하기 : 문자열 출력하기
- 문자열 섞기 : 길이가 같은 두 문자열 번갈아 가며 하나씩 출력하기
***
c++문자열 폭탄!...이 이번 코테의 컨셉이자 단련 부분이었습니다.
근데 첫 번째로 고른 문제가 '특정 문자열로 끝나는 가장 긴 부분 문자열 찾기' 란 문제였는데
도저히 c++로 못 해서 '첫 번째로 나오는 음수' …

[5주차] 이지인 / 첫 번째로 나오는 음수 외 2개

---

Jihyun/BaekJoon_No_1110.java
Jihyun/BaekJoon_No_15813.java
Jihyun/BaekJoon_No_3052.java

| 2023.06.19 | 6주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 더하기 사이클 | 백준 | 브론즈 I | 108ms | https://www.acmicpc.net/problem/1110 |
| 너의 이름은 몇 점이니? | 백준 | 브론즈 II | 112ms | https://www.acmicpc.net/problem/15813 |
| 나머지 | 백준 | 브론즈 II | 116ms | https://www.acmicpc.net/problem/3052 |
- 각 자리의 수를 더하고 원래 수로 돌아오는 사이클의 길이를 구하는 프로그램
- 알파벳 하나하나의 점수를 모두 더하여 점수를 구하는 프로그램
- HashMap 사용
- 42로 나눈 나머지의 값 중 다른 값이 몇 개 있는지 구하는 프로그램
- ArrayList 사용

[6주차] 김지현 / 더하기 사이클 외 2개

---

Sojeong/Programmers/PGS_java_모음제거.java
Sojeong/Programmers/PGS_java_문자열안에문자열.java
Sojeong/Programmers/PGS_java_수박수박.java
Sojeong/Programmers/PGS_java_접미사인지확인하기.java
Sojeong/Programmers/PGS_java_짝수는싫어요.java

| 2023.06.18 | 6주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 수박수박수박수박수박수? | 프로그래머스 | Lv.1 | 0.05ms | https://school.programmers.co.kr/learn/courses/30/lessons/12922 |
| 접미사인지 확인하기 | 프로그래머스 | Lv.unrated | 0.06ms | https://school.programmers.co.kr/learn/courses/30/lessons/181908 |
| 문자열 안에 문자열 | 프로그래머스 | Lv.0 | 0.02ms | https://school.programmers.co.kr/learn/courses/30/lessons/120908 |
| 모음 제거 | 프로그래머스 | Lv.0 | 0.21ms | https://school.programmers.co.kr/learn/courses/30/lessons/120849 |
| 짝수는 싫어요 | 프로그래머스 | Lv.0 | 0.02ms | https://school.programmers.co.kr/learn/courses/30/lessons/120813 |
- 수박수박수박수박수박수? : 길이가 …

[6주차] 나소정 / 수박수박수박수박수박수? 외 4개

---

Sunhee/PGS/A fruit seller.py
Sunhee/PGS/Hall of Fame (1).py
Sunhee/PGS/Memory score.py

| 2023.06.18 | 6주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `python3` <br> `vscode` |
| 추억 점수 | 프로그래머스 | Lv.1 | 0.01ms | https://school.programmers.co.kr/learn/courses/30/lessons/176963 |
| 과일 장수 | 프로그래머스 | Lv.1 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/135808 |
| 명예의 전당 (1)  | 프로그래머스 | Lv.1 | 0.01ms | https://school.programmers.co.kr/learn/courses/30/lessons/138477 |
- 사진들을 보며 추억에 젖어 있던 루는 사진별로 추억 점수를 매길려고 합니다. 사진 속에 나오는 인물의 그리움 점수를 모두 합산한 값이 해당 사진의 추억 점수가 됩니다. 예를 들어 사진 속 인물의 이름이 ["may", "kein", "kain"]이고 각 인물의 그리움 점수가 [5점, 10점, 1점]일 때 해당 사진의 추억 점수는 16(5 + 10 + 1)점이 됩니다. 다른 사진 속 인물의 이름이 ["kali", "mari", …

[6주차] 김선희 / 추억 점수 외 2개

---

Hyeseung/Baekjoon/_1357.java
Hyeseung/Baekjoon/_1977.java
Hyeseung/Baekjoon/_28235.java

| 2023.06.18 | 6주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 코드마스터 2023 | 백준 | 브론즈 5 | 124ms | https://www.acmicpc.net/problem/28235 |
| 뒤집힌 덧셈 | 백준 | 브론즈 1 | 128ms | https://www.acmicpc.net/problem/1357 |
| 완전제곱수 | 백준 | 브론즈 2 | 148ms | https://www.acmicpc.net/problem/1977 |
- 코드마스터 2023 : 네 가지 구호에 맞춰 알맞은 응원을 하는 프로그램을 작성하여라
단순히 switch를 써서 맞으면 해당 응원을 출력시킴
- 뒤집힌 덧셈 : Rev(Rev(X) + Rev(Y))를 구하는 프로그램을 작성하시오
뒤집는 StringBuffer.reverse() 사용함
- 완전제곱수 : M ~ N 까지의 수 들 중에서 완전제곱수들의 합과 최솟값을 구하시오.
최솟값 : Math.min() 사용, for ( i * i ) 를 사용

[6주차] 김혜승 / 코드마스터 2023 외 2개

---

Hyeseung/Baekjoon/_11945.java
Hyeseung/Baekjoon/_1292.java
Hyeseung/Baekjoon/_28062.java

| 2023.06.25 | 7주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 준석이의 사탕 사기 | 백준 | 브론즈 2 | 140ms | https://www.acmicpc.net/problem/28062 |
| 쉽게 푸는 문제 | 백준 | 브론즈 2 | 140ms | https://www.acmicpc.net/problem/1292 |
| 뜨거운 붕어빵 | 백준 | 브론즈 2 | 120ms | https://www.acmicpc.net/problem/11945 |
- 준석이의 사탕 사기 : 준석이가 사간 총 사탕의 개수가 홀수가 되면 두 동생이 사탕을 한 개라도 더 갖기 위해 서로 싸울 것이라 총 짝수 개의 사탕을 가져가려고 한다. 준석이를 위해서 최대로 가져갈 수 있는 사탕의 개수를 구해주자!
String.of.mapToInt.toArray를 사용해서 br.readLine()으로 받은 것을 int 배열로 만듦
<br>
- 쉽게 푸는 문제 : 1 2 2 3 3 3 4 4 4 4 5 .. 이러한 수열을 만들고 어느 일정한 구간을 주면 그 구간의 합을 구하는 것이다.
String.of.mapToInt.toArray를 사용해서 …

[7주차] 김혜승 / 준석이의 사탕 사기 외 2개

---

Jiin/All_scattered.java
Jiin/BiggerAdd.java
Jiin/IwatnToEatIt.java

| 2023.06.25 | 7주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 분산처리 | 백준 | 브론즈 2 | 1048ms | https://www.acmicpc.net/problem/1009 |
| 더 크게 합치기 | 프로그래머스 | Lv.o | 10.37ms | https://school.programmers.co.kr/learn/courses/30/lessons/181939 |
| 분산처리 | 프로그래머스 | Lv.0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/120830 |
- 분산처리 : 10대의 컴퓨터로 a^b만큼의 일을 하나씩 처리할 때, 마지막 일은 몇 번째 컴퓨터가 처리하는가?
- 더 크게 합치기 : 22⊕12 = 2212일때, 두 ⊕식의 값을 비교하고 더 큰 수 출력.
- 양꼬치 : 10인분을 먹으면 음료수 하나가 꽁짜인 양꼬치 집에서 n개의 양꼬치와 k개의 음료수를 먹으면 발생하는 총 비용은?
***
첫 번째 문제를 푸는데 자꾸 시간초과가 써서 묵혀두었던 BufferedReader, BufferedWirter를 써보았습니다.
그랬는데 이번에는 '출력 …

[7주차] 이지인 / 분산처리 그 외 2개

---

Sunhee/PGS/A runner who failed to finish.py
Sunhee/PGS/Mock test.py
Sunhee/PGS/Ternary flip.py

| 2023.06.25 | 7주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `python3` <br> `vscode` |
| 3진법 뒤집기 | 프로그래머스 | Lv.1 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/68935 |
| 모의고사 | 프로그래머스 | Lv.1 | 0.19ms | https://school.programmers.co.kr/learn/courses/30/lessons/42840 |
| 완주하지 못한 선수 | 프로그래머스 | Lv.1 | 21.20ms | https://school.programmers.co.kr/learn/courses/30/lessons/42576 |
- 자연수 n이 매개변수로 주어집니다. n을 3진법 상에서 앞뒤로 뒤집은 후, 이를 다시 10진법으로 표현한 수를 return 하도록 solution 함수를 완성해주세요.
- 수포자는 수학을 포기한 사람의 준말입니다. 수포자 삼인방은 모의고사에 수학 문제를 전부 찍으려 합니다. 수포자는 1번 문제부터 마지막 문제까지 다음과 같이 찍습니다.
1번 수포자가 찍는 방식: 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, ...
2번 수포자가 …

[7주차] 김선희 / 3진법 뒤집기 외 2개

---

Sojeong/Programmers/PGS_java_부족한금액계산하기.java
Sojeong/Programmers/PGS_java_콜라츠추측.java
Sojeong/Programmers/PGS_java_핸드폰번호.java

| 2023.06.25 | 7주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 콜라츠 추측 | 프로그래머스 | Lv.1 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/12943 |
| 핸드폰 번호 가리기 | 프로그래머스 | Lv.1 | 0.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/12948 |
| 부족한 금액 계산하기 | 프로그래머스 | Lv.1 | 0.11ms | https://school.programmers.co.kr/learn/courses/30/lessons/82612 |
- 콜라츠 추측:
- (1-1) 입력된 수가 짝수라면 2로 나눕니다. 
(1-2) 입력된 수가 홀수라면 3을 곱하고 1을 더합니다. 
(2) 결과로 나온 수에 같은 작업을 1이 될 때까지 반복합니다.
- 위 작업을 몇 번이나 반복해야 하는지 return하는 문제.
- 단, 주어진 수가 1인 경우에는 0을, 작업을 500번 반복할 때까지 1이 되지 않는다면 –1을 반환
- 삼항연산자를 사용하였고, while문과 if문으로 …

[7주차] 나소정 / 콜라츠 추측 외 2개

---

Jihyun/BaekJoon_No_10103.java
Jihyun/BaekJoon_No_1152.java
Jihyun/BaekJoon_No_2204.java
Jihyun/BaekJoon_No_3052.java

| 2023.06.26 | 7주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 1152 | 백준 | 브론즈 II | 380ms | https://www.acmicpc.net/problem/1152 |
| 2204 | 백준 | 브론즈 I | 156ms | https://www.acmicpc.net/problem/2204 |
| 10103 | 백준 | 브론즈 III | 112ms | https://www.acmicpc.net/problem/10103 |
- 단어의 개수 : 주어진 문자열에 들어있는 단어의 갯수를 구하는 프로그램
- 도비의 난독증 테스트 : 주어진 영어단어를 대소문자 구별없이 사전순으로 가장 앞서는 단어를 출력하는 프로그램
- 주사위 게임 : 주사위 게임이 끝난 이후에 두 사람의 점수를 구하는 프로그램

[7주차] 김지현 / 단어의 개수 외 2개

---

Jiin/CollatzArray.java
Jiin/CollatzArray.js
Jiin/TurnString.js
Jiin/twoString.js

| 2023.07.15 | 8주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `JS`  `vscode` |
| 콜라츠 수열 만들기 | 프로그래머스 | Lv. 0 | 0.05ms | https://school.programmers.co.kr/learn/courses/30/lessons/181919?language=javascript <br> https://school.programmers.co.kr/learn/courses/30/lessons/181919?language=java |
| 문자열 붙여서 출력하기 | 프로그래머스 | Lv. 0 | 44.35ms | https://school.programmers.co.kr/learn/courses/30/lessons/181946 |
| 문자열 돌리기 | 프로그래머스 | Lv. 0 | 53.18ms | https://school.programmers.co.kr/learn/courses/30/lessons/181945 |
- 콜라츠 수열 만들기 : 콜라츠 문제를 풀며 모든 숫자를 수열로서 기록한 배열을 반환하기
- 문자열 붙여서 출력하기 : 공백으로 구분된 두 문자열을 하나로 출력하기
- 문자열 돌리기 : 가로의 문자열을 세로로 …

[8주차] 이지인 / 콜라츠 수열 만들기 외 2개

---

Hyeseung/Baekjoon/_1924.java
Hyeseung/Baekjoon/_2755.java
Hyeseung/Baekjoon/_28113.java

| 2023.07.16 | 8주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 정보섬의 대중교통 | 백준 | 브론즈 5 | 124ms | https://www.acmicpc.net/problem/28113 |
| 2007년 | 백준 | 브론즈 1 | 128ms | https://www.acmicpc.net/problem/1924 |
| 이번학기 평점은 몇점? | 백준 | 브론즈 1 | 128ms | https://www.acmicpc.net/problem/2755 |
- 정보섬의 대중교통 : N, A, B를 입력받아 Bus, Subway 어느 것이 더 빠른지 찾기. (단, 동일할 경우 Anyway로 출력)
- 2007년 : 2007년의 해에서 month 와 date를 입력했을 때 해당 날의 요일 찾기
- 이번학기 평점은 몇점 ? : 학점 * 성적 / 학점 점수 구하기

[8주차] 김혜승 / 정보섬의 대중교통 외 2개

---

Sojeong/Programmers/PGS_java_나머지가1이되는수찾기.java
Sojeong/Programmers/PGS_java_서울에서김서방찾기.java
Sojeong/Programmers/PGS_java_제일작은수제거하기.java

| 2023.07.17 | 8주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 제일 작은 수 제거하기 | 프로그래머스 | Lv.1 | 0.96ms | https://school.programmers.co.kr/learn/courses/30/lessons/12935 |
| 나머지가 1이 되는 수 찾기 | 프로그래머스 | Lv.1 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/87389 |
| 서울에서 김서방 찾기 | 프로그래머스 | Lv.1 | 7.16ms | https://school.programmers.co.kr/learn/courses/30/lessons/12919 |
- 제일 작은 수 제거하기: 정수를 저장한 배열, arr 에서 가장 작은 수를 제거한 배열을 리턴하는 문제. 쉽게 생각하고 풀었는데, 생각보다 어려워서 당황했습니다.... 이번 문제를 풀면서 clone() 이라는 메소드를 처음 알게 되었는데요, 말 그대로 배열의 값을 복사하는 메소드입니다!
- 나머지가 1이 되는 수 찾기: 자연수 n이 매개변수로 주어질 때, n을 x로 나눈 나머지가 1이 되도록 하는 가장 …

[8주차] 나소정 / 제일 작은 수 제거하기 외 2개 

---

Hyeseung/Baekjoon/_2592.java
Hyeseung/Programmers/flag에 따라 다른 값 반환하기.java
Hyeseung/Programmers/n 번째 원소까지.java
Hyeseung/Programmers/n의 배수.java
Hyeseung/Programmers/공배수.java
Hyeseung/Programmers/대문자로 바꾸기.java
Hyeseung/Programmers/마지막 두 원소.java
Hyeseung/Programmers/문자열 곱하기.java
Hyeseung/Programmers/문자열로 변환.java
Hyeseung/Programmers/문자열을 정수로 변환하기.java
Hyeseung/Programmers/문자열의 앞의 n글자.java
Hyeseung/Programmers/배열 비교하기.java
Hyeseung/Programmers/부분 문자열.java
Hyeseung/Programmers/부분 문자열인지 확인하기.java
Hyeseung/Programmers/소문자로 바꾸기.java
Hyeseung/Programmers/접두사인지 확인하기.java
Hyeseung/Programmers/접미사인지 확인하기.java
Hyeseung/Programmers/정수 부분.java
Hyeseung/Programmers/조건에 맞게 수열 변환하기1.java
Hyeseung/Programmers/카운트 업.java

| 2023.07.23 | 9주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 부분 문자열인지 확인하기 | 프로그래머스 | Level.0 | 0.07ms | https://school.programmers.co.kr/learn/courses/30/lessons/181843 |
| 소문자로 바꾸기 | 프로그래머스 | Level.0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/181876 |
| 공배수 | 프로그래머스 | Level.0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/181936 |
| flag에 따라 다른 값 반환하기 | 프로그래머스 | Level.0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/181933 |
| 문자열을 정수로 변환하기 | 프로그래머스 | Level.0 | 0.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/181848 | …

[9주차] 김혜승 / 부분 문자열인지 확인하기 외 19개

---

Jiin/A_Word.java
Jiin/Divisor.c
Jiin/HowManyWeeks.c

| 2023.07.23 | 9주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` `C` |
| 약수 | 백준 | 브론즈 I | 0ms | https://www.acmicpc.net/problem/1037 |
| 문자와 문자열 | 백준 | 브론즈 V | 112ms | https://www.acmicpc.net/problem/27866 |
| 10! | 백준 | 브론즈 IV | 0ms | https://www.acmicpc.net/problem/28352 |
- 약수 : 진짜 약수들의 수 출력하기
- 문자와 문자열 : 문자열에서 n번째 문자 출력하기
- 10! : 10!초는 6주와 같다. 이처럼 n!초는 몇 주인지 출력하기
***
c를 제출할 때 언어를 C99로 해 놓은 것이랑 관련이 있는 건지 모르겠으나, 
c는 전부 0ms로 나와서 당황스럽습니다.
10!문제 마지막 부분을 보며 처음 안 사실이 있는데,
C/C++의 long long == Java의 long이란 사실입니다.

[9주차] 이지인 / 약수 외 2개

---

Sojeong/Programmers/PGS_java_나누어떨어지는숫자배열.java
Sojeong/Programmers/PGS_java_문자열내림차순으로배치하기.java
Sojeong/Programmers/PGS_java_문자열다루기기본.java

| 2023.07.24 | 9주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 문자열 다루기 기본 | 프로그래머스 | Lv.1 | 0.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/12918 |
| 문자열 내림차순으로 배치하기 | 프로그래머스 | Lv.1 | 0.34ms | https://school.programmers.co.kr/learn/courses/30/lessons/12917 |
| 나누어 떨어지는 숫자 배열 | 프로그래머스 | Lv.1 | 0.33ms | https://school.programmers.co.kr/learn/courses/30/lessons/12910 |
- 문자열 다루기 기본: 문자열 s의 길이가 4 혹은 6이고, 숫자로만 구성돼있는지 확인해주는 함수 완성하기
- charAt()을 사용해서 문자 하나하나 비교하여 풀었습니다
- 문자열 내림차순으로 배치하기: 문자열 s에 나타나는 문자를 큰것부터 작은 순으로 정렬해 새로운 문자열을 리턴하는 함수 완성하기
- reverse() 메소드를 사용하기 위해 answer를 StringBuilder로 선언하여 …

[9주차] 나소정 / 문자열 다루기 기본 외 2개

---

Jihyun/BaekJoon_No_2711.java
Jihyun/BaekJoon_No_2748.py
Jihyun/BaekJoon_No_2953.java

| 2023.05.10 | 9주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `ver.3 python` <br> `vscode` |
| 오타맨 고창영 | 백준 | 브론즈 II | 116ms | https://www.acmicpc.net/problem/2711 |
| 피보나치 수 2 | 백준 | 브론즈 I | 48ms | https://www.acmicpc.net/problem/2748 | 
| 나는 요리사다 | 백준 | 브론즈 III | 116ms | https://www.acmicpc.net/problem/2953 |
- 오타맨 고창영 : 오타낸 위치를 찾아 오타를 삭제하는 문제
- StringBuilder를 사용해 오타의 위치를 찾아 삭제하였다.
- 피보나치 수 2 : n번째의 피보나치 수를 출력하는 문제
- 나는 요리사다 : 5명의 각 참가자들이 만든 음식의 평가점수가 가장 높은 사람의 번호와 점수를 출력하는 문제

[9주차] 김지현 / 오타맨 고창영 외 2개

---

Sunhee/PGS/N numbers spaced by X.py
Sunhee/PGS/Number of p and y in a string.py
Sunhee/PGS/The sum of two integers.py

| 2023.07.23 | 9주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `python3` <br> `vscode` |
| x만큼 간격이 있는 n개의 숫자 | 프로그래머스 | Lv.1 | 0.31ms | https://school.programmers.co.kr/learn/courses/30/lessons/12954 |
| 문자열 내 p와 y의 개수 | 프로그래머스 | Lv.1 | 0.31ms | https://school.programmers.co.kr/learn/courses/30/lessons/12916 |
| 두 정수 사이의 합 | 프로그래머스 | Lv.1 | 0.93ms | https://school.programmers.co.kr/learn/courses/30/lessons/12912 |
- 함수 solution은 정수 x와 자연수 n을 입력 받아, x부터 시작해 x씩 증가하는 숫자를 n개 지니는 리스트를 리턴해야 합니다. 다음 제한 조건을 보고, 조건을 만족하는 함수, solution을 완성해주세요.
- 대문자와 소문자가 섞여있는 문자열 s가 주어집니다. s에 'p'의 개수와 'y'의 개수를 비교해 같으면 True, 다르면 False를 return 하는 solution를 완성하세요. …

[9주차] 김선희 / x만큼 간격이 있는 n개의 숫자 외 2

---

Hyeseung/Programmers/rny_string.java
Hyeseung/Programmers/같은 숫자는 싫어.java
Hyeseung/Programmers/문자열 정수의 합.java
Hyeseung/Programmers/정수 찾기.java

| 2023.07.25 | 10주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 문자열 정수의 합 | 프로그래머스 | Level.0 | 1.66ms | https://school.programmers.co.kr/learn/courses/30/lessons/181849 |
| rny_string | 프로그래머스 | Level.0 | 0.50ms | https://school.programmers.co.kr/learn/courses/30/lessons/181863 |
| 정수 찾기 | 프로그래머스 | Level.0 | 1.93ms | https://school.programmers.co.kr/learn/courses/30/lessons/181840 |
| 같은 숫자는 싫어 | 프로그래머스 | Level.1 | 2.59ms <br> 효율성 : 33.10ms | https://school.programmers.co.kr/learn/courses/30/lessons/181840 |
- 문자열 정수의 합 : 한 자리 정수로 이루어진 문자열 num_str이 주어질 때, 각 자리수의 합 구하기
- rny_string : rny_string이 주어질 때, …

[10주차] 김혜승 / 문자열 정수의 합 외 2개

---

Sunhee/PGS/A discrete array of numbers.py
Sunhee/PGS/Place integers in descending order.py

| 2023.07.25 | 10주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `python3` <br> `vscode` |
| 두 정수 사이의 합 | 프로그래머스 | Lv.1 | 0.35ms | https://school.programmers.co.kr/learn/courses/30/lessons/12912 |
| 정수 내림차순으로 배치하기 | 프로그래머스 | Lv.1 | 132ms | https://school.programmers.co.kr/learn/courses/30/lessons/12933 |
| 나누어 떨어지는 숫자 배열 | 프로그래머스 | Lv.1 | 0.64ms | https://school.programmers.co.kr/learn/courses/30/lessons/12910 |
- 두 정수 a, b가 주어졌을 때 a와 b 사이에 속한 모든 정수의 합을 리턴하는 함수, solution을 완성하세요.
예를 들어 a = 3, b = 5인 경우, 3 + 4 + 5 = 12이므로 12를 리턴합니다.
- 함수 solution은 정수 n을 매개변수로 입력받습니다. n의 각 자릿수를 큰것부터 작은 순으로 정렬한 새로운 정수를 리턴해주세요. 예를들어 n이 118372면 873211을 리턴하면 됩니다. …

[10주차] 김선희 / 문자열을 정수로 바꾸기 외 2개

---

Jiin/DeckOfCard.java
Jiin/If_String.c
Jiin/KnightsWeapon.java

| 2023.07.29 | 10주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `C` |
| 기사단원의 무기 | 프로그래머스 | Lv. 1 | 120.37ms | https://school.programmers.co.kr/learn/courses/30/lessons/136798 |
| 카드뭉치 | 프로그래머스 | Lv. 1 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/159994?language=java |
| 조건 문자열 | 프로그래머스 | Lv. 0 | 0.01ms | https://school.programmers.co.kr/learn/courses/30/lessons/181934?language=c |
- _**기사단원의 무기**_ : 기사단의 기사는 자신의 숫자의 약수의 개수만큼의 공격력을 가진 무기를 구매해야 한다. 이때, 이웃나라의 협약으로 정해진 공격력보다 초과하면 정해진 공격력의 무기를 구매해야 한다. 무기를 만들 때 1공격력당 철 1kg이 필요하면, 한 기사단의 무기를 만들어줄 때 필요한 철의 총량 반환.
- **_카드뭉치_** : 영어단어가 적힌 두 카드뭉치로 단어의 순서 …

[10주차] 이지인 / 기사단원의 무기 외 2개

---

Sojeong/Programmers/PGS_java_x만큼간격이있는n개의숫자.java
Sojeong/Programmers/PGS_java_가장가까운같은글자.java
Sojeong/Programmers/PGS_java_자릿수더하기.java

| 2023.07.29 | 10주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| x만큼 간격이 있는 n개의 숫자 | 프로그래머스 | Lv.1 | 208ms | https://school.programmers.co.kr/learn/courses/30/lessons/12954 |
| 가장 가까운 같은 글자 | 프로그래머스 | Lv.1 | 19.67ms | https://school.programmers.co.kr/learn/courses/30/lessons/142086 | 
| 자릿수 더하기 | 프로그래머스 | Lv.1 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/12931 |
- x만큼 간격이 있는 n개의 숫자 : 정수 x와 자연수 n을 입력 받아, x부터 시작해 x씩 증가하는 숫자를 n개 지니는 리스트를 리턴
- 가장 가까운 같은 글자: 문자열 s가 주어졌을 때, s의 각 위치마다 자신보다 앞에 나왔으면서, 자신과 가장 가까운 곳에 있는 같은 글자가 어디 있는지 알아내어 배열에 넣어 리턴
- 기준이 되는 문자열을 만드는 게 넘 어려웠습니다.... substring()과 …

[10주차] 나소정 / x만큼 간격이 있는 n개의 숫자 외 2개

---

Jiin/InfoProtectClub.java
Jiin/MaxNumInArray.java
Jiin/RepeatString.java

| 2023.08.27 | 14주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` |
| 문자열 반복 | 백준 | 브론즈 II | 76ms | https://www.acmicpc.net/problem/2675 |
| 정보보호학부 동아리 소개 | 백준 | 브론즈 V | 108ms | https://www.acmicpc.net/problem/28691 |
| 최댓값 | 백준 | 브론즈 III | 80ms | https://www.acmicpc.net/problem/2566 |
- 문자열 반복 : 입력된 값만큼 각 문자들을 반복한 문자열 출력 ex) 3 ABC -> AAABBBCCC
- 정보보호학부 동아리 소개 : 입력받은 첫 문자와 일치하는 동아리 이름 출력
- 최댓값 : 9x9행렬에서 최댓값과 그의 행, 열 번호를 출력
***
문자열 반복과 최댓값은 오랫만의 입출력 받는 Java이니 만큼,
BufferedReader과 split(), StringTokenizer을 사용해 보았습니다.
정보보호학부 동아리 소개문제는 사실 쉬운 방법이라면 얼마든지 있지만
저번주에 못 썼던 자료구조를 써보고 싶어서 이진 탐색으로 풀어보았습니다.

[14주차] 이지인 / 문자열 반복 외 2개

---

Hyeseung/Programmers/숫자 비교하기.java

| 2023.08.23 | 14주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 숫자 비교하기 | 프로그래머스 | Level.0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/120807?language=java |
- 숫자 비교하기 : 두 수가 같으면 1 다르면 -1을 retrun

[14주차] 김혜승 / 숫자 비교하기

---

Sunhee/programmers/콜라츠 추측.java

https://school.programmers.co.kr/learn/courses/30/lessons/12943?language=java
| 2024.03.04 | 1주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 콜라츠 추측 | 프로그래머스 | Lv.1 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/12943?language=java |
- 1937년 Collatz란 사람에 의해 제기된 이 추측은, 주어진 수가 1이 될 때까지 다음 작업을 반복하면, 모든 수를 1로 만들 수 있다는 추측입니다. 작업은 다음과 같습니다.
1-1. 입력된 수가 짝수라면 2로 나눕니다. 
1-2. 입력된 수가 홀수라면 3을 곱하고 1을 더합니다. 
2. 결과로 나온 수에 같은 작업을 1이 될 때까지 반복합니다. 
예를 들어, 주어진 수가 6이라면 6 → 3 → 10 → 5 → 16 → 8 → 4 → 2 → 1 이 되어 총 8번 만에 1이 됩니다. 위 작업을 몇 번이나 반복해야 하는지 반환하는 함수, solution을 완성해 주세요. 단, 주어진 수가 1인 경우에는 0을, 작업을 500번 반복할 …

[1주차] 김선희 / 콜라츠 추측

---

Jihyun/Programmers_VerticalReading.java

| 2024.03.04 | 1주차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 세로 읽기 | 프로그래머스 | Level.0 | 14.06ms | https://school.programmers.co.kr/learn/courses/30/lessons/181904 |
- 세로 읽기: 문자열 my_string과 정수 m과 c가 주어질 때 한 줄에 my_string을 m글자씩 가로로 나열했을 때 c번째에 있는 글자를 출력하는 코드

[1주차] 김지현 / 세로 읽기

---

Jihyun/Programmers_ChangeCaseToPrint.java
Jihyun/Programmers_VerticalReading.java

| 2024.03.05. | 2일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 대소문자 바꿔서 출력 | 프로그래머스 | Level.0 | 182.07ms | https://school.programmers.co.kr/learn/courses/30/lessons/181949 |
- 대소문자 바꿔서 출력 : 알파벳으로 주어진 str의 대소문자를 바꿔 출력하는 프로그램

[2일차] 김지현 / 대소문자 바꿔서 출력하기 

---

Hyeseung/Baekjoon/_29751.java
Hyeseung/Baekjoon/_30007.java

| 2024.03.05 | 2일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.11 java` <br> `vscode` |
| 삼각형 | 백준 | 브론즈 V | 232ms | https://www.acmicpc.net/problem/29751 |
| 라면 공식 | 백준 | 브론즈 V | 236ms | https://www.acmicpc.net/problem/30007 |
- 삼각형 : 삼각형의 넓이 구하기 (소수점 첫번째자리 까지)
- 라면 공식 : A * (X - 1) + B 의 공식을 사용하여 N번 정답 출력하기

[2일차] 김혜승 / 삼각형 외 1개

---

Jiin/the_closest_and_same_char.c

| 2024.03.05 | 2일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `C` |
| 가장 가까운 같은 글자 | 프로그래머스 | Lv.1 | 4.24ms | https://school.programmers.co.kr/learn/courses/30/lessons/142086 |
- 가장 가까운 같은 글자 : 문자열 s의 각 위치마다 자신보다 앞에 나왔으면서, 자신과 가장 가까운 곳에 있는 같은 글자가 어디있는지 찾으면 된다.  
**ex> s = "banana"라면**  
b는 처음 나왔기 때문에 자신 앞에 같은 글자가 없어서 -1,  
a는 처음 나왔기 때문에 자신 앞에 같은 글자가 없어서 -1,  
n는 처음 나왔기 때문에 자신 앞에 같은 글자가 없어서 -1,  
a는 자신보다 두 칸 앞에 같은 글자가 있으므로 2,  
n는 자신보다 두 칸 앞에 같은 글자가 있으므로 2,  
a는 자신보다 각각 네 칸, 두 칸 앞에 같은 글자가 있으므로 더 가까운 2  
로 표현하며 최종적으로 [-1, -1, -1, 2, 2, 2]를 반환합니다.

[2일차] 이지인 / 가장 가까운 같은 글자

---

Jiin/according_to_flag.js
Jiin/even_or_odd.js
Jiin/multiple_of_n.c

| 2024.03.06 | 3일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `JavaScript` <br> `C` |
| 홀짝 구분하기 | 프로그래머스 | Lv. 0 | 91.01ms | https://school.programmers.co.kr/learn/courses/30/lessons/181944 |
| flag에 따라 다른 값 변환하기 | 프로그래머스 | Lv. 0 | 0.09ms | https://school.programmers.co.kr/learn/courses/30/lessons/181933 |
| n의 배수 | 프로그래머스 | Lv. 0 | 0.01ms | https://school.programmers.co.kr/learn/courses/30/lessons/181937?language=c |
- 홀짝 구분하기 : 주어진 n이 짝수라면 "n is even"을, 홀수라면 "n is odd" 출력하기
- flag에 따라 다른 값 반환하기 : flag가 true라면 a + b의 결과를, false라면 a - b의 결과를 출력하기
- n의 배수 : num이 n의 배수라면 1 반환, 아니라면 0 반환하기
***
오늘은 문제를 푼 시간 보다 git과 vscode의 문제를 해결하는 시간이 더 …

[3일차] 이지인 / 홀짝 구분하기 외 2개

---

Jihyun/Programmers_MorseCode.java

| 2024.03.06 | 3일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 모스부호 (1) | 프로그래머스 | Level.0 | 12.45ms | https://school.programmers.co.kr/learn/courses/30/lessons/120838 |
- 모스부호 (1): 모스부호로 이루어진 문자열 letter가 주어질 때 letter를 소문자 영어로 해석하는 프로그램

[3일차] 김지현 / 모스부호

---

Jinseon/remember_score.java

https://school.programmers.co.kr/learn/courses/30/lessons/176963
| 2024.03.06 | 3일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 추억 점수 | 프로그래머스 | Level1 | 2.33ms | https://school.programmers.co.kr/learn/courses/30/lessons/176963 |
- 추억 점수 : HashMap을 사용하여 name과 yearning을 저장한 후에 Key와 같은 photo가 있는지 확인하여 점수를 더했다.

[3일차] 이진선 / 추억 점수

---

Hyeseung/Baekjoon/_29863.java
Hyeseung/Baekjoon/_30676.java

| 2024.03.07 | 4일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 이 별은 무슨 색일까 | 백준 | 브론즈 V | 204ms | https://www.acmicpc.net/problem/30676 |
- 이 별은 무슨 색일까 : 
빨간색: 620nm 이상 780nm 이하
주황색: 590nm 이상 620nm 미만
노란색: 570nm 이상 590nm 미만
초록색: 495nm 이상 570nm 미만
파란색: 450nm 이상 495nm 미만
남색: 425nm 이상 450nm 미만
보라색: 380nm 이상 425nm 미만
다음의 색을 프린트하기

[4일차] 김혜승 / 이 별은 무슨 색일까

---

Jiin/print_a_b.js

| 2024.03.07 | 4일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `JavaScript` |
| a와 b 출력하기 | 프로그래머스 | Lv. 0 | 59.52ms | https://school.programmers.co.kr/learn/courses/30/lessons/181951?language=javascript |
- a와 b 출력하기 : a와 b의 값을 a = a b = b라는 형태로 출력하기

[4일차] 이지인 / a와 b 출력하기

---

Jinseon/qr_code.java

https://school.programmers.co.kr/learn/courses/30/lessons/181903
| 2024.03.06 | 4일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| qr code | 프로그래머스 | Level 0 | 14.13ms | https://school.programmers.co.kr/learn/courses/30/lessons/181903 |
- qr code : charAt()로 나눠서 원하는 문자를 더하기

[4일차] 이진선 / qr code

---

Sunhee/programmers/같은 숫자는 싫어.java
Sunhee/programmers/문자열 내림차순으로 배치하기.java
Sunhee/programmers/제일 작은 수 제거하기.java
Sunhee/programmers/최대공약수와 최소공배수.java

| 문자열 내림차순으로 정렬하기 | 프로그래머스 | 브론즈 V | 208ms | https://school.programmers.co.kr/learn/courses/30/lessons/12917 |
| 최대공약수와 최소공배수 | 프로그래머스 | 브론즈 V | 208ms | https://school.programmers.co.kr/learn/courses/30/lessons/12940 |
| 같은 숫자는 싫어 | 프로그래머스 | 브론즈 V | 208ms | https://school.programmers.co.kr/learn/courses/30/lessons/12906 |
- 문자열 s에 나타나는 문자를 큰것부터 작은 순으로 정렬해 새로운 문자열을 리턴하는 함수, solution을 완성해주세요.
s는 영문 대소문자로만 구성되어 있으며, 대문자는 소문자보다 작은 것으로 간주합니다.
- 두 수를 입력받아 두 수의 최대공약수와 최소공배수를 반환하는 함수, solution을 완성해 보세요. 배열의 맨 앞에 최대공약수, 그다음 최소공배수를 넣어 반환하면 됩니다. 예를 들어 두 수 3, …

[5일차] 김선희 / 같은 숫자는 싫어 외 2개

---

Jiin/find_the_string's_tail.js

| 2024.03.08 | 5일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `JavaScript` |
| 특정 문자열로 끝나는 가장 긴 부분 문자열 찾기 | 프로그래머스 | Lv.0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/181872?language=javascript |
- 특정 문자열로 끝나는 가장 긴 부분 문자열 찾기 
: 문자열 myString과 이 문자열속 문자들로 조합된 문자열 pat이 주어질 때, myString에서 pat로 끝나는 가장 긴 문자열 반환

[5일차] 이지인 / 특정 문자열로 끝나는 가장 긴 부분 문자열 찾기

---

Jihyun/Programmers_FindTheNearest1.java

| 2024.03.09 | 6일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 가까운 1 찾기 | 프로그래머스 | Level.0 | 0.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/181898 |
- 가까운 1 찾기: 정수 배열 arr가 주어질 때 정수 idx보다 크면서 배열의 값이 1인 가장 가까운 값을 찾는 코드

[6일차] 김지현 / 가까운 1 찾기

---

Sunhee/programmers/예산.java

https://school.programmers.co.kr/learn/courses/30/lessons/12982
| 2024.03.09 | 6일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 예산 | 프로그래머스 | Lv.1 | 208ms | https://school.programmers.co.kr/learn/courses/30/lessons/12982 |
- S사에서는 각 부서에 필요한 물품을 지원해 주기 위해 부서별로 물품을 구매하는데 필요한 금액을 조사했습니다. 그러나, 전체 예산이 정해져 있기 때문에 모든 부서의 물품을 구매해 줄 수는 없습니다. 그래서 최대한 많은 부서의 물품을 구매해 줄 수 있도록 하려고 합니다.
물품을 구매해 줄 때는 각 부서가 신청한 금액만큼을 모두 지원해 줘야 합니다. 예를 들어 1,000원을 신청한 부서에는 정확히 1,000원을 지원해야 하며, 1,000원보다 적은 금액을 지원해 줄 수는 없습니다.
부서별로 신청한 금액이 들어있는 배열 d와 예산 budget이 매개변수로 주어질 때, 최대 몇 개의 부서에 물품을 지원할 수 있는지 return 하도록 solution 함수를 완성해주세요.

[6일차] 김선희 / 예산 Lv.1

---

Jihyun/Programmers_CollatzConjecture.java

| 2024.03.10 | 7일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 콜라츠 추측 | 프로그래머스 | Level.1 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/12943 |
- 콜라츠 추측: 숫자 num이 주어졌을 때 콜라츠 추측을 통해 몇 번 만에 1이 만들어졌는지 출력하는 프로그램 (단, 500번을 넘었을 경우 -1 출력)

[7일차] 김지현 / 콜라츠 추측

---

Jiin/YourGrade.java

| 2024.03.10 | 7일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `eclipse` |
| 너의 평점은 | 백준 | 실버 V | 84ms | https://www.acmicpc.net/problem/25206 |
- 너의 평점은 : 치훈이의 전공 평점을 계산하는 프로그램을 만들어 보자!
전공평점은 전공과목별 (학점 × 과목평점)의 합을 학점의 총합으로 나눈 값이다.
등급에 따른 과목 평점은 다음과 같다.
| 등급 | 과목 평점 |
| ----- | ----- |
| A+ | 4.5 |
| A0 | 4.0 |
| B+ | 3.5 |
| B0 | 3.0 |
| C+ | 2.5 |
| C0 | 2.0 |
| D+ | 1.5 |
| D0 | 1.0 |
| F | 0.0 |

[7일차] 이지인 / 너의 평점은

---

Hyeseung/Baekjoon/_29731.java
Hyeseung/Baekjoon/_30030.java

| 2024.03.10 | 7일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 2033년 밈 투표 | 백준 | 브론즈 V | 124ms | https://www.acmicpc.net/problem/29731 |
| 스위트콘 가격 구하기 | 백준 | 브론즈 V | 204ms | https://www.acmicpc.net/problem/30030 |
- 2033년 밈 투표 : 하나라도 안맞으면 Yes, 맞으면 No를 출력하기
- 스위트콘 가격 구하기 : n - n / 11 구하기

[7일차] 김혜승 / 2033년 밈 투표 외 1개

---

Jinseon/phone_number.java

https://school.programmers.co.kr/learn/courses/30/lessons/12948
| 2024.03.010 | 7일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 핸드폰 번호 가리기 | 프로그래머스 | Level 1 | 2.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/12948 |
- 핸드폰 번호 가리기 : repeat를 사용한 반복과 substring을 사용한 원하는 인덱스부터 자르기를 사용하여 번호 가리기

[7일차] 이진선 / 핸드폰 번호 가리기

---

Sunhee/programmers/문자열 내림차순으로 배치하기.java
Sunhee/programmers/행렬의 덧셈.java

| 2024.03.11 | 8일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 행렬의 덧셈 | 프로그래머스 | Lv.1 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/12950 |
- 행렬의 덧셈은 행과 열의 크기가 같은 두 행렬의 같은 행, 같은 열의 값을 서로 더한 결과가 됩니다. 2개의 행렬 arr1과 arr2를 입력받아, 행렬 덧셈의 결과를 반환하는 함수, solution을 완성해주세요.

[8일차] 김선희 / 행렬의 덧셈 외 1

---

Jiin/between_x.js

| 2024.03.11 | 8일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `JavaScript` <br> `vscode` |
| x 사이의 개수 | 프로그래머스 | Lv. 0 | 5.26ms | https://school.programmers.co.kr/learn/courses/30/lessons/181867?language=javascript |
- x 사이의 개수 : 문자열 myString을 x로 나눴을 때, 나눠진 문자열들의 길이를 순서대로 배열에 담아서 반환하기

[8일차] 이지인 / x 사이의 개수

---

Jinseon/color_count.java
Jinseon/xy_sum.java

| 2024.03.011 | 8일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 행렬의 덧셈 | 프로그래머스 | Level 1 | 4.39ms | https://school.programmers.co.kr/learn/courses/30/lessons/12950 |
| [PCCE 기출문제] 9번 / 이웃한 칸 | 프로그래머스 | Level 1 | 0.05ms | https://school.programmers.co.kr/learn/courses/30/lessons/250125 |
- 행렬의 덧셈 : 배열의 인덱스를 이용한 문제
- 이웃한 칸 : 배열의 인덱스를 이용한 문제(런타임 에러가 나서 for문을 사용함)

[8일차] 이진선 / 행렬의 덧셈 외 1

---

Jihyun/Programmers_CalculateInsufficientAmount.java

| 2024.03.11 | 8일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 부족한 금액 계산하기 | 프로그래머스 | Level.0 | 0.20ms | https://school.programmers.co.kr/learn/courses/30/lessons/82612 |
- 부족한 금액 계산하기: 놀이기구의 원래 이용료인 금액인 price변수의 count만큼 이용한다면 현재 금액 변수인 money가 얼마나 부족한지 계산하는 코드

[8일차] 김지현 / 부족한 금액 계산하기

---

Sunhee/programmers/두 개 뽑아서 더하기.java
Sunhee/programmers/음양 더하기.java

| 2024.03.012 | 9일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 음양 더하기  | 프로그래머스 | Lv.1 | 0.03ms |https://school.programmers.co.kr/learn/courses/30/lessons/76501 |
- 어떤 정수들이 있습니다. 이 정수들의 절댓값을 차례대로 담은 정수 배열 absolutes와 이 정수들의 부호를 차례대로 담은 불리언 배열 signs가 매개변수로 주어집니다. 실제 정수들의 합을 구하여 return 하도록 solution 함수를 완성해주세요.

[9일차] 김선희 / 음양 더하기 외 1

---

Jiin/Next_in_line.c

| 2024.03.12 | 9일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `C` |
| Next in line | 백준 | 브론즈 IV | 0ms | https://www.acmicpc.net/problem/6749 |
- Next in line : 당신은 한 가정에 세 아이가 있다는 것을 알고 있습니다. 첫째 둘째의 나이차는 둘째와 막내의 나이차와 같습니다. 첫 줄에 막내의 나이가, 둘째 줄에 둘째의 나이가 주어진다면, 첫째의 나이는 얼마인지 출력하시오.
***
백준을 둘러보다가 발견한 문제입니다. 분명히 브론즈 V급의 난이도인데, 
문제 설명이 영어여서 어림 짐작하며 문제를 풀었습니다.
이렇게 영어를 잘 해야 하는 이유가 또 하나 늘어났습니다...

[9일차] 이지인 / Next in line

---

Hyeseung/Baekjoon/_30087.java
Hyeseung/Baekjoon/_30214.java

| 2024.03.12 | 9일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.11 java` <br> `vscode` |
| 진흥원 세미나 | 백준 | 브론즈 V | 208ms | https://www.acmicpc.net/problem/30087 |
| An Easy-Peasy Problem | 백준 | 브론즈 V | 220ms | https://www.acmicpc.net/problem/30214 |
- 진흥원 세미나 : 세미나를 입력받아 그 세미나의 교실을 출력하기
- An Easy-Peasy Problem : 어떤 문제를 대회 중간에 푼 사람 수를 S1, 대회 막바지까지 푼 사람 수를 S2라 할 때, S1이 S2의 절반 이상일 경우, 그 문제는 쉬운 문제이다. 쉬운 문제이면 E, 그렇지 않으면 M을 출력하기

[9일차] 김혜승 / 진흥원 세미나 외 1개

---

Jinseon/same_num.java

https://school.programmers.co.kr/learn/courses/30/lessons/12906
| 2024.03.012 | 9일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 같은 숫자는 싫어 | 프로그래머스 | Level 1 | 57.66ms | https://school.programmers.co.kr/learn/courses/30/lessons/12906 |
- 같은 숫자는 싫어  :  stack을 사용한 풀이(효율은 그다지 좋지 않다....)

[9일차] 이진선 / 같은 숫자는 싫어

---

Jihyun/Programmers_LastTwoElements.java

| 2024.03.12 | 9일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 마지막 두 원소 | 프로그래머스 | Level.0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/181927 |
- 마지막 두 원소: 정수 리스트 num_list가 주어질 때 마지막 원소가 그전 원소보다 크면 마지막 원소에서 그전 원소를 뺀 값을 추가하고, 마지막 원소가 그전 원소보다 크지 않다면 마지막 원소를 두 배한 값을 배열에 추가하는 프로그램

[9일차] 김지현 / 마지막 두 원소

---

Hyeseung/Baekjoon/_30224.java
Hyeseung/Baekjoon/_30328.java
Hyeseung/Baekjoon/_30664.java
Hyeseung/Baekjoon/_31429.java
Hyeseung/Baekjoon/_31450.java

| 2024.03.13 | 10일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.11 java` <br> `vscode` |
| Lucky 7 | 백준 | 브론즈 V | 208ms | https://www.acmicpc.net/problem/30224 |
| Java Warriors | 백준 | 브론즈 V | 204ms | https://www.acmicpc.net/problem/30328 |
| SUAPC 2023 Summer | 백준 | 브론즈 V | 200ms | https://www.acmicpc.net/problem/31429 |
| Everyone is a winner | 백준 | 브론즈 V | 208ms | https://www.acmicpc.net/problem/31450 |
| Loteria Falha | 백준 | 브론즈 V | 236ms | https://www.acmicpc.net/problem/30664 |
-  Lucky 7 :
숫자에 7이 포함되지 않고 7로 나누어지지 않으면 0을 인쇄합니다.
숫자에 7이 포함되어 있지 않지만 7로 나눌 수 있으면 1을 인쇄합니다.
숫자에 7이 포함되어 있지만 7로 나누어지지 않으면 2를 인쇄합니다.
숫자에 7이 포함되어 있고 7로 나눌 …

[10일차] 김혜승 / Lucky 7 외 4개

---

Jinseon/evenodd.java

| 2024.03.13 | 10일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 홀짝구분하기 | 프로그래머스 | Level 1 | 199.27ms | https://school.programmers.co.kr/learn/courses/30/lessons/181944 |
- 홀짝 구분하기 : Scanner를 이용해 n를 입력받아 n이 홀수인지 짝수인지 출력

[10일차] 이진선 / 홀짝 구분하기

---

Jiin/Make_1.java

| 2024.03.13 | 10일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 1로 만들기 | 프로그래머스 | Lv. 0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/181880 |
- 1로 만들기 : 홀수면 - 1 하고 2로 나누고, 짝수면 그냥 2로 나눈다. 이를 반복하면 어느 순간 1이 되는데, 이 단계의 수를 구해라

[10일차] 이지인 / 1로 만들기

---

Sunhee/programmers/나머지가 1이 되는 수 찾기.java
Sunhee/programmers/없는 숫자 더하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/86051?language=java
| 2024.03.14 | 11일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 없는 숫자 더하기 | 프로그래머스 | Lv.1 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/86051?language=java |
-0부터 9까지의 숫자 중 일부가 들어있는 정수 배열 numbers가 매개변수로 주어집니다. numbers에서 찾을 수 없는 0부터 9까지의 숫자를 모두 찾아 더한 수를 return 하도록 solution 함수를 완성해주세요.

[11일차] 김선희 / 없는 숫자 더하기 

---

Hyeseung/Baekjoon/_31606.java
Hyeseung/Baekjoon/_31610.java
Hyeseung/Baekjoon/_31611.java
Hyeseung/Baekjoon/_31614.java

| 2024.03.06 | 11일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.11 java` <br> `vscode` |
| 果物 (Fruit) | 백준 | 브론즈 V | 204ms | https://www.acmicpc.net/problem/31606 |
| 飴の袋詰め (Drops Packing)| 백준 | 브론즈 V | 200ms | https://www.acmicpc.net/problem/31610 |
| 火曜日 (Tuesday) | 백준 | 브론즈 V | 204ms | https://www.acmicpc.net/problem/31611 |
| 分 (Minutes) | 백준 | 브론즈 V | 204ms | https://www.acmicpc.net/problem/31614 |
- 果物 (Fruit) : 사과 + 미칸 + 바나나의 총 갯수 구하기
- 飴の袋詰め (Drops Packing) : 사탕 * 개수 + 봉투 개수 구하기
- 火曜日 (Tuesday) : 일요일에서 X일 후가 화요일이면 1, 아니면 0을 출력하기
- 分 (Minutes) : H : M 에서 시를 분으로 바꿔 총 몇분인지를 출력하기

[11일차] 김혜승 / 果物 (Fruit) 외 3개

---

Jinseon/clap.java
Jinseon/very_small_delete.java
Jinseon/weird_string.java

| 2024.03.014 | 11일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 제일 작은 수 | 프로그래머스 | Level 1 | 0.08ms | https://school.programmers.co.kr/learn/courses/30/lessons/12935 |
| 이상한 문자 만들기 | 프로그래머스 | Level 1 | 3.37ms | https://school.programmers.co.kr/learn/courses/30/lessons/12930 |
| 수박수박수박수박수박수? | 프로그래머스 | Level 1 | 46.90ms | https://school.programmers.co.kr/learn/courses/30/lessons/12922 |
- 제일 작은 수 : 런타임 에러가 나서 찾아보니까 인덱스를 입력할 떄 i가 아니라 변수에 저장해서 사용하는 것이 더 빠르다는 사실을 알게 되었다.
- 이상한 문자 만들기 : toUpperCase()와 toLowerCase() 사용하여 대소문자를 만들고 s.substring(i, i+1)을 사용하여 1개의 문자를 뽑아냈다. 하지만 substring이 아니라 charAt()와 Charater를 사용하여 …

[11일차] 이진선 / 이상한 문자 만들기 외 2개

---

Jiin/LeastCommonMultiple.java

| 최소 공배수 | 백준 | 브론즈 I | 504ms | https://www.acmicpc.net/problem/1934 |
- 최소 공배수 : n개의 두 짝의 숫자들을 받아 각각 그 숫자들의 최소공배수를 출력하시오.

[11일차] 이지인 / 최소 공배수

---

Jiin/Gift_Index.js

| 2024.03.15 | 12일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `JavaScript` |
| 가장 많이 받은 선물 | 프로그래머스 | Lv. 1 | 11.19ms | https://school.programmers.co.kr/learn/courses/30/lessons/258712 |
- 가장 많이 받은 선물 : 친구들끼리 선물을 주고받을 수 있습니다. 이번 달의 선물을 주고받은 기록을 바탕으로 다음 달 누가 선물을 많이 받을지 예측하시오.
&nbsp;&nbsp;&nbsp;&nbsp; A와 B가 선물을 주고 받았을 때, 더 많이 선물한 쪽이 더 많이 선물 받은 쪽에게 선물을 받습니다.
&nbsp;&nbsp;&nbsp;&nbsp; 만약 A와 B가 선물을 주고받은 횟수가 같거나 없다면, 선물지수가 높은 사람이 더 낮은 사람에게 선물을 받습니다.
&nbsp;&nbsp;&nbsp;&nbsp; 선물 지수는 내가 선물을 준 횟수 - 내가 선물을 받은 횟수 입니다.
&nbsp;&nbsp;&nbsp;&nbsp; 만약 선물 지수까지 같다면 선물을 주고받지 않습니다.
***
Lv. 1인데 정답률이 22%라서 시도하는 것에 굉장히 풀죽어 있었습니다. 
하지만 금요일마다 어려운 문제를 풀기로 하였으니 우선 …

[12일차] 이지인 / 가장 많이 받은 선물

---

Jihyun/Programmers/MemoriesScore.java

| 2024.03.15 | 12일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 추억 점수 | 프로그래머스 | Level.1 | 2.25ms | https://school.programmers.co.kr/learn/courses/30/lessons/176963 |
- 추억 점수 : 사진 속에 나오는 인물의 그리움 점수를 모두 합산한 값인 추억 점수를 구하는 프로그램

[12일차] 김지현 / 추억 점수

---

Jinseon/bandage.java

https://school.programmers.co.kr/learn/courses/30/lessons/250137
| 2024.03.016 | 12일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| [PCCP 기출문제] 1번 / 붕대 감기 | 백준 | Level 1| 0.10ms | https://school.programmers.co.kr/learn/courses/30/lessons/250137 |
- 붕대 감기 : while문을 사용한 턴 수 계산

[12일차] 이진선 / 붕대 감기

---

Jiin/CreateStar_7.java
Jiin/SnailWantsToGoUp.java

| 2024.03.17 | 13일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 달팽이는 올라가고 싶다 | 백준 | 브론즈 I | 112ms | https://www.acmicpc.net/problem/2869 |
| 별 찍기 - 7 | 백준 | 브론즈 III | 608ms | https://www.acmicpc.net/problem/2444 |
- 달팽이는 올라라고 싶다 : 달팽이는 낮에 A미터씩 올라갈 수 있고, 밤에 잠을 자느라 B미터씩 미끄러진다. 그렇다면 달팽이가 V미터의 막대를 올라가는데 며칠이 소요될까?
- 별 찍기 - 7 : n이 주어지면 예제의 규칙대로 2*n-1개의 줄 만큼 별을 찍으시오.

[13일차] 이지인 / 달팽이는 올라가고 싶다 외 1개

---

Hyeseung/Programmers/올바른괄호.java
Hyeseung/Programmers/최대공약수와 최소공배수.java

| 2024.03.17 | 13일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.11 java` <br> `vscode` |
| 올바른 괄호 | 프로그래머스 | Level.2 | 6.83ms | https://school.programmers.co.kr/learn/courses/30/lessons/12909 |
| 최대공약수와 최소공배수 | 프로그래머스 | Level.1 | 0.10ms | https://school.programmers.co.kr/learn/courses/30/lessons/12940 |
- 올바른 괄호 : 괄호가 바르게 짝지어졌다는 것은 '(' 문자로 열렸으면 반드시 짝지어서 ')' 문자로 닫혀야 한다는 뜻입니다. 
- 최대공약수와 최소공배수 : 두 수를 입력받아 두 수의 최대공약수와 최소공배수를 반환하는 함수, solution을 완성해 보세요.

[13일차] 김혜승 / 올바른 괄호 외 1개

---

Jinseon/rectangle.java

| 2024.03.17 | 13일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 최소직사각형 | 프로그래머스 | Level 1 | 3.31ms | https://school.programmers.co.kr/learn/courses/30/lessons/86491 |
- 최소직사각형 : Array.sort를 사용하여 작은 값을 정렬.

[13일차] 이진선 / 최소직사각형

---

Jihyun/Programmers/CountUp.java

| 2024.03.17 | 13일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 카운트 업 | 프로그래머스 | Level.0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/181920 |
- 카운트 업 : 정수 start_num와 end_num가 주어질 때, start_num부터 end_num까지의 숫자를 차례로 담은 리스트를 출력하는 프로그램

[13일차] 김지현 / 카운트 업

---

Jiin/StringsLength.java

| 2024.03.18 | 14일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 단어 길이 재기 | 백준 | 브론즈 V | 112ms | https://www.acmicpc.net/problem/2743 |
- 단어 길이 재기 : 입력 받은 단어의 길이를 출력하시오.

[14일차] 이지인 / 단어 길이 재기

---

Jinseon/countdown.java
Jinseon/stringlist.java
Jinseon/sumandsquare.java

| 2024.03.018 | 14일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 원소들의 합과 곱 | 프로그래머스 | Level 0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/181929 |
| 카운트 다운 | 프로그래머스 | Level 0 | 0.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/181899 |
| 문자 리스트를 문자열로 변환하기 | Level 0 | 4.21ms | https://school.programmers.co.kr/learn/courses/30/lessons/181941 |
- 원소들의 합과 곱 : 제어문을 활용한 합과 곱 구하기 
- 카운트 다운 : i--를 이용한 제어문 활용
- 문자 리스트를 문자열로 변환하기 : 제어문을 활용하여 문자열 이어붙이기

[14일차] 이진선 / 원소들의 합과 곱 외 2개

---

Jihyun/Programmers/ReadSpecialCharacters.java

| 특수문자 출력하기 | 프로그래머스 | Level.0 | 160.26ms | https://school.programmers.co.kr/learn/courses/30/lessons/181948 |
- 특수문자 출력하기 : 특수문자 !@#$%^&*()'"<>:; 를 출력하는 프로그램

[14일차] 김지현 / 특수문자 출력하기

---

Sunhee/programmers/덧찰하기.java
Sunhee/programmers/카드 뭉치.java

| 2024.03.019 | 15일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 카드 뭉치 | 프로그래머스 | Lv.1 | 13ms | https://school.programmers.co.kr/learn/courses/30/lessons/159994|
| 달리기 경주 | 프로그래머스 | Lv.1 | 23ms | https://school.programmers.co.kr/learn/courses/30/lessons/178871|
- 코니는 영어 단어가 적힌 카드 뭉치 두 개를 선물로 받았습니다. 코니는 다음과 같은 규칙으로 카드에 적힌 단어들을 사용해 원하는 순서의 단어 배열을 만들 수 있는지 알고 싶습니다.
원하는 카드 뭉치에서 카드를 순서대로 한 장씩 사용합니다.
한 번 사용한 카드는 다시 사용할 수 없습니다.
카드를 사용하지 않고 다음 카드로 넘어갈 수 없습니다.
기존에 주어진 카드 뭉치의 단어 순서는 바꿀 수 없습니다.
예를 들어 첫 번째 카드 뭉치에 순서대로 ["i", "drink", "water"], 두 번째 카드 뭉치에 순서대로 ["want", "to"]가 적혀있을 때 ["i", "want", "to", "drink", "water"] …

[15일차] 김선희 / 카드 뭉치 외 1개

---

Jiin/Divide.c
Jiin/calculation_for_length.js

| 2024.03.19 | 15일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `JavaScript` <br> `C` |
| 길이에 따른 연산 | 프로그래머스 | Lv. 0 | 0.05ms | https://school.programmers.co.kr/learn/courses/30/lessons/181879 |
| 나누기 | 백준 | 브론즈 II | 0ms | https://www.acmicpc.net/problem/1075 |
- 길이에 따른 연산 : 배열 길이가 10 이하라면 그 배열 속 수들을 전부 곱해서 반환하면 됩니다. 만약 11 이상이라면 그 배열 속 수들을 전부 합해서 반환하면 됩니다.
- 나누기 : 두 정수 N과 F가 주어질 때, N에서 뒷자리 2개를 최대한 작은 수로 바꾸어 F를 나눌 때 나누어 떨어지게 하고싶은 소녀 지민이를 도와주세요. N의 최종적인 뒷자리 2개만 출력하면 됩니다.

[15일차] 이지인 / 길이에 따른 연산 외 1개

---

Jinseon/card_bundle.java

https://school.programmers.co.kr/learn/courses/30/lessons/159994
| 카드 뭉치  | 프로그래머스 | Level 1 | 0.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/159994 |
- 카드 뭉치 : 처음에는 두 개의 배열을 만들어서 하나 하나 골라오는 방식을 사용했더니 런타임 에러가 났다. 그래서 찾아보니 조건에 맞으면 인덱스를 늘리는 알고리즘을 알게 되었다.

[15일차] 이진선 / 카드뭉치

---

Jihyun/Programmers/nDrainage.java

| 2024.03.19 | 15일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| n의 배수 | 프로그래머스 | Level.0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/181937 |
- n의 배수: 정수 num과 n이 주어질 때, num이 n의 배수이면 1을, n의 배수가 아니라면 0을 출력하는 프로그램

[15일차] 김지현 / n의 배수

---

Jihyun/Programmers/SequenceAndIntervalQueries3.java

| 2024.03.20 | 16일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 수열과 구간 쿼리 3 | 프로그래머스 | Level.0 | 0.07ms | https://school.programmers.co.kr/learn/courses/30/lessons/181924 |
- 수열과 구간 쿼리 : 정수 배열 arr과 2차원 정수 배열 queries가 주어짐
queries의 원소는 query이며, [i, j] 꼴일 때 모든 queries의 query[i]와 query[j]의 값을 서로 바꾼 배열을 출력하는 프로그램

[16일차] 김지현 / 수열과 구간 쿼리 3

---

Jiin/runner.js

| 달리기 경주 | 프로그래머스 | Lv. 1 | 8201.57ms | https://school.programmers.co.kr/learn/courses/30/lessons/178871?language=javascript |
- 달리기 경주 : 현재 달리기 선수들의 1등부터 들어있는 배열 players와 해설진들의 해설이 담긴 배열 callings가 주어집니다. 해설진들은 달리기 선수중 1등을 제외한 모든 선수들 중 한 명의 이름을 부릅니다. 그러면 이름을 불린 선수가 바로 자기 앞 선수를 추월했다는 해설입니다. 그렇다면 해설진들의 모든 해설이 끝난 후 달리기 선수들의 등급을 반환하시오
***
제가 이 문제를 너무너무 풀고싶어서 JS로도 풀어보고 Java로도 풀어보고 C로도 풀어봤던 기억이 있습니다.
하지만 전부 시간초과가 떠 어찌해야 할지 모르고 결국 포기를 했었습니다.
그러나 12일차때 풀었던 '가장 많이 받은 선물' 을 풀고 영감을 받아
시간이 오래걸리는 선수 이름 찾는 방법을 indexOf()에서 Map()을 이용하였더니
시간초과가 뜨지 않고 잘 할 수 있었습니다. …

[16일차] 이지인 / 달리기 경주

---

Jihyun/Programmers/FindNumberWhoseRemainderIs1.java
Jihyun/Programmers/FlipStringMultipleTimes.java

| 2024.03.21 | 17일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 문자열 여러 번 뒤집기 | 프로그래머스 | Level.0 | 5.43ms | https://school.programmers.co.kr/learn/courses/30/lessons/181913 |
| 나머지가 1이 되는 수 찾기 | 프로그래머스 | Level.1 | 8.38ms | https://school.programmers.co.kr/learn/courses/30/lessons/87389 |
- 문자열 여러 번 뒤집기 : 문자열 my_string과 이차원 정수 배열 queries(원소: [s, e] 형태)가 매개변수로 주어질 때, my_string을 인덱스 s부터 인덱스 e까지 뒤집어 출력하는 프로그램
- 나머지가 1이 되는 수 찾기: n을 x로 나눈 나머지가 1이 되도록 하는 가장 작은 자연수 x를 출력하는 프로그램

[17일차] 김지현 / 문자열 여러 번 뒤집기 외 1개

---

Jinseon/array_length.java
Jinseon/first_negative.java

| 2024.03.021 | 16일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 배열의 길이에 따라 다른 연산하기 | 프로그래머스 | Level 0 | 0.10ms | https://www.acmicpc.net/problem/1000 |
| 첫 번째로 나오는 음수 | 프로그래머스 | Level 0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/181896 |
- 배열의 길이에 따라 다른 연산하기 : for문과 if문을 통해 해결했다. 하지만 다른 풀이를 찾아보니까 i -= 2를 사용하여 if문 없이 해결하는 것을 보고 또 한 번 for문 활용법을 배울 수 있었다.
-  첫 번째로 나오는 음수 : 첫번째 음수를 리턴하는 것이었기 때문에 for문과 return을 통해 쉽게 풀었다.

[17일차] 이진선 / 배열의 길이에 따라 다른 연산하기 외 1개

---

Jiin/change_to_lowercase.js

| 2024.03.21 | 17일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `JavaScript` |
| 소문자로 바꾸기 | 프로그래머스 | Lv.0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/181876 |
- 소문자로 바꾸기 : 주어진 문자열을 소문자로 바꾼 후 반환

[17일차] 이지인 / 소문자로 바꾸기 

---

Jiin/Fibonacci.java

| 2024.03.22 | 18일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 피보나치 수 | 프로그래머스 | Lv. 2 | 208ms | https://school.programmers.co.kr/learn/courses/30/lessons/12945 |
- 피보나치 수 : n번째 피보나치 수를 1234567으로 나눈 나머지를 리턴하는 함수, solution을 완성
***
어려운 코테 풀기~~ 두 번째 시간은 생각보다 빨리 끝났습니다.
분명 Lv.2 지만 정답률은 76%로 저번에 했던 '가장 많이 받은 선물'보다 훨씬 높았기 때문입니다.
그렇다고 술술 잘 풀린건 아니었습니다. 테스트 케이스는 한 번에 잘 되었지만,
제출하면 절반만 맞고 절반이 틀렸다고 나왔습니다.
저는 절반의 붉은 글씨를 읽다 '아, int형으로 해서 오버플로우 됐나보다!' 라고 하여 int를 전부 long형으로 바꾸었지만
결과는 같았습니다.
그제서야 저는 문제를 꼼꼼히 읽었고 n의 최대치가 100,000이라는 사실을 눈치챘습니다.
네.. long으로도 어림 없었습니다. 저는 long보다 더 메모리가 큰 데이터형을 몰랐기에
질문하기 탭에서 저와 같은 문제(절반만 맞음)로 고민중인 …

[18일차] 이지인 / 피보나치 수

---

Jinseon/last_one.java
Jinseon/weare3.java

| 나머지가 1이 되는 수 | 프로그래머스 | Level 0 | 5.24ms | https://school.programmers.co.kr/learn/courses/30/lessons/87389 |
| 삼총사 | 프로그래머스 | Level 1 | 0.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/131705 | 
- 나머지가 1이 되는 수 : 나머지가 1이 될 때까지 n을 나눴다.
- 삼총사 : 3개의 값을 더했을 때 0이 되면 answer++하는 문제이다. 경우의 수를 생각하면 쉽다. 3중 for문을 사용하며 i, j, k의 초기화 값을 i가 1이면 i + 1로 초기화 해줘서 중복을 없애고 for문 i는 length - 2(3명이니까.) 시켜주면서 풀었다.

[18일차] 이진선 / 나머지가 1이 되는 수 외 1개

---

Hyeseung/Programmers/잔챙이 잡은 수 구하기.sql

https://school.programmers.co.kr/learn/courses/30/lessons/293258
| 2024.03.22 | 18일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `sql` <br> `vscode` |
| 잔챙이 잡은 수 구하기 | 프로그래머스 | Level.1 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/293258 |
- 잔챙이 잡은 수 구하기 : 잡은 물고기 중 길이가 10cm 이하인 물고기의 수를 출력하는 SQL 문을 작성해주세요.
물고기의 수를 나타내는 컬럼 명은 FISH_COUNT로 해주세요.

[18일차] 김혜승 / 잔챙이 잡은 수 구하기

---

Sunhee/programmers/가장 많이 받은 선물.java
Sunhee/programmers/짝수와 홀수.java

https://school.programmers.co.kr/learn/courses/30/lessons/181854
| 2024.03.23 | 19일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 배열의 길이에 따라 다른 연산하기 | 프로그래머스 | Lv.0 | 0.3ms | https://school.programmers.co.kr/learn/courses/30/lessons/181854 |
- 정수 배열 arr과 정수 n이 매개변수로 주어집니다. arr의 길이가 홀수라면 arr의 모든 짝수 인덱스 위치에 n을 더한 배열을, arr의 길이가 짝수라면 arr의 모든 홀수 인덱스 위치에 n을 더한 배열을 return 하는 solution 함수를 작성해 주세요

[19일] 김선희 / 배열의 길이에 따라 다른 연산하기

---

Hyeseung/Programmers/Python 개발자 찾기.sql

| 2024.03.06 | 1일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `sql` <br> `vscode` |
| Python 개발자 찾기 | 프로그래머스 | Level.1 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/276013 |
- Python 개발자 찾기 : DEVELOPER_INFOS 테이블에서 Python 스킬을 가진 개발자의 정보를 조회하려 합니다. Python 스킬을 가진 개발자의 ID, 이메일, 이름, 성을 조회하는 SQL 문을 작성해 주세요. 결과는 ID를 기준으로 오름차순 정렬해 주세요.

[19일차] 김혜승 / Python 개발자 찾기

---

Jiin/DifferenceCalculationForArrayLength.java

| 2024.03.23 | 19일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 배열의 길이에 따라 다른 계산하기 | 프로그래머스 | Lv. 0 | 0.06ms | https://school.programmers.co.kr/learn/courses/30/lessons/181854 |
- 배열의 길이에 따라 다른 계산하기 : 배열 arr의 길이가 짝수라면 arr의 모든 짝수 인덱스에 정수n을 더하고, 홀수라면 모든 홀수 인덱스에 n을 더한 배열을 반환합니다.
***
친구가 저에게 구미가 당기는 추천을 해주었습니다.
바로 자신이 주는 코테를 for문 한 개만 써서 푸는 것이었습니다.
저는 너무 재밌어 보여서 바로 도전하였습니다. 문제 푸는 시간은 별로 안 걸렸지만
평소처럼 코테를 하면 if문 두 개 정도 썼을 것 같았습니다.
덕분에 이런 문제를 줄여 쓸 수 있구나를 깨달아서 기쁩니다.

[19일차] 이지인 / 배열의 길이에 따라 다른 계산하기

---

Jinseon/CleanBackground.java

https://school.programmers.co.kr/learn/courses/30/lessons/161990
| 바탕화면 정리 | 프로그래머스 | Level 1| 0.32ms | hhttps://school.programmers.co.kr/learn/courses/30/lessons/161990 |
- 바탕화면 정리 : Integer.MAX_VALUE로 초기화 하기. Math함수를 써서 위치 구하기

[19일차] 이진선 / 바탕화면 정리

---

Jihyun/Programmers/ToComputeDifferentlyDependingOnTheLengthOfTheArray.java

| 2024.03.23 | 19일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 배열의 길이에 따라 다른 연산하기 | 프로그래머스 | Level.0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/181854 |
- 배열의 길이에 따라 다른 연산하기: 주어진 배열 arr의 길이가 짝수라면 arr의 모든 홀수 인덱스 위치에 정수 n을 더해 출력하는 프로그램

[19일차] 김지현 / 배열의 길이에 따라 다른 연산하기

---

Hyeseung/Programmers/가장 큰 물고기 10마리 구하기.sql

| 2024.03.24 | 20일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `sql` <br> `vscode` |
| 가장 큰 물고기 10마리 구하기 | 프로그래머스 | Level.1 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/298517 |
- 가장 큰 물고기 10마리 구하기 : FISH_INFO 테이블에서 가장 큰 물고기 10마리의 ID와 길이를 출력하는 SQL 문을 작성해주세요. 결과는 길이를 기준으로 내림차순 정렬하고, 길이가 같다면 물고기의 ID에 대해 오름차순 정렬해주세요. 단, 가장 큰 물고기 10마리 중 길이가 10cm 이하인 경우는 없습니다. ID 컬럼명은 ID, 길이 컬럼명은 LENGTH로 해주세요.

[20일차] 김혜승 / 가장 큰 물고기 10마리 구하기

---

Jiin/SumOfNumbers.java
Jiin/TheNumberOfNumbers.c

| 2024.03.24 | 20일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `C` |
| 숫자의 합 | 백준 | 브론즈 IV | 112ms | https://www.acmicpc.net/problem/11720 |
| 숫자의 개수 | 백준 | 브론즈 II | 0ms | https://www.acmicpc.net/problem/2577 |
- 숫자의 합 : 첫 번째 줄의 정수 n이 주어지고 두 번째 줄에 n자리 수의 정수들이 공백없이 주어진다. 이 정수들의 합을 출력하시오.
- 숫자의 개수 : 정수 A, B, C가 주어진다. 이 세 정수들의 곱한 결과에서 0~9까지의 숫자가 얼마나 쓰였는지 구한 후, 0~9가 쓰인 숫자를 차례로 한 줄씩 출력하시오.

[20일차] 이지인 / 숫자의 합 외 1개

---

Sunhee/programmers/K번째수.java

https://school.programmers.co.kr/learn/courses/30/lessons/42748
| 2024.03.24 | 20일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| K번째수 | 프로그래머스 | Lv.1 | 0.21ms | https://school.programmers.co.kr/learn/courses/30/lessons/42748 |
- 배열 array의 i번째 숫자부터 j번째 숫자까지 자르고 정렬했을 때, k번째에 있는 수를 구하려 합니다.
예를 들어 array가 [1, 5, 2, 6, 3, 7, 4], i = 2, j = 5, k = 3이라면
array의 2번째부터 5번째까지 자르면 [5, 2, 6, 3]입니다.
1에서 나온 배열을 정렬하면 [2, 3, 5, 6]입니다.
2에서 나온 배열의 3번째 숫자는 5입니다.
배열 array, [i, j, k]를 원소로 가진 2차원 배열 commands가 매개변수로 주어질 때, commands의 모든 원소에 대해 앞서 설명한 연산을 적용했을 때 나온 결과를 배열에 담아 return 하도록 solution 함수를 작성해주세요.

[20일차] 김선희 / K번째수 

---

Jinseon/nonumber.java

https://school.programmers.co.kr/learn/courses/30/lessons/86051?language=java
| 2024.03.024 | 20일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 없는 숫자 더하기 | 프로그래머스 | Level 1 | 0.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/86051?language=java |
- 없는 숫자 더하기 : 보기에 중복이 없기 때문에 다 더하고 45에서 빼는 식으로 계산했다.

[20일차] 이진선 / 없는 숫자 더하기

---

Jihyun/Programmers/Fruiterer.java

| 2024.03.24 | 20일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 과일 장수 | 프로그래머스 | Level.1 | 83.36ms | https://school.programmers.co.kr/learn/courses/30/lessons/135808 |
- 과일 장수: 사과 최대 점수 k와 사과 상자 개수 m, 사과 점수 배열 score이 주어질 때, (최저 사과 점수) x (한 상자에 담긴 사과 개수) x (상자의 개수) 공식을 통해 상자를 팔아 최대 이익을 출력하는 프로그램

[20일차] 김지현 / 과일 장수

---

Sunhee/programmers/핸드폰 번호 가리기.java

https://school.programmers.co.kr/learn/courses/30/lessons/12948
| 2024.03.25 | 21일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 핸드폰 번호 가리기 | 프로그머스 | Lv.1 | 0.12ms | https://school.programmers.co.kr/learn/courses/30/lessons/12948 |
- 프로그래머스 모바일은 개인정보 보호를 위해 고지서를 보낼 때 고객들의 전화번호의 일부를 가립니다.
전화번호가 문자열 phone_number로 주어졌을 때, 전화번호의 뒷 4자리를 제외한 나머지 숫자를 전부 *으로 가린 문자열을 리턴하는 함수, solution을 완성해주세요.

[21일차] 김선희 / 핸드폰 번호 가리기 

---

Hyeseung/Programmers/조건에 맞는 아이템들의 가격의 총합 구하기.sql

| 2024.03.25 | 21일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `sql` <br> `vscode` |
| 조건에 맞는 아이템들의 가격의 총합 구하기 | 프로그래머스 | Level.2 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/273709 |
- 조건에 맞는 아이템들의 가격의 총합 구하기 : ITEM_INFO 테이블에서 희귀도가 'LEGEND'인 아이템들의 가격의 총합을 구하는 SQL문을 작성해 주세요. 이때 컬럼명은 'TOTAL_PRICE'로 지정해 주세요.

[21일차] 김혜승 / 조건에 맞는 아이템들의 가격의 총합 구하기

---

Jiin/HideThePhoneNumber.c

| 2024.03.25 | 21일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `C` |
| 핸드폰 번호 가리기 | 프로그래머스 | Lv. 1 | 0.02ms | https://school.programmers.co.kr/learn/courses/30/lessons/12948?language=c |
- 핸드폰 번호 가리기 : 핸드폰 번호 4~20자가 주어질 때, 뒤 4자리 빼고 전부 *로 가린 전화번호 반환하기

[21일차] 이지인 / 핸드폰 번호 가리기

---

Jinseon/paint.java
Jinseon/scarce_money.java

| 2024.03.025 | 21일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 부족한 금액 계산하기 | 프로그래머스 | Level 1 | 0.29ms | https://school.programmers.co.kr/learn/courses/30/lessons/82612?language=java |
| 덧칠하기 | 프로그래머스 | Level 1 | 1.95ms | https://school.programmers.co.kr/learn/courses/30/lessons/161989 |
- 부족한 금액 계산하기 : for문과 if문을 이용한 간단한 풀이
- 덧칠하기 : start와 end를 정해서 조건에 많게 덧칠한 수 구하기

[21일차] 이진선 / 부족한 금액 계산하기 외 1

---

Hyeseung/Programmers/ROOT 아이템 구하기.sql
Hyeseung/Programmers/경기도에 위치한 식품창고 목록 출력하기.sql
Hyeseung/Programmers/과일로 만든 아이스크림 고르기.sql
Hyeseung/Programmers/나이 정보가 없는 회원 수 구하기.sql
Hyeseung/Programmers/이름이 없는 동물의 아이디.sql
Hyeseung/Programmers/이름이 있는 동물의 아이디.sql
Hyeseung/Programmers/잡은 물고기 중 가장 큰 물고기의 길이 구하기.sql
Hyeseung/Programmers/특정 물고기를 잡은 총 수 구하기.sql

| 2024.03.26 | 22일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `sql` <br> `vscode` |
| 잡은 물고기 중 가장 큰 물고기의 길이 구하기 | 프로그래머스 | Level.1 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/298515 |
| 이름이 없는 동물의 아이디 | 프로그래머스 | Level.1 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/59039 |
| 이름이 있는 동물의 아이디  | 프로그래머스 | Level.1 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/59407 |
| 경기도에 위치한 식품창고 목록 출력하기 | 프로그래머스 | Level.1 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/131114 |
| 나이 정보가 없는 회원 수 구하기 | 프로그래머스 | Level.1 | 0ms | …

[22일차] 김혜승 / 잡은 물고기 중 가장 큰 물고기의 길이 구하기 외 7개

---

Jiin/RemainderIs1.java

| 2024.03.26 | 22일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 나머지가 1이 되는 수 | 프로그래머스 | Lv. 1 | 17.13ms | https://school.programmers.co.kr/learn/courses/30/lessons/87389?language=java |
- 나머지가 1이 되는 수 : 주어진 수 n에서 x를 나누면 나머지가 1이다. 이때 x가 될 수 있는 가장 작은 수는?

[22일차] 이지인 / 나머지가 1이 되는 수

---

Jinseon/Fame.java

https://school.programmers.co.kr/learn/courses/30/lessons/138477?language=java
| 2024.03.26 | 21일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 명예의 전당(1) | 프로그래머스 | Level 1 | 6.59ms | https://school.programmers.co.kr/learn/courses/30/lessons/138477?language=java |
- 명예의 전당 : ArrayList와 size(), Collection.min() 등을 사용하여 가장 낮은 점수를 구했다. ArrayList 문법이 기억나지 않아 약간 창피했지만 다시 외우고... 까먹지 않을 것 같아서 좋았다...ㅠ

[22일차] 이진선 / 명예의 전당(1)

---

1st/Jiin/BiggestFish10.sql

| 2024.03.27 | 23일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `mysql` |
| 가장 큰 물고기 10마리 구하기 | 프로그래머스 | Lv. 1 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/298517 |
- 가장 큰 물고기 10마리 구하기 : FISH_INFO 테이블에서 길이가 긴 물고기부터 차례로 10마릴 출력하기. 만약 길이가 같다면 물고기의 ID를 오름차순으로 정렬한다.

[23일차] 이지인 / 가장 큰 물고기 10마리 구하기

---

1st/Sunhee/programmers/자릿수 더하기.java
1st/Sunhee/programmers/평균 구하기.java
1st/Sunhee/programmers/하샤드 수.java

| 하샤드 수 | 프로그래머스 | Lv.1 | 0.35ms | https://school.programmers.co.kr/learn/courses/30/lessons/12947 |
| 평균 구하기 | 프로그래머스 | Lv.1 | 0.12ms | https://school.programmers.co.kr/learn/courses/30/lessons/12944 |
| 자릿수 더하 | 프로그래머스 | Lv.1 | 0.12ms | https://school.programmers.co.kr/learn/courses/30/lessons/12931 |
- 양의 정수 x가 하샤드 수이려면 x의 자릿수의 합으로 x가 나누어져야 합니다. 예를 들어 18의 자릿수 합은 1+8=9이고, 18은 9로 나누어 떨어지므로 18은 하샤드 수입니다. 자연수 x를 입력받아 x가 하샤드 수인지 아닌지 검사하는 함수, solution을 완성해주세요.
- 정수를 담고 있는 배열 arr의 평균값을 return하는 함수, solution을 완성해보세요.
- 자연수 N이 주어지면, N의 각 자릿수의 합을 구해서 …

[24일차] 김선희 / 하샤드 수 외 2개

---

1st/Jiin/TheSugarDelivery.java

| 2024.03.28 | 24일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 설탕 배달 | 백준 | 실버 IV | 112ms | https://www.acmicpc.net/problem/2839 |
- 설탕 배달 : 상근이는 지금 사탕공장에 설탕을 N 킬로그램 정확히 배달해야 하는 상황이다. 설탕공장에서 만들어진 설탕은 3킬로그램 봉지와 5킬로그램 봉지가 있다. 상근이는 봉지를 최대한 적게 가져가려 한다. 그렇다면 총 몇 봉지를 가져가야 할까? 만약 정확하게 N 킬로그램으로 만들 수 없다면 -1을 반환하자.
***
커밋이 2개가 된 이유는 제가 커밋을 깃허브로 처리하다가 엔터를 잘못 눌러서 저리 되었습니다...

[24일차] 이지인 / 설탕 배달

---

1st/Hyeseung/Programmers/자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기.sql
1st/Hyeseung/Programmers/조건에 맞는 사용자와 총 거래금액 조회하기.sql

| 2024.03.28 | 24일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `sql` <br> `vscode` |
| 자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기 | 프로그래머스 | Level.2 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/151137 |
| 조건에 맞는 사용자와 총 거래금액 조회하기 | 프로그래머스 | Level.3 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/164668 |
- 자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기 : CAR_RENTAL_COMPANY_CAR 테이블에서 '통풍시트', '열선시트', '가죽시트' 중 하나 이상의 옵션이 포함된 자동차가 자동차 종류 별로 몇 대인지 출력하는 SQL문을 작성해주세요. 이때 자동차 수에 대한 컬럼명은 CARS로 지정하고, 결과는 자동차 종류를 기준으로 오름차순 정렬해주세요.
- 조건에 맞는 사용자와 총 거래금액 조회하기 : USED_GOODS_BOARD와 USED_GOODS_USER 테이블에서 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, …

[24일차] 김혜승/ 자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기 외 1개

---

1st/Jinseon/2의 영역.java

https://school.programmers.co.kr/learn/courses/30/lessons/181894
| 2024.03.28 | 23일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 2의 영역 | 프로그래머스 | lovel 0 | 6.10ms | https://school.programmers.co.kr/learn/courses/30/lessons/181894 |
- 2의 영역 : end와 start 변수를 만들어서 값을 구했다. 약간 코드가 더러워져서...깨끗하게 하는 방법이 있다면 추천 받는다.

[23일차] 이진선 / 2의 영역

---

1st/Jihyun/Programmers/Babbling1.java
1st/Jihyun/Programmers/Subak.java

| 2024.03.28 | 24일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 수박수박수박수박수박수? | 프로그래머스 | Level.1 | 57.78ms | https://school.programmers.co.kr/learn/courses/30/lessons/12922 |
| 옹알이(1) | 프로그래머스 | Level.0 | 3.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/120956 |
- 수박수박수박수박수박수? : "수박수박수박수...."와 같은 패턴을 유지하는 문자열을 출력하는 프로그램
- 옹알이(1): "aya", "ye", "woo", "ma" 네 가지 발음을 최대 한 번씩 사용해 조합한(이어 붙인) 발음밖에 하지 못하는 조카가 발음할 수 있는 단어의 개수를 출력하는 프로그램

[24일차] 김지현 / 수박수박수박수박수박수? 외 1개

---

1st/Hyeseung/Programmers/특정 옵션이 포함된 자동차 리스트 구하기.sql

| 2024.03.29 | 25일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `sql` <br> `vscode` |
| 특정 옵션이 포함된 자동차 리스트 구하기 | 프로그래머스 | Level.1 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/157343 |
- 특정 옵션이 포함된 자동차 리스트 구하기 : CAR_RENTAL_COMPANY_CAR 테이블에서 '네비게이션' 옵션이 포함된 자동차 리스트를 출력하는 SQL문을 작성해주세요. 결과는 자동차 ID를 기준으로 내림차순 정렬해주세요.

[25일차] 김혜승 / 특정 옵션이 포함된 자동차 리스트 구하기

---

1st/Sunhee/programmers/덧칠하기.java

| 덧칠하기 | 프로그래머스 | Lv.1 | 0.21ms | https://school.programmers.co.kr/learn/courses/30/lessons/161989 |
- A어느 학교에 페인트가 칠해진 길이가 n미터인 벽이 있습니다. 벽에 동아리 · 학회 홍보나 회사 채용 공고 포스터 등을 게시하기 위해 테이프로 붙였다가 철거할 때 떼는 일이 많고 그 과정에서 페인트가 벗겨지곤 합니다. 페인트가 벗겨진 벽이 보기 흉해져 학교는 벽에 페인트를 덧칠하기로 했습니다.
넓은 벽 전체에 페인트를 새로 칠하는 대신, 구역을 나누어 일부만 페인트를 새로 칠 함으로써 예산을 아끼려 합니다. 이를 위해 벽을 1미터 길이의 구역 n개로 나누고, 각 구역에 왼쪽부터 순서대로 1번부터 n번까지 번호를 붙였습니다. 그리고 페인트를 다시 칠해야 할 구역들을 정했습니다.
벽에 페인트를 칠하는 롤러의 길이는 m미터이고, 롤러로 벽에 페인트를 한 번 칠하는 규칙은 다음과 같습니다.
롤러가 벽에서 벗어나면 안 됩니다.
구역의 일부분만 포함되도록 칠하면 안 됩니다.
즉, 롤러의 좌우측 끝을 구역의 …

[24일차] 김선희 / 덧칠하

---

1st/Jihyun/Programmers/FindingKimInSeoul.java

| 2024.03.29 | 25일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 서울에서 김서방 찾기 | 프로그래머스 | Level.1 | 9.13ms | https://school.programmers.co.kr/learn/courses/30/lessons/12919 |
- 서울에서 김서방 찾기: String 배열인 seoul이 주어질 때, Kim의 위치를 x로 구하고 "김서방은 x에 있다"형식으로 출력하는 프로그램

[25일차] 김지현 / 서울에서 김서방 찾기

---

1st/Sunhee/programmers/2016년.java

https://school.programmers.co.kr/learn/courses/30/lessons/12901
| 2024.03.30 | 24일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 2016 | 프로그래머스 | Lv.1 | 0.14ms | https://www.acmicpc.net/problem/1000 |
- 2016년 1월 1일은 금요일입니다. 2016년 a월 b일은 무슨 요일일까요? 두 수 a ,b를 입력받아 2016년 a월 b일이 무슨 요일인지 리턴하는 함수, solution을 완성하세요. 요일의 이름은 일요일부터 토요일까지 각각 SUN,MON,TUE,WED,THU,FRI,SAT
입니다. 예를 들어 a=5, b=24라면 5월 24일은 화요일이므로 문자열 "TUE"를 반환하세요.

[26일차] 김선희 / 2016 

---

1st/Hyeseung/Programmers/한 해에 잡은 물고기 수 구하기.sql

| 2024.03.30 | 26일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `sql` <br> `vscode` |
| 한 해에 잡은 물고기 수 구하기 | 프로그래머스 | Level.1 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/298516 |
- 한 해에 잡은 물고기 수 구하기 : FISH_INFO 테이블에서 2021년도에 잡은 물고기 수를 출력하는 SQL 문을 작성해주세요. 이 때 컬럼명은 'FISH_COUNT' 로 지정해주세요.

[26일차] 김혜승 / 한 해에 잡은 물고기 수 구하기

---

1st/Jinseon/food-fighter.java

https://school.programmers.co.kr/learn/courses/30/lessons/134240
| 2024.03.30 | 26일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 푸드 파이트 대회 | 프로그래밍 | Level 1 | 31.61ms | https://school.programmers.co.kr/learn/courses/30/lessons/134240 |
- 푸드 파이트 대회 : 이중for문을 사용해서(food[i]/2) 한 명이 먹을 칼로리를 구하고 StringBuffer와 reverse를 사용하여 구했다.

[26일차] 이진선 / 푸드 파이트 대

---

1st/Jiin/BacterialGrowth.java

| 2024.03.30 | 26일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 세균 증식 | 프로그래머스 | Lv. 0 | 0.05ms | https://school.programmers.co.kr/learn/courses/30/lessons/120910 |
- 세균 증식 : 세균은 1시간이 지날 때마다 2배씩 증가한다고 한다. 그렇다면 n마리의 세균은 t시간 뒤에 몇 마리 인지 반환하시오.

[26일차] 이지인 / 세균 증식

---

1st/Jihyun/Programmers/SumOfDivisors.java

| 2024.03.30 | 26일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 약수의 합 | 프로그래머스 | Level.1 | 0.09ms | https://school.programmers.co.kr/learn/courses/30/lessons/12928 |
- 약수의 합: 주어진 변수 n이 주어질 때 n의 약수들의 합을 구하는 프로그램

[26일차] 김지현 / 약수의 합

---

1st/Hyeseung/Programmers/OX퀴즈.java
1st/Hyeseung/Programmers/[PCCE 기출문제] 1번 - 출력.java
1st/Hyeseung/Programmers/다음에 올 숫자.java
1st/Hyeseung/Programmers/등수 매기기.java
1st/Hyeseung/Programmers/문자열 출력하기.java
1st/Hyeseung/Programmers/배열 조각하기.java
1st/Hyeseung/Programmers/연속된 수의 합.java
1st/Hyeseung/Programmers/전국 대회 선발 고사.java

| 2024.03.31 | 27일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `java` <br> `vscode` |
| OX퀴즈 | 프로그래머스 | Level.0 | 0.09ms | https://school.programmers.co.kr/learn/courses/30/lessons/120907 |
| 배열 조각하기 | 프로그래머스 | Level.0 | 0.07ms | https://school.programmers.co.kr/learn/courses/30/lessons/181893 |
| 다음에 올 숫자 | 프로그래머스 | Level.0 | 0.02ms | https://school.programmers.co.kr/learn/courses/30/lessons/120924 |
| 연속된 수의 합 | 프로그래머스 | Level.0 | 0.01ms | https://school.programmers.co.kr/learn/courses/30/lessons/120923 |
| 문자열 출력하기 | 프로그래머스 | Level.0 | 144.17ms | https://school.programmers.co.kr/learn/courses/30/lessons/181952 |
| [PCCE 기출문제] 1번 / 출력 …

[27일차] 김혜승 / OX퀴즈 외 7개

---

1st/Jinseon/둘만의 암호.java

https://school.programmers.co.kr/learn/courses/30/lessons/155652
| 2024.03.31 | 27일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 둘만의 암호 | 프로그래머스 | Level 1 | 23.05ms | https://school.programmers.co.kr/learn/courses/30/lessons/155652 |
- 둘만의 암호 : s.charAt(i) 문자열을 쪼개고 z라면 -26. skip.contains(String.ValueOf(word))를 사용하여 skip이라는 해당 문자에 word가 포함되어 있는지 확인한다.

[27일차] 이진선 / 둘만의 암호

---

1st/Jiin/get_aver.js

| 2024.03.31 | 27일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 평균 구하기 | 프로그래머스 | Lv.1 | 0.07ms | https://school.programmers.co.kr/learn/courses/30/lessons/12944?language=javascript |
- 평균 구하기 : 정수 배열 arr의 평균을 반환하시오.

[27일차] 이지인 / 평균 구하기

---

1st/Jihyun/Programmers/ChangeStringtoInt.java
1st/Jihyun/Programmers/HarshadNumber.java

| 2024.03.31 | 27일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 문자열을 정수로 바꾸기 | 프로그래머스 | Level.1 | 0.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/12925 |
| 하샤드 수 | 프로그래머스 | Level.1 | 0.20ms | https://school.programmers.co.kr/learn/courses/30/lessons/12947 |
- 문자열을 정수로 바꾸기 : 문자열 s를 숫자로 변환한 결과를 출력하는 프로그램
- 하샤드 수 : 주어진 정수 x의 자릿수의 합으로 x가 나누어지는지 아닌지 출력하는 프로그램

[27일차] 김지현 / 문자열을 정수로 바꾸기 외 1개

---

1st/Hyeseung/Programmers/최빈값 구하기.java

| 2024.04.01 | 28일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `java` <br> `vscode` |
| 최빈값 구하기 | 프로그래머스 | Level.0 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/120812?language=java |
- 최빈값 구하기 : 최빈값은 주어진 값 중에서 가장 자주 나오는 값을 의미합니다. 정수 배열 <code>array</code>가 매개변수로 주어질 때, 최빈값을 return 하도록 solution 함수를 완성해보세요. 최빈값이 여러 개면 -1을 return 합니다.

[28일차] 김혜승 / 최빈값 구하기

---

1st/Jinseon/달리기 경주.java

| 2024.04.01 | 28일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 달리기 경주 | 프로그래머스 | Level 1 | 382.37ms | https://school.programmers.co.kr/learn/courses/30/lessons/178871 |
- 달리기 경주 : 처음에는 for문으로 풀었는데 시간초과가 났다. 찾아보니 for문은 O(n) * O(n) 시간복잡도를 가지고 있어서 O(n^2)된다는 것. 때문에 HashMap을 사용하여 문제를 해결했다.

[28일차] 이진선 / 달리기 경주

---

1st/Jiin/HarshadNumber.java

| 2024.04.01 | 28일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 하샤드 수 | 프로그래머스 | Lv. 1 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/12947?language=java |
- 하샤드 수 : 각 자리수의 합으로 그 수가 나누어진다면, 그 수는 하샤드 수다. 주어진 정수 x가 하샤드 수 인지 아닌지 판단하시오.

[28일차] 이지인 / 하샤드 수

---

1st/Jihyun/Programmers/FlipNumber.java

| 2024.04.01 | 28일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 자연수 뒤집기 | 프로그래머스 | Level.1 | 0.05ms | https://school.programmers.co.kr/learn/courses/30/lessons/12932 |
- 자연수 뒤집기: 주어진 long 변수 n을 뒤집어 각 자리 숫자를 원소로 가지는 배열을 출력하는 프로그램

[28일차] 김지현 / 자연수 뒤집기

---

1st/Sunhee/programmers/최소직사각형.java

https://school.programmers.co.kr/learn/courses/30/lessons/86491
| 2024.04.02 | 28일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 최소직사각형 | 프로그래머스 | Lv.1 | 0.32ms | https://school.programmers.co.kr/learn/courses/30/lessons/86491 |
- 명함 지갑을 만드는 회사에서 지갑의 크기를 정하려고 합니다. 다양한 모양과 크기의 명함들을 모두 수납할 수 있으면서, 작아서 들고 다니기 편한 지갑을 만들어야 합니다. 이러한 요건을 만족하는 지갑을 만들기 위해 디자인팀은 모든 명함의 가로 길이와 세로 길이를 조사했습니다.

[29일차] 김선희 / 최소직사각형

---

1st/Hyeseung/Programmers/대소문자 바꿔서 출력하기.java

| 2024.04.02 | 29일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `java` <br> `vscode` |
| 대소문자 바꿔서 출력하기 | 프로그래머스 | Level.0 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/181949 |
- 대소문자 바꿔서 출력하기 : 영어 알파벳으로 이루어진 문자열 str이 주어집니다. 각 알파벳을 대문자는 소문자로 소문자는 대문자로 변환해서 출력하는 코드를 작성해 보세요.

[29일차] 김혜승 / 대소문자 바꿔서 출력하기

---

1st/Jinseon/덧셈식 출력.java

https://school.programmers.co.kr/learn/courses/30/lessons/181947?language=java
| 2024.04.02 | 29일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 덧셈식 출력 | 프로그래머스 | Level 0 | 173.26ms | https://school.programmers.co.kr/learn/courses/30/lessons/181947?language=java |
- 덧셈식 출력 : print문을 사용한 문제

[29일차]이진선 / 덧셈식 출력

---

1st/Jiin/DotProduct.java

| 2024.04.02 | 29일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 내적 | 프로그래머스 | Lv.1 | 0.05ms | https://school.programmers.co.kr/learn/courses/30/lessons/70128 |
- 내적 : 길이가 같은 정수 배열 a, b가 주어집니다. 이 둘의 [내적](https://en.wikipedia.org/wiki/Dot_product)을 반환하세요.

[29일차] 이지인 / 내적

---

1st/Jihyun/Programmers/FindTheSquareRootOfInteger.java

| 2024.04.02 | 29일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 정수 제곱근 판별 | 프로그래머스 | Level.1 | 0.10ms | https://school.programmers.co.kr/learn/courses/30/lessons/12934 |
- 정수 제곱근 판별: 주어진 양의 정수 n이 주어진 양의 정수 x의 제곱인지 아닌지 판별하여 출력하는 프로그램

[29일차] 김지현 / 정수 제곱근 판별

---

1st/Hyeseung/Programmers/두 수의 합.java

| 2024.04.03 | 30일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `java` <br> `vscode` |
| 두 수의 합 | 프로그래머스 | Level.0 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/181846 |
- 두 수의 합 : 0 이상의 두 정수가 문자열 a, b로 주어질 때, a + b의 값을 문자열로 return 하는 solution 함수를 작성해 주세요.

[30일차] 김혜승 / 두 수의 합

---

1st/Sunhee/PGS/두 정수 사이의 합.py
1st/Sunhee/PGS/명예의 전당.py

| 명예의 전당(1) | 프로그래머스 | Lv.1 | 0.23ms | https://school.programmers.co.kr/learn/courses/30/lessons/138477 |
| 두 정수 사이의  | 프로그래머스 | Lv.1 | 0.14ms | https://school.programmers.co.kr/learn/courses/30/lessons/12912 |
-"명예의 전당"이라는 TV 프로그램에서는 매일 1명의 가수가 노래를 부르고, 시청자들의 문자 투표수로 가수에게 점수를 부여합니다. 매일 출연한 가수의 점수가 지금까지 출연 가수들의 점수 중 상위 k번째 이내이면 해당 가수의 점수를 명예의 전당이라는 목록에 올려 기념합니다. 즉 프로그램 시작 이후 초기에 k일까지는 모든 출연 가수의 점수가 명예의 전당에 오르게 됩니다. k일 다음부터는 출연 가수의 점수가 기존의 명예의 전당 목록의 k번째 순위의 가수 점수보다 더 높으면, 출연 가수의 점수가 명예의 전당에 오르게 되고 기존의 k번째 순위의 점수는 명예의 전당에서 내려오게 됩니다.
-  두 정수 a, b가 …

[30일] 김선희 / 명예의 전당 (1) 외 1개

---

1st/Jiin/FoodFightRace.java

| 2024.04.03 | 30일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 푸드 파이트 대회 | 프로그래머스 | Lv.1 | 49.58ms | https://school.programmers.co.kr/learn/courses/30/lessons/134240 |
- 푸드 파이트 대회 : 수웅이는 매년 두 선수가 먹을 음식들을 요리합니다. 두 선수가 먹는 음식의 종류와 양은 같아야 하고, 칼로리가 낮은 음식부터 배치되야 합니다. 중간에 있는 물을 먼저 마시는 사람이 이기는 이 푸드 파이트 대회의 음식 순서를 문자열로 반환하세요.
**EX>** 0번 음식(물) 1개, 1번 음식 1개, 2번 음식 2개, 3번 음식 6개를 준비했다면  
"233303332"가 반환되어야 합니다.

[30일차] 이지인 / 푸드 파이트 대회

---

1st/Jinseon/문자열섞기.java

https://school.programmers.co.kr/learn/courses/30/lessons/181942?language=java
| 2024.04.03 | 30일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 문자열섞기 | 프로그래머스 | Level 0 | 15.35ms | https://school.programmers.co.kr/learn/courses/30/lessons/181942?language=java |
- 문자열섞기 : charAt()를 사용한 문제

[30일차] 이진선 / 문자열섞기

---

1st/Hyeseung/Programmers/커피 심부름.java

| 2024.04.04 | 31일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `java` <br> `vscode` |
| 커피심부름 | 프로그래머스 | Level.0 | 0.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/181837 |
- 커피심부름 : 팀의 막내인 철수는 아메리카노와 카페 라테만 판매하는 카페에서 팀원들의 커피를 사려고 합니다. 아메리카노와 카페 라테의 가격은 차가운 것과 뜨거운 것 상관없이 각각 4500, 5000원입니다. 각 팀원에게 마실 메뉴를 적어달라고 하였고, 그 중에서 메뉴만 적은 팀원의 것은 차가운 것으로 통일하고 "아무거나"를 적은 팀원의 것은 차가운 아메리카노로 통일하기로 하였습니다. 각 직원이 적은 메뉴가 문자열 배열 order로 주어질 때, 카페에서 결제하게 될 금액을 return 하는 solution 함수를 작성해주세요. order의 원소는 아래의 것들만 들어오고, 각각의 의미는 다음과 같습니다.

[31일차] 김혜승 / 커피 심부름

---

1st/Sunhee/PGS/완주하지 못한 선수.py

| 2024.04.04 | 31일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 완주하지 못한 선수 | 프로그래머스 | Lv.1 | 0.21ms | https://school.programmers.co.kr/learn/courses/30/lessons/42576 |
- 수많은 마라톤 선수들이 마라톤에 참여하였습니다. 단 한 명의 선수를 제외하고는 모든 선수가 마라톤을 완주하였습니다.
마라톤에 참여한 선수들의 이름이 담긴 배열 participant와 완주한 선수들의 이름이 담긴 배열 completion이 주어질 때, 완주하지 못한 선수의 이름을 return 하도록 solution 함수를 작성해주세요.

[31일차] 김선희 / 완주하지 못한 선수

---

1st/Jinseon/문자열로변환하기.java

| 2024.04.04 | 31일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 문자열로 변환하기 | 프로그래머스 | Level 0 | 208ms | https://school.programmers.co.kr/learn/courses/30/lessons/181845 |
- 문자열로 변환하기 : Integer.toString()사용

[31일]이진선 / 문자열로 변환하기

---

1st/Jihyun/Programmers/AddDigits.java

| 2024.04.04 | 31일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 자릿수 더하기 | 프로그래머스 | Level.1 | 0.20ms | https://school.programmers.co.kr/learn/courses/30/lessons/12931 |
- 자릿수 더하기: 자연수 n이 주어질 때 n의 각 자릿수의 합을 구해서 출력하는 프로그램

[31일차] 김지현 / 자릿수 더하기

---

1st/Jiin/printADD.js

| 2024.04.04 | 31일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `javascript` <br> `vscode` |
| 덧셈식 출력 | 프로그래머스 | Lv.0 | 43.12ms | https://school.programmers.co.kr/learn/courses/30/lessons/181947 |
- 덧셈식 출력 : 주어진 수 2개를 형식에 맞게 출력하기

[31일차] 이지인 / 덧셈식 출력하기

---

1st/Jiin/change_the_alpabet.js
1st/Jiin/the_roughly_made_keyboard.js

| 2024.04.05 | 32일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `JavaScript` <br> `vscode` |
| 대충 만든 자판 | 프로그래머스 | Lv.1 | 0.67ms | https://school.programmers.co.kr/learn/courses/30/lessons/160586?language=javascript |
| 대소문자 바꿔서 출력하기 | 프로그래머스 | Lv.0 | 46.21ms | https://school.programmers.co.kr/learn/courses/30/lessons/181949?language=javascript |
- **_대충 만든 자판 :_** 핸드폰 자판은 같은 자판을 몇 번씩 눌러야 모든 문자를 사용할 수 있습니다.   
이런 규칙을 적용한 아무렇게나 만든 자판이 있습니다. 
이 자판으로 주어진 문자열을 작성하려 할 때, 최소 몇 번을 눌러야 작성할 수 있는지 배열에 담아 반환하세요. 
만약 작성할 수 없는 문자열이라면 -1의 값으로 반환합니다.
- **_대소문자 바꿔서 출력하기 :_** 주어진 문자열의 대소문자를 바꿔서 출력하세요.

[32일차] 이지인 / 대충 만든 자판 외 1개

---

1st/Hyeseung/Programmers/영어가 싫어요.java

| 2024.04.05 | 32일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `java` <br> `vscode` |
| 영어가 싫어요 | 프로그래머스 | Level.0 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/120894 |
- 영어가 싫어요 : 영어가 싫은 머쓱이는 영어로 표기되어있는 숫자를 수로 바꾸려고 합니다. 문자열 numbers가 매개변수로 주어질 때, numbers를 정수로 바꿔 return 하도록 solution 함수를 완성해 주세요.

[32일차] 김혜승 / 영어가 싫어요

---

1st/Sunhee/programmers/최댓값과 최솟값.java

| 2024.04.05 | 32일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 최댓값과 최솟값 | 프로그래머스 | Lv.2 | 9.49ms | https://school.programmers.co.kr/learn/courses/30/lessons/12939 |
- 문자열 s에는 공백으로 구분된 숫자들이 저장되어 있습니다. str에 나타나는 숫자 중 최소값과 최대값을 찾아 이를 "(최소값) (최대값)"형태의 문자열을 반환하는 함수, solution을 완성하세요.

[32일차] 김선희 / 최댓값과 최솟값

---

1st/Jihyun/Programmers/AddMissingNumber.java

| 2024.04.05 | 32일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 없는 숫자 더하기 | 프로그래머스 | Level.1 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/86051 |
- 없는 숫자 더하기: 0부터 9까지의 숫자 중 일부가 들어있는 정수 배열 numbers가 주어질 때 numbers에 0부터 9까지의 숫자 중 없는 숫자를 더하여 출력하는 프로그램

[32일차] 김지현 / 없는 숫자 더하기

---

1st/Jiin/CountDown.java
1st/Jiin/print_woman_born_in_march.sql
1st/Jiin/qr_code.js

| 2024.04.06 | 33일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `JavaScript` <br> `ver.8 java` <br> `Oracle` |
| qr code | 프로그래머스 | Lv.0 | 0.19ms | https://school.programmers.co.kr/learn/courses/30/lessons/181903?language=javascript |
| 카운트 다운 | 프로그래머스 | Lv.0 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/181899?language=java |
| 3월에 태어난 여성 회원 목록 출력하기 | 프로그래머스 | Lv.0 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/131120#qna |
- qr code : 정수 q와 r이 주어지고 문자열 code가 주어진다. code의 인덱스를 q로 나누고 나눈 각각의 문자열의 r번째 글자들을 차례로 이어붙인 문자열을 반환하시오.
- 카운트 다운 : start_num부터 end_num까지 1씩 줄어드는 수를 차례로 담은 리스트를 반환하시오.
- 3월에 태어난 …

[33일차] 이지인 / qr code 외 2개

---

1st/Jihyun/Programmers/StringReverseSort.java

| 2024.04.06 | 33일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 문자열 내림차순으로 배치하기 | 프로그래머스 | Level.1 | 6.37ms | https://school.programmers.co.kr/learn/courses/30/lessons/12917 |
- 문자열 내림차순으로 배치하기: 문자열 s가 주어질 때 문자가 큰 것부터 작은 순으로 정렬하여 출력하는 프로그램 (단, 대문자는 소문자보다 작은 것으로 간주)

[33일차] 김지현 / 문자열 내림차순으로 배치하기

---

1st/Jinseon/문자열돌리기.java

https://school.programmers.co.kr/learn/courses/30/lessons/181945
| 2024.04.06 | 33일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 문자열 돌리기 | 프로그래머스 | Level 0 | 280.82ms | https://school.programmers.co.kr/learn/courses/30/lessons/181945 |
- 문자열 돌리기 :  StringBuilder result = new StringBuilder(); 사용

[33일차]이진선 / 문자열돌리기

---

1st/Hyeseung/Programmers/공백으로 구분하기2.java

| 2024.04.07 | 34일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `java` <br> `vscode` |
| 공백으로 구분하기2 |프로그래머스| Level.0 | 3.59ms | https://school.programmers.co.kr/learn/courses/30/lessons/181868?language=java |
- 공백으로 구분하기2 : 단어가 공백 한 개 이상으로 구분되어 있는 문자열 my_string이 매개변수로 주어질 때, my_string에 나온 단어를 앞에서부터 순서대로 담은 문자열 배열을 return 하는 solution 함수를 작성해 주세요.

[34일차] 김혜승 / 공백으로 구분하기2

---

1st/Jiin/ColaTest.java
1st/Jiin/print_book_list.sql

| 2024.04.07 | 34일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `MySQL` |
| 조건에 맞는 도서 리스트 출력하기 | 프로그래머스 | Lv.1 | - | https://school.programmers.co.kr/learn/courses/30/lessons/144853 |
| 콜라 문제 | 프로그래머스 | Lv.1 | 1.7ms | https://school.programmers.co.kr/learn/courses/30/lessons/132267 |
- 조건에 맞는 도서 리스트 출력하기 : 테이블에서 2021년에 출판되고 카테고리가 인문인 책들을 출판일을 기준으로 오름차순으로 출력하기
- 콜라 문제 : 빈 콜라병 a개를 주면 b개의 콜라로 다시 돌려주는 마트에 빈 콜라n병을 가져가면, 받을 수 있는 콜라의 개수는?

[34일차] 이지인 / 조건에 맞는 도서 리스트 출력하기 외 1개

---

1st/Jinseon/기사단원의무기.java

| 기사단원의 무기 | 프로그래머스 | Level 1 | 12.41ms | https://school.programmers.co.kr/learn/courses/30/lessons/136798 |
- 기사단원의 무기 : 약수를 배수를 이용해 각 배열에 저장하는 코드

[34일차] 이진선 / 기사단원의 무기

---

1st/Sunhee/programmers/JadenCase 문자열 만들기.java

| 2024.04.07 | 1일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| JadenCase 문자열 만들기
| 프로그래머스 | Lv.2 | 0.34ms | https://school.programmers.co.kr/learn/courses/30/lessons/12951 |
- JadenCase란 모든 단어의 첫 문자가 대문자이고, 그 외의 알파벳은 소문자인 문자열입니다. 단, 첫 문자가 알파벳이 아닐 때에는 이어지는 알파벳은 소문자로 쓰면 됩니다. (첫 번째 입출력 예 참고)
문자열 s가 주어졌을 때, s를 JadenCase로 바꾼 문자열을 리턴하는 함수, solution을 완성해주세요.

[34일차] 김선희 / JadenCase 문자열 만들기

---

1st/Jihyun/Programmers/SmallSubstring.java

| 2024.04.07 | 34일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 크기가 작은 부분 문자열 | 프로그래머스 | Level.1 | 208ms | https://www.acmicpc.net/problem/1000 |
- 크기가 작은 부분 문자열 : 숫자로 이루어진 문자열 t와 p가 주어질 때, t에서 p와 길이가 같은 부분문자열 중에서, 이 부분문자열이 나타내는 수가 p가 나타내는 수보다 작거나 같은 것이 나오는 횟수를 출력하는 프로그램

[34일차] 김지현 / 크기가 작은 부분 문자열

---

1st/Jihyun/Programmers/DotProduct.java

| 2024.04.08 | 35일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 내적 | 프로그래머스 | Level.1 | 0.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/70128 |
- 내적 : 길이가 같은 두 1차원 정수 배열 a, b가 매개변수 주어질 때, a와 b의 내적을 구하는 프로그램

[35일차] 김지현 / 내적

---

1st/Sunhee/programmers/올바른 괄호.java

| 2024.04.08 | 35일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 올바른 괄호 | 프로그래머스 | Lv.1 | 0.15ms | https://school.programmers.co.kr/learn/courses/30/lessons/12909 |
- 괄호가 바르게 짝지어졌다는 것은 '(' 문자로 열렸으면 반드시 짝지어서 ')' 문자로 닫혀야 한다는 뜻입니다. 예를 들어
"()()" 또는 "(())()" 는 올바른 괄호입니다.
")()(" 또는 "(()(" 는 올바르지 않은 괄호입니다.
'(' 또는 ')' 로만 이루어진 문자열 s가 주어졌을 때, 문자열 s가 올바른 괄호이면 true를 return 하고, 올바르지 않은 괄호이면 false를 return 하는 solution 함수를 완성해 주세요.

[35일차] 김선희 / 올바른 괄호

---

1st/Jiin/MissingPoint.java

| 2024.04.08 | 35일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 추억 점수 | 프로그래머스 | Lv.1 | 3.79ms | https://school.programmers.co.kr/learn/courses/30/lessons/176963 |
- 추억 점수 : 사진 속 인물들 별로 추억 점수를 정해, 사진의 추억 점수를 정하였습니다.  
예를 들어 사진 속 인물의 이름이 ["kali", "mari", "don", "tony"]이고 ["kali", "mari", "don"]의 그리움 점수가 각각 [11점, 1점, 55점]이라면 이 사진의 추억점수는  
11+1+55 = 67점 입니다. 추억 점수 명단에 없는 tony는 추억 점수가 0점입니다.

[35일차] 이지인 / 추억 점수

---

1st/Hyeseung/Programmers/3진법 뒤집기.java

| 2024.04.08 | 35일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `java` <br> `vscode` |
| 3진법 뒤집기 |프로그래머스| Level.1 | 12.39ms | https://school.programmers.co.kr/learn/courses/30/lessons/68935 |
- 3진법 뒤집기 : 자연수 n이 매개변수로 주어집니다. n을 3진법 상에서 앞뒤로 뒤집은 후, 이를 다시 10진법으로 표현한 수를 return 하도록 solution 함수를 완성해주세요.

[35일차] 김혜승 / 3진법 뒤집기

---

1st/Jinseon/정수제곱근판별.java

https://school.programmers.co.kr/learn/courses/30/lessons/12934?language=java
| 2024.04.08 | 34일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 정수 제곱근 판별 | 프로그래머스 | Level 1 | 0.14ms | https://school.programmers.co.kr/learn/courses/30/lessons/12934?language=java|
- 정수 제곱근 판별 : 제곱해주는 함수.(Math.pow())와 제곱근을 구하는 함수(Math.sqrt())를 사용하여 제곱근을 판별했다.

[35일차] 이진선 / 정수제곱근판별

---

1st/Hyeseung/Programmers/숫자 문자열과 영단어.java

| 2024.04.09 | 36일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `java` <br> `vscode` |
| 숫자 문자열과 영단어 | 프로그래머스 | Level.1 | 0.57ms | https://school.programmers.co.kr/learn/courses/30/lessons/81301 |
- 숫자 문자열과 영단어 : 다음은 숫자의 일부 자릿수를 영단어로 바꾸는 예시입니다.
1478 → "one4seveneight"
234567 → "23four5six7"
10203 → "1zerotwozero3"
이렇게 숫자의 일부 자릿수가 영단어로 바뀌어졌거나, 혹은 바뀌지 않고 그대로인 문자열 s가 매개변수로 주어집니다. s가 의미하는 원래 숫자를 return 하도록 solution 함수를 완성해주세요

[36일차] 김혜승 / 숫자 문자열과 영단어 

---

1st/Jinseon/문자열반복해서출력하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/181950
| 2024.04.09 | 36일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 문자열 반복해서 출력하기 | 프로그래머스 | Level 0 | 159.73ms | https://school.programmers.co.kr/learn/courses/30/lessons/181950 |
- 문자열 반복해서 출력하기 : for문 사용해서 풀

[36일차]이진선 / 문자열 출력하기

---

1st/Sunhee/programmers/소수 찾기.java

| 2024.04.09 | 36일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 소수 찾기 | 프로그래머스 | Lv.1 | 0.13ms | https://school.programmers.co.kr/learn/courses/30/lessons/12921 |
- 1부터 입력받은 숫자 n 사이에 있는 소수의 개수를 반환하는 함수, solution을 만들어 보세요.
소수는 1과 자기 자신으로만 나누어지는 수를 의미합니다.
(1은 소수가 아닙니다.)

[36일차] 김선희 / 소수 찾기

---

1st/Jiin/Repeat_String.java

| 문자열 반복 | 프로그래머스 | Lv.0 | 148.67ms | https://school.programmers.co.kr/learn/courses/30/lessons/181950 |
- 문자열 반복 : 주어진 문자열 str을 주어진 정수 n만큼 반복시킨 문자열을 출력하시오.

[36일차] 이지인 / 문자열 반복

---

1st/Jihyun/Programmers/EvenOddNumber.java

| 2024.04.09 | 35일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 짝수 홀수 개수 | 프로그래머스 | Level.1 | 0.02ms | https://school.programmers.co.kr/learn/courses/30/lessons/120824 |
- 짝수 홀수 개수: 정수가 담긴 리스트 num_list가 주어질 때, num_list의 원소 중 짝수와 홀수의 개수를 담은 배열을 출력하는 프로그램

[36일차] 김지현 / 짝수 홀수 개수

---

1st/Jinseon/문자열의앞의n글자.java

https://school.programmers.co.kr/learn/courses/30/lessons/181907
| 2024.04.10 | 37일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 문자열 앞의 n글자 | 프로그래머스 | Level 0 | 0.12ms | https://school.programmers.co.kr/learn/courses/30/lessons/181907 |
- 문자열 앞의 n글자 substring사용

[37일차] 이진선 / 문자열 앞의 n글자

---

1st/Jihyun/Programmers/NumberMultiplicationAndSum.java

| 2024.04.10 | 37일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 원소들의 곱과 합 | 프로그래머스 | Level.0 | 1.25ms | https://school.programmers.co.kr/learn/courses/30/lessons/181929 |
- 원소들의 곱과 합: 정수가 담긴 리스트 num_list가 주어질 때, 모든 원소들의 곱이 모든 원소들의 합의 제곱보다 작으면 1을 크면 0을 return하는 프로그램

[37일차] 김지현 / 원소들의 곱과 합

---

1st/Jiin/built_bridge.py

| 2024.04.10 | 37일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `python` <br> `vscode` |
| 다리 놓기 | 백준 | 실버 V | 208ms | https://www.acmicpc.net/problem/1010 |
- 다리 놓기 : 서쪽 사이트와 동쪽 사이트를 이어 다리를 놓으려고 합니다. 이때, 다리는 겹치게 놓을 수 없고 서쪽 사이트 한 개에 하나씩 전부 연결되어 있어야 합니다. 이 때 다리를 놓을 수 있는 경우의 수를 출력하시오.
***
분명 문제를 푸는데 적용하면 딱 일것 같은 익숙한 수학 개념이 있는데  
희미하게 기억나서 오랫만에 수학 공부에 의지를 불태웠습니다.

[37일차] 이지인 / 다리 놓기

---

1st/Sunhee/programmers/옹알이(2).java

https://school.programmers.co.kr/learn/courses/30/lessons/133499
| 2024.04.10 | 37일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 옹알이 | 프로그래머스 | Lv.1 | 0.12ms | https://school.programmers.co.kr/learn/courses/30/lessons/133499 |
- 머쓱이는 태어난 지 11개월 된 조카를 돌보고 있습니다. 조카는 아직 "aya", "ye", "woo", "ma" 네 가지 발음과 네 가지 발음을 조합해서 만들 수 있는 발음밖에 하지 못하고 연속해서 같은 발음을 하는 것을 어려워합니다. 문자열 배열 babbling이 매개변수로 주어질 때, 머쓱이의 조카가 발음할 수 있는 단어의 개수를 return하도록 solution 함수를 완성해주세요.

[37일차]  김선희 / 옹알이 

---

1st/Hyeseung/Programmers/삼총사.java

| 2024.04.11 | 38일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 삼총사 | 프로그래머스 | Level.1 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/131705 |
- 삼총사 : 한국중학교에 다니는 학생들은 각자 정수 번호를 갖고 있습니다. 이 학교 학생 3명의 정수 번호를 더했을 때 0이 되면 3명의 학생은 삼총사라고 합니다. 예를 들어, 5명의 학생이 있고, 각각의 정수 번호가 순서대로 -2, 3, 0, 2, -5일 때, 첫 번째, 세 번째, 네 번째 학생의 정수 번호를 더하면 0이므로 세 학생은 삼총사입니다. 또한, 두 번째, 네 번째, 다섯 번째 학생의 정수 번호를 더해도 0이므로 세 학생도 삼총사입니다. 따라서 이 경우 한국중학교에서는 두 가지 방법으로 삼총사를 만들 수 있습니다.
한국중학교 학생들의 번호를 나타내는 정수 배열 number가 매개변수로 주어질 때, 학생들 중 삼총사를 만들 수 있는 방법의 수를 return 하도록 solution 함수를 완성하세요

[38일차] 김혜승 / 삼총사

---

1st/Sunhee/programmers/숫자 문자열과 영단어.java

https://school.programmers.co.kr/learn/courses/30/lessons/81301
| 2024.04.11 | 38일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 숫자 문자열과 영단어 | 프로그래머스 | Lv.1 | 0.08ms | https://school.programmers.co.kr/learn/courses/30/lessons/81301 |
- 네오와 프로도가 숫자놀이를 하고 있습니다. 네오가 프로도에게 숫자를 건넬 때 일부 자릿수를 영단어로 바꾼 카드를 건네주면 프로도는 원래 숫자를 찾는 게임입니다.

[38일차] 김선희 /  숫자 문자열과 영단어 

---

1st/Jiin/get_root_item.sql
1st/Jiin/seach_ecoli_of_special_genotype.sql

| 2024.04.11 | 38일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `MySQL` <br> `vscode` |
| 특정 형질을 가지는 대장균 찾기 | 프로그래머스 | Lv.1 | - | https://school.programmers.co.kr/learn/courses/30/lessons/301646 |
| ROOT 아이템 구하기 | 프로그래머스 | Lv.2 | - | https://school.programmers.co.kr/learn/courses/30/lessons/273710 |
- 특정 형질을 가지는 대장균 찾기 : 형질을 2진수로 변환 후  
오른쪽부터 첫 번째 숫자가 1이면 1번 형질이 존재하고 0이면 1번 형질이 없는 것 입니다.  
이 대장균 중에서 2번 형질은 없고 1번이나 3번 형질을 가진 대장균의 수를 출력하세요.
- ROOT 아이템 구하기 : 아이템의 정보를 담은 테이블 `ITEM_INFO`와 이런 아이템의 업그레이드 관계 정보를 담은 테이블 `ITEM_TREE`이 있다. 아무 업그레이드도 되지 않은 초기 상태의 아이템을 ROOT 아이템이라고 한다. ROOT 아이템을 아이템 아이디를 기준으로 오름차순하여 출력하시오.

[38일차] 이지인 / 특정 형질을 가지는 대장균 찾기 외 1개

---

1st/Jinseon/대소문자바꿔서출력하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/181949
| 2024.04.11 | 38일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 대소문자 바꿔서 출력하기 | 프로그래머스 | Level 0 | 281.47ms | https://school.programmers.co.kr/learn/courses/30/lessons/181949 |
- 대소문자 바꿔서 출력하기 : isUpperCase()와 toUpperCase()/toLowerCase()를 사용하여  풀었다.

[38일차]이진선 / 대소문자 바꿔서 출력하기

---

1st/Jihyun/Programmers/MaxAndMin.java

| 2024.04.11 | 38일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 최댓값과 최솟값 | 프로그래머스 | Level.2 | 13.97ms | https://school.programmers.co.kr/learn/courses/30/lessons/12939 |
- 최댓값과 최솟값: 공백으로 구분된 숫자들이 저장되어있는 문자열 s가 주어질 때 s에서 나타나는 숫자 중 최소값과 최대값을 찾아
"(최소값) (최대값)"형태의 문자열을 반환하는 프로그램

[38일차] 김지현 / 최댓값과 최솟값

---

1st/Jinseon/queue.java

https://www.acmicpc.net/problem/10845
| 2024.04.12 | 39일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 10845 : 큐 | 백준 | 실버IV | 212ms | https://www.acmicpc.net/problem/10845 |
- 큐 : q.poll(), q.size())등을 사용한 큐 알고리즘으로 풀기

[39일차] 이진선 / 큐

---

1st/Hyeseung/Programmers/2016년.java

| 2024.04.12 | 39일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `java` <br> `vscode` |
| 2016년 | 프로그래머스 | Level.1 | 2.59ms| https://school.programmers.co.kr/learn/courses/30/lessons/12901 |
- 2016년 : 2016년 1월 1일은 금요일입니다. 2016년 a월 b일은 무슨 요일일까요? 두 수 a ,b를 입력받아 2016년 a월 b일이 무슨 요일인지 리턴하는 함수, solution을 완성하세요. 요일의 이름은 일요일부터 토요일까지 각각 SUN,MON,TUE,WED,THU,FRI,SAT

[39일차] 김혜승 / 2016년

---

1st/Sunhee/programmers/큐.java

| 2024.04.12 | 39일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 큐 | 백준 | 0.5ms | https://www.acmicpc.net/problem/10845 |
- 정수를 저장하는 큐를 구현한 다음, 입력으로 주어지는 명령을 처리하는 프로그램을 작성하시오.
명령은 총 여섯 가지이다.
push X: 정수 X를 큐에 넣는 연산이다.
pop: 큐에서 가장 앞에 있는 정수를 빼고, 그 수를 출력한다. 만약 큐에 들어있는 정수가 없는 경우에는 -1을 출력한다.
size: 큐에 들어있는 정수의 개수를 출력한다.
empty: 큐가 비어있으면 1, 아니면 0을 출력한다.
front: 큐의 가장 앞에 있는 정수를 출력한다. 만약 큐에 들어있는 정수가 없는 경우에는 -1을 출력한다.
back: 큐의 가장 뒤에 있는 정수를 출력한다. 만약 큐에 들어있는 정수가 없는 경우에는 -1을 출력한다.

[39일차] 김선희 / 큐

---

1st/Sunhee/programmers/문자열 내마음대로 정렬하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/12915
| 2024.04.13 | 40일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 문자열 내 마음대로 정렬하기 | 프로그래머스 | Lv.1 | 9.7ms | https://school.programmers.co.kr/learn/courses/30/lessons/12915|
- 문자열로 구성된 리스트 strings와, 정수 n이 주어졌을 때, 각 문자열의 인덱스 n번째 글자를 기준으로 오름차순 정렬하려 합니다. 예를 들어 strings가 ["sun", "bed", "car"]이고 n이 1이면 각 단어의 인덱스 1의 문자 "u", "e", "a"로 strings를 정렬합니다.

[40일차] 김선희 /  문자열 내 마음대로 정렬하기 

---

1st/Hyeseung/Programmers/K번째수.java
1st/Hyeseung/Programmers/[1차] 비밀지도.java
1st/Hyeseung/Programmers/가장 가까운 같은 글자.java
1st/Hyeseung/Programmers/두 개 뽑아서 더하기.java
1st/Hyeseung/Programmers/문자열 내 마음대로 정렬하기.java
1st/Hyeseung/Programmers/최소직사각형.java
1st/Hyeseung/Programmers/크기가 작은 부분 문자열.java

| 2024.04.13 | 40일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `java` <br> `vscode` |
| 크기가 작은 부분 문자열 | 프로그래머스 | Level.1 | 0.15ms | https://school.programmers.co.kr/learn/courses/30/lessons/147355 |
| 최소직사각형 | 프로그래머스 | Level.1 | 1.62ms | https://school.programmers.co.kr/learn/courses/30/lessons/86491 |
| 가장 가까운 같은 글자 | 프로그래머스 | Level.1 | 9.65ms | https://school.programmers.co.kr/learn/courses/30/lessons/142086 |
| [1차] 비밀지도 | 프로그래머스 | Level.1 | 1.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/17681 |
| K번째 수 | 프로그래머스 | Level.1 | 0.32ms | https://school.programmers.co.kr/learn/courses/30/lessons/42748 |
| 두 개 뽑아서 더하기 | …

[40일차] 김혜승 / 크기가 작은 부분 문자열 외 6개

---

1st/Jiin/string_overwrite.js

| 2024.04.13 | 40일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `JavaScript` <br> `vscode` |
| 문자열 겹쳐쓰기 | 프로그래머스 | Lv.0 | 0.05ms | https://school.programmers.co.kr/learn/courses/30/lessons/181943?language=javascript |
- 문자열 겹쳐쓰기 : 문자열 my_string, overwrite_string과 정수 s가 주어집니다. 문자열 my_string의 인덱스 s부터 overwrite_string의 길이만큼을 문자열 overwrite_string으로 바꾼 문자열을 return 하는 solution 함수를 작성해 주세요.

[40일차] 이지인 / 문자열 겹처쓰기

---

1st/Jinseon/크기가작은부분문자열.java

https://school.programmers.co.kr/learn/courses/30/lessons/147355
| 2024.04.13 | 40일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 크기가 작은 부분 문자열 | 프로그래머스 | Level 1 | 208ms | https://school.programmers.co.kr/learn/courses/30/lessons/147355 |
- 크기가 작은 부분 문자열 : 반복문의 인덱스를 넘기지 않으면서 문자열을 자르는 것이 포인트.Long.parseLong(p);을 사용하였다.

[40일차]이진선 / 크기가 작은 부분 문자열

---

1st/Jihyun/Programmers/ArrayOfNumbersDividedInto.java
1st/Jihyun/Programmers/MaxAndMin.java

| 2024.04.13 | 40일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 나누어 떨어지는 숫자 배열 | 프로그래머스 | Level.1 | 2.66ms | https://school.programmers.co.kr/learn/courses/30/lessons/12910 |
- 나누어 떨어지는 숫자 배열: array의 각 element 중 divisor로 나누어 떨어지는 값을 오름차순으로 정렬한 배열을 반환하는 프로그램

[40일차] 김지현 / 나누어 떨어지는 숫자 배열

---

1st/Hyeseung/Programmers/추억 점수.java
1st/Hyeseung/Programmers/콜라 문제.java

| 2024.04.14 | 41일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `java` <br> `vscode` |
| 콜라 문제 | 프로그래머스 | Level.1 | 0.01ms| https://school.programmers.co.kr/learn/courses/30/lessons/132267 |
| 추억 점수 | 프로그래머스 | Level.1 | 0.03ms| https://school.programmers.co.kr/learn/courses/30/lessons/176963 |
- 콜라 문제 : 문제를 열심히 풀던 상빈이는 일반화된 콜라 문제를 생각했습니다. 이 문제는 빈 병 a개를 가져다주면 콜라 b병을 주는 마트가 있을 때, 빈 병 n개를 가져다주면 몇 병을 받을 수 있는지 계산하는 문제입니다. 기존 콜라 문제와 마찬가지로, 보유 중인 빈 병이 a개 미만이면, 추가적으로 빈 병을 받을 순 없습니다. 상빈이는 열심히 고심했지만, 일반화된 콜라 문제의 답을 찾을 수 없었습니다. 상빈이를 도와, 일반화된 콜라 문제를 해결하는 프로그램을 만들어 주세요. 콜라를 받기 위해 마트에 주어야 하는 병 수 a, 빈 병 a개를 가져다 주면 마트가 주는 콜라 병 수 b, 상빈이가 가지고 있는 빈 병의 개수 n이 …

[41일차] 김혜승 / 콜라 문제 외 1개

---

1st/Jiin/CollatzConjecture.java

| 2024.04.14 | 41일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 콜라츠 추측 | 프로그래머스 | Lv.1 | 0.06ms | https://school.programmers.co.kr/learn/courses/30/lessons/12943#qna |
- 콜라츠 추측 : 주어진 수가 짝수라면 2를 나누고, 주어진 수가 홀수라면 3을 곱한 후 1을 더하며 최종적으로 1이 되기까지 몇번의 연산이 이루어졌는지 반환하시오. 만약 연산 횟수가 500번을 넘어가면 -1을 반환하고 처음부터 1이 주어진다면 0을 반환하시오.

[41일차] 이지인 / 콜라츠 추측

---

1st/Jinseon/x만큼간격이있는n개의숫자.java

https://school.programmers.co.kr/learn/courses/30/lessons/12954
| 2024.04.14 | 41일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| x만큼 간격이 있는 n개의 숫자 | 프로그래머스 | Level 1 | 0.05ms | https://school.programmers.co.kr/learn/courses/30/lessons/12954 |
- x만큼 간격이 있는 n개의 숫자 : int 때문에 오류 났었는데 long으로 바꿈.

[41일차] 이진선 / x만큼 간격이 있는 n개의 숫자

---

1st/Sunhee/programmers/큐.java

https://school.programmers.co.kr/learn/courses/30/lessons/17681
| 2024.04.14 | 31일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| [1차] 비밀지도 | 프로그래머스 | Lv.1 | 7.08ms | https://school.programmers.co.kr/learn/courses/30/lessons/17681 |
-네오는 평소 프로도가 비상금을 숨겨놓는 장소를 알려줄 비밀지도를 손에 넣었다. 그런데 이 비밀지도는 숫자로 암호화되어 있어 위치를 확인하기 위해서는 암호를 해독해야 한다. 다행히 지도 암호를 해독할 방법을 적어놓은 메모도 함께 발견했다.

[41일차] 김선희 / [1차] 비밀지도 

---

.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
.idea/workspace.xml
1st/1st.iml
1st/Hyeseung/Hyeseung.iml
1st/Jihyun/Jihyun.iml
1st/Jihyun/Programmers/CreateJadenCaseString.java
1st/Jihyun/Programmers/SumBetweenTwoNumber.java
Coding_Test_Study.iml

| 2024.04.14 | 41일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 두 정수 사이의 합 | 프로그래머스 | Level.1 | 15.91ms | https://school.programmers.co.kr/learn/courses/30/lessons/12912 |
- 두 정수 사이의 합: 두 정수 a, b가 주어졌을 때 a와 b 사이에 속한 모든 정수의 합을 리턴하는 프로그램

[41일차] 김지현 / 두 정수 사이의 합

---

1st/Hyeseung/Programmers/피보나치 수.java

| 2024.04.15 | 42일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `java` <br> `vscode` |
| 피보나치 수 | 프로그래머스 | Level.2 | 3.51ms | https://school.programmers.co.kr/learn/courses/30/lessons/12945 |
- 피보나치 수 : 피보나치 수는 F(0) = 0, F(1) = 1일 때, 1 이상의 n에 대하여 F(n) = F(n-1) + F(n-2) 가 적용되는 수 입니다. 2 이상의 n이 입력되었을 때, n번째 피보나치 수를 1234567으로 나눈 나머지를 리턴하는 함수, solution을 완성해 주세요.

[42일차] 김혜승 / 피보나치 수

---

1st/Jinseon/문자열 나누기.java

https://school.programmers.co.kr/learn/courses/30/lessons/140108
| 2024.04.15 | 42일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 문자열 나누기 | 프로그래머스 | Level 1 | 0.92ms | https://school.programmers.co.kr/learn/courses/30/lessons/140108 |
- 문자열 나누기 : count와 charAt()사용

[42일차] 이진선 / 문자열 나누기

---

1st/Jiin/magic_elevator.js

| 2024.04.15 | 42일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `JavaScript` <br> `vscode` |
| 마법의 엘리베이터 | 프로그래머스 | Lv.2 | 0.07ms | https://school.programmers.co.kr/learn/courses/30/lessons/148653#qna |
- 마법의 엘리베이터 : 마법의 세계에 사는 민수는 아주 높은 탑에 살고 있습니다. 탑이 너무 높아서 걸어 다니기 힘든 민수는 마법의 엘리베이터를 만들었습니다. 마법의 엘리베이터의 버튼은 특별합니다. 마법의 엘리베이터에는 -1, +1, -10, +10, -100, +100 등과 같이 절댓값이 10c (c ≥ 0 인 정수) 형태인 정수들이 적힌 버튼이 있습니다. 마법의 엘리베이터의 버튼을 누르면 현재 층 수에 버튼에 적혀 있는 값을 더한 층으로 이동하게 됩니다. 단, 엘리베이터가 위치해 있는 층과 버튼의 값을 더한 결과가 0보다 작으면 엘리베이터는 움직이지 않습니다. 민수의 세계에서는 0층이 가장 아래층이며 엘리베이터는 현재 민수가 있는 층에 있습니다.
마법의 엘리베이터를 움직이기 위해서 버튼 한 번당 마법의 돌 한 개를 사용하게 됩니다.예를 들어, 16층에 있는 민수가 0층으로 …

[42일차] 이지인 / 마법의 엘리베이터

---

1st/Jihyun/Programmers/CreateJadenCaseString.java

| 2024.04.15 | 42일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| JadenCase 문자열 만들기 | 프로그래머스 | Level.2 | 3.15ms | https://school.programmers.co.kr/learn/courses/30/lessons/12951 |
- JadenCase 문자열 만들기: 문자열 s가 주어졌을 때, 모든 단어의 첫 문자가 대문자이고, 그 외의 알파벳은 소문자인 문자열인 JadenCase 문자열을 return 하는 프로그램

[42일차] 김지현 / JadenCase 문자열 만들기

---

1st/Jinseon/두개뽑아서더하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/68644#
| 2024.04.16 | 43일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 두 개 뽑아서 더하기 | 프로그래머스 | Level 1 | 6.69ms | https://school.programmers.co.kr/learn/courses/30/lessons/68644 |
- 두 개 뽑아서 더하기 : distinct() 중복 제거, filter() 원하는 원소 제거, toArray()배열로 바꾸기 toArraty.sort()를 사용하여 문제를 풀었다. 오랜만에 쓰는 메서드가 많아, 다 까먹었지만 이번 기회에 복습하니까 나쁘지 않았다.

[43일차] 이진선 / 두 개 뽑아서 더하기

---

1st/Hyeseung/Programmers/짝지어 제거하기.java

| 2024.04.16 | 43일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `java` <br> `vscode` |
| 짝지어 제거하기 | 프로그래머스 | Level.2 | 20.91ms| https://school.programmers.co.kr/learn/courses/30/lessons/12973 |
- 짝지어 제거하기 : 짝지어 제거하기는, 알파벳 소문자로 이루어진 문자열을 가지고 시작합니다. 먼저 문자열에서 같은 알파벳이 2개 붙어 있는 짝을 찾습니다. 그다음, 그 둘을 제거한 뒤, 앞뒤로 문자열을 이어 붙입니다. 이 과정을 반복해서 문자열을 모두 제거한다면 짝지어 제거하기가 종료됩니다. 문자열 S가 주어졌을 때, 짝지어 제거하기를 성공적으로 수행할 수 있는지 반환하는 함수를 완성해 주세요. 성공적으로 수행할 수 있으면 1을, 아닐 경우 0을 리턴해주면 됩니다. 문자열을 모두 제거할 수 있으므로 1을 반환합니다.

[43일차] 김혜승 / 짝지어 제거하기

---

1st/Jiin/dice_game1.js

| 2024.04.16 | 43일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `JavaScript` <br> `vscode` |
| A + B | 프로그래머스 | Lv.0 | 0.06ms | https://school.programmers.co.kr/learn/courses/30/lessons/181839 |
- 주사위 게임 1 : 정육면체 주사위 2개를 굴린 값을 a, b라 할 때, 다음의 규칙에 맞는 값을 반환하시오.
***
오늘 코테는 최대한 코드를 적게 써보고 싶어서 1줄안에 욱여넣어 봤습니다. 
물론 실전에서 좋은 코드란 가독성이 좋아야 하므로 저런 코드를 내는순간 등짝(?)을 맞겠지요...

[43일차] 이지인 / 주사위 게임 1

---

1st/Sunhee/programmers/실패율.java

https://school.programmers.co.kr/learn/courses/30/lessons/42889
| 실패율 | 프로그래머스 | Lv.1 | 3.67ms | https://school.programmers.co.kr/learn/courses/30/lessons/42889 |
- 슈퍼 게임 개발자 오렐리는 큰 고민에 빠졌다. 그녀가 만든 프랜즈 오천성이 대성공을 거뒀지만, 요즘 신규 사용자의 수가 급감한 것이다. 원인은 신규 사용자와 기존 사용자 사이에 스테이지 차이가 너무 큰 것이 문제였다.
이 문제를 어떻게 할까 고민 한 그녀는 동적으로 게임 시간을 늘려서 난이도를 조절하기로 했다. 역시 슈퍼 개발자라 대부분의 로직은 쉽게 구현했지만, 실패율을 구하는 부분에서 위기에 빠지고 말았다. 오렐리를 위해 실패율을 구하는 코드를 완성하라.
실패율은 다음과 같이 정의한다.
스테이지에 도달했으나 아직 클리어하지 못한 플레이어의 수 / 스테이지에 도달한 플레이어 수
전체 스테이지의 개수 N, 게임을 이용하는 사용자가 현재 멈춰있는 스테이지의 번호가 담긴 배열 stages가 …

[43일차] 김선희 / 실패율 

---

1st/Jihyun/Programmers/MatrixAddition.java

| 2024.04.16 | 43일차 | <ul><li>[x] 문제 풀이</li><li>[ ] 버그 수정</li></ul> | `ver.8 java` <br> `vscode` |
| 행렬의 덧셈 | 프로그래머스 | Level.1 | 16.59ms | https://school.programmers.co.kr/learn/courses/30/lessons/12950 |
- 행렬의 덧셈 : 행과 열의 크기가 같은 2개의 행렬 arr1과 arr2가 주어질 때, 같은 행, 같은 열의 값을 서로 더한 결과를 출력하는 프로그램

[43일차] 김지현 / 행렬의 덧셈

---

1st/Jinseon/서울에서김서방찾기.java

https://school.programmers.co.kr/learn/courses/30/lessons/12919
| 서울에서 김서방 찾기 | 프로그래머스 | Level 1 | 3.47ms | https://school.programmers.co.kr/learn/courses/30/lessons/12919 |
<br/>
<hr/>
<br/>
- 서울에서 김서방 찾기 : equals와 String.valueOf()사용

[44일차]이진선 / 서울에서 김서방 찾기

---

1st/Jiin/from_back_to_top5.js

| 뒤에서 5등까지 | 프로그래머스 | Lv.0 | 0.07ms | [뒤에서 5등까지](https://school.programmers.co.kr/learn/courses/30/lessons/181853) |
***

[44일차] 이지인 / 뒤에서 5등까지

---

1st/Jinseon/달리기경주.java

https://school.programmers.co.kr/learn/courses/30/lessons/178871#
| 달리기 경주 | 프로그래머스 | Level 1 | 483.52ms | https://school.programmers.co.kr/learn/courses/30/lessons/178871#|
<hr/>
- 달리기 경주 : for문으로 했다가 시간초과 떠서.... hashmap으로 고쳤다...

[45일차]이진선 / 달리기 경주

---

1st/Jiin/Kth_number.js

| K번째수 | 프로그래머스 | Level.1 | 0.12ms | [K번째수](https://school.programmers.co.kr/learn/courses/30/lessons/42748) |
***
- K번째수 : array를 commands 첫 번째 수와 두 번째 수만큼 자른 후 오름차순으로 정렬한다. 그 배열에서 commands 세 번째 수에 위치한 수를 반환하면 된다. commands는 이차원 배열로서, 위와 같은 명령들이 최대 50개까지 존재한다. 명령을 실행한 결과값을 전부 순서대로 배열에 넣어 반환하시오.

[45일차] 이지인 / K번째수

---

1st/Sunhee/programmers/[1차] 다트 게임.java
1st/Sunhee/programmers/이진 변환 반복하기.java
1st/Sunhee/programmers/폰켓몬.java

https://school.programmers.co.kr/learn/courses/30/lessons/70129
| 이진 변환 반복하기 | 프로그래머스 | Level.1 | 4.42ms | https://school.programmers.co.kr/learn/courses/30/lessons/70129 |
<hr/>
- 0과 1로 이루어진 어떤 문자열 x에 대한 이진 변환을 다음과 같이 정의합니다.
x의 모든 0을 제거합니다.
x의 길이를 c라고 하면, x를 "c를 2진법으로 표현한 문자열"로 바꿉니다.
예를 들어, x = "0111010"이라면, x에 이진 변환을 가하면 x = "0111010" -> "1111" -> "100" 이 됩니다.
0과 1로 이루어진 문자열 s가 매개변수로 주어집니다. s가 "1"이 될 때까지 계속해서 s에 이진 변환을 가했을 때, 이진 변환의 횟수와 변환 과정에서 제거된 모든 0의 개수를 각각 배열에 담아 return 하도록 solution 함수를 완성해주세요.

[45일차] 김선희 / 이진 변환 반복하기

---

1st/Jihyun/Programmers/FoodFightCompetition.java

| 푸드 파이트 대회 | 프로그래머스 | Level.1 | 21.13ms | https://school.programmers.co.kr/learn/courses/30/lessons/134240 |
<hr/>
- 푸드 파이트 대회 : 수웅이가 준비한 음식의 양을 칼로리가 적은 순서대로 나타내는 정수 배열 food가 주어졌을 때, 대회를 위한 음식의 배치를 나타내는 문자열을 반환하는 프로그램

[45일차] 김지현 / 푸드 파이트 대회

---

1st/Hyeseung/Programmers/카드 뭉치.java

| 카드 뭉치 | 프로그래머스 | Level.1 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/159994?language=java |
<hr/>
- 카드 뭉치 : 코니는 영어 단어가 적힌 카드 뭉치 두 개를 선물로 받았습니다. 코니는 다음과 같은 규칙으로 카드에 적힌 단어들을 사용해 원하는 순서의 단어 배열을 만들 수 있는지 알고 싶습니다.
원하는 카드 뭉치에서 카드를 순서대로 한 장씩 사용합니다.
한 번 사용한 카드는 다시 사용할 수 없습니다.
카드를 사용하지 않고 다음 카드로 넘어갈 수 없습니다.
기존에 주어진 카드 뭉치의 단어 순서는 바꿀 수 없습니다.
예를 들어 첫 번째 카드 뭉치에 순서대로 ["i", "drink", "water"], 두 번째 카드 뭉치에 순서대로 ["want", "to"]가 적혀있을 때 ["i", "want", "to", "drink", "water"] 순서의 단어 배열을 만들려고 한다면 첫 번째 카드 뭉치에서 "i"를 사용한 후 두 번째 카드 뭉치에서 "want"와 "to"를 사용하고 첫 번째 카드뭉치에 "drink"와 "water"를 차례대로 사용하면 원하는 순서의 단어 배열을 만들 수 있습니다.
문자열로 이루어진 배열 cards1, cards2와 원하는 단어 배열 goal이 매개변수로 주어질 때, cards1과 cards2에 적힌 단어들로 goal를 만들 …

[46일차] 김혜승 / 카드 뭉치

---

1st/Jiin/TableHashMethod.java

| 테이블 해시 함수 | 프로그래머스 | Level.2 | 430.82ms | [테이블 해시 함수](https://school.programmers.co.kr/learn/courses/30/lessons/147354?language=java#) |
- 테이블 해시 함수 : 완호가 관리하는 어떤 데이터베이스의 한 테이블은 모두 정수 타입인 컬럼들로 이루어져 있습니다. 테이블은 2차원 행렬로 표현할 수 있으며 열은 컬럼을 나타내고, 행은 튜플을 나타냅니다.
첫 번째 컬럼은 기본키로서 모든 튜플에 대해 그 값이 중복되지 않도록 보장됩니다. 완호는 이 테이블에 대한 해시 함수를 다음과 같이 정의하였습니다.
해시 함수는 col, row_begin, row_end을 입력으로 받습니다.
테이블의 튜플을 col번째 컬럼의 값을 기준으로 오름차순 정렬을 하되, 만약 그 값이 동일하면 기본키인 첫 번째 컬럼의 값을 기준으로 내림차순 정렬합니다.
정렬된 데이터에서 S_i를 i 번째 행의 튜플에 대해 각 컬럼의 값을 i 로 나눈 나머지들의 합으로 정의합니다.
row_begin ≤ i ≤ row_end 인 모든 S_i를 누적하여 bitwise XOR 한 값을 해시 값으로서 반환합니다.
테이블의 데이터 data와 해시 함수에 대한 입력 col, row_begin, row_end이 주어졌을 때 테이블의 해시 값을 return 하도록 solution 함수를 완성해주세요.
***
#347 …

[46일차] 이지인 / 테이블 해시 함수

---

1st/Sunhee/programmers/테이블 해시 함수.java

https://school.programmers.co.kr/learn/courses/30/lessons/147354
| 테이블 해시 함수 | 프로그래머스 | Level.2 | 1.06ms | https://school.programmers.co.kr/learn/courses/30/lessons/147354 |
<hr/>
- 완호가 관리하는 어떤 데이터베이스의 한 테이블은 모두 정수 타입인 컬럼들로 이루어져 있습니다. 테이블은 2차원 행렬로 표현할 수 있으며 열은 컬럼을 나타내고, 행은 튜플을 나타냅니다.
첫 번째 컬럼은 기본키로서 모든 튜플에 대해 그 값이 중복되지 않도록 보장됩니다. 완호는 이 테이블에 대한 해시 함수를 다음과 같이 정의하였습니다.

#347 [46일차] 김선희 /  테이블 해시 함수 

---

1st/Jinseon/k번째수.java

https://school.programmers.co.kr/learn/courses/30/lessons/42748
| k번째 수 | 프로그래머스 | Level.1 | 0.57ms | [주소 ](https://school.programmers.co.kr/learn/courses/30/lessons/42748) |
<hr/>
- k번째 수 : i에서 시작해서 j로 끝나는 수 중에 오름차순으로 정렬하고 k번째 수를 찾는 문제. 가장 어려웠던 건. i에서 시작하고 j에서 끝나는 것이었다. 찾아보니 copyOfRange()라는 메소드가 있길래 이 메소드를 이용해 쉽게 풀 수 있었다.

[46일차] k번째수 / Level 1

---

1st/Jihyun/Programmers/FoodFightCompetition.java
1st/Jihyun/Programmers/ReverseString.java

| 문자열 뒤집기 | 프로그래머스 | Level.0 | 0.13ms | https://school.programmers.co.kr/learn/courses/30/lessons/120822 |
<hr/>
- 문자열 뒤집기: 문자열 my_string이 매개변수로 주어질 때 my_string을 거꾸로 뒤집은 문자열을 return하는 프로그램

[46일차] 김지현 / 문자열 뒤집기

---

1st/Hyeseung/Programmers/폰켓몬.java

| 폰켓몬 | 프로그래머스 | Level.1 | 3.54ms | https://school.programmers.co.kr/learn/courses/30/lessons/1845 |
<hr/>
- 폰켓몬 : 당신은 폰켓몬을 잡기 위한 오랜 여행 끝에, 홍 박사님의 연구실에 도착했습니다. 홍 박사님은 당신에게 자신의 연구실에 있는 총 N 마리의 폰켓몬 중에서 N/2마리를 가져가도 좋다고 했습니다.
홍 박사님 연구실의 폰켓몬은 종류에 따라 번호를 붙여 구분합니다. 따라서 같은 종류의 폰켓몬은 같은 번호를 가지고 있습니다. 예를 들어 연구실에 총 4마리의 폰켓몬이 있고, 각 폰켓몬의 종류 번호가 [3번, 1번, 2번, 3번]이라면 이는 3번 폰켓몬 두 마리, 1번 폰켓몬 한 마리, 2번 폰켓몬 한 마리가 있음을 나타냅니다. 이때, 4마리의 폰켓몬 중 2마리를 고르는 방법은 다음과 같이 6가지가 있습니다.
첫 번째(3번), 두 번째(1번) 폰켓몬을 선택
첫 번째(3번), 세 번째(2번) 폰켓몬을 선택
첫 번째(3번), 네 번째(3번) 폰켓몬을 선택
두 번째(1번), 세 번째(2번) 폰켓몬을 선택
두 번째(1번), 네 번째(3번) 폰켓몬을 선택
세 번째(2번), 네 번째(3번) 폰켓몬을 선택
이때, 첫 번째(3번) 폰켓몬과 네 번째(3번) 폰켓몬을 선택하는 방법은 한 종류(3번 폰켓몬 두 마리)의 폰켓몬만 가질 수 있지만, 다른 방법들은 모두 두 종류의 폰켓몬을 가질 수 …

[47일차] 김혜승 / 폰켓몬

---

1st/Jiin/Factorial2.java

| 팩토리얼 2 | 백준 | 브론즈 V | 204ms | [팩토리얼 2](https://www.acmicpc.net/problem/27433) |
***
- 팩토리얼 2 : 0보다 크거나 같은 정수 N이 주어진다. 이때, N!을 출력하는 프로그램을 작성하시오.

[47일차] 이지인 / 팩토리얼 2

---

1st/Jinseon/테이블해시함수.java

https://school.programmers.co.kr/learn/courses/30/lessons/147354?language=java
| 테이블 해시 함수 | 프로그래머스 | Level.2 | 13.52ms | [주소](https://school.programmers.co.kr/learn/courses/30/lessons/147354?language=java) |
<hr/>
- 테이블 해시 함수 : Arrays.sort(data, (o1, o2) -> {를 사용하여 정렬하며 if문에 o1과 o2가 같다면 내림차순 정렬(Integer.compare) ^=연산자를 사용하여 XOR 연산.
문제는 제대로 이해를 못했다는 것....계속 들어와서 이해할 때까지 보고 갈 예정입니다.....ㅠㅠ

[47일차] 이진선 / 테이블 해시 함수

---

1st/Jihyun/Programmers/AddYinAndYang.java

| 음양 더하기 | 프로그래머스 | Level.1 | 0.05ms | https://school.programmers.co.kr/learn/courses/30/lessons/76501 |
<hr/>
- 음양 더하기: 정수들의 절댓값을 차례대로 담은 정수 배열 absolutes와 정수들의 부호를 차례대로 담은 불리언 배열 signs가 매개변수로 주어질 때, 실제 정수들의 합을 구하여 return하는 프로그램

[47일차] 김지현 / 음양 더하기

---

1st/Sunhee/programmers/다음 큰 숫자.java

https://school.programmers.co.kr/learn/courses/30/lessons/12911
| 다음 큰 숫자 | 프로그래머스 | Level.1 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/12911 |
<hr/>
- 자연수 n이 주어졌을 때, n의 다음 큰 숫자는 다음과 같이 정의 합니다.
조건 1. n의 다음 큰 숫자는 n보다 큰 자연수 입니다.
조건 2. n의 다음 큰 숫자와 n은 2진수로 변환했을 때 1의 갯수가 같습니다.
조건 3. n의 다음 큰 숫자는 조건 1, 2를 만족하는 수 중 가장 작은 수 입니다.
예를 들어서 78(1001110)의 다음 큰 숫자는 83(1010011)입니다.
자연수 n이 매개변수로 주어질 때, n의 다음 큰 숫자를 return 하는 solution 함수를 완성해주세요.

[48일차] 김선희 / 다음 큰 숫자 

---

1st/Jihyun/Programmers/StringHandlingBasics.java

| 문자열 다루기 기본 | 프로그래머스 | Level.1 | 0.08ms | https://school.programmers.co.kr/learn/courses/30/lessons/12918 |
<hr/>
- 문자열 다루기 기본: 문자열 s의 길이가 4 혹은 6이고, 숫자로만 구성돼있는지 확인해주는 함수를 작성하는 프로그램

[48일차] 김지현 / 문자열 다루기 기본

---

1st/Jiin/print_average_daily_fee.sql

| 평균 일일 대여 요금 구하기 | 프로그래머스 | Level.1 | - | [평균 일일 대여 요금 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/151136) |
***
- 평균 일일 대여 요금 구하기 : 'SUV'인 자동차들의 평균 일일 요금을 컬럼명 'AVERAGE_FEE' 로 출력하기

[49일차] 이지인 / 평균 일일 대여 요금 구하기

---

1st/Jihyun/Programmers/TritFlip.java

| 3진법 뒤집기 | 프로그래머스 | Level.1 | 0.13ms | https://school.programmers.co.kr/learn/courses/30/lessons/68935 |
<hr/>
- 3진법 뒤집기: 자연수 n이 매개변수로 주어질 때, n을 3진법 상에서 앞뒤로 뒤집은 후, 이를 다시 10진법으로 표현한 수를 return하는 프로그램

[49일차] 김지현 / 3진법 뒤집기

---

1st/Jinseon/a와b출력하기.java

| a와 b출력하기 | 프로그래머스 | Level.0 | 157.74ms | [주소](https://school.programmers.co.kr/learn/courses/30/lessons/181951?language=java) |
<hr/>
- a와 b출력하기 : 문자열 연산자 사용

[49일차] 이진선 / a와 b출력하기

---

1st/Hyeseung/Programmers/다음 큰 숫자.java
1st/Hyeseung/Programmers/멀리 뛰기.java

| 다음 큰 숫자 | 프로그래머스 | Level.2 | 0.03ms | https://school.programmers.co.kr/learn/courses/30/lessons/12911 |
| 멀리 뛰기 | 프로그래머스 | Level.2 | 0.13ms | https://school.programmers.co.kr/learn/courses/30/lessons/12914 | 
<hr/>
- 다음 큰 숫자 : 자연수 n이 주어졌을 때, n의 다음 큰 숫자는 다음과 같이 정의 합니다.
조건 1. n의 다음 큰 숫자는 n보다 큰 자연수 입니다.
조건 2. n의 다음 큰 숫자와 n은 2진수로 변환했을 때 1의 갯수가 같습니다.
조건 3. n의 다음 큰 숫자는 조건 1, 2를 만족하는 수 중 가장 작은 수 입니다.
예를 들어서 78(1001110)의 다음 큰 숫자는 83(1010011)입니다.
자연수 n이 매개변수로 주어질 때, n의 다음 큰 숫자를 return 하는 solution 함수를 완성해주세요.
- 멀리 뛰기 : 멀리뛰기에 사용될 칸의 수 n이 주어질 때, 효진이가 끝에 도달하는 방법이 몇 가지인지 알아내, 여기에 1234567를 나눈 나머지를 리턴하는 함수, solution을 완성하세요. 예를 들어 4가 입력된다면, 5를 return하면 됩니다.

[50일차] 김혜승 / 다음 큰 숫자 외 1

---

1st/Jihyun/Programmers/AddDigits.java
1st/Jihyun/Programmers/AddMissingNumber.java
1st/Jihyun/Programmers/AddYinAndYang.java
1st/Jihyun/Programmers/ArrayOfNumbersDividedInto.java
1st/Jihyun/Programmers/CreateJadenCaseString.java
1st/Jihyun/Programmers/DotProduct.java
1st/Jihyun/Programmers/EvenOddNumber.java
1st/Jihyun/Programmers/FibonacciNumbers.java
1st/Jihyun/Programmers/FindAverage.java
1st/Jihyun/Programmers/FoodFightCompetition.java
1st/Jihyun/Programmers/IDontLikeSameNumber.java
1st/Jihyun/Programmers/MaxAndMin.java
1st/Jihyun/Programmers/NumberMultiplicationAndSum.java
1st/Jihyun/Programmers/SmallSubstring.java
1st/Jihyun/Programmers/StringHandlingBasics.java
1st/Jihyun/Programmers/StringReverseSort.java
1st/Jihyun/Programmers/SumBetweenTwoNumber.java
1st/Jihyun/Programmers/TritFlip.java

| 피보나치 수 | 프로그래머스 | Level.2 | 3.16ms | https://school.programmers.co.kr/learn/courses/30/lessons/12945 |
<hr/>
- 피보나치 수 : 2 이상의 n이 입력되었을 때, n번째 피보나치 수를 1234567으로 나눈 나머지를 리턴하는 함수를 작성하는 프로그램

[50일차] 김지현 / 피보나치 수

---

1st/Jinseon/문자열붙이기.java

| 문자열 붙이기 | 프로그래머스 | Level.0 | 163.09ms | [주소 ](https://school.programmers.co.kr/learn/courses/30/lessons/181946)|
<hr/>
- 문자열 붙이기 : concatenation operator사용

[50일차] 이진선 / 문자열 붙이기

---

1st/Jiin/print_age_info_is_empty.sql

| 나이 정보가 없는 회원 수 구하기 | 프로그래머스 | Level.1 | - | [나이 정보가 없는 회원 수 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/131528) |
<hr/>
- 나이 정보가 없는 회원 수 구하기 : 나이 정보가 비워있는 회원 수의 컬럼명을 'USERS'로 출력하시오

[50일차] 이지인 / 나이 정보가 없는 회원 수 구하기

---

1st/Jinseon/가위바위보.java

https://level.goorm.io/exam/43056/%EA%B0%80%EC%9C%84%EB%B0%94%EC%9C%84%EB%B3%B4/quiz/1
| 가위바위보 | 구름 | Level.1 | 0.06| [주소 ](https://level.goorm.io/exam/43056/%EA%B0%80%EC%9C%84%EB%B0%94%EC%9C%84%EB%B3%B4/quiz/1)|
<hr/>
- 가위바위보 : for, if, else if만으로 풀었기 때문에 코드가 좀 더럽다...

[51일차] 이진선 / 가위바위보

---

1st/Jihyun/Programmers/MakeWithL.java

| l로 만들기 | 프로그래머스 | Level.0 | 5.49ms | https://school.programmers.co.kr/learn/courses/30/lessons/181834# |
<hr/>
- l로 만들기: 알파벳 소문자로 이루어진 문자열 myString이 주어질 때, 알파벳 순서에서 "l"보다 앞서는 모든 문자를 "l"로 바꾼 문자열을 return하는 프로그램

[52일차] 김지현 / l로 만들기

---

1st/Jinseon/방배정하기.java
1st/Jinseon/합계산기.java

| 방 배정하기 | 구름 | Level.1 | 0.10ms | [주소 ](https://level.goorm.io/exam/48128/%EB%B0%A9-%EB%B0%B0%EC%A0%95%ED%95%98%EA%B8%B0/quiz/1)|
| 합 계산하기 | 구름 | Level.1 | 0.10ms| [주소 ](https://level.goorm.io/exam/195685/%ED%95%A9-%EA%B3%84%EC%82%B0%EA%B8%B0/quiz/1)|
<hr/>
- 방 배정하기 : 최대공약수를 구하여 계산함.
- 합 계산하기 : 간단하게 switch문을 사용함.

[52일차] 이진선 / 방 배정하기 외 1개

---

1st/Jihyun/Programmers/CreateMinimum.java
1st/Jihyun/Programmers/NumberOf7.java

| 최솟값 만들기 | 프로그래머스 | Level.2 | 0.60ms | https://school.programmers.co.kr/learn/courses/30/lessons/12941 |
<hr/>
- 최솟값 만들기: 자연수로 이루어져 있는 길이가 같은 배열 A, B 두 개가 주어질 때, A, B에서 각각 한 개의 숫자를 뽑아 두 수를 곱한 후 두 수를 곱한 값을 누적하여 더하는 프로그램

[53일차] 김지현 / 최솟값 만들기

---

1st/Jiin/AddNothingNumber.java

| 없는 숫자 더하기 | 프로그래머스 | Level.1 | 0.03ms | [없는 숫자 더하기](https://school.programmers.co.kr/learn/courses/30/lessons/86051?language=java) |
***
- 없는 숫자 더하기 : 주어지는 numbers배열에는 0~9까지의 정수중 몇개가 없다. 이때, 없는 정수들을 모두 더한 값을 반환하시오.

[53일차] 이지인 / 없는 숫자 더하기

---

1st/Hyeseung/Programmers/DATETIME에서 DATE로 형 변환.sql

| DATETIME에서 DATE로 형 변환 | 프로그래머스 |  Level.2 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/59414 |
<hr/>
- DATETIME에서 DATE로 형 변환 : ANIMAL_INS 테이블에 등록된 모든 레코드에 대해, 각 동물의 아이디와 이름, 들어온 날짜를 조회하는 SQL문을 작성해주세요. 이때 결과는 아이디 순으로 조회해야 합니다.

[53일차] 김혜승 / DATETIME에서 DATE로 형 변환

---

1st/Jinseon/직사각형별찍기.java

https://school.programmers.co.kr/learn/courses/30/lessons/12969?language=java
| 직사각형 별찍기| 프로그래머스 | Level.1 | 237.86ms | [주소 ](https://school.programmers.co.kr/learn/courses/30/lessons/12969?language=java)|
<hr/>
- 직사각형 별찍기 : 그냥 for문 이용함. 혹시 다른 방법 있다면 추천해주세요~

[53일차] 이진선 / 직사각형별찍기

---

1st/Sunhee/programmers/다음 큰 숫자.java
1st/Sunhee/programmers/숫자의 표현.java
1st/Sunhee/programmers/짝지어 제거하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/12973?language=java
| 짝지어 제거하기 | 프로그래머스 | Level.2 | 43.83ms | [주소](https://school.programmers.co.kr/learn/courses/30/lessons/12973?language=java) |
<hr/>
- 짝지어 제거하기는, 알파벳 소문자로 이루어진 문자열을 가지고 시작합니다. 먼저 문자열에서 같은 알파벳이 2개 붙어 있는 짝을 찾습니다. 그다음, 그 둘을 제거한 뒤, 앞뒤로 문자열을 이어 붙입니다. 이 과정을 반복해서 문자열을 모두 제거한다면 짝지어 제거하기가 종료됩니다. 문자열 S가 주어졌을 때, 짝지어 제거하기를 성공적으로 수행할 수 있는지 반환하는 함수를 완성해 주세요. 성공적으로 수행할 수 있으면 1을, 아닐 경우 0을 리턴해주면 됩니다.
예를 들어, 문자열 S = baabaa 라면
b aa baa → bb aa → aa →
의 순서로 문자열을 모두 제거할 수 있으므로 1을 반환합니다.

[53일차] 김선희 / 짝지어 제거하기 

---

1st/Jihyun/Programmers/EraseLetter.java
1st/Jihyun/Programmers/FibonacciNumbers.java
1st/Jihyun/Programmers/PersonWhoTallerThanMeosseug.java
1st/Jihyun/Programmers/ReturnsDifferentValuesD​ependingOnTheFlag.java
1st/Jihyun/Programmers/rny_string.java

| flag에 따라 다른 값 반환하기 | 프로그래머스 | Level.0 | 0.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/181933 |
| 글자 지우기 | 프로그래머스 | Level.0 | 0.64ms | https://school.programmers.co.kr/learn/courses/30/lessons/181900 |
| rny_string | 프로그래머스 | Level.0 | 0.21ms | https://school.programmers.co.kr/learn/courses/30/lessons/181863 |
<hr/>
- flag에 따라 다른 값 반환하기: 두 정수 a, b와 boolean 변수 flag가 매개변수로 주어질 때, flag가 true면 a + b를 false면 a - b를 return 하는 프로그램
- 글자 지우기: 문자열 my_string과 정수 배열 indices가 주어질 때, my_string에서 indices의 원소에 해당하는 인덱스의 글자를 지우고 이어 붙인 문자열을 return 하는 프로그램
- rny_string: 문자열 rny_string이 주어질 때, rny_string의 모든 'm'을 "rn"으로 바꾼 문자열을 return하는 프로그램

[54일차] 김지현 / flag에 따라 다른 값 반환하기 외 2개

---

1st/Hyeseung/Programmers/카테고리 별 상품 개수 구하기.sql

| 카테고리 별 상품 개수 구하기 | 프로그래머스 | Level.2 | 0ms | https://school.programmers.co.kr/learn/courses/30/lessons/131529 |
<hr/>
- 카테고리 별 상품 개수 구하기 : PRODUCT 테이블에서 상품 카테고리 코드(PRODUCT_CODE 앞 2자리) 별 상품 개수를 출력하는 SQL문을 작성해주세요. 결과는 상품 카테고리 코드를 기준으로 오름차순 정렬해주세요.

[54일차] 김혜승 / 카테고리 별 상품 개수 구하기

---

1st/Jiin/CodeForTwoPeople.java

| 둘만의 암호 | 프로그래머스 | Level.1 | 13.36ms | [둘만의 암호](https://school.programmers.co.kr/learn/courses/30/lessons/155652#) |
***
- 둘만의 암호 : s의 문자열에 있는 알파벳을 index만큼 뒤로 미루되, skip문자열에 있는 알파벳은 포함하지 않고 뒤로 미룬다. 이 규칙을 적용한 문자열을 반환하시오.

[54일차] 이지인 / 둘만의 암호

---

1st/Jinseon/예산.java

https://school.programmers.co.kr/learn/courses/30/lessons/12982?language=java
| 예산| 프로그래머스 | Level.1 | 0.67ms | [주소 ](https://school.programmers.co.kr/learn/courses/30/lessons/12982?language=java)|
<hr/>
- 예산 : 정렬하고 for문 돌리기. 만약 예산을 벗어나면 break;

[54일차] 이진선 / 예산

---

1st/Hyeseung/Programmers/중성화 여부 파악하기.sql

| 중성화 여부 파악하기 | 프로그래머스 | Level.2 | 0ms | [주소](https://school.programmers.co.kr/learn/courses/30/lessons/59409) |
<hr/>
- 중성화 여부 파악하기 : 보호소의 동물이 중성화되었는지 아닌지 파악하려 합니다. 중성화된 동물은 SEX_UPON_INTAKE 컬럼에 'Neutered' 또는 'Spayed'라는 단어가 들어있습니다. 동물의 아이디와 이름, 중성화 여부를 아이디 순으로 조회하는 SQL문을 작성해주세요. 이때 중성화가 되어있다면 'O', 아니라면 'X'라고 표시해주세요.

[55일차] 김혜승 / 중성화 여부 파악하기

---

1st/Jiin/HallOfFame1.java

| 명예의 전당 (1) | 프로그래머스 | Level.1 | 0ms | [명예의 전당 (1)](https://school.programmers.co.kr/learn/courses/30/lessons/138477) |
<hr/>
- 명예의 전당 (1) : "명예의 전당"이라는 TV 프로그램에서는 매일 1명의 가수가 노래를 부르고, 시청자들의 문자 투표수로 가수에게 점수를 부여합니다. 매일 출연한 가수의 점수가 지금까지 출연 가수들의 점수 중 상위 k번째 이내이면 해당 가수의 점수를 명예의 전당이라는 목록에 올려 기념합니다. 즉 프로그램 시작 이후 초기에 k일까지는 모든 출연 가수의 점수가 명예의 전당에 오르게 됩니다. k일 다음부터는 출연 가수의 점수가 기존의 명예의 전당 목록의 k번째 순위의 가수 점수보다 더 높으면, 출연 가수의 점수가 명예의 전당에 오르게 되고 기존의 k번째 순위의 점수는 명예의 전당에서 내려오게 됩니다. 
명예의 전당 목록의 점수의 개수 k, 1일부터 마지막 날까지 출연한 가수들의 점수인 score가 주어졌을 때, 매일 발표된 명예의 전당의 최하위 점수를 return하는 solution 함수를 완성해주세요.

[55일차] 이지인 / 명예의 전당 (1)

---

1st/Jinseon/Even.java

https://school.programmers.co.kr/learn/courses/30/lessons/120813?language=java
| 짝수는 싫어요 | 프로그래머스 | Level.0 | 0.03ms | [주소](https://school.programmers.co.kr/learn/courses/30/lessons/120813?language=java) |
<hr/>
- 짝수는 싫어요 : for문으로 간단하게 풀음

[55일차] 이진선 / 짝수는 싫어요

---

1st/Sunhee/programmers/카펫.java

https://school.programmers.co.kr/learn/courses/30/lessons/42842
| 카펫 | 프로그래머스 | Level.2 | 0.04ms | https://school.programmers.co.kr/learn/courses/30/lessons/42842 |
<hr/>
- Leo는 카펫을 사러 갔다가 아래 그림과 같이 중앙에는 노란색으로 칠해져 있고 테두리 1줄은 갈색으로 칠해져 있는 격자 모양 카펫을 봤습니다.
Leo는 집으로 돌아와서 아까 본 카펫의 노란색과 갈색으로 색칠된 격자의 개수는 기억했지만, 전체 카펫의 크기는 기억하지 못했습니다.
Leo가 본 카펫에서 갈색 격자의 수 brown, 노란색 격자의 수 yellow가 매개변수로 주어질 때 카펫의 가로, 세로 크기를 순서대로 배열에 담아 return 하도록 solution 함수를 작성해주세요.

[55일차] 김선희 / 카펫 

---

1st/Jihyun/Programmers/Budget.java
1st/Jihyun/Programmers/VerticalReading.java

| 예산 | 프로그래머스 | Level.1 | 0.49ms | https://school.programmers.co.kr/learn/courses/30/lessons/12982 |
<hr/>
- 예산 : 부서별로 신청한 금액이 들어있는 배열 d와 예산 budget이 매개변수로 주어질 때, 최대 몇 개의 부서에 물품을 지원할 수 있는지 return하는 프로그램

[55일차] 김지현 / 예산

---

1st/Hyeseung/Programmers/상품 별 오프라인 매출 구하기.sql
1st/Hyeseung/Programmers/완주하지 못한 선수.java
1st/Hyeseung/Programmers/전화번호 목록.java
1st/Hyeseung/Programmers/조건에 맞는 도서와 저자 리스트 출력하기.sql

| 완주하지 못한 선수 | 프로그래머스 |  Level.1 | 325.54ms | [주소 ](https://school.programmers.co.kr/learn/courses/30/lessons/42576) |
| 전화번호 목록  | 프로그래머스 |  Level.2 |  275.15ms | [주소 ](https://school.programmers.co.kr/learn/courses/30/lessons/42577) |
| 조건에 맞는 도서와 저자 리스트 출력하기 | 프로그래머스 |  Level.2 | 0ms | [주소 ](https://school.programmers.co.kr/learn/courses/30/lessons/144854)|
| 상품 별 오프라인 매출 구하기| 프로그래머스 |  Level.2 | 0ms | [주소 ](https://school.programmers.co.kr/learn/courses/30/lessons/131533)|
<hr/>
- 완주하지 못한 선수 : 마라톤에 참여한 선수들의 이름이 담긴 배열 participant와 완주한 선수들의 이름이 담긴 배열 completion이 주어질 때, 완주하지 못한 선수의 이름을 return 하도록 solution 함수를 작성해주세요.
- 전화번호 목록 : 전화번호부에 적힌 전화번호를 담은 배열 phone_book 이 solution 함수의 매개변수로 주어질 때, 어떤 번호가 다른 번호의 …

[56일차] 김혜승 / 완주하지 못한 선수 외 3개

---

1st/Jihyun/Programmers/KthNumber.java

| K번째 수 | 프로그래머스 | Level.1 | 0.27ms | https://school.programmers.co.kr/learn/courses/30/lessons/42748?language=java |
<hr/>
- K번째 수 : 배열 array, [i, j, k]를 원소로 가진 2차원 배열 commands가 매개변수로 주어질 때, 배열 array의 i번째 숫자부터 j번째 숫자까지 자르고 정렬했을 때, k번째에 있는 수를 담은 배열을 return 하는 프로그램

[56일차] 김지현 / K번째 수

---

1st/Jiin/babbling2.js

| 옹알이 (2) | 프로그래머스 | Level.1 | 0.49ms | [옹알이 (2)](https://school.programmers.co.kr/learn/courses/30/lessons/133499) |
<hr/>
- 옹알이 (2) : 머쓱이의 조카는 할 줄 아는 발음이 'aya', 'ye', 'woo', 'ma' 밖에 없다. 또한 같은 발음을 연속해서 하는 것도 힘들어 한다. 여러 단어 배열 babbling이 주어질 때, 조카가 발음 할 수 있는 단어의 수를 반환하시오.

[56일차] 이지인 / 옹알이 (2)

---

1st/Jinseon/1로만들기.java

https://school.programmers.co.kr/learn/courses/30/lessons/181880
| 1로 만들기 | 프로그래머스 | Level.0 | 0.03ms | [주소](https://school.programmers.co.kr/learn/courses/30/lessons/181880) |
<hr/>
- 1로 만들기 : 사실 증감식을 넣어야 하는 게 맞지만 이 문제는 증감식에 대입을 넣는 게 더 간단하게 풀 수 있을 것 같아서 for문 증감식에 j = num_list[i]를 넣었다.

[56일차] 이진선 / 1로 만들기

---

1st/Jiin/d_between_dist_average.sql

| 노션별 평균 역 사이 거리 조회하기 | 프로그래머스 | Level.2 | - | [노션별 평균 역 사이 거리 조회하기](https://school.programmers.co.kr/learn/courses/30/lessons/284531#qna) |
<hr/>
- 노션별 평균 역 사이 거리 조회하기 : SUBWAY_DISTANCE 테이블에서 노선별로 노선, 총 누계 거리, 평균 역 사이 거리를 노선별로 조회하는 SQL문을 작성해주세요.
총 누계거리는 테이블 내 존재하는 역들의 역 사이 거리의 총 합을 뜻합니다. 총 누계 거리와 평균 역 사이 거리의 컬럼명은 각각 TOTAL_DISTANCE, AVERAGE_DISTANCE로 해주시고, 총 누계거리는 소수 둘째자리에서, 평균 역 사이 거리는 소수 셋째 자리에서 반올림 한 뒤 단위(km)를 함께 출력해주세요.
결과는 총 누계 거리를 기준으로 내림차순 정렬해주세요.

[57일차] 이지인 / 노선별 평균 역 사이 거리 조회하기 

---

1st/Jinseon/비밀지도.java

| 비밀지도 | 프로그래머스 | Level.1 |
<hr/>
- 비밀지도
arr1[i] | arr2[i] : 비트를 비교하고, 둘 중 하나라도 1인 경우 해당 비트를 1로 설정
toBinaryString : 2진수로 변경
format("%" + n + "s") : %와 s를 사용하여 문자열을 왼쪽으로 정렬하고, 폭을 n으로 지정

[59일차] 이진선 / 비밀지도

---

1st/Hyeseung/Programmers/문자열 바꿔서 찾기.java

[59일차] 김혜승 / 문자열 바꿔서 찾기

---

1st/Jiin/CompareToTwoCalculatingNumber.java
1st/Jiin/CreateArray4.java
1st/Jiin/ReturnTheDifferValueForOddOrEven.java
1st/Jiin/StringMultiplcation.java

| [배열 만들기 4](https://school.programmers.co.kr/learn/courses/30/lessons/181918) | 프로그래머스 | Level.0 |
| [홀짝에 따라 다른 값 반환하기](https://school.programmers.co.kr/learn/courses/30/lessons/181935) | 프로그래머스 | Level.0 |
| [문자열 곱하기](https://school.programmers.co.kr/learn/courses/30/lessons/181940) | 프로그래머스 | Level.0 |
| [두 수의 연산값 비교하기](https://school.programmers.co.kr/learn/courses/30/lessons/181938) | 프로그래머스 | Level.0 |
<hr/>
- 배열 만들기 4 : 주어진 정수 배열 arr을 다음과 같은 규칙으로 새로운 stk 배열로 만들려고 한다.
1. 변수 i를 0으로 초기화 합니다.
2. 만약 stk가 빈 배열이라면 arr[i]를 stk에 추가하고 i에 1을 더합니다.
3. stk에 원소가 있고, stk의 마지막 원소가 arr[i]보다 작으면 arr[i]를 stk의 뒤에 추가하고 i에 1을 더합니다.
4. stk에 원소가 있는데 stk의 마지막 원소가 arr[i]보다 크거나 같으면 stk의 마지막 원소를 stk에서 제거합니다.
- 홀짝에 따라 다른 값 반환하기 : 주어진 양의 정수 n이 짝수라면 n 이하의 짝수들의 제곱 값을 …

[59일차] 이지인 / 배열 만들기 4 외 3개

---

1st/Jihyun/Programmers/NumberOfPAndYInString.java

| 문자열 내 p와 y의 개수 | 프로그래머스 | Level.1 |
<hr/>
- 문자열 내 p와 y의 개수 : 대문자와 소문자가 섞여있는 문자열 s가 주어질 때, 'p'의 개수와 'y'의 개수를 비교해 같으면 True, 다르면 False를 return 하는 solution 작성 (단, 개수를 비교할 때 대문자와 소문자 구별 X)

[59일차] 김지현 / 문자열 내 p와 y의 개수

---

1st/Jinseon/대문자로 바꾸기.java

<hr/>
- 대문자로 바꾸기 : toUpperCase()사용

[60일차] 이진선 / 대문자로 바꾸기

---

1st/Hyeseung/Programmers/특별한 이차원 배열 1.java

| 특별한 이차원 배열 1  | 프로그래머스 | Level.0 |
<hr/>
- 특별한 이차원 배열 1  : 정수 n이 매개변수로 주어질 때, 다음과 같은 n × n 크기의 이차원 배열 arr를 return 하는 solution 함수를 작성해 주세요. arr[i][j] (0 ≤ i, j < n)의 값은 i = j라면 1, 아니라면 0입니다.

[60일차] 김혜승 / 특별한 이차원 배열 1 

---

3st/Jaeyoung/가습기.java

https://school.programmers.co.kr/learn/courses/30/lessons/250127
| 가습기 | 프로그래머스 | Level.0 |
<hr/>
- 가습기 : 상우가 사용하는 가습기에는 "auto", "target", "minimum"의 세 가지 모드가 있습니다. 가습기의 가습량은 0~5단계로 구분되며 각 모드 별 동작 방식은 다음과 같습니다.
"auto" 모드
습도가 0 이상 10 미만인 경우 : 5단계
습도가 10 이상 20 미만인 경우 : 4단계
습도가 20 이상 30 미만인 경우 : 3단계
습도가 30 이상 40 미만인 경우 : 2단계
습도가 40 이상 50 미만인 경우 : 1단계
습도가 50 이상인 경우 : 0단계
"target" 모드
습도가 설정값 미만일 경우 : 3단계
습도가 설정값 이상일 경우 : 1단계
"minimum"모드
습도가 설정값 미만일 경우 : 1단계
습도가 설정값 이상일 경우 : 0단계
상우가 설정한 가습기의 모드를 나타낸 문자열 mode_type, 현재 공기 중 습도를 나타낸 정수 humidity, 설정값을 나타낸 정수 val_set이 주어질 때 현재 가습기가 몇 단계로 작동 중인지 return하도록 빈칸을 채워 solution 함수를 완성해 주세요.

[60일차] 박재영 / 가습기

---

1st/Jiin/Szyfr.java

| [Szyfr](https://www.acmicpc.net/problem/8610) | 백준 | 브론즈 I |
<hr/>
- Szyfr : Jaś는 카이사르 암호문을 해독해야 합니다. 그런데 key가 몇 인지 모릅니다. 대신 암호중 가장 많은 글자를 차지하는 알파벳의 복호된 알파벳을 알고있습니다. 첫 번째 줄에 암호의 길이와 가장 많은 알파벳의 암호화 전 알파벳이 주어집니다. 두 번째 줄에는 카이사르 암호문이 주어집니다. 원래 글자가 무엇인지 복호화 하시오.

[60일차] 이지인 / Szyfr

---

1st/Jihyun/Programmers/PlaceIntegersInReverseOrder.java

| 정수 내림차순으로 배치하기 | 프로그래머스 | Level.1 |
<hr/>
- 정수 내림차순으로 배치하기 : 정수 n이 매개변수로 주어질 때, n의 각 자릿수를 큰것부터 작은 순으로 정렬한 새로운 정수를 리턴하는 solution 작성

[60일차] 김지현 / 정수 내림차순으로 배치하기

---

2st/Riyeon/9로 나눈 나머지.java
2st/Riyeon/간단한 논리 연산.java
2st/Riyeon/글자 이어 붙여 문자열 만들기.java
2st/Riyeon/문자열 여러 번 뒤집기.java
2st/Riyeon/배열 만들기 4.java
2st/Riyeon/주사위 게임 3.java

| 배열 만들기 4 | 프로그래머스 | Level.0 |
| 간단한 논리 연산 | 프로그래머스 | Level.0 |
| 주사위 게임 3| 프로그래머스 | Level.0 |
| 글자 이어 붙여 문자열 만들기 | 프로그래머스 | Level.0 |
| 9로 나눈 나머지 | 프로그래머스 | Level.0 |
| 문자열 여러 번 뒤집기 | 프로그래머스 | Level.0 |
<hr/>
- 배열 만들기 4 : arr를 이용해 새로운 배열 stk를 만들기.
<배열 만드는 규칙>
만약 stk가 빈 배열이라면 arr[i]를 stk에 추가하고 i에 1을 더합니다.
stk에 원소가 있고, stk의 마지막 원소가 arr[i]보다 작으면 arr[i]를 stk의 뒤에 추가하고 i에 1을 더합니다.
stk에 원소가 있는데 stk의 마지막 원소가 arr[i]보다 크거나 같으면 stk의 마지막 원소를 stk에서 제거합니다.
- 간단한 논리 연산 :  boolean 변수 x1, x2, x3, x4가 매개변수로 주어질 때, (x1 ∨ x2) ∧ (x3 ∨ x4)의 true/false를 return 하는 solution 함수를 작성하. (∧ = and, ∨ = or)
- 주사위 게임 3 : 네 주사위를 굴렸을 때 나온 숫자가 정수 매개변수 a, b, c, d로 주어질 때, 얻는 점수를 return 하는 solution 함수를 작성하기
<점수 얻는 방법> 
네 주사위에서 나온 숫자가 모두 p로 같다면 1111 × p점을 얻습니다.
세 주사위에서 나온 숫자가 p로 …

[60일차] 김리연 / 배열 만들기 4 외 5개

---

1st/Hyeseung/Programmers/오랜 기간 보호한 동물(2).sql

| 오랜 기간 보호한 동물(2) | 프로그래머스 | Level.3 |
<hr/>
- 오랜 기간 보호한 동물(2) : 입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름을 조회하는 SQL문을 작성해주세요. 이때 결과는 보호 기간이 긴 순으로 조회해야 합니다.

[61일차] 김혜승 / 오랜 기간 보호한 동물(2) 

---

1st/Jiin/print_the_number_of_fish_caught_per_month.sql

| [월별 잡은 물고기 수 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/293260) | 프로그래머스 | Level.2 |
<hr/>
- 월별 잡은 물고기 수 구하기 : 월별로 잡은 물고기 수의 열 이름을 FISH_COUNT라 하고, 월을 나타내는 행의 이름을 MONTH라 하여 출력하시오.

[61일차] 이지인 / 월별 잡은 물고기 수 구하기

---

1st/Sunhee/programmers/예상 대진표.java

https://school.programmers.co.kr/learn/courses/30/lessons/12985
| 예상 대진표 | 프로그래머스 | Level.2 |
<hr/>
- △△ 게임대회가 개최되었습니다. 이 대회는 N명이 참가하고, 토너먼트 형식으로 진행됩니다. N명의 참가자는 각각 1부터 N번을 차례대로 배정받습니다. 그리고, 1번↔2번, 3번↔4번, ... , N-1번↔N번의 참가자끼리 게임을 진행합니다. 각 게임에서 이긴 사람은 다음 라운드에 진출할 수 있습니다. 이때, 다음 라운드에 진출할 참가자의 번호는 다시 1번부터 N/2번을 차례대로 배정받습니다. 만약 1번↔2번 끼리 겨루는 게임에서 2번이 승리했다면 다음 라운드에서 1번을 부여받고, 3번↔4번에서 겨루는 게임에서 3번이 승리했다면 다음 라운드에서 2번을 부여받게 됩니다. 게임은 최종 한 명이 남을 때까지 진행됩니다.
이때, 처음 라운드에서 A번을 가진 참가자는 경쟁자로 생각하는 B번 참가자와 몇 번째 라운드에서 만나는지 궁금해졌습니다. 게임 참가자 수 N, 참가자 번호 A, 경쟁자 번호 B가 함수 solution의 매개변수로 주어질 때, 처음 라운드에서 A번을 가진 참가자는 경쟁자로 생각하는 B번 참가자와 몇 번째 라운드에서 만나는지 return 하는 solution 함수를 완성해 주세요. 단, A번 참가자와 B번 참가자는 서로 붙게 되기 전까지 항상 이긴다고 가정합니다.

[61일차] 김선희 / 예상 대진표 

---

1st/Jinseon/세로 읽기.java

https://school.programmers.co.kr/learn/courses/30/lessons/181904
| 세로 읽기 | 프로그래머스 | Level.0 |
<hr/>
- 세로 읽기 : for문에서 증감과 초기화를 각각 m, c 변수를 사용하여 문제를 풀었다.

[61일차] 이진선 / 세로 읽기

---

3st/Jaeyoung/덧셈식 출력하기.java

| 덧셈식 출력하기 | 프로그래머스 | Level.0 |
<hr/>

[61일차] 박재영 / 덧셈식 출력하기

---

1st/Jihyun/Programmers/GetMiddleLetter.java

| 가운데 글자 가져오기 | 프로그래머스 | Level.1 |
<hr/>
- 가운데 글자 가져오기 : 문자열 s가 주어졌을 때, 단어 s의 가운데 글자를 반환하는 함수, solution 작성

[61일차] 김지현 / 가운데 글자 가져오기

---

2st/Riyeon/qr code.java
2st/Riyeon/문자열 뒤집기.java
2st/Riyeon/문자열의 뒤의 n글자.java
2st/Riyeon/문자열의 앞의 n글자.java
2st/Riyeon/배열 만들기 5.java
2st/Riyeon/부분 문자열 이어 붙여 문자열 만들기.java
2st/Riyeon/세로 읽기.java
2st/Riyeon/접두사인지 확인하기.java
2st/Riyeon/접미사 배열.java
2st/Riyeon/접미사인지 확인하기.java

| 배열 만들기 5 | 프로그래머스 | Level.0 |
| 접미사 배열| 프로그래머스 | Level.0 |
| 접미사인지 확인하기 | 프로그래머스 | Level.0 |
| 문자열의 앞의 n글자| 프로그래머스 | Level.0 |
| 접두사인지 확인하기| 프로그래머스 | Level.0 |
| 문자열 뒤집기| 프로그래머스 | Level.0 |
| 세로 읽기| 프로그래머스 | Level.0 |
| qr code| 프로그래머스 | Level.0 |
<hr/>
- 배열 만들기 5 : 배열 intStrs의 각 원소마다 s번 인덱스에서 시작하는 길이 l짜리 부분 문자열을 잘라내 정수로 변환. 이때 변환한 정수값이 k보다 큰 값들을 담은 배열을 return 하는 solution 함수 작성.
- 부분 문자열 이어 붙여 문자열 만들기 : my_strings의 원소의 parts에 해당하는 부분 문자열을 순서대로 이어 붙인 문자열을 return 하는 solution 함수를 작성.
- 문자열의 뒤의 n글자  : my_string의 뒤의 n글자로 이루어진 문자열을 return 하는 solution 함수를 작성.
- 접미사 배열 : my_string이 매개변수로 주어질 때, my_string의 모든 접미사( 특정 인덱스부터 시작하는 문자열)를 사전순으로 정렬한 문자열 배열을 return 하는 solution …

[61일차] 김리연 / 배열 만들기 5 외 9개

---

1st/Jinseon/순서바꾸기.java

[62일차] 이진선 / 순서 바꾸기

---

3st/Hyeonseo/핸드폰 번호 가리기

| 제목 | 백준 / 프로그래머스 | 브론즈 V / Level.1 |
<hr/>
- 제목 : 프로그래머스 모바일은 개인정보 보호를 위해 고지서를 보낼 때 고객들의 전화번호의 일부를 가립니다.
전화번호가 문자열 phone_number로 주어졌을 때, 전화번호의 뒷 4자리를 제외한 나머지 숫자를 전부 *으로 가린 문자열을 리턴하는 함수, solution을 완성해주세요.

[62일차] 조현서 / 핸드폰 번호 가리기

---

1st/Hyeseung/Programmers/카테고리 별 도서 판매량 집계하기.sql

| 카테고리 별 도서 판매량 집계하기 |  프로그래머스 | Level.3 |
<hr/>
- 카테고리 별 도서 판매량 집계하기 : 2022년 1월의 카테고리 별 도서 판매량을 합산하고, 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력하는 SQL문을 작성해주세요.
결과는 카테고리명을 기준으로 오름차순 정렬해주세요.

[62일차] 김혜승 / 카테고리 별 도서 판매량 집계하기

---

2st/Riyeon/2의 영역.java
2st/Riyeon/가까운 1 찾기.java
2st/Riyeon/글자 지우기.java
2st/Riyeon/리스트 자르기.java
2st/Riyeon/문자 개수 세기.java
2st/Riyeon/배열 만들기 1.java
2st/Riyeon/배열 만들기 3.java
2st/Riyeon/배열 조각하기.java
2st/Riyeon/첫 번째로 나오는 음수.java
2st/Riyeon/카운트 다운.java

| 문자 개수 세기 | 프로그래머스 | Level.0 |
| 글자 지우기 | 프로그래머스 | Level.0 |
| 리스트 자르기 | 프로그래머스 | Level.0 |
| 배열 만들기 3 | 프로그래머스 | Level.0 |
| 2의 영역 | 프로그래머스 | Level.0 |
|배열 조각하기 | 프로그래머스 | Level.0 |
<hr/>
- 문자 개수 세기 : 알파벳 대소문자로만 이루어진 문자열 my_string이 주어질 때, my_string에서 'A'의 개수, my_string에서 'B'의 개수,..., my_string에서 'Z'의 개수, my_string에서 'a'의 개수, my_string에서 'b'의 개수,..., my_string에서 'z'의 개수를 순서대로 담은 길이 52의 정수 배열을 return 하는 solution 함수를 작성해 주세요.알파벳 대소문자로만 이루어진 문자열 my_string이 주어질 때, my_string에서 'A'의 개수, my_string에서 'B'의 개수,..., my_string에서 'Z'의 개수, my_string에서 'a'의 개수, my_string에서 'b'의 개수,..., my_string에서 'z'의 개수를 순서대로 담은 길이 52의 정수 배열을 …

[62일차] 김리연 / 문자 개수 세기 외 9개

---

1st/Jiin/Network.java

| [네트워크](https://school.programmers.co.kr/learn/courses/30/lessons/43162#qna) | 프로그래머스 | Level.3 |
<hr/>
- 네트워크 : 네트워크란 컴퓨터 상호 간에 정보를 교환할 수 있도록 연결된 형태를 의미합니다. 예를 들어, 컴퓨터 A와 컴퓨터 B가 직접적으로 연결되어있고, 컴퓨터 B와 컴퓨터 C가 직접적으로 연결되어 있을 때 컴퓨터 A와 컴퓨터 C도 간접적으로 연결되어 정보를 교환할 수 있습니다. 따라서 컴퓨터 A, B, C는 모두 같은 네트워크 상에 있다고 할 수 있습니다.
컴퓨터의 개수 n, 연결에 대한 정보가 담긴 2차원 배열 computers가 매개변수로 주어질 때, 네트워크의 개수를 return 하도록 solution 함수를 작성하시오.

[62일차] 이지인 / 네트워크

---

1st/Hyeseung/Programmers/있었는데요 없었습니다.sql

| 있었는데요 없었습니다 | 프로그래머스 | Level.3 |
<hr/>
- 있었는데요 없었습니다 : 관리자의 실수로 일부 동물의 입양일이 잘못 입력되었습니다. 보호 시작일보다 입양일이 더 빠른 동물의 아이디와 이름을 조회하는 SQL문을 작성해주세요. 이때 결과는 보호 시작일이 빠른 순으로 조회해야합니다.

[63일차] 김혜승 / 있었는데요 없었습니다

---

2st/Riyeon/5명씩.java
2st/Riyeon/n 번째 원소까지.java
2st/Riyeon/n 번째 원소부터.java
2st/Riyeon/n개 간격의 원소들.java
2st/Riyeon/수열과 구간 쿼리 1.java
2st/Riyeon/순서 바꾸기.java
2st/Riyeon/왼쪽 오른쪽.java
2st/Riyeon/할 일 목록.java

| n 번째 원소부터 | 프로그래머스 | Level.0 |
| 왼쪽 오른쪽 | 프로그래머스 | Level.0 |
<hr/>
- 순서 바꾸기 : 정수 리스트 num_list와 정수 n이 주어질 때, num_list를 n 번째 원소 이후의 원소들과 n 번째까지의 원소들로 나눠 n 번째 원소 이후의 원소들을 n 번째까지의 원소들 앞에 붙인 리스트를 return하도록 solution 함수를 완성해주세요.
- 왼쪽 오른쪽 : 문자열 리스트 str_list에는 "u", "d", "l", "r" 네 개의 문자열이 여러 개 저장되어 있습니다. str_list에서 "l"과 "r" 중 먼저 나오는 문자열이 "l"이라면 해당 문자열을 기준으로 왼쪽에 있는 문자열들을 순서대로 담은 리스트를, 먼저 나오는 문자열이 "r"이라면 해당 문자열을 기준으로 오른쪽에 있는 문자열들을 순서대로 담은 리스트를 return하도록 solution 함수를 완성해주세요. "l"이나 "r"이 없다면 빈 …

[63일차] 김리연 / n 번째 원소부터 외 6개

---

1st/Jiin/H-Index.java

| [H-Index](https://school.programmers.co.kr/learn/courses/30/lessons/42747#fn1) | 프로그래머스 | Level.2 |
<hr/>
- H-Index : 과학자들의 논문 인용 수가 배열로 주어질 때 과학자의 [H-Index](https://en.wikipedia.org/wiki/H-index)를 구하시오.

[63일차] 이지인 / H-Index

---

2st/Riyeon/1로 만들기.java
2st/Riyeon/꼬리 문자열.java
2st/Riyeon/부분 문자열.java
2st/Riyeon/부분 문자열인지 확인하기.java
2st/Riyeon/조건에 맞게 수열 변환하기 2.java

| 조건에 맞게 수열 변환하기 2 | 프로그래머스 | Level.0 |
| 1로 만들기 | 프로그래머스 | Level.0 |
| 부분 문자열인지 확인하기 | 프로그래머스 | Level.0 |
<hr/>
- 수열과 구간 쿼리 1 : 정수 배열 arr와 2차원 정수 배열 queries이 주어집니다. queries의 원소는 각각 하나의 query를 나타내며, [s, e] 꼴입니다. 각 query마다 순서대로 s ≤ i ≤ e인 모든 i에 대해 arr[i]에 1을 더합니다. 위 규칙에 따라 queries를 처리한 이후의 arr를 return 하는 solution 함수를 완성해 주세요.
- 조건에 맞게 수열 변환하기 2 : 정수 배열 arr가 주어집니다. arr의 각 원소에 대해 값이 50보다 크거나 같은 짝수라면 2로 나누고, 50보다 작은 홀수라면 2를 곱하고 다시 1을 더합니다. 이러한 작업을 x번 반복한 결과인 배열을 arr(x)라고 표현했을 때, arr(x) = arr(x + 1)인 x가 항상 존재합니다. 이러한 x 중 가장 작은 값을 return 하는 solution 함수를 완성해 주세요. 단, 두 배열에 대한 "="는 두 배열의 크기가 서로 같으며, 같은 인덱스의 원소가 각각 서로 같음을 의미합니다.
- 1로 만들기 : 정수가 있을 때, 짝수라면 반으로 …

[64일차] 김리연 / 수열과 구간 쿼리 1 외 5개

---

1st/Jinseon/길이에따른연산.java

https://school.programmers.co.kr/learn/courses/30/lessons/181879
| 길이에 따른 연산 | 프로그래머스 | Level.0 |
<hr/>
- 길이에 따른 연산 : length 사용함.

[63일차]이진선 / 길이에 따른 연산

---

1st/Jihyun/Programmers/IDontLikeEnglish.java

| 영어가 싫어요 | 프로그래머스 | Level.0 |
<hr/>
- 영어가 싫어요 : 문자열 numbers가 매개변수로 주어질 때, numbers를 영어로 표기되어있는 숫자를 정수로  바꿔 return 하는 solution 작성

[63일차] 김지현 / 영어가 싫어요

---

1st/Sunhee/programmers/멀리 뛰기.java
1st/Sunhee/programmers/영어 끝말잇기.java

| 멀리 뛰기 | 프로그래머스 |  Level.2 |
| 영어 끝말잇기 | 프로그래머스 |  Level.2 |
<hr/>
- 효진이는 멀리 뛰기를 연습하고 있습니다. 효진이는 한번에 1칸, 또는 2칸을 뛸 수 있습니다. 칸이 총 4개 있을 때, 효진이는
(1칸, 1칸, 1칸, 1칸)
(1칸, 2칸, 1칸)
(1칸, 1칸, 2칸)
(2칸, 1칸, 1칸)
(2칸, 2칸)
의 5가지 방법으로 맨 끝 칸에 도달할 수 있습니다. 멀리뛰기에 사용될 칸의 수 n이 주어질 때, 효진이가 끝에 도달하는 방법이 몇 가지인지 알아내, 여기에 1234567를 나눈 나머지를 리턴하는 함수, solution을 완성하세요. 예를 들어 4가 입력된다면, 5를 return하면 됩니다.
- 1부터 n까지 번호가 붙어있는 n명의 사람이 영어 끝말잇기를 하고 있습니다. 영어 끝말잇기는 다음과 같은 규칙으로 진행됩니다.

[64일차] 김선희 / 멀리 뛰기 외 1개

---

1st/Jihyun/Programmers/NumberStringsAndEnglishWords.java

| 숫자 문자열과 영단어 | 프로그래머스 | Level.1 |
<hr/>
- 숫자 문자열과 영단어 : 숫자의 일부 자릿수가 영단어로 바뀌어졌거나, 혹은 바뀌지 않고 그대로인 문자열 s가 매개변수로 주어질 때, s가 의미하는 원래 숫자를 return 하도록 solution 작성

[64일차] 김지현 / 숫자 문자열과 영단어

---

1st/Hyeseung/Programmers/오랜 기간 보호한 동물(1).sql

| 오랜 기간 보호한 동물(1)  | 프로그래머스 | Level.3 |
<hr/>
- 오랜 기간 보호한 동물(1)  : 아직 입양을 못 간 동물 중, 가장 오래 보호소에 있었던 동물 3마리의 이름과 보호 시작일을 조회하는 SQL문을 작성해주세요. 이때 결과는 보호 시작일 순으로 조회해야 합니다.

[64일차] 김혜승 / 오랜 기간 보호한 동물(1) 

---

1st/Jiin/RightParentheses.java

| [올바른 괄호](https://school.programmers.co.kr/learn/courses/30/lessons/12909) | 프로그래머스 | Level.2 |
<hr/>
- 올바른 괄호 : 괄호가 올바르게 열려있고 닫혀있다면 그것은 올바른 괄호 입니다. 주어진 문자열이 올바른 괄호라면 true, 아니라면 false를 반환하시오.
`()()`, `(()(()))` 은 올바른 괄호입니다.
`)(()`, `(()))(` 은 올바른 괄호가 아닙니다.

[64일차] 이지인 / 올바른 괄호

---

2st/Riyeon/0 떼기.java
2st/Riyeon/A 강조하기.java
2st/Riyeon/ad 제거하기.java
2st/Riyeon/공백으로 구분하기 1.java
2st/Riyeon/공백으로 구분하기 2.java
2st/Riyeon/문자열 정수의 합.java
2st/Riyeon/문자열이 몇 번 등장하는지 세기.java
2st/Riyeon/배열에서 문자열 대소문자 변환하기.java
2st/Riyeon/특정 문자열로 끝나는 가장 긴 부분 문자열 찾기.java
2st/Riyeon/특정한 문자를 대문자로 바꾸기.java

| 특정한 문자를 대문자로 바꾸기 | 프로그래머스 | Level.0 |
| 특정 문자열로 끝나는 가장 긴 부분 문자열 찾기 | 프로그래머스 | Level.0 |
| 문자열이 몇 번 등장하는지 세기 | 프로그래머스 | Level.0 |
| ad 제거하기 | 프로그래머스 | Level.0 |
| 공백으로 구분하기 1 | 프로그래머스 | Level.0 |
| 공백으로 구분하기 2 | 프로그래머스 | Level.0 |
| 0 떼기 | 프로그래머스 | Level.0 |
<hr/>
- 특정한 문자를 대문자로 바꾸기 : 영소문자로 이루어진 문자열 my_string과 영소문자 1글자로 이루어진 문자열 alp가 매개변수로 주어질 때, …

[65일차] 김리연 / 배열에서 문자열 대소문자 변환하기 외 9개

---

2st/Riyeon/rny_string.java
2st/Riyeon/x 사이의 개수.java
2st/Riyeon/간단한 식 계산하기.java
2st/Riyeon/문자열 바꿔서 찾기.java
2st/Riyeon/문자열 잘라서 정렬하기.java
2st/Riyeon/배열의 원소만큼 추가하기.java
2st/Riyeon/세 개의 구분자.java

| x 사이의 개수 | 프로그래머스 | Level.0 |
| 문자열 잘라서 정렬하기 | 프로그래머스 | Level.0 |
| 세 개의 구분자 | 프로그래머스 | Level.0 |
<hr/>
- x 사이의 개수 : 문자열 myString이 주어집니다. myString을 문자 "x"를 기준으로 나눴을 때 나눠진 문자열 각각의 길이를 순서대로 저장한 배열을 return 하는 solution 함수를 완성해 주세요.
- 문자열 잘라서 정렬하기 : 문자열 myString이 주어집니다. "x"를 기준으로 해당 문자열을 잘라내 배열을 만든 후 사전순으로 정렬한 배열을 return 하는 solution 함수를 완성해 주세요. 단, 빈 문자열은 반환할 배열에 넣지 않습니다.
- 문자열 바꿔서 찾기 : 문자 "A"와 "B"로 이루어진 문자열 myString과 pat가 주어집니다. myString의 "A"를 "B"로, …

[66일차] 김리연 / x 사이의 개수 외 6개

---

1st/Jihyun/Programmers/RepresentationOfNumbers.java

| 숫자의 표현 | 프로그래머스 | Level.2 |
<hr/>
- 숫자의 표현 : 자연수 n이 매개변수로 주어질 때, 연속된 자연수들로 n을 표현하는 방법의 수를 return하는 solution 작성

[66일차] 김지현 / 숫자의 표현

---

1st/Hyeseung/Programmers/조건별로 분류하여 주문상태 출력하기.sql

| 조건별로 분류하여 주문상태 출력하기 | 프로그래머스 | Level.3 |
<hr/>
- 조건별로 분류하여 주문상태 출력하기 : FOOD_ORDER 테이블에서 5월 1일을 기준으로 주문 ID, 제품 ID, 출고일자, 출고여부를 조회하는 SQL문을 작성해주세요. 출고여부는 5월 1일까지 출고완료로 이 후 날짜는 출고 대기로 미정이면 출고미정으로 출력해주시고, 결과는 주문 ID를 기준으로 오름차순 정렬해주세요.

[66일차] 김혜승 / 조건별로 분류하여 주문상태 출력하기

---

1st/Jiin/BiggestFish.sql

| [잡은 물고기 중 가장 큰 물고기의 길이 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/298515) | 프로그래머스 | Level.1 |
<hr/>
- 잡은 물고기 중 가장 큰 물고기의 길이 구하기 : 잡은 물고기중 가장 길이가 긴 물고기의 Length 뒤에 cm를 붙이고 열 이름을 `MAX_LENGTH`로 바꿔서 출력하시오

[66일차] 이지인 / 잡은 물고기 중 가장 큰 물고기의 길이 구하기

---

1st/Jinseon/키패드 만들기

https://school.programmers.co.kr/learn/courses/30/lessons/67256
| 키패드 만들기 | 프로그래머스 | Level.1 |
<hr/>
- 키패드 만들기 : *과 #, 0을 각각 11, 13, 12로 설정하고 Math.abs()를 사용

[66일차] 이진선 / 키패드 만들기

---

1st/Sunhee/programmers/두 수의 차.java

https://school.programmers.co.kr/learn/courses/30/lessons/120803?language=java
| 두 수의 차 | 프로그래머스 | Level.0 |
<hr/>
- 정수 num1과 num2가 주어질 때, num1에서 num2를 뺀 값을 return하도록 soltuion 함수를 완성해주세요.

[66일차] 김선희 / 두 수의 차 

---

1st/Hyeseung/Programmers/보호소에서 중성화한 동물.sql

| 보호소에서 중성화한 동물 | 프로그래머스 | Level.4 |
<hr/>
- 보호소에서 중성화한 동물 : 보호소에서 중성화 수술을 거친 동물 정보를 알아보려 합니다. 보호소에 들어올 당시에는 중성화[1](https://school.programmers.co.kr/learn/courses/30/lessons/59045#fn1)되지 않았지만, 보호소를 나갈 당시에는 중성화된 동물의 아이디와 생물 종, 이름을 조회하는 아이디 순으로 조회하는 SQL 문을 작성해주세요.

[67일차] 김혜승 / 보호소에서 중성화한 동물

---

1st/Jinseon/a와b출력하기.py
1st/Jinseon/flag에따라다른값반환하기.py
1st/Jinseon/간단한식계산하기.py
1st/Jinseon/글자지우기.py
1st/Jinseon/대소문자바꾸기.py
1st/Jinseon/덧셈식출력하기.py
1st/Jinseon/문자열겹쳐쓰기.py
1st/Jinseon/문자열붙이기.py
1st/Jinseon/문자열잘라서정렬하기.py
1st/Jinseon/홀짝구분하기.py

| 대소문자 바꿔서 출력하기 | 프로그래머스 | Level.0 |
| 덧셈식 출력하기 | 프로그래머스 | Level.0 |
| 글자 지우기 | 프로그래머스 | Level.0 |
| 문자열 잘라서 정렬하기 | 프로그래머스 | Level.0 |
| 문자열 여러 번 뒤집기 | 프로그래머스 | Level.0 |
| 문자열 겹쳐쓰기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 붙여서 출력하기 : str1, str2 = input().split(' ')
- 대소문자 바꿔서 출력하기 : if i.isupper() == True:
- a와 b 출력하기 : print('a =', a)
- 덧셈식 출력하기 : print(a, '+', b, '=', a+b)
- 글자 지우기 : if i not in indices:
- 간단한 식 계산하기 : str1, op, str2 = binomial.split(" ")
- 문자열 잘라서 정렬하기 : answer = list(filter(None, myString.split("x")))
- flag에 따라 다른 값 반환하기 : if flag:
- 문자열 여러 번 뒤집기
for start, end in queries:
answer = …

[67일차] 이진선 / 문자열 붙여서 출력하기 외 9개

---

2st/Riyeon/뒤에서 5등까지.java
2st/Riyeon/무작위로 K개의 수 뽑기.java
2st/Riyeon/문자열 묶기.java
2st/Riyeon/배열 만들기 6.java
2st/Riyeon/배열 비교하기.java
2st/Riyeon/배열의 길이를 2의 거듭제곱으로 만들기.java
2st/Riyeon/배열의 길이에 따라 다른 연산하기.java
2st/Riyeon/빈 배열에 추가, 삭제하기.java

| 빈 배열에 추가, 삭제하기 | 프로그래머스 | Level.0 |
| 배열 만들기 6 | 프로그래머스 | Level.0 |
| 무작위로 K개의 수 뽑기 | 프로그래머스 | Level.0 |
| 배열의 길이를 2의 거듭제곱으로 만들기 | 프로그래머스 | Level.0 |
| 배열 비교하기 | 프로그래머스 | Level.0 |
| 문자열 묶기 | 프로그래머스 | Level.0 |
| 배열의 길이에 따라 다른 연산하기 | 프로그래머스 | Level.0 |
<hr/>
- 빈 배열에 추가, 삭제하기 : 아무 원소도 들어있지 않은 빈 배열 X가 있습니다. 길이가 같은 정수 배열 arr과 boolean 배열 flag가 매개변수로 주어질 때, flag를 차례대로 순회하며 flag[i]가 true라면 X의 뒤에 arr[i]를 arr[i] × 2 번 추가하고, flag[i]가 false라면 X에서 마지막 arr[i]개의 원소를 제거한 뒤 X를 return 하는 solution 함수를 작성해 주세요.
- 배열 만들기 6 : 0과 1로만 이루어진 정수 배열 arr가 주어집니다. arr를 이용해 새로운 배열 stk을 만드려고 합니다. i의 초기값을 0으로 설정하고 i가 arr의 길이보다 작으면 다음을 반복합니다. 
만약 stk이 빈 배열이라면 arr[i]를 stk에 추가하고 i에 1을 더합니다.
stk에 원소가 있고, stk의 마지막 원소가 arr[i]와 같으면 stk의 마지막 원소를 …

[67일차] 김리연 / 빈 배열에 추가, 삭제하기 외 7개

---

1st/Jiin/LastTwoItems.java

| [마지막 두 원소](https://school.programmers.co.kr/learn/courses/30/lessons/181927) |  프로그래머스 | Level.0 |
<hr/>

[67일차] 이지인 / 마지막 두 원소

---

1st/Hyeseung/Programmers/대여 기록이 존재하는 자동차 리스트 구하기.sql

| 대여 기록이 존재하는 자동차 리스트 구하기 | 프로그래머스 | Level.3 |
<hr/>
- 대여 기록이 존재하는 자동차 리스트 구하기 : CAR_RENTAL_COMPANY_CAR 테이블과 CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블에서 자동차 종류가 '세단'인 자동차들 중 10월에 대여를 시작한 기록이 있는 자동차 ID 리스트를 출력하는 SQL문을 작성해주세요. 자동차 ID 리스트는 중복이 없어야 하며, 자동차 ID를 기준으로 내림차순 정렬해주세요.

[68일차] 김혜승 / 대여 기록이 존재하는 자동차 리스트 구하기

---

2st/Riyeon/l로 만들기.java
2st/Riyeon/두 수의 합.java
2st/Riyeon/뒤에서 5등 위로.java
2st/Riyeon/문자열로 변환.java
2st/Riyeon/문자열을 정수로 변환하기.java
2st/Riyeon/배열의 원소 삭제하기.java
2st/Riyeon/전국 대회 선발 고사.java

| 뒤에서 5등 위로 | 프로그래머스 | Level.0 |
| 전국 대회 선발 고사 | 프로그래머스 | Level.0 |
| 두 수의 합 | 프로그래머스 | Level.0 |
| 문자열로 변환 | 프로그래머스 | Level.0 |
| 배열의 원소 삭제하기 | 프로그래머스 | Level.0 |
| l로 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 뒤에서 5등 위로 : 정수로 이루어진 리스트 num_list가 주어집니다. num_list에서 가장 작은 5개의 수를 제외한 수들을 오름차순으로 담은 리스트를 return하도록 solution 함수를 완성해주세요.
- 전국 대회 선발 고사 : 0번부터 n - 1번까지 n명의 학생 중 3명을 선발하는 전국 대회 선발 고사를 보았습니다. 등수가 높은 3명을 선발해야 하지만, 개인 사정으로 전국 대회에 참여하지 못하는 학생들이 있어 참여가 가능한 학생 중 등수가 높은 3명을 선발하기로 했습니다. 각 학생들의 선발 고사 등수를 담은 정수 배열 rank와 전국 대회 참여 가능 여부가 담긴 boolean 배열 attendance가 매개변수로 주어집니다. 전국 대회에 선발된 학생 번호들을 등수가 높은 순서대로 각각 a, b, c번이라고 할 때 10000 × a + 100 × b + c를 return 하는 solution 함수를 작성해 주세요.
- 문자열을 정수로 변환하기 : 숫자로만 이루어진 문자열 n_str이 주어질 …

[68일차] 김리연 / 뒤에서 5등 위로 외 6개

---

1st/Jiin/AddingSpecificItemsOfArithmeticSequence.java
1st/Jiin/JoinTogetherNumber.c
1st/Jiin/ModifiedNumber.java
1st/Jiin/Multiplecation_and_sum_of_elements.c
1st/Jiin/PlayingDice.java

| 등차수열의 특정한 항만 더하기 | 프로그래머스 | Level.0 |
| 주사위 게임 2 | 프로그래머스 | Level.0 |
| 이어붙인 수 | 프로그래머스 | Level.0 |
| 수 조작하기 | 프로그래머스 | Level.0 |
<hr/>
- 등차수열의 특정한 항만 더하기 : 두 정수 a, d와 길이가 n인 boolean 배열 included가 주어집니다. 첫째항이 a, 공차가 d인 등차수열에서 included[i]가 i + 1항을 의미할 때, 이 등차수열의 1항부터 n항까지 included가 true인 항들만 더한 값을 return 하는 solution 함수를 작성해 주세요.
- 주사위 게임 2 : 1부터 6까지 숫자가 적힌 주사위가 세 개 있습니다. 세 주사위를 굴렸을 때 나온 숫자를 각각 a, b, c라고 했을 때 얻는 점수는 다음과 같습니다.
세 숫자가 모두 다르다면 a + b + c 점을 얻습니다.
세 숫자 중 어느 두 숫자는 같고 나머지 다른 숫자는 다르다면 (a + b + c) × (a2 + b2 + c2 )점을 얻습니다.
세 숫자가 모두 같다면 (a + b + c) × (a2 + b2 + c2 ) × (a3 + b3 + c3 )점을 얻습니다.
세 정수 a, b, c가 매개변수로 주어질 때, 얻는 점수를 return 하는 solution 함수를 작성해 주세요.
- 원소들의 곱과 합 : 정수가 담긴 리스트 num_list가 주어질 때, 모든 원소들의 …

[68일차] 이지인 / 등차수열의 특정한 항만 더하기 외 4개

---

1st/Jihyun/Programmers/TemplarWeapon.java

| 기사단원의 무기 | 프로그래머스 | Level.1 |
<hr/>
- 기사단원의 무기 : 기사단원의 수를 나타내는 정수 number와 이웃나라와 협약으로 정해진 공격력의 제한수치를 나타내는 정수 limit와 제한수치를 초과한 기사가 사용할 무기의 공격력을 나타내는 정수 power가 주어졌을 때, 무기점의 주인이 무기를 모두 만들기 위해 필요한 철의 무게를 return 하는 solution 함수 작성

[68일차] 김지현 / 기사단원의 무기

---

1st/Hyeseung/Programmers/5월 식품들의 총매출 조회하기.sql

| 5월 식품들의 총매출 조회하기 | 프로그래머스 | Level.4 |
<hr/>
- 5월 식품들의 총매출 조회하기 : FOOD_PRODUCT와 FOOD_ORDER 테이블에서 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회하는 SQL문을 작성해주세요. 이때 결과는 총매출을 기준으로 내림차순 정렬해주시고 총매출이 같다면 식품 ID를 기준으로 오름차순 정렬해주세요.

[69일차] 김혜승 / 5월 식품들의 총매출 조회하기

---

1st/Jiin/FoundPrimeNumberInKBase.java

| k진수에서 소수 개수 구하기 | 프로그래머스 | Level.2 |
<hr/>
- k진수에서 소수 개수 구하기 : n을 k진수로 변환한 숫자에 0으로 분리시킨 후 10진수 기준 소수인 수들의 개수를 구하시오.

[69일차] 이지인 / k진수에서 소수 개수 구하기

---

1st/Jinseon/9로나눈나머지.py

| 9로 나눈 나머지 | 프로그래머스 | Level.0 |
<hr/>
- 9로 나눈 나머지 : %연산자 사용, 형변환 사용

[69일차] 이진선 / 9로 나눈 나머지

---

2st/Riyeon/그림 확대.java
2st/Riyeon/날짜 비교하기.java
2st/Riyeon/커피 심부름.java
2st/Riyeon/특별한 이차원 배열 1.java
2st/Riyeon/특별한 이차원 배열 2.java

| 날짜 비교하기 | 프로그래머스 | Level.0 |
| 커피 심부름 | 프로그래머스 | Level.0 |
| 그림 확대 | 프로그래머스 | Level.0 |
| 특별한 이차원 배열 1 | 프로그래머스 | Level.0 |
| 특별한 이차원 배열 2 | 프로그래머스 | Level.0 |
<hr/>
- 날짜 비교하기 : 정수 배열 date1과 date2가 주어집니다. 두 배열은 각각 날짜를 나타내며 [year, month, day] 꼴로 주어집니다. 각 배열에서 year는 연도를, month는 월을, day는 날짜를 나타냅니다. 만약 date1이 date2보다 앞서는 날짜라면 1을, 아니면 0을 return 하는 solution 함수를 완성해 주세요.
- 커피 심부름 : 팀의 막내인 철수는 아메리카노와 카페 라테만 판매하는 카페에서 팀원들의 커피를 사려고 합니다. 아메리카노와 카페 라테의 가격은 차가운 것과 뜨거운 것 상관없이 각각 4500, 5000원입니다. 각 팀원에게 마실 메뉴를 적어달라고 하였고, 그 중에서 메뉴만 적은 팀원의 것은 차가운 것으로 통일하고 "아무거나"를 적은 팀원의 것은 차가운 아메리카노로 통일하기로 하였습니다. 각 직원이 적은 메뉴가 문자열 배열 order로 주어질 때, 카페에서 결제하게 될 금액을 return 하는 solution 함수를 작성해주세요. order의 원소는 아래의 것들만 들어오고, 각각의 의미는 다음과 같습니다.
- 그림 확대 : 직사각형 형태의 그림 파일이 있고, 이 그림 파일은 1 …

[69일차] 김리연 / 날짜 비교하기 외 4개

---

1st/Jihyun/Programmers/FivePeopleEach.java

<hr/>
- 5명씩 : 사람들의 이름이 담긴 문자열 리스트 names가 주어질 때, 앞에서 부터 5명씩 묶은 그룹의 가장 앞에 서있는 사람들의 이름을 담은 리스트를 return하도록 solution 함수 작성

[69일차] 김지현 / 5명씩

---

1st/Sunhee/programmers/괄호 회전하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/76502
| 괄호 회전하기 | 프로그래머스 | Level.2 |
<hr/>
- 다음 규칙을 지키는 문자열을 올바른 괄호 문자열이라고 정의합니다.
(), [], {} 는 모두 올바른 괄호 문자열입니다.
만약 A가 올바른 괄호 문자열이라면, (A), [A], {A} 도 올바른 괄호 문자열입니다. 예를 들어, [] 가 올바른 괄호 문자열이므로, ([]) 도 올바른 괄호 문자열입니다.
만약 A, B가 올바른 괄호 문자열이라면, AB 도 올바른 괄호 문자열입니다. 예를 들어, {} 와 ([]) 가 올바른 괄호 문자열이므로, {}([]) 도 올바른 괄호 문자열입니다.
대괄호, 중괄호, 그리고 소괄호로 이루어진 문자열 s가 매개변수로 주어집니다. 이 s를 왼쪽으로 x (0 ≤ x < (s의 길이)) 칸만큼 회전시켰을 때 s가 올바른 괄호 문자열이 되게 하는 x의 개수를 return 하도록 solution 함수를 완성해주세요.

[70일차] 김선희 / 괄호 회전하기

---

1st/Jihyun/Programmers/CorrectParentheses.java

| 올바른 괄호 | 프로그래머스 | Level.1 |
<hr/>
- 올바른 괄호 : '(' 또는 ')' 로만 이루어진 문자열 s가 주어졌을 때, 문자열 s가 올바른 괄호이면 true를 return 하고, 올바르지 않은 괄호이면 false를 return 하는 solution 함수 작성

[70일차] 김지현 / 올바른 괄호

---

1st/Jiin/DivideString.js

| [문자열 나누기](https://school.programmers.co.kr/learn/courses/30/lessons/140108?language=javascript) | 프로그래머스 | Level.1 |
<hr/>
- 문자열 나누기 : 문자열 s가 입력되었을 때 다음 규칙을 따라서 이 문자열을 여러 문자열로 분해하려고 합니다.
먼저 첫 글자를 읽습니다. 이 글자를 x라고 합시다.
이제 이 문자열을 왼쪽에서 오른쪽으로 읽어나가면서, x와 x가 아닌 다른 글자들이 나온 횟수를 각각 셉니다. 처음으로 두 횟수가 같아지는 순간 멈추고, 지금까지 읽은 문자열을 분리합니다.
s에서 분리한 문자열을 빼고 남은 부분에 대해서 이 과정을 반복합니다. 남은 부분이 없다면 종료합니다.
만약 두 횟수가 다른 상태에서 더 이상 읽을 글자가 없다면, 역시 지금까지 읽은 문자열을 분리하고, 종료합니다.
문자열 s가 매개변수로 주어질 때, 위 과정과 같이 문자열들로 분해하고, 분해한 문자열의 개수를 return 하는 함수 solution을 완성하세요.

[70일차] 이지인 / 문자열 나누기

---

1st/Jinseon/A강조하기.py
1st/Jinseon/간단한논리연산.py
1st/Jinseon/배열만들기1.py
1st/Jinseon/소문자로만들기.py
1st/Jinseon/특정한문자를대문자로바꾸기.py

| 간단한 논리 | 프로그래머스 | Level.0 |
| 특정한 문자 대문자로 바꾸기 | 프로그래머스 | Level.0 |
<hr/>
- 간단한 논리 : boolean 변수 x1, x2, x3, x4가 매개변수로 주어질 때, 다음의 식의 true/false를 return 하는 solution 함수를 작성해 주세요.
- 특정한 문자를 대문자로 바꾸기 : 영소문자로 이루어진 문자열 my_string과 영소문자 1글자로 이루어진 문자열 alp가 매개변수로 주어질 때, my_string에서 alp에 해당하는 모든 글자를 대문자로 바꾼 문자열을 return 하는 solution 함수를 …

[70일차] 이진선 / 간단한 논리 외 4개

---

2st/Riyeon/문자열 내 p와 y의 개수.java
2st/Riyeon/문자열을 정수로 바꾸기.java
2st/Riyeon/약수의 합.java
2st/Riyeon/이차원 배열 대각선 순회하기.java
2st/Riyeon/자릿수 더하기.java
2st/Riyeon/정사각형으로 만들기.java
2st/Riyeon/정수를 나선형으로 배치하기.java
2st/Riyeon/짝수와 홀수.java

| 이차원 배열 대각선 순회하기 | 프로그래머스 | Level.0 |
| 정사각형으로 만들기 | 프로그래머스 | Level.0 |
| 정수를 나선형으로 배치하기 | 프로그래머스 | Level.0 |
| 문자열 내 p와 y의 개수 | 프로그래머스 | Level.1 |
| 문자열을 정수로 바꾸기 | 프로그래머스 | Level.1 |
| 약수의 합 | 프로그래머스 | Level.1 |
| 자릿수 더하기 | 프로그래머스 | Level.1 |
| 짝수와 홀수 | 프로그래머스 | Level.1 |
<hr/>
- 이차원 배열 대각선 순회하기 : 2차원 정수 배열 board와 정수 k가 주어집니다. i + j <= k를 만족하는 모든 (i, j)에 대한 board[i][j]의 합을 return 하는 solution 함수를 완성해 주세요.
- 정사각형으로 만들기 : 이차원 정수 배열 arr이 매개변수로 주어집니다. arr의 행의 수가 더 많다면 열의 수가 행의 수와 같아지도록 각 행의 끝에 0을 추가하고, 열의 수가 더 많다면 행의 수가 열의 수와 같아지도록 각 열의 끝에 0을 추가한 이차원 배열을 return 하는 solution 함수를 작성해 주세요.
- 정수를 나선형으로 배치하기 : 양의 정수 n이 매개변수로 주어집니다. n × n 배열에 1부터 n2 까지 정수를 인덱스 [0][0]부터 시계방향 나선형으로 배치한 이차원 배열을 return 하는 solution 함수를 작성해 주세요.
- 문자열 내 p와 y의 개수 : 대문자와 소문자가 …

[70일차] 김리연 / 이차원 배열 대각선 순회하기 외 7개

---

1st/Hyeseung/Programmers/없어진 기록 찾기.sql

| 없어진 기록 찾기 | 프로그래머스 | Level.3 |
<hr/>
- 없어진 기록 찾기  : 천재지변으로 인해 일부 데이터가 유실되었습니다. 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 동물의 ID와 이름을 ID 순으로 조회하는 SQL문을 작성해주세요.

[71일차] 김혜승 / 없어진 기록 찾기 

---

1st/Sunhee/programmers/할인 행사.java

https://school.programmers.co.kr/learn/courses/30/lessons/131127
| 할인 행사 | 프로그래머스 | Level.2 |
<hr/>
- XYZ 마트는 일정한 금액을 지불하면 10일 동안 회원 자격을 부여합니다. XYZ 마트에서는 회원을 대상으로 매일 한 가지 제품을 할인하는 행사를 합니다. 할인하는 제품은 하루에 하나씩만 구매할 수 있습니다. 알뜰한 정현이는 자신이 원하는 제품과 수량이 할인하는 날짜와 10일 연속으로 일치할 경우에 맞춰서 회원가입을 하려 합니다.
예를 들어, 정현이가 원하는 제품이 바나나 3개, 사과 2개, 쌀 2개, 돼지고기 2개, 냄비 1개이며, XYZ 마트에서 14일간 회원을 대상으로 할인하는 제품이 날짜 순서대로 치킨, 사과, 사과, 바나나, 쌀, 사과, 돼지고기, 바나나, 돼지고기, 쌀, 냄비, 바나나, 사과, 바나나인 경우에 대해 알아봅시다. 첫째 날부터 열흘 간에는 냄비가 할인하지 않기 때문에 첫째 날에는 회원가입을 하지 않습니다. 둘째 날부터 열흘 간에는 바나나를 원하는 만큼 할인구매할 수 없기 때문에 둘째 날에도 회원가입을 하지 않습니다. 셋째 날, 넷째 날, 다섯째 날부터 각각 열흘은 원하는 제품과 수량이 일치하기 때문에 셋 중 하루에 회원가입을 하려 합니다.
정현이가 원하는 제품을 나타내는 문자열 배열 want와 정현이가 원하는 제품의 수량을 나타내는 정수 배열 number, XYZ 마트에서 할인하는 제품을 나타내는 문자열 배열 …

[71일차] 김선희 / 할인 행사 

---

1st/Jinseon/가까운1찾기.py
1st/Jinseon/배열에서문자열대소문자변환하기.py

<hr/>
- 가까운 1 찾기 : 정수 배열 arr가 주어집니다. 이때 arr의 원소는 1 또는 0입니다. 정수 idx가 주어졌을 때, idx보다 크면서 배열의 값이 1인 가장 작은 인덱스를 찾아서 반환하는 solution 함수를 완성해 주세요. 단, 만약 그러한 인덱스가 없다면 -1을 반환합니다.

[71일차] 이진선 / 가까운 1 찾기 외 1개

---

1st/Jiin/NotEnoughFee.java

| 부족한 금액 | 프로그래머스 | Level.1 |
<hr/>
- 부족한 금액 : 놀이공원에서 요금이 price인 기구를 탈 때, n번 타면 n배의 요금을 추가로 내야 합니다. 이 때 요금이 price인 놀이기구를 count번 탄다고 가정하면, 현재 돈에서 얼마가 부족한지 반환하시오. 돈이 부족하지 않다면 0을 반환하시오.

[71일차] 이지인 / 부족한 금액

---

2st/Riyeon/나머지가 1이 되는 수 찾기.java
2st/Riyeon/자연수 뒤집어 배열로 만들기.java
2st/Riyeon/정수 내림차순으로 배치하기.java
2st/Riyeon/정수 제곱근 판별.java
2st/Riyeon/평균 구하기.java

| 자연수 뒤집어 배열로 만들기 | 프로그래머스 | Level.1 |
| 정수 내림차순으로 배치하기 | 프로그래머스 | Level.1 |
| 정수 제곱근 판별 | 프로그래머스 | Level.1 |
| 평균 구하기 | 프로그래머스 | Level.1 |
| 나머지가 1이 되는 수 찾기 | 프로그래머스 | Level.1 |
<hr/>
- 자연수 뒤집어 배열로 만들기 : 자연수 n을 뒤집어 각 자리 숫자를 원소로 가지는 배열 형태로 리턴해주세요. 예를들어 n이 12345이면 [5,4,3,2,1]을 리턴합니다.
- 정수 내림차순으로 배치하기 : 함수 solution은 정수 n을 매개변수로 입력받습니다. n의 각 자릿수를 큰것부터 작은 순으로 정렬한 새로운 정수를 리턴해주세요. 예를들어 n이 118372면 873211을 리턴하면 됩니다.
- 정수 제곱근 판별 : 임의의 양의 정수 n에 대해, n이 어떤 양의 정수 x의 제곱인지 아닌지 판단하려 합니다. n이 양의 정수 x의 제곱이라면 x+1의 제곱을 리턴하고, n이 양의 정수 x의 제곱이 아니라면 -1을 리턴하는 함수를 완성하세요.
- 나머지가 1이 되는 수 찾기 : 자연수 n이 매개변수로 주어집니다. n을 x로 나눈 나머지가 1이 되도록 하는 가장 작은 자연수 x를 return 하도록 solution 함수를 완성해주세요. 답이 항상 존재함은 증명될 수 있습니다.

[71일차] 김리연 / 자연수 뒤집어 배열로 만들기 외 4개

---

1st/Hyeseung/Programmers/조건에 맞는 사원 정보 조회하기.sql

| 조건에 맞는 사원 정보 조회하기 | 프로그래머스 | Level.2 |
<hr/>
- 조건에 맞는 사원 정보 조회하기 : HR_DEPARTMENT, HR_EMPLOYEES, HR_GRADE 테이블에서 2022년도 한해 평가 점수가 가장 높은 사원 정보를 조회하려 합니다. 2022년도 평가 점수가 가장 높은 사원들의 점수, 사번, 성명, 직책, 이메일을 조회하는 SQL문을 작성해주세요. 2022년도의 평가 점수는 상,하반기 점수의 합을 의미하고, 평가 점수를 나타내는 컬럼의 이름은 SCORE로 해주세요.

[72일차] 김혜승 / 조건에 맞는 사원 정보 조회하기

---

1st/Sunhee/programmers/H-Index.java

https://school.programmers.co.kr/learn/courses/30/lessons/42747
| H-Index | 프로그래머스 | Level.2 |
<hr/>
- H-Index는 과학자의 생산성과 영향력을 나타내는 지표입니다. 어느 과학자의 H-Index를 나타내는 값인 h를 구하려고 합니다. 위키백과[1](https://school.programmers.co.kr/learn/courses/30/lessons/42747#fn1)에 따르면, H-Index는 다음과 같이 구합니다.
어떤 과학자가 발표한 논문 n편 중, h번 이상 인용된 논문이 h편 이상이고 나머지 논문이 h번 이하 인용되었다면 h의 최댓값이 이 과학자의 H-Index입니다.
어떤 과학자가 발표한 논문의 인용 횟수를 담은 배열 citations가 매개변수로 주어질 때, 이 과학자의 H-Index를 return 하도록 solution 함수를 작성해주세요.

[72일차] 김선희 / H-Index

---

1st/Jiin/ModefiedNumber.java

| 수 조작하기 2 | 프로그래머스 | Level.0 |
<hr/>
- 수 조작하기 2 : 정수 배열 numLog가 주어집니다. 처음에 numLog[0]에서 부터 시작해 "w", "a", "s", "d"로 이루어진 문자열을 입력으로 받아 순서대로 다음과 같은 조작을 했다고 합시다.
"w" : 수에 1을 더한다.
"s" : 수에 1을 뺀다.
"d" : 수에 10을 더한다.
"a" : 수에 10을 뺀다.
그리고 매번 조작을 할 때마다 결괏값을 기록한 정수 배열이 numLog입니다. 즉, numLog[i]는 numLog[0]로부터 총 i번의 조작을 가한 결과가 저장되어 있습니다.
주어진 정수 배열 numLog에 대해 조작을 위해 입력받은 문자열을 return 하는 solution 함수를 완성해 주세요.

[72일차] 이지인 / 수 조작하기 2

---

1st/Jihyun/Programmers/EmphasizeA.java

<hr/>
- A 강조하기 : 문자열 myString이 주어질 때, myString에서 알파벳 "a"는 전부 "A"로 변환하고, "A"가 아닌 모든 대문자 알파벳은 소문자 알파벳으로 변환하여 return 하는 solution 작성

[72일차] 김지현 / A 강조하기

---

1st/Jinseon/리스트자르기.py

https://school.programmers.co.kr/learn/courses/30/lessons/181897
| 리스트 자르기 | 프로그래머스 | Level.0 |
<hr/>
- 리스트 자르기
정수 n과 정수 3개가 담긴 리스트 slicer 그리고 정수 여러 개가 담긴 리스트 num_list가 주어집니다. slicer에 담긴 정수를 차례대로 a, b, c라고 할 때, n에 따라 다음과 같이 num_list를 슬라이싱 하려고 합니다. 올바르게 슬라이싱한 리스트를 return하도록 solution 함수를 완성해주세요.

[72일차] 이진선 / 리스트자르기

---

1st/Hyeseung/Programmers/콜라츠 수열 만들기.sql

[73일차] 김혜승 / 콜라츠 수열 만들기

---

1st/Jinseon/나누어떨어지는숫자배열.py
1st/Jinseon/직사각형별찍기.py

| 나누어 떨어지는 숫자배열 | 프로그래머스 | Level.1 |
| 직사각형 별찍기 | 프로그래머스 | Level.1 |
<hr/>
- 나누어 떨어지는 숫자배열 : array의 각 element 중 divisor로 나누어 떨어지는 값을 오름차순으로 정렬한 배열을 반환하는 함수, solution을 작성해주세요. divisor로 나누어 떨어지는 element가 하나도 없다면 배열에 -1을 담아 반환하세요.
- 직사각형 별찍기 : 이 문제에는 표준 입력으로 두 개의 정수 n과 m이 주어집니다. 별(*) 문자를 이용해 가로의 길이가 n, 세로의 길이가 m인 직사각형 형태를 출력해보세요.

[73일차] 이진선 / 나누어 떨어지는 숫자배열 외 1개

---

1st/Jihyun/Programmers/CorrectParentheses.java
1st/Jihyun/Programmers/CreateStrangeCharacter.java

| 이상한 문자 만들기 | 프로그래머스 | Level.1 |
<hr/>
- 이상한 문자 만들기 : 문자열 s가 주어졌을 때, 각 단어의 짝수번째 알파벳은 대문자로, 홀수번째 알파벳은 소문자로 바꾼 문자열을 리턴하는 함수 solution 작성

[73일차] 김지현 / 이상한 문자 만들기

---

2st/Riyeon/x만큼 간격이 있는 n개의 숫자.java
2st/Riyeon/가운데 글자 가져오기.java
2st/Riyeon/같은 숫자는 싫어.java
2st/Riyeon/내적.java
2st/Riyeon/두 정수 사이의 합.java
2st/Riyeon/문자열 내림차순으로 배치하기.java
2st/Riyeon/문자열 다루기 기본.java
2st/Riyeon/부족한 금액 계산하기.java
2st/Riyeon/서울에서 김서방 찾기.java
2st/Riyeon/수박수박수박수박수박수.java
2st/Riyeon/약수의 개수와 덧셈.java
2st/Riyeon/최대공약수와 최소공배수.java
2st/Riyeon/하샤드 수.java
2st/Riyeon/행렬의 덧셈.java

| 가운데 글자 가져오기 | 프로그래머스 | Level.1 |
| 수박수박수박수박수박수? | 프로그래머스 | Level.1 |
| 내적 | 프로그래머스 | Level.1 |
| 약수의 개수와 덧셈 | 프로그래머스 | Level.1 |
| 문자열 내림차순으로 배치하기 | 프로그래머스 | Level.1 |
| 부족한 금액 계산하기 | 프로그래머스 | Level.1 |
| 문자열 다루기 기본 | 프로그래머스 | Level.1 |
| 행렬의 덧셈 | 프로그래머스 | Level.1 |
| 최대공약수와 최소공배수 | 프로그래머스 | Level.1 |
| 같은 숫자는 싫어 | 프로그래머스 | Level.1 |
<hr/>
- 가운데 글자 가져오기 : 단어 s의 가운데 글자를 반환하는 함수, solution을 만들어 보세요. 단어의 길이가 짝수라면 가운데 두글자를 반환하면 됩니다.
- 수박수박수박수박수박수? : 길이가 n이고, "수박수박수박수...."와 같은 패턴을 유지하는 문자열을 리턴하는 함수, solution을 완성하세요. 예를들어 n이 4이면 "수박수박"을 리턴하고 3이라면 "수박수"를 리턴하면 됩니다.
- 내적 : 길이가 같은 두 1차원 정수 배열 a, b가 매개변수로 주어집니다. a와 b의 [내적]을 return 하도록 solution 함수를 완성해주세요. 이때, a와 b의 내적은 a[0]*b[0] + a[1]*b[1] + ... + a[n-1]*b[n-1] 입니다. (n은 a, b의 길이)
- 약수의 개수와 덧셈 : 두 정수 …

[73일차] 김리연 / 가운데 글자 가져오기 외 9개

---

1st/Jiin/Search1.java

<hr/>
- 가까운 1 찾기 : 원소가 0, 1로만 이루어진 정수 배열과 idx가 주어진다. 인덱스 idx보다 크면서 값이 1인 가장 작은 인덱스를 반환하시오. 만약 없다면 -1을 반환하시오.

[73일차] 이지인 / 가까운 1 찾기

---

1st/Hyeseung/Programmers/부서별 평균 연봉 조회하기.sql

| 부서별 평균 연봉 조회하기 | 프로그래머스 | Level.3 |
<hr/>
- 부서별 평균 연봉 조회하기 : HR_DEPARTMENT와 HR_EMPLOYEES 테이블을 이용해 부서별 평균 연봉을 조회하려 합니다. 부서별로 부서 ID, 영문 부서명, 평균 연봉을 조회하는 SQL문을 작성해주세요. 평균연봉은 소수점 첫째 자리에서 반올림하고 컬럼명은 AVG_SAL로 해주세요. 결과는 부서별 평균 연봉을 기준으로 내림차순 정렬해주세요.

[74일차] 김혜승 / 부서별 평균 연봉 조회하기

---

1st/Jinseon/더크게합치기.py
1st/Jinseon/마지막두원소.py

| 더 크게 합치기 | 프로그래머스 | Level.1 |
| 마지막 두 원소 | 프로그래머스 | Level.0 |
<hr/>
- 더 크게 합치기 : 양의 정수 a와 b가 주어졌을 때, a ⊕ b와 b ⊕ a 중 더 큰 값을 return 하는 solution 함수를 완성해 주세요.

[74일차] 이진선 / 더 크게 합치기 외 1개

---

1st/Jiin/CompletionPlayer.java

| 완주하지 못한 선수 | 프로그래머스 | Level.1 |
<hr/>
- 완주하지 못한 선수 : 경기에 참가한 선수와 결승전을 지난 선수의 이름이 있는 문자열 배열 2개가 주어집니다. 아직 결승전을 지나지 못한 한 선수의 이름을 문자열로 반환하세요. 선수들의 이름 중 동명이인이 있을 수 있습니다

[74일차] 이지인 / 완주하지 못한 선수

---

1st/Sunhee/programmers/N개의 최소공배수.java
1st/Sunhee/programmers/귤 고르기.java
1st/Sunhee/programmers/점프와 순간 이동.java

https://school.programmers.co.kr/learn/courses/30/lessons/12949
| 행렬의 곱셈 | 프로그래머스 | Level.2 |
<hr/>
- 2차원 행렬 arr1과 arr2를 입력받아, arr1에 arr2를 곱한 결과를 반환하는 함수, solution을 완성해주세요.

[74일차] 김선희 / 행렬의 곱셈 

---

1st/Jihyun/Programmers/ConvertStringCaseInArray.java

| 배열에서 문자열 대문자 소문자 변환하기 | 프로그래머스 | Level.0 |
<hr/>
- 배열에서 문자열 대문자 소문자 변환하기 : 문자열 배열 strArr가 주어질 때, 모든 원소가 알파벳으로만 이루어져 있을 때, 배열에서 홀수번째 인덱스의 문자열은 모든 문자를 대문자로, 짝수번째 인덱스의 문자열은 모든 문자를 소문자로 바꿔서 반환하는 solution 함수 작성

[74일차] 김지현 / 배열에서 문자열 대문자 소문자 변환하기

---

2st/Riyeon/3진법 뒤집기.java
2st/Riyeon/삼총사.java
2st/Riyeon/예산.java
2st/Riyeon/이상한 문자 만들기.java
2st/Riyeon/최소직사각형.java
2st/Riyeon/크기가 작은 부분문자열.java

| 3진법 뒤집기 | 프로그래머스 | Level.1 |
| 크기가 작은 부분문자열 | 프로그래머스 | Level.1 |
| 예산 | 프로그래머스 | Level.1 |
| 이상한 문자 만들기 | 프로그래머스 | Level.1 |
| 삼총사 | 프로그래머스 | Level.1 |
| 최소직사각형 | 프로그래머스 | Level.1 |
<hr/>
- 3진법 뒤집기 : 자연수 n이 매개변수로 주어집니다. n을 3진법 상에서 앞뒤로 뒤집은 후, 이를 다시 10진법으로 표현한 수를 return 하도록 solution 함수를 완성해주세요.
- 크기가 작은 부분문자열 : 숫자로 이루어진 문자열 t와 p가 주어질 때, t에서 p와 길이가 같은 부분문자열 중에서, 이 부분문자열이 나타내는 수가 p가 나타내는 수보다 작거나 같은 것이 나오는 횟수를 return하는 함수 solution을 완성하세요. 예를 들어, t="3141592"이고 p="271" 인 경우, t의 길이가 3인 부분 문자열은 314, 141, 415, 159, 592입니다. 이 문자열이 나타내는 수 중 271보다 작거나 같은 수는 141, 159 2개 입니다.
- 예산 : S사에서는 각 부서에 필요한 물품을 지원해 주기 위해 부서별로 물품을 구매하는데 필요한 금액을 조사했습니다. 그러나, 전체 예산이 정해져 있기 때문에 모든 부서의 물품을 구매해 줄 수는 없습니다. 그래서 최대한 많은 부서의 물품을 구매해 줄 수 있도록 하려고 합니다. 물품을 구매해 줄 때는 각 부서가 신청한 …

[74일차] 김리연 / 3진법 뒤집기 외 5개

---

1st/Jiin/IHateTheSameNumber.java

| 같은 숫자는 싫어 | 프로그래머스 | Level.1 |
<hr/>
- 같은 숫자는 싫어 : 0~9까지의 수중 중복된 값은 하나로만 적은 배열을 반환하시오.
**EX>**  [1, 1, 3, 3, 0, 1, 1] 이면 [1, 3, 0, 1] 을 return

[75일차] 이지인 / 같은 숫자는 싫어

---

1st/Jinseon/음양더하기.py

https://school.programmers.co.kr/learn/courses/30/lessons/76501
| 음양 더하기  | 프로그래머스 | Level.0 |
<hr/>
- 음양 더하기 : 어떤 정수들이 있습니다. 이 정수들의 절댓값을 차례대로 담은 정수 배열 absolutes와 이 정수들의 부호를 차례대로 담은 불리언 배열 signs가 매개변수로 주어집니다. 실제 정수들의 합을 구하여 return 하도록 solution 함수를 완성해주세요.

[75일차] 이진선 / 음양더하기

---

1st/Jihyun/Programmers/ClosestSameLetter.java

| 가장 가까운 같은 글자 | 프로그래머스 | Level.1 |
<hr/>
- 가장 가까운 같은 글자 : 문자열 s가 주어질 때, s의 각 위치마다 자신보다 앞에 나왔으면서, 자신과 가장 가까운 곳에 있는 같은 글자의 인덱스를 담은 배열을 return하는 solution 작성

[75일차] 김지현 / 가장 가까운 같은 글자

---

1st/PlusNegativePositive.java

| 음양 더하기 | 프로그래머스 | Level.1 |
<hr/>
- 음양 더하기 : 어떤 정수들이 있습니다. 이 정수들의 절댓값을 차례대로 담은 정수 배열 absolutes와 이 정수들의 부호를 차례대로 담은 불리언 배열 signs가 매개변수로 주어집니다. 실제 정수들의 합을 구하여 return 하도록 solution 함수를 완성해주세요.

[76일차] 이지인 / 음양 더하기

---

2st/Riyeon/K번째수.java
2st/Riyeon/명예의 전당 (1).java
2st/Riyeon/푸드 파이트 대회.java

| 소수 찾기 | 프로그래머스 | Level.1 |
| 문자열 내 마음대로 정렬하기 | 프로그래머스 | Level.1 |
| 비밀지도 | 프로그래머스 | Level.1 |
| K번째수 | 프로그래머스 | Level.1 |
| 푸드 파이트 대회 | 프로그래머스 | Level.1 |
| 명예의 전당 (1) | 프로그래머스 | Level.1 |
<hr/>
- 소수 찾기 : 1부터 입력받은 숫자 n 사이에 있는 소수의 개수를 반환하는 함수, solution을 만들어 보세요. 소수는 1과 자기 자신으로만 나누어지는 수를 의미합니다. (1은 소수가 아닙니다.)
- 문자열 내 마음대로 정렬하기 : 문자열로 구성된 리스트 strings와, 정수 n이 주어졌을 때, 각 문자열의 인덱스 n번째 글자를 기준으로 오름차순 정렬하려 합니다. 예를 들어 strings가 ["sun", "bed", "car"]이고 n이 1이면 각 단어의 인덱스 1의 문자 "u", "e", "a"로 strings를 정렬합니다.
- 비밀지도 : 네오는 평소 프로도가 비상금을 숨겨놓는 장소를 알려줄 비밀지도를 손에 넣었다. 그런데 이 비밀지도는 숫자로 암호화되어 있어 위치를 확인하기 위해서는 암호를 해독해야 한다. 다행히 지도 암호를 해독할 방법을 적어놓은 메모도 함께 발견했다. 지도는 한 변의 길이가 n인 정사각형 배열 형태로, 각 칸은 "공백"(" ") 또는 "벽"("#") 두 종류로 이루어져 있다. 전체 지도는 두 장의 지도를 겹쳐서 얻을 수 있다. 각각 "지도 1"과 …

[76일차] 김리연 / 소수 찾기 외 5개

---

1st/Sunhee/programmers/의상.java
1st/Sunhee/programmers/행렬의 곱셈.java

https://school.programmers.co.kr/learn/courses/30/lessons/42586
| 기능개발 |  프로그래머스 | Level.2 |
<hr/>
- 프로그래머스 팀에서는 기능 개선 작업을 수행 중입니다. 각 기능은 진도가 100%일 때 서비스에 반영할 수 있습니다.
또, 각 기능의 개발속도는 모두 다르기 때문에 뒤에 있는 기능이 앞에 있는 기능보다 먼저 개발될 수 있고, 이때 뒤에 있는 기능은 앞에 있는 기능이 배포될 때 함께 배포됩니다.
먼저 배포되어야 하는 순서대로 작업의 진도가 적힌 정수 배열 progresses와 각 작업의 개발 속도가 적힌 정수 배열 speeds가 주어질 때 각 배포마다 몇 개의 기능이 배포되는지를 return 하도록 solution 함수를 완성하세요.

[76일차] 김선희 / 기능개발 

---

1st/Jihyun/Programmers/IsTheLoginSuccessful.java

| 로그인 성공? | 프로그래머스 | Level.0 |
<hr/>
- 로그인 성공? : 입력한 아이디와 패스워드가 담긴 배열 `id_pw`와 회원들의 정보가 담긴 2차원 배열 `db`가 주어질 때, 로그인 성공, 실패에 따른 메시지를 return하도록 solution 함수 작성

[76일차] 김지현 / 로그인 성공?

---

1st/Sunhee/programmers/기능개발.java

https://school.programmers.co.kr/learn/courses/30/lessons/87946
| 피로도 | 백프로그래머스 | Level.2 |
<hr/>
- XX게임에는 피로도 시스템(0 이상의 정수로 표현합니다)이 있으며, 일정 피로도를 사용해서 던전을 탐험할 수 있습니다. 이때, 각 던전마다 탐험을 시작하기 위해 필요한 "최소 필요 피로도"와 던전 탐험을 마쳤을 때 소모되는 "소모 피로도"가 있습니다. "최소 필요 피로도"는 해당 던전을 탐험하기 위해 가지고 있어야 하는 최소한의 피로도를 나타내며, "소모 피로도"는 던전을 탐험한 후 소모되는 피로도를 나타냅니다. 예를 들어 "최소 필요 피로도"가 80, "소모 피로도"가 20인 던전을 탐험하기 위해서는 유저의 현재 남은 피로도는 80 이상 이어야 하며, 던전을 탐험한 후에는 피로도 20이 소모됩니다.
이 게임에는 하루에 한 번씩 탐험할 수 있는 던전이 여러개 있는데, 한 유저가 오늘 이 던전들을 최대한 많이 탐험하려 합니다. 유저의 현재 피로도 k와 각 던전별 "최소 필요 피로도", "소모 피로도"가 담긴 2차원 배열 dungeons 가 매개변수로 주어질 때, 유저가 탐험할수 있는 최대 던전 수를 return 하도록 solution 함수를 완성해주세요.

[77일차] 김선희 / 피로도 

---

1st/Jihyun/Programmers/EnlargeThePicture.java

| 그림 확대 | 프로그래머스 | Level.0 |
<hr/>
- 그림 확대 : 정사각형 크기의 픽셀로 이루어진 그림 파일을 나타낸 문자열 배열 picture과 정수 k가 매개변수로 주어질 때, k배 늘린 그림 파일을 나타내도록 문자열 배열을 return 하는 solution 함수 작성

[77일차] 김지현 / 그림 확대

---

2st/Riyeon/2016년.java
2st/Riyeon/기사단원의 무기.java
2st/Riyeon/옹알이 (2).java
2st/Riyeon/추억 점수.java
2st/Riyeon/카드 뭉치.java
2st/Riyeon/폰켓몬.java

| 추억 점수 | 프로그래머스 | Level.1 |
| 카드 뭉치 | 프로그래머스 | Level.1 |
| 폰켓몬 | 프로그래머스 | Level.1 |
| 2016년 | 프로그래머스 | Level.1 |
| 기사단원의 무기 | 프로그래머스 | Level.1 |
| 옹알이 (2) | 프로그래머스 | Level.1 |
<hr/>
- 추억 점수 : 그리워하는 사람의 이름을 담은 문자열 배열 name, 각 사람별 그리움 점수를 담은 정수 배열 yearning, 각 사진에 찍힌 인물의 이름을 담은 이차원 문자열 배열 photo가 매개변수로 주어질 때, 사진들의 추억 점수를 photo에 주어진 순서대로 배열에 담아 return하는 solution 함수를 완성해주세요.
- 카드 뭉치 : 문자열로 이루어진 배열 cards1, cards2와 원하는 단어 배열 goal이 매개변수로 주어질 때, cards1과 cards2에 적힌 단어들로 goal를 만들 있다면 "Yes"를, 만들 수 없다면 "No"를 return하는 solution 함수를 완성해주세요.
- 폰켓몬 : 당신은 최대한 다양한 종류의 폰켓몬을 가지길 원하기 때문에, 최대한 많은 종류의 폰켓몬을 포함해서 N/2마리를 선택하려 합니다. N마리 폰켓몬의 종류 번호가 담긴 배열 nums가 매개변수로 주어질 때, N/2마리의 폰켓몬을 선택하는 방법 중, 가장 많은 종류의 폰켓몬을 선택하는 방법을 찾아, 그때의 폰켓몬 종류 번호의 개수를 return 하도록 solution 함수를 완성해주세요. …

[77일차] 김리연 / 추억 점수 외 5개

---

2st/Riyeon/과일 장수.java
2st/Riyeon/덧칠하기.java
2st/Riyeon/모의고사.java
2st/Riyeon/문자열 나누기.java

| 모의고사 | 프로그래머스 | Level.1 |
| 과일 장수 | 프로그래머스 | Level.1 |
| 덧칠하기 | 프로그래머스 | Level.1 |
| 문자열 나누기 | 프로그래머스 | Level.1 |
<hr/>
- 모의고사 : 1번 문제부터 마지막 문제까지의 정답이 순서대로 들은 배열 answers가 주어졌을 때, 가장 많은 문제를 맞힌 사람이 누구인지 배열에 담아 return 하도록 solution 함수를 작성해주세요.
- 과일 장수 : 사과의 최대 점수 k, 한 상자에 들어가는 사과의 수 m, 사과들의 점수 score가 주어졌을 때, 과일 장수가 얻을 수 있는 최대 이익을 return하는 solution 함수를 완성해주세요.
- 덧칠하기 : 정수 n, m과 다시 페인트를 칠하기로 정한 구역들의 번호가 담긴 정수 배열 section이 매개변수로 주어질 때 롤러로 페인트칠해야 하는 최소 횟수를 return 하는 solution 함수를 작성해 주세요.
- 문자열 나누기 : 문자열 s가 입력되었을 때 다음 규칙을 따라서 이 문자열을 여러 문자열로 분해하려고 합니다.
먼저 첫 글자를 읽습니다. 이 글자를 x라고 합시다.
이제 이 문자열을 왼쪽에서 오른쪽으로 읽어나가면서, x와 x가 아닌 다른 글자들이 나온 횟수를 각각 셉니다. 처음으로 두 횟수가 같아지는 순간 멈추고, 지금까지 읽은 문자열을 분리합니다.
s에서 분리한 문자열을 빼고 남은 부분에 대해서 이 과정을 반복합니다. 남은 부분이 없다면 종료합니다.
만약 두 횟수가 …

[1일차] 김리연 / 모의고사 외 3개

---

1st/Jihyun/Programmers/SimilarityOfArrays.java

<hr/>
- 배열의 유사도 : 문자열 배열 s1과 s2가 주어질 때, 같은 원소의 개수를 return하도록 solution 함수 작성

[78일차] 김지현 / 배열의 유사도

---

2st/Riyeon/가채점.java
2st/Riyeon/창고 정리.java
2st/Riyeon/피타고라스의 정리.java

| 피타고라스의 정리 | 프로그래머스 | Level.0 |
| 가채점 | 프로그래머스 | Level.0 |
| 창고 정리 | 프로그래머스 | Level.0 |
<hr/>
- 피타고라스의 정리 : 직각삼각형의 한 변의 길이를 나타내는 정수 a와 빗변의 길이를 나타내는 정수 c가 주어질 때, 다른 한 변의 길이의 제곱, b_square 을 출력하도록 한 줄을 수정해 코드를 완성해 주세요.
- 가채점 : 성적을 문의하려는 학생들의 번호가 담긴 정수 리스트 numbers와 가채점한 점수가 성적을 문의하려는 학생 순서대로 담긴 정수 리스트 our_score, 실제 성적이 번호 순서대로 담긴 정수 리스트 score_list가 주어집니다. 주어진 solution 함수는 가채점한 점수가 실제 성적과 동일하다면 "Same"을, 다르다면 "Different"를 순서대로 리스트에 담아 return하는 함수입니다. solution 함수가 올바르게 작동하도록 한 줄을 수정해 주세요.
- 창고 정리 : 주어진 solution 함수는 정리되기 전 창고의 물건 이름이 담긴 문자열 리스트 storage와 각 물건의 개수가 담긴 정수 리스트 num이 주어질 때, 정리된 창고에서 개수가 가장 많은 물건의 이름을 return 하는 함수입니다. solution 함수가 올바르게 작동하도록 한 줄을 수정해 주세요. 예를 들어 창고의 각 칸에 담겨있는 물건의 이름이storage = ["pencil", "pencil", "pencil", "book"], 각 물건의 …

[3일차] 김리연 / 피타고라스의 정리 외 2개

---

2st/Riyeon/최댓값과 최솟값.java

| 최댓값과 최솟값 | 프로그래머스 | Level.2 |
<hr/>
- 최댓값과 최솟값 : 문자열 s에는 공백으로 구분된 숫자들이 저장되어 있습니다. str에 나타나는 숫자 중 최소값과 최대값을 찾아 이를 "(최소값) (최대값)"형태의 문자열을 반환하는 함수, solution을 완성하세요. 예를들어 s가 "1 2 3 4"라면 "1 4"를 리턴하고, "-1 -2 -3 -4"라면 "-4 -1"을 리턴하면 됩니다.

[4일차] 김리연 / 최댓값과 최솟값

---

2st/Riyeon/최솟값 만들기.java

| 최솟값 만들기 | 프로그래머스 | Level.2 |
<hr/>
- 최솟값 만들기 : 길이가 같은 배열 A, B 두개가 있습니다. 각 배열은 자연수로 이루어져 있습니다. 배열 A, B에서 각각 한 개의 숫자를 뽑아 두 수를 곱합니다. 이러한 과정을 배열의 길이만큼 반복하며, 두 수를 곱한 값을 누적하여 더합니다. 이때 최종적으로 누적된 값이 최소가 되도록 만드는 것이 목표입니다. (단, 각 배열에서 k번째 숫자를 뽑았다면 다음에 k번째 숫자는 다시 뽑을 수 없습니다.) 배열 A, B가 주어질 때 최종적으로 누적된 최솟값을 return 하는 solution 함수를 완성해 주세요.

[5일차] 김리연 / 최솟값 만들기

---

2st/Riyeon/숫자의 표현.java

| 숫자의 표현 | 프로그래머스 | Level.2 |
<hr/>
- 숫자의 표현 : Finn은 요즘 수학공부에 빠져 있습니다. 수학 공부를 하던 Finn은 자연수 n을 연속한 자연수들로 표현 하는 방법이 여러개라는 사실을 알게 되었습니다. 예를들어 15는 다음과 같이 4가지로 표현 할 수 있습니다.
1 + 2 + 3 + 4 + 5 = 15
4 + 5 + 6 = 15
7 + 8 = 15
15 = 15
자연수 n이 매개변수로 주어질 때, 연속된 자연수들로 n을 표현하는 방법의 수를 return하는 solution를 완성해주세요.

[6일차] 김리연 / 숫자의 표현

---

2st/Riyeon/다음 큰 숫자.java

| 다음 큰 숫자 | 프로그래머스 | Level.2 |
<hr/>
- 다음 큰 숫자 : 자연수 n이 주어졌을 때, n의 다음 큰 숫자는 다음과 같이 정의 합니다.
조건 1. n의 다음 큰 숫자는 n보다 큰 자연수 입니다.
조건 2. n의 다음 큰 숫자와 n은 2진수로 변환했을 때 1의 갯수가 같습니다.
조건 3. n의 다음 큰 숫자는 조건 1, 2를 만족하는 수 중 가장 작은 수 입니다.
예를 들어서 78(1001110)의 다음 큰 숫자는 83(1010011)입니다. 자연수 n이 매개변수로 주어질 때, n의 다음 큰 숫자를 return 하는 solution 함수를 완성해주세요.

[7일차] 김리연 / 다음 큰 숫자

---

2st/Riyeon/대충 만든 자판.java

| 대충 만든 자판 | 프로그래머스 | Level.1 |
<hr/>
- 대충 만든 자판 : 휴대폰의 자판은 컴퓨터 키보드 자판과는 다르게 하나의 키에 여러 개의 문자가 할당될 수 있습니다. 키 하나에 여러 문자가 할당된 경우, 동일한 키를 연속해서 빠르게 누르면 할당된 순서대로 문자가 바뀝니다. 예를 들어, 1번 키에 "A", "B", "C" 순서대로 문자가 할당되어 있다면 1번 키를 한 번 누르면 "A", 두 번 누르면 "B", 세 번 누르면 "C"가 되는 식입니다. 같은 규칙을 적용해 아무렇게나 만든 휴대폰 자판이 있습니다. 이 휴대폰 자판은 키의 개수가 1개부터 최대 100개까지 있을 수 있으며, 특정 키를 눌렀을 때 입력되는 문자들도 무작위로 배열되어 있습니다. 또, 같은 문자가 자판 전체에 여러 번 할당된 경우도 있고, 키 하나에 같은 문자가 여러 번 할당된 경우도 있습니다. 심지어 아예 할당되지 않은 경우도 있습니다. 따라서 몇몇 문자열은 작성할 수 없을 수도 있습니다. 이 휴대폰 자판을 이용해 특정 문자열을 작성할 때, 키를 최소 몇 번 눌러야 그 문자열을 작성할 수 있는지 알아보고자 합니다. 1번 키부터 차례대로 할당된 문자들이 순서대로 담긴 문자열배열 keymap과 입력하려는 문자열들이 담긴 문자열 배열 targets가 주어질 때, 각 문자열을 작성하기 위해 키를 최소 몇 번씩 눌러야 하는지 순서대로 배열에 담아 return 하는 solution 함수를 완성해 주세요. 단, 목표 문자열을 작성할 수 없을 때는 …

[8일차] 김리연 / 대충 만든 자판

---

2st/Riyeon/햄버거 만들기.java

| 햄버거 만들기 | 프로그래머스 | Level.1 |
<hr/>
- 햄버거 만들기 : 햄버거 가게에서 일을 하는 상수는 햄버거를 포장하는 일을 합니다. 함께 일을 하는 다른 직원들이 햄버거에 들어갈 재료를 조리해 주면 조리된 순서대로 상수의 앞에 아래서부터 위로 쌓이게 되고, 상수는 순서에 맞게 쌓여서 완성된 햄버거를 따로 옮겨 포장을 하게 됩니다. 상수가 일하는 가게는 정해진 순서(아래서부터, 빵 – 야채 – 고기 - 빵)로 쌓인 햄버거만 포장을 합니다. 상수는 손이 굉장히 빠르기 때문에 상수가 포장하는 동안 속 재료가 추가적으로 들어오는 일은 없으며, 재료의 높이는 무시하여 재료가 높이 쌓여서 일이 힘들어지는 경우는 없습니다.
예를 들어, 상수의 앞에 쌓이는 재료의 순서가 [야채, 빵, 빵, 야채, 고기, 빵, 야채, 고기, 빵]일 때, 상수는 여섯 번째 재료가 쌓였을 때, 세 번째 재료부터 여섯 번째 재료를 이용하여 햄버거를 포장하고, 아홉 번째 재료가 쌓였을 때, 두 번째 재료와 일곱 번째 재료부터 아홉 번째 재료를 이용하여 햄버거를 포장합니다. 즉, 2개의 햄버거를 포장하게 됩니다.
상수에게 전해지는 재료의 정보를 나타내는 정수 배열 ingredient가 주어졌을 때, 상수가 포장하는 햄버거의 개수를 return 하도록 solution 함수를 완성하시오.

[9일차] 김리연 / 햄버거 만들기

---

2st/Riyeon/다트 게임.java
2st/Riyeon/로또의 최고 순위와 최저 순위.java
2st/Riyeon/소수 만들기·java

| 소수 만들기 | 프로그래머스 | Level.1 |
| 다트 게임 | 프로그래머스 | Level.1 |
| 로또의 최고 순위와 최저 순위 | 프로그래머스 | Level.1 |
<hr/>
- 소수 만들기 : 주어진 숫자 중 3개의 수를 더했을 때 소수가 되는 경우의 개수를 구하려고 합니다. 숫자들이 들어있는 배열 nums가 매개변수로 주어질 때, nums에 있는 숫자들 중 서로 다른 3개를 골라 더했을 때 소수가 되는 경우의 개수를 return 하도록 solution 함수를 완성해주세요.
- 다트 게임 : 카카오톡 게임별의 하반기 신규 서비스로 다트 게임을 출시하기로 했다. 다트 게임은 다트판에 다트를 세 차례 던져 그 점수의 합계로 실력을 겨루는 게임으로, 모두가 간단히 즐길 수 있다.
갓 입사한 무지는 코딩 실력을 인정받아 게임의 핵심 부분인 점수 계산 로직을 맡게 되었다. 다트 게임의 점수 계산 로직은 아래와 같다.
1. 다트 게임은 총 3번의 기회로 구성된다.
2. 각 기회마다 얻을 수 있는 점수는 0점에서 10점까지이다.
3. 점수와 함께 Single(S), Double(D), Triple(T) 영역이 존재하고 각 영역 당첨 시 점수에서 1제곱, 2제곱, 3제곱 (점수1 , 점수2 , 점수3 )으로 계산된다.
4. 옵션으로 스타상(*) , 아차상(#)이 존재하며 스타상(*) 당첨 시 해당 점수와 바로 전에 얻은 점수를 각 2배로 만든다. 아차상(#) 당첨 시 해당 점수는 마이너스된다.
5. 스타상(*)은 첫 번째 …

[11일차] 김리연 / 소수 만들기 외 2개

---

2st/Riyeon/둘만의 암호.java
2st/Riyeon/완주하지 못한 선수.java

| 둘만의 암호 | 프로그래머스 | Level.1 |
| 완주하지 못한 선수 | 프로그래머스 | Level.1 |
<hr/>
- 둘만의 암호 : 두 문자열 s와 skip, 그리고 자연수 index가 주어질 때, 다음 규칙에 따라 문자열을 만들려 합니다. 암호의 규칙은 다음과 같습니다.
문자열 s의 각 알파벳을 index만큼 뒤의 알파벳으로 바꿔줍니다.
index만큼의 뒤의 알파벳이 z를 넘어갈 경우 다시 a로 돌아갑니다.
skip에 있는 알파벳은 제외하고 건너뜁니다.
두 문자열 s와 skip, 그리고 자연수 index가 매개변수로 주어질 때 위 규칙대로 s를 변환한 결과를 return하도록 solution 함수를 완성해주세요.
- 완주하지 못한 선수 : 수많은 마라톤 선수들이 마라톤에 참여하였습니다. 단 한 명의 선수를 제외하고는 모든 선수가 마라톤을 완주하였습니다. 마라톤에 참여한 선수들의 이름이 담긴 배열 participant와 완주한 선수들의 이름이 담긴 배열 completion이 주어질 때, 완주하지 못한 선수의 이름을 return 하도록 solution 함수를 작성해주세요.

[12일차] 김리연 / 둘만의 암호 외 1개

---

2st/Riyeon/달리기 경주.java

| 달리기 경주 | 프로그래머스 | Level.1 |
<hr/>
- 달리기 경주 : 얀에서는 매년 달리기 경주가 열립니다. 해설진들은 선수들이 자기 바로 앞의 선수를 추월할 때 추월한 선수의 이름을 부릅니다. 예를 들어 1등부터 3등까지 "mumu", "soe", "poe" 선수들이 순서대로 달리고 있을 때, 해설진이 "soe"선수를 불렀다면 2등인 "soe" 선수가 1등인 "mumu" 선수를 추월했다는 것입니다. 즉 "soe" 선수가 1등, "mumu" 선수가 2등으로 바뀝니다. 선수들의 이름이 1등부터 현재 등수 순서대로 담긴 문자열 배열 players와 해설진이 부른 이름을 담은 문자열 배열 callings가 매개변수로 주어질 때, 경주가 끝났을 때 선수들의 이름을 1등부터 등수 순서대로 배열에 담아 return 하는 solution 함수를 완성해주세요.

[13일차] 김리연 / 달리기 경주

---

2st/Riyeon/성격 유형 검사하기.java
2st/Riyeon/올바른 괄호.java
2st/Riyeon/이진 변환 반복하기.java

| 성격 유형 검사하기 | 프로그래머스 | Level.1 |
<hr/>
- 성격 유형 검사하기 :나만의 카카오 성격 유형 검사지를 만들려고 합니다. 성격 유형 검사는 다음과 같은 4개 지표로 성격 유형을 구분합니다. 성격은 각 지표에서 두 유형 중 하나로 결정됩니다. 질문마다 판단하는 지표를 담은 1차원 문자열 배열 survey와 검사자가 각 질문마다 선택한 선택지를 담은 1차원 정수 배열 choices가 매개변수로 주어집니다. 이때, 검사자의 성격 유형 검사 결과를 지표 번호 순서대로 return 하도록 solution 함수를 완성해주세요.

[14일차] 김리연 / 성격 유형 검사하기

---

2st/Riyeon/숫자 짝꿍.java

| 숫자 짝꿍 | 프로그래머스 | Level.1 |
<hr/>
- 숫자 짝꿍 : 두 정수 X, Y의 임의의 자리에서 공통으로 나타나는 정수 k(0 ≤ k ≤ 9)들을 이용하여 만들 수 있는 가장 큰 정수를 두 수의 짝꿍이라 합니다(단, 공통으로 나타나는 정수 중 서로 짝지을 수 있는 숫자만 사용합니다). X, Y의 짝꿍이 존재하지 않으면, 짝꿍은 -1입니다. X, Y의 짝꿍이 0으로만 구성되어 있다면, 짝꿍은 0입니다.
예를 들어, X = 3403이고 Y = 13203이라면, X와 Y의 짝꿍은 X와 Y에서 공통으로 나타나는 3, 0, 3으로 만들 수 있는 가장 큰 정수인 330입니다. 다른 예시로 X = 5525이고 Y = 1255이면 X와 Y의 짝꿍은 X와 Y에서 공통으로 나타나는 2, 5, 5로 만들 수 있는 가장 큰 정수인 552입니다(X에는 5가 3개, Y에는 5가 2개 나타나므로 남는 5 한 개는 짝 지을 수 없습니다.)
두 정수 X, Y가 주어졌을 때, X, Y의 짝꿍을 return하는 solution 함수를 완성해주세요.

[17일차] 김리연 / 숫자 짝꿍

---

2st/Riyeon/이웃한 칸.java
2st/Riyeon/체육복.java

| 체육복 | 프로그래머스 | Level.1 |
<hr/>
- 체육복 : 점심시간에 도둑이 들어, 일부 학생이 체육복을 도난당했습니다. 다행히 여벌 체육복이 있는 학생이 이들에게 체육복을 빌려주려 합니다. 학생들의 번호는 체격 순으로 매겨져 있어, 바로 앞번호의 학생이나 바로 뒷번호의 학생에게만 체육복을 빌려줄 수 있습니다. 예를 들어, 4번 학생은 3번 학생이나 5번 학생에게만 체육복을 빌려줄 수 있습니다. 체육복이 없으면 수업을 들을 수 없기 때문에 체육복을 적절히 빌려 최대한 많은 학생이 체육수업을 들어야 합니다.
전체 학생의 수 n, 체육복을 도난당한 학생들의 번호가 담긴 배열 lost, 여벌의 체육복을 가져온 학생들의 번호가 담긴 배열 reserve가 매개변수로 주어질 때, 체육수업을 들을 수 있는 학생의 최댓값을 return 하도록 solution 함수를 작성해주세요.

[18일차] 김리연 / 체육복

---

3st/Jaeyoung/나이 계산.java
3st/Jaeyoung/대소문자 바꿔서 출력하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/250131
| 나이 계산 | 프로그래머스 | Level.0 |
<hr/>
- 제목 : 나이를 세는 방법은 여러 가지가 있습니다. 그중 한국식 나이는 태어난 순간 1살이 되며 해가 바뀔 때마다 1살씩 더 먹게 됩니다. 연 나이는 태어난 순간 0살이며 해가 바뀔 때마다 1살씩 더 먹게 됩니다. 각각 나이의 계산법은 다음과 같습니다.
한국식 나이 : 현재 연도 - 출생 연도 + 1
연 나이 : 현재 연도 - 출생 연도
출생 연도를 나타내는 정수 year와 구하려는 나이의 종류를 나타내는 문자열 age_type이 주어질 때 2030년에 몇 살인지 출력하도록 빈칸을 채워 코드를 완성해 주세요. age_type이 "Korea"라면 한국식 나이를, "Year"라면 연 나이를 출력합니다.

[19일차] 박재영 / 나이 계산

---

2st/Riyeon/개인정보 수집 유효기간.java
2st/Riyeon/공원 산책.java
2st/Riyeon/바탕화면 정리.java
2st/Riyeon/신규 아이디 추천.java
2st/Riyeon/키패드 누르기.java

| 공원 산책 | 프로그래머스 | Level.1 |
<hr/>
- 공원 산책 : 지나다니는 길을 'O', 장애물을 'X'로 나타낸 직사각형 격자 모양의 공원에서 로봇 강아지가 산책을 하려합니다. 산책은 로봇 강아지에 미리 입력된 명령에 따라 진행하며, 명령은 다음과 같은 형식으로 주어집니다.
["방향 거리", "방향 거리" … ]
예를 들어 "E 5"는 로봇 강아지가 현재 위치에서 동쪽으로 5칸 이동했다는 의미입니다. 로봇 강아지는 명령을 수행하기 전에 다음 두 가지를 먼저 확인합니다.
주어진 방향으로 이동할 때 공원을 벗어나는지 확인합니다.
주어진 방향으로 이동 중 장애물을 만나는지 확인합니다.
위 두 가지중 어느 하나라도 해당된다면, 로봇 강아지는 해당 명령을 무시하고 다음 명령을 수행합니다.
공원의 가로 길이가 W, 세로 길이가 H라고 할 때, 공원의 좌측 상단의 좌표는 (0, 0), 우측 하단의 좌표는 (H - 1, W - 1) 입니다.
공원을 나타내는 문자열 배열 park, 로봇 강아지가 수행할 명령이 담긴 문자열 배열 routes가 매개변수로 주어질 때, 로봇 강아지가 모든 명령을 수행 후 놓인 위치를 [세로 방향 좌표, 가로 방향 좌표] 순으로 배열에 담아 return 하도록 solution 함수를 완성해주세요.

[20일차] 김리연 / 공원 산책

---

2st/Riyeon/JadenCase 문자열 만들기.java

| JadenCase 문자열 만들기 | 프로그래머스 | Level.2 |
<hr/>
- JadenCase 문자열 만들기 : JadenCase란 모든 단어의 첫 문자가 대문자이고, 그 외의 알파벳은 소문자인 문자열입니다. 단, 첫 문자가 알파벳이 아닐 때에는 이어지는 알파벳은 소문자로 쓰면 됩니다. (첫 번째 입출력 예 참고)
문자열 s가 주어졌을 때, s를 JadenCase로 바꾼 문자열을 리턴하는 함수, solution을 완성해주세요.

[25일차] 김리연 / JadenCase 문자열 만들기

---

2st/Riyeon/피보나치 수.java

| 피보나치 수 | 프로그래머스 | Level.2 |
<hr/>
- 피보나치 수 : 피보나치 수는 F(0) = 0, F(1) = 1일 때, 1 이상의 n에 대하여 F(n) = F(n-1) + F(n-2) 가 적용되는 수 입니다.
예를들어
F(2) = F(0) + F(1) = 0 + 1 = 1
F(3) = F(1) + F(2) = 1 + 1 = 2
F(4) = F(2) + F(3) = 1 + 2 = 3
F(5) = F(3) + F(4) = 2 + 3 = 5 와 같이 이어집니다. 
2 이상의 n이 입력되었을 때, n번째 피보나치 수를 1234567으로 나눈 나머지를 리턴하는 함수, solution을 완성해 주세요.

[26일차] 김리연 / 피보나치 수

---

1st/Jinseon/콜라츠 추측.java

https://school.programmers.co.kr/learn/courses/30/lessons/12943
| 콜라츠 추측 | 프로그래머스 | Level.1 |
<hr/>
- 콜라츠 추측 : num이 486에서 멈추는 이슈 발생. long으로 바꿔주니 해결

[80일차] 이진선 / 콜라츠 추측

---

1st/Sunhee/programmers/피로도.java

https://school.programmers.co.kr/learn/courses/30/lessons/12916?language=javascript
| 문자열 내 p와 y의 개수 | 프로그래머스 | Level.1 |
<hr/>
- 대문자와 소문자가 섞여있는 문자열 s가 주어집니다. s에 'p'의 개수와 'y'의 개수를 비교해 같으면 True, 다르면 False를 return 하는 solution를 완성하세요. 'p', 'y' 모두 하나도 없는 경우는 항상 True를 리턴합니다. 단, 개수를 비교할 때 대문자와 소문자는 구별하지 않습니다.
예를 들어 s가 "pPoooyY"면 true를 return하고 "Pyy"라면 false를 return합니다.

[80일차] 김선희 / 문자열 내 p와 y의 개수

---

1st/Jinseon/문자열 곱하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/181940?language=java
<hr/>
- 문자열 곱하기 : repeat()메소드를 사용

[81일차] 이진선 / 문자열 곱하기

---

3st/Seojun/Coding_Test240626.java
3st/Seojun/덧셈식 출력하기..c
3st/Seojun/홀짝에 따라 다른 값 반환하기.java

| 홀짝 구분하기 | 프로그래머스 | Level.0 |
<hr/>
-홀짝 구분하기 : 자연수 n이 입력으로 주어졌을 때 만약 n이 짝수이면 "n is even"을, 홀수이면 "n is odd"를 출력하는 코드를 작성해 보세요.

[29일차] 김서준 / 홀짝 구분하기

---

3st/Jaeyoung/문자열 돌리기.java

https://school.programmers.co.kr/learn/courses/30/lessons/181945
| 문자열 돌리기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 돌리기 : 문자열 str이 주어집니다.

[29일차] 박재영 / 문자열 돌리기

---

1st/Jihyun/Programmers/MakeItTwoDimensional.java
1st/Jihyun/Programmers/RemoveVowels.java

<hr/>
- 모음 제거: 문자열 my_string이 매개변수로 주어질 때 모음을 제거한 문자열을 return하도록 solution 함수 작성

[82일차] 김지현 / 모음 제거

---

1st/Jiin/ConcatString.java

| [글자 이어 붙여 문자열 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/181915) | 프로그래머스 | Level.0 |
<hr/>
- 글자 이어 붙여 문자열 만들기 : 문자열 my_string과 정수 배열 index_list가 매개변수로 주어집니다. my_string의 index_list의 원소들에 해당하는 인덱스의 글자들을 순서대로 이어 붙인 문자열을 return 하는 solution 함수를 작성해 주세요.

[82일차] 이지인 / 글자 이어 붙여 문자열 만들기

---

3st/Juhee/문자열 반복해서 출력하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/181950
| 문자열 반복해서 출력하기 | 프로그래머스 | Level.0 |
<hr/>

[31일차] 최주희 / 문자열 반복해서 출력하기

---

3st/Hyeonseo/programmer/두 개 뽑아서 더하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/68644
| 두 개 뽑아서 더하기| 프로그래머스 | Level.1 |
<hr/>
- 두 개 뽑아서 더하기 : 정수 배열 numbers가 주어집니다. numbers에서 서로 다른 인덱스에 있는 두 개의 수를 뽑아 더해서 만들 수 있는 모든 수를 배열에 오름차순으로 담아 return 하도록 solution 함수를 완성해주세요.

[31일차]조현서/두 개 뽑아서 더하

---

1st/Jihyun/Programmers/CtrlZ.java

| 컨트롤 제트 | 프로그래머스 | Level.0 |
<hr/>
- 컨트롤 제트: 숫자와 "Z"로 이루어진 문자열 s가 주어질 때, 머쓱이가 구한 값을 return 하도록 solution 함수 작성

[84일차] 김지현 / 컨트롤 제트

---

2st/Riyeon/나머지 구하기.py
2st/Riyeon/배열 두배 만들기.py
2st/Riyeon/중앙값 구하기.py

| 배열 두배 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 배열 두배 만들기 : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 각 원소에 두배한 원소를 가진 배열을 return하도록 solution 함수를 완성해주세요.
- 중앙값 구하기 : 중앙값은 어떤 주어진 값들을 크기의 순서대로 정렬했을 때 가장 중앙에 위치하는 값을 의미합니다. 예를 들어 1, 2, 7, 10, 11의 중앙값은 7입니다. 정수 배열 array가 매개변수로 주어질 때, 중앙값을 return 하도록 solution 함수를 완성해보세요.  // 배열 인덱스는 0부터 시작한다.!

[31일차] 김리연 / 배열 두배 만들기 외 2개

---

2st/Riyeon/최빈값 구하기.py

| 최빈값 구하기 | 프로그래머스 | Level.0 |
<hr/>

[32일차] 김리연 / 최빈값 구하기

---

3st/Juhee/조건에 맞게 수열 변환하기.java

| 홀짝 구분하기| 프로그래머스 | Level.0 |
<hr/>

[ 32일차 ] 최주희 / 홀짝 구분하기 

---

3st/Jaeyoung/n의 배수.java
3st/Jaeyoung/문자 리스트를 문자열로 변환하기.java
3st/Jaeyoung/산책.java
3st/Jaeyoung/양꼬치.java
3st/Jaeyoung/완주하지 못한 선수.java

| 양꼬치 | 프로그래머스 | Level.1 |
<hr/>
- 제목 : 머쓱이네 양꼬치 가게는 10인분을 먹으면 음료수 하나를 서비스로 줍니다. 양꼬치는 1인분에 12,000원, 음료수는 2,000원입니다. 정수 n과 k가 매개변수로 주어졌을 때, 양꼬치 n인분과 음료수 k개를 먹었다면 총얼마를 지불해야 하는지 return 하도록 solution 함수를 완성해보세요.

[32일차] 박재영 / 양꼬치

---

3st/Jaeyoung/피타고라스의 정의.java

https://school.programmers.co.kr/learn/courses/30/lessons/250132
| 피타고라스의 정의 | 프로그래머스 | Level.0 |
<hr/>
- 제목 : 직각삼각형이 주어졌을 때 빗변의 제곱은 다른 두 변을 각각 제곱한 것의 합과 같습니다. 한 변의 길이를 나타내는 정수 a와 빗변의 길이를 나타내는 정수 c가 주어질 때, 다른 한 변의 길이의 제곱, b_square 을 출력하도록 한 줄을 수정해 코드를 완성해 주세요.

[33일차] 박재영 / 피타고라스의 정의

---

2st/Riyeon/짝수는 싫어요.py
2st/Riyeon/피자 나눠 먹기 (1).py

| 짝수는 싫어요 | 프로그래머스 | Level.0 |
| 피자 나눠 먹기 (1) | 프로그래머스 | Level.0 |
<hr/>

[33일차] 김리연 / 짝수는 싫어요 외 1개

---

3st/Jaeyoung/홀짝에 따라 다른 값 반환하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/181935
<hr/>
- 제목 : 양의 정수 n이 매개변수로 주어질 때, n이 홀수라면 n 이하의 홀수인 모든 양의 정수의 합을 return 하고 n이 짝수라면 n 이하의 짝수인 모든 양의 정수의 제곱의 합을 return 하는 solution 함수를 작성해 주세요.

[34일차] 박재영 / 홀짝에 따라 다른 값 반환하기

---

3st/Hyeonseo/programmer/가위 바위 보.java

https://school.programmers.co.kr/learn/courses/30/lessons/120839
|가위 바위 보 | 프로그래머스 |  Level.0 |
<hr/>
- 가위 바위  : 가위는 2 바위는 0 보는 5로 표현합니다. 가위 바위 보를 내는 순서대로 나타낸 문자열 rsp가 매개변수로 주어질 때, rsp에 저장된 가위 바위 보를 모두 이기는 경우를 순서대로 나타낸 문자열을 return하도록 solution 함수를 완성해보세요.

[34일차] 조현서 / 가위 바위 보

---

1st/Jihyun/Programmers/UnsuccessfulRunner.java

| 완주하지 못한 선수 | 프로그래머스 | Level.1 |
<hr/>
- 완주하지 못한 선수 : 마라톤에 참여한 선수들의 이름이 담긴 배열 participant와 완주한 선수들의 이름이 담긴 배열 completion이 주어질 때, 완주하지 못한 선수의 이름을 return 하도록 solution 함수 작성

[87일차] 김지현 / 완주하지 못한 선수

---

2st/Riyeon/배열의 평균값.py
2st/Riyeon/피자 나눠 먹기 (2).py
2st/Riyeon/피자 나눠 먹기 (3).py

| 피자 나눠 먹기 (2) | 프로그래머스 | Level.0 |
| 피자 나눠 먹기 (3) | 프로그래머스 | Level.0 |
| 배열의 평균값 | 프로그래머스 | Level.0 |
<hr/>
- 피자 나눠 먹기 (2) : 머쓱이네 피자가게는 피자를 여섯 조각으로 잘라 줍니다. 피자를 나눠먹을 사람의 수 n이 매개변수로 주어질 때, n명이 주문한 피자를 남기지 않고 모두 같은 수의 피자 조각을 먹어야 한다면 최소 몇 판을 시켜야 하는지를 return 하도록 solution 함수를 완성해보세요.
- 피자 나눠 먹기 (3) : 머쓱이네 피자가게는 피자를 두 조각에서 열 조각까지 원하는 조각 수로 잘라줍니다. 피자 조각 수 slice와 피자를 먹는 사람의 수 n이 매개변수로 주어질 때, n명의 사람이 최소 한 조각 이상 피자를 먹으려면 최소 몇 판의 피자를 시켜야 하는지를 return 하도록 solution 함수를 완성해보세요.
- 배열의 평균값 : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소의 평균값을 return하도록 solution 함수를 완성해주세요.

[34일차] 김리연 / 피자 나눠 먹기 (2) 외 2개

---

1st/Sunhee/JavaScript/다음 큰 숫자.js
1st/Sunhee/JavaScript/정수 삼각형.js

https://school.programmers.co.kr/learn/courses/30/lessons/43162
| 네트워크 | 프로그래머스 | Level.3 |
<hr/>
- 네트워크란 컴퓨터 상호 간에 정보를 교환할 수 있도록 연결된 형태를 의미합니다. 예를 들어, 컴퓨터 A와 컴퓨터 B가 직접적으로 연결되어있고, 컴퓨터 B와 컴퓨터 C가 직접적으로 연결되어 있을 때 컴퓨터 A와 컴퓨터 C도 간접적으로 연결되어 정보를 교환할 수 있습니다. 따라서 컴퓨터 A, B, C는 모두 같은 네트워크 상에 있다고 할 수 있습니다.
컴퓨터의 개수 n, 연결에 대한 정보가 담긴 2차원 배열 computers가 매개변수로 주어질 때, 네트워크의 개수를 return 하도록 solution 함수를 작성하시오.

[87일차] 김선희 / 네트워크

---

1st/Jiin/Sangenald.cpp

| [상근날드](https://www.acmicpc.net/problem/5543) | 백준 | 브론즈 IV |
<hr/>
- 상근날드 : 상근날드에는 세 개의 햄버거와 두 개의 음료수 종류가 있습니다. 각각 한 개의 버거와 음료수가 한 세트이고, 버거와 음료수의 값에서 50원을 뺀 값이 세트의 가격 입니다. 세 개의 햄버거 가격과 두 개의 음료수 가격이 주어졌을 때 가장 낮은 세트의 금액을 출력하시오

[87일차] 이지인 / 상근날드

---

3st/Jaeyoung/옷가게 할인 받기.java

https://school.programmers.co.kr/learn/courses/30/lessons/120818
| 옷가게 할인받기 | 프로그래머스 | Level.0 |
<hr/>
- 제목 : 머쓱이네 옷가게는 10만 원 이상 사면 5%, 30만 원 이상 사면 10%, 50만 원 이상 사면 20%를 할인해줍니다.

[35일차] 박재영 / 옷가게 할인받기

---

1st/Sunhee/JavaScript/네트워크.js

https://school.programmers.co.kr/learn/courses/30/lessons/42628
| 이중우선순위큐 | 프로그래머스 | Level.3 |
<hr/>
- 이중 우선순위 큐는 다음 연산을 할 수 있는 자료구조를 말합니다.
- 이중 우선순위 큐가 할 연산 operations가 매개변수로 주어질 때, 모든 연산을 처리한 후 큐가 비어있으면 [0,0] 비어있지 않으면 [최댓값, 최솟값]을 return 하도록 solution 함수를 구현해주세요.

[88일차] 김선희 / 이중우선순위큐

---

2st/Yeonwoo/합성수 찾기

https://school.programmers.co.kr/learn/courses/30/lessons/120846
| 합성수 찾기 | 프로그래머스 | Level.0 |
<hr/>
- 합성수 찾기 : 약수의 개수가 세 개 이상인 수를 합성수라고 합니다. 자연수 n이 매개변수로 주어질 때 n이하의 합성수의 개수를 return하도록 solution 함수를 완성해주세요.

[35일차] 채연우 / 합성수 찾기

---

1st/Jihyun/Programmers/BundleOfCard.java

| 카드 뭉치 | 프로그래머스 | Level.1 |
<hr/>
- 카드 뭉치 : 문자열로 이루어진 배열 cards1, cards2와 원하는 단어 배열 goal이 매개변수로 주어질 때, cards1과 cards2에 적힌 단어들로 goal를 만들 있다면 "Yes"를, 만들 수 없다면 "No"를 return하는 solution 함수 작성

[88일차] 김지현 / 카드 뭉치

---

2st/Riyeon/나이 출력.py
2st/Riyeon/배열 뒤집기.py
2st/Riyeon/아이스 아메리카노.py
2st/Riyeon/옷가게 할인 받기.py

| 옷가게 할인 받기 | 프로그래머스 | Level.0 |
| 배열 뒤집기 | 프로그래머스 | Level.0 |
<hr/>
- 옷가게 할인 받기 : 머쓱이네 옷가게는 10만 원 이상 사면 5%, 30만 원 이상 사면 10%, 50만 원 이상 사면 20%를 할인해줍니다. 구매한 옷의 가격 price가 주어질 때, 지불해야 할 금액을 return 하도록 solution 함수를 완성해보세요.
- 나이 출력 : 머쓱이는 선생님이 몇 년도에 태어났는지 궁금해졌습니다. 2022년 기준 선생님의 나이 age가 주어질 때, 선생님의 출생 연도를 return 하는 solution 함수를 완성해주세요 
- 배열 뒤집기 : 정수가 들어 있는 배열 num_list가 매개변수로 주어집니다. num_list의 원소의 순서를 거꾸로 뒤집은 배열을 return하도록 solution 함수를 완성해주세요.

[35일차] 김리연 / 옷가게 할인 받기 외 3개

---

3st/Hyeonseo/programmer/나이 출력.java

https://school.programmers.co.kr/learn/courses/30/lessons/120820
| 나이 출력 | 프로그래머스 | Level.0|
<hr/>
- 나이 출 : 머쓱이는 선생님이 몇 년도에 태어났는지 궁금해졌습니다. 2022년 기준 선생님의 나이 age가 주어질 때, 선생님의 출생 연도를 return 하는 solution 함수를 완성해주세요

[36일차] 조현서/나이 출력

---

1st/Sunhee/JavaScript/야근지수.js
1st/Sunhee/JavaScript/이중우선순위큐.js

https://school.programmers.co.kr/learn/courses/30/lessons/12927
| 야근 지수 | 프로그래머스 | Level.3 |
<hr/>
- 회사원 Demi는 가끔은 야근을 하는데요, 야근을 하면 야근 피로도가 쌓입니다. 야근 피로도는 야근을 시작한 시점에서 남은 일의 작업량을 제곱하여 더한 값입니다. Demi는 N시간 동안 야근 피로도를 최소화하도록 일할 겁니다.Demi가 1시간 동안 작업량 1만큼을 처리할 수 있다고 할 때, 퇴근까지 남은 N 시간과 각 일에 대한 작업량 works에 대해 야근 피로도를 최소화한 값을 리턴하는 함수 solution을 완성해주세요.

[89일차] 김선희 /  야근 지수

---

2st/Riyeon/문자열 뒤집기.py

[36일차] 김리연 / 문자열 뒤집기

---

2st/Riyeon/직각삼각형 출력하기.py

| 직각삼각형 출력하기 | 프로그래머스 | Level.0 |
<hr/>
- 직각삼각형 출력하기 : "\*"의 높이와 너비를 1이라고 했을 때, "*"을 이용해 직각 이등변 삼각형을 그리려고합니다. 정수 n 이 주어지면 높이와 너비가 n 인 직각 이등변 삼각형을 출력하도록 코드를 작성해보세요.

[37일차] 김리연 /  직각삼각형 출력하기

---

3st/Hyeonseo/programmer/각도기.java

https://school.programmers.co.kr/learn/courses/30/lessons/120829
| 각도기 | 프로그래머스 |  Level.1 |
<hr/>

[38일차] 조현서 / 각도기

---

2st/Riyeon/짝수 홀수 개수.py

[38일차] 김리연 / 짝수 홀수 개수

---

1st/Sunhee/JavaScript/단어변환.js

https://school.programmers.co.kr/learn/courses/30/lessons/12938
| 최고의 집합 | 프로그래머스 | Level.3 |
<hr/>
- 자연수 n 개로 이루어진 중복 집합(multi set, 편의상 이후에는 "집합"으로 통칭) 중에 다음 두 조건을 만족하는 집합을 최고의 집합이라고 합니다.
각 원소의 합이 S가 되는 수의 집합
위 조건을 만족하면서 각 원소의 곱 이 최대가 되는 집합
예를 들어서 자연수 2개로 이루어진 집합 중 합이 9가 되는 집합은 다음과 같이 4개가 있습니다.
{ 1, 8 }, { 2, 7 }, { 3, 6 }, { 4, 5 }
그중 각 원소의 곱이 최대인 { 4, 5 }가 최고의 집합입니다.
집합의 원소의 개수 n과 모든 원소들의 합 s가 매개변수로 주어질 때, 최고의 집합을 return 하는 solution 함수를 완성해주세요.

[91일차] 김선희 / 최고의 집합 

---

3st/Juhee/대소문자 바꿔서 출력하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/181935
<hr/>

[38일차] 최주희 / 홀짝에 따라 다른 값 반환하기 

---

2st/Riyeon/문자 반복 출력하기.py

[39일차] 김리연 / 문자 반복 출력하기

---

1st/Jihyun/Programmers/LengthOfArrayElement.java

<hr/>
- 배열 원소의 길이 : 문자열 배열 strlist가 주어질 때, strlist 각 원소의 길이를 담은 배열을 retrun하도록 solution 함수 작성

[92일차] 김지현 / 배열 원소의 길이

---

2st/Riyeon/특정 문자 제거하기.py

[40일차] 김리연 / 특정 문자 제거하기

---

1st/Jihyun/Programmers/YearOf2016.java

| 2016년 | 프로그래머스 | Level.1 |
<hr/>
- 2016년 : 두 수 a ,b를 입력받아 2016년 a월 b일이 무슨 요일인지 리턴하는 solution 함수 작성

[93일차] 김지현 / 2016년

---

1st/Sunhee/JavaScript/등굣길.js

https://school.programmers.co.kr/learn/courses/30/lessons/42898
| 등굣길 | 프로그래머스 | Level.3 |
<hr/>
- 계속되는 폭우로 일부 지역이 물에 잠겼습니다. 물에 잠기지 않은 지역을 통해 학교를 가려고 합니다. 집에서 학교까지 가는 길은 m x n 크기의 격자모양으로 나타낼 수 있습니다.
아래 그림은 m = 4, n = 3 인 경우입니다.
가장 왼쪽 위, 즉 집이 있는 곳의 좌표는 (1, 1)로 나타내고 가장 오른쪽 아래, 즉 학교가 있는 곳의 좌표는 (m, n)으로 나타냅니다.
격자의 크기 m, n과 물이 잠긴 지역의 좌표를 담은 2차원 배열 puddles이 매개변수로 주어집니다. 오른쪽과 아래쪽으로만 움직여 집에서 학교까지 갈 수 있는 최단경로의 개수를 1,000,000,007로 나눈 나머지를 return 하도록 solution 함수를 작성해주세요.
제한사항

[93일차] 김선희 / 등굣길

---

2st/Riyeon/각도기.py

[41일차] 김리연 / 각도기

---

2st/Riyeon/양꼬치.py
2st/Riyeon/짝수의 합.py

[42일차] 김리연 /  양꼬치

---

2st/Riyeon/배열 자르기.py

[43일차] 김리연 / 배열 자르기

---

2st/Riyeon/외계행성의 나이.py

| 외계행성의 나이 | 프로그래머스 | Level.0 |
<hr/>
- 외계행성의 나이 : 우주여행을 하던 머쓱이는 엔진 고장으로 PROGRAMMERS-962 행성에 불시착하게 됐습니다. 입국심사에서 나이를 말해야 하는데, PROGRAMMERS-962 행성에서는 나이를 알파벳으로 말하고 있습니다. a는 0, b는 1, c는 2, ..., j는 9입니다. 예를 들어 23살은 cd, 51살은 fb로 표현합니다. 나이 age가 매개변수로 주어질 때 PROGRAMMER-962식 나이를 return하도록 solution 함수를 완성해주세요.

[45일차] 김리연 / 외계행성의 나이

---

2st/Riyeon/진료 순서 정하기.py

| 진료 순서 정하기 | 프로그래머스 | Level.0 |
<hr/>
- 진료 순서 정하기 : 외과의사 머쓱이는 응급실에 온 환자의 응급도를 기준으로 진료 순서를 정하려고 합니다. 정수 배열 emergency가 매개변수로 주어질 때 응급도가 높은 순서대로 진료 순서를 정한 배열을 return하도록 solution 함수를 완성해주세요.

[46일차] 김리연 / 진료 순서 정하기

---

3st/Juhee/주사위 게임 1.java

https://school.programmers.co.kr/learn/courses/30/lessons/181839
| 주사위 게임 1 | 프로그래머스 | Level.0 |
<hr/>
- 주사위 게임 1 : 1부터 6까지 숫자가 적힌 주사위가 두 개 있습니다. 두 주사위를 굴렸을 때 나온 숫자를 각각 a, b라고 했을 때 얻는 점수는 다음과 같습니다.
두 정수 a와 b가 매개변수로 주어질 때, 얻는 점수를 return 하는 solution 함수를 작성해 주세요.

[47일차] 최주희 / 주사위 게임 1

---

2st/Riyeon/개미 군단.py
2st/Riyeon/순서쌍의 개수.py

<hr/>
- 개미 군단 : 개미 군단이 사냥을 나가려고 합니다. 개미군단은 사냥감의 체력에 딱 맞는 병력을 데리고 나가려고 합니다. 장군개미는 5의 공격력을, 병정개미는 3의 공격력을 일개미는 1의 공격력을 가지고 있습니다. 예를 들어 체력 23의 여치를 사냥하려고 할 때, 일개미 23마리를 데리고 가도 되지만, 장군개미 네 마리와 병정개미 한 마리를 데리고 간다면 더 적은 병력으로 사냥할 수 있습니다. 사냥감의 체력 hp가 매개변수로 주어질 때, 사냥감의 체력에 딱 맞게 최소한의 병력을 구성하려면 몇 마리의 개미가 필요한지를 return하도록 solution 함수를 완성해주세요.

[47일차] 김리연 / 순서쌍의 개수 외 1개

---

3st/Hyeonseo/programmer/배열의 길이에 따라 다른 연산하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/181854
| 배열의 길이에 따라 다른 연산하기  | 프로그래머스 | Level.0 |
<hr/>

[48일차] 조현서 / 베열의 길이에 따라 다른 연산하기

---

2st/Riyeon/배열 회전시키기.py
2st/Riyeon/주사위의 개수.py
2st/Riyeon/짝지어 제거하기.java
2st/Riyeon/최댓값 만들기 (1).py
2st/Riyeon/팩토리얼.py
2st/Riyeon/합성수 찾기.py

| 배열 회전시키기 | 프로그래머스 | Level.0 |
| 주사위의 개수 | 프로그래머스 | Level.0 |
| 합성수 찾기 | 프로그래머스 | Level.0 |
| 최댓값 만들기 (1) | 프로그래머스 | Level.0 |
| 팩토리얼 | 프로그래머스 | Level.0 |
| 짝지어 제거하기 | 프로그래머스 | Level.2 |
<hr/>
- 배열 회전시키기 : 정수가 담긴 배열 numbers와 문자열 direction가 매개변수로 주어집니다. 배열 numbers의 원소를 direction방향으로 한 칸씩 회전시킨 배열을 return하도록 solution 함수를 완성해주세요.
- 주사위의 개수 : 머쓱이는 직육면체 모양의 상자를 하나 가지고 있는데 이 상자에 정육면체 모양의 주사위를 최대한 많이 채우고 싶습니다. 상자의 가로, 세로, 높이가 저장되어있는 배열 box와 주사위 모서리의 길이 정수 n이 매개변수로 주어졌을 때, 상자에 들어갈 수 있는 주사위의 최대 개수를 return 하도록 solution 함수를 완성해주세요.
- 합성수 찾기 : 약수의 개수가 세 개 이상인 수를 합성수라고 합니다. 자연수 n이 매개변수로 주어질 때 n이하의 합성수의 개수를 return하도록 solution 함수를 완성해주세요.
- 최댓값 만들기 (1) : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소 중 두 개를 곱해 만들 수 있는 최댓값을 return하도록 solution 함수를 완성해주세요.
- 팩토리얼 : …

[49일차] 김리연 / 배열 회전시키기 외 5개

---

3st/Juhee/배열 비교하기.java
3st/Juhee/피자 나눠 먹기 (1).java

| 피자 나눠 먹기 (1) | 프로그래머스 |  Level.0 |
<hr/>

[49일차] 최주희 / 피자 나눠 먹기(1) 

---

2st/Riyeon/모음 제거.py
2st/Riyeon/문자열 정렬하기 (1).py
2st/Riyeon/소인수분해.py
2st/Riyeon/숨어있는 숫자의 덧셈 (1).py

| 문자열 정렬하기 (1) | 프로그래머스 | Level.0 |
| 숨어있는 숫자의 덧셈 (1) | 프로그래머스 | Level.0 |
| 소인수분해 | 프로그래머스 | Level.0 |
<hr/>
- 모음 제거 : 영어에선 a, e, i, o, u 다섯 가지 알파벳을 모음으로 분류합니다. 문자열 my_string이 매개변수로 주어질 때 모음을 제거한 문자열을 return하도록 solution 함수를 완성해주세요.
- 문자열 정렬하기 (1) : 문자열 my_string이 매개변수로 주어질 때, my_string 안에 있는 숫자만 골라 오름차순 정렬한 리스트를 return 하도록 solution 함수를 작성해보세요.
- 숨어있는 숫자의 덧셈 (1) : 문자열 my_string이 매개변수로 주어집니다. my_string안의 모든 자연수들의 합을 return하도록 solution 함수를 완성해주세요.
- 소인수분해 : 소인수분해란 어떤 수를 소수들의 곱으로 표현하는 것입니다. 예를 들어 12를 소인수 분해하면 2 * 2 * 3 으로 나타낼 수 있습니다. 따라서 12의 소인수는 2와 3입니다. 자연수 n이 매개변수로 주어질 때 n의 소인수를 오름차순으로 담은 배열을 return하도록 solution 함수를 완성해주세요.

[50일차] 김리연 / 모음 제거 외 3개

---

2st/Riyeon/배열 원소의 길이.py
2st/Riyeon/삼각형의 완성조건 (1).py
2st/Riyeon/점프와 순간 이동.java
2st/Riyeon/중복된 문자 제거.py
2st/Riyeon/카펫.java
2st/Riyeon/컨트롤 제트.py

| 컨트롤 제트 | 프로그래머스 | Level.0 |
| 중복된 문자 제거 | 프로그래머스 | Level.0 |
| 삼각형의 완성조건 (1) | 프로그래머스 | Level.0 |
| 카펫 | 프로그래머스 | Level.2 |
| 점프와 순간 이동 | 프로그래머스 | Level.2 |
<hr/>
- 컨트롤 제트 : 숫자와 "Z"가 공백으로 구분되어 담긴 문자열이 주어집니다. 문자열에 있는 숫자를 차례대로 더하려고 합니다. 이 때 "Z"가 나오면 바로 전에 더했던 숫자를 뺀다는 뜻입니다. 숫자와 "Z"로 이루어진 문자열 s가 주어질 때, 머쓱이가 구한 값을 return 하도록 solution 함수를 완성해보세요.
- 배열 원소의 길이 : 문자열 배열 strlist가 매개변수로 주어집니다. strlist 각 원소의 길이를 담은 배열을 retrun하도록 solution 함수를 완성해주세요.
- 중복된 문자 제거 : 문자열 my_string이 매개변수로 주어집니다. my_string에서 중복된 문자를 제거하고 하나의 문자만 남긴 문자열을 return하도록 solution 함수를 완성해주세요.
- 삼각형의 완성조건 (1) : 삼각형의 세 변의 길이가 담긴 배열 sides이 매개변수로 주어집니다. 세 변으로 삼각형을 만들 수 있다면 1, 만들 수 없다면 2를 return하도록 solution 함수를 완성해주세요.
- 카펫 : Leo는 카펫을 사러 갔다가 아래 그림과 같이 중앙에는 …

[51일차] 김리연 / 컨트롤 제트 외 5개

---

3st/Juhee/나이 출력.java

https://school.programmers.co.kr/learn/courses/30/lessons/120820
<hr/>
- 나이 출력 : 머쓱이는 선생님이 몇 년도에 태어났는지 궁금해졌습니다. 2022년 기준 선생님의 나이 age가 주어질 때, 선생님의 출생 연도를 return 하는 solution 함수를 완성해주세요

[52일차] 최주희 / 나이 출력

---

2st/Riyeon/369게임.py
2st/Riyeon/가까운 수.py
2st/Riyeon/대문자와 소문자.py
2st/Riyeon/암호 해독.py

| 가까운 수 | 프로그래머스 | Level.0 |
| 369게임 | 프로그래머스 | Level.0 |
| 암호 해독 | 프로그래머스 | Level.0 |
<hr/>
- 가까운 수 : 정수 배열 array와 정수 n이 매개변수로 주어질 때, array에 들어있는 정수 중 n과 가장 가까운 수를 return 하도록 solution 함수를 완성해주세요.
- 369게임 : 머쓱이는 친구들과 369게임을 하고 있습니다. 369게임은 1부터 숫자를 하나씩 대며 3, 6, 9가 들어가는 숫자는 숫자 대신 3, 6, 9의 개수만큼 박수를 치는 게임입니다. 머쓱이가 말해야하는 숫자 order가 매개변수로 주어질 때, 머쓱이가 쳐야할 박수 횟수를 return 하도록 solution 함수를 완성해보세요.
- 암호 해독 : 문자열 cipher와 정수 code가 매개변수로 주어질 때 해독된 암호 문자열을 return하도록 solution 함수를 완성해주세요.

[52일차] 김리연 / 가까운 수 외 3개

---

2st/Riyeon/가장 큰 수 찾기.py
2st/Riyeon/약수 구하기.py
2st/Riyeon/영어가 싫어요.py
2st/Riyeon/인덱스 바꾸기.py
2st/Riyeon/편지.py
2st/Riyeon/한 번만 등장한 문자.py

| 영어가 싫어요 | 프로그래머스 | Level.0 |
| 인덱스 바꾸기 | 프로그래머스 | Level.0 |
| 한 번만 등장한 문자 | 프로그래머스 | Level.0 |
<hr/>
- 영어가 싫어요 : 영어가 싫은 머쓱이는 영어로 표기되어있는 숫자를 수로 바꾸려고 합니다. 문자열 numbers가 매개변수로 주어질 때, numbers를 정수로 바꿔 return 하도록 solution 함수를 완성해 주세요.
- 인덱스 바꾸기 : 문자열 my_string과 정수 num1, num2가 매개변수로 주어질 때, my_string에서 인덱스 num1과 인덱스 num2에 해당하는 문자를 바꾼 문자열을 return 하도록 solution 함수를 완성해보세요.
- 한 번만 등장한 문자 : 문자열 s가 매개변수로 주어집니다. s에서 한 번만 등장하는 문자를 사전 순으로 정렬한 문자열을 return 하도록 solution 함수를 완성해보세요. 한 번만 등장하는 문자가 없을 경우 빈 문자열을 return 합니다.
- 편지 : 머쓱이는 할머니께 생신 축하 편지를 쓰려고 합니다. 할머니가 보시기 편하도록 글자 한 자 한 자를 가로 2cm 크기로 …

[53일차] 김리연 / 영어가 싫어요 외 5

---

3st/Juhee/숫자 비교하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/120807
<hr/>

[53일차] 최주희 / 숫자 비교하기

---

2st/Riyeon/OX퀴즈.py
2st/Riyeon/n의 배수 고르기.py
2st/Riyeon/문자열 계산하기.py
2st/Riyeon/배열의 유사도.py
2st/Riyeon/숫자 찾기.py
2st/Riyeon/자릿수 더하기.py

| 문자열 계산하기 | 프로그래머스 | Level.0 |
| n의 배수 고르기 | 프로그래머스 | Level.0 |
| OX퀴즈 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 계산하기 : my_string은 "3 + 5"처럼 문자열로 된 수식입니다. 문자열 my_string이 매개변수로 주어질 때, 수식을 계산한 값을 return 하는 solution 함수를 완성해주세요.
- OX퀴즈 : 덧셈, 뺄셈 수식들이 'X [연산자] Y …

[54일차] 김리연 / 문자열 계산하기 외 5개

---

2st/Riyeon/7의 개수.py
2st/Riyeon/문자열 정렬하기 (2).py
2st/Riyeon/문자열안에 문자열.py
2st/Riyeon/세균 증식.py
2st/Riyeon/잘라서 배열로 저장하기.py
2st/Riyeon/제곱수 판별하기.py

| 제곱수 판별하기 | 프로그래머스 | Level.0 |
| 7의 개수 | 프로그래머스 | Level.0 |
| 잘라서 배열로 저장하기 | 프로그래머스 | Level.0 |
<hr/>
- 제곱수 판별하기 : 어떤 자연수를 제곱했을 때 나오는 정수를 제곱수라고 합니다. 정수 n이 매개변수로 주어질 때, n이 제곱수라면 1을 아니라면 2를 return하도록 solution 함수를 완성해주세요.
- 세균 증식 : 어떤 세균은 1시간에 두배만큼 증식한다고 합니다. 처음 세균의 마리수 n과 경과한 시간 t가 매개변수로 주어질 때 t시간 후 세균의 수를 return하도록 solution 함수를 완성해주세요.
- 7의 개수 : 머쓱이는 행운의 숫자 7을 가장 좋아합니다. 정수 배열 array가 매개변수로 주어질 때, 7이 총 몇 개 있는지 return …

[55일차] 김리연 / 문자열안에 문자열 외 5개

---

2st/Riyeon/다항식 더하기.py
2st/Riyeon/머쓱이보다 키 큰 사람.py
2st/Riyeon/중복된 숫자 개수.py
2st/Riyeon/직사각형 넓이 구하기.py
2st/Riyeon/최댓값 만들기 (2).py
2st/Riyeon/캐릭터의 좌표.py

| 머쓱이보다 키 큰 사람 | 프로그래머스 | Level.0 |
| 직사각형 넓이 구하기 | 프로그래머스 | Level.0 |
| 캐릭터의 좌표 | 프로그래머스 | Level.0 |
| 최댓값 만들기 (2) | 프로그래머스 | Level.0 |
| 다항식 더하기 | 프로그래머스 | Level.0 |
<hr/>
- 머쓱이보다 키 큰 사람 : 머쓱이는 학교에서 키 순으로 줄을 설 때 몇 번째로 서야 하는지 궁금해졌습니다. 머쓱이네 반 친구들의 키가 담긴 정수 배열 array와 머쓱이의 키 height가 매개변수로 주어질 때, 머쓱이보다 키 큰 사람 수를 return 하도록 solution 함수를 완성해보세요.
- 직사각형 넓이 구하기 : 2차원 좌표 평면에 변이 축과 평행한 직사각형이 있습니다. 직사각형 네 꼭짓점의 좌표 [[x1, y1], [x2, y2], [x3, y3], [x4, y4]]가 담겨있는 배열 dots가 매개변수로 주어질 때, 직사각형의 넓이를 return 하도록 solution 함수를 완성해보세요.
- 캐릭터의 좌표 : 머쓱이는 RPG게임을 하고 있습니다. 게임에는 up, down, left, right 방향키가 있으며 각 키를 누르면 위, 아래, 왼쪽, 오른쪽으로 한 칸씩 …

[56일차] 김리연 / 중복된 숫자 개수 외 5개

---

2st/Riyeon/문자열을 정수로 변환하기.py
2st/Riyeon/삼각형의 완성조건 (2).py
2st/Riyeon/숨어있는 숫자의 덧셈 (2).py
2st/Riyeon/안전지대.py
2st/Riyeon/외계어 사전.py
2st/Riyeon/저주의 숫자 3.py
2st/Riyeon/평행.py

| 숨어있는 숫자의 덧셈 (2) | 프로그래머스 | Level.0 |
| 안전지대 | 프로그래머스 | Level.0 |
| 삼각형의 완성조건 (2) | 프로그래머스 | Level.0 |
| 외계어 사전 | 프로그래머스 | Level.0 |
| 저주의 숫자 3 | 프로그래머스 | Level.0 |
| 평행 | 프로그래머스 | Level.0 |
<hr/>
- 숨어있는 숫자의 덧셈 (2) : 문자열 my_string이 매개변수로 주어집니다. my_string은 소문자, 대문자, 자연수로만 구성되어있습니다. my_string안의 자연수들의 합을 return하도록 solution 함수를 완성해주세요.
- 안전지대 : 지뢰는 2차원 배열 board에 1로 표시되어 있고 board에는 지뢰가 매설 된 지역 1과, 지뢰가 없는 지역 0만 존재합니다.
지뢰가 매설된 지역의 지도 board가 매개변수로 주어질 때, 안전한 지역의 칸 수를 return하도록 solution 함수를 완성해주세요.
- 삼각형의 완성조건 (2) : 삼각형의 두 변의 길이가 담긴 배열 sides이 매개변수로 주어집니다. 나머지 한 변이 될 수 있는 정수의 개수를 return하도록 solution 함수를 완성해주세요.
- 외계어 사전 : PROGRAMMERS-962 행성에 불시착한 우주비행사 머쓱이는 외계행성의 언어를 공부하려고 합니다. 알파벳이 담긴 배열 spell과 외계어 사전 dic이 매개변수로 …

[57일차] 김리연 / 숨어있는 숫자의 덧셈 (2) 외 6개

---

2st/Riyeon/겹치는 선분의 길이.py
2st/Riyeon/등수 매기기.py
2st/Riyeon/로그인 성공.py
2st/Riyeon/옹알이 (1).py
2st/Riyeon/유한소수 판별하기.py
2st/Riyeon/특이한 정렬.py

| 겹치는 선분의 길이 | 프로그래머스 | Level.0 |
| 유한소수 판별하기 | 프로그래머스 | Level.0 |
| 특이한 정렬 | 프로그래머스 | Level.0 |
| 등수 매기기 | 프로그래머스 | Level.0 |
| 옹알이 (1) | 프로그래머스 | Level.0 |
| 로그인 성공? | 프로그래머스 | Level.0 |
<hr/>
- 겹치는 선분의 길이 : 선분 3개가 평행하게 놓여 있습니다. 세 선분의 시작과 끝 좌표가 [[start, end], [start, end], [start, end]] 형태로 들어있는 2차원 배열 lines가 매개변수로 주어질 때, 두 개 이상의 선분이 겹치는 부분의 길이를 return 하도록 solution 함수를 완성해보세요.
- 유한소수 판별하기 : 두 정수 a와 b가 매개변수로 주어질 때, a/b가 유한소수이면 1을, 무한소수라면 2를 return하도록 solution 함수를 완성해주세요.
- 특이한 정렬 : 정수 n을 기준으로 n과 가까운 수부터 정렬하려고 합니다. 이때 n으로부터의 거리가 같다면 더 큰 수를 앞에 오도록 배치합니다. 정수가 담긴 배열 numlist와 정수 n이 주어질 때 numlist의 원소를 n으로부터 가까운 순서대로 정렬한 배열을 return하도록 solution 함수를 완성해주세요.
- 등수 매기기 : 영어 점수와 수학 점수의 평균 점수를 기준으로 학생들의 등수를 매기려고 합니다. 영어 점수와 수학 점수를 담은 2차원 정수 배열 score가 주어질 …

[58일차] 김리연 / 겹치는 선분의 길이 외 5개

---

2st/Riyeon/A로 B 만들기.py
2st/Riyeon/k의 개수.py
2st/Riyeon/문자열 밀기.py
2st/Riyeon/이진수 더하기.py
2st/Riyeon/종이 자르기.py
2st/Riyeon/치킨 쿠폰.py

| 치킨 쿠폰 | 프로그래머스 | Level.0 |
| 이진수 더하기 | 프로그래머스 | Level.0 |
| A로 B 만들기 | 프로그래머스 | Level.0 |
| k의 개수 | 프로그래머스 | Level.0 |
| 문자열 밀기 | 프로그래머스 | Level.0 |
| 종이 자르기 | 프로그래머스 | Level.0 |
<hr/>
- 치킨 쿠폰 : 프로그래머스 치킨은 치킨을 시켜먹으면 한 마리당 쿠폰을 한 장 발급합니다. 쿠폰을 열 장 모으면 치킨을 한 마리 서비스로 받을 수 있고, 서비스 치킨에도 쿠폰이 발급됩니다. 시켜먹은 치킨의 수 chicken이 매개변수로 주어질 때 받을 수 있는 최대 서비스 치킨의 수를 return하도록 solution 함수를 완성해주세요.
- 이진수 더하기 : 이진수를 의미하는 두 개의 문자열 bin1과 bin2가 매개변수로 주어질 때, 두 이진수의 합을 return하도록 solution 함수를 완성해주세요.
- A로 B 만들기 : 문자열 before와 after가 매개변수로 주어질 때, before의 순서를 바꾸어 after를 만들 수 있으면 1을, 만들 수 없으면 0을 return 하도록 solution 함수를 완성해보세요.
- k의 개수 : 1부터 13까지의 수에서, 1은 1, 10, 11, 12, 13 이렇게 총 6번 등장합니다. 정수 i, j, k가 매개변수로 주어질 때, i부터 j까지 k가 몇 번 등장하는지 return 하도록 solution 함수를 완성해주세요.
- 문자열 밀기 : …

[59일차] 김리연 / 치킨 쿠폰 외 5개

---

2st/Riyeon/rny_string.py
2st/Riyeon/다음에 올 숫자.py
2st/Riyeon/뒤에서 5등까지.py
2st/Riyeon/배열 비교하기.py
2st/Riyeon/배열의 원소만큼 추가하기.py
2st/Riyeon/연속된 수의 합.py
2st/Riyeon/정수 부분.py

| 연속된 수의 합 | 프로그래머스 | Level.0 |
| 다음에 올 숫자 | 프로그래머스 | Level.0 |
| 정수 부분 | 프로그래머스 | Level.0 |
| 배열 비교하기 | 프로그래머스 | Level.0 |
<hr/>
- 연속된 수의 합 : 연속된 세 개의 정수를 더해 12가 되는 경우는 3, 4, 5입니다. 두 정수 num과 total이 주어집니다. 연속된 수 num개를 더한 값이 total이 될 때, 정수 배열을 오름차순으로 담아 return하도록 solution함수를 완성해보세요.
- 다음에 올 숫자 : 등차수열 혹은 등비수열 common이 매개변수로 주어질 때, 마지막 원소 다음으로 올 숫자를 return 하도록 solution 함수를 완성해보세요.
- 배열 비교하기 : 두 정수 배열 arr1과 arr2가 주어질 때, 위에서 정의한 배열의 대소관계에 대하여 arr2가 크다면 -1, arr1이 …

[60일차] 김리연 / 연속된 수의 합 외 6개

---

2st/Riyeon/A 강조하기.py
2st/Riyeon/공백으로 구분하기 1.py
2st/Riyeon/공백으로 구분하기 2.py
2st/Riyeon/문자열 바꿔서 찾기.py
2st/Riyeon/배열에서 문자열 대소문자 변환하기.py
2st/Riyeon/특정한 문자를 대문자로 바꾸기.py

| 공백으로 구분하기 2 | 프로그래머스 | Level.0 |
| 공백으로 구분하기 1 | 프로그래머스 | Level.0 |
| 특정한 문자를 대문자로 바꾸기 | 프로그래머스 | Level.0 |
<hr/>
- 공백으로 구분하기 2 : 단어가 공백 한 개 이상으로 구분되어 있는 문자열 my_string이 매개변수로 주어질 때, my_string에 나온 단어를 앞에서부터 순서대로 담은 문자열 배열을 return 하는 solution 함수를 작성해 주세요.
- 공백으로 구분하기 1 : 단어가 공백 한 개로 구분되어 있는 문자열 my_string이 매개변수로 주어질 때, my_string에 나온 단어를 앞에서부터 순서대로 담은 문자열 배열을 return 하는 solution 함수를 작성해 주세요.
- 특정한 문자를 대문자로 바꾸기 : 영소문자로 이루어진 문자열 my_string과 영소문자 1글자로 이루어진 문자열 alp가 매개변수로 주어질 때, …

[61일차] 김리연 / 문자열 바꿔서 찾기 외 5개

---

2st/Riyeon/n보다 커질 때까지 더하기.py
2st/Riyeon/길이에 따른 연산.py
2st/Riyeon/대문자로 바꾸기.py
2st/Riyeon/소문자로 바꾸기.py
2st/Riyeon/원하는 문자열 찾기.py
2st/Riyeon/조건에 맞게 수열 변환하기 1.py

| 원하는 문자열 찾기 | 프로그래머스 | Level.0 |
| 길이에 따른 연산 | 프로그래머스 | Level.0 |
| 조건에 맞게 수열 변환하기 1 | 프로그래머스 | Level.0 |
<hr/>
- 원하는 문자열 찾기 : 알파벳으로 이루어진 문자열 myString과 pat이 주어집니다. myString의 연속된 부분 문자열 중 pat이 존재하면 1을 그렇지 않으면 0을 return 하는 solution 함수를 완성해 주세요. 단, 알파벳 대문자와 소문자는 구분하지 않습니다.
- 조건에 맞게 수열 변환하기 1 : 정수 배열 arr가 주어집니다. arr의 각 원소에 대해 값이 50보다 …

[62일차] 김리연 / 소문자로 바꾸기 외 5개

---

2st/Riyeon/5명씩.py
2st/Riyeon/n 번째 원소까지.py
2st/Riyeon/n 번째 원소부터.py
2st/Riyeon/n개 간격의 원소들.py
2st/Riyeon/순서 바꾸기.py
2st/Riyeon/할 일 목록.py

| n 번째 원소부터 | 프로그래머스 | Level.0 |
<hr/>
- n 번째 원소까지 : 정수 리스트 num_list와 정수 n이 주어질 때, num_list의 첫 …

[63일차] 김리연 / 할 일 목록 외 5개

---

2st/Riyeon/문자열의 앞의 n글자.py
2st/Riyeon/배열 만들기 1.py
2st/Riyeon/접두사인지 확인하기.py
2st/Riyeon/접미사인지 확인하기.py
2st/Riyeon/첫 번째로 나오는 음수.py
2st/Riyeon/카운트 다운.py

| 접두사인지 확인하기 | 프로그래머스 | Level.0 |
| 접미사인지 확인하기 | 프로그래머스 | Level.0 |
<hr/>
- 접두사인지 확인하기 : 어떤 문자열에 대해서 접두사는 특정 인덱스까지의 문자열을 의미합니다. 예를 들어, "banana"의 모든 접두사는 "b", "ba", "ban", …

[64일차] 김리연 / 첫 번째로 나오는 음수 외 5개

---

2st/Riyeon/글자 이어 붙여 문자열 만들기.py
2st/Riyeon/마지막 두 원소.py
2st/Riyeon/문자열의 뒤의 n글자.py
2st/Riyeon/부분 문자열 이어 붙여 문자열 만들기.py
2st/Riyeon/수 조작하기 1.py
2st/Riyeon/이어 붙인 수.py

| 글자 이어 붙여 문자열 만들기 | 프로그래머스 | Level.0 |
| 마지막 두 원소 | 프로그래머스 | Level.0 |
<hr/>
- 문자열의 뒤의 n글자 : 문자열 my_string과 정수 n이 매개변수로 주어질 때, my_string의 뒤의 n글자로 이루어진 문자열을 return 하는 solution 함수를 작성해 주세요.
- 부분 문자열 이어 붙여 문자열 만들기 : 길이가 같은 문자열 배열 my_strings와 이차원 정수 배열 parts가 매개변수로 주어집니다. parts[i]는 [s, e] 형태로, my_string[i]의 인덱스 s부터 인덱스 e까지의 부분 문자열을 의미합니다. 각 my_strings의 원소의 parts에 해당하는 부분 문자열을 순서대로 이어 붙인 문자열을 return 하는 solution 함수를 작성해 주세요.
- 글자 이어 붙여 문자열 만들기 : 문자열 my_string과 정수 배열 index_list가 매개변수로 주어집니다. my_string의 index_list의 원소들에 해당하는 인덱스의 글자들을 순서대로 이어 붙인 문자열을 return 하는 solution 함수를 작성해 주세요.
- 수 조작하기 1 : 정수 n과 문자열 …

[65일차] 김리연 / 문자열의 뒤의 n글자 외 5개

---

3st/Juhee/각도기.java
3st/Juhee/공배수.java
3st/Juhee/나머지 구하기.java
3st/Juhee/더 크게 합치기.java
3st/Juhee/두 수의 곱.java
3st/Juhee/두 수의 나눗셈.java
3st/Juhee/두 수의 차.java
3st/Juhee/두 수의 합.java
3st/Juhee/머쓱이보다 키 큰 사람.java
3st/Juhee/몫 구하기.java
3st/Juhee/문자열 돌리기.java
3st/Juhee/배열 만들기 1.java
3st/Juhee/배열의 평균값.java
3st/Juhee/세균 증식.java
3st/Juhee/양꼬치.java
3st/Juhee/중복된 숫자 개수.java
3st/Juhee/짝수의 합.java
3st/Juhee/특수문자 출력하기.java
3st/Juhee/편지.java
3st/Juhee/홀짝에 따라 다른 값 반환하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/120809
| 배열 두배 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 배열 두배 만들기 : 자연수 n이 입력으로 주어졌을 때 만약 n이 짝수이면 "n is even"을, 홀수이면 "n is odd"를 출력하는 코드를 작성해 보세요.

[66일차] 최주희 / 배열 두배 만들기

---

2st/Yeonwoo/k의 개수.py
2st/Yeonwoo/n보다 커질 때까지 더하기.py
2st/Yeonwoo/rny_string.py
2st/Yeonwoo/가위 바위 보.py
2st/Yeonwoo/공배수.py
2st/Yeonwoo/공백으로 구분하기1.py
2st/Yeonwoo/공백으로 구분하기2.py
2st/Yeonwoo/길이에 따른 연산.py
2st/Yeonwoo/대문자로 바꾸기.py
2st/Yeonwoo/문자열 계산하기.py
2st/Yeonwoo/문자열 정렬하기(1).py
2st/Yeonwoo/문자열 정렬하기(2).py
2st/Yeonwoo/삼각형의 완성조건(1).py
2st/Yeonwoo/소문자로 바꾸기.py
2st/Yeonwoo/숫자 찾기.py
2st/Yeonwoo/점의 위치 구하기.py
2st/Yeonwoo/조건에 맞게 수열 변환하기1.py
2st/Yeonwoo/중복된 문자 제거.py
2st/Yeonwoo/첫 번째로 나오는 음수.py
2st/Yeonwoo/특정 문자 제거하기.py

| 특정 문자 제거하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120826) |
| 삼각형의 완성조건(1) | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120889) |
| 점의 위치 구하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120841) |
| 숫자 찾기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120904) |
| 문자열 정렬하기(1) | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120850) |
| 문자열 정렬하기(2) | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120911) |
| 가위 바위 보 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120839) |
| 중복된 문자 제거 | 프로그래머스 | …

[66일차] 채연우 / 특정 문자 제거하기 외 22개

---

2st/Riyeon/더 크게 합치기.py
2st/Riyeon/두 수의 연산값 비교하기.py
2st/Riyeon/문자 리스트를 문자열로 변환하기.py
2st/Riyeon/문자열 곱하기.py
2st/Riyeon/원소들의 곱과 합.py
2st/Riyeon/홀짝에 따라 다른 값 반환하기.py

| 두 수의 연산값 비교하기 | 프로그래머스 | Level.0 |
| 더 크게 합치기 | 프로그래머스 | Level.0 |
<hr/>
- 두 수의 연산값 비교하기 : 연산 ⊕는 두 정수에 대한 연산으로 두 정수를 붙여서 쓴 값을 반환합니다. 양의 정수 a와 b가 주어졌을 때, a ⊕ b와 2 * a * b 중 더 큰 값을 return하는 solution 함수를 완성해 주세요.
- 더 크게 합치기 : 연산 ⊕는 두 정수에 대한 연산으로 두 정수를 붙여서 쓴 값을 반환합니다. 양의 정수 a와 b가 주어졌을 때, a ⊕ b와 b ⊕ a 중 더 큰 값을 return 하는 solution 함수를 완성해 주세요.
- …

[66일차] 김리연 / 원소들의 곱과 합 외 5개

---

3st/Juhee/배열 두배 만들기.java
3st/Juhee/짝수 홀수 개수.java
3st/Juhee/홀짝 구분하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/120824
<hr/>

[67일차] 최주희 / 짝수 홀수 개수

---

2st/Riyeon/x 사이의 개수.py
2st/Riyeon/배열의 원소 삭제하기.py
2st/Riyeon/접미사 배열.py
2st/Riyeon/조건에 맞게 수열 변환하기 3.py
2st/Riyeon/카운트 업.py
2st/Riyeon/홀짝 구분하기.py

| 홀짝 구분하기 | 프로그래머스 | Level.0 |
| x 사이의 개수 | 프로그래머스 | Level.0 |
| 배열의 원소 삭제하기 | 프로그래머스 | Level.0 |
| 접미사 배열 | 프로그래머스 | Level.0 |
| 조건에 맞게 수열 변환하기 3 | 프로그래머스 | Level.0 |
<hr/>
- x 사이의 개수 : 문자열 myString이 주어집니다. myString을 문자 "x"를 기준으로 나눴을 때 나눠진 문자열 각각의 길이를 순서대로 저장한 배열을 return 하는 solution 함수를 완성해 주세요.
- 배열의 원소 삭제하기 : 정수 배열 arr과 delete_list가 있습니다. arr의 원소 중 delete_list의 원소를 모두 삭제하고 남은 원소들은 기존의 arr에 있던 순서를 유지한 배열을 return 하는 solution 함수를 작성해 주세요.
- 접미사 배열 : 어떤 문자열에 대해서 접미사는 특정 인덱스부터 시작하는 문자열을 의미합니다. 예를 들어, "banana"의 모든 접미사는 …

[67일차] 김리연 / 홀짝 구분하기 외 5개

---

2st/Yeonwoo/5명씩.py
2st/Yeonwoo/A 강조하기.py
2st/Yeonwoo/n 번째 원소까지.py
2st/Yeonwoo/n 번째 원소부터.py
2st/Yeonwoo/n개 간격의 원소들.py
2st/Yeonwoo/가까운 1 찾기.py
2st/Yeonwoo/대소문자 바꿔서 출력하기.py
2st/Yeonwoo/뒤에서 5등 위로.py
2st/Yeonwoo/뒤에서 5등까지.py
2st/Yeonwoo/문자열 돌리기.py
2st/Yeonwoo/문자열 바꿔서 찾기.py
2st/Yeonwoo/문자열을 정수로 변환하기.py
2st/Yeonwoo/문자열의 뒤의 n글자.py
2st/Yeonwoo/배열 만들기1.py
2st/Yeonwoo/배열 비교하기.py
2st/Yeonwoo/배열에서 문자열 대소문자 변환하기.py
2st/Yeonwoo/원하는 문자열 찾기.py
2st/Yeonwoo/정수 부분.py
2st/Yeonwoo/카운트 다운.py
2st/Yeonwoo/할 일 목록.py

| 카운트 다운 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181899) |
| 덧셈식 출력하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181947) |
| 9로 나눈 나머지 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181914) |
| 주사위 게임2 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181930) |
| 문자열 출력하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181952) |
| 문자열 반복해서 출력하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181950) |
| 배열 비교하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181856) |
| 문자열을 정수로 변환하기 | 프로그래머스 | …

[68일차] 채연우 / 카운트 다운 외 22개

---

2st/Riyeon/0 떼기.py
2st/Riyeon/꼬리 문자열.py
2st/Riyeon/부분 문자열.py
2st/Riyeon/부분 문자열인지 확인하기.py
2st/Riyeon/정수 찾기.py
2st/Riyeon/홀수 vs 짝수.py

| 홀수 vs 짝수 | 프로그래머스 | Level.0 |
| 정수 찾기 | 프로그래머스 | Level.0 |
| 부분 문자열인지 확인하기 | 프로그래머스 | Level.0 |
| 0 떼기 | 프로그래머스 | Level.0 |
<hr/>
- 꼬리 문자열 : 문자열 리스트 str_list와 제외하려는 문자열 ex가 주어질 때, str_list에서 ex를 포함한 문자열을 제외하고 만든 꼬리 문자열을 return하도록 solution 함수를 완성해주세요.
- 부분 문자열 : 문자열 str1과 str2가 주어질 때, str1이 str2의 부분 문자열이라면 1을 부분 문자열이 아니라면 0을 return하도록 solution 함수를 완성해주세요.
- 정수 찾기 : 정수 리스트 num_list와 찾으려는 정수 n이 주어질 때, num_list안에 n이 있으면 1을 없으면 0을 return하도록 solution 함수를 완성해주세요.
- 부분 문자열인지 확인하기 : 문자열 my_string과 target이 매개변수로 주어질 때, target이 문자열 …

[68일차] 김리연 / 꼬리 문자열 외 5개

---

3st/Juhee/n의 배수 고르기.java
3st/Juhee/아이스 아메리카노.java

https://school.programmers.co.kr/learn/courses/30/lessons/120819
<hr/>

[69일차] 최주희 / 아이스 아메리카노

---

2st/Riyeon/ad 제거하기.py
2st/Riyeon/flag에 따라 다른 값 반환하기.py
2st/Riyeon/뒤에서 5등 위로.py
2st/Riyeon/문자열 정수의 합.py
2st/Riyeon/문자열로 변환.py
2st/Riyeon/배열의 길이에 따라 다른 연산하기.py

| 배열의 길이에 따라 다른 연산하기 | 프로그래머스 | Level.0 |
| 문자열로 변환 | 프로그래머스 | Level.0 |
| 뒤에서 5등 위로 | 프로그래머스 | Level.0 |
| ad 제거하기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열로 변환 : 정수 n이 주어질 때, n을 문자열로 변환하여 return하도록 solution 함수를 완성해주세요.
- 뒤에서 5등 위로 : 정수로 이루어진 리스트 num_list가 주어집니다. num_list에서 가장 작은 5개의 수를 제외한 수들을 오름차순으로 담은 리스트를 return하도록 solution 함수를 완성해주세요.
- 문자열 정수의 합 : 한 자리 정수로 이루어진 문자열 num_str이 …

[69일차] 김리연 / 배열의 길이에 따라 다른 연산하기 외 5개

---

3st/Juhee/옷가게 할인 받기.java

https://school.programmers.co.kr/learn/courses/30/lessons/120818
| 옷가게 할인 받기 | 프로그래머스 | Level.0 |
<hr/>
- 옷가게 할인 받기 : 머쓱이네 옷가게는 10만 원 이상 사면 5%, 30만 원 이상 사면 10%, 50만 원 이상 사면 20%를 할인해줍니다.

[70일차] 최주희 / 옷가게 할인 받기

---

2st/Riyeon/l로 만들기.py
2st/Riyeon/n의 배수.py
2st/Riyeon/문자열 붙여서 출력하기.py
2st/Riyeon/주사위 게임 1.py
2st/Riyeon/콜라츠 수열 만들기.py
2st/Riyeon/특별한 이차원 배열 1.py

| 특별한 이차원 배열 1 | 프로그래머스 | Level.0 |
| 주사위 게임 1 | 프로그래머스 | Level.0 |
| n의 배수 | 프로그래머스 | Level.0 |
| l로 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 특별한 이차원 배열 1 : 정수 n이 매개변수로 주어질 때, 다음과 같은 n × n 크기의 이차원 배열 arr를 return 하는 solution 함수를 작성해 주세요.
- 주사위 게임 1 : 두 정수 a와 b가 매개변수로 주어질 때, 얻는 점수를 return 하는 solution 함수를 작성해 주세요.
- n의 배수 : 정수 num과 n이 매개 변수로 주어질 때, num이 n의 배수이면 1을 return n의 배수가 아니라면 0을 return하도록 solution 함수를 완성해주세요.
- l로 만들기 : 알파벳 소문자로 이루어진 문자열 myString이 주어집니다. 알파벳 순서에서 "l"보다 앞서는 모든 문자를 "l"로 바꾼 문자열을 return 하는 solution 함수를 완성해 주세요.
- 콜라츠 수열 만들기 : 임의의 1,000 보다 작거나 같은 양의 정수 n이 주어질 때 초기값이 n인 콜라츠 수열을 return 하는 solution 함수를 완성해 주세요.
- 문자열 붙여서 출력하기 : 두 개의 문자열 str1, str2가 공백으로 구분되어 입력으로 …

[70일차] 김리연 / 특별한 이차원 배열 1 외 5개

---

3st/Juhee/가장 큰 수 찾기.java

https://school.programmers.co.kr/learn/courses/30/lessons/120899
<hr/>

[71일차] 최주희 / 가장 큰 수 찾기

---

2st/Yeonwoo/가운데 글자 가져오기.py
2st/Yeonwoo/나머지가 1이 되는 수 찾기.py
2st/Yeonwoo/내적.py
2st/Yeonwoo/두 수 비교하기.py
2st/Yeonwoo/등차수열의 특정한 항만 더하기.py
2st/Yeonwoo/문자열 내림차순으로 배치하기.py
2st/Yeonwoo/부족한 금액 계산하기.py
2st/Yeonwoo/사분면 고르기.py
2st/Yeonwoo/삼총사.py
2st/Yeonwoo/순서쌍의 개수.py
2st/Yeonwoo/시험성적.py
2st/Yeonwoo/약수의 개수와 덧셈.py
2st/Yeonwoo/없는 숫자 더하기.py
2st/Yeonwoo/윤년.py
2st/Yeonwoo/음양 더하기.py
2st/Yeonwoo/주사위 세개.py
2st/Yeonwoo/콜라츠 추축.py
2st/Yeonwoo/핸드폰 번호 가리기.py

| 나머지가 1이 되는 수 찾기 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/87389) |
| 음양 더하기 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/76501) |
| 없는 숫자 더하기 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/86051) |
| 내적 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/70128) |
| 삼총사 | 프로그래머스 |[ Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/131705) |
| 두 개 뽑아서 더하기 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/68644) |
| 콜라츠 추측 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/12943) |
| 핸드폰 번호 가리기 | 프로그래머스 | …

[71일차] 채연우 / 나머지가 1이 되는 수 찾기 외 18개 

---

2st/Riyeon/대소문자 바꿔서 출력하기.py
2st/Riyeon/문자열 출력하기.py
2st/Riyeon/배열 만들기 2.py
2st/Riyeon/배열 조각하기.py
2st/Riyeon/전국 대회 선발 고사.py
2st/Riyeon/코드 처리하기.py

| 문자열 출력하기 | 프로그래머스 | Level.0 |
| 배열 조각하기 | 프로그래머스 | Level.0 |
| 코드 처리하기 | 프로그래머스 | Level.0 |
| 배열 만들기 2 | 프로그래머스 | Level.0 |
| 대소문자 바꿔서 출력하기 | 프로그래머스 | Level.0 |
| 전국 대회 선발 고사 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 출력하기 : 문자열 str이 주어질 때, str을 출력하는 코드를 작성해 보세요.
- 배열 조각하기 : 정수 배열 arr와 query가 주어집니다. query를 순회하면서 작업을 마친 후 남은 arr의 부분 배열을 return 하는 solution 함수를 완성해 주세요.
- 코드 처리하기 : 문자열 code를 통해 만들어진 문자열 ret를 return 하는 solution 함수를 완성해 주세요.
- 배열 만들기 2 : 정수 l과 r이 주어졌을 때, l 이상 r이하의 정수 중에서 숫자 "0"과 "5"로만 이루어진 모든 정수를 오름차순으로 저장한 배열을 return 하는 solution 함수를 완성해 주세요.
- 대소문자 바꿔서 출력하기 : 영어 알파벳으로 이루어진 문자열 str이 주어집니다. 각 알파벳을 대문자는 소문자로 소문자는 대문자로 변환해서 출력하는 코드를 작성해 보세요.
- 전국 대회 선발 고사 : 각 학생들의 선발 고사 등수를 담은 정수 배열 rank와 전국 대회 참여 가능 여부가 담긴 boolean 배열 attendance가 매개변수로 …

[71일차] 김리연 / 문자열 출력하기 외 5개

---

2st/Yeonwoo/0 떼기.py
2st/Yeonwoo/1로 만들기.py
2st/Yeonwoo/다음에 올 숫자.py
2st/Yeonwoo/로그인 성공.py
2st/Yeonwoo/직각삼각형 출력하기.py
2st/Yeonwoo/코드 처리하기.py
2st/Yeonwoo/콜라츠 수열 만들기.py

| 다음에 올 숫자 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120924) |
| 1로 만들기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181880) |
| 콜라츠 수열 만들기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181919) |
| 로그인 성공? | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120883) |
| 직각삼격형 출력하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120823) |
| 0 떼기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181847) |
| 코드 처리하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181932) |
<hr/>
- 다음에 올 숫자 : 등차수열 혹은 등비수열 common이 매개변수로 주어질 때, 마지막 …

[72일차] 채연우 / 다음에 나올 숫자 외 6개

---

3st/Juhee/직각삼각형 출력하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/120823
| 직각삼각형 출력하기 | 프로그래머스 | Level.0 |
<hr/>
- 직각삼각형 출력하기 : "*"의 높이와 너비를 1이라고 했을 때, "*"을 이용해 직각 이등변 삼각형을 그리려고합니다. 정수 n 이 주어지면 높이와 너비가 n 인 직각 이등변 삼각형을 출력하도록 코드를 작성해보세요.

[72일차] 최주희 / 직각삼각형 출력하기

---

2st/Riyeon/a와 b 출력하기.py
2st/Riyeon/그림 확대.py
2st/Riyeon/무작위로 K개의 수 뽑기.py
2st/Riyeon/문자열 겹쳐쓰기.py
2st/Riyeon/수열과 구간 쿼리 2.py
2st/Riyeon/정사각형으로 만들기.py

| 그림 확대 | 프로그래머스 | Level.0 |
| 문자열 겹쳐쓰기 | 프로그래머스 | Level.0 |
| 정사각형으로 만들기 | 프로그래머스 | Level.0 |
| 수열과 구간 쿼리 2 | 프로그래머스 | Level.0 |
| 무작위로 K개의 수 뽑기 | 프로그래머스 | Level.0 |
<hr/>
- 그림 확대 : 직사각형 형태의 그림 파일이 있고, 이 그림 파일은 1 × 1 크기의 정사각형 크기의 픽셀로 이루어져 있습니다. 이 그림 파일을 나타낸 문자열 배열 picture과 정수 k가 매개변수로 주어질 때, 이 그림 파일을 가로 세로로 k배 늘린 그림 파일을 나타내도록 문자열 배열을 return 하는 solution 함수를 작성해 주세요.
- 문자열 겹쳐쓰기 : 문자열 my_string, overwrite_string과 정수 s가 주어집니다. 문자열 my_string의 인덱스 s부터 overwrite_string의 길이만큼을 문자열 overwrite_string으로 바꾼 문자열을 return 하는 solution 함수를 작성해 주세요.
- a와 b 출력하기 : 정수 a와 b가 주어집니다. 각 수를 입력받아 입출력 예와 같은 형식으로 출력하는 코드를 작성해 보세요.
- 정사각형으로 만들기 : 이차원 정수 배열 arr이 매개변수로 주어집니다. arr의 행의 수가 더 많다면 열의 수가 행의 수와 같아지도록 각 행의 끝에 0을 추가하고, 열의 수가 더 많다면 …

[72일차] 김리연 / 그림 확대 외 5개

---

3st/Juhee/주사위의 개수.java

https://school.programmers.co.kr/learn/courses/30/lessons/120845
| 주사위의 개수 | 프로그래머스 | Level.0 |
<hr/>
- 주사위의 개수 : 머쓱이는 직육면체 모양의 상자를 하나 가지고 있는데 이 상자에 정육면체 모양의 주사위를 최대한 많이 채우고 싶습니다. 상자의 가로, 세로, 높이가 저장되어있는 배열 box와 주사위 모서리의 길이 정수 n이 매개변수로 주어졌을 때, 상자에 들어갈 수 있는 주사위의 최대 개수를 return 하도록 solution 함수를 완성해주세요.

[73일차] 최주희 / 주사위의 개수

---

2st/Riyeon/조건 문자열.py

| 조건 문자열 | 프로그래머스 | Level.0 |
<hr/>
- 조건 문자열 : 두 문자열 ineq와 eq가 주어집니다. ineq는 "<"와 ">"중 하나고, eq는 "="와 "!"중 하나입니다. 그리고 두 정수 n과 m이 주어질 때, n과 m이 ineq와 eq의 조건에 맞으면 1을 아니면 0을 return하도록 solution 함수를 완성해주세요.

[73일차] 김리연 /  조건 문자열

---

2st/Yeonwoo/PCCE 기출문제 가습기.py
2st/Yeonwoo/PCCE 기출문제 가채점.py
2st/Yeonwoo/PCCE 기출문제 나이 계산.py
2st/Yeonwoo/PCCE 기출문제 산책.py
2st/Yeonwoo/PCCE 기출문제 저축.py
2st/Yeonwoo/PCCE 기출문제 창고 정리.py
2st/Yeonwoo/PCCE 기출문제 출력.py
2st/Yeonwoo/PCCE 기출문제 피타고라스의 정리.py
2st/Yeonwoo/배열의 원소 삭제하기.py
2st/Yeonwoo/전국 대회 선발 고사.py
2st/Yeonwoo/종이 자르기.py

| 리스트 자르기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181897) |
| 배열의 원소 삭제하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181844) |
| OX퀴즈 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120907) |
| 종이 자르기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120922) |
| 전국 대회 선발 고사 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181851) |
| PCCE 기출문제 출력 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/250133) |
| PCCE 기출문제 피타고라스의 정리 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/250132) |
| PCCE 기출문제 나이 계산 | 프로그래머스 | …

[74일차] 채연우 / 리스트 자르기 외 12개

---

3st/Juhee/최댓값 만들기 (1).java

https://school.programmers.co.kr/learn/courses/30/lessons/120847
| 최댓값 만들기 (1) | 프로그래머스 | Level.0 |
<hr/>
- 최댓값 만들기 (1) : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소 중 두 개를 곱해 만들 수 있는 최댓값을 return하도록 solution 함수를 완성해주세요.

[74일차] 최주희 / 최댓값 만들기 (1)

---

3st/Juhee/개미 군단.java

https://school.programmers.co.kr/learn/courses/30/lessons/120837
<hr/>
- 개미 군단 : 개미 군단이 사냥을 나가려고 합니다. 개미군단은 사냥감의 체력에 딱 맞는 병력을 데리고 나가려고 합니다. 장군개미는 5의 공격력을, 병정개미는 3의 공격력을 일개미는 1의 공격력을 가지고 있습니다. 예를 들어 체력 23의 여치를 사냥하려고 할 때, 일개미 23마리를 데리고 가도 되지만, 장군개미 네 마리와 병정개미 한 마리를 데리고 간다면 더 적은 병력으로 사냥할 수 있습니다. 사냥감의 체력 hp가 매개변수로 주어질 때, 사냥감의 체력에 딱 맞게 최소한의 병력을 구성하려면 몇 마리의 개미가 필요한지를 return하도록 solution 함수를 완성해주세요.

[75일차] 최주희 / 개미 군단

---

2st/Riyeon/괄호 회전하기.java

| 괄호 회전하기 | 프로그래머스 | Level.2 |
<hr/>
- 괄호 회전하기 : 대괄호, 중괄호, 그리고 소괄호로 이루어진 문자열 s가 매개변수로 주어집니다. 이 s를 왼쪽으로 x (0 ≤ x < (s의 길이)) 칸만큼 회전시켰을 때 s가 올바른 괄호 문자열이 되게 하는 x의 개수를 return 하도록 solution 함수를 완성해주세요.

[75일차] 김리연 / 괄호 회전하기

---

2st/Yeonwoo/날짜 비교하기.py
2st/Yeonwoo/수 조작하기 2.py
2st/Yeonwoo/순서 바꾸기.py
2st/Yeonwoo/추억 점수.py

| 빈 배열에 추가, 삭제하기| 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181860) |
<hr/>
- 빈 배열에 추가, 삭제하기 : 아무 원소도 들어있지 않은 빈 배열 X가 있습니다. 길이가 같은 정수 배열 arr과 boolean 배열 flag가 매개변수로 주어질 때, flag를 차례대로 순회하며 flag[i]가 true라면 X의 뒤에 arr[i]를 arr[i] × 2 번 추가하고, flag[i]가 false라면 X에서 마지막 arr[i]개의 원소를 제거한 뒤 X를 return 하는 solution 함수를 작성해 주세요.

[75일차] 채연우 / 빈 배열에 추가, 삭제하기

---

2st/Yeonwoo/2차원으로 만들기.py
2st/Yeonwoo/qr code.py
2st/Yeonwoo/간단한 논리 연산.py
2st/Yeonwoo/부분 문자열 이어 붙여 문자열 만들기.py

| 추억 점수 | 프로그래머스 | [Level.1](https://school.programmers.co.kr/learn/courses/30/lessons/176963) |
| 순서 바꾸기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181891) |
| 수 조작하기 2 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181925) |
| 날짜 비교하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181838) |
| qr code | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181903) |
| 간단한 논리 연산 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181917) |
| 부분 문자열 이어 붙여 문자열 만들기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181911) |
| 2차원 배열로 만들기 | 프로그래머스 | …

[76일차] 채연우 / 추억 점수 외 7개

---

3st/Juhee/369게임.java

https://school.programmers.co.kr/learn/courses/30/lessons/120891
| 369게임 | 프로그래머스 | Level.0 |
<hr/>
- 369게임 : 머쓱이는 친구들과 369게임을 하고 있습니다. 369게임은 1부터 숫자를 하나씩 대며 3, 6, 9가 들어가는 숫자는 숫자 대신 3, 6, 9의 개수만큼 박수를 치는 게임입니다. 머쓱이가 말해야하는 숫자 order가 매개변수로 주어질 때, 머쓱이가 쳐야할 박수 횟수를 return 하도록 solution 함수를 완성해보세요.

[77일차] 최주희 / 369게임

---

2st/Yeonwoo/배열 만들기 2.py
2st/Yeonwoo/배열 만들기 3.py
2st/Yeonwoo/배열 조각하기.py
2st/Yeonwoo/배열 회전시키기.py
2st/Yeonwoo/외계어 사전.py
2st/Yeonwoo/이진수 더하기.py
2st/Yeonwoo/커피 심부름.py

| 배열 조각하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181893) |
| 커피 심부름 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181837) |
| 배열 만들기 3 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181895) |
| 배열 만들기 2 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181921) |
| 배열 회전시키기 | 프로그래머스 | [Level.0 ](https://school.programmers.co.kr/learn/courses/30/lessons/120844)|
| 이진수 더하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120885) |
| 외계어 사전 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120869) |
<hr/>
- 배열 조각하기 : 정수 배열 arr와 query가 주어집니다.
query를 순회하면서 다음 …

[77일차] 채연우 / 배열 조각하기 외 6개

---

2st/Riyeon/영어 끝말잇기.java

| 영어 끝말잇기 | 프로그래머스 | Level.2 |
<hr/>
- 영어 끝말잇기 : 사람의 수 n과 사람들이 순서대로 말한 단어 words 가 매개변수로 주어질 때, 가장 먼저 탈락하는 사람의 번호와 그 사람이 자신의 몇 번째 차례에 탈락하는지를 구해서 return 하도록 solution 함수를 완성해주세요.

[77일차] 김리연 / 영어 끝말잇기

---

3st/Juhee/문자 반복 출력하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/120825
<hr/>

[78일차] 최주희 / 문자 반복 출력하기

---

2st/Riyeon/예상 대진표.java

| 예상 대진표 | 프로그래머스 | Level.2 |
<hr/>
- 예상 대진표 : △△ 게임대회가 개최되었습니다. 이 대회는 N명이 참가하고, 토너먼트 형식으로 진행됩니다. N명의 참가자는 각각 1부터 N번을 차례대로 배정받습니다. 그리고, 1번↔2번, 3번↔4번, ... , N-1번↔N번의 참가자끼리 게임을 진행합니다. 각 게임에서 이긴 사람은 다음 라운드에 진출할 수 있습니다. 이때, 다음 라운드에 진출할 참가자의 번호는 다시 1번부터 N/2번을 차례대로 배정받습니다. 만약 1번↔2번 끼리 겨루는 게임에서 2번이 승리했다면 다음 라운드에서 1번을 부여받고, 3번↔4번에서 겨루는 게임에서 3번이 승리했다면 다음 라운드에서 2번을 부여받게 됩니다. 게임은 최종 한 명이 남을 때까지 진행됩니다. 
이때, 처음 라운드에서 A번을 가진 참가자는 경쟁자로 생각하는 B번 참가자와 몇 번째 라운드에서 만나는지 궁금해졌습니다. 게임 참가자 수 N, 참가자 번호 A, 경쟁자 번호 B가 함수 solution의 매개변수로 주어질 때, 처음 라운드에서 A번을 가진 참가자는 경쟁자로 생각하는 B번 참가자와 몇 번째 라운드에서 만나는지 return 하는 solution 함수를 완성해 주세요. 단, A번 참가자와 B번 참가자는 서로 붙게 되기 전까지 항상 이긴다고 가정합니다.

[78일차] 김리연 / 예상 대진표

---

2st/Yeonwoo/l로 만들기.py
2st/Yeonwoo/배열 만들기 4.py
2st/Yeonwoo/배열로 만들기 5.py
2st/Yeonwoo/잘라서 배열로 저장하기.py

| 잘라서 배열로 저장하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120913) |
| l로 만들기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181834) |
| 배열 만들기 4 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181918) |
| 배열 만들기 5 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181912) |
| 배열 만들기 6 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181859) |
<hr/>
- 잘라서 배열로 저장하기 : 문자열 my_str과 n이 매개변수로 주어질 때, my_str을 길이 n씩 잘라서 저장한 배열을 return하도록 solution 함수를 완성해주세요.
- l로 만들기 : 알파벳 소문자로 이루어진 문자열 myString이 주어집니다. 알파벳 순서에서 "l"보다 앞서는 모든 문자를 "l"로 바꾼 문자열을 return 하는 solution 함수를 완성해 주세요.
- 배열 만들기 4 : 정수 배열 arr가 …

[78일차] 채연우 잘라서 배열로 저장하기 외 4개

---

3st/Juhee/배열 뒤집기.java

https://school.programmers.co.kr/learn/courses/30/lessons/120821
| 배열 뒤집기 | 프로그래머스 | Level.0 |
<hr/>
- 배열 뒤집기 : 정수가 들어 있는 배열 num_list가 매개변수로 주어집니다. num_list의 원소의 순서를 거꾸로 뒤집은 배열을 return하도록 solution 함수를 완성해주세요.

[79일차] 최주희 / 배열 뒤집기

---

2st/Yeonwoo/무작위로 K개의 수 뽑기.py
2st/Yeonwoo/문자열 묶기.py
2st/Yeonwoo/문자열 여러 번 뒤집기.py
2st/Yeonwoo/이차원 배열 대각선 순회하기.py
2st/Yeonwoo/접미사 배열.py
2st/Yeonwoo/특별한 이차원 배열 2.py
2st/Yeonwoo/특이한 이차원 배열 1.py
2st/Yeonwoo/특정 문자열로 끝나는 가장 긴 부분 문자열 찾기.py

| 무작위로 K개의 수 뽑기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181858) |
| 접미사 배열 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181909) |
| 특별한 이차원 배열 1 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181833) |
| 특별한 이차원 배열 2 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181831) |
| 이차원 배열 대각선 순회하기 | 프로그래머스 | Level.0 |
| 특정 문자열로 끝나는 가장 긴 부분 문자열 찾기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181872) |
| 문자열 묶기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181855) |
| 문자열 여러 번 뒤집기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/l …

[79일차] 채연우 / 무작위로 K개의 수 뽑기 외 7개

---

2st/Riyeon/n^2 배열 자르기.java

| n^2 배열 자르기 | 프로그래머스 | Level.2 |
<hr/>
- n^2 배열 자르기 : 정수 n, left, right가 주어집니다. 다음 과정을 거쳐서 1차원 배열을 만들고자 합니다.
n행 n열 크기의 비어있는 2차원 배열을 만듭니다.
i = 1, 2, 3, ..., n에 대해서, 다음 과정을 반복합니다.
1행 1열부터 i행 i열까지의 영역 내의 모든 빈 칸을 숫자 i로 채웁니다.
1행, 2행, ..., n행을 잘라내어 모두 이어붙인 새로운 1차원 배열을 만듭니다.
새로운 1차원 배열을 arr이라 할 때, arr[left], arr[left+1], ..., arr[right]만 남기고 나머지는 지웁니다.
정수 n, left, right가 매개변수로 주어집니다. 주어진 과정대로 만들어진 1차원 배열을 return 하도록 solution 함수를 완성해주세요.

[79일차] 김리연 /  n^2 배열 자르기

---

2st/Riyeon/귤 고르기.java

| 귤 고르기 | 프로그래머스 | Level.2 |
<hr/>
- 귤 고르기 : 경화는 과수원에서 귤을 수확했습니다. 경화는 수확한 귤 중 'k'개를 골라 상자 하나에 담아 판매하려고 합니다. 그런데 수확한 귤의 크기가 일정하지 않아 보기에 좋지 않다고 생각한 경화는 귤을 크기별로 분류했을 때 서로 다른 종류의 수를 최소화하고 싶습니다.
예를 들어, 경화가 수확한 귤 8개의 크기가 [1, 3, 2, 5, 4, 5, 2, 3] 이라고 합시다. 경화가 귤 6개를 판매하고 싶다면, 크기가 1, 4인 귤을 제외한 여섯 개의 귤을 상자에 담으면, 귤의 크기의 종류가 2, 3, 5로 총 3가지가 되며 이때가 서로 다른 종류가 최소일 때입니다.
경화가 한 상자에 담으려는 귤의 개수 k와 귤의 크기를 담은 배열 tangerine이 매개변수로 주어집니다. 경화가 귤 k개를 고를 때 크기가 서로 다른 종류의 수의 최솟값을 return 하도록 solution 함수를 작성해주세요.

[80일차] 김리연 / 귤 고르기

---

2st/Yeonwoo/문자열이 몇 번 등장하는지 세기.py
2st/Yeonwoo/세로 읽기.py
2st/Yeonwoo/행렬의 덧셈.py

| 세로 읽기 | 프로그래머스 | [Level.0 ](https://school.programmers.co.kr/learn/courses/30/lessons/181904)|
| 행렬의 덧셈 | 프로그래머스 | [Level.0 ](https://school.programmers.co.kr/learn/courses/30/lessons/12950)|
| 문자열이 몇 번 등장하는지 세기 | 프로그래머스 | [Level.0 ](https://school.programmers.co.kr/learn/courses/30/lessons/181871)|
<hr/>
- 세로 일기 : 문자열 my_string과 두 정수 m, c가 주어집니다. my_string을 한 줄에 m 글자씩 가로로 적었을 때 왼쪽부터 세로로 c번째 열에 적힌 글자들을 문자열로 return 하는 solution 함수를 작성해 주세요.
- 행렬의 덧셈 : 행렬의 덧셈은 행과 열의 크기가 같은 두 행렬의 같은 행, 같은 열의 값을 서로 더한 결과가 됩니다. 2개의 행렬 arr1과 arr2를 입력받아, 행렬 덧셈의 결과를 반환하는 함수, solution을 완성해주세요.
- 문자열이 몇 번 등장하는지 세기 : 문자열 myString과 pat이 주어집니다. myString에서 pat이 등장하는 횟수를 return 하는 solution 함수를 완성해 주세요.

[80일차] 채연우 / 세로 일기 외 2개

---

2st/Yeonwoo/소인수분해.py

| 소인수분해 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120852) |
<hr/>
- 소인수분 : 소인수분해란 어떤 수를 소수들의 곱으로 표현하는 것입니다. 예를 들어 12를 소인수 분해하면 2 * 2 * 3 으로 나타낼 수 있습니다. 따라서 12의 소인수는 2와 3입니다. 자연수 n이 매개변수로 주어질 때 n의 소인수를 오름차순으로 담은 배열을 return하도록 solution 함수를 완성해주세요.

[81일차] 채연우 / 소인수분해

---

2st/Riyeon/구명보트.java

| 구명보트 | 프로그래머스 | Level.2 |
<hr/>
- 구명보트 : 무인도에 갇힌 사람들을 구명보트를 이용하여 구출하려고 합니다. 구명보트는 작아서 한 번에 최대 2명씩 밖에 탈 수 없고, 무게 제한도 있습니다.
예를 들어, 사람들의 몸무게가 [70kg, 50kg, 80kg, 50kg]이고 구명보트의 무게 제한이 100kg이라면 2번째 사람과 4번째 사람은 같이 탈 수 있지만 1번째 사람과 3번째 사람의 무게의 합은 150kg이므로 구명보트의 무게 제한을 초과하여 같이 탈 수 없습니다.
구명보트를 최대한 적게 사용하여 모든 사람을 구출하려고 합니다. 사람들의 몸무게를 담은 배열 people과 구명보트의 무게 제한 limit가 매개변수로 주어질 때, 모든 사람을 구출하기 위해 필요한 구명보트 개수의 최솟값을 return 하도록 solution 함수를 작성해주세요.

[81일차] 김리연 / 구명보트

---

3st/Juhee/가위 바위 보.java
3st/Juhee/최댓값 만들기 (2).java

https://school.programmers.co.kr/learn/courses/30/lessons/120862
| 최댓값 만들기 (2) | 프로그래머스 | Level.0 |
<hr/>
- 최댓값 만들기 (2) : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소 중 두 개를 곱해 만들 수 있는 최댓값을 return하도록 solution 함수를 완성해주세요.

[82일차] 최주희 / 최댓값 만들기 (2)

---

2st/Riyeon/할인 행사.java

| 할인 행사 | 프로그래머스 | Level.2 |
<hr/>
- 할인 행사 : XYZ 마트는 일정한 금액을 지불하면 10일 동안 회원 자격을 부여합니다. XYZ 마트에서는 회원을 대상으로 매일 한 가지 제품을 할인하는 행사를 합니다. 할인하는 제품은 하루에 하나씩만 구매할 수 있습니다. 알뜰한 정현이는 자신이 원하는 제품과 수량이 할인하는 날짜와 10일 연속으로 일치할 경우에 맞춰서 회원가입을 하려 합니다.
예를 들어, 정현이가 원하는 제품이 바나나 3개, 사과 2개, 쌀 2개, 돼지고기 2개, 냄비 1개이며, XYZ 마트에서 14일간 회원을 대상으로 할인하는 제품이 날짜 순서대로 치킨, 사과, 사과, 바나나, 쌀, 사과, 돼지고기, 바나나, 돼지고기, 쌀, 냄비, 바나나, 사과, 바나나인 경우에 대해 알아봅시다. 첫째 날부터 열흘 간에는 냄비가 할인하지 않기 때문에 첫째 날에는 회원가입을 하지 않습니다. 둘째 날부터 열흘 간에는 바나나를 원하는 만큼 할인구매할 수 없기 때문에 둘째 날에도 회원가입을 하지 않습니다. 셋째 날, 넷째 날, 다섯째 날부터 각각 열흘은 원하는 제품과 수량이 일치하기 때문에 셋 중 하루에 회원가입을 하려 합니다.
정현이가 원하는 제품을 나타내는 문자열 배열 want와 정현이가 원하는 제품의 수량을 나타내는 정수 배열 number, XYZ 마트에서 할인하는 제품을 나타내는 문자열 배열 discount가 주어졌을 때, 회원등록시 정현이가 원하는 제품을 모두 할인 받을 수 있는 회원등록 날짜의 총 …

[82일차] 김리연 / 할인 행사

---

2st/Yeonwoo/영어가 싫어요.py
2st/Yeonwoo/주사위 게임 3.py

| 주사위 게임 3 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181916) |
| 영어가 싫어요 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120894) |
<hr/>
- 주사위 게임 3 : 1부터 6까지 숫자가 적힌 주사위가 네 개 있습니다. 네 주사위를 굴렸을 때 나온 숫자에 따라 다음과 같은 점수를 얻습니다.
네 주사위에서 나온 숫자가 모두 p로 같다면 1111 × p점을 얻습니다.
세 주사위에서 나온 숫자가 p로 같고 나머지 다른 주사위에서 나온 숫자가 q(p ≠ q)라면 (10 × p + q)2 점을 얻습니다.
주사위가 두 개씩 같은 값이 나오고, 나온 숫자를 각각 p, q(p ≠ q)라고 한다면 (p + q) × |p - q|점을 얻습니다.
어느 두 주사위에서 나온 숫자가 p로 같고 나머지 두 주사위에서 나온 숫자가 각각 p와 다른 q, r(q ≠ r)이라면 q × r점을 얻습니다.
네 주사위에 적힌 숫자가 모두 다르다면 나온 숫자 중 가장 작은 숫자 만큼의 점수를 얻습니다.
네 주사위를 굴렸을 때 나온 숫자가 정수 매개변수 a, b, c, d로 주어질 때, 얻는 점수를 return 하는 solution 함수를 작성해 주세요.
- 영어가 싫어요 : 영어가 싫은 머쓱이는 영어로 표기되어있는 숫자를 수로 바꾸려고 합니다. …

[82일차] 채연우 / 주사위 게임 3 외 1개

---

2st/Yeonwoo/순열과 구간 쿼리 1.py

| 순열과 구간 쿼리 1 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181883) |
<hr/>
- 순열과 구간 쿼리 1 : 정수 배열 arr와 2차원 정수 배열 queries이 주어집니다. queries의 원소는 각각 하나의 query를 나타내며, [s, e] 꼴입니다.

[83일차] 채연우 / 순열과 구간 쿼리 1

---

2st/Riyeon/행렬의 곱셈.java

| 행렬의 곱셈 | 프로그래머스 | Level.2 |
<hr/>
- 행렬의 곱셈 : 2차원 행렬 arr1과 arr2를 입력받아, arr1에 arr2를 곱한 결과를 반환하는 함수, solution을 완성해주세요.

[83일차] 김리연 / 행렬의 곱셈

---

3st/Jaeyoung/1998년생인 내가 태국에서는 2541년생.cs
3st/Jaeyoung/A%B.cs
3st/Jaeyoung/A+B.cs
3st/Jaeyoung/A-B.cs
3st/Jaeyoung/AxB.cs
3st/Jaeyoung/Hello World.cs
3st/Jaeyoung/QQE.cs
3st/Jaeyoung/강아지.cs
3st/Jaeyoung/고양이.cs
3st/Jaeyoung/곱셈.cs
3st/Jaeyoung/꼬마 정민.cs
3st/Jaeyoung/나머지.cs
3st/Jaeyoung/사칙연산.cs

https://www.acmicpc.net/problem/10172
| 개 | 백준 | 브론즈 |
<hr/>
- 개 : 아래 예제와 같이 개를 출력하시오.

[84일] 박재영 / 개 외 11개

---

2st/Yeonwoo/순열과 구간 쿼리 2.py

| 순열과 구간 쿼리 2 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181923) |
<hr/>
- 순열과 구간 쿼리 2 : 정수 배열 arr와 2차원 정수 배열 queries이 주어집니다. queries의 원소는 각각 하나의 query를 나타내며, [s, e, k] 꼴입니다.
각 query마다 순서대로 s ≤ i ≤ e인 모든 i에 대해 k보다 크면서 가장 작은 arr[i]를 찾습니다.
각 쿼리의 순서에 맞게 답을 저장한 배열을 반환하는 solution 함수를 완성해 주세요.
단, 특정 쿼리의 답이 존재하지 않으면 -1을 저장합니다.

[84일차] 채연우 / 순열과 구간 쿼리 2

---

2st/Riyeon/의상.java

| 의상 | 프로그래머스 | Level.2 |
<hr/>
- 의상 : 코니가 가진 의상들이 담긴 2차원 배열 clothes가 주어질 때 서로 다른 옷의 조합의 수를 return 하도록 solution 함수를 작성해주세요.

[84일차] 김리연 / 의상

---

3st/Jaeyoung/사분면 고르기.cs
3st/Jaeyoung/시험 성적.cs
3st/Jaeyoung/알람 시계.cs
3st/Jaeyoung/윤년.cs

| 알람 시계 | 백준 | 브론즈 3 |
| 사분면 고르기 | 백준 | 브론즈 5 |
| 윤년 | 백준 | 브론즈 5 |
| 시험 성적 | 백준 | 브론즈 5 |
<hr/>
- 알람 시계 : 상근이는 매일 아침 알람을 듣고 일어난다. 알람을 듣고 바로 일어나면 다행이겠지만, 항상 조금만 더 자려는 마음 때문에 매일 학교를 지각하고 있다.
상근이는 모든 방법을 동원해보았지만, 조금만 더 자려는 마음은 그 어떤 것도 없앨 수가 없었다.
이런 상근이를 불쌍하게 보던 창영이는 자신이 사용하는 방법을 추천해 주었다.
바로 "45분 일찍 알람 설정하기"이다.
이 방법은 단순하다. 원래 설정되어 있는 알람을 45분 앞서는 시간으로 바꾸는 것이다. 어차피 알람 소리를 들으면, 알람을 끄고 조금 더 잘 것이기 때문이다. 이 방법을 사용하면, 매일 아침 더 잤다는 기분을 느낄 수 있고, 학교도 지각하지 않게 된다.
현재 상근이가 설정한 알람 시각이 주어졌을 때, 창영이의 방법을 사용한다면, 이를 언제로 고쳐야 하는지 구하는 프로그램을 작성하시오.
- 사분면 고르기 : 흔한 수학 문제 중 하나는 주어진 점이 어느 사분면에 속하는지 알아내는 것이다. 사분면은 아래 그림처럼 1부터 4까지 번호를 갖는다. "Quadrant n"은 "제n사분면"이라는 뜻이다.
예를 들어, 좌표가 (12, 5)인 점 A는 x좌표와 y좌표가 모두 양수이므로 제1사분면에 속한다. 점 B는 x좌표가 음수이고 y좌표가 양수이므로 제2사분면에 속한다.
점의 좌표를 입력받아 그 …

[85일차] 박재영 / 알람 시계 외 3개

---

3st/Jaehee/두 수의 곱.java

| 두 수의 곱 |  프로그래머스 | Level.0 |
<hr/>
- 두 수의 곱 : 정수 num1, num2가 매개변수 주어집니다. num1과 num2를 곱한 값을 return 하도록 solution 함수를 완성해주세요.

[85일차] 이제희 / 두 수의 곱

---

3st/Seojun/두 수의 합,java

| 두 수의 합 | 프로그래머스 | Level.0 |
<hr/>
- 두 수의 합 : 정수 num1과 num2가 주어질 때, num1과 num2의 합을 return하도록 soltuion 함수를 완성해주세요.

[85일차] 김서준 / 두 수의 합

---

2st/Yeonwoo/수열과 구간 쿼리 3.py

| 수열과 구간 쿼리 3 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181924) |
<hr/>
- 수열과 구간 쿼리 3 : 정수 배열 arr와 2차원 정수 배열 queries이 주어집니다. queries의 원소는 각각 하나의 query를 나타내며, [i, j] 꼴입니다.
각 query마다 순서대로 arr[i]의 값과 arr[j]의 값을 서로 바꿉니다.

[85일차] 채연우 / 수열과 구간 쿼리 3

---

3st/Juhee/삼각형의 완성조건 (1).java
3st/Juhee/약수 구하기.java
3st/Juhee/피자 나눠 먹기 (3).java

https://school.programmers.co.kr/learn/courses/30/lessons/120897
<hr/>

[85일차] 최주희 / 약수 구하기

---

2st/Riyeon/H-Index.java

| H-Index | 프로그래머스 | Level.2 |
<hr/>
- H-Index : H-Index는 과학자의 생산성과 영향력을 나타내는 지표입니다. 어느 과학자의 H-Index를 나타내는 값인 h를 구하려고 합니다. 위키백과에 따르면, H-Index는 다음과 같이 구합니다.
어떤 과학자가 발표한 논문 n편 중, h번 이상 인용된 논문이 h편 이상이고 나머지 논문이 h번 이하 인용되었다면 h의 최댓값이 이 과학자의 H-Index입니다.
어떤 과학자가 발표한 논문의 인용 횟수를 담은 배열 citations가 매개변수로 주어질 때, 이 과학자의 H-Index를 return 하도록 solution 함수를 작성해주세요.

[85일차] 김리연 / H-Index

---

3st/Hyeonseo/programmer/피보나치 수.java

https://school.programmers.co.kr/learn/courses/30/lessons/12945
|  피보나치 수| 프로그래머스 | Level.2 |
<hr/>
- 피보나치 수 : 피보나치 수는 F(0) = 0, F(1) = 1일 때, 1 이상의 n에 대하여 F(n) = F(n-1) + F(n-2) 가 적용되는 수 입니다.
예를들어
F(2) = F(0) + F(1) = 0 + 1 = 1
F(3) = F(1) + F(2) = 1 + 1 = 2
F(4) = F(2) + F(3) = 1 + 2 = 3
F(5) = F(3) + F(4) = 2 + 3 = 5
와 같이 이어집니다.
2 이상의 n이 입력되었을 때, n번째 피보나치 수를 1234567으로 나눈 나머지를 리턴하는 함수, solution을 완성해 주세요.

[85일차] 조현서 / 피보나치 수

---

3st/Jaeyoung/오븐 시계.cs

https://www.acmicpc.net/problem/2525
| 오븐 시계 | 백준 | 브론즈 3 |
<hr/>
- 오븐 시 : KOI 전자에서는 건강에 좋고 맛있는 훈제오리구이 요리를 간편하게 만드는 인공지능 오븐을 개발하려고 한다. 인공지능 오븐을 사용하는 방법은 적당한 양의 오리 훈제 재료를 인공지능 오븐에 넣으면 된다. 그러면 인공지능 오븐은 오븐구이가 끝나는 시간을 분 단위로 자동적으로 계산한다.
또한, KOI 전자의 인공지능 오븐 앞면에는 사용자에게 훈제오리구이 요리가 끝나는 시각을 알려 주는 디지털 시계가 있다.
훈제오리구이를 시작하는 시각과 오븐구이를 하는 데 필요한 시간이 분단위로 주어졌을 때, 오븐구이가 끝나는 시각을 계산하는 프로그램을 작성하시오.

[86일차] 박재영 / 오븐 시계

---

2st/Riyeon/기능개발.java

| 기능개발 | 프로그래머스 | Level.2 |
<hr/>
- 기능개발 : 프로그래머스 팀에서는 기능 개선 작업을 수행 중입니다. 각 기능은 진도가 100%일 때 서비스에 반영할 수 있습니다. 
또, 각 기능의 개발속도는 모두 다르기 때문에 뒤에 있는 기능이 앞에 있는 기능보다 먼저 개발될 수 있고, 이때 뒤에 있는 기능은 앞에 있는 기능이 배포될 때 함께 배포됩니다.
먼저 배포되어야 하는 순서대로 작업의 진도가 적힌 정수 배열 progresses와 각 작업의 개발 속도가 적힌 정수 배열 speeds가 주어질 때 각 배포마다 몇 개의 기능이 배포되는지를 return 하도록 solution 함수를 완성하세요.

[86일차] 김리연 / 기능개발

---

2st/Yeonwoo/수열과 구간 쿼리 4.py

| 수열과 구간 쿼리 4 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181922) |
<hr/>
- 수열과 구간 쿼리 4 : 정수 배열 arr와 2차원 정수 배열 queries이 주어집니다. queries의 원소는 각각 하나의 query를 나타내며, [s, e, k] 꼴입니다.
각 query마다 순서대로 s ≤ i ≤ e인 모든 i에 대해 i가 k의 배수이면 arr[i]에 1을 더합니다.

[86일차] 채연우 / 수열과 구간 쿼리 4

---

3st/Juhee/피자 나눠 먹기 (2).java

https://school.programmers.co.kr/learn/courses/30/lessons/120815
| 피자 나눠 먹기 (2) | 프로그래머스 | Level.0 |
<hr/>
- 피자 나눠 먹기 (2) : 머쓱이네 피자가게는 피자를 여섯 조각으로 잘라 줍니다. 피자를 나눠먹을 사람의 수 n이 매개변수로 주어질 때, n명이 주문한 피자를 남기지 않고 모두 같은 수의 피자 조각을 먹어야 한다면 최소 몇 판을 시켜야 하는지를 return 하도록 solution 함수를 완성해보세요.

[86일차] 최주희 / 피자 나눠 먹기 (2)

---

3st/Hyeonseo/programmer/최대공약수와 최소공배수.java

https://school.programmers.co.kr/learn/courses/30/lessons/12940
| 최대공약수와 최소공배수 | 프로그래머스 | Level.1 |
<hr/>
- 최대공약수와 최대공배수 : 두 수를 입력받아 두 수의 최대공약수와 최소공배수를 반환하는 함수, solution을 완성해 보세요. 배열의 맨 앞에 최대공약수, 그다음 최소공배수를 넣어 반환하면 됩니다. 예를 들어 두 수 3, 12의 최대공약수는 3, 최소공배수는 12이므로 solution(3, 12)는 [3, 12]를 반환해야 합니다.

[86일차] 최대공약수와 최소공배수 / 조현서

---

3st/Juhee/순서쌍의 개수.java

https://school.programmers.co.kr/learn/courses/30/lessons/120836
<hr/>

[87일차] 최주희 / 순서쌍의 개수

---

2st/Riyeon/프로세스.java

| 프로세스 | 프로그래머스 | Level.2 |
<hr/>
- 프로세스 : 현재 실행 대기 큐(Queue)에 있는 프로세스의 중요도가 순서대로 담긴 배열 priorities와, 몇 번째로 실행되는지 알고싶은 프로세스의 위치를 알려주는 location이 매개변수로 주어질 때, 해당 프로세스가 몇 번째로 실행되는지 return 하도록 solution 함수를 작성해주세요.

[87일차] 김리연 / 프로세스

---

2st/Yeonwoo/왼쪽 오른쪽.py

| 왼쪽 오른쪽 | 프로그래머스 | [Level.0 ](https://school.programmers.co.kr/learn/courses/30/lessons/181890)|
<hr/>
- 왼쪽 오른쪽 : 문자열 리스트 str_list에는 "u", "d", "l", "r" 네 개의 문자열이 여러 개 저장되어 있습니다. str_list에서 "l"과 "r" 중 먼저 나오는 문자열이 "l"이라면 해당 문자열을 기준으로 왼쪽에 있는 문자열들을 순서대로 담은 리스트를, 먼저 나오는 문자열이 "r"이라면 해당 문자열을 기준으로 오른쪽에 있는 문자열들을 순서대로 담은 리스트를 return하도록 solution 함수를 완성해주세요. "l"이나 "r"이 없다면 빈 리스트를 return합니다.

[87일차] 채연우 / 왼쪽 오른쪽

---

2st/Riyeon/뒤에 있는 큰 수 찾기.java

| 뒤에 있는 큰 수 찾기 | 프로그래머스 | Level.2 |
<hr/>
- 뒤에 있는 큰 수 찾기 : 정수로 이루어진 배열 numbers가 있습니다. 배열 의 각 원소들에 대해 자신보다 뒤에 있는 숫자 중에서 자신보다 크면서 가장 가까이 있는 수를 뒷 큰수라고 합니다.
정수 배열 numbers가 매개변수로 주어질 때, 모든 원소에 대한 뒷 큰수들을 차례로 담은 배열을 return 하도록 solution 함수를 완성해주세요. 단, 뒷 큰수가 존재하지 않는 원소는 -1을 담습니다.

[88일차] 김리연 / 뒤에 있는 큰 수 찾기

---

3st/Juhee/분수의 덧셈.java

https://school.programmers.co.kr/learn/courses/30/lessons/120808
| 분수의 덧셈 | 프로그래머스 | Level.0 |
<hr/>
- 분수의 덧셈 : 첫 번째 분수의 분자와 분모를 뜻하는 numer1, denom1, 두 번째 분수의 분자와 분모를 뜻하는 numer2, denom2가 매개변수로 주어집니다. 두 분수를 더한 값을 기약 분수로 나타냈을 때 분자와 분모를 순서대로 담은 배열을 return 하도록 solution 함수를 완성해보세요.

[88일차] 최주희 / 분수의 덧셈

---

3st/Jaeyoung/시각.java
3st/Jaeyoung/주사위 세개.cs

https://www.acmicpc.net/problem/2480
| 주사위 세개 | 백준 | 브론즈 4 |
<hr/>
- 주사위 세개 : 1에서부터 6까지의 눈을 가진 3개의 주사위를 던져서 다음과 같은 규칙에 따라 상금을 받는 게임이 있다.
같은 눈이 3개가 나오면 10,000원+(같은 눈)×1,000원의 상금을 받게 된다.
같은 눈이 2개만 나오는 경우에는 1,000원+(같은 눈)×100원의 상금을 받게 된다.
모두 다른 눈이 나오는 경우에는 (그 중 가장 큰 눈)×100원의 상금을 받게 된다.
예를 들어, 3개의 눈 3, 3, 6이 주어지면 상금은 1,000+3×100으로 계산되어 1,300원을 받게 된다. 또 3개의 눈이 2, 2, 2로 주어지면 10,000+2×1,000 으로 계산되어 12,000원을 받게 된다. 3개의 눈이 6, 2, 5로 주어지면 그중 가장 큰 값이 6이므로 6×100으로 계산되어 600원을 상금으로 받게 된다.
3개 주사위의 나온 눈이 주어질 때, 상금을 계산하는 프로그램을 작성 하시오.

[88일차] 박재영 / 주사위 세개

---

2st/Yeonwoo/문자 개수 세기.py
2st/Yeonwoo/정사각형으로 만들기.py

| 문자 개수 세기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181902) |
<hr/>
- 문자 개수 세 : 알파벳 대소문자로만 이루어진 문자열 my_string이 주어질 때, my_string에서 'A'의 개수, my_string에서 'B'의 개수,..., my_string에서 'Z'의 개수, my_string에서 'a'의 개수, my_string에서 'b'의 개수,..., my_string에서 'z'의 개수를 순서대로 담은 길이 52의 정수 배열을 return 하는 solution 함수를 작성해 주세요.

[88일차] 채연우 / 문자 개수 세기

---

3st/Jaeyoung/랜덤 게임~~.py

https://www.acmicpc.net/problem/10944
| 랜덤 게임~~ | 백준 | X |
<hr/>
- 랜덤 게임~~ : 1부터 10,000까지 정수 중에서 하나를 출력한다. 이 수가 채점 프로그램이 랜덤으로 얻은 수와 같으면 이 문제를 맞힐 수 있다. 채점 프로그램은 채점을 할 때마다 랜덤을 수행한다.

[89일차] 박재영 / 랜덤 게임~~

---

3st/Juhee/외계행성의 나이.java

https://school.programmers.co.kr/learn/courses/30/lessons/120834
| 외계행성의 나이 | 프로그래머스 | Level.0 |
<hr/>
- 외계행성의 나이 : 우주여행을 하던 머쓱이는 엔진 고장으로 PROGRAMMERS-962 행성에 불시착하게 됐습니다. 입국심사에서 나이를 말해야 하는데, PROGRAMMERS-962 행성에서는 나이를 알파벳으로 말하고 있습니다. a는 0, b는 1, c는 2, ..., j는 9입니다. 예를 들어 23살은 cd, 51살은 fb로 표현합니다. 나이 age가 매개변수로 주어질 때 PROGRAMMER-962식 나이를 return하도록 solution 함수를 완성해주세요.

[89일차] 최주희 / 외계행성의 나이

---

2st/Riyeon/롤케이크 자르기.java

| 롤케이크 자르기 | 프로그래머스 | Level.2 |
<hr/>
- 롤케이크 자르기 : 철수는 롤케이크를 두 조각으로 잘라서 동생과 한 조각씩 나눠 먹으려고 합니다. 이 롤케이크에는 여러가지 토핑들이 일렬로 올려져 있습니다. 철수와 동생은 롤케이크를 공평하게 나눠먹으려 하는데, 그들은 롤케이크의 크기보다 롤케이크 위에 올려진 토핑들의 종류에 더 관심이 많습니다. 그래서 잘린 조각들의 크기와 올려진 토핑의 개수에 상관없이 각 조각에 동일한 가짓수의 토핑이 올라가면 공평하게 롤케이크가 나누어진 것으로 생각합니다. 롤케이크에 올려진 토핑들의 번호를 저장한 정수 배열 topping이 매개변수로 주어질 때, 롤케이크를 공평하게 자르는 방법의 수를 return 하도록 solution 함수를 완성해주세요.

[89일차] 김리연 / 롤케이크 자르기

---

3st/Jaeyoung/시각.java
3st/Jaeyoung/최댓값과 최솟값.cs

https://school.programmers.co.kr/learn/courses/30/lessons/12939
| 최댓값과 최솟값 | 프로그래머스 | Level.2 |
<hr/>
- 최댓값과 최솟값 : 문자열 s에는 공백으로 구분된 숫자들이 저장되어 있습니다. str에 나타나는 숫자 중 최소값과 최대값을 찾아 이를 "(최소값) (최대값)"형태의 문자열을 반환하는 함수, solution을 완성하세요.

[90일차] 박재영 / 최댓값과 최솟값

---

2st/Riyeon/전화번호 목록.java

| 전화번호 목록 | 프로그래머스 | Level.2 |
<hr/>
- 전화번호 목록 : 전화번호부에 적힌 전화번호 중, 한 번호가 다른 번호의 접두어인 경우가 있는지 확인하려 합니다. 전화번호가 다음과 같을 경우, 구조대 전화번호는 영석이의 전화번호의 접두사입니다.
구조대 : 119
박준영 : 97 674 223
지영석 : 11 9552 4421
전화번호부에 적힌 전화번호를 담은 배열 phone_book 이 solution 함수의 매개변수로 주어질 때, 어떤 번호가 다른 번호의 접두어인 경우가 있으면 false를 그렇지 않으면 true를 return 하도록 solution 함수를 작성해주세요.

[90일차] 김리연 / 전화번호 목록

---

3st/Juhee/외계행성의 나이.java
3st/Juhee/점의 위치 구하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/120841
<hr/>
x 좌표 (x, y)를 차례대로 담은 정수 배열 dot이 매개변수로 주어집니다. 좌표 dot이 사분면 중 어디에 속하는지 1, 2, 3, 4 중 하나를 return 하도록 solution 함수를 완성해주세요.

[90일차] 최주희 / 점의 위치 구하기

---

2st/Yeonwoo/정사각형으로 만들기_.py

| 정사각형으로 만들기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/181830) |
<hr/>
- 정사각형으로 만들기 : 이차원 정수 배열 arr이 매개변수로 주어집니다. arr의 행의 수가 더 많다면 열의 수가 행의 수와 같아지도록 각 행의 끝에 0을 추가하고, 열의 수가 더 많다면 행의 수가 열의 수와 같아지도록 각 열의 끝에 0을 추가한 이차원 배열을 return 하는 solution 함수를 작성해 주세요.

[90일차] 채연우 / 정사각형으로 만들기

---

3st/Hyeonseo/programmer/최댓값 만들기(1).java

https://school.programmers.co.kr/learn/courses/30/lessons/120847
|  최대값 만들기(1) | 프로그래머스 | Level.0 |
<hr/>

[PGS] 최댓값 만들기(1) / level 0

---

2st/Riyeon/캐시.java

| 캐시 | 프로그래머스 | Level.2 |
<hr/>
- 캐시 : 지도개발팀에서 근무하는 제이지는 지도에서 도시 이름을 검색하면 해당 도시와 관련된 맛집 게시물들을 데이터베이스에서 읽어 보여주는 서비스를 개발하고 있다.
이 프로그램의 테스팅 업무를 담당하고 있는 어피치는 서비스를 오픈하기 전 각 로직에 대한 성능 측정을 수행하였는데, 제이지가 작성한 부분 중 데이터베이스에서 게시물을 가져오는 부분의 실행시간이 너무 오래 걸린다는 것을 알게 되었다.
어피치는 제이지에게 해당 로직을 개선하라고 닦달하기 시작하였고, 제이지는 DB 캐시를 적용하여 성능 개선을 시도하고 있지만 캐시 크기를 얼마로 해야 효율적인지 몰라 난감한 상황이다.
어피치에게 시달리는 제이지를 도와, DB 캐시를 적용할 때 캐시 크기에 따른 실행시간 측정 프로그램을 작성하시오.

[91일차] 김리연 / 캐시

---

2st/Yeonwoo/가까운 수.py

| 가까운 수 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120890) |
<hr/>
- 가까운 수 : 정수 배열 array와 정수 n이 매개변수로 주어질 때, array에 들어있는 정수 중 n과 가장 가까운 수를 return 하도록 solution 함수를 완성해주세요.

[91일차] 채연우 / 가까운 수

---

3st/Jaeyoung/최솟값 만들기.cs

https://school.programmers.co.kr/learn/courses/30/lessons/12941
| 최솟값 만들기 | 프로그래머스 | Level.2 |
<hr/>
- 최솟값 만들기 : 길이가 같은 배열 A, B 두개가 있습니다. 각 배열은 자연수로 이루어져 있습니다.
배열 A, B에서 각각 한 개의 숫자를 뽑아 두 수를 곱합니다. 이러한 과정을 배열의 길이만큼 반복하며, 두 수를 곱한 값을 누적하여 더합니다. 이때 최종적으로 누적된 값이 최소가 되도록 만드는 것이 목표입니다. (단, 각 배열에서 k번째 숫자를 뽑았다면 다음에 k번째 숫자는 다시 뽑을 수 없습니다.)
예를 들어 A = [1, 4, 2] , B = [5, 4, 4] 라면
A에서 첫번째 숫자인 1, B에서 첫번째 숫자인 5를 뽑아 곱하여 더합니다. (누적된 값 : 0 + 5(1x5) = 5)
A에서 두번째 숫자인 4, B에서 세번째 숫자인 4를 뽑아 곱하여 더합니다. (누적된 값 : 5 + 16(4x4) = 21)
A에서 세번째 숫자인 2, B에서 두번째 숫자인 4를 뽑아 곱하여 더합니다. (누적된 값 : 21 + 8(2x4) = 29)
즉, 이 경우가 최소가 되므로 29를 return 합니다.
배열 A, B가 주어질 때 최종적으로 누적된 최솟값을 return 하는 solution 함수를 완성해 주세요.

[91일차] 박재영 / 최솟값 만들기

---

3st/Hyeonseo/programmer/배열의 평균값.java

https://school.programmers.co.kr/learn/courses/30/lessons/120817
| 배열의 평균값 | 프로그래머스 | Level.0 |
<hr/>
- 배열의 평균값 : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소의 평균값을 return하도록 solution 함수를 완성해주세요.

[91일차] 조현서 / 배열의 평균값

---

3st/Juhee/대문자와 소문자.java

https://school.programmers.co.kr/learn/courses/30/lessons/120893?language=java
<hr/>

[92일차] 최주희 / 대문자와 소문자

---

2st/Riyeon/튜플.java

| 튜플 | 프로그래머스 | Level.2 |
<hr/>
- 튜플 : 특정 튜플을 표현하는 집합이 담긴 문자열 s가 매개변수로 주어질 때, s가 표현하는 튜플을 배열에 담아 return 하도록 solution 함수를 완성해주세요.

[92일차] 김리연 / 튜플

---

2st/Yeonwoo/최빈값 구하기.py

| 최빈값 구하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120812) |
<hr/>

[92일차] 채연우 / 최빈값 구하기

---

3st/Jaeyoung/나머지 구하기.java
3st/Jaeyoung/두 수의 곱.java
3st/Jaeyoung/몫 구하기.java
3st/Jaeyoung/숫자 비교하기.java
3st/Jaeyoung/시각.java
3st/Jaeyoung/피보나치 수.java

https://school.programmers.co.kr/learn/courses/30/lessons/12945
| 피보나치 수 | 프로그래머스 | Level.2 |
| 두 수의 곱 | 프로그래머스 | Level.0 |
| 몫 구하기 | 프로그래머스 | Level.0 |
<hr/>
- 피보나치  : 피보나치 수는 F(0) = 0, F(1) = 1일 때, 1 이상의 n에 대하여 F(n) = F(n-1) + F(n-2) 가 적용되는 수 입니다.
예를들어
F(2) = F(0) + F(1) = 0 + 1 = 1
F(3) = F(1) + F(2) = 1 + 1 = 2
F(4) = F(2) + F(3) = 1 + 2 = 3
F(5) = F(3) + F(4) = 2 + 3 = 5
와 같이 이어집니다.
2 이상의 n이 입력되었을 때, n번째 피보나치 수를 1234567으로 나눈 나머지를 리턴하는 함수, solution을 완성해 주세요.
- 두 수의 곱 : 정수 num1, num2가 매개변수 주어집니다. num1과 num2를 곱한 값을 return 하도록 solution 함수를 완성해주세요.
- 몫 구하기 : 정수 num1, num2가 매개변수로 주어질 때, num1을 …

[92일차] 박재영 / 피보나치 수 외 4개

---

3st/Hyeonseo/programmer/두 정수 사의 합.java

https://school.programmers.co.kr/learn/courses/30/lessons/12912
| 두 정수 사이의 합 | 프로그래머스 | Level.1 |
<hr/>
- 두 정수 사이의  합: 두 정수 a, b가 주어졌을 때 a와 b 사이에 속한 모든 정수의 합을 리턴하는 함수, solution을 완성하세요.
예를 들어 a = 3, b = 5인 경우, 3 + 4 + 5 = 12이므로 12를 리턴합니다.

[92일차] 조현서 / 두 정수 사이의 합

---

3st/Juhee/짝수는 싫어요.java

https://school.programmers.co.kr/learn/courses/30/lessons/120833?language=java
<hr/>

[93일차] 최주희 / 배열 자르기

---

2st/Riyeon/짝수와 홀수.py

| 짝수와 홀수 | 프로그래머스 | Level.1 |
<hr/>
- 짝수와 홀수 : 정수 num이 짝수일 경우 "Even"을 반환하고 홀수인 경우 "Odd"를 반환하는 함수, solution을 완성해주세요.

[93일차] 김리연 / 짝수와 홀수

---

3st/Jaeyoung/flag에 따라 다른 값 반환하기.js
3st/Jaeyoung/약수 구하기.js
3st/Jaeyoung/약수의 개수와 덧셈.js
3st/Jaeyoung/약수의 합.js

https://school.programmers.co.kr/learn/courses/30/lessons/77884
| 약수의 개수와 덧셈 | 프로그래머스 | Level.1 |
| 약수의 합 | 프로그래머스 | Level.1 |
| flag에 따른 다른 값 반환하기 | 프로그래머스 | Level.0 |
<hr/>
- 약수의 개수와 덧셈 : 두 정수 left와 right가 매개변수로 주어집니다. left부터 right까지의 모든 수들 중에서, 약수의 개수가 짝수인 수는 더하고, 약수의 개수가 홀수인 수는 뺀 수를 return 하도록 solution 함수를 완성해주세요.
- 약수의 합 : 정수 n을 입력받아 n의 약수를 모두 더한 값을 리턴하는 함수, solution을 완성해주세요.
- flag에 따른 다른 값 반환하기 : 두 정수 a, b와 boolean 변수 flag가 매개변수로 주어질 때, flag가 true면 a + b를 false면 a - b를 return 하는 solution 함수를 작성해 주세요.

[92일차] 박재영 / 약수의 개수와 덧셈 외 3개

---

2st/Yeonwoo/최솟값 만들기.py

| 최솟값 만들기 | 프로그래머스 | [Level.2](https://school.programmers.co.kr/learn/courses/30/lessons/12941) |
<hr/>
- 최솟값 만들기 : 길이가 같은 배열 A, B 두개가 있습니다. 각 배열은 자연수로 이루어져 있습니다.
배열 A, B에서 각각 한 개의 숫자를 뽑아 두 수를 곱합니다. 이러한 과정을 배열의 길이만큼 반복하며, 두 수를 곱한 값을 누적하여 더합니다. 이때 최종적으로 누적된 값이 최소가 되도록 만드는 것이 목표입니다. (단, 각 배열에서 k번째 숫자를 뽑았다면 다음에 k번째 숫자는 다시 뽑을 수 없습니다.)
예를 들어 A = [1, 4, 2] , B = [5, 4, 4] 라면
A에서 첫번째 숫자인 1, B에서 첫번째 숫자인 5를 뽑아 곱하여 더합니다. (누적된 값 : 0 + 5(1x5) = 5)
A에서 두번째 숫자인 4, B에서 세번째 숫자인 4를 뽑아 곱하여 더합니다. (누적된 값 : 5 + 16(4x4) = 21)
A에서 세번째 숫자인 2, B에서 두번째 숫자인 4를 뽑아 곱하여 더합니다. (누적된 값 : 21 + 8(2x4) = 29)
즉, 이 경우가 최소가 되므로 29를 return 합니다.
배열 A, B가 주어질 때 최종적으로 누적된 최솟값을 return 하는 solution 함수를 완성해 주세요.

[93일차] 채연우 / 최솟값 만들기

---

3st/Hyeonseo/programmer/숫자 비교하기.java

https://school.programmers.co.kr/learn/courses/30/lessons/120807
<hr/>

[93일차] 조현서 / 숫자 비교하기

---

2st/Riyeon/약수의 합.py

| 약수의 합 | 프로그래머스 | Level.1 |
<hr/>
- 약수의 합 : 정수 n을 입력받아 n의 약수를 모두 더한 값을 리턴하는 함수, solution을 완성해주세요.

[94일차] 김리연 / 약수의 합

---

2st/Yeonwoo/최대공약수와 최소공배수.py

| 최대공약수와 최소공배수 | 프로그래머스 | [Level.1 ](https://school.programmers.co.kr/learn/courses/30/lessons/12940)|
<hr/>
- 최대공약수와 최소공배수 : 두 수를 입력받아 두 수의 최대공약수와 최소공배수를 반환하는 함수, solution을 완성해 보세요. 배열의 맨 앞에 최대공약수, 그다음 최소공배수를 넣어 반환하면 됩니다. 예를 들어 두 수 3, 12의 최대공약수는 3, 최소공배수는 12이므로 solution(3, 12)는 [3, 12]를 반환해야 합니다.

[94일차] 채연우 / 최대공약수와 최소공배수

---

3st/Juhee/배열 자르기.java
3st/Juhee/삼각형의 완성조건 (2).java

https://school.programmers.co.kr/learn/courses/30/lessons/120868?language=java
| 삼각형의 완성조건 (2) | 프로그래머스 | Level.0 |
<hr/>
- 삼각형의 완성조건 (2) : 선분 세 개로 삼각형을 만들기 위해서는 다음과 같은 조건을 만족해야 합니다.
가장 긴 변의 길이는 다른 두 변의 길이의 합보다 작아야 합니다.
삼각형의 두 변의 길이가 담긴 배열 sides이 매개변수로 주어집니다. 나머지 한 변이 될 수 있는 정수의 개수를 return하도록 solution 함수를 완성해주세요.

[95일차] 최주희 / 삼각형의 완성조건 (2)

---

2st/Yeonwoo/직사각형 넓이 구하기.py

| 직사각형 넓이 구하기 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120860) |
<hr/>
- 직사각형 넓이 구하 : 2차원 좌표 평면에 변이 축과 평행한 직사각형이 있습니다. 직사각형 네 꼭짓점의 좌표 [[x1, y1], [x2, y2], [x3, y3], [x4, y4]]가 담겨있는 배열 dots가 매개변수로 주어질 때, 직사각형의 넓이를 return 하도록 solution 함수를 완성해보세요.

[95일차] 채연우 / 직사각형 넓이 구하기

---

2st/Riyeon/x만큼 간격이 있는 n개의 숫자.py

| x만큼 간격이 있는 n개의 숫자 | 프로그래머스 | Level.1 |
<hr/>
- x만큼 간격이 있는 n개의 숫자 : 함수 solution은 정수 x와 자연수 n을 입력 받아, x부터 시작해 x씩 증가하는 숫자를 n개 지니는 리스트를 리턴해야 합니다. 다음 제한 조건을 보고, 조건을 만족하는 함수, solution을 완성해주세요.

[95일차] 김리연 / x만큼 간격이 있는 n개의 숫자

---

3st/Jaeyoung/배열 두 배 만들기.js
3st/Jaeyoung/중복된 숫자 개수.java
3st/Jaeyoung/피자 나눠먹기.java

| 피자 나눠 먹기 | 프로그래머스 | Level.0 |
| 배열 두 배 만들기 | 프로그래머스 | Level.0 |
<hr/>
- 피자 나눠 먹기 : 머쓱이네 피자가게는 피자를 일곱 조각으로 잘라 줍니다. 피자를 나눠먹을 사람의 수 n이 주어질 때, 모든 사람이 피자를 한 조각 이상 먹기 위해 필요한 피자의 수를 return 하는 solution 함수를 완성해보세요.
- 배열 두 배 만들기 : 정수 배열 numbers가 매개변수로 주어집니다. numbers의 각 원소에 두배한 원소를 가진 배열을 return하도록 solution 함수를 완성해주세요.

[1일차] 박재영 / 피자 나눠 먹기 외 2개

---

2st/Yeonwoo/캐릭터의 좌표.py

| 캐릭터의 좌표 | 프로그래머스 | [Level.0](https://school.programmers.co.kr/learn/courses/30/lessons/120861) |
<hr/>
- 캐릭터의 좌표 : 머쓱이는 RPG게임을 하고 있습니다. 게임에는 up, down, left, right 방향키가 있으며 각 키를 누르면 위, 아래, 왼쪽, 오른쪽으로 한 칸씩 이동합니다. 예를 들어 [0,0]에서 up을 누른다면 캐릭터의 좌표는 [0, 1], down을 누른다면 [0, -1], left를 누른다면 [-1, 0], right를 누른다면 [1, 0]입니다. 머쓱이가 입력한 방향키의 배열 keyinput와 맵의 크기 board이 매개변수로 주어집니다. 캐릭터는 항상 [0,0]에서 시작할 때 키 입력이 모두 끝난 뒤에 캐릭터의 좌표 [x, y]를 return하도록 solution 함수를 완성해주세요.

[96일차] 채연우 / 캐릭터의 좌표

---

3st/Juhee/문자열 겹쳐쓰기.java

https://school.programmers.co.kr/learn/courses/30/lessons/181943
| 문자열 겹쳐쓰기 | 프로그래머스 | Level.0 |
<hr/>
- 문자열 겹쳐쓰기 : 문자열 my_string, overwrite_string과 정수 s가 주어집니다. 문자열 my_string의 인덱스 s부터 overwrite_string의 길이만큼을 문자열 overwrite_string으로 바꾼 문자열을 return 하는 solution 함수를 작성해 주세요.

[1일차] 최주희 / 문자열 겹쳐쓰기

---

3st/Jaehee/두 수의 합.java

https://school.programmers.co.kr/learn/courses/30/lessons/120802
| 두 수의 합| 프로그래머스 |  Level.0 |
<hr/>
- 두 수의 합 : 정수 num1과 num2가 주어질 때, num1과 num2의 합을 return하도록 soltuion 함수를 완성해주세요.

[1일차] 이제희/ 두 수의 합 / Lv.0
